### ISSUE TITLE
Error occurs in CreateChromatinAssay when using cellranger-atac 2.0.0 output files

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [timoast/signac#1004]
Thanks for providing a good R package for processing scATAC-seq data, and I am new to the filed of scATAC-seq( or Signac).
I follow the code presented in Signc Vignettes using cellranger 2.0.0 output files, but a error occurs in CreateChromatinAssay function. The following is the code I run:

library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)
library(ggplot2)
library(patchwork)
library("hdf5r")
set.seed(1234)

counts <- Read10X_h5(filename = "filtered_peak_bc_matrix.h5")
metadata <- read.csv(file = "singlecell.csv", header = TRUE, row.names = 1)

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(";", "-"),
  genome = "GRCh38",
  fragments = "fragments.tsv.gz",
  min.cells = 10,
  min.features = 200
)

The error messager is `Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]) : 
  some values in the "end" column cannot be turned into numeric values
In addition: Warning message:
Expected 3 pieces. Missing pieces filled with `NA` in 42891 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].`

R version: 4.1.1
cellranger-atac version: 2.0.0
Signac version: latest

I expect a update in Signc to read the output files generated by cellranger-atac 2.0.0 correctly.

**Comment by timoast** [comment]
You have a typo: `sep = c(";", "-")` should be `sep = c(":", "-")` if this is cellranger data.

**Comment by 0106WeiWeiDeng** [comment]
oh, it is my falut! Thanks for your correction.
