### ISSUE TITLE
How to add my genome data in `CreateChromatinAssay()` ?

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1005]
I use `registered_NCBI_assemblies()` and `registered_UCSC_genomes()` , but I found my species did not have a registered NCBI assembly or UCSC genome. So how to add it to `CreateChromatinAssay()` ?

`CreateChromatinAssay()`  `genome=` needs 'A [Seqinfo] object containing basic information about the genome used'. 
So, how do I generate this seqinfo object with my species being not listed in NCBI or UCSC ?

**Comment by timoast** [comment]
`genome` is not a required argument, so you can leave it out and move forward.

If you want to create one you can forge a custom BSgenome and extract the seqinfo from that: https://bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf

**Comment by jiangpuxuan** [comment]
> `genome` is not a required argument, so you can leave it out and move forward.
> 
> If you want to create one you can forge a custom BSgenome and extract the seqinfo from that: https://bioconductor.org/packages/devel/bioc/vignettes/BSgenome/inst/doc/BSgenomeForge.pdf

Thank you for your help!
Actually I had a Bsgenome for my animal model when using ArchR.
Could I use the Bsgenome in Signac?

**Comment by timoast** [comment]
Sure, you can extract the seqinfo from it using the `seqinfo()` function
