### ISSUE TITLE
Error: Cannot use BSgenome in GetGRangesFromEnsDb()

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1006]
I use `annotations <- GetGRangesFromEnsDb(ensdb = BSgenome.medaka.UCSC.ens94)`, but it did not work. However, it had worked well with ArchR  pipeline.
Error code:
`Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'crunch' for signature '"BSgenome"'`

I also tried `BSgenome.Hsapiens.UCSC.hg19` but it got the same error.
Here is my Bsgenome:
```r
Medaka genome:
# organism: Medaka (Medaka)
# genome: UCSC
# provider: jiangpuxuan
# release date: May. 2019
# 1014 sequences:
#   MT         ERCC-00171 ERCC-00170 ERCC-00168 ERCC-00165 ERCC-00164 ERCC-00163 ERCC-00162 ERCC-00160 ERCC-00158
#   ERCC-00157 ERCC-00156 ERCC-00154 ERCC-00150 ERCC-00148 ERCC-00147 ERCC-00145 ERCC-00144 ERCC-00143 ERCC-00142
#   ERCC-00138 ERCC-00137 ERCC-00136 ERCC-00134 ERCC-00131 ERCC-00130 ERCC-00126 ERCC-00123 ERCC-00120 ERCC-00117
#   ERCC-00116 ERCC-00113 ERCC-00112 ERCC-00111 ERCC-00109 ERCC-00108 ERCC-00104 ERCC-00099 ERCC-00098 ERCC-00097
#   ERCC-00096 ERCC-00095 ERCC-00092 ERCC-00086 ERCC-00085 ERCC-00084 ERCC-00083 ERCC-00081 ERCC-00079 ERCC-00078
#   ...        ...        ...        ...        ...        ...        ...        ...        ...        ...       
#   000087F    000086F    000085F    000084F    000076F    000074F    000071F    000069F    000066F    000062F   
#   000058F    000056F    000047F    000044F    000043F    000039F    000029F    24         23         22        
#   21         20         19         18         17         16         15         14         13         12        
#   11         10         9          8          7          000007F    6          000006F    5          4         
#   3          000003F    2          1                                                                           
# (use 'seqnames()' to see all the sequence names, use the '$' or '[[' operator to access a given sequence)
```

**Comment by timoast** [comment]
The `GetGRangesFromEnsDb()` function requires an EnsDb object, not a BSgenome object. See the documentation here: https://satijalab.org/signac/reference/getgrangesfromensdb

**Comment by jiangpuxuan** [comment]
> The `GetGRangesFromEnsDb()` function requires an EnsDb object, not a BSgenome object. See the documentation here: https://satijalab.org/signac/reference/getgrangesfromensdb
Thank you for your help! So could I generate an EnsDb from my `.fa` file?

**Comment by timoast** [comment]
> So could I generate an EnsDb from my .fa file?

You will need a gtf or gff fine containing the gene annotations for your organism. See https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-

**Comment by jiangpuxuan** [comment]
> > So could I generate an EnsDb from my .fa file?
> 
> You will need a gtf or gff fine containing the gene annotations for your organism. See https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-

Thank you for your help!

**Comment by jiangpuxuan** [comment]
> 

Thank you for your help ! I think that would work.
