### ISSUE TITLE
Signac develop version display error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#101]
Please search the previous issues for similar questions before opening a new issue. If there are similar previous issues, please reference them in your issue (https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls)

If your question is related to Seurat functionality, please post an issue on the Seurat repository instead: https://github.com/satijalab/seurat/issues

Please clearly explain your question and include all relevant code. Please ensure that code is formatted correctly: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

Please delete this instructional text before creating the issue
Hi @timoast
   The develop version you release last one day  run error like below:
   Error in SetFragments(obj, file = fragment.path) : 
  lazy-load database '/share/nas2/public/R/library/3.6/Signac/R/Signac.rdb' is corrupt 
 should any tip or advices for this ?

**Comment by timoast** [comment]
Try reinstalling Signac and restart R.

By the way, the text that appears when you create a new issue is meant to be read and then deleted before posting the issue:
>Please delete this instructional text before creating the issue

**Comment by honghh2018** [comment]
It is grateful for your reply.
 The issue had solved.
Thanks.
