### ISSUE TITLE
scATAC seq integration

### ISSUE THREAD

**Issue by cnwokolo2** [timoast/signac#1010]
Hi, 
I am trying to integrate two scATAC seq dataset in RStudio but it terminates R at the point of either merging the datasets or integration. Any advice on how to overcome this.
Here is a snippet of the point of error:
<img width="903" alt="Screen Shot 2022-03-01 at 12 19 48 PM" src="https://user-images.githubusercontent.com/70290049/156226486-c7a53190-0356-4d8b-a269-4f4e466513f7.png">

Here is my script:
#Integration using a combination of joint RNA & ATAC analysis and scATAC seq data integration vignettes
library(dplyr)
library(Seurat)
library(cowplot)
library(ggplot2)
library(metap)
library(tidyverse)
library("broom")
library(ggrepel)
library(dittoSeq)
library(ggpubr)
library(rstatix)
library('magrittr')
library(Signac)
library(EnsDb.Mmusculus.v79)

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)
# change to UCSC style siNCe the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'

counts1 <- Read10X("/Users/lindseykuehm/Desktop/Diet_data/NC_data")
metadataNC <- read.csv(file = "/Users/lindseykuehm/Desktop/Diet_data/NC_data/NCMetadata.csv", header = TRUE, row.names = 1)
fragment1 = "/Users/lindseykuehm/Desktop/Diet_data/NC_data/atac_fragments.tsv.gz"
NC <- CreateSeuratObject(counts = counts1$`Gene Expression`, assay = "RNA")
NC[["ATAC"]] <- CreateChromatinAssay(counts = counts1$Peaks, sep = c(":", "-"),fragments = fragment1, annotation = annotations)
NC$KO <- "NC"
NC$Condition <- "Untrt"
NC$Diet <- "NC"

counts2 <- Read10X("/Users/lindseykuehm/Desktop/Diet_data/WD_data/")
metadataWD <- read.csv(file = "/Users/lindseykuehm/Desktop/Diet_data/WD_data/WDMetadata.csv", header = TRUE, row.names = 1)
fragment2 = "/Users/lindseykuehm/Desktop/Diet_data/WD_data/atac_fragments.tsv.gz"
WD <- CreateSeuratObject(counts = counts2$`Gene Expression`, assay = "RNA")
WD[["ATAC"]] <- CreateChromatinAssay(counts = counts2$Peaks, sep = c(":", "-"),fragments = fragment2, annotation = annotations)
WD$KO <- "WD"
WD$Condition <- "Untrt"
WD$Diet <- "WD"

DefaultAssay(NC) <- "ATAC"
DefaultAssay(WD) <- "ATAC"
NC <- NucleosomeSignal(NC)
WD <- NucleosomeSignal(WD)
NC <- TSSEnrichment(NC)
WD <- TSSEnrichment(WD)

VlnPlot(object = NC, features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),ncol = 4, pt.size = 0)
VlnPlot(object = WD, features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),ncol = 4, pt.size = 0)

# filter out low quality cells
NC <- subset(x = NC, subset = nCount_ATAC < 75000 & nCount_RNA < 7000 & nCount_ATAC > 500 & nCount_RNA > 100 &
               nucleosome_signal < 1.2 & TSS.enrichment > 1)
NC
WD <- subset(x = WD, subset = nCount_ATAC < 70000 & nCount_RNA < 7500 & nCount_ATAC > 500 & nCount_RNA > 10 &
               nucleosome_signal < 1.2 & TSS.enrichment > 1)
WD

# call peaks using MACS2
peaks1 <- CallPeaks(NC, macs2.path = "/Users/lindseykuehm/opt/miniconda3/bin/macs2", effective.genome.size = 2.6e9)
peaks2 <- CallPeaks(WD, macs2.path = "/Users/lindseykuehm/opt/miniconda3/bin/macs2", effective.genome.size = 2.6e9)

# remove peaks on nonstandard chromosomes and in genomic blacklist regions
peaks1 <- keepStandardChromosomes(peaks1, pruning.mode = "coarse")
peaks1 <- subsetByOverlaps(x = peaks1, ranges = blacklist_hg38_unified, invert = TRUE)
peaks2 <- keepStandardChromosomes(peaks2, pruning.mode = "coarse")
peaks2 <- subsetByOverlaps(x = peaks2, ranges = blacklist_hg38_unified, invert = TRUE)

# quantify counts in each peak
macs2_counts1 <- FeatureMatrix(fragments = Fragments(NC), features = peaks1, cells = colnames(NC))
macs2_counts2 <- FeatureMatrix(fragments = Fragments(WD), features = peaks2, cells = colnames(WD))

# create a new assay using the MACS2 peak set and add it to the Seurat object
NC[["peaks"]] <- CreateChromatinAssay(counts = macs2_counts1, fragments = fragment1,
                                      annotation = annotations)
WD[["peaks"]] <- CreateChromatinAssay(counts = macs2_counts2, fragments = fragment2,
                                      annotation = annotations)

DefaultAssay(NC) <- "RNA"
DefaultAssay(WD) <- "RNA"
NC <- SCTransform(NC, verbose = FALSE)
NC <- RunPCA(NC)
WD <- SCTransform(WD, verbose = FALSE)
WD <- RunPCA(WD)

DefaultAssay(NC) <- "peaks"
NC <- FindTopFeatures(NC, min.cutoff = 5)
NC <- RunTFIDF(NC)
NC <- RunSVD(NC)

DefaultAssay(WD) <- "peaks"
WD <- FindTopFeatures(WD, min.cutoff = 5)
WD <- RunTFIDF(WD)
WD <- RunSVD(WD)

saveRDS(NC, file="/Users/lindseykuehm/Desktop/Diet_data/ATAC_Integration/processedNC.rds") 
saveRDS(WD, file="/Users/lindseykuehm/Desktop/Diet_data/ATAC_Integration/processedWD.rds") 
options(future.globals.maxSize= 2000 * 1024^5) 
# merge
diet.combined <- merge(NC, WD)

# process the combined dataset
diet.combined <- FindTopFeatures(diet.combined, min.cutoff = 5)
diet.combined <- RunTFIDF(diet.combined)
diet.combined <- RunSVD(diet.combined)
diet.combined <- RunUMAP(diet.combined, reduction = "lsi", dims = 2:20)
p1 <- DimPlot(diet.combined, group.by = "KO")

**Comment by timoast** [comment]
I would recommend following the [merge vignette](https://satijalab.org/signac/articles/merging.html). The key point is that you need to quantify the same features across all of the objects you want to merge before merging them. You can also remove unused assays by assigning `NULL`, eg `object[['peaks']] <- NULL`

**Comment by cnwokolo2** [comment]
Thank you for your response. My goal is to integrate the datasets. I only used merge first to allow for comparison between merged and integrated data. I still encounter the same problem at the point of integration without merging.
Here is the integration part:
diet.list <- list(NC, WD)

options(future.globals.maxSize= 2000 * 1024^7) 

diet.features <- SelectIntegrationFeatures(object.list = diet.list, nfeatures = 3000)

diet.list <- PrepSCTIntegration(object.list = diet.list, anchor.features = diet.features, 
                                verbose = FALSE)
diet.anchors <- FindIntegrationAnchors(object.list = diet.list, normalization.method = "SCT", 
                                       anchor.features = diet.features, verbose = FALSE)
saveRDS(diet.anchors, file="diet.anchors.rds") 

diet.combined <- IntegrateData(anchorset = diet.anchors, normalization.method = "SCT", 
                               verbose = FALSE)
genome(diet.combined[['peaks']]) = 'GRCm38'

**Comment by timoast** [comment]
The code above is what you would run when integrating scRNA-seq datasets, and cannot be used for scATAC-seq integration. Please see the integration and dataset merging vignettes on the Signac website for guidance on how to integrate or merge scATAC-seq datasets.
