### ISSUE TITLE
Error: Cannot generate annotations by keepStandardChromosomes().

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1013]
I am working with an organism that does not have a BSgenome genome package or EnsDB annotation package available on BioConductor, so I refered to [https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-](https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-)

```r
#To use a GTF file, you can import it using rtracklayer, for example:
gtf <- rtracklayer::import('genes.gtf')
gene.coords <- gtf[gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'UCSC'
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
```
Here is my problem with this code: 
We get a GRanges object `gene.coords` as annotation. However, compared with the annotation generated by `annotations <- GetGRangesFromEnsDb(ensdb = xxxx)`, `gene.coords`  did not have `seqinfo` and many other data.
Here is my code:
```r
gtf <- rtracklayer::import('Mus_musculus.GRCm38.95.gtf')
gene.coords <- gtf[gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'UCSC'
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
```

**Comment by timoast** [comment]
Your species must be supported in the `genomeStyles()` function if you want to run `keepStandardChromosomes()`, see the documentation here: https://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/GenomeInfoDb/html/seqlevels-wrappers.html

Running `keepStandardChromosomes()` is not essential, and will just remove some unneeded genomic ranges. You can skip this step.
