### ISSUE TITLE
Peak calling MACS2

### ISSUE THREAD

**Issue by andrewjiabuling** [timoast/signac#1014]
I've tried to install the MACS2. However, when the installation of MACS2 by anaconda is done, I put the route after the "peaks <- CallPeaks(pbmc, macs2.path =". Then the result is 'ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Warning in file(file, "rt") :
  cannot open file '/var/folders/b9/t9vv27056mzb43_lgsk16qjw0000gn/T//RtmpvbwmGp/SeuratProject_peaks.narrowPeak': No such file or directory
Error in file(file, "rt") : cannot open the connection"
I want to know which procedure I did may wrong.

**Comment by timoast** [comment]
Does macs2 work for you outside of using Signac? This may be a more general issue with your macs2 installation

**Comment by JBreunig** [comment]
I had the identical problem over the past week.  I uninstalled macs2 "pip uninstall macs2", upgraded numpy "pip install -U numpy", and reinstalled macs2 "pip install -U  macs2.  That fixed it.

akin to this https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by timoast** [comment]
@andrewjiabuling I think this is an issue with your MACS2 installation rather than Signac, see the comment above
