### ISSUE TITLE
The Analysis question about multiple sample on ATAC

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#102]
Hi @timoast ,
     Thanks for developping the great tool for ATAC data analysis.
      I have a little biological problem about ATAC data analysis showing below:
      The ATAC data was generated by cutting DNA open zone through Tn enzyme, Did it means that 
      the cellrange-atac matrix's peak, rownames of matrix or H5 file generated by cellrange-atac 
      pipeline, represent counts of this peaks? whether or not the significant differential peaks using 
      FindMarker function to test was considered a significantly the most openning accessiable peak 
      between treatment and contral.
      In my project, four mouse testis samples made  replicate two of them with fat treatment, high 
      caloric diet，and the contral group with normal diet. It named after fat1,fat2 and health1,health2. The result i hope to discover different change of mouse testis about reproductive. 
     on the above basis,  I using FindMarker function to test the differential expression between treatment and contral, the code showing below. is that right for my analysis to query the openning 
accessible between treatment and contral using FindMarker function below.
```r
      ######the combined data owned eighteen clusters
      for(i in 0:17){
         atac1 <- FindMarkers(
        object = atac,
        subset.ident = i,
        group.by = 'orig.ident',
        ident.1 = 'fat',
        ident.2 = 'health'
        )
        atac_cluster<-subset(atac1,p_val_adj <0.05)
   }
```

In this case,  it is tremendously confusing me that why the most significantly differential expression peaks between treatment and contral having no different on the plot using CoveragePlot setting up the parameter,group.by = 'groups_of_treatment_and_contral'.
     I wonder that though, as we all know, the matrix had presented the counts of peak, like H5 file and filtered_peak_bc_matrix directory, it  also provide the fragment file as well. and the most fatal, the function  CoveragePlot need the fragment but matrix count to plot.
     what different about fragment and matrix file generated by cellrage-atac, why plot CoveragePlot using fragment file, and what different between matrix count and fragment file, is that same files into different type. 
      By the way, I not only perform the ATAC data but also achived single cell RNA-seq. Logically, 
      The data shloud be fit each other, nevertheless, in this case, the scRNA-seq differential expression showing Star genes downregulation on fat compared with health on cluster11, but showing contrary on ATAC differential test.
       was that  coincidence or the data i analyze wrong ?
       Any advice and comment would be grateful.

**Comment by timoast** [comment]
> Did it means that
the cellrange-atac matrix's peak, rownames of matrix or H5 file generated by cellrange-atac
pipeline, represent counts of this peaks?

Yes

> what different about fragment and matrix file generated by cellrage-atac

The matrix contains fragment counts within each peak for each cell, the fragment file contains all fragments sequenced (including those not inside peaks)

> scRNA-seq differential expression showing Star genes downregulation on fat compared with health on cluster11, but showing contrary on ATAC differential test.

Cluster 11 in the scRNA-seq data will not necessarily correspond to the same type of cells in cluster 11 in the scATAC-seq data

In the code that you've shown, you overwrite the FindMarkers results at each iteration of the loop. See the Seurat [immune alignment](https://satijalab.org/seurat/v3.1/immune_alignment.html) vignette for more information about comparing across treatment and control groups.

**Comment by honghh2018** [comment]
The advices made me lots of help.
 But the problem about CoveragePlot still make me perplexed. 
  what mean about the ATAC differential expression test? 
   For instance, like peak ,chr1:879870-879992, if peak 'chr1:879870-879992' within treatment group significantly upregulation  expression compared with control group, could it be said that the peak, chr1:879870-879992,  was more openning in treatment than control ?.

**Comment by honghh2018** [comment]
Hi @timoast, 
    The hand-down question above this morning, had a little detail to modify demenstrated below:
    Since the cluster 11 significantly up-regulation gene, Star, between treatment and control on ScRNA-seq finished, then, as I run FindTransferAnchor function to tranfer the label generated by ScRNA-seq into ATAC data and predicted the cell cluster ID.
    Since the step  FindTransferAnchor run over, i finally get the same cluster 11 within ATAC data. So, i run FindMarker to test this cluster between treatment and control showing the contrary result of gene 'Star', significant download-regulation.

**Comment by timoast** [comment]
> For instance, like peak ,chr1:879870-879992, if peak 'chr1:879870-879992' within treatment group significantly upregulation expression compared with control group, could it be said that the peak, chr1:879870-879992, was more openning in treatment than control ?.

Yes, that's what it means.

> Since the cluster 11 significantly up-regulation gene, Star, between treatment and control on ScRNA-seq finished, then, as I run FindTransferAnchor function to tranfer the label generated by ScRNA-seq into ATAC data and predicted the cell cluster ID.
Since the step FindTransferAnchor run over, i finally get the same cluster 11 within ATAC data. So, i run FindMarker to test this cluster between treatment and control showing the contrary result of gene 'Star', significant download-regulation.

Since you're measuring different data modalities (gene expression and chromatin accessibility), it's expected that there will be differences. It's unclear here what you mean by significant downregulation of the gene in scATAC-seq.

**Comment by honghh2018** [comment]
> Since you're measuring different data modalities (gene expression and chromatin accessibility), it's expected that there will be differences. It's unclear here what you mean by significant downregulation of the gene in scATAC-seq.
Thanks for the urgen reply.
 The significantly down-regulation gene, Star, was activated by function FeatureMatrix, as it running over, i practiced the differential expression using activated slots RNA generated by FeatureMatrix.
   After differential expression result come out, I found the genes within ATAC down-regulation between treatment and control in cluster 11 predicted with fucntion FindTransferAnchor but contrary in same gene with cluster11 within ScRNA data.
    Why was result so incomformity between scRNA and ATAC activated matric ?
 Thanks

**Comment by timoast** [comment]
I think what you're saying is you created a gene activity matrix from the scATAC-seq data and found the gene activity for the Star gene was lower between treatment and control, whereas the gene expression for the matched cluster in the scRNA-seq data was higher between treatment and control?

All I can say is that there is not a perfect correlation between chromatin accessibility in the gene body and promoter and the expression of the gene.
