### ISSUE TITLE
`FragmentHistogram(object = pbmc, group.by = 'nucleosome_group')` consume too much  RAM

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1020]
Here is my seurat object.

```r
An object of class Seurat 
71182 features across 16542 samples within 1 assay 
Active assay: peaks (71182 features, 0 variable features)
ChromatinAssay data with 71182 features for 16542 cells
Variable features: 0 
Genome: ASM223467v1 
Annotation present: TRUE 
Motifs present: FALSE 
Fragment files: 1 
GRanges object with 71182 ranges and 0 metadata columns:
          seqnames            ranges strand
             <Rle>         <IRanges>  <Rle>
      [1]        1       89382-92840      *
      [2]        1       93360-94145      *
      [3]        1     109281-109729      *
      [4]        1     117848-121373      *
      [5]        1     128795-128996      *
      ...      ...               ...    ...
  [71178]       24 23505561-23507146      *
  [71179]       24 23555490-23556484      *
  [71180]       24 23559503-23560657      *
  [71181]       24 23595393-23595446      *
  [71182]       24 23600390-23600870      *
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
```
When run `FragmentHistogram(object = pbmc, group.by = 'nucleosome_group')`, it consumed over 80G RAM.
It was quite strange because this code only aims to draw a plot.
Thank you for your help!

**Comment by timoast** [comment]
I wasn't able to reproduce this issue. Running `FragmentHistogram()` on a dataset with 21688 cells used 400 Mb RAM for me (profiled using profvis).

**Comment by cmf1997** [comment]
it's strange to me as well, i was using mm39 as reference and annotation for genome and gene,
it take me too long when i trying to run FragmentHistogram() FUNCTION with 7666cells
i wonder if you solve the issue? @jiangpuxuan 
very thanks for any infomation

**Comment by jiangpuxuan** [comment]
> it's strange to me as well, i was using mm39 as reference and annotation for genome and gene, it take me too long when i trying to run FragmentHistogram() FUNCTION with 7666cells i wonder if you solve the issue? @jiangpuxuan very thanks for any infomation
I have not  solved it yet.....

**Comment by cmf1997** [comment]
may be the problem lay on genomic infomation
i have noticed that you were using non-standard or self-construct genomic information and gene annotation as well as i did
