### ISSUE TITLE
can not find hsc_cell.txt in monocle3 vignettes

### ISSUE THREAD

**Issue by wjyzidane** [timoast/signac#1023]
When I try "Building trajectories with Monocle 3" (https://satijalab.org/signac/articles/monocle.html)

I can not find a place to download the file hsc_cell.txt to complete this step in vignettes.

# load the pre-selected HSCs
hsc <- readLines("../vignette_data/hsc_cells.txt")

**Comment by timoast** [comment]
Did you download the hsc_cell.txt file? It is linked in the vignette. You will need to set the path to wherever you have saved the file

**Comment by wjyzidane** [comment]
Sorry. I just found the link:

Here we’ve pre-selected some cells as the root, and saved these to a file for reproducibility. This file can be downloaded [here](https://www.dropbox.com/s/w5jbokcj9u6iq04/hsc_cells.txt).

Thanks for your quick reply!
