### ISSUE TITLE
Coverageplot cannot display both `title` and `features` at the same time

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1027]
Here is my code:
```r
CoveragePlot(
  object = xxxx.atac,
  region = region,
  extend.upstream = 40000,
  extend.downstream = 20000,

  region.highlight = ranges.show,
  features = 'xxxx'
)+ labs(
    title = 'xxxxxx'
)
```
If I choose `features = 'xxxx'`, the plot has no `labs(title = 'xxxxxx')` and no `region.highlight = ranges.show`.
How could I adjust parameters to make it work? Thank you for your help.

**Comment by timoast** [comment]
The `CoveragePlot()` function returns a `patchwork` object, not a standard `ggplot` object (see the [documentation](https://satijalab.org/signac/reference/coverageplot)). In some cases this can't be modified using the standard ggplot2 syntax. However you can access each sub-plot using list indexing. For example:

```r
p1 <- CoveragePlot(
  object = obj,
  ...
)
p1[[1]][[1]] <- p1[[1]][[1]] + ggtitle("Title")
```

**Comment by jiangpuxuan** [comment]
> The `CoveragePlot()` function returns a `patchwork` object, not a standard `ggplot` object (see the [documentation](https://satijalab.org/signac/reference/coverageplot)). In some cases this can't be modified using the standard ggplot2 syntax. However you can access each sub-plot using list indexing. For example:
> 
> ```r
> p1 <- CoveragePlot(
>   object = obj,
>   ...
> )
> p1[[1]][[1]] <- p1[[1]][[1]] + ggtitle("Title")
> ```

Thank you.
