### ISSUE TITLE
MergeWithRegions can not work...

### ISSUE THREAD

**Issue by TeruUme** [timoast/signac#1034]
Now, I am trying the integration of two scATAC-Seq samples by using MergeWithRegions function, as described in https://satijalab.org/signac/0.2/articles/integration.html.
However, I got the following error message, when I use this function.

> unintegrated <- MergeWithRegions(object.1 = sample1, object.2 = sample2, assay.1 = 'peaks', assay.2 = 'Peaks', sep.1 = c("-", "-"), 
 sep.2 = c("-", "-"))
Error in MergeWithRegions(object.1 = sample1, object.2 = sample2, assay.1 = "peaks",  : 
  could not find function "MergeWithRegions"

And when I try the command "Signac::MergeWithRegions",  the following message is generated.

> Signac::MergeWithRegions
Error: 'MergeWithRegions' is not an exported object from 'namespace:Signac'

This kind of problems was observed in "GetFragments".
Please help!

**Comment by timoast** [comment]
Hi @TeruUme, you're looking at an older version of the documentation for Signac 0.2. This won't work unless you have Signac 0.2 installed. I'd suggest using the latest Signac release and the latest version of the documentation: https://satijalab.org/signac/

**Comment by TeruUme** [comment]
Thank you, timoast.

I am now trying the integration of two scATAC-Seq samples by refering to the manual of Signac 1.6.0 (https://satijalab.org/signac/articles/integrate_atac.html).
However, I have new error at the step of IntegrateEmbeddings.
Now, I have the following error massage.

> integrated <- IntegrateEmbeddings(anchorset = integration.anchors, reductions = Combined[["lsi"]], new.reduction.name = "integrated_lsi", dims.to.integrate = 2:30, k.weight = 47)
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
  |===========================================================================================================================| 100%
Binding matrix rows
Merging dataset 1 into 2
Extracting anchors for merged samples
Finding integration vectors
Finding integration vector weights
**Error in idx[i, ] <- res[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length**

Since 48 anchors were found at the step of FindTopFeatures, I add "k.weight = 47" in this step.
What steps should I confirm to solve this problem?
