### ISSUE TITLE
Coverageplot() cannot add `links=TRUE`

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1036]
Hi,
Here is my code:
```r
CoveragePlot(
  object = my.atac,
  region = 15-20220000-20229000',
  links = TRUE,
  extend.upstream = 20000,
  extend.downstream = 10000,
  region.highlight = ranges.show,
)
```
<img width="350" alt="cf432c2d37c3d6b748ef84a035361c4" src="https://user-images.githubusercontent.com/81287604/157805406-fd95e702-ed8b-4b5f-bbd3-f99640952a48.png">

Howerver it cannot display the linkplot.

And I run `LinkPlot(  object = my.atac,region = '15-20220000-20229000')` individually, but this Linkplot is `NULL`.

**Comment by timoast** [comment]
Did you run `LinkPeaks()` Can you show the full code?

**Comment by jiangpuxuan** [comment]
> Did you run `LinkPeaks()`? Can you show the full code?

Well, I found I cannot run `LinkPeaks()` ...Here is my code.
```
my.atac<-RegionStats(my.atac, genome = BSgenome.medaka.UCSC.ens94,assay='peaks',verbose = TRUE)
my.atac<-LinkPeaks(my.atac,peak.assay = 'peaks',expression.assay='RNA',
  expression.slot = "data",
  gene.coords = NULL, # GRanges object containing coordinates of genes in the expression assay. If NULL, extract from gene annotations stored in the assay.
  distance = 5e+05,
  min.distance = NULL,
  min.cells = 10,
  method = "pearson",
  genes.use = NULL,
  n_sample = 200,
  pvalue_cutoff = 0.05,
  score_cutoff = 0.05,
  verbose = TRUE)
```
The error is `Could not find gene coordinates for requested genes`.
I look up [https://github.com/timoast/signac/blob/master/R/links.R](url), finding the `gene.coords` comes from:
```
CollapseToLongestTranscript(
      ranges = Annotation(object = object[['peaks']])
    )
```
But I cannot find `CollapseToLongestTranscript` function...................

**Comment by timoast** [comment]
The reason you see this error is that none of the gene names in the expression assay were found in the gene annotations stored in your object. I'd suggest looking into why that is the case.
