### ISSUE TITLE
Failed to run FeatureMatrix() with a customized fragment object

### ISSUE THREAD

**Issue by HKL-97** [timoast/signac#1038]
Hi!

I have a follow-up question for Discussion #1025 .
I created a fragment object with a customized .bed file (not generated from 10X) with CreateFragmentObject().
(The .bed file has been sorted, compressed and tabix-indexed with `bgzip` and `tabix -p bed fragments.bed.gz`)

Next I created a GRange object with CallPeaks().
But then, I failed to create a matrix with FeatureMatrix().

Codes shown below:
`fragments<-CreateFragmentObject('fragments.bed.gz')`
`features<-CallPeaks(fragments,format='BED',outdir ='out',name='name',
                    cleanup=FALSE)`
`matrix<-FeatureMatrix(fragments,features)`

Error message shown below:

> Extracting reads overlapping genomic regions
>   |                                                  | 0 % ~calculating  Error in sparseMatrix(i = matrix.features, j = matrix.cells, x = rep(x = 1,  : 
>   NA's in (i,j) are not allowed

`sessionInfo()`

> R version 4.1.0 (2021-05-18)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 20.04.2 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] Signac_1.2.1
> 
> loaded via a namespace (and not attached):
>   [1] Seurat_4.0.2           Rtsne_0.15             colorspace_2.0-2      
>   [4] deldir_1.0-6           ellipsis_0.3.2         ggridges_0.5.3        
>   [7] lsa_0.73.2             XVector_0.32.0         GenomicRanges_1.44.0  
>  [10] rstudioapi_0.13        spatstat.data_2.1-2    farver_2.1.0          
>  [13] leiden_0.3.8           listenv_0.8.0          SnowballC_0.7.0       
>  [16] ggrepel_0.9.1          fansi_0.5.0            codetools_0.2-18      
>  [19] splines_4.1.0          docopt_0.7.1           RcppRoll_0.3.0        
>  [22] polyclip_1.10-0        jsonlite_1.7.2         Rsamtools_2.8.0       
>  [25] ica_1.0-2              cluster_2.1.1          png_0.1-7             
>  [28] uwot_0.1.10            ggforce_0.3.3          shiny_1.6.0           
>  [31] sctransform_0.3.2      spatstat.sparse_2.1-0  compiler_4.1.0        
>  [34] httr_1.4.2             assertthat_0.2.1       SeuratObject_4.0.4    
>  [37] Matrix_1.3-4           fastmap_1.1.0          lazyeval_0.2.2        
>  [40] tweenr_1.0.2           later_1.3.0            htmltools_0.5.2       
>  [43] tools_4.1.0            igraph_1.2.11          gtable_0.3.0          
>  [46] glue_1.6.0             GenomeInfoDbData_1.2.6 RANN_2.6.1            
>  [49] reshape2_1.4.4         dplyr_1.0.6            fastmatch_1.1-0       
>  [52] Rcpp_1.0.7             slam_0.1-48            scattermore_0.7       
>  [55] vctrs_0.3.8            Biostrings_2.60.0      nlme_3.1-152          
>  [58] ggseqlogo_0.1          lmtest_0.9-39          stringr_1.4.0         
>  [61] globals_0.14.0         mime_0.12              miniUI_0.1.1.1        
>  [64] lifecycle_1.0.1        irlba_2.3.5            goftest_1.2-3         
>  [67] future_1.23.0          zlibbioc_1.38.0        MASS_7.3-53.1         
>  [70] zoo_1.8-9              scales_1.1.1           spatstat.core_2.1-2   
>  [73] promises_1.2.0.1       spatstat.utils_2.3-0   parallel_4.1.0        
>  [76] RColorBrewer_1.1-2     reticulate_1.22        pbapply_1.5-0         
>  [79] gridExtra_2.3          ggplot2_3.3.3          rpart_4.1-15          
>  [82] stringi_1.7.6          S4Vectors_0.30.0       BiocGenerics_0.38.0   
>  [85] BiocParallel_1.26.0    GenomeInfoDb_1.28.0    rlang_0.4.12          
>  [88] pkgconfig_2.0.3        matrixStats_0.61.0     bitops_1.0-7          
>  [91] qlcMatrix_0.9.7        lattice_0.20-41        ROCR_1.0-11           
>  [94] purrr_0.3.4            tensor_1.5             patchwork_1.1.1       
>  [97] htmlwidgets_1.5.4      cowplot_1.1.1          tidyselect_1.1.1      
> [100] parallelly_1.30.0      RcppAnnoy_0.0.19       plyr_1.8.6            
> [103] magrittr_2.0.1         R6_2.5.1               IRanges_2.26.0        
> [106] generics_0.1.1         DBI_1.1.1              mgcv_1.8-35           
> [109] pillar_1.6.4           fitdistrplus_1.1-6     survival_3.2-10       
> [112] abind_1.4-5            RCurl_1.98-1.3         tibble_3.1.2          
> [115] future.apply_1.8.1     crayon_1.4.2           KernSmooth_2.23-18    
> [118] utf8_1.2.2             spatstat.geom_2.3-1    plotly_4.9.4          
> [121] grid_4.1.0             data.table_1.14.2      sparsesvd_0.2         
> [124] digest_0.6.29          xtable_1.8-4           tidyr_1.1.3           
> [127] httpuv_1.6.5           stats4_4.1.0           munsell_0.5.0         
> [130] viridisLite_0.4.0    
>

**Comment by timoast** [comment]
Can you show the output of `head(fragments)` and `head(features)`?

**Comment by HKL-97** [comment]
`head(fragments)`
```
    V1      V2      V3               V4
1 chr1 3022501 3022608 R140R209R331P105
2 chr1 3030821 3030871 R130R286R330P105
3 chr1 3044170 3044359 R190R256R356P105
4 chr1 3047321 3047366 R185R264R343P105
5 chr1 3060730 3060786 R118R289R328P105
6 chr1 3064264 3064369 R187R217R329P105
```


`head(features)`
```
GRanges object with 6 ranges and 6 metadata columns:
      seqnames          ranges strand |        name     score fold_change neg_log10pvalue_summit neg_log10qvalue_summit
         <Rle>       <IRanges>  <Rle> | <character> <integer>   <numeric>              <numeric>              <numeric>
  [1]     chr1 3514835-3515183      * | name_peak_1       124     9.70149               16.02205               12.46392
  [2]     chr1 3671584-3671867      * | name_peak_2        38     4.75683                6.45110                3.81055
  [3]     chr1 4571630-4572028      * | name_peak_3        49     5.46875                7.67852                4.91268
  [4]     chr1 4671606-4671831      * | name_peak_4        56     6.00000                8.46401                5.61649
  [5]     chr1 4722319-4722525      * | name_peak_5        38     4.75683                6.45110                3.81055
  [6]     chr1 4766588-4766797      * | name_peak_6        63     6.41026                9.29850                6.37134
      relative_summit_position
                     <integer>
  [1]                      155
  [2]                      192
  [3]                      260
  [4]                      164
  [5]                      117
  [6]                       59
  -------
  seqinfo: 20 sequences from an unspecified genome; no seqlengths
```

Thank you so much!

**Comment by timoast** [comment]
Ok so the fragment file is not in the correct format, there needs to be a 5th column containing the PCR duplicate count for each fragment. You can create a fragment file using the [Sinto](https://timoast.github.io/sinto/basic_usage.html#create-scatac-seq-fragments-file) package

**Comment by timoast** [comment]
In fact, newer Signac releases will throw an error in `CreateFragmentObject()` if the file is not formatted correctly (https://github.com/timoast/signac/issues/748), I'd suggesting updating to the latest release

**Comment by HKL-97** [comment]
Sounds great! Thank you Tim.
