### ISSUE TITLE
Error with RegionStats

### ISSUE THREAD

**Issue by Eoin-W** [timoast/signac#1039]
I've been trying to analyse 10X Multiome data of rat cells. Samples seem to process fine, I can cluster cells and create UMAPs and CoveragePlots just fine. But when I run RegionStats I get an error. 

```
Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width,  : 
  sequence 1 not found
```

Full code below. Any help here would be much appreciated! 

![image](https://user-images.githubusercontent.com/101597955/158251528-2f654c1a-e545-453d-923b-0fd2d49931b2.png)
![image](https://user-images.githubusercontent.com/101597955/158251552-a38c21c2-f42b-4366-a80e-2fab4b884190.png)
![image](https://user-images.githubusercontent.com/101597955/158251565-8f222c37-0cba-4ba5-b3cc-9a720b6f1823.png)
![image](https://user-images.githubusercontent.com/101597955/158251732-95e0adf1-c398-4abb-aa79-ee2d8665c0bd.png)
![image](https://user-images.githubusercontent.com/101597955/158251764-bdf46452-8ccb-4531-9c35-f00002cd14d5.png)
![image](https://user-images.githubusercontent.com/101597955/158251821-7f937579-d6b0-4e26-9d0d-942da6b1076f.png)
![image](https://user-images.githubusercontent.com/101597955/158251838-da1a855d-f79e-44b2-a8bb-6b120bdc862a.png)

**Comment by timoast** [comment]
The seqnames in the genome object need to match the seqnames used in your analysis. Here, it looks like you have NCBI seqnames (1, 2,, 3, etc.), but the genome is UCSC-style (chr1, chr2, chr2, etc.).

For some reason it doesn't look like the `seqlevelsStyle()` function works for the rat genome, but you can change the seqnames style by running:

```
seqnames(BSgenome.Rnorvegicus.UCSC.rn6) <- gsub("^chr", "", seqnames(BSgenome.Rnorvegicus.UCSC.rn6))
```
