### ISSUE TITLE
coverageplot track labels

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#104]
Hi Tim,

Is it possible to manually input labels for the different coverage tracks in CoveragePlot?

Thank you,

**Comment by timoast** [comment]
The labels come from the cell identities, to change the labels change the cell identities. See the [Idents](https://www.rdocumentation.org/packages/Seurat/versions/3.1.0/topics/Idents) function in Seurat.

**Comment by Brawni** [comment]
thanks for the prompt reply..ok cool! It's just that i need to plot some additional values for each track but I guess i can attach them to idents too. I think it would be useful anyway to add labels to individual tracks.

Cheers!

**Comment by timoast** [comment]
This is how ggplot2 works (labels come from the data), and I think we want to continue to follow that design principle. If you wanted to change the legend in ggplot2 you would change the values in input dataframe, in Seurat or Signac you would change the Idents or the metadata.
