### ISSUE TITLE
The Addmotif get error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#1040]
Hi @timoast ,

library(JASPAR2020)
library(TFBSTools)

The motif predicted still getting error, the  code lying below:

pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
)
library(BSgenome.Hsapiens.UCSC.hg19)

DefaultAssay(pbmc1)<-'peaks'
# add motif information
pbmc1 <- AddMotifs(
  object = pbmc1,
  genome = BSgenome.Hsapiens.UCSC.hg19,
  pfm = pfm
)

Building motif matrix
Error in loadFUN(x, seqname, ranges) : 
  trying to load regions beyond the boundaries of non-circular sequence "chr3"

Best,
Hanhuihong

**Comment by timoast** [comment]
Can you show the output of `head(rownames(pbmc1))` and `sessionInfo()`?

**Comment by honghh2018** [comment]
Hi @timoast ，
     I had figured it out myself,  because the coordination was mapping with hg38, not  the hg19. so changing the BSgenome.Hsapiens.UCSC.hg19 into BSgenome.Hsapiens.UCSC.hg30, the issue solved itself.
    The coordination of hg38 boundary out of the boundary of hg19


Best,
hanhuihong
