### ISSUE TITLE
Footprinting on defined regions

### ISSUE THREAD

**Issue by arielpourmorady** [timoast/signac#1041]
Hi there,

I am trying to identify footprints from a set of genomic coordinates. I am using the Footprint function in Signac as follows:

Step 1: Generating Regions object

```r
bed <- as.data.frame(read.table("/data/multiome/Greek_Islands.bed",header = FALSE, sep="\t",stringsAsFactors=FALSE))
bed$regions <-  paste(bed$V1, bed$V2, bed$V3, sep = "-")
bed <- bed[1:62,]
regions = StringToGRanges(bed$regions, keep.extra.columns=TRUE)
regions`

GRanges object with 62 ranges and 0 metadata columns:
       seqnames              ranges strand
          <Rle>           <IRanges>  <Rle>
   [1]     chr1   92545930-92546383      *
   [2]     chr1 173190529-173190944      *
   [3]     chr1 173212162-173212558      *
   [4]     chr1 173265692-173266108      *
   [5]     chr1 174035928-174036370      *
   ...      ...                 ...    ...
  [58]     chr7 108797459-108797867      *
  [59]     chr7 140186968-140187491      *
  [60]     chr9   19651135-19651501      *
  [61]     chr9   37687616-37688065      *
  [62]     chr9   39951989-39952440      *
  -------
  seqinfo: 15 sequences from an unspecified genome; no seqlengths
```

Step 2: Footprinting

```r
moe  <- Footprint(
  object = moe,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  regions = regions,
  key = "islands"
)
```

However, when I do this, I get the following error:

```
Computing observed Tn5 insertions per base
Computing base composition at motif sites
Error in .Call2("C_solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 55: 'allow.nonnarrowing' is FALSE and the solved end (871) is > refwidth
In addition: Warning messages:
1: In Extend(x = regions, upstream = upstream, downstream = downstream) :
  '*' ranges were treated as '+'
2: In Extend(x = regions, upstream = 3, downstream = 3) :
  '*' ranges were treated as '+'`
```

It looks like the error has something to do with reconciling the length of a region with the reference? I don't really understand this though, because even when I subset regions by those that overlap with the scATAC fragments as follows:

`overlap_regions = subsetByOverlaps(granges(moe), regions)
`

I still produce the same error.

Do you know how to resolve this issue? Thank you.

**Comment by timoast** [comment]
I think this is due to the input regions having different widths. The documentation was not clear here, and I've now updated it, but all the regions should have the same width. 

The footprinting function was not really designed for this use-case, you should try using the `RegionMatrix()` and `RegionPlot()`/`RegionHeatmap()` functions instead.
