### ISSUE TITLE
About FindTransferAnchors issue

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#105]
Hi @timoast 
     I did the workflow that you posted in vignette on the step FindTransferAnchor showing the resultting plot below:
     The scRNA UMAP plot:
      
      
![image](https://user-images.githubusercontent.com/41668708/75619373-fd979780-5bb5-11ea-9eb7-c8fbd364c9c0.png)

     The ATAC TransferAnchor UMAP plot:
     
![image](https://user-images.githubusercontent.com/41668708/75619395-3a638e80-5bb6-11ea-8124-b5d2e006d5fb.png)
    The combined plot:
![image](https://user-images.githubusercontent.com/41668708/75619401-4c453180-5bb6-11ea-8641-c702cc096af8.png)
   ### the sample both ATAC-seq and ScRNA-seq come from same testis sample. Logically the combined UMAP analysis should be showing same cluster trend. whereas, the plot showing above 
 in ATAC demonstrating all cluster mix together?
 What can be for this issue? can i amend this problem?

**Comment by timoast** [comment]
The RNA-seq data looks very unusual so I would recommend taking a second look at how you're processing that. 

> in ATAC demonstrating all cluster mix together?

I would not say that all clusters are mixed together in the scATAC-seq, quite the opposite. You have good separation of many clusters. There is some ambiguity in the larger cluster, but not really any more so than in the scRNA-seq data

**Comment by honghh2018** [comment]
Hi @timoast,
    Thanks for the crucial prompting about ScRNA.
     The whole processing of ScRNA code showing below:
#load packages
library(dplyr)
library(cowplot)
library(ggplot2)
library(Seurat)
#read sample matrix data
H1.data <- Read10X(data.dir = "/share/nas1/Data/Users/yinl/Project/personality/LCM_20191218/count/H1/")
H2.data <- Read10X(data.dir = "/share/nas1/Data/Users/yinl/Project/personality/LCM_20191218/count/H2/")
F1.data <- Read10X(data.dir = "/share/nas1/Data/Users/yinl/Project/personality/LCM_20191218/count/F1/")
F2.data <- Read10X(data.dir = "/share/nas1/Data/Users/yinl/Project/personality/LCM_20191218/count/F2/")
#transfer into seurat object
H1 <- CreateSeuratObject(counts = H1.data, project = "Health1", min.cells = 3, min.features = 200)
H2 <- CreateSeuratObject(counts = H2.data, project = "Health2", min.cells = 3, min.features = 200)
F1 <- CreateSeuratObject(counts = F1.data, project = "Fat1", min.cells = 3, min.features = 200)
F2 <- CreateSeuratObject(counts = F2.data, project = "Fat2", min.cells = 3, min.features = 200)
#filter mt gene and ribosome gene
H1[["percent.mt"]] <- PercentageFeatureSet(H1, pattern = "^mt-")
H1[["rp.mt"]] <- PercentageFeatureSet(H1, pattern = "^Rpl|^Rps")
H2[["percent.mt"]] <- PercentageFeatureSet(H2, pattern = "^mt-")
H2[["rp.mt"]] <- PercentageFeatureSet(H2, pattern = "^Rpl|^Rps")
F1[["percent.mt"]] <- PercentageFeatureSet(F1, pattern = "^mt-")
F1[["rp.mt"]] <- PercentageFeatureSet(F1, pattern = "^Rpl|^Rps")
F2[["percent.mt"]] <- PercentageFeatureSet(F2, pattern = "^mt-")
F2[["rp.mt"]] <- PercentageFeatureSet(F2, pattern = "^Rpl|^Rps")
grep('rpl',rownames(H1),ignore.case = T,value = T)
#draw 
VlnPlot(H1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","rp.mt"), ncol = 2,pt.size = 0)
VlnPlot(H2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","rp.mt"), ncol = 2,pt.size = 0)
VlnPlot(F1, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","rp.mt"), ncol = 2,pt.size = 0)
VlnPlot(F2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt","rp.mt"), ncol = 2,pt.size = 0)
#filter data
H1 <- subset(H1, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 15)
H2 <- subset(H2, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 15)
F1 <- subset(F1, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 15)
F2 <- subset(F2, subset = nFeature_RNA > 200 & nFeature_RNA < 7500 & percent.mt < 15)
#merge four sample and normalized 
merge_LCM_data<-merge(x=H1, y=c(H2, F1, F2),add.cell.ids = c('Health1','Health2','Fat1','Fat2'))
split_LCM_list<-SplitObject(merge_LCM_data,split.by = 'orig.ident')
combined_LCM_list<-lapply(X=split_LCM_list,FUN=function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
#find anchor and integrated data
pancreas_LCM.anchors <- FindIntegrationAnchors(object.list = combined_LCM_list, dims = 1:30)
pancreas_LCM.integrated <- IntegrateData(anchorset = pancreas_LCM.anchors, dims = 1:30)
#cheack object data
table(pancreas_LCM.integrated@meta.data$orig.ident=="Health1")
table(pancreas_LCM.integrated@meta.data$orig.ident=="Health2")
table(pancreas_LCM.integrated@meta.data$orig.ident=="Fat1")
table(pancreas_LCM.integrated@meta.data$orig.ident=="Fat2")
groups <- c(rep("Health",29534),rep("Fat",27578))
names(groups) <- colnames(pancreas_LCM.integrated)
#add 
pancreas_LCM.integrated<- AddMetaData(object =pancreas_LCM.integrated, metadata = groups, col.name = "group")
#draw umap and tsne
DefaultAssay(pancreas_LCM.integrated) <- "integrated"
pancreas_LCM.integrated <- ScaleData(pancreas_LCM.integrated, verbose = FALSE)
pancreas_LCM.integrated <- RunPCA(pancreas_LCM.integrated, npcs = 30, verbose = FALSE)
pancreas_LCM.integrated <- JackStraw(pancreas_LCM.integrated, num.replicate = 100)
ElbowPlot(pancreas_LCM.integrated)
pancreas_LCM.integrated <- FindNeighbors(pancreas_LCM.integrated, dims = 1:12)
pancreas_LCM.integrated <- FindClusters(pancreas_LCM.integrated, resolution = 0.2)
pancreas_LCM.integrated <- RunTSNE(pancreas_LCM.integrated, reduction = "pca", dims = 1:12)
pancreas_LCM.integrated <- RunUMAP(pancreas_LCM.integrated, reduction = "pca", dims = 1:12)

plot_group<-DimPlot(pancreas_LCM.integrated, reduction = "tsne",label = T,split.by = 'group')
plot_sample<-DimPlot(pancreas_LCM.integrated, reduction = "umap",label = T)

#find marker
DefaultAssay(pancreas_LCM.integrated) <- "RNA"
pancreas_LCM.integrated<-NormalizeData(pancreas_LCM.integrated,verbose = FALSE)
pancreas_LCM.integrated.markers <- FindAllMarkers(pancreas_LCM.integrated, only.pos = TRUE, min.pct = 0.1, logfc.threshold = 0.25)
write.table(pancreas_LCM.integrated.markers,file = '/share/nas1/Data/Users/yinl/Project/personality/LCM_20191218/Seurat/20191222/all_markgene.xls',quote = F,row.names = F,sep = '\t')
# 
The code i posted above was all i processed ScRNA data?
Any advices would be grateful.

**Comment by timoast** [comment]
Two things to note:

1. Are you sure that you are assigning the treatment groups correctly? The code you used will only work if the cells are in the order that you expect (all healthy cells followed by all fat cells)
2. You are only using 12 PCs, which is quite low.

**Comment by honghh2018** [comment]
Thanks for the warn.
     It is no doubt that the cell order come from seurat object meta.data was health1, health2, fat1, fat2. 
     For the sake of throwing your concerns, I checked the meta.data of my object twice, and confirm the cell order that was i told above.
     The next question you need me to notice was the PCs. on this case, I run lots of times about attemptting get the best PCs on my next analysis. nevertheless, It make cluster 23 at least or more, as i make the PCs hight than twelve. 
     I expected the cluster number can be less and just conformed to sperm growth. So i picked the 12.
     Thanks
