### ISSUE TITLE
running signac on cellranger aggr output - orig.idents

### ISSUE THREAD

**Issue by el-hodiri** [timoast/signac#1051]
Previous discussion:  "Yes, the output of cellranger atac aggr is very similar to that of cellranger count. See here for information on cellranger atac aggr outputs: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/aggr

"You will have a count matrix, fragments file, and single-cell metrics file that you can use to create a Seurat object and run the Signac pipeline as shown in the vignettes: https://satijalab.org/signac/articles/pbmc_vignette.html"

_Originally posted by @timoast in https://github.com/timoast/signac/issues/43#issuecomment-561203277_

**Comment by el-hodiri** [comment]
After running cellranger-atac aggr output through Signac, is there a way to identify cells by the equivalent of "orig.ident"? The cellranger aggr documentation states that barcodes are assigned a suffix corresponding to GEM well and part of the input for aggr is library_id, so it seems that this information may be in the Seurat/Signac object.

**Comment by timoast** [comment]
The `names.field` and `names.delim` parameters in `CreateSeuratObject()` control what is set as `orig.ident`. The default parameters will set the value after the first `-` character in the cell barcode as the `orig.ident` value.
