### ISSUE TITLE
GeneActivity returning non-gene names

### ISSUE THREAD

**Issue by el-hodiri** [timoast/signac#1055]
Hi!  I am using Signac to analyze scATAC seq data from chicken.  After I  run GeneActivity to assign gene names to genomic ranges, I get what look like placeholders (".n", where n is an integer) instead of gene names in some instances.  Here is an example from an object called ATAC_10:

![image](https://user-images.githubusercontent.com/85573641/159737749-298303e1-6c14-4ade-b950-795af34f1687.png)

My thought was that the ".n"s represented genomic regions that could not be assigned to genes, but I am not sure how to see those ranges.  I tried looking up the genomic ranges from the ATAC assay, but they don't seem to correspond.

![image](https://user-images.githubusercontent.com/85573641/159738553-92906a9e-2078-424e-9c07-b2a79f3a159c.png)

The third genomic range in the genomic ranges list, for example, does not correspond to the the third gene in the gene list (GOLGB1), which is on chromosome 1 (not W).

I tried expanding the genomic range in GeneActivity to 500 upstream of TSS and 1000 downstream of TTS but that made no difference in the ".n"s and gene names.  I also tried setting biotypes = "protein_coding" in GeneActivity, but that made no difference.

So - what do these ".n" represent and how do I resolve them?

Any help would be greatly appreciated.  Thanks in advance.

**Comment by el-hodiri** [comment]
Note added ... I prepared the Signac/Seurat object using 4 individual cellranger-ATAC outputs and a common peak file from cellranger-ATAC aggr.  When I build the object straight from aggr output, I do not have this problem.  The issue returns if I build the object from aggr output but use names.field and names.delim in CreateSeuratObject to distinguish between different libraries.

**Comment by timoast** [comment]
What version of Signac are you using? Can you show the output of sessionInfo()?

My guess is that the gene names for these genes are not present in the gene annotations you're using, although we should be replacing those with the gene ID. I guess it's possible that both the gene name and gene ID are blank for these genes. Can you show the first few lines of the gene annotations you're using?

**Comment by el-hodiri** [comment]
screen grab of annotations:

![image](https://user-images.githubusercontent.com/85573641/160451615-c23f7cf4-6da5-4b5b-8509-f68555ff09b3.png)

**Comment by timoast** [comment]
Should be fixed now on the develop branch

**Comment by el-hodiri** [comment]
IT WORKED! THANK YOU!!!

![image](https://user-images.githubusercontent.com/85573641/160880840-f6cd0572-023f-47d4-8f70-b62b1ff04f3e.png)
