### ISSUE TITLE
Possible bug in SplitFragments()

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#1057]
I split fragments by cluster before running `macs2` on each cluster individually: 
```
atac <- AddMetaData(atac, metadata = metadata)   # add data frame to seurat object metadata

# split fragments by cluster ('cluster.links' column in atac@meta.data)
SplitFragments(atac, group.by = 'cluster.links', outdir = frag.dir,
               file.suffix = paste0('_', sample.id[i]))
```

I feed each cluster to `macs2` individually using Signac source code: 
```
cmd <- paste0('macs2 callpeak -t ', frag.path, cluster[j], '_', sample.id[i], '.bed ',
                '-g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n ', cluster[j],
                '.peaks.', sample.id[i],' --outdir ', outs)
  system(cmd)
```
 
`macs2` gives multiple errors.  One in particular may be related to `SplitFragments`.  Look: 
```
system(cmd)
# Traceback (most recent call last):
# [a bunch of macs2 commands]
# MACS2.IO.Parser.StrandFormatError: 'Strand information can not be recognized in this line: 
# "chr9\t37080530\t37080807\tCACGTTCTCTCATCCGchr9\t36894268\t36894318\tACTGCGGTCACACGTA-1\t6","36894318"'
```
If you look at line 1871023 of the bed file output from `SplitFragments`:
```
# in bash, not R
sed -n '187102p' Astro1_1557.bed
chr9    37080530        37080807        CACGTTCTCTCATCCGchr9    36894268        36894318        ACTGCGGTCACACGTA-1  6
```
Seems to be no new line insertion for some reason.  Of all the files output from splitfragments, this error happens in about 2% of them (I have 600 total)

I recieved other errors in MACS2, possibly related to this.  I am looking into them now.

**Comment by timoast** [comment]
Can you confirm that this incorrect entry was not present in the original fragment file before splitting?

**Comment by danielcgingerich** [comment]
Hey Tim.  Sorry for the misunderstanding.  This seemed to be a problem with my storage capacity.  Looks like text stopped appending to the file midway through the run.  This is why some entries were truncated.  Cleared out the storage and everything seem to run smoothly

**Comment by danielcgingerich** [comment]
@timoast this issue was not a bug.  not sure how to remove the tag.  Sorry about that!
