### ISSUE TITLE
selecting biotypes for creating gene activity

### ISSUE THREAD

**Issue by SinghalDivya** [timoast/signac#1058]
Hi,

I am trying to create the gene activity matrix for not only protein-coding regions but also other mentioned biotypes such as  biotypes = c("protein_coding", "lincRNA", "rRNA", "processed_transcript"). But whenever i try to change the biotypes, i get following error:

```r
> gene.activities <- GeneActivity(
+   pbmc,
+   assay = NULL,
+   features = NULL,
+   extend.upstream = 2000,
+   extend.downstream = 0,
+   biotypes = c("protein_coding", "lincRNA", "rRNA", "processed_transcript"),
+   max.width = 5e+05,
+   gene.id = FALSE,
+   verbose = TRUE
+ )
Extracting gene coordinates
Error in FeatureMatrix(fragments = Fragments(object = object[[assay]]),  : 
  unused arguments (biotypes = c("protein_coding", "lincRNA", "rRNA", "processed_transcript"), max.width = 5e+05, gene.id = FALSE)
```

It would be great if you could suggest to me how to include other biotypes. 

Thank you

**Comment by timoast** [comment]
Can you show the output of `sessionInfo()`?

**Comment by timoast** [comment]
Should be fixed now on the develop branch

**Comment by SinghalDivya** [comment]
I am unable to install develop branch, is there something to do with R version?

> remotes::install_github("timoast/signac", ref = "develop")
Downloading GitHub repo timoast/signac@develop
Skipping 6 packages not available: BiocGenerics, S4Vectors, Rsamtools, IRanges, GenomicRanges, GenomeInfoDb
   During startup - Warning messages:
   1: Setting LC_CTYPE failed, using "C" 
   2: Setting LC_TIME failed, using "C" 
   3: Setting LC_MESSAGES failed, using "C" 
   4: Setting LC_MONETARY failed, using "C" 
   5: Setting LC_PAPER failed, using "C" 
   6: Setting LC_MEASUREMENT failed, using "C" 
v  checking for file '/tmp/RtmpmGmuRG/remotes1cbbc615c25d76/timoast-signac-979cf4a/DESCRIPTION' ... OK
-  preparing 'Signac':
v  checking DESCRIPTION meta-information ... OK
-  cleaning src
-  installing the package to process help pages
-  saving partial Rd database (43.6s)
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Removed empty directory 'Signac/.github'
   Removed empty directory 'Signac/vignettes'
-  building 'Signac_1.6.0.9008.tar.gz'
   Warning: invalid uid value replaced by that for user 'nobody'
   Warning: invalid gid value replaced by that for user 'nobody'
   
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) installation of package '/tmp/RtmpmGmuRG/file1cbbc64cfbdb1c/Signac_1.6.0.9008.tar.gz' had non-zero exit status

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.4 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /work/gallo_lab/divya/softwares/miniconda3/envs/signac/lib/libopenblasp-r0.3.12.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.5.2    compiler_4.0.3    R6_2.5.1          rprojroot_2.0.2  
 [5] cli_3.2.0         prettyunits_1.1.1 tools_4.0.3       withr_2.5.0      
 [9] curl_4.3.2        crayon_1.5.1      remotes_2.2.0     callr_3.7.0      
[13] ps_1.6.0          pkgbuild_1.2.0

**Comment by timoast** [comment]
This looks like a locale issue unrelated to Signac, you could try some suggestions here: https://stackoverflow.com/questions/27299420/how-to-get-rid-of-warning-messages-after-installing-r
