### ISSUE TITLE
Non-reproducible cluster numbering

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#1059]
Problem is this:
Some time ago we used this quite standard process (peaks assay from scATAC):
s.data <- RunUMAP(object = s.data, reduction = 'lsi', dims = 2:30, min.dist=0.05, spread=1.1)
s.data <- FindNeighbors(object = s.data, reduction = 'lsi', dims = 2:30)
s.data <- FindClusters(object = s.data, verbose = FALSE, algorithm = 4, resolution = 1)
DimPlot(object = s.data, label = TRUE, pt.size=1.2) + NoLegend()

with Seurat 4.0.5, Signac 1.4.0, leiden_0.3.9. Set.seed() was set.

This resulted in a certain number for each cluster obviously. Now we tried to run the same code on another machine, same architecture (Intel Mac), and same OS, but with some differences in conda env and in packages. Anyhow, we did install there specifically same Seurat, Signac, and leiden versions. Nevertheless, what happens is that umap projection itself is exactly the same, but no matter what we do, cluster numbers are assigned differently. A same number of clusters and all, but the decision of which number is given to which cluster is different.

Where this code goes to get this numbering? Something we haven't been able to standardize between the machines. We have been reading the source code but yet not found a reason for this.

It is quite a big problem now as our student can't take the project into his computer to carry on with it.

**Comment by timoast** [comment]
Since these functions are part of Seurat, please open this issue in the Seurat repo.

You could also try setting the algorithm to 1, 2, or 3 (the methods that don't require Python), to narrow down the issue further.
