### ISSUE TITLE
Why RunUMAP with dim = 2:30

### ISSUE THREAD

**Issue by Ceeyouthere** [timoast/signac#106]
Hi, 
I am following the PBMC tutorial of the Signac. The RunUMAP and  FindNeighbors step both set the dimentions to 2:30(`dim = 2:30`). Is there a particular reason for not using the dimension 1?  
**Here is the link for mentioned vignette,**
[https://satijalab.org/signac/articles/pbmc_vignette.html#normalization-and-linear-dimensional-reduction](url)(https://satijalab.org/signac/articles/pbmc_vignette.html#normalization-and-linear-dimensional-reduction)

BTW, great analysis tool, it helped me a lot.

**Comment by timoast** [comment]
Hi, the first LSI dimension is highly correlated with sequencing depth in that case, as sometimes happens with scATAC-seq data. For this reason we discard the first component for downstream analysis. You can check this by running `FeatureScatter(object, "nCount_peaks", "LSI_1")`.
