### ISSUE TITLE
Value returned by signac::Footprint() 

### ISSUE THREAD

**Issue by Yijun-Tian** [timoast/signac#1064]
Hello,
Could you give more explanation about the positionEnrichment object returned by Footprint()? Specifically, about the interpretation of "i" and "x". If I want to check variability of TF enrichment across each cell, which number should I take into account?
Thanks

**Comment by timoast** [comment]
Running `Footprint()` stores a position x cell sparse matrix within the ChromatinAssay that contains the number of Tn5 insertion counts at each position for each cell, centered on the motif. The matrix also has the expected Tn5 insertion rate per base stored as an additional row named "expected", and the position of the motif itself one-hot encoded in a row called "motif". You can access it using the `GetAssayData()` function with `slot="positionEnrichment"`.

> Specifically, about the interpretation of "i" and "x"

This is part of the `dgCMatrix` object: https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/dgCMatrix-class.html
