### ISSUE TITLE
Unable to use CallPeaks function and reproduce joint analysis

### ISSUE THREAD

**Issue by aj088** [timoast/signac#1069]
Hi, I am trying to reproduce the joint ATAC and RNA analysis in vignette: https://satijalab.org/signac/articles/pbmc_multiomic.html. 
However, I am unable to use CallPeaks. The error message shows "Traceback (most recent call last):
  File "/opt/anaconda3/bin/macs2", line 653, in <module>
    main()
  File "/opt/anaconda3/bin/macs2", line 49, in main
    from MACS2.callpeak_cmd import run
  File "/opt/anaconda3/lib/python3.9/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/opt/anaconda3/lib/python3.9/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 242, in init MACS2.IO.Parser
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Warning in file(file, "rt") :
  cannot open file '/var/folders/79/yz2sgggd11n9c7kj2nws4w700000gp/T//Rtmpq0e4PA/SeuratProject_peaks.narrowPeak': No such file or directory
Error in file(file, "rt") : cannot open the connection"

My code is below, which is the same code as vignette except MACS2 path: 

```
counts <- Read10X_h5(file.path(multiome_dir, "/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5"))
fragpath <- file.path(multiome_dir,"pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz")

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"

pbmc <- CreateSeuratObject(
  counts = counts$`Gene Expression`,
  assay = "RNA"
)

pbmc[["ATAC"]] <- CreateChromatinAssay(
  counts = counts$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)

DefaultAssay(pbmc) <- "ATAC"

pbmc <- NucleosomeSignal(pbmc)
pbmc <- TSSEnrichment(pbmc)

VlnPlot(
  object = pbmc,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)

pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 100000 &
    nCount_RNA < 25000 &
    nCount_ATAC > 1000 &
    nCount_RNA > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 1
)
pbmc

peaks <- CallPeaks(pbmc, macs2.path = '/opt/anaconda3/bin/macs2')


```

Can you help me identify what might go wrong? Thank you very much!

**Comment by timoast** [comment]
Please see https://github.com/timoast/signac/issues/739 and https://github.com/timoast/signac/issues/1014
