### ISSUE TITLE
GeneActivity is error: Gene Activity Error in names(cell.convert) <- cells :

### ISSUE THREAD

**Issue by Liripo** [timoast/signac#1071]
I followed the pbmc tutorial: https://satijalab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data-1,but when I using SeuratDisk to save object , and then running GeneActivity will report this error. It cause by Fragment class cell names.
The test object is load from Seuratdisk. 
```r
> names(Fragments(pbmc)[[1]]@cells) |> head()
[1] "AAACGAAAGAGCGAAA-1" "AAACGAAAGAGTTTGA-1" "AAACGAAAGCGAGCTA-1"
[4] "AAACGAAAGTGCTGAG-1" "AAACGAAGTCAGGCTC-1" "AAACGAAGTGCCCGAT-1"
> names(Fragments(test)[[1]]@cells) |> head()
NULL
```

**Comment by timoast** [comment]
This is an issue with SeuratDisk that I previously reported here: https://github.com/mojaveazure/seurat-disk/issues/97
