### ISSUE TITLE
The vapply error strikes again: values must be length 1, but FUN(X[[2]]) result is length 0

### ISSUE THREAD

**Issue by LilianaLucca** [timoast/signac#1072]
Hello, I am running into a similar issue when trying to work with a list of Seurat objects, which I named seurats.
My code:
lapply(X = seurats, FUN = function(x){
  FeatureScatter(x, feature1 = "percent.mt", feature2 = "nFeature_RNA") +
    geom_density2d()
})

the answer:
Error in vapply(X = keyed.objects, FUN = function(x) { : 
values must be length 1,
but FUN(X[[2]]) result is length 0

The versions:
packageVersion("SeuratObject") 
[1] ‘4.0.4’
> packageVersion("Seurat")
[1] ‘4.1.0’

R is 4.1.2
RStudio is 2022.02.0
OS is MacOS Monterey

If this is a bug that it's going to take some time to fix, what can I do in the meantime?
Many thanks!

Lili

**Comment by timoast** [comment]
Please open this issue in the Seurat repo, since this does not involve any Signac functions

**Comment by LilianaLucca** [comment]
Apologies, new to github. Will do!
