### ISSUE TITLE
Issue of reading fragment files

### ISSUE THREAD

**Issue by 1213812138zqc** [timoast/signac#1079]
Hey @timoast,
Thanks so much for developing such a useful tool!
I just notice that many public scATAC-seq data only make the .fragments.tsv.gz file available but don't provide the .tsv.bgz.tbi file. I would like to know whether your tool can analysis this data without .tsv.bgz.tbi file or I miss some steps to process .fragments.tsv.gz file. Appreciate it!!

**codes:**
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Mmusculus.v79)
library(ggplot2)
library(patchwork)
set.seed(1234)
fragment.path <- 'E:/QiuchenZhao/DC27/scATAC/mice/data/GSM5362105_ATAC_WT_v12-mm10.fragments.tsv.gz'
mice_scATAC <- Fragments(
  object = mice_scATAC,
  file = fragment.path
)
**output:**
Error in CreateFragmentObject(path = fragment.path, cells = colnames(mice_scATAC),  : 
  Fragment file is not indexed.

**session info:**
 [1] patchwork_1.1.1            ggplot2_3.3.3             
 [3] SeuratObject_4.0.4         Seurat_4.1.0              
 [5] Signac_1.6.0               EnsDb.Mmusculus.v79_2.99.0
 [7] ensembldb_2.18.4           AnnotationFilter_1.18.0   
 [9] GenomicFeatures_1.46.5     AnnotationDbi_1.56.2      
[11] Biobase_2.52.0             GenomicRanges_1.44.0      
[13] GenomeInfoDb_1.30.1        IRanges_2.26.0            
[15] S4Vectors_0.30.0           BiocGenerics_0.38.0

**Comment by timoast** [comment]
This file is the [tabix index](http://www.htslib.org/doc/tabix.html), you can generate it by running `tabix -p bed <fragmentfile>`

**Comment by jad362** [comment]
Hi Tim,

I am reopening this issue as the proposed fix does not remove the issue and I would love some help. Are there hidden requirements for this to work? I have the original `fragments.tsv.gz` file and ran `tabix -p bed` successfully and created the tabix index file. `CreateFragmentObject` still returns the error that the file is not indexed for some reason.

**Comment by jad362** [comment]
Update for those who may encounter this as well. I checked my `fragments.tsv.gz` file against the example one in Signac's `extdata` and realized that the 10X fragments file contains the header while Signac expects the fragments file to begin with the actual data right away. I was able to fix this error by splitting up the typical fragments file into two files and indexing the new one using `tabix -p bed <new filename>`
