### ISSUE TITLE
RunSVD

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#108]
Hi Tim,

I have seen that with signac v0.2.2 i got different UMAPs than i was getting with previous versions, even after specifying reduction='umap-learn' and method='correlation'. Can this be due to the bug fix on RunSVD?

**Comment by timoast** [comment]
That's probably the reason, as the LSI results will be slightly different between v0.2.1 and >v0.2.1

You can check by re-running with the previous version.

**Comment by Brawni** [comment]
Hi Tim,
yes that seems to make the difference. I tested it using signac v0.2.1 and i could recover a more similar, although not identical UMAP and clustering. It also seems now that the label transfer from matching RNA sample is not as neat as it was using signac < v0.2.2. Here is an example of label transfer from RNA to ATAC for a sample im working on:
[rna_atac_integration_v.0.2.1_.pdf](https://github.com/timoast/signac/files/4304019/rna_atac_integration_v.0.2.1_.pdf)
[rna_atac_integration_v.0.2.2_.pdf](https://github.com/timoast/signac/files/4304020/rna_atac_integration_v.0.2.2_.pdf)

As you can see the labels aren't passed as neatly as in the previous version, and this is holding true also for another three scATAC samples with matching RNA im working on. Any thoughts?

Thanks a lot!

**Comment by timoast** [comment]
It's possible that the first component is now capturing sequencing depth and needs to be removed. You can check by running `FeatureScatter(object, 'nCount_ATAC', 'LSI_1')`. If there is a correlation you should run all downstream steps without the first component, eg `RunUMAP(object, reduction = 'lsi', dims = 2:30)`

**Comment by Brawni** [comment]
Hi Tim,

That seems to be the case:
[LSI1:2_vs_ncount.pdf](https://github.com/timoast/signac/files/4307590/LSI1.2_vs_ncount.pdf)

I will remove the first component and see how it looks!

**Comment by Brawni** [comment]
Hi Tim,

Removing the 1st LSI component fix the problem with the UMAP clustering on the atac data. However when i pass the labels from the rna I still have a noisier mapping. Should i also change the weight.reduction argument when running TransferData? If yes how do i do it? if I subset the reduction object it doesnt work:
 predicted.labels = TransferData(
    anchorset = transfer.anchors,
    refdata = lung.rna@active.ident,
    weight.reduction = signac_obj[['lsi']][,-1]
  )
Thank you!

**Comment by timoast** [comment]
You should change the `dims` argument in TransferData, eg:

```r
predicted.labels = TransferData(
anchorset = transfer.anchors,
refdata = lung.rna@active.ident,
weight.reduction = signac_obj[['lsi']],
dims = 2:30
)
```

**Comment by Brawni** [comment]
oh ok sorry got it!

**Comment by Brawni** [comment]
Hi Tim,
Actually when i do the RNA integration it still doesnt work as good as before. UMAPs and code are included.

`  lung.atac = readRDS (paste0(wd,sample_name, '_gene_activity_',celltype,'.rds'))
  lung.rna = readRDS (paste0(wd,sample_name,'_rna.rds'))

DefaultAssay(lung.atac) = 'RNA'
k.anchor=5; k.filter=50; k.score=10
  transfer.anchors = FindTransferAnchors(
    reference = lung.rna,
    query = lung.atac, features = VariableFeatures(object = lung.rna),
    reduction = 'cca', k.anchor = k.anchor,
                                           k.filter = k.filter,
                                           k.score = k.score, dims=2:30)
  predicted.labels = TransferData(
    anchorset = transfer.anchors,
    refdata = lung.rna@active.ident,
    weight.reduction = lung.atac[['lsi']],dims = 2:30
  )
lung.atac = AddMetaData(object = lung.atac, metadata = predicted.labels)
  lung.atac $predicted.id = as.factor (as.character(lung.atac $predicted.id))
 
  rna_cols = setNames (hue_pal()(length (levels(lung.rna@active.ident))), levels(lung.rna@active.ident))
  atac_cols = rna_cols[levels(lung.atac$predicted.id)]
  p_rna = DimPlot( object = lung.rna,cols =rna_cols, label = TRUE,  repel = TRUE) + ggtitle('scRNA-seq') + NoLegend()
  p_atac_pred = DimPlot(object = lung.atac,cols =atac_cols, group.by = 'predicted.id', label = FALSE,
    repel = TRUE)  + ggtitle('scATAC-seq') + NoLegend()
CombinePlots (list (p_rna,p_atac_pred))
  `
[rna_atac_int_test.pdf](https://github.com/timoast/signac/files/4309024/rna_atac_int_test.pdf)

**Comment by timoast** [comment]
You shouldn't set `dims=2:30` in the FindTransferAnchors step because that's a different dimension reduction (CCA between the RNA and gene activities), and the first CC is likely very important. You only need to set `dims=2:30` for steps that use the LSI (TransferData).

This should improve things, you could also try leaving the k.anchor, k.filter, k.score as their default values.

**Comment by Brawni** [comment]
Thanks for your prompt reply, i removed the dim argument in FindTransferAnchors and left the other settings as default but it didn't change much. I still can see the pink cluster on the left spilling to all the others, in particular on the green one. I tried further lowering the dims starting from 3-4 to 30 but it didn't change anything.

**Comment by Brawni** [comment]
wait...should i at some point specify dims also in the generation of the gene activity matrix?

My code for that is this:
`    gene.activities= FeatureMatrix(
      fragments = fragment.path,
      features = genebodyandpromoter.coords,
      cells = colnames(signac_obj),
      chunk = 20
    )
    genebodyandpromoter.coords$gene_name = mapIds(org.Hs.eg.db, genebodyandpromoter.coords$gene_id, "SYMBOL","ENTREZID")
    gene.key = genebodyandpromoter.coords$gene_name
    names(gene.key) = GRangesToString(grange = genebodyandpromoter.coords)
    rownames(gene.activities) = gene.key[rownames(gene.activities)]
    # add the gene activity matrix to the Seurat object as a new assay, and normalize it
    gene.activities = gene.activities[!is.na(rownames(gene.activities)),] 
    signac_obj[['RNA']] =CreateAssayObject(counts = gene.activities)
    signac_obj = NormalizeData(
      object = signac_obj,
      assay = 'RNA',
      normalization.method = 'LogNormalize',
      scale.factor = median(signac_obj$nCount_RNA)
    )`

**Comment by timoast** [comment]
There's no dims parameter for FeatureMatrix (there's no dimension reduction going on there)

**Comment by Brawni** [comment]
So do you have any other ideas as to why RNA label transfer doesnt perform as good now using v0.2.2?

**Comment by timoast** [comment]
No, that's quite strange. This change should only affect the anchor weighting, and considering you still get a nice UMAP from the LSI the weighting should not be that different. I can take a look if you're able to share the objects with me (lung.atac and lung.rna). You can send a download link to tstuart@nygenome.org.
