### ISSUE TITLE
overlay TF footprints for different feature sets

### ISSUE THREAD

**Issue by chromatinitis** [timoast/signac#1080]
Hi, The footprint functionality is a nice addition to an already loaded tool. 
What would be even more useful for me is to be able to superimpose in one graph footprints of a given motif in a given cell population(s) that have been computed based on different peak sets. Or is this something that's possible in the current version?
Thanks so much.

**Comment by timoast** [comment]
You can do this using the `regions` parameter in `Footprint()`, you will just need to create a set of motif regions that you're interested in

**Comment by chromatinitis** [comment]
Hi,

I'm reopening this because I wasn't successful in trying to implement your suggestion.

On a single plot, I am aiming to overlay:
footprint around motif X from cells Y computed from peakset.1,
footprint around motif X from cells Y computed from peakset.2,

```
instances.1 <- matchMotifs(pwm, StringToGRanges(peakset.1), genome = "mm10", out='positions')
instances.2 <- matchMotifs(pwm, StringToGRanges(peakset.2), genome = "mm10", out='positions')

integrated <- Footprint(
  object =integrated,
  key=clst,
  assay='mac.peaks',
  genome = BSgenome.Mmusculus.UCSC.mm10,
  regions=c(instances.1, instances.2)
)
```
Running the above gives:

  |                                                  | 0 % ~calculating  Error in as.vector(x, mode) : 
  coercing an AtomicList object to an atomic vector is supported only for
  objects with top-level elements of length <= 1
In addition: Warning message:
In if (any(strand(x = x) == "*")) { :
  the condition has length > 1 and only the first element will be used

Running `instances.1` without `instances.2` gives the same error.

Would you be able to suggest a workaround? I can provide more code if needed.

Thanks.
