### ISSUE TITLE
Error in integrating chromatin assay

### ISSUE THREAD

**Issue by carversh** [timoast/signac#1083]
Sorry for the continual errors, but I got another error when trying to integrate rna seq and atac.

After this line of code: 
`gene.activities <- GeneActivity(morab.atac, features = VariableFeatures(morab.rna))`

I am getting the following error: 
Error in SingleFeatureMatrix(fragment = fragments[[x]], features = features, : No matching chromosomes found in fragment file.
Traceback:

1. GeneActivity(morab.atac, features = VariableFeatures(morab.rna))
2. FeatureMatrix(fragments = frags, features = transcripts, cells = cells, 
 .     verbose = verbose, ...)
3. sapply(X = obj.use, FUN = function(x) {
 .     SingleFeatureMatrix(fragment = fragments[[x]], features = features, 
 .         cells = cells, sep = sep, verbose = verbose, process_n = process_n)
 . })
4. lapply(X = X, FUN = FUN, ...)
5. FUN(X[[i]], ...)
6. SingleFeatureMatrix(fragment = fragments[[x]], features = features, 
 .     cells = cells, sep = sep, verbose = verbose, process_n = process_n)
7. stop("No matching chromosomes found in fragment file.")

Here are the first few lines of my fragments.tsv.gz file:
0 ['chr1', '10007', '10124', 'ACTTTCACAAGCAACG-13', '1']
1 ['chr1', '10007', '10192', 'AGGACGAGTGGACAGT-14', '1']
2 ['chr1', '10007', '10198', 'TAATTCCAGAACTCCT-14', '1']
3 ['chr1', '10007', '10290', 'TCCCACACAACTACTG-14', '1']
4 ['chr1', '10007', '10296', 'CAGCTAAAGGGTCCCT-14', '1']
5 ['chr1', '10007', '10313', 'CTGTATTAGTTGACAA-14', '1']
6 ['chr1', '10007', '10394', 'GCGGAAAAGTCGAGCA-8', '1']
7 ['chr1', '10007', '10401', 'CTCAACCCAAGGAGGG-17', '1']
8 ['chr1', '10011', '10142', 'CAGCCTTAGGCCTCGT-8', '1']
9 ['chr1', '10012', '10355', 'TACCTATTCTATCTAC-8', '1']

Additionally, here is what I'm using to make the chromatin assay:
```
library('Signac')
library('Seurat')
library('Matrix')
library("data.table")
library('SeuratDisk')
library('ggplot2')
library('bcbioRNASeq')
library('GenomicRanges')
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
# reading in processed atac matrix
m <- readMM(file='matrix.mtx')


#m <- as(object = m, Class = "dgCMatrix")
m <- m*1

# creating barcode and feature labels
barcodes <- fread(file='/barcodes_atac.csv', header=F)[[1]]
features <- fread(file='peaks.csv', header=F)[[1]]

# adding these feature and barcode names to the matrix
rownames(m) <- features
colnames(m) <- barcodes

# Define GRanges object using the features
granges <- StringToGRanges(features, sep = c(":", "-"))
granges <- granges[as.vector(seqnames(granges) %in% standardChromosomes(granges)),]

# Create Seurat Chromatin Assay
chrom_assay <- CreateChromatinAssay(
  counts = m,
  sep = c(":", "-"),
  ranges = granges,
  #genome = 'hg38',
  fragments = 'fragments.tsv.gz',
  min.cells = 0,
  min.features = 0,
  annotation = annotation
)

# read in metadata
metadata <- read.csv(
  file = "snATAC_metadta.csv",
  header = TRUE,
  row.names = 1
)

morab.atac <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)

```

**Comment by carversh** [comment]
I am either (1) using the incorrect annotations or (2) I am importing the sc rna seq from disk (I don't think this is the issue)

**Comment by timoast** [comment]
Since your chromosome names are UCSC-style you need to change the seqlevels style for the annotations: `seqlevelsStyle(annotation) <- "UCSC"`

**Comment by carversh** [comment]
Got it -- thank you so so much!
