### ISSUE TITLE
integrating atac-seq with peaks from multiome kit

### ISSUE THREAD

**Issue by afcmalone** [timoast/signac#1084]
Hi,
I would like to know if it is possible to integrate multiple ATAC-seq samples with multiple multiome (peaks) samples?
I realize there is a there is a vignette that integrates one atac-seq dataset with one multiome dataset based on features found in the multiome object.

thanks
Andrew

**Comment by timoast** [comment]
It's no different from merging or integrating multiple scATAC datasets, you can follow what's shown here:
https://satijalab.org/signac/articles/merging.html
https://satijalab.org/signac/articles/integrate_atac.html
