### ISSUE TITLE
Segmentation Fault with FindTransferAnchors

### ISSUE THREAD

**Issue by justin-malin** [timoast/signac#109]
Hi Tim, 

I'm trying to get up to speed with SIgnac and have found the tutorials and this GitHib page very helpful. However, I haven't been able to find a workaround for the following issue. Would you have any insights on how to get the following code to work? Specifically, it is throwing a Segmentation Fault at FindTransferAnchors. The script is being run on a node with 100G RAM requested. The administrator assured me that the job is not running out of memory.

Thanks,
Justin

_**The script:**_

pbmc.2 <- readRDS('../pbmc.2_4-assays')
immune.combined.KLF6.KO <- readRDS('../immune.combined.KLF6.KO_includes_contaminants')

DefaultAssay(pbmc.2) <- 'RNA'

pbmc.2
immune.combined.KLF6.KO

transfer.anchors <- FindTransferAnchors(reference = immune.combined.KLF6.KO, query = pbmc.2, reduction = 'cca',dims = 1:40)

_**output from the run**_ :

(base) [malinjl@cn0864 src]$ Rscript transfer_anchor.R 

No methods found in package ‘IRanges’ for request: ‘score’ when loading ‘TFBSTools’
Loading required package: BSgenome
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: GenomicRanges
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading required package: rtracklayer
Loading required package: ensembldb
Loading required package: GenomicFeatures
Loading required package: AnnotationDbi
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: AnnotationFilter

Attaching package: 'ensembldb'

The following object is masked from 'package:stats':

    filter

Attaching package: 'Matrix'

The following object is masked from 'package:S4Vectors':

    expand

The following object is masked from 'package:TFBSTools':

    Matrix

Attaching package: 'dplyr'

The following objects are masked from 'package:ensembldb':

    filter, select

The following object is masked from 'package:AnnotationDbi':

    select

The following object is masked from 'package:Biobase':

    combine

The following objects are masked from 'package:Biostrings':

    collapse, intersect, setdiff, setequal, union

The following object is masked from 'package:XVector':

    slice

The following objects are masked from 'package:GenomicRanges':

    intersect, setdiff, union

The following object is masked from 'package:GenomeInfoDb':

    intersect

The following objects are masked from 'package:IRanges':

    collapse, desc, intersect, setdiff, slice, union

The following objects are masked from 'package:S4Vectors':

    first, intersect, rename, setdiff, setequal, union

The following objects are masked from 'package:BiocGenerics':

    combine, intersect, setdiff, union

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

Attaching package: 'tidyr'

The following objects are masked from 'package:Matrix':

    expand, pack, unpack

The following object is masked from 'package:S4Vectors':

    expand

Attaching package: 'reshape2'

The following object is masked from 'package:tidyr':

    smiths

********************************************************
Note: As of version 1.0.0, cowplot does not change the
  default ggplot2 theme anymore. To recover the previous
  behavior, execute:
  theme_set(theme_cowplot())
********************************************************

An object of class Seurat 
676424 features across 1600 samples within 4 assays 
Active assay: RNA (21553 features)
 3 other assays present: peaks, unifiedPeaks, reducedPeaks
 2 dimensional reductions calculated: lsi, umap
An object of class Seurat 
20067 features across 1497 samples within 1 assay 
Active assay: RNA (20067 features)
 2 dimensional reductions calculated: pca, umap
Running CCA

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: Standardize(mat = object1, display_progress = FALSE)
 2: RunCCA.default(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
 3: RunCCA(object1 = data1, object2 = data2, standardize = TRUE,     num.cc = num.cc, verbose = verbose, )
 4: RunCCA.Seurat(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
 5: RunCCA(object1 = reference, object2 = query, features = features,     num.cc = max(dims), renormalize = FALSE, rescale = FALSE,     verbose = verbose)
 6: FindTransferAnchors(reference = immune.combined.KLF6.KO, query = pbmc.2,     reduction = "cca", dims = 1:40)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault

**Comment by timoast** [comment]
What's the output of
```
length(intersect(rownames(pbmc.2), rownames(immune.combined.KLF6.KO)))
```

**Comment by justin-malin** [comment]
Thanks, Tim, for your quick reply.

length(intersect(rownames(pbmc.2), rownames(immune.combined.KLF6.KO)))
[1] 0

Also:

head(rownames(immune.combined.KLF6.KO))
[1] "chr1-3205901-3673498" "chr1-4290846-4411241" "chr1-4490931-4499354"
head(rownames(pbmc.2))
[4] "chr1-4773206-4787739" "chr1-4805788-4848410" "chr1-4805892-4886770

What's confusing is that the active assay for both objects is 'RNA'. 
immune.combined.KLF6.KO only holds scRNA-Seq data so I'm not sure where these chromosomal coordinates came from.

And finally:

length(rownames(immune.combined.KLF6.KO))
[1] 20067
length(rownames(pbmc.2))
[1] 21553

**Comment by timoast** [comment]
It looks like you haven't named the genes in your RNA assay correctly for the ATAC-seq experiment.

Did you follow the instructions here: https://satijalab.org/signac/articles/pbmc_vignette.html#create-a-gene-activity-matrix ?

**Comment by justin-malin** [comment]
Ah, I did but I completely missed the error that was thrown because of a typo. Thanks again for your help!
Justin
