### ISSUE TITLE
Reopening Overlay TF footprints for different feature sets (#1080)

### ISSUE THREAD

**Issue by chromatinitis** [timoast/signac#1098]
Hi,

I'm reopening this because I wasn't successful in trying to implement your suggestion.

On a single footprint plot, I am aiming to overlay:
footprint around motif X from cells Y computed from peakset.1,
footprint around motif X from cells Y computed from peakset.2,

```
instances.1 <- matchMotifs(pwm, StringToGRanges(peakset.1), genome = "mm10", out='positions')
instances.2 <- matchMotifs(pwm, StringToGRanges(peakset.2), genome = "mm10", out='positions')

integrated <- Footprint(
  object =integrated,
  key=clst,
  assay='mac.peaks',
  genome = BSgenome.Mmusculus.UCSC.mm10,
  regions=c(instances.1, instances.2)
)
```
Running the above gives:

  |                                                  | 0 % ~calculating  Error in as.vector(x, mode) : 
  coercing an AtomicList object to an atomic vector is supported only for
  objects with top-level elements of length <= 1
In addition: Warning message:
In if (any(strand(x = x) == "*")) { :
  the condition has length > 1 and only the first element will be used

Running `instances.1` without `instances.2` gives the same error.

Would you be able to suggest a workaround? I can provide more code if needed.

Thanks.

**Comment by timoast** [comment]
Here `instances.1` and `instances.2` will be a `GRangesList` object with one list entry for each PWM, which is not quite what you need here. You need to extract the motif positions for the motif you're interested in from the `GRangesList` object, and combine `instances.1` and `instances.2` (motif instances in different peak sets) using a list rather than `c()`. For example:

```r
instances.1 <- matchMotifs(pwm, StringToGRanges(peakset.1), genome = "mm10", out='positions')
instances.2 <- matchMotifs(pwm, StringToGRanges(peakset.2), genome = "mm10", out='positions')

ins.use <- list(instances.1[[1]], instances.2[[1]])

integrated <- Footprint(
  object =integrated,
  key=c("peakset1", "peakset2"),
  assay='mac.peaks',
  genome = BSgenome.Mmusculus.UCSC.mm10,
  regions=ins.use
)
```

**Comment by chromatinitis** [comment]
Thanks. That makes sense. I can run `Footprint` on  `instances.1[[1]]`.

But when I do

```
ins.use <- list(instances.1[[1]], instances.2[[1]])

integrated <- Footprint(
  object =integrated,
  key=c("peakset1", "peakset2"),
  assay='mac.peaks',
  genome = BSgenome.Mmusculus.UCSC.mm10,
  regions=ins.use
)
```

 it gives the following error:

  |                                                  | 0 % ~calculating  Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'width' for signature '"list"'


> ins.use
[[1]]
GRanges object with 230 ranges and 1 metadata column:
        seqnames              ranges strand |     score
           <Rle>           <IRanges>  <Rle> | <numeric>
    [1]     chr1   12991194-12991204      + |   14.7689
    [2]     chr1 131527839-131527849      + |   17.2206
    [3]     chr1 134079206-134079216      + |   14.5075
    [4]     chr1 153549861-153549871      + |   15.6162
    [5]     chr1 172501157-172501167      + |   14.7259
    ...      ...                 ...    ... .       ...
  [226]     chr9   95512035-95512045      + |   14.7813
  [227]     chrX   53269932-53269942      + |   14.7689
  [228]     chrX   74281848-74281858      + |   14.1017
  [229]     chrX   74282984-74282994      + |   14.7828
  [230]     chrX   99136010-99136020      + |   15.6939

  seqinfo: 20 sequences from an unspecified genome; no seqlengths

[[2]]
GRanges object with 63 ranges and 1 metadata column:
       seqnames              ranges strand |     score
          <Rle>           <IRanges>  <Rle> | <numeric>
   [1]    chr10 128695507-128695517      + |   14.9769
   [2]    chr10   75932512-75932522      + |   14.7894
   [3]    chr10   79555172-79555182      + |   14.7736
   [4]    chr10   79767156-79767166      + |   17.2049
   [5]    chr10   81037168-81037178      + |   17.2267
   ...      ...                 ...    ... .       ...
  [59]     chr9 110880153-110880163      + |   14.7894
  [60]     chr9 114401076-114401086      + |   14.7894
  [61]     chr9 114401993-114402003      + |   15.7000
  [62]     chr9   44134585-44134595      + |   14.7736
  [63]     chr9   44136361-44136371      + |   14.3927

  seqinfo: 20 sequences from an unspecified genome; no seqlengths

**Comment by timoast** [comment]
Should be fixed now on the develop branch

**Comment by chromatinitis** [comment]
Great, thanks!

Below is what I get, when grouping by dataset. 
Is there any way with the current tool to get the footprint for peakset1 overlaid in the same panel as peakset2 to allow for a head-to-head comparison of the two peak sets? Something like  `group.by=feature` .

![image](https://user-images.githubusercontent.com/98503489/165553415-66a39b2f-bb20-49b8-bfba-a2e2ef98647f.png)

**Comment by timoast** [comment]
No not currently, I think you'll have to extract the data from the object and plot it yourself. The data is stored in the `positionEnrichment` slot of the assay

**Comment by chromatinitis** [comment]
Ah, good to know.
Thanks again!!

**Comment by ZayaAyush** [comment]
Could you able to show how to make "peakset.1 and peakset.2", please? I wanted to make the peaked/defined region.
