### ISSUE TITLE
Using BSgenome with 'GetGRangesFromEnsDb'

### ISSUE THREAD

**Issue by ashwinikumarkulkarni** [timoast/signac#1099]
I am trying to use "BSgenome.Mmusculus.UCSC.mm10" for my ATAC-seq analysis. How can I get it to work with "GetGRangesFromEnsDb" command from the ATAC-seq pipeline? Thanks!

**Comment by timoast** [comment]
`GetGRangesFromEnsDb` works with an EnsDb object (which is a gene annotation), not a BSgenome object (which is the genome sequence). You need to use the `EnsDb.Mmusculus.v79` object

**Comment by ashwinikumarkulkarni** [comment]
Thanks! Can I create a gene annotation (EnsDb object) using GTF that I have used for 'cellranger count'? Thanks again!

**Comment by ashwinikumarkulkarni** [comment]
Will something like this work?
`
gtf <- rtracklayer::import("my_genes.gtf")
gene.coords <- gtf[gtf$type == "gene"]
seqlevelsStyle(gene.coords) <- "UCSC"
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = "coarse")
`

**Comment by timoast** [comment]
Yes, please see https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-

**Comment by ashwinikumarkulkarni** [comment]
Thanks a lot!
