### ISSUE TITLE
Non Ensdb genomes

### ISSUE THREAD

**Issue by cuperusj** [timoast/signac#11]
Arabidopsis does not have a ensemblDB library like mouse and human do. Do you have a grasp on how to make such a thing, it is not obvious to me.

stuck at this point:
ene.coords <- genes(EnsDb.Hsapiens.v75, filter = ~ gene_biotype == "protein_coding")

or if you have an easy bypass using a gtf

**Comment by timoast** [comment]
Hi, this is what you'd do for a gtf file:

```r
gtf <- rtracklayer::import('genes.gtf')
gene.coords <- gtf[gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'UCSC'
genebody.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
genebodyandpromoter.coords <- Extend(x = gene.coords, upstream = 2000, downstream = 0)
```
