### ISSUE TITLE
Select certain clusters in featureplots function

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#110]
Hello @timoast ,

First, I would like to thank you for your excellent work. You have really help me analyzing scATACseq data.
 
I am writing to you, because I need to generate a feature plot with certain clusters, excluding the others. I have tried generating a vector with the cluster names and using **cells = **. But it doesn't work. Can you help me? I would appreciate any suggestion.

Best,

Aitor

**Comment by timoast** [comment]
Hi Aitor, you can use the `cells` parameter in FeaturePlot to plot a subset of cells. 

Here's an example using the `pbmc_small` dataset:

```r
cells <- WhichCells(pbmc_small, idents = 1)
FeaturePlot(pbmc_small, features = "MS4A1", cells = cells)
```

**Comment by Aitor91** [comment]
That helps me a lot. Thank you for the suggestion and help.

Aitor
