### ISSUE TITLE
what's the difference between run_cicero in all cell types and in each cell type respectively?

### ISSUE THREAD

**Issue by l-magnificence** [timoast/signac#1105]
If a single cell ATAC dataset have two clusters, when we run cicero in dataset overall we get conns
```
atac_cds<- as.cell_data_set(x = atac)
atac_cicero <- make_cicero_cds(atac_cds, reduced_coordinates = reducedDims(atac_cds)$UMAP)
conns<- run_cicero(atac_cicero , genomic_coords = genome.df, sample_num = 100)
```
Also we can run cicero in each cluster respectively and get conns1 of cluster1 and conns2 of cluster2. for example:
```
atac_sub<-subset(atac,type == cluster1)
atac_sub_cds <- as.cell_data_set(x = atac_sub)
atac_sub_cicero <- make_cicero_cds(atac_sub_cds, reduced_coordinates = reducedDims(atac_sub_cds)$UMAP)
conns1<- run_cicero(atac_sub_cicero, genomic_coords = genome.df, sample_num = 100)
```
However the coaccess score of a pair of peaks is 3 in conns, same pair of peaks in conns1 is -2
Why this is much different? If we want to konw cluster-specific conns, we should not run cicero in all dataset?

**Comment by timoast** [comment]
Please see https://github.com/timoast/signac/discussions/949
