### ISSUE TITLE
Using my interested da peaks in `FindMotifs()` turns into an error.

### ISSUE THREAD

**Issue by jiangpuxuan** [timoast/signac#1109]
Here is my code:

```
de.motif <- rownames(mydata)[1:50]
enriched.motifs <- FindMotifs(
  object = mydata,
  features = de.motif,
)
```
```
head(enriched.motifs)
```
<img width="540" alt="1651584391(1)" src="https://user-images.githubusercontent.com/81287604/166461420-54676a6f-4051-4a0a-aca2-3346fba07716.png">

Everything is OK. 

And I tried to use my interested da peaks in `enriched.motifs` :

```
enriched.motifs <- FindMotifs(
  object = mydata,
  features = the da peaks in some interested cells ,
)
```
But the error is:
```
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian", : 'x' contains missing values
```
Thank you for your help!

**Comment by timoast** [comment]
Can you show the DA peaks that cause the error? First few lines and output of `dim`

**Comment by jiangpuxuan** [comment]
<img width="509" alt="1651631710(1)" src="https://user-images.githubusercontent.com/81287604/166616205-27c460fa-109d-4b18-9db7-a7358a15fdac.png">
`de.motif` did not cause the error, but `interested da peaks` did.

**Comment by jiangpuxuan** [comment]
> Can you show the DA peaks that cause the error? First few lines and output of `dim`

Now I ran `chromeVar`  and found differentially activating motifs , following the [https://satijalab.org/signac/articles/motif_vignette.html](url).

But I still want to know the cause of this error.

**Comment by timoast** [comment]
How many peaks are in the set of peaks that causes the error?

**Comment by jiangpuxuan** [comment]
> How many peaks are in the set of peaks that causes the error?

About 120.

**Comment by pabloswfly** [comment]
Curious about the resolution of this issue, I am encountering the same error.

**Comment by jiangpuxuan** [comment]
> Curious about the resolution of this issue, I am encountering the same error. The peak data in my specific case looks like this:
> 
> ```r
> top.da.peak <- rownames(da_peaks[da_peaks$p_val < 0.005,])
> head(top.da.peak)
> length(top.da.peak)
> dim(da_peaks)
> 
> ----------------------------------------------------------------
> 
> 'chr3-14451939-14453443''chr2-42903457-42904464''chr18-58364914-58365919''chr4-84417769-84418850''chr1-17602697-17603858''chr1-91585801-91586419'
> 
> 17242
> 
> 18728  7
> ```

Could you ran chromeVar and found differentially activating motifs?

**Comment by pabloswfly** [comment]
yes I could, as they are two independent processes.

**Comment by jiangpuxuan** [comment]
> yes I could, as they are two independent processes.

Have you calculated the `background` in `Findmotifs()`? 

Or I thought that our interested `da.peaks` are not informative enough so that `Findmotifs()` get errors.

**Comment by pabloswfly** [comment]
My error occurs after calculating the background regions, during the matching of GC content:

```R
Selecting background regions to match input sequence characteristics

Matching GC.percent distribution

Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian", : 'x' contains missing values
Traceback:

1. FindMotifs(sub_endocrine, features = top.da.peak)
2. MatchRegionStats(meta.feature = mf.choose, query.feature = mf.query, 
 .     regions = features, n = background, verbose = verbose, ...)
3. density(x = query.feature[[featmatch]], kernel = "gaussian", 
 .     bw = 1)
4. density.default(x = query.feature[[featmatch]], kernel = "gaussian", 
 .     bw = 1)
5. stop("'x' contains missing values")
```

I had some peaks with zero counts in all cells in my object, but after filtering these rows out, I still get the same error.

**Comment by rLannes** [comment]
I did, and I managed to run chromvar, but the Find Motifs function give me the same error as you.  The thing that trouble me is if I use a subset of DE peaks it is fine. That is why I would want to try to subset only the peaks with at least some counts.

```
enriched.motifs <- FindMotifs(
  object = integrated,
  features = rownames(de)
)
Selecting background regions to match input sequence characteristics
Matching GC.percent distribution
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  'x' contains missing values

```


```
enriched.motifs <- FindMotifs(
  object = integrated,
  features = rownames(de)[1:100]
)
Selecting background regions to match input sequence characteristics
Matching GC.percent distribution
Testing motif enrichment in 100 regions
```

**Comment by rLannes** [comment]
I got the solution to my issue. Some peaks in the Differential peak object have an extension "chrX-131703821-131705582.1" removing the .1 solve the issue for me, hope this will help others.

**Comment by timoast** [comment]
Thanks @rLannes, I've added a check to `FindMotifs()` for features that are not present in the assay that should resolve these issues.

**Comment by ElyasMo** [comment]
I think the answer is, by:

tops <- list()
for (clust in unique(da_peaks.heart$cluster)) {
  set <- subset(da_peaks.heart,cluster==clust)
  tops[[clust]] <- rownames(set[set$p_val < 0.01 & set$pct.1 > 0.2, ])
}

you are removing all the fragments for some of your celltypes. So you will have zero fragment for some of the celltypes in your list. This would be the rout of the error, I assume.  Maybe decrease the set$pct.1 > 0.2 threshold to allow more fragments be included
