### ISSUE TITLE
Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters?

### ISSUE THREAD

**Issue by matteozoia4** [timoast/signac#1112]
Dear Satijalab,

My aim is to run a peak calling per clustered regions based on the variable "celltype" in the metadata list of the object "heart".
With the final aim to call peaks specific per each cluster in a given region.
It seems that no peaks per cell type are found.

Many thanks for your help!

Code :

`DefaultAssay(heart) <- "ATAC" Macs2PeaksCulsters <- CallPeaks(heart, group.by = "celltype", macs2.path = "/Users/mz20v137/opt/anaconda3/envs/htseq_pipelines/bin/macs2")`

`Macs2PeaksCulsters <- keepStandardChromosomes(Macs2PeaksCulsters, pruning.mode = "coarse") Macs2PeaksCulsters <- subsetByOverlaps(x = Macs2PeaksCulsters, ranges = blacklist_mm10, invert = TRUE)`

`macs2_counts_Clusters <- FeatureMatrix( fragments = Fragments(heart), features = Macs2PeaksCulsters, cells = colnames(heart) )`

`heart[["Macs2PeaksClusters"]] <- CreateChromatinAssay( counts = macs2_counts_Clusters, fragments = frag.file, annotation = annotations )`

`DefaultAssay(heart) <- "Macs2PeaksClusters" peak_plot <- PeakPlot( heart, region = "chr3-66337001-67337000", assay = NULL, peaks = NULL, group.by = 'celltype' )`

Warning message:

`In PeakPlot(heart, region = "chr3-66337001-67337000", assay = NULL, : Requested grouping variable not found`

**Comment by timoast** [comment]
What's the output of: `"celltype" %in% colnames(heart[[]])` ?

**Comment by matteozoia4** [comment]
Here:


> "celltype" %in% colnames(heart[[]])

[1] TRUE


________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 6. maggio 2022 15:20:17
A: timoast/signac
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [timoast/signac] Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters? (Issue #1112)


What's the output of: "celltype" %in% colnames(heart[[]]) ?

**Comment by timoast** [comment]
The grouping variable for `PeakPlot()` needs to be in the feature metadata, not the cell metadata, since the function is plotting features rather than cells

**Comment by matteozoia4** [comment]
Many thanks Tim for your time,



How should I approach my object to overcome this issue?

(Or eventually change the code called)


I am new and learning about how to read between parameters and features.


Many thanks.




________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 6. maggio 2022 18:56:26
A: timoast/signac
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [timoast/signac] Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters? (Issue #1112)


The grouping variable for PeakPlot() needs to be in the feature metadata, not the cell metadata, since the function is plotting features rather than cells

**Comment by timoast** [comment]
You can directly plot the output of macs2, which will have a `peak_called_in` column if setting the `group.by` parameter:

```r
PeakPlot(heart, region = "chr3-66337001-67337000", group.by = "peak_called_in")
```

**Comment by matteozoia4** [comment]
I have one assay Macs2 and a second one named Macs2PeaksClusters (used group.by = "cellytpe").


I am then obliged to select the assay, am  assuming correct?



DefaultAssay(heart) <- 'Macs2PeaksClusters'

PeakPlot(heart, region = "chr3-66337001-67337000", group.by = "peak_called_in")


Many thanks for all your time! Highly appreciated!


________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 6. maggio 2022 19:15:42
A: timoast/signac
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [timoast/signac] Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters? (Issue #1112)


You can directly plot the output of macs2, which will have a peak_called_in column if setting the group.by parameter:

PeakPlot(heart, region = "chr3-66337001-67337000", group.by = "peak_called_in")

**Comment by timoast** [comment]
The assay doesn't matter since the genomic ranges shown are coming from the manually-supplied ranges in the `peaks` parameter

**Comment by matteozoia4** [comment]
Sorry to bother again... may it be that the peak_called_in has a different name n my peaks parameters?


ERROR

In PeakPlot(heart, region = "chr3-66337001-67337000", group.by = "peak_called_in") :

  Requested grouping variable not found


Zoia Matteo, Ph.D. Student
Gene Regulation & Cardiac Development

Marco Osterwalder Laboratory
Department for BioMedical Research (DBMR)
University of Bern
Lab 369, Murtenstrasse 28
CH - 3008 Bern
SWITZERLAND

________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 6. maggio 2022 19:25:55
A: timoast/signac
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [timoast/signac] Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters? (Issue #1112)


The assay doesn't matter since the genomic ranges shown are coming from the manually-supplied ranges in the peaks parameter

**Comment by timoast** [comment]
Need to set `peaks  = Macs2PeaksCulsters`

**Comment by matteozoia4** [comment]
Many thanks Tim!


Zoia Matteo, Ph.D. Student
Gene Regulation & Cardiac Development

Marco Osterwalder Laboratory
Department for BioMedical Research (DBMR)
University of Bern
Lab 369, Murtenstrasse 28
CH - 3008 Bern
SWITZERLAND

________________________________
Da: Tim Stuart ***@***.***>
Inviato: venerdì, 6. maggio 2022 19:41:05
A: timoast/signac
Cc: Zoia, Matteo (DBMR); Author
Oggetto: Re: [timoast/signac] Macs2 PeakCalling On Single Clusters - Error - No peaks assigned to clusters? (Issue #1112)


Need to set peaks = Macs2PeaksCulsters
