### ISSUE TITLE
FindMarkers on  scATAC-seq using normalized Tn5 cuts?

### ISSUE THREAD

**Issue by ccshao** [timoast/signac#1119]
I have a quite naive but anyway would like to confirm that the `FindMarkers` in `Signac` using the TF-IDF normlized **Tn5 Cuts counts** from Peak/Cell matrix provided by 10x, but **NOT** based on the fragment file?

Actually I saw a related note here:
https://github.com/timoast/signac/issues/373#issuecomment-750450454

The reason why I asked is that I think `ArchR` is using the fragments as the basic mearements (converted to tilematrix) and then performed the TF-IDF normalization. Differentially accessible peaks are computated subsequently. In the vignette I didn't find how they use Tn5 cuts at all.  To me Signac and ArchR are quite different from the very beginning.

These two approaches also give us quite different results on clustering an UMAP.

Thanks!

**Comment by timoast** [comment]
I think the issue you've linked to gives the answer to this question

Whether cut sites or fragments are counted to create the matrix depends on the method used. Cellranger counts cut sites, Signac currently counts fragments.

**Comment by ccshao** [comment]
> Cellranger counts cut sites, Signac currently counts fragments.

Now I get more confused. Wouldn't the data used in Signac be the cut sites from Peak/Cell matrix? 
I mean, `GetAssayData(object = pbmc, slot = "counts")` will give the cuts in peak region?

**Comment by timoast** [comment]
I'm referring to the `FeatureMatrix()` function in Signac counting fragments rather than cut sites
