### ISSUE TITLE
TF score

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#112]
Hello @timoast ,

Thank you for your excellent vignette about TF analysis. It is really helpful. 

However, reading some articles about scATACseq where they use ChromVar to analyze TF motifs,  they say that ChromVar gives them a score (z-score) which they use to compare within different conditions (This is one example https://www.cell.com/cell-reports/pdf/S2211-1247(19)31151-9.pdf).

In your case, I have followed your script about ChromVar, but I do not see any reference about z-score. In stead you have described a differential activity score. Is that the same? Any explanation would be appreciated. 

Thank you again for your excellent work.

Aitor

**Comment by timoast** [comment]
It's the same thing (activity score = z-score), the function in Signac just runs chromVAR and stores the output as a new assay.
