### ISSUE TITLE
AddMotifs using own GTF reference

### ISSUE THREAD

**Issue by MoritzTh** [timoast/signac#1120]
Hi Tim, 
this is a reference to [issue 1107](https://github.com/timoast/signac/issues/1107) (see this issue for code and sessionInfo).
I am still having problems with the ```AddMotifs```function, likely because of a mismatch between chromosome names in the genome object vs the fragment file. I did rename the chromosome names in the reference accordingly, but I am still getting the error. Do you have any idea why? Thanks in advance!

**Comment by timoast** [comment]
I'd suggest running `getSeq(BSgenome.Mfascicularis.NCBI.5.0.renamed, granges(macaca))` and seeing which range/s in the object are causing an error, and then removing the problematic ranges or working out why they're there in the first place

**Comment by MoritzTh** [comment]
Running ```getSeq(BSgenome.Mfascicularis.NCBI.5.0.renamed, granges(macaca))```throws the error:
```
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence "MFA2"
  ```
Strangely, I cant see the chromosome "MFA2" anywhere in ```BSgenome.Mfascicularis.NCBI.5.0.renamed``` or my Signac object...

**Comment by timoast** [comment]
This doesn't seem like it's an issue with Signac, I'd suggest asking a question on the Bioconductor support page and hopefully someone there can help: https://support.bioconductor.org/
