### ISSUE TITLE
How can I integrate samples sequenced from different years?

### ISSUE THREAD

**Issue by caodudu** [timoast/signac#1122]
I have four samples sequenced in 2018 and  two samples sequenced in 2020. All six samples were taken from the pancreas. I merged the four samples from 2018 for analysis and found that I could annotate the correct cells. The merged 2020 sample was fine, too. 
However, when I try to merge the samples of the two years together, biologically identical cell populations are far apart in UMAP. I found that the number of peak features in the two samples of 2020 was much larger than that of the four samples of 2018.

_> dim(data2020_1)
[1] 108200   1479
> dim(data2020_2)
[1] 142330   1972

> dim(data2018_1)
[1] 54698  1418
> dim(data2018_2)
[1] 38787  1787
> dim(data2018_3)
[1] 67702  1168
> dim(data2018_4)
[1] 34764   735_

Could this be the reason why the samples from the two years on UMAP are so far apart?
Now I want to integrate the samples of two years together. How should I deal with it?

**Comment by timoast** [comment]
Please see the [merge](https://satijalab.org/signac/articles/merging.html) and [integration](https://satijalab.org/signac/articles/integrate_atac.html) vignettes
