### ISSUE TITLE
macs2 callpeaks function group.by bug 

### ISSUE THREAD

**Issue by Sabdelhamid98** [timoast/signac#1123]
hello , i'm currently trying to do a peak calling with the macs2 function. I want to use the function group.by as a group variable. However when i try to run the function it doesn't work . 

First i create a metadata columns 'cell_types' who correspond to my indents i have compute with my rna assay 

```
only_STERO$cell_types=Idents(only_STERO)
[ reached getOption("max.print") -- omitted 706 entries ]
14 Levels: Endothelial Cells Male specific Medulla Male Fasciculata Replicate 1 ... X zone 

```
cell_types is now a columns of my metadata 
now when i run my function on my atac assay :

`run_macs_stero<- CallPeaks(object = multiomics,macs2.path = '/home/absta/.conda/envs/envpython/bin/macs2',effective.genome.size = 1.87e9 ,group.by = 'cell_types',assay = 'ATAC') `

and here is the error message : 

```
Processing file /home/absta/Téléchargements/wetransfer_raw_feature_bc_matrix_female12-h5_2022-03-25_1151/atac_fragments_male16.tsv.gz
can't open file

Erreur dans SplitFragments(object = object, assay = assay, group.by = group.by,  : 
  Error: cannot open requested file

```
That's strange since i was able before to do a peak calling with the group.by function so i don't really know. Also if i don't use the group.by argument , the function run well .. 

thanks you !

**Comment by timoast** [comment]
Can you show the output of `sessionInfo()`?

**Comment by timoast** [comment]
@Sabdelhamid98 any update on this?

**Comment by nhu-github** [comment]
I recently experience the same issue here. What is the solution?
