### ISSUE TITLE
Issue with calling peaks merged multiome GEX/ATAC

### ISSUE THREAD

**Issue by Eoin-W** [timoast/signac#1125]
I'm struggling to integrate rat 10X multiome samples. 

Eventually I was able to get a single integrated sample using [this vignette](https://satijalab.org/signac/articles/integrate_atac.html). It runs, but extremely slowly (like, over 24 hours on a server Rstudio for 4 ~5,000-cell samples). But this vignette does not use macs2 or RegionStats and I want to do e.g. motif analysis. 

I am not sure how best to proceed. Here I'm trying to create a peaks object using macs2, which appears to work at first but throws a lot of errors. Is this the correct approach and if so any idea what is wrong?

<img width="875" alt="Screen Shot 2022-05-17 at 12 17 42 PM" src="https://user-images.githubusercontent.com/101597955/169084001-2924789e-c58e-4078-a549-7d67328eec81.png">
<img width="875" alt="Screen Shot 2022-05-17 at 12 17 59 PM" src="https://user-images.githubusercontent.com/101597955/169084050-7851f057-556a-489d-a29a-2d2b775138f4.png">
I've skipped some similar rows
<img width="929" alt="Screen Shot 2022-05-17 at 12 40 04 PM" src="https://user-images.githubusercontent.com/101597955/169084205-3e4b1cd2-8a03-4173-acdb-97de71999a7e.png">
<img width="910" alt="Screen Shot 2022-05-17 at 12 40 13 PM" src="https://user-images.githubusercontent.com/101597955/169084251-121b9b83-29b6-490b-a93e-10d2ac80399e.png">

<img width="771" alt="Screen Shot 2022-05-18 at 11 42 29 AM" src="https://user-images.githubusercontent.com/101597955/169085228-7fde1832-4b1d-46cf-ba42-c79835d36979.png">
<img width="767" alt="Screen Shot 2022-05-18 at 11 42 38 AM" src="https://user-images.githubusercontent.com/101597955/169085258-3468e663-89e5-4dd7-b96f-ff1124688dd3.png">
<img width="780" alt="Screen Shot 2022-05-18 at 11 42 49 AM" src="https://user-images.githubusercontent.com/101597955/169085272-656cc85f-7b5e-4a3f-af3f-bc2c0d23c72a.png">

**Comment by timoast** [comment]
If the integration is taking a long time, it's likely you haven't quantified the same set of regions across the different datasets. I'd strongly suggest following the [merge vignette](https://satijalab.org/signac/articles/merging.html) when analyzing multiple samples.

For the MACS2 part, it looks like there could be an issue with your MACS2 installation. Can you confirm that you are able to successfully run MACS2 using these fragment files outside of Signac/R?

**Comment by Eoin-W** [comment]
Thank you! I'm still trying to follow. What is the difference between the merge vignette and the integration vignette? Won't the merge by itself leave batch effects between samples as shown in the integration vignette? 

MACS2 works just fine on individual (non-integrated) datasets and when following the vignette for a single sample, no problems with RegionStats or any of the downstream steps and I'm able to get motif analysis. It's the integrated object that's a problem.

**Comment by timoast** [comment]
> MACS2 works just fine on individual (non-integrated) datasets and when following the vignette for a single sample

But does it work when running on all of the fragment files together, as is being done when running on the merged dataset?

**Comment by timoast** [comment]
@Eoin-W any update on this?
