### ISSUE TITLE
why the  ClosestFeature result showing different peak for input peak files

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#113]
Hi @timoast ,
     There are questions about ClosestFeature output result. In my case, the file peak as function  ClosestFeature's input as regions parameter is different from ClosestFeature output peak result column.
     If the output file peak cannot be identical with input peak, so how can i recognize what peak 
that i want to find the closest gene?
     Thanks

**Comment by timoast** [comment]
Are you saying that the column "query_region" in the output from ClosestFeature is different to the genomic ranges that you gave as input to the `regions` parameter? If so, can you provide a reproducible example?

**Comment by timoast** [comment]
Any update on this?

**Comment by honghh2018** [comment]
Hi @timoast ,
     I need some time to figure it out what happen and post the reproduciable code on it

**Comment by honghh2018** [comment]
Hi @timoast ,
     I have found the issue eventually alread.
     Now, the trouble had soved in latest Signac package, since the problem i posted above appeared early Signac package.
     The closest_region different from query_region was same as input peak files. and  my problem have done on it.
     The matter showing below:
      ClosestFeature chart on red line drawn was identical with input peak with red line drawn.
![image](https://user-images.githubusercontent.com/41668708/77137021-10133b80-6aa7-11ea-90e6-f82417c71585.png)
     The input peak file:
![image](https://user-images.githubusercontent.com/41668708/77137063-45b82480-6aa7-11ea-8f4e-28d673a7616b.png)
     Thanks.

**Comment by timoast** [comment]
You’re saying this is not an issue in the latest release?

**Comment by timoast** [comment]
I actually still don't understand what the issue is

**Comment by honghh2018** [comment]
Hi @timoast 
Sorry for the ambiguous describtion above.
      Firstly, The earliest developed function CloestFeature within Signac seems like a bug that when as inputed peak to find the closest feature, the outputed result table's  was different from the imputed peak. 
      Secondly,  On the basis above, I was unable to affirm what peak that i input was on the output result table of function CloestFeatures.Obviously, this was notable on me.
        Lately, I taken your latest Signac package to analysize again, its output table 's   query_region of  CloestFeature column was identical with peak inputed. So, the problem have solved now.
       Thanks.
