### ISSUE TITLE
Vignette: mentioning of non-exiting future strategy "multiprocessor"

### ISSUE THREAD

**Issue by HenrikBengtsson** [timoast/signac#1135]
Hi. You've got:

https://github.com/timoast/signac/blob/10d950ea478371782939fc998df782d6398e86d9/vignettes/future.Rmd#L23

Note that `multiprocessor` doesn't exist. You probably meant `multiprocess`, which is now deprecated and will eventually be removed.  I think you just wanna drop it and only mention `multisession` and `multicore`.

**Comment by timoast** [comment]
Hi Henrik, thanks for pointing this out! Was definitely meant to be `multiprocess` rather than `multiprocessor`, but I will just remove it entirely since it's now deprecated.

**Comment by timoast** [comment]
Should be fixed now on the develop branch and on the website
