### ISSUE TITLE
Problem creating Seurat object from fragment file

### ISSUE THREAD

**Issue by sinkaha** [timoast/signac#1139]
Hi!

Do you have a suggestion on how to create a Seurat object without a peak-cell matrix in a situation like this: 

I am trying to create a Seurat object from a fragment file, that was originally created from preprocessing by Chromap. I have already done some analyses with ArchR and wish to continue using Signac with the fragments that came out of the filtering steps I perfomed with ArchR. I performed peak calling using Macs2, converted peak to genomic ranges and created a unified peak set for my four samples. 

I used getFragmentsFromProject() in ArchR to get my fragments and to create a new, subsetted fragment file, which I sorted and indexed. However, by doing this, I end up with a fragment file that does not contain the read pairs/fragment (fifth column, https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments ). Therefore, when trying to create the fragment object, I get this error:

```
fragments <- CreateFragmentObject(path="/path/to/fragments/fragments.tsv.gz", cells = rownames(combined_peaks))
Error in CreateFragmentObject(path = "/path/to/fragments/fragments.tsv.gz",  : 
  Incorrect number of columns found in fragment file
```
I guess there is still the option to filter the original fragment file,  based on the fragments that were discarded by filtering steps in ArchR. However, the fifth column of the fragment file from Chromap is also not identical to the 10 x fragment file. Do you have any suggestions how I should proceed?

**Comment by timoast** [comment]
The fragment file needs to be in the correct format, once you fix that you should be able to follow the vignettes on the website without any issues.
