### ISSUE TITLE
the merge issue

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#114]
Hi @timoast ,
     It was confused that the merge object of four samples on meta.data showing NA values like below picture.
![image](https://user-images.githubusercontent.com/41668708/76383501-0860e200-6397-11ea-9ea6-b66bd323cfd7.png)

**Comment by timoast** [comment]
Hi, you'll have to provide more information. What code did you run?  Do you expect that all cells would have values for those columns showing NA?

**Comment by timoast** [comment]
Any update on this?

**Comment by honghh2018** [comment]
Hi @timoast 
     sorry for the late reply.
     The code showing below:
     The picture showing above indicated NA on the meta.data of object 'combined', In the face of your following just you posted on vigentte. 
create_obj <- function(dir) {
  count.path <- list.files(path = dir, pattern = "filtered_peak_bc_matrix.h5", full.names = TRUE)
  fragment.path <- list.files(path = dir, pattern = "fragments.tsv.gz", full.names = TRUE)[1]
  counts <- Read10X_h5(count.path)
  md.path <- list.files(path = dir, pattern = "singlecell.csv", full.names = TRUE)
  md <- read.table(file = md.path, stringsAsFactors = FALSE, sep = ",", header = TRUE)
  obj <- CreateSeuratObject(counts = counts, assay = "ATAC", meta.data = md)
  obj <- SetFragments(obj, file = fragment.path)
  return(obj)
}
#####create obj
fat1 <- create_obj("/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/F1/outs/")
fat2 <- create_obj("/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/F2/outs/")
h1 <- create_obj("/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/H1/outs/")
h2 <- create_obj("/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39/H2/outs/")
################Creating a common peak set
combined.peaks <- UnifyPeaks(object.list = list(fat1, fat2, h1, h2), mode = "reduce")
combined.peaks

################Quantify peaks in each dataset

fat1.counts <- FeatureMatrix(
  fragments = GetFragments(fat1),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(fat1)
)

fat2.counts <- FeatureMatrix(
  fragments = GetFragments(fat2),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(fat2)
)

h1.counts <- FeatureMatrix(
  fragments = GetFragments(h1),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(h1)
)
h2.counts <- FeatureMatrix(
  fragments = GetFragments(h2),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(h2)
)

fat1[['peaks']] <- CreateAssayObject(counts = fat1.counts)
fat2[['peaks']] <- CreateAssayObject(counts = fat2.counts)
h1[['peaks']] <- CreateAssayObject(counts = h1.counts)
h2[['peaks']] <- CreateAssayObject(counts = h2.counts)
################Merge objects
# add information to identify dataset of origin
fat1$dataset <- 'fat1'
fat2$dataset <- 'fat2'
h1$dataset <- 'h1'
h2$dataset <- 'h2'

# merge all datasets, adding a cell ID to make sure cell names are unique
combined <- merge(x = fat1, y = list(fat2, h1, h2), add.cell.ids = c("f1", "f2", "h1", "h2"))

################## make sure to change to the assay containing common peaks
DefaultAssay(combined) <- "peaks" 
combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(
  combined,
  reduction.key = 'LSI_',
  reduction.name = 'lsi', 
  irlba.work = 400
)
ElbowPlot(combined,reduction = 'lsi')
combined <- RunUMAP(combined, dims = 2:25, reduction = 'lsi')
combined <- FindNeighbors(
  object = combined,
  reduction = 'lsi',
  dims = 2:25
)
combined <- FindClusters(
  object = combined,
  verbose = FALSE
)
######UMAP draw
DimPlot(combined, group.by = 'dataset', pt.size = 0.1)
DimPlot(combined, pt.size = 0.1)
################################

**Comment by timoast** [comment]
This is because the row names were not being read correctly when loading the metadata. I will update the merge vignette, the correct function is:

```r
create_obj <- function(dir) {
  count.path <- list.files(path = dir, pattern = "filtered_peak_bc_matrix.h5", full.names = TRUE)
  fragment.path <- list.files(path = dir, pattern = "fragments.tsv.gz", full.names = TRUE)[1]
  counts <- Read10X_h5(count.path)
  md.path <- list.files(path = dir, pattern = "singlecell.csv", full.names = TRUE)
  md <- read.table(file = md.path, stringsAsFactors = FALSE, sep = ",", header = TRUE, row.names = 1)
  obj <- CreateSeuratObject(counts = counts, assay = "ATAC", meta.data = md)
  obj <- SetFragments(obj, file = fragment.path)
  return(obj)
}
```

In future, please format your comments correctly so they are readable: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by timoast** [comment]
Updated online now
