### ISSUE TITLE
FindMarkers in ATAC assay is not consistent with CoveragePlot

### ISSUE THREAD

**Issue by pmcdil** [timoast/signac#1142]
Hi Signac team,

I am running FindMarkers between two clusters to check if my marker peaks in atac assay. The problem is; on CoveragePlot I can clearly see that sample 1 has this peak and sample 2 doesn't. But when I run FindMarkers, or FoldChange functions on these samples the marker peak has 0.1 logFC and this is not matching with what I see in coverage plot. Later, I broke down these functions and I saw that CoveragePlot works with sum of normalised counts in 100 bp sliding window, meanwhile FindMarkers uses rowMeans. The issue here is probably not my all cells have enough reads on these locations making my row (the marker location) sparse, so that lowering the signal by taking the mean.
My question is how can I work with this issue? Can I modify the FoldChange to use rowSums instead of rowMeans? Or can I use something like z-test on the table used by coverageplot (sum of normalised counts in 100 bp sliding window)? 
As you see, my struggle is to have consistency between foldchange and coverageplot. How can I handle this in the best way?

Thanks in advance.

**Comment by timoast** [comment]
I don't think using the sum makes sense for computing differences between groups, then you'd be strongly biased towards higher signal in whatever group happened to have more cells.

Can you show the coverage plot and the fold change value for the region you're referring to?

**Comment by pmcdil** [comment]
Hi thanks for reply. I solved the problem. Basically, the marker peak was present in a subcluster of my main cluster and that is why taking all cluster together on coverage plot was misleading.
