### ISSUE TITLE
error in signac motif tutorial

### ISSUE THREAD

**Issue by davemcg** [timoast/signac#115]
https://satijalab.org/signac/articles/motif_vignette.html
```r
# Add the Motif object to the assay
mouse_brain[['peaks']] <- AddMotifObject(
  object = mouse_brain[['peaks']],
  motif.object = motif
)
```

This should be
```r
# Add the Motif object to the assay
mouse_brain[['peaks']] <- AddMotifObject(
  object = mouse_brain,
  motif.object = motif
)
```

**Comment by timoast** [comment]
No, the vignette is correct. Why do you think it's a bug?

**Comment by davemcg** [comment]
Sorry, I'm following along with own Seurat obj (`rpe.atac` (which doesn't already have a peak slot)....I get an error:

```
> rpe.atac[['peaks']] <- AddMotifObject(
   object = rpe.atac[['peaks']],
   motif.object = motif
 )
Error in `[[.Seurat`(rpe.atac, "peaks") : 
  Cannot find 'peaks' in this Seurat object
```

Doesn't `object` refer to seurat object, and not the slot?

**Comment by timoast** [comment]
Object in this case refers to an Assay object. Here you're getting the error because you don't have an assay called "peaks" in the Seurat object

**Comment by davemcg** [comment]
Ah, I named my ATAC assay 'ATAC'....sorry for the wasted time.
