### ISSUE TITLE
CallPeaks function using the cellranger's fragments file without the strand column

### ISSUE THREAD

**Issue by jase11** [timoast/signac#1152]
When analyzing single cell ATAC-seq data, the tutorial recommends to call peaks with **macs2** rather than using the peaks called by cellranger. And the `CallPeaks` function splits the cellranger’s **fragments.tsv.gz** by groups, and uses the split files as the input to macs2.
However, according to the [macs2’s documentation](https://github.com/macs3-project/MACS/blob/master/docs/callpeak.md), the input bed file needs to have the 6th **strand** column, which is not present in cellranger's fragments file. I'm wondering if this is the correct way to use macs2.

**Comment by timoast** [comment]
As far as I know it doesn't have any impact, and the peak calls seem to be fine. I'd suggest asking the MACS2 authors for more information.
