### ISSUE TITLE
About CoveragePlot funciton indicated no differential for significantly expression differential peak using FindMarker 

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#117]
Hi @timoast ,
     There are question to draw my ATAC data's significantly differential expression peak  that was control versus treatment sample with the CoveragePlot for showing same plot below just like your vignette. So, how can i plot with the significantly peak been differential? In a addition, The problem just had quizzed a mouth ago,The solved parameter you give it to me unable to overcoming this issue.
![image](https://user-images.githubusercontent.com/41668708/77220315-db23e900-6b79-11ea-8685-8ac7b0c80f3b.png)
Thanks.

**Comment by timoast** [comment]
Sorry I'm not understanding the question. Please re-state the question clearly and provide all relevant code.

**Comment by timoast** [comment]
Any update on this?
