### ISSUE TITLE
ATAC imputation?

### ISSUE THREAD

**Issue by klgoss** [timoast/signac#1182]
Hello, 

I appreciate this wonderful tool! I am fairly new to scATACseq analysis, so forgive me if if my question is naive. I have 1 multiome dataset and 1 CITEseq dataset. I’d like to follow the steps on the “RNA imputation” part of this vignette: https://satijalab.org/signac/articles/integrate_atac.html#rna-imputation-1 , except I would like to impute ATAC for the CITEseq dataset. Below is the code I’ve tried, and while the data does transfer, I’m not able to do any downstream analysis with my newly added “predicted_ATAC” slot in the CITEseq dataset. Am I missing something or is this kind of imputation not possible? Thanks in advance for any insight.

My code:

````
DefaultAssay(multiome) <- "RNA"
DefaultAssay(cite) <- "RNA"

multiome <- RunSPCA(multiome, assay = "RNA", graph = "wsnn")

#Computing a cached neighbor index
multiome <- FindNeighbors(
  object = multiome,
  reduction = "spca",
  dims = 1:50,
  graph.name = "spca.annoy.neighbors", 
  k.param = 50,
  cache.index = TRUE,
  return.neighbor = TRUE,
  l2.norm = TRUE
)

#Query dataset processing
#Find anchors between the query and reference 
anchors <- list()

anchors <- FindTransferAnchors(
  reference = multiome,
  query = cite,
  k.filter = NA,
  reference.reduction = "spca", 
  reference.neighbors = "spca.annoy.neighbors", 
  dims = 1:50
)

atac <- TransferData(
  anchorset = anchors,
  refdata = GetAssayData(multiome[["peaks"]], slot = "data"),
  weight.reduction = cite[["pca"]],
  dims = 1:50
)

cite[["predicted_ATAC"]] <- atac
cite[["predicted_ATAC"]] <- as.ChromatinAssay(cite[["predicted_ATAC"]])
````

**Comment by timoast** [comment]
What do you mean exactly that you are not able to do any downstream analysis using the predicted ATAC assay?

**Comment by klgoss** [comment]
I’m not able to find differentially accessible peaks using `FindMarkers` with latent.vars = ‘peak_region_fragments’ because I don’t have peak_region_fragments here. I just realized I can get around that by just using `FoldChange()` or I guess I could just run `FindMarkers` without latent.vars.

I’m unable to create a coverage plot because I get the following error: ”Error: Cannot find 'nCount_atac' in this Seurat object”. Is there a way to add this manually?

**Comment by timoast** [comment]
`peak_region_fragments` is metadata that is specific to the ATAC dataset, it's not transferred to the query dataset when you run `TransferData()`. I wouldn't recommend running `FindMarkers()` on the imputed data anyway, for the same reason that we don't recommend doing it on batch-corrected data. The datapoints are not independent in the imputed data, which violates the assumption of the test.

> I’m unable to create a coverage plot because I get the following error: ”Error: Cannot find 'nCount_atac' in this Seurat object”. Is there a way to add this manually?

You won't be able to create a coverage plot in the query dataset using an imputed ATAC matrix, these plots require a fragment file, which contains genome-wide information.
