### ISSUE TITLE
the blacklist ratio of an aggregated multiomic object

### ISSUE THREAD

**Issue by Leonrunning** [timoast/signac#1185]
Hi,

I am trying to calculate the blacklist ratio of an aggregated multiomic (ATAC+RNA) object. Samples were pre-processed with cellranger-arc Aggr, which does not provide metadata information like the other pipelines.

The ratio of blacklist was calculated manually:

F1$blacklist_fraction <- FractionCountsInRegion(
  object = F1, 
  assay = 'peaks',
  regions = blacklist_mm10
)

However, the results showed that all cells have the same value of blacklist_fraction. They are all zero.

Can anyone let me know what's wrong with this calculation?

thanks

**Comment by Leonrunning** [comment]
The "peaks" is from macs2. If I use the assay of "ATAC", the values are not zero. Still interested to know the differences.

**Comment by timoast** [comment]
The `FractionCountsInRegion` function uses the count matrix to find how many counts per cell overlap with a blacklist region. If peaks overlapping with blacklist regions were removed, then the value will be zero for all cells.

**Comment by Leonrunning** [comment]
> 
Oh, I see, probably, those information were removed from MACS2. I will check about that. Thanks!
