### ISSUE TITLE
Coverage Plot Links Track Score

### ISSUE THREAD

**Issue by cl-37** [timoast/signac#1189]
Hello, I was wondering if there is a way to change the scale of the score bar (circled in red on the screenshot below) when using the CoveragePlot() function.
<img width="701" alt="Screen Shot 2022-08-15 at 5 11 33 PM" src="https://user-images.githubusercontent.com/111324059/184784371-1cf70dc1-466f-4b31-9af3-8256a5aee3ce.png">
Thanks so much for any help!

**Comment by timoast** [comment]
Currently there's no easy way to change this

**Comment by timoast** [comment]
The link score will now show the minimum value as 0 (or negative if there are negative values), and limit to three values shown in the scale in the legend. I think this solves the main issue here, so I'll close this.
