### ISSUE TITLE
error in RunChromVAR

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#119]
Hi @timoast 
     The error occured when step on RunChromVAR of signac your post, the error detail showing below:
Error in mcexit(0L) : Typing error, please close the channel to the main process
Calls: RunChromVAR ... bploop.lapply -> .send_to -> .send_to -> <Anonymous> -> mcexit
     That make me confused, and i don't know what it make for this problem.
     Thanks

**Comment by timoast** [comment]
Can you provide the code you're running?

**Comment by timoast** [comment]
Any update on this?
