### ISSUE TITLE
aesthetic issue about the peaks plotted by Coverageplot

### ISSUE THREAD

**Issue by yxiao832** [timoast/signac#1191]
Hi Tim, 

Is there a way to make the outline of the peak thicker using CoveragePlot? Here is the peak I plotted and I want to increase the weight of peak outlines. 
<img width="397" alt="Screen Shot 2022-08-17 at 3 45 54 PM" src="https://user-images.githubusercontent.com/46054827/185229908-269b3939-86b6-43ff-b9a5-bc05f1f3631c.png">

Thank you!
Yang

**Comment by timoast** [comment]
We do not have any parameters for that, you can find documentation for functions here: https://satijalab.org/signac/reference/index.html
