### ISSUE TITLE
add motifs problem after co embeding RNA+ATAC

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#1192]
I have a coembeded object (RNA +ATAC merged together as you descibe to do in you r vingette)

When I try to add motifs to the ATAC part using:

oembed_harmon2 <- AddMotifs(
+   object = coembed_harmon2,
+   genome = BSgenome.Mmusculus.UCSC.mm10,
+   pfm = pfm
+ )

I get:

Building motif matrix
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'matchMotifs' for signature '"PWMatrixList", "Assay"'

When I run:
> class(coembed_harmon2[["ATAC"]])
[1] "Assay"
attr(,"package")
[1] "SeuratObject"

Can you tell me how I can turn this assay in my RNA+ATAC object back to a chromatin assay?

The previous ATAC object did have motifs attahced but they seem to have been removed when I co embeded.

Thanks
Chris

**Comment by timoast** [comment]
Can you show the code you're using?

**Comment by timoast** [comment]
Closing this now, please reopen if you're still having issues and can provide the code
