### ISSUE TITLE
CoveragePlot show a large normalize signal

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#1195]
Hi signal team!
I plot the peak coverage with CoveragePlot function and found the normalized signal (y-axis) is so large.
Is this ok? I'm very confused.
![image](https://user-images.githubusercontent.com/33304280/185780213-ffd58c05-4a03-4917-bcd4-d3712667af8b.png)

**Comment by timoast** [comment]
Your sample must have a lot of fragments, this is nothing to be concerned about
