### ISSUE TITLE
Access to pseudobulk track data

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#1196]
Not certain if this exists, but is there at least "semi-easy" way to get access to pseudobulk track data which CoveragePlot uses?

Like if I would like to calculate dendrogram between pseudobulk accessibility profiles across some marker genes from few cell clusters. Theoretically info for that calculation is in Patchwork object returned by CoveragePlot, but just wanted to ask that isn't there really any easier access to that data currently? Ultimately I am looking for like sparse-matrix representation of the data in coverageplot accessibility tracks.

**Comment by timoast** [comment]
We don't have any functions to return those values, but the function that generates the base-resolution matrix of Tn5 cut sites is called `CutMatrix()`. It's not exported from the package, but you can still access it with the triple-colon syntax: `Signac:::CutMatrix()`. 

Function definition is here: https://github.com/timoast/signac/blob/fa23843c1c14b5d54d2af78fb10e9f13c5a57ead/R/utilities.R#L1513-L1571
