### ISSUE TITLE
Installation ERROR: dependency ‘Rsamtools’ is not available for package ‘Signac’

### ISSUE THREAD

**Issue by mateuszstrzelecki86** [timoast/signac#1199]
Trying to download Signac and it keeps coming up with this issue:

"ERROR: dependency ‘Rsamtools’ is not available for package ‘Signac’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Signac’
Warning messages:
1: In i.p(...) :
  installation of package ‘Rhtslib’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘Rsamtools’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/1k/5g3g42912rn8klfdrj79h35h68nwdw/T//RtmpZ7mVpk/file6a1162db0e2/Signac_1.7.0.9002.tar.gz’ had non-zero exit status"

Does anyone else have problems with this?

**Comment by mateuszstrzelecki86** [comment]
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.7.0    compiler_4.2.1    R6_2.5.1          rprojroot_2.0.3  
 [5] cli_3.3.0         prettyunits_1.1.1 tools_4.2.1       withr_2.5.0      
 [9] rstudioapi_0.14   curl_4.3.2        crayon_1.5.1      remotes_2.4.2    
[13] callr_3.7.2       ps_1.7.1          pkgbuild_1.3.1   
>

**Comment by timoast** [comment]
It looks like Rsamtools failed to install, I'd suggest investigating why that failed (maybe it says in the error message), and try installing Signac again once you have the dependencies installed successfully

**Comment by mateuszstrzelecki86** [comment]
Found the solution here: [https://github.com/Bioconductor/Rhtslib/issues/23#issuecomment-848448454] 

As an Apple M1 user, I have downloaded _R-4.1.0-arm64.pkg_ (as recommended on the website). Deleting it, and re-downloading R via **R-4.1.0.pkg** fixed the issues I was having.

''... Concretely this means that if you are on an Apple M1 system, we strongly recommend that you use the official Intel 64-bit R (x86_64 arch) from CRAN available here: https://cran.r-project.org/bin/macosx/ (choose R-4.1.0.pkg, NOT R-4.1.0-arm64.pkg) ...''
