### ISSUE TITLE
10X sample alignment

### ISSUE THREAD

**Issue by JBreunig** [timoast/signac#12]
I'm trying to align 2 10X datasets that should be very similar.
sci <- brain03
tenx <- brain

At this code, I get an error unless I change the code to the following:

> intersecting.regions <- GetIntersectingFeatures(
>   object.1 = sci,
>   object.2 = tenx,
>   sep.1 = c(":", "-"), ## from c("-", "-")
>   sep.2 = c(":", "-")
> )

The error reads as follows:

> Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]) : 
>   some values in the "end" column cannot be turned into numeric values
> In addition: Warning message:
> Expected 3 pieces. Missing pieces filled with `NA` in 96883 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].

By changing the hypen to a colon I can get past that but then I get the following error running this code:

> sci_peaks_tenx <- FeatureMatrix(
>    fragments = GetFragments(object = tenx, assay = 'peaks'),
>    features = StringToGRanges(peaks.use),
>    cells = colnames(tenx)
>  )
> Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]) : 
>   some values in the "end" column cannot be turned into numeric values
> In addition: Warning message:
> Expected 3 pieces. Missing pieces filled with `NA` in 10000 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].

**Comment by timoast** [comment]
Can you run the following?

```r
head(rownames(sci))
head(rownames(tenx))
```

**Comment by JBreunig** [comment]
> head(rownames(sci))
[1] "chr1:4332549-4332612" "chr1:4571405-4572299" "chr1:4768318-4768789" "chr1:4769795-4770315" "chr1:4780053-4780514"
[6] "chr1:4785123-4786360"
> head(rownames(tenx))
[1] "chr1:3292470-3293295" "chr1:3395466-3395983" "chr1:3514780-3515099" "chr1:4392651-4392910" "chr1:4412405-4412920"
[6] "chr1:4414035-4414774"

**Comment by timoast** [comment]
> By changing the hypen to a colon I can get past that

So the first part does not give an error when you use `sep.1 = c(":", "-")` and `sep.2 = c(":", "-")`?

**Comment by JBreunig** [comment]
No it doesn't give an error with the change.

**Comment by timoast** [comment]
Ok, this is expected. The vignettes are not really meant to be copied verbatim, you will need to change some arguments depending on your data, especially the `sep` argument depending how your peaks are encoded. For your data you will need use `c(":", "-")` for everything, since this is how your peaks are formatted.

**Comment by JBreunig** [comment]
I see, in case someone needs the fix for 2 10X datasets:

 
> sci_peaks_tenx <- FeatureMatrix(
>   fragments = GetFragments(object = tenx, assay = 'peaks'),
>   features = StringToGRanges(peaks.use, sep = c(":", "-")),
>   sep = c(":", "-"),
>   cells = colnames(tenx),
>   verbose= TRUE
> )
