### ISSUE TITLE
Create metadata from sciATAC

### ISSUE THREAD

**Issue by raphaela2018** [timoast/signac#120]
Hi Tim,

I would like to compute QC matrics. But I don't have .csv file from 10X genomics for metadata. Can I get some idea how to get this similar matrix from sciATAC method? 

Thanks!

**Comment by timoast** [comment]
Hi, please see the last section in the [PBMC vignette](https://satijalab.org/signac/articles/pbmc_vignette.html), under the drop-down menu "Working with datasets that were not quantified using CellRanger"

**Comment by raphaela2018** [comment]
Thanks for the prompt response! I will try.
