### ISSUE TITLE
callpeaks error

### ISSUE THREAD

**Issue by wfma** [timoast/signac#1202]
Hi Folks,

I have looked into this in previous github issues and could not make this work. Basically, running the tutorial data gives the exact same error as with running my own data.

```r
> peaks <- CallPeaks(Ma_2023, outdir = "OUTPUT-Signac-PeakCalls", macs2.path = "~/opt/anaconda3/lib/python3.8/site-packages/MACS2")
sh: /Users/wm5wt/opt/anaconda3/lib/python3.8/site-packages/MACS2: is a directory
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'OUTPUT-Signac-PeakCalls/Ma_2023_ChemoDCM_peaks.narrowPeak': No such file or directory

```
So it seems like it cant find Macs2 AND cant find the peaks.narrowPeak file.

I checked that indeed Macs2 is installed and updated, as well as writable by running chmod -rw of the directories of both mac2 and "OUTPUT-Signac-PeakCalls" folder. Furthermore I tested writing to both directories (just a .csv file) and it works.

```
> a <- 1
> write.csv(a, file = "OUTPUT-Signac-PeakCalls/test.csv")
> 
> write.csv(a, file = "~/opt/anaconda3/lib/python3.8/site-packages/MACS2/test.csv")
> 
```

I am honestly not sure what is going on here. Can yall help?

Attached is session info().

Wei

[session.txt](https://github.com/timoast/signac/files/9436978/session.txt)

**Comment by timoast** [comment]
You need to provide the path to the actual macs2 program, not just the folder that contains it
