### ISSUE TITLE
CoveragePlot() does not return the same plot with the same parameters

### ISSUE THREAD

**Issue by l-cli** [timoast/signac#1206]
Hi, thanks for developing Signac!
When I run CoveragePlot() with the same parameters, I do not get the same plot each time. I thought max.downsample and downsample.rate was what causes the random sampling of positions, but even when I set the downsample.rate to 1 (which to my understanding means to retain all of the positions) the plots do not come out to be the same each time I run the function. I also tried to change the smoothing window size, but cannot control the outcome of the smoothing function. Could you suggest if there is a parameter I can specify to make the same plot with the same parameter values, while reflecting a reliable number of counts at each peak? 

Plots I obtained from the two times I ran the same codes:
![test_2](https://user-images.githubusercontent.com/55997222/188223327-5a7b3319-d54a-4a1e-a688-f5e0a61ebb84.jpeg)
![test_1](https://user-images.githubusercontent.com/55997222/188223328-d4186da3-70b0-4a1c-bba0-ec117eed2a5b.jpeg)

Codes used to produce the above 2 plots:
`CoveragePlot(
  object = nmglut,
  region = "GRIN2A",
  features = "GRIN2A", annotation = T,
  expression.assay = "SCT", 
  region.highlight = StringToGRanges(c("chr16-9735961-9737093",
                                       "chr16-9787990-9788950",
                                       "chr16-10079470-10081122")),
  assay.scale = "common", group.by = "timextype.ident", 
  ymax = 700, downsample.rate = 1, 
  extend.upstream = 100000,
  extend.downstream = 100000
)`

**Comment by timoast** [comment]
Thanks for pointing this out, this was due to random downsampling that happens within the function. I've now added a random seed set within the function to ensure the same downsampling is applied across multiple function calls.

**Comment by timoast** [comment]
@marlenam94 `downsample.rate=1` will prevent downsampling
