### ISSUE TITLE
colSums of expm1(assay$chromvar@data) is not a same value as expm1(assay$ACTIVITY@data).

### ISSUE THREAD

**Issue by ElevenYU98** [timoast/signac#1207]
Hi Signac team, 

I am new to the package, and I want to draw a heatmap with the data slot of chromvar assay.
But I realized, even after expm1() the value, the total number of value from the the data slot of chromvar assay each cell is not the same.
However, the total number of value from the the data slot of ACTIVITY assay each cell is all the same.
I want to know the reason behind it. And more importantly, I want to know if I should scale and center the value after running `AverageExpression` getting the matrix (as in [issue264](https://github.com/timoast/signac/issues/264)) for drawing heatmap.

`sub_merged_ATAC.integrate@assays$chromvar@data %>% expm1() %>% colSums() %>% head()`

> 80M_CTRL_AAACGAAAGGCGATTG-1 80M_CTRL_AAACGAAAGGCTCCTG-1 80M_CTRL_AAACGAAAGGTTAGTA-1 
>                1.376375e+02                1.963680e+02                1.504934e+06 
> 80M_CTRL_AAACGAAAGTATCTGC-1 80M_CTRL_AAACGAAAGTCGAGCA-1 80M_CTRL_AAACGAACACCATTCC-1 
>                1.991077e+08                6.083079e+09                1.347993e+09 

`sub_merged_ATAC.integrate@assays$ACTIVITY@data %>% expm1() %>% colSums() %>% head()`

> 80M_CTRL_AAACGAAAGGCGATTG-1 80M_CTRL_AAACGAAAGGCTCCTG-1 80M_CTRL_AAACGAAAGGTTAGTA-1 
>                       10186                       10186                       10186 
> 80M_CTRL_AAACGAAAGTATCTGC-1 80M_CTRL_AAACGAAAGTCGAGCA-1 80M_CTRL_AAACGAACACCATTCC-1 
>                       10186                       10186                       10186

**Comment by timoast** [comment]
ChromVAR returns z-scores for each TF motif or set of regions for each cell, I'd suggest taking a look at the chromVAR paper to understand how it works: https://www.nature.com/articles/nmeth.4401/
