### ISSUE TITLE
error in running NucleosomeSignal()

### ISSUE THREAD

**Issue by candacelei** [timoast/signac#121]
Hi,
I am using R version 3.6.2 (2019-12-12). I encountered error when running NucleosomeSignal().

This is my code:
>pbmc<-CreateSeuratObject(counts=peaks,
                                               assay='peaks',
                                               project="ATAC",
                                               min.cells=1,
                                               meta.data=metadata)
>fragment.path<-"/data/trial/fragments.tsv.gz"
>pbmc<-SetFragments(object = pbmc, file=fragment.path)
>pbmc<-NucleosomeSignal(object=pbmc)

This is the error message that I received running NucleosomeSignal(object=pbmc):
Extracting reads in requested region
Computing ratio of mononucleosomal to nucleosome-free fragments
Error in `[.data.table`(fragments.use, , c("cell", "length")) :
  column(s) not found: cell, length

The first 5 lines in my fragments.tsv.gz (from 10X cellranger-atac v1.2.0). I made a copy of it and unzipped it: 
chr1    10068   10209   AGCCAGCGTGTGACCC-1      1
chr1    10085   10479   CACTGAACAATGGCAG-1      1
chr1    10095   10198   CAGGGCTCACCCTTTG-1      4
chr1    10132   10260   CCCTGATGTGCTTGAT-1      1
chr1    10150   10202   ACAAGCTGTGGACGAT-1      1

Is the fragment file not in the right format?

Thanks,

**Comment by timoast** [comment]
If you made the file with cellranger it should be the correct format. Can you include the full code you're running, including how you're reading in the peaks matrix, and the output of the following:

```r
dim(pbmc)
head(colnames(pbmc))
head(rownames(pbmc))
```

**Comment by candacelei** [comment]
full code:
library(Seurat)
library(patchwork)
library(ggplot2)
library(Signac)

>metadata<-read.csv("/data/trial/singlecell.csv",
		header=TRUE,
		row.names=1)
>peaks<-Read10X_h5("/data/trial/filtered_peak_bc_matrix.h5",
		use.names=TRUE,
		unique.features=TRUE)
>pbmc<-CreateSeuratObject(
	counts=peaks,
	assay='peaks',
	project="ATAC",
	min.cells=1,
	meta.data=metadata
	)
>fragment.path<-"/data/trial/fragments.tsv.gz"
>pbmc<-SetFragments(
	object = pbmc,
	file=fragment.path)

>dim(pbmc) 
[1] 108189   7020

>head(colnames(pbmc))
[1] "AAACGAAAGAAAGGGT-1" "AAACGAAAGAGCTGTG-1" "AAACGAAAGCGCACAA-1"
[4] "AAACGAAAGGAACCGT-1" "AAACGAAAGGCTGGAT-1" "AAACGAAAGTCATCTG-1"

>head(rownames(pbmc))
[1] "chr1:181272-181608" "chr1:191433-191953" "chr1:267837-268171"
[4] "chr1:629729-630163" "chr1:633794-634259" "chr1:778165-779875"

>pbmc<-NucleosomeSignal(object=pbmc)
Extracting reads in requested region
Computing ratio of mononucleosomal to nucleosome-free fragments
Error in [.data.table(fragments.use, , c("cell", "length")) :
column(s) not found: cell, length

Thank you!

**Comment by timoast** [comment]
Are you using the latest version?

What happens if you run:

```r
fpath <- system.file("extdata", "fragments.tsv.gz", package="Signac")
atac_small <- SetFragments(object = atac_small, file = fpath)
NucleosomeSignal(atac_small)
```

**Comment by candacelei** [comment]
Version of Signac: 0.2.4
It failed even in the SetFragments() process.

> fragment.path<-system.file("extdata","/data/trial/fragments.tsv.gz",package="Signac")
> pbmc<-SetFragments(
                 object = pbmc,
                 file=fragment.path)
Error in SetFragments(object = pbmc, file = fragment.path) :
  Requested file does not exist or is not indexed

Thank you for your help!

**Comment by timoast** [comment]
Can you copy paste the exact code shown above?

**Comment by candacelei** [comment]
It all went through.

> fpath <- system.file("extdata", "fragments.tsv.gz", package="Signac")
> atac_small <- SetFragments(object = atac_small, file = fpath)
> NucleosomeSignal(atac_small)
Extracting reads in requested region
Computing ratio of mononucleosomal to nucleosome-free fragments
An object of class Seurat
300 features across 100 samples within 3 assays
Active assay: peaks (100 features)
 2 other assays present: bins, RNA
 2 dimensional reductions calculated: lsi, umap

**Comment by timoast** [comment]
Your fragments file is gzipped right?

**Comment by candacelei** [comment]
Yes. It's in /outs directory from cellranger-atac count (version 1.2.0).

**Comment by timoast** [comment]
Ok but the path you've provided above is not to a `/outs` directory.

Just to be clear, because you said above that you made a copy and unzipped the file: is the file at the path you specify in R (`/data/trial/fragments.tsv.gz`) a gzipped file?

**Comment by candacelei** [comment]
I changed the name of the /outs directory to /trial, which contains the components of a usual /outs from cellranger-atac count. 

And to your second question, yes.

**Comment by timoast** [comment]
Ok, are you able to send me the fragments file and index so I can take a look? You can email a download link to tstuart@nygenome.org

**Comment by timoast** [comment]
It seems the fragment file was not bgzipped but only compressed using gzip. Was this definitely the output of cellranger? If so you should raise an issue with them because the output should be bgzipped, and I don't know how the tabix index was created if the file was not bgzipped.

Are you sure you didn't decompress the file and then re-compress it using gzip?

The problem can be fixed by running:

```
gzip -d fragments.tsv.gz
bgzip fragments.tsv
tabix -p bed fragments.tsv.gz
```

**Comment by candacelei** [comment]
Hi Tim, 

It worked perfectly. Thank you for your help. Much appreciated!

**Comment by bc2zb** [comment]
Hmm, I had this same issue, and reindexing worked beautifully. Maybe 10x is generating this things using their own code, and that's why it's different.

**Comment by annamath** [comment]
I had the same error when running NucleosomeSignal() for a merged object. 

`Extracting reads in requested region Computing ratio of mononucleosomal to nucleosome-free fragments Error in [.data.table (fragments.use, , c("cell", "length")) : column(s) not found: length`

In my case the problem was that the cell IDs in the fragments files and in the seurat object were different. 
Cell barcodes re-occur in different 10x runs, so when merging you have to rename both the object's cell IDs (merge function, `add.cell.ids` argument) and merged fragments file's cell IDs (fragments.tsv.gz) but consistently.
