### ISSUE TITLE
How to correctly subset Seurat by features

### ISSUE THREAD

**Issue by wudustan** [timoast/signac#1218]
Hi, I have the following code:

    fn.peaks <- read.table(file = peaks.file,
                         col.names = c("chr", "start", "end"))
    fn.md <- read.table(file = metadata.file,
                      stringsAsFactors = FALSE,
                      sep = ",",
                      header = TRUE,
                      row.names = 1)[-1, ]
    fn.md <- fn.md[(fn.md$passed_filters > passed.min & fn.md$is__cell_barcode==1), ]
    fn.frags <- CreateFragmentObject(path = fragments.file,
                                   cells = rownames(fn.md))
    macs.features <- CallPeaks(object = fn.frags, 
                             macs2.path = macs.path)
    fn.counts <- FeatureMatrix(fragments = fn.frags,
                             features = macs.features,
                             cells = rownames(fn.md))
    fn.assay <- CreateChromatinAssay(fn.counts, 
                                   fragments = fn.frags)
    fn.seurat <- CreateSeuratObject(fn.assay, 
                                  assay = "peaks", 
                                  meta.data = fn.md)

If i want to create a subset of the fn.seurat object to remove certain features for all cells, how would I go about this? I tried to look through the documentation first but I'm still not sure.

**Comment by timoast** [comment]
The `subset` function has a `features` parameter, any features not present in that vector will be dropped

https://mojaveazure.github.io/seurat-object/reference/Seurat-methods.html

**Comment by wudustan** [comment]
Hi, thanks what would be the correct way to specify this for the feature of an ATAC Seurat object derived from Signac?

**Comment by timoast** [comment]
You need to convert the granges to strings that match the rownames of the assay, eg `StringToGRanges(...)`

**Comment by wudustan** [comment]
Thanks Tim!
