### ISSUE TITLE
Highlight regions using rectangles across multiple groups of cells

### ISSUE THREAD

**Issue by YangLi-Bio** [timoast/signac#1222]
Hi Tim,

I was trying to generate the following figure using "CoveragePlot" which highlights some regions in the genome across multiple cell groups, but I can only get separate rectangle highlights for each individual cell group. 

Could you please tell me whether Signac can generate such a figure?

<img width="146" alt="Capture" src="https://user-images.githubusercontent.com/35290254/191117153-0c814a4f-05fe-4a74-95c2-efb533b4bfab.PNG">

**Comment by timoast** [comment]
This is currently not possible, and would be difficult to implement with the way that ggplot2 constructs plots
