### ISSUE TITLE
subsetting for peaks in cluster

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#123]
Hi Tim,

Is there a way to obtain all peaks found in one cells cluster? I don't need to recall peaks for that cell cluster, just looking at which peaks are found in the cluster from the whole object.

Thanks!

**Comment by timoast** [comment]
Hi, you can do something like this to find which peaks are accessible in at least one cell in the cluster:

```r
library(Signac)
library(Seurat)

cells <- atac_small$seurat_clusters == 0  # choose cells for the cluster you want
counts <- GetAssayData(atac_small, assay = 'peaks', slot = 'counts')
peaks.use <- which(Matrix::rowSums(counts[, cells]) > 0)
```
