### ISSUE TITLE
Ability to output Wig/BigWig tracks at the current identity class

### ISSUE THREAD

**Issue by ShanSabri** [timoast/signac#124]
It seems the as the function [`SinglePlotCoverage`](https://github.com/timoast/signac/blob/a3772c9b0b061f8633034e7390cddcd3238c9f06/R/visualization.R#L22) nearly does this in a downsampled manner. [`Rtracklayer`](https://bioconductor.org/packages/devel/bioc/manuals/rtracklayer/man/rtracklayer.pdf) has an export to wiggle function for Granges objects.  

I've been using [this](https://divingintogeneticsandgenomics.rbind.io/post/split-a-10xscatac-bam-file-by-cluster/) as a way to generate cluster-level bam files which I convert down to BigWigs but integrating this functionality into Signac would be very useful.

**Comment by timoast** [comment]
Hi, this was also discussed here: https://github.com/timoast/signac/issues/28

I don't have any plans to add this but am open to a PR if you'd like to contribute
