### ISSUE TITLE
error in NucleosomeSignal

### ISSUE THREAD

**Issue by aselewa** [timoast/signac#128]
Hello,

I am getting the following error when I run NucleosomeSignal

```
setwd('~/outs/')

gut <- SetFragments(
  object = gut,
  file = 'fragments.tsv.gz'
)

gut <- NucleosomeSignal(object = gut)
Extracting reads in requested region
Computing ratio of mononucleosomal to nucleosome-free fragments
Error in `[.data.table`(fragments.use, , c("cell", "length")) : 
  column(s) not found: length
```

As you can see, I was able to set the fragment file successfully. This file was generated by cellranger. 
I saw in another issue that gzip might be an issue so I made sure it is bgzipped and has a corresponding .tbi file. The problem is still the same.

This is how my file looks like:

```
chr1    10245   10302   AAAGATGAGGCTAAAT-1      1
chr1    55313   55699   AAACTCGTCTGGCACG-1      2
chr1    56455   56658   AAACTCGTCTGGCACG-1      1
chr1    60687   60726   AAACTGCAGTCTGTGT-1      1
chr1    235723  235936  AAACTGCTCCTATCCG-1      1
```

I've tried everything and I cannot figure out why. I tried looking at the code base but I got lost from all the redirects. I would appreciate it if you can help me out. I saw others submitted similar issues but it seems theres several ways to get this problem.

I am using Signac 0.2.4 and Seurat 3.1.0

Thanks

**Comment by aselewa** [comment]
Fixed it a few moments after posting, sorry. My problem was that my barcodes in the fragment file didnt match any of the barcodes in Signac. For some reason, all barcodes end with -1 (i.e. TGTAGTTG-1) in the fragment file, but I think Signac drops the -1 when loading the data.

**Comment by timoast** [comment]
The Seurat function `Read10X` will remove the `-1` if all cells have it. I recommend using `Read10X_h5` instead, it should be faster and won't change the cell names.
