### ISSUE TITLE
Compare accessibility plots

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#131]
Hi @timoast,

I have a question regarding the accessibility analysis. I know that we can compare visually the accessibility between different clusters with the coverage plot. However, sometimes it is hard to see the differences, so I would like to have a clearer way to show that difference. 

One way to solve this problem would be creating a violin plot, but, If I am not wrong, it represents the gene activity matrix value that takes into account the whole peaks in the gene body. 

My question is, is there any way to integrate o compare just the promoter or a specific peak using violin-plot function? I think that could help to compare certain peak within different groups.

I would appreciate any suggestion or idea you have. Thank you very much for your excellent work and contribution. I really like it.

Best,

Aitor

**Comment by timoast** [comment]
You can use `VlnPlot` or other visualization functions in Seurat like `RidgePlot` or `FeaturePlot` to visualize individual peaks. Just set the assay to the assay containing the feature (eg, peaks) and input the feature names you want to visualize. Example shown here: https://satijalab.org/signac/articles/pbmc_vignette.html#find-differentially-accessible-peaks-between-clusters

**Comment by Aitor91** [comment]
Thank you for your suggestion, I didn't realize of that. However, trying your way I have a new issue. I have attached an image to make my issue easier to explain. 

In the peak line, I have just one bar, but in the coverage-plot, I can see several peaks. Do you know why is that? Why don't I have several peak-bars, instead of just one?

With all that in mind, I can generate a violin plot if I select the whole region, but not If I want to select a certain or specific peak, such as the one that is marked with a black box.

I would really appreciate any idea or suggestion. Again, thank you very much for your help and time.

Aitor

![Klk10](https://user-images.githubusercontent.com/61357098/79274581-c7b32780-7e72-11ea-92ee-bc4ba5d614c2.png)

**Comment by timoast** [comment]
The problem here is that your peak calling has not identified the different peaks, and has merged them all into one region. You could try running some different peak callers on the bulk data, or try splitting each cluster into a separate file and calling peaks on each cluster separately to try to get more accurate peaks. See this issue for some more discussion of peak calling: https://github.com/timoast/signac/issues/74

**Comment by Aitor91** [comment]
Thank you for the suggestion. I will look more into that.

Aitor
