### ISSUE TITLE
Warning in getting differentially accessible peaks

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#132]
Hello,

I get this warning many many times when I use FindMarkers to get differentially accessible peaks as in:
https://satijalab.org/signac/articles/mouse_brain_vignette.html

```
Warning message:
"glm.fit: fitted probabilities numerically 0 or 1 occurred"
```

Should I just ignore it?

Thank you

**Comment by timoast** [comment]
Yes you can ignore that, it's just indicating that one of the comparisons gave p=1 or p=0. This is due to either all the cells in one group containing 0 vs all containing 1 in the comparison group, or more likely what's happening is both groups have all 0 counts and the probability given by the model is zero.

**Comment by ahmedabbas81** [comment]
Thank you,

What is the function of the parameter `latent.vars = 'peak_region_fragments'`? What if I remove this parameter and use the default value 'NULL'? Are the results still Ok in case of using the default value 'NULL'?

Thank you

**Comment by timoast** [comment]
That is a term to include in the model. The intuition is that if the difference between the groups can be explained by the latent variable, then the results are not significant.

**Comment by ahmedabbas81** [comment]
Suppose I have two integrated scATAC-seq objects and I want to find the differentially accessible peaks between the two objects. How to use `latent.vars` in this case so that I am sure that the difference is not significant because they are two diff objects. Also, the two objects are of the same technology, then, do I need to use `latent.vars` in this case? Thanks a lot

**Comment by timoast** [comment]
@ahmedabbas81 you would set `latent.vars` to the variable that groups cells by their original object
