### ISSUE TITLE
Weird UMAP plot after merging datasets

### ISSUE THREAD

**Issue by kpadm** [timoast/signac#133]
Hello Tim, 

This is related to my earlier issue with `RunTFIDF`. Briefly, I am merging three different single cell datasets to run contrasts later, but when after `RunUMAP`, I get a very weird looking UMAP plot. See this image for instance - [https://imgur.com/mX9N7L6](https://imgur.com/mX9N7L6). 

If I just run the UMAP on the individual datasets, I am getting a plot that one would expect. See here for a UMAP plot for just one of the samples - [https://imgur.com/DLWyFIa](https://imgur.com/DLWyFIa).

My ultimate goal is to set up differential comparisons between the three different sample sets. Is there something I am doing wrong? Is there a different way to do this without merging these three separate objects into one? 

Thanks for your help!

Karthik

**Comment by timoast** [comment]
Can you post the full code you're running?

**Comment by kpadm** [comment]
Thanks Tim, here is the code:

```library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Mmusculus.v79)
library(ggplot2)
library(patchwork)
set.seed(1234)
library(hdf5r)

counts_day0 = Read10X_h5(filename = "raw_data/Sample_352-AH-1-ATAC/outs/raw_peak_bc_matrix.h5")
counts_day7 = Read10X_h5(filename = "raw_data/Sample_352-AH-2-ATAC/outs/raw_peak_bc_matrix.h5") 
counts_day42 = Read10X_h5(filename = "raw_data/Sample_352-AH-6-ATAC/outs/raw_peak_bc_matrix.h5")

metadata_day0 = read.csv(file="raw_data/Sample_352-AH-1-ATAC/outs/singlecell.csv", header=TRUE, row.names = 1)
metadata_day7 = read.csv(file="raw_data/Sample_352-AH-2-ATAC/outs/singlecell.csv", header=TRUE, row.names = 1)
metadata_day42 = read.csv(file="raw_data/Sample_352-AH-6-ATAC/outs/singlecell.csv", header=TRUE, row.names = 1)

msc_day0 = CreateSeuratObject(counts = counts_day0, assay = 'peaks', project = 'ATAC', min.cells = 1, meta.data = metadata_day0)
msc_day7 = CreateSeuratObject(counts = counts_day7, assay = 'peaks', project = 'ATAC', min.cells = 1, meta.data = metadata_day7)
msc_day42 = CreateSeuratObject(counts = counts_day42, assay = 'peaks', project = 'ATAC', min.cells = 1, meta.data = metadata_day42)

fragments_day0 = "raw_data/Sample_352-AH-1-ATAC/outs/fragments.tsv.gz"
fragments_day7 = "raw_data/Sample_352-AH-2-ATAC/outs/fragments.tsv.gz"
fragments_day42 = "raw_data/Sample_352-AH-6-ATAC/outs/fragments.tsv.gz"

msc_day0 = SetFragments(object = msc_day0, file = fragments_day0)
msc_day7 = SetFragments(object = msc_day7, file = fragments_day7)
msc_day42 = SetFragments(object = msc_day42, file = fragments_day42)

combined.peaks <- UnifyPeaks(object.list = list(msc_day0, msc_day7, msc_day42), mode = "reduce")
combined.peaks

msc_day0_counts <- FeatureMatrix(
  fragments = GetFragments(msc_day0),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(msc_day0)
)

msc_day7_counts <- FeatureMatrix(
  fragments = GetFragments(msc_day7),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(msc_day7)
)

msc_day42_counts <- FeatureMatrix(
  fragments = GetFragments(msc_day42),
  features = combined.peaks,
  sep = c(":", "-"),
  cells = colnames(msc_day42)
)

msc_day0[['peaks']] <- CreateAssayObject(counts = msc_day0_counts)
msc_day7[['peaks']] <- CreateAssayObject(counts = msc_day7_counts)
msc_day42[['peaks']] <- CreateAssayObject(counts = msc_day42_counts)

msc_day0$dataset <- 'msc_day0'
msc_day7$dataset <- 'msc_day7'
msc_day42$dataset <- 'msc_day42'

combined <- merge(x = msc_day0, y = list(msc_day7, msc_day42), 
                  add.cell.ids = c("day0", "day7", "day42"))

DefaultAssay(combined) <- "peaks" 
combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(
  combined,
  reduction.key = 'LSI_',
  reduction.name = 'lsi', 
  irlba.work = 400
)
combined <- RunUMAP(combined, dims = 2:30, reduction = 'lsi')
DimPlot(combined, group.by = 'dataset', pt.size = 0.1)
```

**Comment by timoast** [comment]
I don't see anything wrong with the code, are you 100% sure that generates the plot (https://imgur.com/mX9N7L6)? Can you re-run in a fresh R session and attach the final output from `DimPlot` here?

**Comment by kpadm** [comment]
Hi Tim, 

Sorry that plot was one generated along with the corresponding scRNA-seq data. This is the plot that was generated - [https://imgur.com/WBN9MdJ](https://imgur.com/WBN9MdJ). It still looks weird though. 

Karthik

**Comment by timoast** [comment]
How many peaks do you get with `UnifyPeaks`? (`length(combined.peaks)`)

**Comment by kpadm** [comment]
This is how `combined.peaks` looks like:

```> combined.peaks
GRanges object with 181855 ranges and 0 metadata columns:
           seqnames            ranges strand
              <Rle>         <IRanges>  <Rle>
       [1]     chr1   3119732-3120279      *
       [2]     chr1   3297501-3297896      *
       [3]     chr1   3414478-3414863      *
       [4]     chr1   3514693-3515293      *
       [5]     chr1   3611195-3611529      *
       ...      ...               ...    ...
  [181851]     chrY 90761165-90762014      *
  [181852]     chrY 90797418-90798001      *
  [181853]     chrY 90798544-90805995      *
  [181854]     chrY 90806828-90809631      *
  [181855]     chrY 90810205-90813945      *
  -------
  seqinfo: 21 sequences from an unspecified genome; no seqlengths```

**Comment by timoast** [comment]
What about the output of `length(VariableFeatures(combined))`?

**Comment by kpadm** [comment]
Here is the output:

```
> length(VariableFeatures(combined))
[1] 181787
```

**Comment by timoast** [comment]
The only other thing I can think of is that it could have something to do with overwriting the default assay when you assign the new assay to `peaks`. Can you try again calling it something else? If that still doesn't work could you send me a link to the `combined` object and I'll try to take a further look at it: tstuart@nygenome.org

**Comment by kpadm** [comment]
Hello Tim, 

I assigned the new assay to a different term but it still didn't work. I have sent you the `combined` object through Box. Thanks! 

Karthik

**Comment by timoast** [comment]
Ok I worked out what the issue is here, you're loading the raw matrix and didn't do any filtering, so there are lots of cells with very low counts (some even have zero counts). If you set a total count cutoff then you get a reasonable UMAP (for example, minimum of 100 or 200 counts per cell).

**Comment by kpadm** [comment]
Hi Tim, 

Thanks for your response. So it would make sense to run the QC metrics first and filter peaks using for example:

```
brain <- subset(brain, subset = peak_region_fragments > 3000 & peak_region_fragments < 100000 & pct_reads_in_peaks > 15 & blacklist_ratio < 0.025 & nucleosome_signal < 10 & TSS.enrichment > 2)
```

before merging them?

**Comment by timoast** [comment]
The issue is not with merging per se, you just need to make sure that some filtering is done before running TF-IDF, SVD, and UMAP  to remove non-cells. I would recommend doing the filtering first though just for efficiency (otherwise you're using much larger matrices)

**Comment by kpadm** [comment]
Thanks Tim for all your help. I get a 'normal' looking UMAP after I added `min.features = 100` to `CreateSeuratObject` like you suggested. [https://imgur.com/tzqzpB3](https://imgur.com/tzqzpB3)
