### ISSUE TITLE
Excessive use of memory by RunChromVAR

### ISSUE THREAD

**Issue by ccruizm** [timoast/signac#136]
Hello @timoast ,

Thanks for developing such a great friendly-user tool. I am having an issue when running `RunChromVAR`. I am working on an HPC and after start running the function, uses parallel processing and takes all the available memory (`Error in mcfork(detached): unable to fork, possible reason: Cannot allocate memory`). There is a way to limit/change this behavior?

Thanks in advance

**Comment by timoast** [comment]
Hi, you should be able to turn of the parallelization by running:

```r
library(BiocParallel)
register(SerialParam())
``` 

Or if you just want to reduce the number of cores used:

```
register(MulticoreParam(4))
```
