### ISSUE TITLE
Cell-type specific responses

### ISSUE THREAD

**Issue by ccruizm** [timoast/signac#137]
Good day!

I am working with two datasets of HSC, one control and the other one after treatment. As expected, after merging datasets, each condition is represented across the different clusters. I would like to know whether I can use the approach described for RNA (Integrating stimulated vs. control PBMC datasets to learn cell-type-specific responses) with scATAC data using Signac. If so, should I use the 'peaks' or 'RNA' assay? If you have any considerations or suggestions to perform this type of analysis, I would like to hear them.

Thanks in advance!

**Comment by timoast** [comment]
Yes, you can certainly use the integration methods for integrating different scATAC-seq dataset. See the  vignette here for an example: https://satijalab.org/signac/articles/integration.html

After you integrate the control and treatment datasets you could follow a very similar workflow to that shown in the Seurat stimulated vs control vignette (find clusters, find differentially accessible peaks within a cluster across treatment/control conditions)
