### ISSUE TITLE
merge two Signac Objects

### ISSUE THREAD

**Issue by SinghalDivya** [timoast/signac#14]
Hi
I tried to merge two scATAC samples the way we can merge Seurat object using merge function in scRNA-seq. However, as the scATAC is different and we need to merge fragments files as well, can you suggest me the way to merge two Signac object?

**Comment by hjack123** [comment]
what if the barcodes have duplicates in 2 datasets?

**Comment by timoast** [comment]
@hjack123 great question, I am working on better ways to handle this but for now I suggest replacing the cell barcode name using sed on the command line before merging the fragment files

**Comment by WWJiaxuan** [comment]
> @hjack123 great question, I am working on better ways to handle this but for now I suggest replacing the cell barcode name using sed on the command line before merging the fragment files

Hi,

Thanks for your useful comments, but can you elaborate more on how to use sed to replace cell barcode name?

For example, I want to add subject before the barcode (i.e from 'TACG-1' to 'sample1_TACG-1').

Thanks in advance!

**Comment by WWJiaxuan** [comment]
> > @hjack123 great question, I am working on better ways to handle this but for now I suggest replacing the cell barcode name using sed on the command line before merging the fragment files
> 
> Hi,
> 
> Thanks for your useful comments, but can you elaborate more on how to use sed to replace cell barcode name?
> 
> For example, I want to add subject before the barcode (i.e from 'TACG-1' to 'sample1_TACG-1').
> 
> Thanks in advance!

Never mind, I found the solution  in #45 . Thanks again for the user-friendly package!

**Comment by timoast** [comment]
@WWJiaxuan note that you don’t need to merge fragment files as of Signac version 1.0.0 

See https://satijalab.org/signac/articles/merging.html

**Comment by WWJiaxuan** [comment]
> @WWJiaxuan note that you don’t need to merge fragment files as of Signac version 1.0.0
> 
> See https://satijalab.org/signac/articles/merging.html

Well noted with many thanks!
