### ISSUE TITLE
Error in FindIntegrationAnchors

### ISSUE THREAD

**Issue by millersan** [timoast/signac#143]
Hi
When i used my own data, I get this Error 
##################################################################
Error in DietSeurat(object = object.list[[i]], assays = assay[i], features = anchor.features,  : 
  The default assay is slated to be removed, please change the default assay
##################################################################
The code is similarly with Signac code, I just set my data names to sci and tenx.
Could you help me to solve this problem?
Thank you!

**Comment by timoast** [comment]
Hi, can you post the full code you're running and the output of `sessionInfo()`?

**Comment by millersan** [comment]
Thank you very much! Here is my full code.

library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v86)
library(ggplot2)
library(gdata)
library(patchwork)

##################################G1
counts <- Read10X_h5(GP1_atac_h5)
metadata <- read.table(file = GP1_meta, header = TRUE, row.names = 1,sep = ",",stringsAsFactors = FALSE)

pbmc <- CreateSeuratObject(counts = counts, assay = 'G1.peaks', project = 'G1_ATAC', min.cells = 1, meta.data = metadata)


pbmc <- SetFragments(object = pbmc, file = G1_fragment)

pbmc
gc()
pbmc <- NucleosomeSignal(object = pbmc)

pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
pbmc$blacklist_ratio <- pbmc$blacklist_region_fragments / pbmc$peak_region_fragments

p1 <- VlnPlot(pbmc, c('pct_reads_in_peaks', 'peak_region_fragments'), pt.size = 0.1)
p2 <- VlnPlot(pbmc, c('blacklist_ratio', 'nucleosome_signal'), pt.size = 0.1) & scale_y_log10()

p1 | p2

pbmc$nucleosome_group <- ifelse(pbmc$nucleosome_signal > 10, 'NS > 10', 'NS < 10')
FragmentHistogram(object = pbmc, group.by = 'nucleosome_group')

# create granges object with TSS positions
gene.ranges <- genes(EnsDb.Hsapiens.v86)
seqlevelsStyle(gene.ranges) <- 'UCSC'
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding',]
gene.ranges <- keepStandardChromosomes(gene.ranges, pruning.mode = 'coarse')

tss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges),
  ranges = IRanges(start = start(gene.ranges), width = 2),
  strand = strand(gene.ranges)
)

seqlevelsStyle(tss.ranges) <- 'UCSC'
tss.ranges <- keepStandardChromosomes(tss.ranges, pruning.mode = 'coarse')

# to save time use the first 2000 TSSs
pbmc <- TSSEnrichment(object = pbmc, tss.positions = tss.ranges[1:2000])


pbmc$high.tss <- ifelse(pbmc$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(pbmc, group.by = 'high.tss') + ggtitle("TSS enrichment score") + NoLegend()

pbmc <- RunTFIDF(pbmc)
pbmc <- FindTopFeatures(pbmc, min.cutoff = 'q0')
pbmc <- RunSVD(object = pbmc, assay = 'G1.peaks', reduction.key = 'LSI_', reduction.name = 'lsi')
pbmc <- RunUMAP(object = pbmc, reduction = 'lsi', dims = 2:30)
DimPlot(pbmc, label = TRUE)
G1_atac <- pbmc
rm(list=(c("counts","gene.ranges","metadata","p1","p2","tss.ranges","pbmcs","pbmc")))
##################################G2
counts <- Read10X_h5(GP2_atac_h5)
metadata <- read.table(file = GP2_meta, header = TRUE, row.names = 1,sep = ",",stringsAsFactors = FALSE)

pbmc <- CreateSeuratObject(counts = counts, assay = 'G2.peaks', project = 'G2_ATAC', min.cells = 1, meta.data = metadata)


pbmc <- SetFragments(object = pbmc, file = G2_fragment)

pbmc
gc()
pbmc <- NucleosomeSignal(object = pbmc)

pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
pbmc$blacklist_ratio <- pbmc$blacklist_region_fragments / pbmc$peak_region_fragments

p1 <- VlnPlot(pbmc, c('pct_reads_in_peaks', 'peak_region_fragments'), pt.size = 0.1)
p2 <- VlnPlot(pbmc, c('blacklist_ratio', 'nucleosome_signal'), pt.size = 0.1) & scale_y_log10()

p1 | p2

pbmc$nucleosome_group <- ifelse(pbmc$nucleosome_signal > 10, 'NS > 10', 'NS < 10')
FragmentHistogram(object = pbmc, group.by = 'nucleosome_group')

# create granges object with TSS positions
gene.ranges <- genes(EnsDb.Hsapiens.v86)
seqlevelsStyle(gene.ranges) <- 'UCSC'
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding',]
gene.ranges <- keepStandardChromosomes(gene.ranges, pruning.mode = 'coarse')

tss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges),
  ranges = IRanges(start = start(gene.ranges), width = 2),
  strand = strand(gene.ranges)
)

seqlevelsStyle(tss.ranges) <- 'UCSC'
tss.ranges <- keepStandardChromosomes(tss.ranges, pruning.mode = 'coarse')

# to save time use the first 2000 TSSs
pbmc <- TSSEnrichment(object = pbmc, tss.positions = tss.ranges[1:2000])


pbmc$high.tss <- ifelse(pbmc$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(pbmc, group.by = 'high.tss') + ggtitle("TSS enrichment score") + NoLegend()

##################################intersecting
intersecting.regions <- GetIntersectingFeatures(
  object.1 = G1_atac,
  object.2 = G2_atac,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)

# choose a subset of intersecting peaks
peaks.use <- sample(intersecting.regions[[1]], size = 10000, replace = FALSE)

# count fragments per cell overlapping the set of peaks in the 10x data
sci_peaks_tenx <- FeatureMatrix(
  fragments = GetFragments(object = G2_atac, assay = 'G2.peaks'),
  features = StringToGRanges(peaks.use,sep = c(":","-")),
  cells = colnames(G2_atac)
)

# create a new assay and add it to the 10x dataset
G2_atac[['testpeaks']] <- CreateAssayObject(counts = sci_peaks_tenx, min.cells = 1)
G2_atac <- RunTFIDF(object = G2_atac, assay = 'testpeaks')
##################################integration
# find integration anchors between 10x and G1_atac-ATAC

anchors <- FindIntegrationAnchors(
  object.list = list(G2_atac, G1_atac),
  anchor.features = peaks.use,
  assay = c("testpeaks","G1.peaks"),
  k.filter = NA)

Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07s  
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Error in DietSeurat(object = object.list[[i]], assays = assay[i], features = anchor.features,  : 
  The default assay is slated to be removed, please change the default assay

##################################sessionInfo()
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)
Signac_0.2.4            
Seurat_3.1.4

**Comment by millersan** [comment]
I check the file's chr:xxxx-xxxx and I found the different.
Now I solve the problem. Thanks a lot!
