### ISSUE TITLE
wrong dataset assignment

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#144]
I noticed that the merged dataset does not have the right dataset assignment? Maybe I am missing something here, is this normal?
[Merging_PBMC.pdf](https://github.com/timoast/signac/files/4536261/Merging_PBMC.pdf)

**Comment by rojinsafavi** [comment]
It's a bit strange. When I call a specific barcode, it's dataset label is correct

![image](https://user-images.githubusercontent.com/19545198/80316875-4bdfa600-87b5-11ea-9e5d-86de9d7e40df.png)

**Comment by timoast** [comment]
When I run `combined$dataset` I see the correct assignments, so this seems a bit weird. I think the jupyter notebook could be displaying it incorrectly, especially given that it's showing different information when printing all cells vs just one individual cell as you showed above. Can you replicate this in a standard R session (not in the notebook)?

**Comment by rojinsafavi** [comment]
yeah, that's weird. I will give it a try later, and let you know. Meanwhile, I'm gonna close the issue! thanks :-)
