### ISSUE TITLE
integrating scATAC-seq data

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#145]
Hello,
Is there a way to integrate more than two samples?
Thanks

**Comment by timoast** [comment]
Yes, you can have as many objects as you want in the object list specified in `FindIntegrationAnchors` (https://satijalab.org/signac/articles/integration.html#integration). See the Seurat site for some more examples: https://satijalab.org/seurat/v3.1/integration.html. You can also integrate multiple samples with harmony, running the same code as shown in the [vignette](https://satijalab.org/signac/articles/integration.html#integration-with-harmony-1) but with >2 groups

**Comment by ahmedabbas81** [comment]
Thank you. But how can I get the intersection peaks for more than 2 objects using this function `GetIntersectingFeatures()`?

**Comment by timoast** [comment]
You will need to follow the [merge vignette](https://satijalab.org/signac/articles/merging.html), then with the final merged object you can run `SplitObject` to split into separate datasets that contain the same set of features

**Comment by ahmedabbas81** [comment]
ok, thank you

**Comment by mudappathir** [comment]
I have gone through vignettes of scatac merge and integration. I am currently working on 4 scatac datasets which were obtained in different time points. Also there are scRNA datasets for these time points. What is the best approach to clustering and integrating scATAC and scRNA seq? For scATAC should I first merge (https://satijalab.org/signac/articles/merging.html) and then integrate (https://satijalab.org/signac/0.2/articles/integration.html).

**Comment by yasin-uzun** [comment]
Hi. I have the same problem as  mudappathir. I have X number of samples. For each sample, I have scRNA and scATAC. I want to integrate everything (scRNA + scATAC). Is there a solution for this? What is the best way?
