### ISSUE TITLE
RunTF-IDF methods difference

### ISSUE THREAD

**Issue by wangmeijiao** [timoast/signac#146]
Dear Tim,

   I noticed that the RunTF-IDF function had four methods to perform the LSI algorithm. After a full test of all four methods with the same scATAC data (around 7000 cells of 10X), I happened to realize that the final dimension space may vary with methods used. (For example, two separated pseudotime paths with the method 1,3 but only one with  method 2.)  Could you please explain a few word about the difference of these LSI methods and which one do you recommend for some reason (especially for datasets with low-depth cells)?

**Comment by timoast** [comment]
The term-frequency inverse-document-frequency aims to combine local and global weighting functions to normalize the matrix before running singular value decomposition. See [here](https://en.wikipedia.org/wiki/Latent_semantic_analysis#Latent_semantic_indexing) for more details.

The "standard" TF-IDF method used for text analysis computes the TF-IDF matrix as TF x log(IDF). This is available as **method 2**. We found a modification to this method tends to perform better for scATAC-seq data as it produces a better distribution of values. This method computes the TF-IDF matrix as log(TF x IDF), and is available as **method 1**. Similar improvements were found by Andrew Hill by taking TF-IDF = log(TF) x log(IDF), and is available as **method 3**. See [here](http://andrewjohnhill.com/blog/2019/05/06/dimensionality-reduction-for-scatac-data/) for more details. Finally, [10x Genomics](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/algorithms/overview#clustering) uses only the IDF matrix (no TF normalization) in their cellranger-atac software, and this is available as **method 4**.

I recommend using the default (method 1), as this has performed the best in my experience.

See the documentation for the RunTFIDF function: https://satijalab.org/signac/reference/RunTFIDF.html

Here are some slides from a talk I gave that have some more details about the TF-IDF method: https://www.dropbox.com/s/tewlbj8arbmh20e/scgd_2020_stuart.pdf?dl=1

**Comment by wangmeijiao** [comment]
Thanks Tim, for your quick response, and this explained the similar result of method 1 and 3, which both are TF-IDF log normalized. Thanks for the links and  they further explained much more questions I have.
