### ISSUE TITLE
GenomeBinMatrix - problem with code from vignette

### ISSUE THREAD

**Issue by ltosti** [timoast/signac#147]
Hi @timoast ,

when I run the GenomeBinMatrix as described in the vignette:
```
bin_matrix <- GenomeBinMatrix(
  fragments = fragment.path,
  genome = 'hg19',
  binsize = 5000
)
```

I get the following error:
```
Error in tileGenome(seqlengths = genome, tilewidth = binsize, cut.last.tile.in.chrom = TRUE): 'seqlengths' must be a non-empty numeric vector
Traceback:

1. GenomeBinMatrix(fragments = fragment.path, genome = 'hg19', binsize = 5000)
2. tileGenome(seqlengths = genome, tilewidth = binsize, cut.last.tile.in.chrom = TRUE)
3. stop("'seqlengths' must be a non-empty numeric vector")
```

I guess the option `genome` should be a numeric value and not `'hg19'`? Any idea about how to retrieve the correct number?

Thanks!

**Comment by timoast** [comment]
The vignette is incorrect and will be updated, but the documentation for the function is correct: https://satijalab.org/signac/reference/GenomeBinMatrix.html

The `genome` parameter should be a vector of genome sizes, which you can find by running [`seqlengths`](https://www.rdocumentation.org/packages/GenomeInfoDb/versions/1.8.3/topics/seqinfo) on a [BSgenome](https://bioconductor.org/packages/release/bioc/html/BSgenome.html) object.

**Comment by ltosti** [comment]
Thank you for the speedy reply. Yes, you are right, I did the following and it worked:

```
hg19 = seqlengths(BSgenome.Hsapiens.UCSC.hg19)

bin_matrix <- GenomeBinMatrix(
  fragment.path,
  hg19,
  binsize = 5000,
  chunk = 50
)
```

Sorry, I hadn't checked the documentation properly!
