### ISSUE TITLE
Error in FindTransferAnchors

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#149]
So I have two batches that I would like to 
1. batch correct and merge
2. label transfer from scRNA

I cannot figure out why I am getting this error? I would very much appreciate if you can help me with that. The code is attached here.

![image](https://user-images.githubusercontent.com/19545198/80562160-bce0b280-899b-11ea-8a51-c8e36c32e481.png)

[harmony_label.pdf](https://github.com/timoast/signac/files/4549829/harmony_label.pdf)

**Comment by timoast** [comment]
I think this is the same issue as https://github.com/satijalab/seurat/issues/2726, I will look into this today

**Comment by rojinsafavi** [comment]
thank you

**Comment by timoast** [comment]
This has now been fixed and will be available on the develop branch of Seurat soon (hopefully tomorrow). This issue was due to a bug in subsetting cells in the SCT assay

**Comment by rojinsafavi** [comment]
Hello,
I was wondering if the Seurat has been updated to resolve this issue?

**Comment by timoast** [comment]
Yes, this is now fixed on the develop branch of Seurat (https://github.com/satijalab/seurat/commit/0ef1df468576075c2f4298240c190e5f888935e1)
