### ISSUE TITLE
motif analysis

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#151]
I'm trying to do motif enrichment between two of my clusters. As it was recommended, I used JASPAR2020 with 633 motif. The strange thing is that all the motifs are identified as having differential activity between the two clusters (with p-val from ^-13 - ^-288). I was wondering if you know why this might be happening?

**Comment by timoast** [comment]
Can you provide the full code you're running?

**Comment by rojinsafavi** [comment]
Sure I'll post that shortly

**Comment by rojinsafavi** [comment]
Here is my code:
[motiffAnalysis-seurat-report.pdf](https://github.com/timoast/signac/files/4565578/motiffAnalysis-seurat-report.pdf)

**Comment by timoast** [comment]
You're using quite a small number of background peaks here (the default is 40,000, you've set it to 10,000), what happens if you increase it?

It also looks like lots of the DA peaks have 0 counts for all cells one group which is a bit unusual. Can you post the code used to create the object?

**Comment by rojinsafavi** [comment]
I tried with 40,000 and was getting the same results, I will post the full code today or tomorrow, thank you!

**Comment by rojinsafavi** [comment]
[MergingObjects_seurat.pdf](https://github.com/timoast/signac/files/4569343/MergingObjects_seurat.pdf)
[QC.pdf](https://github.com/timoast/signac/files/4569344/QC.pdf)
[label_and_motif.pdf](https://github.com/timoast/signac/files/4569342/label_and_motif.pdf)

**Comment by rojinsafavi** [comment]
Hello again,
Any updates on this? Thank you!

**Comment by timoast** [comment]
In the document you sent initially (motiffAnalysis-seurat-report.pdf) you created the motif matrix with the wrong assay (the "ATAC" assay rather than the "peaks" assay that contains the common peaks). That's why there are so many peaks in the assay (~900k) and so many of them have zero counts for a lot of cells. If you run the analysis with the "peaks" assay, as you did in label_and_motif.pdf, the results look fine. I would remove the "ATAC" assay entirely to avoid these types of problems.

**Comment by rojinsafavi** [comment]
@timoast yes, but the problem is that all the motifs have very small p_vals (if you look at the very last table in label_and_motif.pdf), isn't that a problem?

**Comment by timoast** [comment]
Not all the motifs have a small p-value, only 18 are shown in the document and 633 were tested.

**Comment by rojinsafavi** [comment]
The tail is shown on the last page

Here is the full table:

  | motif | observed | background | percent.observed | percent.background | fold.enrichment | pvalue | motif.name
-- | -- | -- | -- | -- | -- | -- | -- | --

MA0497.1 | 1319 | 10815 | 67.02236 | 27.0375 | 2.478867 | 9.227461e-317 | MEF2C
MA0052.4 | 1337 | 11252 | 67.93699 | 28.1300 | 2.415108 | 9.763872e-311 | MEF2A
MA0773.1 | 1090 | 7612 | 55.38618 | 19.0300 | 2.910467 | 2.792275e-300 | MEF2D
MA0660.1 | 1026 | 6782 | 52.13415 | 16.9550 | 3.074854 | 1.743609e-297 | MEF2B
MA0050.2 | 1364 | 14697 | 69.30894 | 36.7425 | 1.886343 | 1.086144e-198 | IRF1
MA1596.1 | 1035 | 9136 | 52.59146 | 22.8400 | 2.302603 | 3.759957e-191 | ZNF460
MA0149.1 | 1233 | 12493 | 62.65244 | 31.2325 | 2.006001 | 1.726944e-190 | EWSR1-FLI1
MA0080.5 | 1291 | 13573 | 65.59959 | 33.9325 | 1.933238 | 5.372397e-190 | SPI1
MA1112.2 | 792 | 5705 | 40.24390 | 14.2625 | 2.821658 | 2.758381e-187 | NR4A1
MA0073.1 | 1013 | 8919 | 51.47358 | 22.2975 | 2.308491 | 3.618610e-186 | RREB1
MA1652.1 | 1024 | 9094 | 52.03252 | 22.7350 | 2.288653 | 4.479882e-186 | ZKSCAN5
MA1540.1 | 678 | 4335 | 34.45122 | 10.8375 | 3.178890 | 1.059273e-183 | NR5A1
MA1107.2 | 998 | 8780 | 50.71138 | 21.9500 | 2.310314 | 1.729500e-182 | KLF9
MA0504.1 | 761 | 5442 | 38.66870 | 13.6050 | 2.842242 | 4.236080e-180 | NR2C2
MA0901.2 | 929 | 7805 | 47.20528 | 19.5125 | 2.419233 | 1.734711e-179 | HOXB13
MA0508.3 | 978 | 8595 | 49.69512 | 21.4875 | 2.312746 | 1.187030e-177 | PRDM1
MA0592.3 | 681 | 4494 | 34.60366 | 11.2350 | 3.079987 | 9.311594e-177 | ESRRA
MA1643.1 | 895 | 7394 | 45.47764 | 18.4850 | 2.460246 | 9.588426e-176 | NFIB
MA0599.1 | 1021 | 9355 | 51.88008 | 23.3875 | 2.218282 | 1.670059e-174 | KLF5
MA0130.1 | 1034 | 9570 | 52.54065 | 23.9250 | 2.196056 | 2.810929e-174 | ZNF354C
MA0090.3 | 780 | 5893 | 39.63415 | 14.7325 | 2.690253 | 1.477477e-170 | TEAD1
MA1125.1 | 1216 | 12815 | 61.78862 | 32.0375 | 1.928634 | 3.522207e-170 | ZNF384
MA1111.1 | 669 | 4477 | 33.99390 | 11.1925 | 3.037204 | 1.245509e-169 | NR2F2
MA0141.3 | 620 | 3898 | 31.50407 | 9.7450 | 3.232844 | 4.358360e-169 | ESRRB
MA0039.4 | 1016 | 9442 | 51.62602 | 23.6050 | 2.187080 | 1.842805e-168 | KLF4
MA0152.1 | 976 | 8834 | 49.59350 | 22.0850 | 2.245574 | 1.801861e-167 | NFATC2
MA1522.1 | 949 | 8431 | 48.22154 | 21.0775 | 2.287821 | 7.720097e-167 | MAZ
MA0517.1 | 1073 | 10432 | 54.52236 | 26.0800 | 2.090581 | 1.526522e-166 | STAT1::STAT2
MA1648.1 | 666 | 4500 | 33.84146 | 11.2500 | 3.008130 | 2.088285e-166 | TCF12(var.2)
MA1587.1 | 835 | 6754 | 42.42886 | 16.8850 | 2.512814 | 2.860133e-166 | ZNF135
⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮
MA1509.1 | 71 | 591 | 3.607724 | 1.4775 | 2.441776 | 4.786455e-12 | IRF6
MA0664.1 | 110 | 1138 | 5.589431 | 2.8450 | 1.964651 | 1.350592e-11 | MLXIPL
MA0862.1 | 55 | 445 | 2.794715 | 1.1125 | 2.512104 | 4.172904e-10 | GMEB2
MA0763.1 | 138 | 1654 | 7.012195 | 4.1350 | 1.695815 | 1.001216e-09 | ETV3
MA0474.2 | 153 | 1921 | 7.774390 | 4.8025 | 1.618821 | 2.950621e-09 | ERG
MA1139.1 | 136 | 1654 | 6.910569 | 4.1350 | 1.671238 | 3.332918e-09 | FOSL2::JUNB(var.2)
MA0877.2 | 63 | 581 | 3.201220 | 1.4525 | 2.203938 | 4.651383e-09 | BARHL1
MA1484.1 | 164 | 2114 | 8.333333 | 5.2850 | 1.576790 | 4.922019e-09 | ETS2
MA0760.1 | 176 | 2312 | 8.943089 | 5.7800 | 1.547247 | 5.161293e-09 | ERF
MA0711.1 | 41 | 310 | 2.083333 | 0.7750 | 2.688172 | 9.803650e-09 | OTX1
MA0641.1 | 182 | 2444 | 9.247967 | 6.1100 | 1.513579 | 1.384740e-08 | ELF4
MA0076.2 | 196 | 2729 | 9.959350 | 6.8225 | 1.459780 | 5.496328e-08 | ELK4
MA1140.2 | 119 | 1470 | 6.046748 | 3.6750 | 1.645374 | 7.596602e-08 | JUNB(var.2)
MA0834.1 | 126 | 1588 | 6.402439 | 3.9700 | 1.612705 | 9.501038e-08 | ATF7
MA1136.1 | 132 | 1689 | 6.707317 | 4.2225 | 1.588471 | 1.100323e-07 | FOSB::JUNB(var.2)
MA0098.3 | 158 | 2120 | 8.028455 | 5.3000 | 1.514803 | 1.262331e-07 | ETS1
MA0748.2 | 125 | 1591 | 6.351626 | 3.9775 | 1.596889 | 1.817873e-07 | YY2
MA1483.1 | 152 | 2044 | 7.723577 | 5.1100 | 1.511463 | 2.524916e-07 | ELF2
MA0527.1 | 84 | 1004 | 4.268293 | 2.5100 | 1.700515 | 1.758732e-06 | ZBTB33
MA0475.2 | 136 | 1872 | 6.910569 | 4.6800 | 1.476617 | 3.706982e-06 | FLI1
MA0024.3 | 49 | 501 | 2.489837 | 1.2525 | 1.987894 | 4.511794e-06 | E2F1
MA0864.2 | 54 | 615 | 2.743902 | 1.5375 | 1.784652 | 3.300651e-05 | E2F2
MA1129.1 | 97 | 1315 | 4.928862 | 3.2875 | 1.499274 | 5.187200e-05 | FOSL1::JUN(var.2)
MA0156.2 | 117 | 1663 | 5.945122 | 4.1575 | 1.429975 | 6.900809e-05 | FEV
MA0594.2 | 34 | 353 | 1.727642 | 0.8825 | 1.957668 | 1.636641e-04 | HOXA9
MA0749.1 | 26 | 244 | 1.321138 | 0.6100 | 2.165800 | 1.932008e-04 | ZBED1
MA0470.2 | 43 | 522 | 2.184959 | 1.3050 | 1.674298 | 7.496453e-04 | E2F4
MA0759.1 | 103 | 1526 | 5.233740 | 3.8150 | 1.371885 | 7.745521e-04 | ELK3
MA0028.2 | 95 | 1416 | 4.827236 | 3.5400 | 1.363626 | 1.460432e-03 | ELK1
MA1475.1 | 74 | 1096 | 3.760163 | 2.7400 | 1.372322 | 3.946959e-03 | CREB3L4(var.2)

**Comment by timoast** [comment]
I think the reason for this is that a sub-optimal background set of peaks is being used to compare with the differentially accessible set. Since you contrasted two groups of cells in the `FindMarkers` call to identify the differentially accessible set, you should use a background set of peaks chosen from peaks that are accessible in those groups of cells. For example:

```r
# find peaks open in the group of cells compared in FindMarkers
cells <- WhichCells(DF, idents = c("label1", "label2"))
open.peaks <- GetAssayData(DF, assay = "peaks", slot = "counts")[, cells]
peaks.use <- names(which(rowSums(open.peaks > 0) > 10))

# find a matched background set
peaks.matched <- MatchRegionStats(
  meta.feature = GetAssayData(DF, assay = "peaks", slot = "meta.features")[peaks.use, ],
  regions = head(rownames(da_peaks), 1000),
  n = 30000
)

# test enrichment
enriched.motifs <- FindMotifs(
  object = DF,
  features = head(rownames(da_peaks), 1000),
  background = peaks.matched
)
```

You can also adjust the raw p-values for multiple testing (using the bonferroni or benjamini-hochberg method for example)

You should also filter the differentially accessible peaks that you're putting into the motif analysis first, rather than taking all peaks output by `FindMarkers`.

I'll try to update the motif vignette to include this information in the future, and maybe add another function to easily pull the peaks accessible in a subset of cells.

**Comment by rojinsafavi** [comment]
Thanks @timoast , I will give that a try and let you know if I have a question :-)

**Comment by rojinsafavi** [comment]
@timoast I did as you suggested, and I ended up with 10705 cells that had label1 or label2. But I am still getting all motifs as DE. And as you said I am only inputting the first 1000 DE peaks into the motif analysis. 
But I am still observing  similar thing as before (all motifs have small adj pval)

**Comment by rojinsafavi** [comment]
And I calculated the adjusted p_val, all were significant and small

**Comment by timoast** [comment]
> I did as you suggested, and I ended up with 10705 cells that had label1 or label2.

I was suggesting that you subset the peaks used to find the background set of peaks,  not the cells

**Comment by rojinsafavi** [comment]
@timoast by cells I meant using whichcells as you noted. I put the code here. The only thing that I decided to change was using the cluster id instead of cluster label(which was obtained by scRNA and atacseq integration). I am not sure what I am doing wrong here, but we are getting over 500 overexpressed motifs. And with chromVAR I am getting over 500 motifs with significant differential activity

<img width="747" alt="Screen Shot 2020-05-07 at 9 57 28 AM" src="https://user-images.githubusercontent.com/19545198/81322883-70efd680-9049-11ea-9865-7710a430276b.png">
<img width="557" alt="Screen Shot 2020-05-07 at 9 58 00 AM" src="https://user-images.githubusercontent.com/19545198/81322893-74835d80-9049-11ea-84f5-4f9105cbff94.png">
<img width="744" alt="Screen Shot 2020-05-07 at 9 58 40 AM" src="https://user-images.githubusercontent.com/19545198/81322902-777e4e00-9049-11ea-9697-066ae6680cff.png">
<img width="733" alt="Screen Shot 2020-05-07 at 9 58 48 AM" src="https://user-images.githubusercontent.com/19545198/81322907-78af7b00-9049-11ea-83de-cc5f94482731.png">
<img width="739" alt="Screen Shot 2020-05-07 at 9 58 54 AM" src="https://user-images.githubusercontent.com/19545198/81322912-7a793e80-9049-11ea-8dad-13e0fa5fe59d.png">
<img width="741" alt="Screen Shot 2020-05-07 at 10 10 17 AM" src="https://user-images.githubusercontent.com/19545198/81323929-0c357b80-904b-11ea-815d-e977a8ae1dbf.png">
<img width="752" alt="Screen Shot 2020-05-07 at 10 10 37 AM" src="https://user-images.githubusercontent.com/19545198/81323932-0d66a880-904b-11ea-96f6-596c6409e30e.png">

**Comment by timoast** [comment]
I think the issue here is still that the background peaks are not matched properly with the test peaks, so they're effectively coming from a different population that the DA peaks are drawn from, and all the motifs look "significant". You can try tweaking the set of background peaks further, but the relative p-values for different motifs are still informative here. You can see that the top motifs have p-values that are far far smaller than later motifs. Setting a higher p-value cutoff should give a reasonable set of enriched motifs.
