### ISSUE TITLE
appending to loaded JASPAR db

### ISSUE THREAD

**Issue by jlmalin** [timoast/signac#153]
Hi Tim, 

I realize that loading JASPAR motifs into signac is done via a function of TFBSTools (via _getMatrixSet_), but I was hoping you or a fellow user could shed some light on how can I 
append to the set of motifs used for downstream analysis. 

Thus far, I have the database of pfms loaded via:
_pfm <- getMatrixSet(x = JASPAR2018, opts = list(all = T))_
It contains motifs for hundreds of TFs, but not for KLF2 or KLF6 (MA1515.1 and MA1517.1). However, these are directly downloadable as pfms from the JASPAR website itself:

http://jaspar.genereg.net/api/v1/matrix/MA1515/versions.jaspar
>MA1515.1	KLF2
A  [  1054   2510    741    403   4622      0   1702      0    128     68   1838 ]
C  [  1376   1103   4622   4622   2265   4622    274   4622   4622   4622   1142 ]
G  [  1320   2112    495    186   1060      0   2920     49    195    105    389 ]
T  [   872    433    346    312    214     78    167     22      9    444   1253 ]

http://jaspar.genereg.net/api/v1/matrix/MA1517/versions.jaspar
>MA1517.1	KLF6
A  [   443   1035    569    432   2192      0   1024      0     25     71    955 ]
C  [   624    490   2192   2192    284   2192      0   2192   2192   2192    665 ]
G  [   626   1157    332    298     60      0   2192      0     60     12     52 ]
T  [   499    136    219    140     60     24      0      0      0     64    520 ]

I've looked at the TFBStools documentation to see if there's a way to add motifs to my loaded pfms. There are functions described for database operations "to initialize, store matrix or delete matrix in JASPAR database." None seem to be able to append to an existing db new pfms in a text file. 

Googling, I found references to conversion from .csv to .sql but it's not clear if this would be a useful pre-processing step, or even how to format the above pfm in a .csv (eg are brackets included?). I have no knowledge of working with databases.

Do you have suggestions on how I can incorporate these pfms into the JASPAR database used by signac? If it's not possible to alter the loaded db, I'd settle for being able to load
these pfms separately in a way that permits downstream analysis.

Thank you,
Justin

**Comment by timoast** [comment]
Hi Justin, you should be able to append to the `PFMatrixList` (output of `getMatrixSet(x = JASPAR2018, opts = list(all = T))`) if you have another PFMatrix or PFMatrixList using `c()`.

The TFBSTools vignette shows how to create these PFMatrix objects (https://www.bioconductor.org/packages/release/bioc/vignettes/TFBSTools/inst/doc/TFBSTools.html), so if you have the pfms for those TFs you should be able to create a new PFMatrixList and append it to the main list using: `all.pfm <- c(pfm, new.pfm)`

Alternatively, I think those PFMs are part of JASPAR2020 which is not on bioconductor yet but you could try installing it from https://github.com/da-bar/JASPAR2020 using devtools:

```r
devtools::install_github("da-bar/JASPAR2020")
```

**Comment by jlmalin** [comment]
Thanks, Tim. Your first suggestion worked great: after using the PFMatrix template in the tutorial and coercing the resulting PFMatrix using PFMatrixList(), I was able to use c() to append the new motif to the existing object.

Incidentally, JASPAR 2020 installed correctly, but I got this error when I tried to extract the pfms:

> pfm <- getMatrixSet(x = JASPAR2020, opts = list(all = T))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'getMatrixSet' for signature '"JASPAR2020"'

**Comment by timoast** [comment]
I think you just need to load the TFBSTools package (`library(TFBSTools)`)

**Comment by jlmalin** [comment]
Actually, the library was already loaded.
> library(TFBSTools)
> pfm <- getMatrixSet(x = JASPAR2020, opts = list(all = T))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'getMatrixSet' for signature '"JASPAR2020"'

**Comment by Lesdormis** [comment]
Hi @jlmalin sorry to reopen this issue,
I was wondering have you figured out a way to solve the JASPAR2020 issue?
I came across with the same problem currently with TFBSTools

Thanks,

**Comment by jlmalin** [comment]
Hi Shaowen,
Sorry, but I haven’t figured it out. Been using 2018 version. Justin

**Comment by Lesdormis** [comment]
No problem, thanks for the quick response.
Actually, if you do this in the R 4.0 version, I think it works fine.

Best,
Shaowen

**Comment by jlmalin** [comment]
Ah, good find. Thanks for letting me know.

Best,
Justin
