### ISSUE TITLE
Creating gene activity matrix with merged fragment files

### ISSUE THREAD

**Issue by jgamache014** [timoast/signac#156]
Hi Tim,

I followed the "scATAC-seq data integration" tutorial to integrate 2 scATAC-seq datasets and am now trying to create a gene activity matrix for the integrated dataset. To do this, I assumed I would need to merge the fragment files, as in the "Merging objects" vignette. After setting the merged_fragments.path <- '.../snATAC/merged_fragments/fragments.tsv.gz', when I try to create the gene activity matrix with the merged fragment file, I get an error as follows:

```r
integrated <- SetFragments(
   object = integrated,
   file = merged_fragments.path
 )
gene.activities <- FeatureMatrix(
   fragments = merged_fragments.path,
   features = genebodyandpromoter.coords,
   cells = colnames(integrated),
   chunk = 20
 )
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=56m 50s
Constructing matrix
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE
```
Any advice you have is much appreciated!

**Comment by timoast** [comment]
Can you post the code you used to create the merged fragment file?

**Comment by jgamache014** [comment]
Here is the code I used to merge the fragment files: 
gzip -dc fragments1690.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"1690_"$4,$5}' - > atac1690_fragments.tsv
gzip -dc fragments730.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,"730_"$4,$5}' - > atac730_fragments.tsv
sort -m -k 1,1V -k2,2n atac730_fragments.tsv atac1690_fragments.tsv > fragments.tsv
bgzip -@ 2 fragments.tsv
tabix -p bed fragments.tsv.gz

I also tried with an "unannotated" version of the merged file and got the same error message. Here's how I made the unannotated version:
gzip -dc fragments1690.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,$4,$5}' - > atac1690_fragments_unannotated.tsv
gzip -dc fragments730.tsv.gz | awk 'BEGIN {FS=OFS="\t"} {print $1,$2,$3,$4,$5}' - > atac730_fragments_unannotated.tsv
sort -m -k 1,1V -k2,2n atac730_fragments_unannotated.tsv atac1690_fragments_unannotated.tsv > fragments_unannotated.tsv
bgzip -@ 2 fragments_unannotated.tsv
tabix -p bed fragments_unannotated.tsv.gz

**Comment by timoast** [comment]
The code looks fine, assuming `1690` and `730` are the cell IDs you added when merging the objects. Are you able to share the fragment file (or a downsampled version, eg one chromosome) that reproduces the error? You can email a link to tstuart@nygenome.org

**Comment by jgamache014** [comment]
1690 and 730 are the sample IDs. I just sent you an email with a link.

**Comment by timoast** [comment]
That error occurs when there are no matching cell barcodes in the fragment file (we'll try to add a more informative error message), so my best guess is that the cell barcodes in the fragment file don't match the cell barcodes in the object. Did you read the count matrix in using `Read10X` by any chance? That will strip the `-1` suffix (in the new version of Seurat we've disabled that behavior), which can create a mismatch between cell barcodes in the object and in the file.

**Comment by jgamache014** [comment]
I used Read10X_h5 to read in the filtered_peak_bc_matrix.h5 file for each sample and the "-1" suffix is still there in the column names. I think it will be helpful for downstream analysis to use the annotated fragment file so each barcode is associated with a specific sample, so I added sample numbers to the column names in the Seurat objects as follows:

atac730=RenameCells(object=atac730,new.names=paste0("730_",colnames(atac730)))
atac1690=RenameCells(object=atac1690,new.names=paste0("1690_",colnames(atac1690)))

Now viewing column names returns the following, which matches the annotated merged fragments file:

> head(colnames(atac730))
[1] "730_AAACGAAAGTGTCGCC-1" "730_AAACGAACAACGCACC-1" "730_AAACGAATCCGAGAGA-1"
[4] "730_AAACGAATCTTTCGAT-1" "730_AAACTCGTCAATGCAC-1" "730_AAACTGCAGAAATGGG-1"
> head(colnames(atac1690))
[1] "1690_AAACGAAAGACCATAA-1" "1690_AAACGAACAACGTAGG-1"
[3] "1690_AAACGAACACTGTCAA-1" "1690_AAACGAAGTAACCCAT-1"
[5] "1690_AAACGAAGTAGACGCA-1" "1690_AAACGAAGTAGCGAGT-1"

Following the "scATAC-seq data integration" tutorial, I attempted to integrate the datasets, but got an error message:

atac730_peaks_atac1690 <- FeatureMatrix(
  fragments = GetFragments(object = atac1690, assay = 'peaks'),
  features = StringToGRanges(peaks.use, sep=c(":","-")),
  cells = colnames(atac1690),
  verbose = TRUE
)

Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=20m 23s
Constructing matrix
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE

**Comment by timoast** [comment]
Are you 100% sure that the cells in the object are present in that fragment file? What happens if you search for a few of them using `grep`? Like I said, the FeatureMatrix function is not finding any of the cell names requested in the file, so the only thing I can think of is that there is a mismatch somewhere.

**Comment by timoast** [comment]
Closing this now as I haven't heard back
