### ISSUE TITLE
Aggregate peaks in a cluster

### ISSUE THREAD

**Issue by orr161** [timoast/signac#159]
Is it possible to aggregate the peaks in a cluster, and have a semi-bulk peak set per cluster, without re-calling the peaks? Will taking the union of the peaks in a cluster be sufficient?

Thank you!

**Comment by timoast** [comment]
Hi, not sure what you mean exactly. Can you elaborate on your question?

**Comment by Connorr0** [comment]
I would recommend looking into Seurat's (and by extension Signac's) `AverageExpression()`.

**Comment by timoast** [comment]
@orr161 closing this now as I haven't heard back, but please re-open if you still require help on this.
