### ISSUE TITLE
Question about motif analysis

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#160]
Hello,
In the tutorial of motif analysis,

you use this command:
```
enriched.motifs <- FindMotifs(
  object = mouse_brain,
  features = head(rownames(da_peaks), 1000)
)
```
shouldn't we only care about da_peaks with adj p-value < 0.05 rather than using all of them (or the top 1000) as in the command? Or there is something that I misunderstand?

Thank you

**Comment by timoast** [comment]
Yes, you should filter based on p-value and/or fold change. In the case shown in the vignette, the first 1000 peaks are all highly significant and for simplicity I just took the top 1000 peaks. I will update the vignette in future to clarify this point.
