### ISSUE TITLE
Data Integration and clusters and differential analysis 

### ISSUE THREAD

**Issue by gouthamatla** [timoast/signac#165]
Hi,

I am trying to integrate two datasets from different conditions. Its one biological sample split into two parts, treated with two different "drugs" (labelled as High and Low) and then we generated scATAC data.  

Here is what I am using to integrate, mostly following the tutorial. Two Seurat objects were created independently and the cells in each dataset were clustered by cell type. Looked promising. No issues there.  Then I did integration.

```
# Add a label for each object.

High$condition <- 'High'
Low$condition <- 'Low'

# get intersecting peaks
intersecting.regions <- GetIntersectingFeatures(
  object.1 = High,
  object.2 = Low,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)

# choose a subset of intersecting peaks.
peaks.use <- sample(intersecting.regions[[1]], size = 100000, replace = FALSE)


# count fragments in "Low" condition for peaks in "High" condition.

Low_with_highPeaks_tenx <- FeatureMatrix(
  fragments = GetFragments(object = Low, assay = 'Low'),
  features = StringToGRanges(peaks.use, sep = c(":", "-")),
  cells = colnames(Low)
)

# Change the delimiter as original delimiter is no longer maintained. To make it compatible with "High" ( chr1-100-200 to chr1:100-200 )
rownames(Low_with_highPeaks_tenx) = sub("-",":",rownames(Low_with_highPeaks_tenx))

# Create assay object with new quantifications.

Low[['highPeaks']] <- CreateAssayObject(counts = Low_with_highPeaks_tenx, min.cells = 1)
Low <- RunTFIDF(object = Low, assay = 'highPeaks')

anchors <- FindIntegrationAnchors(
  object.list = list(High, Low),
  anchor.features = peaks.use,
  assay = c('High', 'highPeaks'),
)

integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = 'lsi',
  dims = 2:30,  # Tried with 1:30, its gives similar results.
  preserve.order = TRUE
)

integrated <- RunSVD(
  object = integrated,
  n = 30,
  reduction.name = 'integratedLSI'
)

integrated <- RunUMAP(
  object = integrated,
  dims = 1:30,
  n.neighbors = 30,
  reduction = 'integratedLSI'
)
```

`DimPlot(integrated, pt.size = 0.2, label=T) + ggplot2::ggtitle("Integrated")
`

![signac_0](https://user-images.githubusercontent.com/4629007/84565769-ca93a100-ad6b-11ea-840a-aacffea3f3b6.PNG)

`DimPlot(integrated, pt.size = 0.2, label=F, group.by = 'condition') + ggplot2::ggtitle("Integrated")
`

![signac_1](https://user-images.githubusercontent.com/4629007/84565773-d4b59f80-ad6b-11ea-9421-4a4d412760e2.png)

`DimPlot(integrated,split.by="condition", label=T, pt.size = 0.2) + ggplot2::ggtitle("Integrated")
`

![signac_2](https://user-images.githubusercontent.com/4629007/84565779-ded79e00-ad6b-11ea-9f93-0e381cc89849.PNG)

What I am confused about is the last plot. When I split the clusters in to conditions, why the cluster names do not match, I was hoping that the cluster names would be independent of condition. Is this normal ? Why the cluster numbers from "High" do not overlap with "Low" given that the data is integrated and split just for plotting ?

**Comment by gouthamatla** [comment]
I realized that the cluster numbers are coming from original clusters of individual objects. It looks meaningful. But how can I perform differential analysis between conditions per cluster if they have different cluster IDs  ?

**Comment by timoast** [comment]
You need to cluster using the integrated LSI rather than that the original LSI, and then combine the cluster and condition information as shown in the [Seurat vignette](https://satijalab.org/seurat/v3.1/immune_alignment.html)
