### ISSUE TITLE
Error: scanTabix: 'chr1' not present in tabix index path: 

### ISSUE THREAD

**Issue by mailcolm9** [timoast/signac#168]
Hello,

I came across above issue about reference genome. I used hg38 and mm10 mixed reference genome  to aligh my data by cellranger atac. When I use signac to analyze my data, I got this error. I know the contig name in my reference is like "GRCh38_chr1", don't know whether this is the source of this issue.
Could you help me out?
Thanks!

Sincerely,
Z

**Comment by timoast** [comment]
See #169 , you need to make sure the seqnames of the genomic ranges you request from the fragment file match the seqnames in the fragment file
