### ISSUE TITLE
Human and mouse cell mixture analysis

### ISSUE THREAD

**Issue by mailcolm9** [timoast/signac#169]
Hi,

I am trying your pipeline on my scATAC analysis with the 10X genomics human and mouse cell mixture data, but I think the hybrid reference genome has different contig names as "GRCh28_chr1". so it is incompactible with the contig names in other variables, such as "gene.ranges", from cmd "gene.ranges <- genes(EnsDb.Hsapiens.v75)
seqlevelsStyle(gene.ranges) <- 'UCSC' ", which has "chr1". 

I am wondering is there a mouse and human hybrid annotation that can be used in the cell mixture analysis? Or I need to change something by myself?

Thank you so much for your help!

Ale

**Comment by timoast** [comment]
You should be able to do something like this:
```r
library(EnsDb.Hsapiens.v75)

gene.ranges <- genes(EnsDb.Hsapiens.v75)
seqlevelsStyle(gene.ranges) <- 'UCSC'
seqlevels(gene.ranges) <- paste0("GRCh28_", seqlevels(gene.ranges))
```

**Comment by mailcolm9** [comment]
Hi,

Thanks for the reply! I have another question, as we know in the human and mouse cell mixture analysis, I think now the human part is solved but how can I add the mm10 contigs which are in my reference genome already into the EnsDb.Hsapiens.v75? 

Thank you so much!

Z

**Comment by mailcolm9** [comment]
in the reference genome, there are GRCh38_chr1 ..... and mm10_chr1 ..., so I am wondering is there a way to put them together!

Thanks!

**Comment by Puriney** [comment]
Be aware the hg38 and hg19 have different Ensembl db lirary.
```
library(EnsDb.Hsapiens.v86)
library(EnsDb.Hsapiens.v75)
```

Since the EnsDb is just a Grange (data.frame), you can modify the seqnames and combine them to create a species-mix Grange object.

```
library(EnsDb.Hsapiens.v86)
library(EnsDb.Hsapiens.v75)
library(EnsDb.Mmusculus.v79)

gene.ranges <- genes(EnsDb.Hsapiens.v75)
seqlevelsStyle(gene.ranges) <- 'UCSC'
seqlevels(gene.ranges) <- paste0("GRCh38_", seqlevels(gene.ranges))

mm.granges <- genes(EnsDb.Mmusculus.v79)
seqlevels(mm.granges) <- paste0("mm10_", seqlevels(mm.granges))

final_granges <- c(gene.ranges, mm.granges)
length(final_granges)
length(gene.ranges)
length(mm.granges)
```

**Comment by mailcolm9** [comment]
Sorry I need to reopen this isse.

Since our reference genome is customed, I used our gtf file instead of using library.
Howeverr, I can't use function seqlevelStyle and it gives me following error

`Error in .replace_seqlevels_style(x_seqlevels, value) : 
  found no sequence renaming map compatible with seqname style "UCSC" for this object`

Could you inform me what might get wrong? Also if I don't run this line, will it affect later analysis?
Thanks!

Sincerely,
Z

**Comment by mailcolm9** [comment]
Also, I found that I couldn't run the function CreateAssyaObject and NormalizeData. Error messages from both functions are given below.

`Error: Cannot add a different number of cells than already present`

'Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'median': Cannot find 'nCount_RNA' in this Seurat object'

Could you help me to get this out?
Many appreciation.

Sincerely,
Z

**Comment by timoast** [comment]
@mailcolm9 can you open a new issue and provide the full code you're using?

**Comment by mailcolm9** [comment]
Thanks, and I will

**Comment by mailcolm9** [comment]
> @mailcolm9 can you open a new issue and provide the full code you're using?

https://github.com/timoast/signac/issues/172#issue-643464526
