### ISSUE TITLE
Combining Coverage Plots

### ISSUE THREAD

**Issue by SJayYang** [timoast/signac#17]
Hi, 

I was wondering if there was a simple way to put two coverage plots from two conditions and compare them side by side by scaling them the same way. I'm not really aware of how cowplot works or how I'd be able to get the CoveragePlot function with the same y axis limit as another one to compare them. 

Thanks!

**Comment by timoast** [comment]
Hi, I just pushed an update that will allow finer control over the scaling of tracks in `CoveragePlot`. Right now this is only on the develop branch, so to use it install from the develop branch using devtools: `devtools::install("timoast/signac", ref = "develop")`

I added two parameters to `CoveragePlot`: `scale.factor` and `ymax`. You can scale different plots equivalently by setting the same `scale.factor` value, and ensure the track heights are the same by setting `ymax`. Here's an example using data from the [mouse brain vignette](https://satijalab.org/signac/articles/mouse_brain_vignette.htmlhttps://satijalab.org/signac/articles/mouse_brain_vignette.html) where I plot accessibility in a region either with 3 groups of cells together, or as two separate plots and achieve the same track scaling in both plots:

```r
library(Signac)
library(EnsDb.Mmusculus.v79)
library(ggplot2)

brain <- readRDS("brain.rds") # from the mouse brain vignette

p1 <- CoveragePlot(
  object = brain,
  idents = c('Sst', 'Pvalb'),
  region = "chr2-22622205-22643874",
  sep = c(":", "-"),
  annotation = EnsDb.Mmusculus.v79,
  extend.upstream = 5000,
  extend.downstream = 0,
  scale.factor = 1e7,
  ncol = 1
)

p2 <- CoveragePlot(
  object = brain,
  idents = c('Astro'),
  region = "chr2-22622205-22643874",
  sep = c(":", "-"),
  annotation = EnsDb.Mmusculus.v79,
  extend.upstream = 5000,
  extend.downstream = 0,
  ymax = 28,
  scale.factor = 1e7,
  ncol = 1
)

p3 <- cowplot::plot_grid(
  p1, p2,
  ncol = 1
)

p4 <- CoveragePlot(
  object = brain,
  idents = c('Astro', 'Sst', 'Pvalb'),
  region = "chr2-22622205-22643874",
  sep = c(":", "-"),
  annotation = EnsDb.Mmusculus.v79,
  extend.upstream = 5000,
  extend.downstream = 0,
  scale.factor = 1e7,
  ncol = 1
)

cowplot::plot_grid(p3, p4, ncol = 2)
```

![combine_coverage_plots](https://user-images.githubusercontent.com/4591688/64027655-28256c80-cb0f-11e9-96da-e803d242a630.png)


You can see above that plotting one group separately (left) but setting the `scale.factor` and `ymax` values lets you plot it and have the track appear the same as if it were plotted together with the other groups (right).

**Comment by SJayYang** [comment]
Thank you so much! This saved up us a huge headache trying to compare conditions between samples. Have a great day!

**Comment by SJayYang** [comment]
Sorry, one last thing. How can I cite Signac analysis?

**Comment by timoast** [comment]
We currently don't have any plans for a Signac paper, so you can just state the version that you used and link to the github page. You could also consider citing Seurat v3, as Signac is an extension of Seurat: https://doi.org/10.1016/j.cell.2019.05.031

**Comment by SJayYang** [comment]
Hi,

It's not a huge issue, but when changing the axis, some of the values of the coverage plot get cutoff, but we just raise it to super high ymax values in order to ensure the entire graph is shown. Is the normalization changing when we alter the axis? The range at first used to be 0-41, but now it's going from 0-120, and it looks like the peak value is 120 instead of the 40.

**Comment by timoast** [comment]
This will be due to changing the `scale.factor`. As long as the scale factor is constant between tracks, it's not a problem. You should however be sure to set `ymax` sufficiently high to not cut off any values. You could just plot the tracks first without changing `ymax`, take note of the highest y-axis value, then re-plot setting `ymax` to that value for all the tracks.

**Comment by SJayYang** [comment]
Ah I see, I changed both the scale factor as well as the ymax without first considering the fact that the scale factor isn't the same as the original graph. Thanks!

**Comment by Dragonmasterx87** [comment]
@timoast may God bless you bro. You're doing God's work. ymax really helps in CoveragePlot.
