### ISSUE TITLE
Cellranger aggr normalization before using Signac

### ISSUE THREAD

**Issue by chent5** [timoast/signac#171]
Hi,

Thanks a lot for developing this package. I used 10x cellranger-atac aggr to merge different samples and then used signac to analyze the aggregated matrix. 

In 10x cellranger-atac aggr, there are there options for normalization: depth, none and signal. Below are the explanation from 10x website:
1. depth: (default) Subsample fragments from higher-depth GEM wells until they all have an equal number of unique fragments per cell.
2. none: Do not normalize at all.
3. signal: Subsample fragments from GEM wells such that each GEM well library has the same distribution of enriched cut sites along the genome. 

In the normalization part of signac tutorial, it is mentioned "This is a two-step normalization procedure, that both normalizes across cells to correct for differences in cellular sequencing depth, and across peaks to give higher values to more rare peaks." In the identification of differentially accessible peaks, it is mentioned "the total number of fragments was added as a latent variable to mitigate the effect of differential sequencing depth on the result."

Should I normalize the sequencing depth using cellranger-atac aggr before using signac? Which normalization option for cellranger-atac aggr do you recommend?

Thank you so much!

**Comment by timoast** [comment]
Hi, I would recommend choosing the "none" option, as the other options will throw out useful data (see #51)
