### ISSUE TITLE
Error with self defined genome sequence and normalization issue

### ISSUE THREAD

**Issue by mailcolm9** [timoast/signac#172]
Since our reference genome is customed, I used our gtf file instead of using EnsDb.Hsapiens.v75.
Howeverr, I can't use function seqlevelStyle and it gives me following error

`Error in .replace_seqlevels_style(x_seqlevels, value) : found no sequence renaming map compatible with seqname style "UCSC" for this object`

Also, I found that I couldn't run the function CreateAssyaObject and NormalizeData. Error messages from both functions are given below.

`Error: Cannot add a different number of cells than already present`

`Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'median': Cannot find 'nCount_RNA' in this Seurat object`

Tim asked me to give the full code for debugging, and how should I give my full code?
Thanks!

Sincerely,
Z

**Comment by timoast** [comment]
Addressed in https://github.com/timoast/signac/issues/173
