### ISSUE TITLE
Plot heatmap of chromvar result

### ISSUE THREAD

**Issue by raphaela2018** [timoast/signac#175]
Hi, 

I would like to plot a heatmap of chromvar results, specifically, aggregated by cluster or group. But if I use the same way as RNA by running AverageExpression(object, assay = "chromvar",  return.seurat = TRUE or FALSE both) and doHeatmap, it gave me a weird result. How can I plot chromvar result using heatmap? 

Thanks a lot!

**Comment by timoast** [comment]
Weird result in what way? Can you provide a reproducible example, or at least the code you're running?

**Comment by timoast** [comment]
Any update on this?

**Comment by yojetsharma** [comment]
How can we plot chromVar results as heat-map?
