### ISSUE TITLE
What is the value in meta.data$mitochondrial representing?

### ISSUE THREAD

**Issue by luzgaral** [timoast/signac#178]
Hi,

When I read my peaks matrix, I see there is `meta.data$mitochondrial` field. What is the number representing? Total peaks in mitochondrial genes? In some cases, the `meta.data$mitochondrial` value is higher than the number of total peaks in the barcode. It may be somewhere in the documentation, but I couldn't find it.

Thank you!

**Comment by timoast** [comment]
This is metadata generated by the 10x Cellranger pipeline, and refers to the total number of read pairs mapped to the non-nuclear genome: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/singlecell
