### ISSUE TITLE
co-embedding ploting problem

### ISSUE THREAD

**Issue by millersan** [timoast/signac#179]
Hi Tim,
  I have integrated 2 ATAC data, and next, I wanted to co-embedding with integrated RNA data, but the result is very strange, could you please help me?
![234](https://user-images.githubusercontent.com/46741428/87148462-0412ea00-c2e1-11ea-9cc3-76a4aaeed0ae.png)
Here is my code 
```
GP<-readRDS("../GP.rds")
integrated<-readRDS("../integrated.rds")
```
GP
An object of class Seurat 
21398 features across 18728 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, umap, tsne

integrated
An object of class Seurat 
394669 features across 11351 samples within 4 assays 
Active assay: RNA (19767 features, 0 variable features)
 3 other assays present: peaks, sciPeaks, integrated
 2 dimensional reductions calculated: integratedLSI, umap

```
transfer.anchors <- FindTransferAnchors(reference = GP, query = integrated, features = VariableFeatures(object = GP),reference.assay = "RNA", query.assay = "RNA", reduction = "cca")

celltype.predictions <- TransferData(anchorset = transfer.anchors, refdata = GP@meta.data$seurat_clusters, 
    weight.reduction = integrated[["integratedLSI"]])
integrated <- AddMetaData(integrated, metadata = celltype.predictions)

p1<-DimPlot(GP,group.by = "seurat_clusters",label = T)+ggtitle("scRNA-seq")
p2<-DimPlot(integrated,reduction = "umap",group.by = "predicted.id",label = T)+ggtitle("scATAC-seq")
p1
p2
```
![123](https://user-images.githubusercontent.com/46741428/87148553-2ad12080-c2e1-11ea-9225-1dde2d97bb14.png)

```
hist(integrated$prediction.score.max)
abline(v = 0.5, col = "red")
pbmc.atac.filtered <- subset(integrated, subset = prediction.score.max > 0.3)
pbmc.atac.filtered$predicted.id <- factor(pbmc.atac.filtered$predicted.id, levels = levels(integrated))  # to make the colors match
genes.use <- VariableFeatures(GP)
refdata <- GetAssayData(GP, assay = "integrated", slot = "data")[genes.use, ]
imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, weight.reduction = integrated[["integratedLSI"]])
integrated[["RNA"]] <- imputation
coembed <- merge(x = GP, y = integrated)
coembed <- ScaleData(coembed, features = genes.use, do.scale = TRUE)
coembed <- RunPCA(coembed, features = genes.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)
coembed$seurat_clusters<- ifelse(!is.na(coembed$seurat_clusters), coembed$seurat_clusters, coembed$predicted.id)
p1 <- DimPlot(coembed, group.by = "tech")
p2 <- DimPlot(coembed, group.by = "seurat_clusters", label = TRUE, repel = TRUE)
p1 + p2`
```
![234](https://user-images.githubusercontent.com/46741428/87148657-610ea000-c2e1-11ea-9626-e4473808e312.png)

**Comment by timoast** [comment]
It might be because you use the "RNA" assay to find anchors but then impute the "integrated" assay. If that doesn't help, please include the steps required to create the initial objects and ensure it's [formatted](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) and I'll take another look

**Comment by millersan** [comment]
My apologies for the incorrect format, I use Jupiter notebook to create a pdf of my full code, hope you could help me!
[step1.pdf](https://github.com/timoast/signac/files/4918226/step1.pdf)
[step2.pdf](https://github.com/timoast/signac/files/4918228/step2.pdf)

**Comment by timoast** [comment]
Did you try my initial suggestion, to use use the same assay to find anchors that you use to impute?

**Comment by timoast** [comment]
Any update on this?
