### ISSUE TITLE
Unable to install Signac in R version 3.6.3

### ISSUE THREAD

**Issue by paoloabondio** [timoast/signac#180]
**Hi Tim, 
I hope this issue is not a waste of your time. I've tried several times to install the package "Signac" to analyze ATAC-seq data and I always get the following lazy loading error:**

install.packages("Signac")
installing the source package ‘Signac’

provo con l'URL 'https://cran.rstudio.com/src/contrib/Signac_0.2.5.tar.gz'
Content type 'application/x-gzip' length 158168 bytes (154 KB)
downloaded 154 KB

installing *source* package ‘Signac’ ...
** package ‘Signac’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 42067 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/jb/hjyzn79j21b5t0tldh8vbvwh0000gn/T//Rtmp9eiPjc/filea44c1e84aeb3'
ERROR: lazy loading failed for package ‘Signac’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Signac’
Warning in install.packages :
  installation of package ‘Signac’ had non-zero exit status

**I also get the same result when trying to install the development version of the package:**

devtools::install_github("timoast/signac", ref = "develop")
Downloading GitHub repo timoast/signac@develop
Skipping 6 packages not available: GenomeInfoDb, GenomicRanges, IRanges, Rsamtools, S4Vectors, BiocGenerics
✓  checking for file ‘/private/var/folders/jb/hjyzn79j21b5t0tldh8vbvwh0000gn/T/Rtmpn369Sp/remotesabba392febf3/timoast-signac-f469c9e/DESCRIPTION’ ...
─  preparing ‘Signac’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘Signac/.github’
   Removed empty directory ‘Signac/vignettes’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘Signac_0.2.5.tar.gz’
   
 installing *source* package ‘Signac’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 44012 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/jb/hjyzn79j21b5t0tldh8vbvwh0000gn/T//RtmpuGSAa3/fileabe547163636'
ERROR: lazy loading failed for package ‘Signac’
removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Signac’
Errore: Failed to install 'Signac' from GitHub:
  (contertito da avviso) installation of package ‘/var/folders/jb/hjyzn79j21b5t0tldh8vbvwh0000gn/T//Rtmpn369Sp/fileabba792bbbd9/Signac_0.2.5.tar.gz’ had non-zero exit status

**I've tried installing and updating several other packages and dependencies, but it doesn't seem to help.
FYI, my operating system is macOS Catalina version 10.15.5.**
Thanks for your help!

**Comment by timoast** [comment]
I'm not sure what the issue is here, the installation is getting killed (`sh: line 1: 44012 Killed: 9 R_TESTS`). That tends to happen when you run out of memory...although I wouldn't expect that to happen during installation unless you have _very_ little RAM. How much RAM do you have?

**Comment by paoloabondio** [comment]
Hi Tim, thanks for the answer.
My Macbook has a 16GB RAM and more than 100GB of free memory space, so I'm afraid that wouldn't be the problem.

**Comment by timoast** [comment]
Unfortunately I'm not able to reproduce this, I tried on R 3.6.3 on macOS Catalina 10.15.6 and it worked fine. My only suggestion is to try restarting R, reinstalling the dependencies, or maybe reinstall R itself.
