### ISSUE TITLE
Error messages when using MergeWithRegions() and FindIntegrationAnchors() functions

### ISSUE THREAD

**Issue by chent5** [timoast/signac#181]
Thanks a lot for developing this package. I got error messages when integrating 2 scATAC datasets:
1. MergeWithRegions(): Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : invalid character indexing
2. FindIntegrationAnchors(): Error in DietSeurat(object = object.list[[j]], assays = assay[j], features = anchor.features,  : 
  The default assay is slated to be removed, please change the default assay
In addition: Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

The codes I used are listed below:
object1 and object2 are both 10x data processed by Signac.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/40006284/88001329-e78b6480-cacd-11ea-9c1a-c540a471962d.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/40006284/88001333-ebb78200-cacd-11ea-97a3-4d39158dd434.png">

Could you please help to solve these problems? Thanks so much!

**Comment by timoast** [comment]
What's the output of:

```r
length(intersect(rownames(object1[["peaks"]]), rownames(object2[["ob1.Peaks"]])))
```

**Comment by chent5** [comment]
Output is "0"...

**Comment by timoast** [comment]
Ok, my guess is that the default assay for `object1` is not "peaks" when you run `GetIntersectingFeatures`, or possibly there are no intersecting features. Both the errors you're seeing are due to no features in common between the assays you're trying to merge or integrate.

**Comment by chent5** [comment]
Below is how I loaded object1 and object2:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/40006284/88126311-3d7c0d00-cb9f-11ea-97b4-56821a28bfb8.png">
I also double-checked the default assay of object1, which is "peaks". 

After that I followed the online tutorial step by step: (1) find peaks that intersect in both datasets, (2) choose a subset of intersecting peaks, (3) count fragments per cell overlapping the set of peaks in object2 (please see below or the figures I posted before)
<img width="464" alt="image" src="https://user-images.githubusercontent.com/40006284/88126661-0bb77600-cba0-11ea-8187-66fe11c73c53.png">

Here is what intersecting.regions looks like:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/40006284/88126932-98faca80-cba0-11ea-9945-5bd12eb7aa0d.png">

I don't understand why there are no common features in the end...

**Comment by chent5** [comment]
I know where the problem is: The format of chromosome corrdinates is changed in the new assay of object2.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/40006284/88128857-c77aa480-cba4-11ea-89df-454e0b592eda.png">

After I changed them back to "chr:start-end", both functions work. Thanks so much for your help!
