### ISSUE TITLE
Error message when running IntegrateData()

### ISSUE THREAD

**Issue by chent5** [timoast/signac#182]
I posted "Error messages when using MergeWithRegions() and FindIntegrationAnchors() functions (#181)" one day before. After these errors were clear, I got an error message when running IntegrateData() as below:

![image](https://user-images.githubusercontent.com/40006284/88201838-fb41e280-cc15-11ea-9c80-39cf3a89ffa8.png)

Could you help to solve this problem? Thanks so much!

**Comment by timoast** [comment]
Can you provide the full code you're running (not as screenshots)?

**Comment by chent5** [comment]
Please see below:
====== CODE, start =====
library(Signac)
library(Seurat)
library(patchwork)
set.seed(1234)

pbmc <- readRDS("dir_to_object1/object1.rds")
DefaultAssay(pbmc) <- 'peaks'
object1 <- pbmc

pbmc <- readRDS(readRDS("dir_to_object2/object2.rds"))
DefaultAssay(pbmc) <- 'peaks'
object2 <- pbmc
rm(pbmc)

intersecting.regions <- GetIntersectingFeatures(
  object.1 = object1,
  object.2 = object2,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)

peaks.use <- sample(intersecting.regions[[1]], size = 10000, replace = FALSE)

ob1_peaks_in_object2 <- FeatureMatrix(
  fragments = GetFragments(object = object2, assay = 'peaks'),
  features = StringToGRanges(peaks.use, sep = c(":", "-")),
  cells = colnames(object2)
)

object2[['ob1.Peaks']] <- CreateAssayObject(counts = ob1_peaks_in_object2, min.cells = 1)
object2 <- RunTFIDF(object = object2, assay = 'ob1.Peaks')

### The reason why I changed the rownames was mentioned in #181
rownames(object2@assays$ob1.Peaks@counts) <- sub("-", ":", rownames(object2@assays$ob1.Peaks))
rownames(object2@assays$ob1.Peaks@data) <- sub("-", ":", rownames(object2@assays$ob1.Peaks))

anchors <- FindIntegrationAnchors(
  object.list = list(object1, object2),
  anchor.features = peaks.use,
  assay = c('peaks', 'ob1.Peaks'),
  k.filter = NA
)
saveRDS(anchors, file = "anchors.rds")

####  integrate data and create a new merged object
integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = object1[['lsi']],
  dims = 2:30,
  preserve.order = TRUE
)
saveRDS(integrated, file = "Integrated.rds")
====== CODE, end =====

I got the output file of "anchors.rds", but I failed to pass IntegratedData() function. The error message is shown in the screenshot I posted above.

**Comment by timoast** [comment]
The weight.reduction needs to be for the query object rather than the reference object, here you’re passing the dimension reduction for the reference cells. You need to run LSI on the query (object2) and pass weight.reduction=object2[[“lsi”]]

**Comment by chent5** [comment]
I changed the code as below:
integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = object2[['lsi']],
  dims = 2:30,
  preserve.order = TRUE
)

However, I still got the same error messages:
Error in RunIntegration(filtered.anchors = filtered.anchors, normalization.method = normalization.method,  : 
  Query cells not present in supplied DimReduc object. Set weight.reduction to a DimReduc object containing the query cells.
Calls: IntegrateData -> PairwiseIntegrateReference -> RunIntegration

I carefully go through the tutorial online: https://satijalab.org/signac/articles/integration.html
I am a little confused: It seems "sci" is as a reference and "tenx" is a query dataset with a new assay named "sciPeaks". For the function of IntegrateData(), weight.reduction = sci[['lsi']] (reference) rather than tenx[['lsi']] (query).

In my case, no matter reference or query object I set, both don't work... Thus, I have two questions:
(1) What causes this error message?
(2) Should I use reference or query object to pass weight.reduction?

Thanks so much for your help!

**Comment by timoast** [comment]
> I am a little confused: It seems "sci" is as a reference and "tenx" is a query dataset with a new assay named "sciPeaks". For the function of IntegrateData(), weight.reduction = sci[['lsi']] (reference) rather than tenx[['lsi']] (query).

This is not correct, in the vignette `sci` is the query and `tenx` is the reference.

>In my case, no matter reference or query object I set, both don't work... Thus, I have two questions:
(1) What causes this error message?
(2) Should I use reference or query object to pass weight.reduction?

Addressed in #183 

I'm not sure why you're still seeing this error. Can you try passing `weight.reduction="lsi"` instead?

**Comment by chent5** [comment]
I will try weight.reduction="lsi" and let you know whether it works. Thanks a lot for the explanation.

**Comment by chent5** [comment]
It works. Thank you.
