### ISSUE TITLE
AddModuleScore for scATAC

### ISSUE THREAD

**Issue by laurabchopp** [timoast/signac#185]
Hi Tim,

I know the AddModuleScore function is actually part of the Seurat package for RNA analysis, but I'm wondering if it's appropriate to use to score cells for peak accessibility. I've used it as:

`atac.integrated <- AddModuleScore(object = atac.integrated, features = list(PeakList), ctrl = 10, name = "PeakSignature")
`

Where PeakList is a list of hundreds of peaks.

I've tried modulating the ctrl number up to 500 (peak set is > 500 that I'm using for the score), and it doesn't change the result.

The result makes biological sense, but I want to be sure it's an appropriate use of the function, and that I'm not missing a key argument in the code.

Thank you!

**Comment by timoast** [comment]
Hi, I think a better approach for this would be to use chromVAR (https://greenleaflab.github.io/chromVAR/). If you make a binary peak by "module" matrix, where entries are 1 if the peak belongs to the module and 0 otherwise, you should be able to compute the deviation for that group of peaks for each cell. You should be able to supply the peak by module matrix to the RunChomVAR function in Signac through the `motif.matrix` argument

**Comment by timoast** [comment]
Just to follow up, this function will do what you need (I'll add it to the next Signac version):

```r
library(fastmatch)
library(Matrix)

AddChromatinModule <- function(object, features, genome, assay) {
  # first find index of each feature
  feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = object[[assay]]))
  j <- sapply(X = seq_along(along.with = features), FUN = function(x) {
    rep(x = x, length(x = features[[x]]))
  })
  
  # construct sparse matrix with features
  mat <- sparseMatrix(
    i = unlist(x = feat.idx, use.names = FALSE),
    j = unlist(x = j, use.names = FALSE),
    x = 1,
    dims = c(nrow(x = object[[assay]]), length(x = features))
  )
  rownames(x = mat) <- rownames(x = object[[assay]])
  colnames(x = mat) <- names(x = features)
  
  # run chromVAR
  cv <- RunChromVAR(
    object = object,
    assay = assay,
    motif.matrix = mat,
    genome = genome,
    new.assay.name = "chromvar"
  )
  
  # add module scores to metadata
  chromvar.data <- GetAssayData(object = cv, assay = "chromvar", slot = "data")
  object <- AddMetaData(object = object, metadata = as.data.frame(x = t(x = chromvar.data)))
  return(object)
}
```

**Comment by laurabchopp** [comment]
Hi Tim,

Thanks for the help! I tried the function as follows:



 ```
library(fastmatch)
library(Matrix)

AddChromatinModule <- function(object, features, genome, assay) {
  # first find index of each feature
  feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = object[[assay]]))
  j <- sapply(X = seq_along(along.with = features), FUN = function(x) {
    rep(x = x, length(x = features[[x]]))
  })
  
  # construct sparse matrix with features
  mat <- sparseMatrix(
    i = unlist(x = feat.idx, use.names = FALSE),
    j = unlist(x = j, use.names = FALSE),
    x = 1,
    dims = c(nrow(x = object[[assay]]), length(x = features))
  )
  rownames(x = mat) <- rownames(x = object[[assay]])
  colnames(x = mat) <- names(x = features)
  
  # run chromVAR
  cv <- RunChromVAR(
    object = object,
    assay = assay,
    motif.matrix = mat,
    genome = genome,
    new.assay.name = "chromvar"
  )
  
  # add module scores to metadata
  chromvar.data <- GetAssayData(object = cv, assay = "chromvar", slot = "data")
  object <- AddMetaData(object = object, metadata = as.data.frame(x = t(x = chromvar.data)))
  return(object)
}

atac.integrated2 <- AddChromatinModule(object = atac.integrated2, features = peaklist, genome = mm10, assay = "MergedPeaks")


```



And got the following error message. 

Error in sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j,  : 
  NA's in (i,j) are not allowed 

I ran traceback and got

3.
stop("NA's in (i,j) are not allowed") 
2.
sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j, 
    use.names = FALSE), x = 1, dims = c(nrow(x = object[[assay]]), 
    length(x = features))) 
1.
AddChromatinModule(object = atac.integrated2, features = CD4specific, 
    genome = mm10, assay = "MergedPeaks") 


and Debug


> atac.integrated3 <- AddChromatinModule(object = atac.integrated2, features = CD4specific, genome = mm10, assay = "MergedPeaks")
Error in sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j,  : 
  NA's in (i,j) are not allowed
Called from: sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j, 
    use.names = FALSE), x = 1, dims = c(nrow(x = object[[assay]]), 
    length(x = features)))


Any idea why the matrix would include NAs, and how to remove those? Thanks!

**Comment by timoast** [comment]
Sorry, I forgot to mention what the arguments should be. The `features` argument should be a named list, where each element in the list will be a "module" of peaks. For example:

```r
features <- list("module1" = c("chr1:1-100", "chr2:2-200"))
```

The other arguments are a bit more obvious but just to be clear, `object` is a Seurat object, `assay` is the name of the assay to use, `genome` is a BSgenome object

**Comment by laurabchopp** [comment]
Getting closer! Now I get an error message:

 Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘computeDeviations’ for signature ‘"RangedSummarizedExperiment", "numeric"’ 

Google was unfortunately of no help with this error...

**Comment by timoast** [comment]
This suggests that the sparse matrix is being changed into a numeric vector at some point...maybe you could just modify the function like this to return the sparse matrix, then verify that it looks correct before calling RunChromVAR:

```r
ChromatinModuleSparseMat <- function(object, features, genome, assay) {
 # first find index of each feature
 feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = object[[assay]]))
 j <- sapply(X = seq_along(along.with = features), FUN = function(x) {
   rep(x = x, length(x = features[[x]]))
 })
 
 # construct sparse matrix with features
 mat <- sparseMatrix(
   i = unlist(x = feat.idx, use.names = FALSE),
   j = unlist(x = j, use.names = FALSE),
   x = 1,
   dims = c(nrow(x = object[[assay]]), length(x = features))
 )
 rownames(x = mat) <- rownames(x = object[[assay]])
 colnames(x = mat) <- names(x = features)
 return(mat)
}
```

**Comment by laurabchopp** [comment]
I don't have much (any) experience with making sparse matrices, but II think there is something strange with the matrix construction. I ran the matrix construction command as follows:



```
features <- list("module1" = CD4specific)

ChromatinModuleSparseMat <- function(object, features, genome, assay) {
  # first find index of each feature
  feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = object[[assay]]))
  j <- sapply(X = seq_along(along.with = features), FUN = function(x) {
    rep(x = x, length(x = features[[x]]))
  })
  
  # construct sparse matrix with features
  mat <- sparseMatrix(
    i = unlist(x = feat.idx, use.names = FALSE),
    j = unlist(x = j, use.names = FALSE),
    x = 1,
    dims = c(nrow(x = object[[assay]]), length(x = features))
  )
  rownames(x = mat) <- rownames(x = object[[assay]])
  colnames(x = mat) <- names(x = features)
  return(mat)
}


atac.integrated3.mat <- ChromatinModuleSparseMat(object = atac.integrated2, features = features, genome = "mm10", assay = "MergedPeaks")


```

And this is the result:

<img width="899" alt="Screen Shot 2020-08-09 at 8 44 33 PM" src="https://user-images.githubusercontent.com/58085469/89746930-e8d30000-da81-11ea-9e01-458ec9769c28.png">


```
head(atac.integrated3.mat)[1:20]
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

`print(atac.integrated3.mat)
`

<img width="338" alt="Screen Shot 2020-08-09 at 8 56 53 PM" src="https://user-images.githubusercontent.com/58085469/89747133-eb822500-da82-11ea-8fd4-558265f4dffc.png">


To try to trouble shoot, I ran the feat.idx command alone. It's certainly not the peak name since it doesn't follow the format of "chr1:1-1000". I double checked the row names of the assay, and it follows the convention of "chr1:1-1000"

`feat.idx <- sapply(X = features, FUN = fmatch, rownames(x = atac.integrated2[["MergedPeaks"]]))
`
 and this is it's output:

<img width="138" alt="Screen Shot 2020-08-09 at 8 52 13 PM" src="https://user-images.githubusercontent.com/58085469/89747005-5f6ffd80-da82-11ea-8ee5-c0ee833e3049.png">


I'm not sure where to go from here.

**Comment by timoast** [comment]
The sparse matrix looks ok, other than the somewhat random order of features but that should be the same as the order in the assay. `feat.idx` stores the index of each feature in the object, so that's fine. Did you try running `RunChromVAR` with the  sparse matrix? eg, `RunChromVAR(atac.integrated2, genome = "mm10", motif.matrix = atac.integrated3.mat, assay = "MergedPeaks")`?

**Comment by laurabchopp** [comment]
Yes, it gave me the same error as before:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘computeDeviations’ for signature ‘"RangedSummarizedExperiment", "numeric"’

**Comment by timoast** [comment]
Ok, not sure what the issue is. If you can save the object and email me a link and the code you're running I'd be happy to take a look (tstuart@nygenome.org)

**Comment by timoast** [comment]
Ok the issue was that the sparse matrix is subset inside the `RunChromVAR` function, and if it had only one column it was coerced to a numeric vector. I've fixed this in the next version, but in the meantime you can work around by just adding a second module (just choose some peaks at random and ignore the results for that module). Eg:

```r
features <- list("module1" = CD4specific, "module2" = head(rownames(atac.integrated2)))
```

**Comment by laurabchopp** [comment]
Wow, that looks great! It worked, and gave similar results to the AddModuleScore, and now I'm confident in the results. Thank you so much!
