### ISSUE TITLE
How to specify the parameters when using distal peaks for gene activity matrix

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#186]
Hi,

 Is it okay to provide a range for upstream and leave the downstream as 0 if we would like to use distal peaks as a measure of gene activity in the integration of scATAC with scRNA seq datasets?

Thanks!

**Comment by timoast** [comment]
Sure, the `Extend` function just extends the given ranges by the amount you want. You can change the upstream and downstream values to whatever suits your purpose.
