### ISSUE TITLE
Differentially accessible peaks and motifs between treatments

### ISSUE THREAD

**Issue by singcell** [timoast/signac#187]
I am comparing control and treated samples using scATAC-seq data integration vignette.  I wanted to find differentially accessible peaks and motifs between treatments. In SEURAT integration [vignette](https://satijalab.org/seurat/v3.1/immune_alignment.html), I use `FindMarkers` to find differentially expressed genes to find DEGs between two conditions, How can I find differentially accessible peaks and motifs between treatments using Signac for my integrated data?
What function do I use?

Thank you

**Comment by timoast** [comment]
You can use the `FindMarkers` function as show in the vignette: https://satijalab.org/signac/articles/pbmc_vignette.html#find-differentially-accessible-peaks-between-clusters-1
