### ISSUE TITLE
Specifying upstream and downstream limits in Integration Analysis

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#188]
Hi,
Please advice on how to specify the upstream coordinates where one wishes to include a very specific range as it would appear that this script does not utilize the conventional minus sign for Upstream of TSS versus plus sign for downstream of TSS.
So in the script if upstream= 2000 and downstream =0, I'm assuming it is searching for accessibility in the region spanning 2000 to 0.
However, I'm interested in the 100-2kb upstream WITHOUT the 2kb-0 upstream region. How then would i ensure that 2kb-0 region is being excluded if I set upstream to 100000-2000 and downstream =0.
Thank you!!!!

**Comment by timoast** [comment]
You just need to resize the set of genomic ranges to suit your purposes. For example:

```r
library(Signac)
library(GenomicRanges)
library(EnsDb.Hsapiens.v75)

gene.ranges <- genes(EnsDb.Hsapiens.v75)
tss.ranges <- resize(gene.ranges, width = 1, fix = "start")
regions.use <- Extend(tss.ranges, upstream = 100000, downstream = -2000)
```

>  it would appear that this script does not utilize the conventional minus sign for Upstream of TSS versus plus sign for downstream of TSS.

I'm not sure what you mean exactly, can you elaborate?

**Comment by sylestiel** [comment]
Did not realize that we could write -2000.
Why is upstream not -10000?

What is width?
Why is it 1?

**Comment by timoast** [comment]
The docs for `GenomicRanges::resize`:
> resize returns an object of the same type and length as x containing intervals that have been resized to width width based on the strand(x) values. Elements where strand(x) == "+" or strand(x) == "*" are anchored at start(x) and elements where strand(x) == "-" are anchored at the end(x). The use.names argument determines whether or not to keep the names on the ranges.

> Why is upstream not -10000?

The `upstream` argument controls the number of bases to move the start coordinate upstream. Setting to -10000 would move it 10000 bp downstream of the start coordinate

**Comment by sylestiel** [comment]
So just writing 
peaks <- Read10X_h5("FILEPATH/outs/filtered_peak_bc_matrix.h5")
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = peaks, annotation.file = "FILEPATH/Mus_musculus.GRCm38.99.chr.gtf", 
    seq.levels = c(1:19, "X", "Y"), include.body = FALSE, upstream = 100000, downstream =-2000, verbose = TRUE)
will not suffice?

**Comment by timoast** [comment]
No, in this case you're using the gtf file rather than the TSS, so "downstream" is counted from the end of the gene. `CreateGeneActivityMatrix` is a different function and is part of the Seurat package. It sums the rows of a count matrix rather than quantify regions using the scATAC-seq fragment file.

**Comment by sylestiel** [comment]
Sorry to press the issue but I need to know that I'm doing it correctly. 
So for proximal peaks the script says to put include.body=TRUE, upstream =2000, downstream=0

If I want to provide distal peaks to generate the CreateGeneActivityMatrix my question to you is how to do it?
Is it:
seq.levels = c(1:19, "X", "Y"), include.body = FALSE, upstream = 100000-2000, downstream =0, verbose = TRUE)


Where would I introduce 
gene.ranges <- genes(EnsDb.Mmusculus.v79)
tss.ranges <- resize(gene.ranges, width = 1, fix = "start")
regions.use <- Extend(tss.ranges, upstream = 100000, downstream = -2000)

Thanks!

**Comment by timoast** [comment]
Which script are you referring to? See https://satijalab.org/signac/articles/pbmc_vignette.html#create-a-gene-activity-matrix-1

In short, you cannot do what you're asking using `Seurat::CreateGeneActivityMatrix()`. You will need to use `Signac::FeatureMatrix()` and the steps I outlined above

**Comment by sylestiel** [comment]
I was using the scATAC-seq + scRNA-seq integration vignette on Seurat. I think we are referred to that for an indepth integration in Signac. Right?

**Comment by timoast** [comment]
> I think we are referred to that for an indepth integration in Signac. Right?

Again, not sure what "that" refers to, but I think this question is answered now.

**Comment by sylestiel** [comment]
That as in integration with scRNA seq. Yes thank you immensely.
