### ISSUE TITLE
latent.vars in finding DA peaks

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#19]
Dear Tim,

Thanks for developing very useful tool for scATAC analysis.
In the vignette of "Human PBMCs" and "Adult mouse brain",  latent vars  = 'peak_region_fragments' was used in finding the differential peaks with FindMarkers function.

da_peaks <- FindMarkers( .......
  test.use = 'LR',
  latent.vars = 'peak_region_fragments' )

"Motif analysis with Signac" vignette,  latent vars  = 'nCount_peaks' was adopted in da_peaks selections.

da_peaks <- FindMarkers(.......
  test.use = 'LR',
  latent.vars = 'nCount_peaks')

I am wondering there are some reasons to select "nCount_peaks" in this situation?

Best,
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, these are essentially the same thing and I will probably change the PBMC vignette in the future to avoid confusion.

The `peak_region_fragments` comes from the 10x Genomics cell metadata produced by running CellRanger, and `nCount_peaks` is computed by Seurat (the total number of fragment counts for the cell).

They are highly correlated:

```r
> cor(pbmc$peak_region_fragments, pbmc$nCount_peaks)
[1] 0.9999125
```

You can use either as a latent variable when finding DA peaks

**Comment by ymuto802** [comment]
Thank you very much !
Yoshi
