### ISSUE TITLE
How to process cellranger-atac count output for scATAC-seq data integration vignette?

### ISSUE THREAD

**Issue by singcell** [timoast/signac#190]
I am comparing control and treated samples using Signac data integration [vignette](https://satijalab.org/signac/articles/integration.html). However in the tutorial  you use "Cell metadata"
and "Count matrix" which is already processed data.
I have raw scATAC-seq output from `cellranger-atac count` and wanted to perform integration. I was wondering how to process `cellranger-atac count` raw data to get "Cell metadata" and "Count matrix" so that I can use it with Signac.

Thank you

**Comment by timoast** [comment]
> I was wondering how to process cellranger-atac count raw data to get "Cell metadata" and "Count matrix" so that I can use it with Signac.

The cell metadata and count matrix files are outputs of cellranger-atac, and are used as input for most of the Signac vignettes.
