### ISSUE TITLE
how to calculate gene activity matrix of merged peak across multi-samples?

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#193]
Base on the  vignettes of "merging object", I merged the integrated the scATAC data across 4 samples. Then I have a question how to calculated the gene activity matrix of the integrated data? using the merged peak?
Whether I can calculated the gene activity of each sample in turn and combined them directly?

**Comment by timoast** [comment]
You can create a gene activity matrix before or after merging using the GeneActivity function
