### ISSUE TITLE
Error message when running SetAssayData() function

### ISSUE THREAD

**Issue by chent5** [timoast/signac#194]
Thanks a lot for developing this package. I am trying the development version following your online tutorial. I got an error message "Error: 'slot' must be one of counts, data, scale.data" when running SetAssayData().

=== Here is the code I use, start ===
motif.positions <- matchMotifs(
  pwms = pwm,
  subject = StringToGRanges(rownames(signac.object), sep = c(":", "-")),
  out = 'positions',
  genome = 'hg38'
)

motif <- CreateMotifObject(
  positions = motif.positions,
  pwm = pwm
)

signac.object <- SetAssayData(
  object = signac.object,
  slot = 'motifs',
  new.data = motif
)
=== Here is my code, end ===
There is no error using matchMotifs() or CreateMotifObject() function. But I cannot pass the SetAssayData() function. Could you help to solve this problem? Thank you so much!

**Comment by timoast** [comment]
Are you sure that you have version 1.0.0 loaded? `packageVersion("Signac")`

Are you sure that you're adding the motif object to a ChromatinAssay, not a regular Seurat Assay?

**Comment by chent5** [comment]
Thanks a lot for your prompt response.

The signac object was generate by Signac old version. So that is the problem. I have converted the peaks assay to a Chromatin Assay. After that, there is no error when running SetAssayData().

However, when I ran Footprint() using the following code:
signac.object <- Footprint(
  object = signac.object,
  motif.name = c("GATA2", "CEBPA", "EBF1"),
  genome = BSgenome.Hsapiens.UCSC.hg38
)
I got a new error message: 
Computing Tn5 insertion bias
Error in validObject(.Object) : invalid class "GRanges" object: 
    'x@strand' is not parallel to 'x'

Could you please help to solve this problem? Thank you so much!

**Comment by timoast** [comment]
I'd suggest restarting R and try again

**Comment by chent5** [comment]
I restarted R and tried again, and then I got the same error...

**Comment by timoast** [comment]
Something weird has happened to the granges object...try re-creating the ChromatinAssay from the counts. For example:

```r
counts <- GetAssayData(object, assay = <assay>, slot = "counts")
object[["ATAC"]] <- CreateChromatinAssay(counts = counts)
```

**Comment by chent5** [comment]
I recreated the ChromatinAssay from the counts using the code below:
counts <- GetAssayData(signac.object, assay = "peaks", slot = "counts")
signac.object[["peaks"]] <- CreateChromatinAssay(counts = counts, sep = c(":", "-"))

But I still got the same error.

Here is how the granges look like:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/40006284/90336189-15b67400-dfa8-11ea-8d72-0b409b98de88.png">

Is there anything wrong with the granges object?

**Comment by timoast** [comment]
Can you send the full code you're running and a link to download the Seurat object to tstuart@nygenome.org, and I can take a further look?

**Comment by chent5** [comment]
I have sent you the full code and the Seurat object by email. Thanks so much for your help!

**Comment by timoast** [comment]
I couldn't reproduce the GRanges error you were seeing, but the error during the Footprint function was due to having no fragment files set for the object. If you set the fragment file when creating the assay, this should go away. I've updated the code to give a more informative error when this happens

**Comment by chent5** [comment]
I generated a new signac object using version 1.0.0 instead of the old signac object generated by the old version. There is no error any more when using the new signac object. Thanks so much for your help!
