### ISSUE TITLE
Merging and Integrating objects

### ISSUE THREAD

**Issue by singcell** [timoast/signac#197]
I wanted to compare  Wild type (WT) and Knockout (KO) samples each with 3 replicates. I am using scATAC-seq data integration vignette.  I was wondering which of the following approaches would be the best:

Merge replicates WT1, WT2 and WT3 into one object (WT) and merge KO1, KO2 and KO3 into another object (KO) using `Merge` function. Then use scATAC-seq data integration vignette to integrate WT and KO objects.

Or

 I use CellRanger-atac aggr function to merge replicates and then integrate WT and KO in Signac.

Which approach would be best?

--------
Another question, If I use to `FindMarkers` to find differentially accessible peaks and motifs **between WT and KO samples**  (NOT between clusters in same condition) on  my integrated data, What should be the value of ident.1 and ident.2?

For example, Which motif is more accessible or active in KO vs WT in a particular cluster?

Thank you

**Comment by timoast** [comment]
I would first quantify the same set of peaks for _all_ samples, following the workflow shown in the [merge vignette](https://satijalab.org/signac/articles/merging.html). Then merge everything together and see if there are batch differences that need to be adjusted. If so, use the Seurat integration methods or Harmony as shown in the [integration vignette](https://satijalab.org/signac/articles/integration.html).

Regarding cellranger-aggr, see #51 

To find differential peaks or motifs between WT and KO, follow a similar workflow shown in the Seurat [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html) (ie, combine the cluster and treatment information to do DE within a cluster across treatment groups)

**Comment by singcell** [comment]
@timoast Thank you for your reply. I have some followup questions.

> I would first quantify the same set of peaks for _all_ samples, following the workflow shown in the [merge vignette](https://satijalab.org/signac/articles/merging.html). Then merge everything together and see if there are batch differences that need to be adjusted. 

I have merged the samples according to Signac merge vignette. Now, how should I figure out if there are batch differences? Which Signac function I need to use and what output I need to look for?



> 
> To find differential peaks or motifs between WT and KO, follow a similar workflow shown in the Seurat [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html) (ie, combine the cluster and treatment information to do DE within a cluster across treatment groups)

How should I combine the cluster and treatment information? Which Seurat vignette/function I need to use?  I have now Seurat object containing merged WT and KO samples.
If I use Seurat [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html), what kind of input I need?
In immune alignment vignette I used `FindIntegrationAnchors` and `integratedata` to combine Seurat objects of two conditions for scRNA-Seq data. Can I use it for scATAC as well?
