### ISSUE TITLE
CreateChromatinAssay

### ISSUE THREAD

**Issue by afcmalone** [timoast/signac#198]
Hi,
I am creating a seurat object using signac 1.0.0
My data aligned to GRCH38/hg38,
I created a chrom_assay and seurat assay following https://satijalab.org/signac/articles/pbmc_vignette.html:

library(Signac)
library(Seurat)
library(SeuratWrappers)
library(ggplot2)
library(patchwork)
library(cicero)
library(BSgenome.Hsapiens.UCSC.hg38)

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'hg38',
  fragments = '/Users/.../fragments.tsv.gz',
  min.cells = 0,
  min.features = 200
)
# bug in CreateChromatinAssay so need to set min.cells=0
pbmc <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)
pbmc

my chrom_assay@seqinfo slot is then empty:
@seeqlengths - all 'NA'
@is_circular - all 'NA'
@genome - all 'NA'

The rest of this pipeline/vigette works fine for my data.

I realized this was an issue when moving onto Find Cicero connections 
https://satijalab.org/signac/articles/cicero.html

running:
genome <- seqlengths(pbmc)
Error in slot(object = x[[assay]], name = "seqinfo") : 
  no slot of name "seqinfo" for this object of class "Assay"

I wonder what is wrong with the CreateChromatinAssay as the @seqinfo slot is wrong or empty.

Thanks
Andrew

**Comment by timoast** [comment]
```
genome <- seqlengths(pbmc)
Error in slot(object = x[[assay]], name = "seqinfo") :
no slot of name "seqinfo" for this object of class "Assay"
```

This indicates that the default assay is not a ChromatinAssay, but a regular Seurat Assay. You probably need to change the default assay.

```
my chrom_assay@seqinfo slot is then empty:
@seeqlengths - all 'NA'
@is_circular - all 'NA'
@genome - all 'NA'
```

If you supply a genome name when creating the ChromatinAssay, that requires an internet connection. Is your R session able to connect to the internet? Alternatively you can provide an existing seqinfo object to supply the genome information (you can get this from a BSgenome, for example).

**Comment by afcmalone** [comment]
thank you for the reply, seems easy to fix.
