### ISSUE TITLE
Overlapping enriched motifs on positively/negativelydifferential peaks

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#20]
Hi Tim,

Thanks for developing very useful tool for scATAC analysis.
In the vignette of "Motif analysis", enriched motifs are evaluated on the differential peaks of Pvalb compared with Sst. 

>da_peaks <- FindMarkers(
  object = mouse_brain,
  ident.1 = 'Pvalb',
  ident.2 = 'Sst',
  only.pos = TRUE,
  test.use = 'LR',
  latent.vars = 'nCount_peaks')

>enriched.motifs <- FindMotifs(
  object = mouse_brain,
  features = rownames(da_peaks[da_peaks$p_val   < 0.01, ]))

When I tried similarly motif analysis on these of Sst (that is, closed motifs in Pvalb compared to Sst) I saw many overlapping motifs on the both differentially active motif lists for Pvalb and Sst (MEF2s, SP1/2, PLAG2 etc...).

>da_peaks <- FindMarkers(
  object = mouse_brain,
  ident.1 = 'Sst',
  ident.2 = 'Pvalb',
  only.pos = TRUE,
  test.use = 'LR',
  latent.vars = 'nCount_peaks')

>enriched.motifs <- FindMotifs(
  object = mouse_brain,
  features = rownames(da_peaks[da_peaks$p_val   < 0.01, ]))

These results makes identifying differentially-active motifs between cell types difficult - Do you have any suggestions for dealing with this problem? Using chromvar motif analysis might be simplest solution.

Thanks,
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, I find some overlap between the two sets of enriched motifs using the mouse brain data, although I don't see any MEF family motifs or PLAG2 enriched in the Sst-specific peaks. Are you using the same dataset I used in the vignette?

Although it seems maybe counterintuitive, it's possible for a motif to be enriched in both comparisons, unlike in differential expression testing. If you want to identify motifs that are only present in one direction, I would suggest running both comparisons (A vs B, B vs A) and filtering out motifs that were enriched in both.

**Comment by ymuto802** [comment]
The filtration of low-quality cells of my data seemed different from the vignette - Sorry for confusion. Actually I also found many overlaps of TF motifs in the other datasets though. Probably these TFs might be simply on the every promoter or enhancer hence they are enriched on every differential peak set. Anyway, thank you for your suggestion about identifying specific motifs - It helps me a lot !

**Comment by timoast** [comment]
Another thing you might try is selecting a background set of peaks from the set of peaks that are open in Pvalb and Sst interneurons (ie, the group of cells you want to contrast).

For example:

```r
library(Signac)
library(Seurat)
library(Matrix)

# get a set of peaks to test
pvalb.peaks <- FindMarkers(
  object = mouse_brain,
  ident.1 = 'Pvalb',
  ident.2 = 'Sst',
  only.pos = TRUE,
  test.use = 'LR',
  latent.vars = 'nCount_peaks'
)

peaks.test <- rownames(pvalb.peaks[pvalb.peaks$p_val < 0.01, ])

# get peaks that are open in PV and SST
pvsst.cells <- WhichCells(object = mouse_brain, idents = c('Pvalb', 'Sst'))
pvsst.counts <- GetAssayData(object = mouse_brain, assay = 'peaks', slot = 'counts')[, pvsst.cells]
pvsst.peaks <- rownames(mouse_brain)[(rowSums(pvsst.counts) > 30)] # 30 is arbitrary, but increasing the threshold will increase the number of cells the peak is open in

# remove the set of peaks that we're testing from the background set
possible.background <- setdiff(pvsst.peaks, peaks.test)
  
# select a set of peaks matched for GC percent
peak.metadata <- GetAssayData(mouse_brain, assay = 'peaks', slot = 'meta.features')
background.use <- MatchRegionStats(meta.feature = peak.metadata, regions = peaks.test, features.match = 'GC.percent', n = 10000)

# find enriched motifs
motifs <- FindMotifs(mouse_brain, features = peaks.test, background = background.use)
```

This should reduce the number of motifs that are enriched in both Pvalb- and Sst-specific peaks from appearing significant, as they would be present more frequently in the background set. It won't prevent them from occurring entirely, as some of these are likely real results.

**Comment by ymuto802** [comment]
Thanks Tim, I agree. Actually I am analyzing two sets of data with and without stimulation. When comparing two conditions in the same cell-type, I found many overlap TF motifs on each side of differential peak set. I guess the best solution is what you suggested in the previous response.
