### ISSUE TITLE
Unable to update to the 1.0 version

### ISSUE THREAD

**Issue by mailcolm9** [timoast/signac#201]
Hi Tim 
I wanted to update Signac from 0.25 to 1.0 so that I can use the fold change function. However, when I tried to updated it, it never works but says

`ERROR: dependencies ‘ggbio’, ‘biovizBase’, ‘qvalue’ are not available for package ‘Signac’
* removing ‘/Users/zonghao/Library/R/4.0/library/Signac’
Warning in install.packages :
  installation of package ‘Signac’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/pt/6gbysd8n47x0r4j44zfw9py40000gv/T/Rtmp1EExBk/downloaded_packages’`

I updated R and R studio to most updated version. Can you help me to figure out what is going on?
Thanks!

**Comment by timoast** [comment]
Did you follow the instructions on the install page? https://satijalab.org/signac/articles/install.html

ie:

```r
# Install bioconductor
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()

# To automatically install Bioconductor dependencies
setRepositories(ind=1:2)

install.packages("Signac")
```

**Comment by mailcolm9** [comment]
I didn't run the Repositories, and it is fixed now.
