### ISSUE TITLE
FindMarkers returns genes instead of coordinates

### ISSUE THREAD

**Issue by mailcolm9** [timoast/signac#202]
Hi Tim,

I was trying to find the differential peaks using FIndMarkers, but this function returned gene name instead of coordinates. As a result, I can't run the CoveragePlot. Could you take a look and help me solve it?
Thanks!

Here is my code and the result of da peak
`da_peaks <- FindMarkers(
  object = Object,
  ident.1 = "EBVHigh",
  ident.2 = "EBVLow1",
  group.by = "predicted.id",
  min.pct = 0.05,
  test.use = 'LR',
  latent.vars = 'peak_region_fragments'`

`CD48
0.000000e+00
-0.7541163
1.000
1.000
0.000000e+00`
`TGA4
9.946484e-273
-0.3915470
0.998
1.000
1.989297e-269`
`MT-CO2
1.862805e-261
-0.9372049
1.000
1.000
3.725609e-258`

**Comment by timoast** [comment]
You probably are using the wrong assay. You can change the assay using the `DefaultAssay()` function

**Comment by mailcolm9** [comment]
after set the default assay to peaks, the issue was solved. Thanks!
