### ISSUE TITLE
Is there a way to change the directory to the fragment file?

### ISSUE THREAD

**Issue by chent5** [timoast/signac#206]
I have generate a signac object using the newest Signac version. After that, one folder associated with the directory to the fragment file has to be renamed. Is there a way to only change the directory to the fragment file for the signac object? Thank you so much!

**Comment by timoast** [comment]
Added `UpdatePath()` function and the ability to remove fragment objects by assigning NULL (eg, `Fragments(object) <- NULL`). This is available on the develop branch and will be added to the documentation on the website in the next release
