### ISSUE TITLE
Motif analysis Vignette error: wrong mouse tax id

### ISSUE THREAD

**Issue by Puriney** [timoast/signac#209]
https://github.com/timoast/signac/blob/c53f27048b309fa67fe9879702ab330525130d60/vignettes/motif_vignette.Rmd#L53-L65

Here the tutorial used the human. But Mm10's tax id is ['10090'](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=info&id=10090).

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/58#issuecomment-571183108
