### ISSUE TITLE
error with FindIntegrationAnchors

### ISSUE THREAD

**Issue by ctrhodes** [timoast/signac#211]
I merged two replicates of a sample using 10X genomics cellranger-atac aggr pipeline (to generate common peak coordinates and read downsampling). The resulting filtered peak by cell matrix was then subset by replicates into separate Seurat objects following the vignettes. Then trying for find integration anchors with Signac integration methods results in an error.

Any of the following 3 calls to FindIntegrationAnchors results in an error:

Option 1:
anchors <- FindIntegrationAnchors(
  object.list = list(seurat_ref, seurat_query),
  assay = c('peaks', 'peaks')
)
Error 1:
"Computing 2000 integration features
Scaling features for provided objects
  |                                                  | 0 % ~calculating

Error in SetAssayData.ChromatinAssay(object = object, slot = "scale.data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object"

Option 2:
anchors <- FindIntegrationAnchors(
  object.list = list(seurat_ref, seurat_query),
  anchor.features = intersect(VariableFeatures(seurat_ref), VariableFeatures(seurat_query)),
  assay = c('peaks', 'peaks')
)
Error 2:
"Scaling features for provided objects
  |                                                  | 0 % ~calculating  Error in SetAssayData.ChromatinAssay(object = object, slot = "scale.data",  : 
  Number of rows in provided matrix does not match
           the number of rows in the object"

Option 3:
anchors <- FindIntegrationAnchors(
  object.list = list(seurat_ref, seurat_query),
  anchor.features = rownames(seurat_ref),
  assay = c('peaks', 'peaks'),
  k.filter = NA
)
Error 3:
"Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07m 27s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Error in SetAssayData.ChromatinAssay(object = object[[assay]], slot = slot,  : 
  Number of rows in provided matrix does not match
           the number of rows in the object"

To prep the data I did the following (QC/preprocessing not shown):

seurat_ref = readRDS(file = file.path(indir, replicate1.reference.rds))
DefaultAssay(seurat_ref) <- "peaks"

seurat_query = readRDS(file = file.path(indir, replicate2.query.rds))
DefaultAssay(seurat_query) <- "peaks"

seurat_ref <- Signac::RunTFIDF(
  object = seurat_ref, 
  assay = 'peaks')
seurat_ref <- FindTopFeatures(
  object = seurat_ref, 
  assay = 'peaks', 
  min.cutoff = 50)

seurat_query <- Signac::RunTFIDF(
  object = seurat_query, 
  assay = 'peaks')
seurat_query <- FindTopFeatures(
  object = seurat_query, 
  assay = 'peaks', 
  min.cutoff = 50)

> length(rownames(seurat_ref))
[1] 131466
> length(rownames(seurat_query))
[1] 131466
> length(intersect(rownames(seurat_ref), rownames(seurat_query)))
[1] 131466

Any advice? Let me know if you need more info.

Thanks in advance,
Chris

**Comment by MagpiePKU** [comment]
Similar problem here. 

I found the problem exists earlier in the point when I constructed the 'common feature' slot like:

ATAC_peaks_common <- FeatureMatrix(
  fragments = Fragments(ATAC),
  features = combined.peaks,
  cells = colnames(ATAC)
)

ATAC[['commonpeaks']] <- CreateChromatinAssay(
  counts = ATAC_peaks_common,
  min.cells = 1,
  ranges = combined.peaks,
  genome = hg19_seqinfo # I have the object downloaded and saved 
)
ATAC[['commonpeaks']]  <- FindVariableFeatures(ATAC[['commonpeaks']])
ATAC[['commonpeaks']]  <- ScaleData(ATAC[['commonpeaks']] )

Error:
Centering and scaling data matrix
  |======================================================================| 100%
Error in SetAssayData.ChromatinAssay(object = object, slot = "scale.data",  :
  Number of rows in provided matrix does not match
           the number of rows in the object

The thing is like if I scale data on 'peaks' (the original input) there is no problem so I guess it is a bug in 'FeatureMatrix' construction? 

> ATAC
An object of class Seurat
43074 features across 1283 samples within 2 assays
Active assay: peaks (23629 features, 0 variable features)
 1 other assay present: commonpeaks

> ATAC[['peaks']]
ChromatinAssay data with 23629 features for 1283 cells
Variable features: 0
Genome: hg19
Annotation present: TRUE
Motifs present: FALSE
Fragment files: 1
> ATAC[['commonpeaks']]
ChromatinAssay data with 19445 features for 1283 cells
Variable features: 2000
Genome: hg19
Annotation present: FALSE
Motifs present: FALSE
Fragment files: 0


### 



> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /gpfs/bin/R-3.6.2/lib/libRblas.so
LAPACK: /gpfs/bin/R-3.6.2/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] harmony_1.0                 Rcpp_1.0.4.6
 [3] devtools_2.3.0              usethis_1.6.1
 [5] EnsDb.Hsapiens.v86_2.99.0   ensembldb_2.10.2
 [7] AnnotationFilter_1.10.0     GenomicFeatures_1.38.2
 [9] AnnotationDbi_1.48.0        Matrix_1.2-18
[11] hdf5r_1.3.2                 Signac_1.0.0
[13] SingleR_1.0.6               reshape2_1.4.4
[15] DoubletFinder_2.0.3         furrr_0.1.0
[17] jsonlite_1.6.1              future_1.17.0
[19] patchwork_1.0.0             monocle3_0.2.0
[21] SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.1
[23] DelayedArray_0.12.3         BiocParallel_1.20.1
[25] matrixStats_0.56.0          GenomicRanges_1.38.0
[27] GenomeInfoDb_1.22.1         IRanges_2.20.2
[29] S4Vectors_0.24.4            Biobase_2.46.0
[31] BiocGenerics_0.32.0         ggsci_2.9
[33] RColorBrewer_1.1-2          ggalluvial_0.12.2
[35] Seurat_3.2.1                mixtools_1.2.0
[37] customLayout_0.3.1          GSVA_1.34.0
[39] forcats_0.5.0               stringr_1.4.0
[41] dplyr_1.0.0                 purrr_0.3.4
[43] readr_1.3.1                 tidyr_1.1.0
[45] tibble_3.0.1                tidyverse_1.3.0
[47] survminer_0.4.8             ggpubr_0.4.0
[49] ggplot2_3.3.1               survival_3.1-12

**Comment by MagpiePKU** [comment]
However, the feature matrix looks fine, like: 

> head(ATAC_peaks_common[,1:10])
6 x 10 sparse Matrix of class "dgCMatrix"
   [[ suppressing 10 column names 'AAACGAACAAGAAACT-1', 'AAACGAACACGACGAA-1', 'AAACGAACACGATATC-1' ... ]]

chr1-629768-630135 . . . . . . . . . .
chr1-633799-634258 . . . . . . . 1 . 1
chr1-778468-779011 . . . . 1 . . . . .
chr1-827351-827748 . . . . . . . . . .
chr1-869724-870082 . . . . . . . . . .
chr1-939394-939416 . . . . . . . . . .

**Comment by ninal88** [comment]
I get the same error tying to run FindAnchorFetures. Can you let me know how you fixed it?

**Comment by MagpiePKU** [comment]
> I get the same error tying to run FindAnchorFetures. Can you let me know how you fixed it?

I have used Harmony to get around of this problem but do not know whether it would be correct. Based on the concordance of cell annotation on individual datasets it seems to be ok. 

## Codes:
library(harmony)

unintegrated <- merge(ATAC_data_set_1, ATAC_data_set_2) # both annotated with a 'celltype_original'
DefaultAssay(unintegrated) <- "commonpeaks" 
unintegrated <- RunTFIDF(unintegrated)
unintegrated <- FindTopFeatures(unintegrated, min.cutoff = 50)
unintegrated <- RunSVD(unintegrated)
unintegrated <- RunUMAP(unintegrated, reduction = 'lsi', dims = 2:30)

hm.integrated <- RunHarmony(object=unintegrated,group.by.vars='orig.ident',reduction='lsi',assay.use='commonpeaks',project.dim=F)
hm.integrated <- RunUMAP(hm.integrated,dims=2:30,reduction='harmony')
hm.integrated <- FindNeighbors(hm.integrated, dims = 1:30,reduction='harmony')
hm.integrated <- FindClusters(hm.integrated, resolution = 2,reduction='harmony')
hm.integrated <- BuildClusterTree(object = hm.integrated,reorder = T,reorder.numeric = T,verbose = T)

p2 <- DimPlot(hm.integrated,group.by='orig.ident',pt.size=0.1) + ggplot2::ggtitle('HM.integrated')
p3 <- DimPlot(hm.integrated,group.by='celltype_original',pt.size=0.1) + ggplot2::ggtitle('HM.integrated')

**Comment by Dragonmasterx87** [comment]
@timoast can you please comment on this? I am getting a similar error to that described above.

**Comment by timoast** [comment]
@Dragonmasterx87 Should be fixed on the develop branch
