### ISSUE TITLE
Question about merging objects

### ISSUE THREAD

**Issue by edt711** [timoast/signac#212]
Hello Tim/Signac team,

I had a few questions about your "merging objects" vignette. First, it looks like the way that vignette initially constructs Seurat objects is completely different than in the basic PBMC workflow. This method constructs a FeatureMatrix based on a unified peak set and the individual samples' fragments files and uses it as the `counts` argument, as opposed to the `Read10X_h5` output. This vignette also generates an assay called 'ATAC' rather than 'peaks.' Do these differences have any impact on any downstream analysis? Also, I noticed that the objects generated in this vignette lack a lot of the metadata that these Seurat objects typically have (such as pct_region_fragments). Is it fine to define `meta.data = metadata` when creating the Seurat object (i.e. as you do in the PBMC vignette) in order to add this info for downstream analysis?

Second, when I tried out this vignette with my own data, each of my objects contained a far greater number of cells than they originally had. For instance, one object that had 5305 cells when testing the PBMC workflow (10x's web summary for this sample also had that number) had 8832 cells when setting it up via the merging method. A similar increase was seen in the other two samples that I wanted to merge together. Do you have any idea why these two different methods of Seurat object construction would lead to different numbers of cells for the same dataset?

Finally, in the previous version of Signac, when merging objects we needed to create one large, combined fragments file for all  objects. Since, in this new workflow, each object stores its own fragments file within it, is it fair to assume that this is no longer necessary?

Thanks for all of your hard work in developing these pipelines. We had great success with previous versions of Signac and are looking forward to utilizing the new version!

Best,
Eric

**Comment by timoast** [comment]
> I had a few questions about your "merging objects" vignette. First, it looks like the way that vignette initially constructs Seurat objects is completely different than in the basic PBMC workflow. This method constructs a FeatureMatrix based on a unified peak set and the individual samples' fragments files and uses it as the counts argument, as opposed to the Read10X_h5 output.

All that is needed to create the assay is a count matrix. There are many different ways you could generate this count matrix. Often people use the output of cellranger, and many of the Signac vignettes start with cellranger output being read into R using the `Read10X_h5` function.

In the case where you want to merge different datasets together, it's essential that the same set of peaks are quantified in each dataset. If the datasets were processed independently using cellranger, then the peak sets will be different and will lead to massive batch effects between the datasets (you can see this in the second section of the [merge vignette](https://satijalab.org/signac/articles/merging.html#merging-without-a-common-feature-set-1), where we merge datasets without quantifying the same features).

The workflow in the merge vignette shows how to create a unified peak set across several different experiments, quantify those peaks in each dataset, then create Seurat objects and merge them together. This is the recommended workflow when combining multiple experiments.

> This vignette also generates an assay called 'ATAC' rather than 'peaks.' Do these differences have any impact on any downstream analysis?

No, the name of the assay has no impact on the analysis and is just meant as a unique identifier

> Also, I noticed that the objects generated in this vignette lack a lot of the metadata that these Seurat objects typically have (such as pct_region_fragments). Is it fine to define meta.data = metadata when creating the Seurat object (i.e. as you do in the PBMC vignette) in order to add this info for downstream analysis?

Yes, you can add whatever metadata you need using the standard `meta.data` parameter in `CreateSeuratObject()`, or later using the `AddMetaData()` function.

> Second, when I tried out this vignette with my own data, each of my objects contained a far greater number of cells than they originally had. For instance, one object that had 5305 cells when testing the PBMC workflow (10x's web summary for this sample also had that number) had 8832 cells when setting it up via the merging method. A similar increase was seen in the other two samples that I wanted to merge together. Do you have any idea why these two different methods of Seurat object construction would lead to different numbers of cells for the same dataset?

The cellranger output is a filtered peak x cell matrix based on their own methods for defining what cells should be included in the downstream analysis. In the merge vignette, we used a simpler cutoff based on the total number of fragments per cell. You will need to find your own optimal values to decide which cells to include in the downstream analysis, or you could use the list of cells to include produced by cellranger.

> Finally, in the previous version of Signac, when merging objects we needed to create one large, combined fragments file for all objects. Since, in this new workflow, each object stores its own fragments file within it, is it fair to assume that this is no longer necessary?

This is no longer necessary in the new version of Signac. We maintain a list of fragment objects behind-the-scenes, with a conversion for cell names in the Seurat object to cell names in the fragment file. You can read the [release notes](https://satijalab.org/signac/news/index.html#signac-1-0-0-2020-08-16) for more information
