### ISSUE TITLE
Merge data

### ISSUE THREAD

**Issue by troygustat** [timoast/signac#214]
Hi,

I have merged two scATAC data and tried to create the gene activity matrix by GeneActivity function. However, the errors showed as below

Error in GeneActivity(iWAT_combined) : 
  No gene annotations present in object

Anything can I do to solve this?

Thanks!

Troy

**Comment by timoast** [comment]
You need to add gene annotations to the object. You can add annotations when the assay is created using the `annotation` parameter in `CreateChromatinAssay` or using the [`Annotation()`](https://satijalab.org/signac/reference/Annotation.html) assignment function

**Comment by troygustat** [comment]
Thanks so much!
