### ISSUE TITLE
Comparing accessibility across conditions.

### ISSUE THREAD

**Issue by singcell** [timoast/signac#215]
@timoast Thank you for your reply. I have some followup questions. (with reference to #197)

> I would first quantify the same set of peaks for _all_ samples, following the workflow shown in the [merge vignette](https://satijalab.org/signac/articles/merging.html). Then merge everything together and see if there are batch differences that need to be adjusted. 

I have merged the samples according to Signac merge vignette. Now, how should I figure out if there are batch differences? Which Signac function I need to use and what output I need to look for?

> 
> To find differential peaks or motifs between WT and KO, follow a similar workflow shown in the Seurat [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html) (ie, combine the cluster and treatment information to do DE within a cluster across treatment groups)

How should I combine the cluster and treatment information? Which Seurat vignette/function I need to use?  I have now Seurat object containing merged WT and KO samples.
If I use Seurat [immune alignment vignette](https://satijalab.org/seurat/v3.2/immune_alignment.html), what kind of input I need?
In immune alignment vignette I used `FindIntegrationAnchors` and `integratedata` to combine Seurat objects of two conditions for scRNA-Seq data. Can I use it for scATAC as well?

_Originally posted by @singcell in https://github.com/timoast/signac/issues/197#issuecomment-682330012_

**Comment by timoast** [comment]
> I have merged the samples according to Signac merge vignette. Now, how should I figure out if there are batch differences? Which Signac function I need to use and what output I need to look for?

You can create a UMAP and color cells by batch and check if you think there are batch-specific differences between the groups of cells. You could also cluster the data an check the proportion of cells in each batch present in each cluster

> How should I combine the cluster and treatment information? Which Seurat vignette/function I need to use? I have now Seurat object containing merged WT and KO samples.

You can create a new metadata column containing cluster and treatment information using the `paste0` function in R. For example: `object$cluster_treatment <- paste0(object$seurat_cluster, "_", object$treatment)`

> If I use Seurat immune alignment vignette, what kind of input I need?

A Seurat object

> In immune alignment vignette I used FindIntegrationAnchors and integratedata to combine Seurat objects of two conditions for scRNA-Seq data. Can I use it for scATAC as well?

You don't have to use the integration methods if there are no batch differences. If there are batch differences you can certainly run the integration methods (see the [integration vignette](https://satijalab.org/signac/articles/integration.html)). The part to focus on in the immune alignment vignette is how to do a differential expression (or in this case, accessibility) test within a cluster between conditions

**Comment by ccruizm** [comment]
Good day!

I have a related question. When comparing two conditions (e.g., non-treated and treated cells) and after merging (or integration), should I use the RNA assay (using the inferred gene activities based on ATAC) or the ATAC (peaks) assay itself?

I have tried this:

```
DefaultAssay(combined) <- 'peaks'

da_peaks <- FindMarkers(
  object = combined,
  ident.1 = "treated",
    group.by = 'treatment',
    subset.ident = 'HSC',
  min.pct = 0.2,
  test.use = 'LR',
  latent.vars = 'peak_region_fragments'
)
```
and also following the 'Integrating stimulated vs. control PBMC datasets to learn cell-type-specific responses' vignette from RNA using the RNA assay from my ATAC data:
```
hsc <- subset(combined, idents = "HSC")
Idents(hsc) <- "treatment"
avg.hsc <- log1p(AverageExpression(hsc, verbose = FALSE)$RNA)
avg.hsc$gene <- rownames(avg.hsc)
```
but I am not sure which approach is the best for this case.

Thanks in advance for your help!

**Comment by singcell** [comment]
@ccruizm I would recommend you to create a separate issue, that would help get attention of the owner of this program.

**Comment by ccruizm** [comment]
Thanks! will do
