### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by Connorr0** [timoast/signac#216]
I am trying to install Signac on a new Mac and am unclear on what is going wrong.

```
> setRepositories(ind=1:2)
> install.packages("Signac")
Package which is only available in source form, and may need compilation of C/C++/Fortran: ‘Signac’
Do you want to attempt to install these from sources? (Yes/no/cancel) y
installing the source package ‘Signac’

trying URL 'https://cran.rstudio.com/src/contrib/Signac_1.0.0.tar.gz'
Content type 'application/x-gzip' length 702895 bytes (686 KB)
==================================================
downloaded 686 KB

* installing *source* package ‘Signac’ ...
** package ‘Signac’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c filter.cpp -o filter.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c group.cpp -o group.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c validate.cpp -o validate.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Signac.so RcppExports.o filter.o group.o validate.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-Signac/00new/Signac/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1:  7055 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --slave 2>&1 < '/var/folders/s6/sgdnr_3x3311v4jn8581ns9h0000gn/T//RtmpjPE12q/file1b7c7673880e'
ERROR: lazy loading failed for package ‘Signac’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Signac’
Warning in install.packages :
  installation of package ‘Signac’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/s6/sgdnr_3x3311v4jn8581ns9h0000gn/T/RtmpC7Xhf3/downloaded_packages’
```

**Comment by timoast** [comment]
I was able to install Signac on macOS Catalina R 4.0.2 without any issues. Did you install Bioconductor first?

**Comment by Connorr0** [comment]
Yes, although this computer was still using R 3.6

**Comment by timoast** [comment]
Killed: 9 is usually due to running out of RAM but I don't know why this would happen during installation (unless you had a tiny amount of RAM available). You could try restarting R and installing again in a fresh R session, and if that doesn't work maybe install R 4.0.2

**Comment by timoast** [comment]
If you're in a rush to get this working you could also use the [docker image](https://hub.docker.com/r/timoast/signac)

**Comment by lutservitz** [comment]
Hi Tim, 
I am getting the same error when installing Signac. I am using macOS Catalina, R 4.0.2, have enough RAM, and have Bioconductor version 3.11. Any idea on what my issue may be?

**Comment by timoast** [comment]
@lutservitz try installing in a fresh R session (outside of RStudio)

**Comment by lutservitz** [comment]
@timoast Hi Tim, thanks for your reply! I receive the same error in a fresh R session outside of RStudio as well.

I just ran again, and here is the error I receive:

`installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Signac/00new/Signac/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 23740 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/xr/4zs5t6756l75s3p43j5j6qj40000gn/T//Rtmpdg8PZQ/file5ca92a247767'
ERROR: lazy loading failed for package ‘Signac’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Signac’

The downloaded source packages are in
	‘/private/var/folders/xr/4zs5t6756l75s3p43j5j6qj40000gn/T/RtmpOn3IYD/downloaded_packages’
Warning message:
In install.packages("Signac") :
  installation of package ‘Signac’ had non-zero exit status`

**Comment by timoast** [comment]
Try reinstalling Rcpp (`install.packages("Rcpp")`)

If that still doesn't work you could try the suggestions here: https://github.com/satijalab/seurat/issues/3273#issuecomment-660562035

**Comment by YiminZhao97** [comment]
Hi, everyone. I got a similar question. I am using R 4.0.2 in Mac. When I want to install Signac, it failed. The errors are like that.

The downloaded source packages are in
	‘/private/var/folders/xj/m5zq_92n51582531fb0hz3tm0000gn/T/RtmpCsTMcK/downloaded_packages’
Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘lmtest’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘stringi’ had non-zero exit status

**Comment by timoast** [comment]
@YiminZhao97 you need to install those packages that failed (`install.packages(c("stringi", "lmtest"))`)

**Comment by YiminZhao97** [comment]
@timoas Hi, Tim. I did just like you suggested. 
install.packages(c("stringi", "lmtest"))

  There are binary versions available but the source versions are later:
        binary source needs_compilation
stringi  1.4.6  1.5.3              TRUE
lmtest  0.9-37 0.9-38              TRUE

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) 

I chose Yes. Then it failed like this:
Error in download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb"): download from 'http://www.gagolewski.com/software/stringi/icudt61l.zip' failed

icudt download failed
Error: Stopping on error
In addition: Warning messages:
1: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip': status was 'Couldn't connect to server'
2: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'https://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip': status was 'Couldn't connect to server'
: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu61/data/icudt61l.zip': status was 'Couldn't connect to server'
4: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://raw.githubusercontent.com/gagolews/stringi/master/src/icu55/data/icudt61l.zip': status was 'Couldn't connect to server'
5: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  downloaded length 84647 != reported length 10791080
6: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://www.ibspan.waw.pl/~gagolews/stringi/icudt61l.zip': status was 'Failure when receiving data from the peer'
7: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  downloaded length 2084855 != reported length 10791080
8: In download.file(paste(href, fname, sep = ""), icudtzipfname, mode = "wb") :
  URL 'http://www.gagolewski.com/software/stringi/icudt61l.zip': status was 'Transferred a partial file'
Execution halted
*** icudt download failed. stopping.
ERROR: configuration failed for package ‘stringi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/stringi’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/stringi’
Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status
* installing *source* package ‘lmtest’ ...
** 成功将‘lmtest’程序包解包并MD5和检查
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
gfortran -mmacosx-version-min=10.13 -fno-optimize-sibling-calls  -fPIC  -Wall -g -O2  -c pan.f -o pan.o
make: gfortran: No such file or directory
make: *** [pan.o] Error 1
ERROR: compilation failed for package ‘lmtest’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/lmtest’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/lmtest’
Warning in install.packages :
  installation of package ‘lmtest’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/xj/m5zq_92n51582531fb0hz3tm0000gn/T/RtmpCsTMcK/downloaded_packages’

**Comment by timoast** [comment]
@YiminZhao97 you can choose "No" to install the pre-compiled binaries rather than compiling from source

**Comment by timoast** [comment]
It looks like you're having issues downloading from CRAN, probably due to internet connectivity issues. You'll have to fix your internet connection
