### ISSUE TITLE
The dimplot so weird

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#217]
Hi @timoast ,
     I used the newest version to merge fours mouse ATAC data display weird dimplot.
![image](https://user-images.githubusercontent.com/41668708/92103162-25401480-ee12-11ea-877a-6a5642fff6f4.png)
what happen to this fours ATAC sample indicated lots of little cluster on the dimplot like below red arrow point.
![image](https://user-images.githubusercontent.com/41668708/92103352-6a644680-ee12-11ea-902d-908f1ac51529.png)
The code i token show following,
# load metadata
F1meta <- read.table(
  file = "./F1/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

F2meta <- read.table(
  file = "./F2/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

H1meta <- read.table(
  file = "./H1/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

H2meta <- read.table(
  file = "./H2/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

# perform an initial filtering of low count cells
F1 <- F1meta[F1meta$passed_filters > 500, ]
F2 <- F2meta[F2meta$passed_filters > 500, ]
H1 <- H1meta[H1meta$passed_filters > 500, ]
H2 <- H2meta[H2meta$passed_filters > 500, ] # sequenced deeper so set higher cutoff

F1frag <- CreateFragmentObject(
  path = "./F1/outs/fragments.tsv.gz",
  cells = rownames(F1)
)
F2frag <- CreateFragmentObject(
  path = "./F2/outs/fragments.tsv.gz",
  cells = rownames(F2)
)
H1frag <- CreateFragmentObject(
  path = "./H1/outs/fragments.tsv.gz",
  cells = rownames(H1)
)

H2frag <- CreateFragmentObject(
  path = "./H2/outs/fragments.tsv.gz",
  cells = rownames(H2)
)
# Quantify peaks in each dataset
setwd('/share/nas1/Data/Users/honghh/ScRNA_Project/jida_project_data/39')
# load('./mergedata.RData')
F1counts <- FeatureMatrix(
  fragments = F1frag,
  features = combined.peaks,
  cells = rownames(F1)
)

F2counts <- FeatureMatrix(
  fragments = F2frag,
  features = combined.peaks,
  cells = rownames(F2)
)
H1counts <- FeatureMatrix(
  fragments = H1frag,
  features = combined.peaks,
  cells = rownames(H1)
)
H2counts <- FeatureMatrix(
  fragments = H2frag,
  features = combined.peaks,
  cells = rownames(H2)
)
# Create the objects

F1counts_as <- CreateChromatinAssay(F1counts, fragments = F1frag)
F1obj <- CreateSeuratObject(F1counts_as, assay = "ATAC")

F2counts_as <- CreateChromatinAssay(F2counts, fragments = F2frag)
F2obj <- CreateSeuratObject(F2counts_as, assay = "ATAC")

H1counts_as <- CreateChromatinAssay(H1counts, fragments = H1frag)
H1obj <- CreateSeuratObject(H1counts_as, assay = "ATAC")

H2counts_as <- CreateChromatinAssay(H2counts, fragments = H2frag)
H2obj <- CreateSeuratObject(H2counts_as, assay = "ATAC")
####
# Merge objects
# add information to identify dataset of origin
F1obj$dataset <- 'F1'
F2obj$dataset <- 'F2'
H1obj$dataset <- 'H1'
H2obj$dataset <- 'H2'

# merge all datasets, adding a cell ID to make sure cell names are unique
combined <- merge(
  x = F1obj,
  y = list(F2obj, H1obj, H2obj),
  add.cell.ids = c("f1", "f2", "h1", "h2")
)

combined[["ATAC"]]

combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(combined)
combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')  

  Any advice would be appreciated.
  Regards,
   hanhuihong

**Comment by timoast** [comment]
How did you define `combined.peaks`?

You might need to perform more stringent filtering of cells based on total counts and QC metrics like TSS enrichment and nucleosome signal. If you look at the count distribution for each dataset using `VlnPlot` you should be able to decide on reasonable upper and lower cutoffs to use.

**Comment by honghh2018** [comment]
The combined.peaks defined like below,
F1 <- read.table(
  file = "./F1/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)
F2 <- read.table(
  file = "./F2/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)

H1 <- read.table(
  file = "./H1/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)
H2 <- read.table(
  file = "./H2/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)

##
# library(GenomicRanges)
# convert to genomic ranges
F1 <- makeGRangesFromDataFrame(F1)
F2 <- makeGRangesFromDataFrame(F2)
H1 <- makeGRangesFromDataFrame(H1)
H2 <- makeGRangesFromDataFrame(H2)
# Create a unified set of peaks to quantify in each dataset
combined.peaks <- reduce(x = c(F1, F2, H1, H2))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks
Then executed follow up analysis.
 There was a question about the merge?
  Should i filter the ATAC data individually like a sample did and then put it into one?
   Any advice would be appreciated
   Regards,
   hanhuihong

**Comment by honghh2018** [comment]
Hi @timoast ,
  I want to report a qc vlnplot in my case, it was very different between your vignitte's pbmc case and my mouse ATAC  data. it seem bad data for my mouse ATAC case that picture showing below
![image](https://user-images.githubusercontent.com/41668708/92211473-1bc2b500-eec3-11ea-99ff-9c5f9914b94d.png)
  my sample including a large number of cells, approximate 62520. Nevertheless, the cutoff condition that you posted on vignitte had cells filter out about 56000 cell.  the filter cell so big, and then, the rest cells was just 5600 or so.
   Based above condition,   any advice would be appreciated.
    Had any advice about my  data cutoff to filter my data?  thanks again.
     Regards,
      hanhuihong

**Comment by timoast** [comment]
How many cells do you expect to have in the dataset? If this is from 4 10x experiments I doubt that you'd expect to have 62k cells. You can also use the list of cells output by cellranger if you're not confident in defining your own count-based cutoffs

**Comment by honghh2018** [comment]
> How did you define `combined.peaks`?
> You might need to perform more stringent filtering of cells based on total counts and QC metrics like TSS enrichment and nucleosome signal. If you look at the count distribution for each dataset using `VlnPlot` you should be able to decide on reasonable upper and lower cutoffs to use.

Sorry to reopen this issue,  About your mention on total counts and qc metrics. should i plot the meta.data colnames like 'nFeature_peaks', 'nCount_peaks','total'  using Vlnplot just like below ?
 The vlnplot,
![image](https://user-images.githubusercontent.com/41668708/97245880-fa34d880-1836-11eb-9a1d-216784e23129.png)
 which cutoff should be set on this Vlnplot ? the red arrow?
  
![image](https://user-images.githubusercontent.com/41668708/97246052-60b9f680-1837-11eb-851d-629d8d1dc59e.png)
  Any advice would be appreciated.
   hanhuihong
