### ISSUE TITLE
Gene activity after merging

### ISSUE THREAD

**Issue by ArisStefanosSn** [timoast/signac#218]
Hello,

I am following the tutorial (link1: https://satijalab.org/signac/articles/merging.html) to merge two 10x scATAC samples / runs (cell ranger-atac-1.2.0), "ms43" and "ms44", annotate them with hg19 (link2: https://satijalab.org/signac/articles/pbmc_vignette.html) and then estimate the gene activities (link2). The gene activities I obtain are all 0 which is weird. The UMAP plot gives a meaningful cluster separation (see code section merge below; not using the gene activities). 

Running the analysis per sample and estimating gene activity as shown in link 1, gives me similar cluster separation and positive gene activities for several features / cells (I am using the same annotation and cutoffs). Can you please suggest why this occurs in the merged dataset? Should I estimate the gene activities per sample and then merge (will that merge the gene activities)? 

I paste my code below. Thank you very much!

#################
# process the peaks #
#################
peaks43<-read.table(paste(input_MS20043_hg19_bedfiles,"peaks.bed",sep=""),col.names=c("chr","start","end"))
peaks44<-read.table(paste(input_MS20044_hg19_bedfiles,"peaks.bed",sep=""),col.names=c("chr","start","end"))
gr43 <- makeGRangesFromDataFrame(peaks43)
gr44 <- makeGRangesFromDataFrame(peaks44)

##################
# combine the peaks #
##################
combined.peaks <- reduce(x = c(gr43, gr44))
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]

################################################
# read the singlecell meta and filter                                               #
# filtering is based on the analysis of each                                   #
#    individual sample as shown in link1 (not shown in this code) #
################################################
md43 <- read.table(file = paste(input_MS20043_hg19_bedfiles,"singlecell.csv",sep=""),
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1)[-1, ]
md44 <- read.table(file = paste(input_MS20044_hg19_bedfiles,"singlecell.csv",sep=""),
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1)[-1, ]
md43 <- md43[match(as.character(colnames(ms20043@assays$peaks@data)),as.character(rownames(md43)),nomatch=0),]
md44 <- md44[match(as.character(colnames(ms20044@assays$peaks@data)),as.character(rownames(md44)),nomatch=0), ]

####################
# read the fragments #
###################
frags43 <- CreateFragmentObject(path=paste(input_MS20043_hg19_bedfiles,"fragments.tsv.gz",sep=""),cells = rownames(md43))
frags44 <- CreateFragmentObject(path=paste(input_MS20044_hg19_bedfiles,"fragments.tsv.gz",sep=""),cells = rownames(md44))

###########################
# make the counts and the assay
###########################
counts43 <- FeatureMatrix(fragments = frags43,features = combined.peaks,cells = rownames(md43))
counts44 <- FeatureMatrix(fragments = frags44,features = combined.peaks,cells = rownames(md44))

assay43 <- CreateChromatinAssay(counts43, fragments = frags43,sep=c(":","-"),min.cells=10,min.features=200,genome="hg19")
ms43 <- CreateSeuratObject(assay43, assay = "ATAC",meta.data=md43)
assay44 <- CreateChromatinAssay(counts44, fragments = frags44,sep=c(":","-"),min.cells=10,min.features=200,genome="hg19")
ms44 <- CreateSeuratObject(assay44, assay = "ATAC",meta.data=md44)
 
ms43$dataset <- 'ms43'
ms44$dataset <- 'ms44'

################
# merge
################
combined <- merge(x = ms43,y = ms44,add.cell.ids = c("ms43","ms44"))

combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(combined)
combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')
combined <- FindNeighbors(object = combined, reduction = 'lsi', dims = 2:30)
combined <- FindClusters(object = combined, verbose = FALSE, algorithm = 3)

####################
# annotate with hg19
###################
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "hg19"
Annotation(combined) <- annotations

#######################
# get gene activities
#######################
gene.activities <- GeneActivity(combined)

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/205
