### ISSUE TITLE
Issues when trying to coembed scRNA and scATAC data

### ISSUE THREAD

**Issue by chent5** [timoast/signac#219]
Thanks a lot for developing this very useful package. I met some problems when trying to coembed the scRNA-seq and scATAC-seq data. 

"pbmc.rna" is a Seurat object of scRNA-seq processed by Seurat package.
"pbmc.atac" is a Seurat object of scATAC-seq processed by Signac package. Gene activity matrix has been computed and stored in "RNA" assay.
scATAC and scRNA data are from the same person and the same tissue.

#### dataset prep
```
pbmc.rna$tech <- "RNA"
DefaultAssay(pbmc.atac) <- 'RNA'
pbmc.atac$tech <- "ATAC"
```

#### label transfer: categorical variables
```
transfer.anchors <- FindTransferAnchors(
  reference = pbmc.rna, 
  query = pbmc.atac, reduction = "cca"
  )

celltype.predictions <- TransferData(
  anchorset = transfer.anchors,
  refdata = pbmc.rna$CellType,
  weight.reduction = pbmc.atac[['lsi']],
  dims = 2:30
)

pbmc.atac <- AddMetaData(pbmc.atac, metadata = celltype.predictions)
hist(pbmc.atac$prediction.score.max)
abline(v = 0.5, col = "red")
```
![image](https://user-images.githubusercontent.com/40006284/92252800-bc51ae80-ee9c-11ea-8d41-a96b6f27eba1.png)
```
p1 <- DimPlot(pbmc.atac, group.by = "predicted.id", label = TRUE, repel = TRUE) + ggtitle("Label transferred") + 
  NoLegend() + scale_colour_hue(drop = FALSE)
p2 <- DimPlot(pbmc.atac, group.by = "CellType", label = TRUE, repel = TRUE) + ggtitle("Annotated") + 
  NoLegend() + scale_colour_hue(drop = FALSE)
p1 + p2
```
![image](https://user-images.githubusercontent.com/40006284/92252970-f9b63c00-ee9c-11ea-8508-51e3956778ae.png)

"CellType" was annotated based on biological knowledge and peak accessibility. "predicted.id" was transferred from scRNA data set. The predicted ids are very consistent with the annotated cell types.

After that, I intended to look at co-embedding.

#### Compute co-embedding
```
genes.use <- VariableFeatures(pbmc.rna)
refdata <- GetAssayData(pbmc.rna, assay = "RNA", slot = "data")[genes.use, ]

imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, 
                           weight.reduction = pbmc.atac[["lsi"]],  dims = 2:30)

pbmc.atac[["RNA"]] <- imputation
coembed <- merge(x = pbmc.rna, y = pbmc.atac)

coembed <- ScaleData(coembed, features = genes.use, do.scale = FALSE)
coembed <- RunPCA(coembed, features = genes.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)
coembed$NewLabel <- ifelse(!is.na(coembed$predicted.id), coembed$predicted.id, coembed$CellType)
```
#### visualization
```
p1 <- DimPlot(coembed, group.by = "tech")
p2 <- DimPlot(coembed, group.by = "NewLabel")
p1 + p2
```
![image](https://user-images.githubusercontent.com/40006284/92253592-b14b4e00-ee9d-11ea-81c1-ba819c9bbe58.png)

However, coembedding is failed. In ATAC seq data, I cannot even see a separation between cell types. I really can't figure out where problems are... Is there anything wrong with my code? Thank you so much!

**Comment by timoast** [comment]
It looks like you have two separate batches in the scRNA dataset that have very strong batch differences, and that might be affecting the imputed values in the ATAC. I'd recommend integrating the RNA datasets and imputing the batch-corrected values in the ATAC dataset for co-embedding

**Comment by chent5** [comment]
Thanks a lot for your prompt response. Both RNA and ATAC objects contain the samples under different conditions from the same patient. The samples are sent for both RNA and ATAC sequencing. Thus, the only difference between RNA and ATAC objects are the techniques. 

I understand your point, so I subset the cells under each condition and try coembedding again. In this way, there is only one batch included in both RNA and ATAC object. So there is no batch effect issue. Here is my code:
```
# pbmc.rna & pbmc.atac are subsetted seurat object containing the cells under only one condition.
# label transfer
transfer.anchors <- FindTransferAnchors(
  reference = pbmc.rna, 
  query = pbmc.atac, reduction = "cca",
  reference.assay = "RNA",
  query.assay = "RNA",
  )

celltype.predictions <- TransferData(
  anchorset = transfer.anchors,
  refdata = pbmc.rna$CellType,
  weight.reduction = pbmc.atac[['lsi']],
  dims = 2:30
)

pbmc.atac <- AddMetaData(pbmc.atac, metadata = celltype.predictions)

###  Compute co-embedding  ###
genes.use <- VariableFeatures(pbmc.rna)
refdata <- GetAssayData(pbmc.rna, assay = "RNA", slot = "data")[genes.use, ]

imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, 
                           weight.reduction = pbmc.atac[["lsi"]],  dims = 2:30)

pbmc.atac[["RNA"]] <- imputation
coembed <- merge(x = pbmc.rna, y = pbmc.atac)

coembed <- ScaleData(coembed, features = genes.use, do.scale = FALSE)
coembed <- RunPCA(coembed, features = genes.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)
coembed$NewLabel <- ifelse(!is.na(coembed$CellType), coembed$CellType, coembed$predicted.id)
```
The transferred cell type labels make a lot of sense as before. There is only one batch included in pbmc.rna and pbmc.atac, but the co-embedding still does't work... Different cell types in pbmc.atac are still mixed together. Here are the figures:
![image](https://user-images.githubusercontent.com/40006284/92307110-ff298a00-ef61-11ea-89dc-3d132feeac31.png)

Is there anything wrong with the parameter settings I used? Thanks so much for your help!

**Comment by timoast** [comment]
I'm wondering if the RNA assay somehow isn't being overwritten when you assign the new imputed assay. What happens if you name the RNA activity assay something else (eg, "ACTIVITY")?

**Comment by chent5** [comment]
I checked the dimension of the RNA assay using the code below before and after adding the imputed data matrix to the pbmc.atac object.
`dim(pbmc.atac@assays$RNA)`

At the every beginning, the dimension are 19713 vs. 450, which is the matrix of computed gene activity using scATAC data. After adding the imputed data to pbmc.atac object RNA assay, the dimension are 3000 vs. 450. 3000 is the number of variable features in pbmc.rna, which indicates the RNA assay of pbmc.atac has been successfully changed into the imputed matrix.

I took a look at the pca embedding for the coembed object. I found that the cells from scRNA tend to be separated based on cell types, but all cells from scATAC get the same PCA projection...
<img width="564" alt="image" src="https://user-images.githubusercontent.com/40006284/92551171-60d04980-f22b-11ea-86f9-fdfc2555b9b2.png">

Here is the screenshot for the pca embeddings:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/40006284/92551227-7e9dae80-f22b-11ea-8ba3-77182a9987a6.png">
The cells ended with "-4_3" are from scRNA, and the ones ended with "-4$" are from scATAC.

**Comment by timoast** [comment]
I'd suggest trying this:
1. Look at the imputed gene expression values in the scATAC-seq dataset on the original scATAC-seq UMAP (the one you showed in the first comment) and check if marker genes are being imputed in the cell types you'd expect or if they're imputed uniformly across all cells
2. Try running ScaleData with `do.scale=TRUE`

**Comment by chent5** [comment]
Thanks a lot for the suggestion.

First, I looked at the imputed celltype-specific marker genes:
```
genes.use <- VariableFeatures(pbmc.rna)
imputation <- TransferData(anchorset = transfer.anchors, refdata = refdata, 
                           weight.reduction = pbmc.atac[["lsi"]],  dims = 2:30)
pbmc.atac[["RNA"]] <- imputation

# check marker gene expression
FeaturePlot(
  object = pbmc.atac,
  features = c("CD14", "FCGR3A", "CD1C"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  ncol = 3
)
```
![image](https://user-images.githubusercontent.com/40006284/92771723-24a30300-f369-11ea-9720-143db598f00f.png)
The imputed marker genes largely make sense.

Then, I tried running ScaleData with do.scale = T:

```
coembed <- merge(x = pbmc.rna, y = pbmc.atac)
coembed <- ScaleData(coembed, features = genes.use, do.scale = T)
coembed <- RunPCA(coembed, features = genes.use, verbose = FALSE)
coembed <- RunUMAP(coembed, dims = 1:30)
coembed$NewLabel <- ifelse(!is.na(coembed$CellType), coembed$CellType, coembed$predicted.id)

# visualization
p1 <- DimPlot(coembed, group.by = "tech")
p2 <- DimPlot(coembed, group.by = "NewLabel", label = TRUE, repel = TRUE)
p1 + p2
```
![image](https://user-images.githubusercontent.com/40006284/92772164-7ba8d800-f369-11ea-9913-db097d4b671b.png)
However, coembedding still doesn't work...

**Comment by timoast** [comment]
I don't really have any other suggestions, I'm not sure why this isn't working. It seems like it should if the imputed expression values seem correct. Since the coembedding is purely for visualization and really serves no other purpose I'd suggest moving on

**Comment by plantformatics** [comment]
I am having a similar issue, anyone else find a solution?

**Comment by dhoneyi** [comment]
I have solved the issue. You can check the activity assay in your scRNA object and scATAC object. Make sure the scRNA activity assay is 'RNA' may works.

**Comment by dhoneyi** [comment]
> I am having a similar issue, anyone else find a solution?

I have solved the issue. You can check the activity assay in your scRNA object and scATAC object. Make sure the scRNA activity assay is 'RNA' may works.
