### ISSUE TITLE
error when using CreateChromatinAssay command

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#221]
Hi,

 I'm getting the following error when trying to read in the fragments.tsv.gz file

Error: Can't extract columns that don't exist.
x Column `ranges` doesn't exist.

I'm attaching a screen shot of the fragment file.

I need some helping addressing this problem.

Thanks!!!
![fragments](https://user-images.githubusercontent.com/64283689/92417567-7c066080-f128-11ea-82f5-0707c4ccac44.png)

**Comment by timoast** [comment]
Can you include the full code you ran?

**Comment by sylestiel** [comment]
```{r}
filepath <- "/Volumes/...../scATAC_data/72020_scATAC/SH7_P2/outs/filtered_peak_bc_matrix/"

peaks <- read.table(paste0(filepath, "peaks.bed"), header = FALSE)
cells <- read.table(paste0(filepath, "barcodes.tsv"), header = FALSE, stringsAsFactors = FALSE)
rownames(cells) <- make.unique(cells$V1)

mtx <- readMM(file = paste0(filepath, "matrix.mtx"))
mtx <- as(object = mtx, Class = "dgCMatrix")
colnames(mtx) <- rownames(cells)
rownames(mtx) <- peaks$Feature
```

```{r}
SH7_assay <- CreateChromatinAssay(
  counts = mtx,
  min.cells = 5,
  fragments = "/Volumes,,,,/scATAC_data/72020_scATAC/SH7_P2/outs/fragments.tsv.gz",
  sep = c("_", "_"),
  genome = "hg19"
)
SH7 <- CreateSeuratObject(
  counts = SH7_assay,
  meta.data = cells,
  assay = "ATAC"
)

SH7[["ATAC"]]
```

**Comment by sylestiel** [comment]
FYI- I'm using cell ranger output for the analysis

**Comment by sylestiel** [comment]
The genome is mm10 not hg19

**Comment by timoast** [comment]
At what line do you get the error?

Can you show the output of `traceback()` run immediately after the error occurs?

**Comment by sylestiel** [comment]
[Error.docx](https://github.com/timoast/signac/files/5185312/Error.docx)

**Comment by timoast** [comment]
The error message suggest that you're using the wrong separators for the genomic ranges. What's the output of `head(rownames(mtx))`?

**Comment by sylestiel** [comment]
It says NULL

**Comment by timoast** [comment]
That's the problem. My guess is that there's no column named "Feature" in the peak bed file that you're reading in. If it's the standard output from cellranger this would be a standard BED file with three columns (chromosome, start, end) and no header. If you ensure that the features are named correctly this issue should be resolved. Alternatively you can use the `Seurat::Read10X_h5()` function to read the `.h5` file output by cellranger, as shown in the Signac vignettes

**Comment by sylestiel** [comment]
Yes it is the peak.bed file.  Thanks for your suggestion!

**Comment by liuxuesunny** [comment]
Hi There, 

I had the same problem and switched to .h5 files, however when I run makeGRangesFromDataFrame with the peaks readin from .h5 file, it shows: Error in .find_start_end_cols(df_colnames0, start.field0, end.field0) : cannnot determine start/end columns. Any suggestions? Thanks.

**Comment by ZeitgeberH** [comment]
Had the same error following the vignette. 
It turns out that my h5 file from `cellranger-atac` have two assays, "counts$Peaks" for ATAC,  "counts$`Gene Expression`" for gene expressions. Thus, 
Change the code from: 
`chrom_assay <- CreateChromatinAssay(
  counts = counts, 
  sep = c(":", "-"),
  genome = 'hg19',
  fragments = sampleFragmentsFile,
  min.cells = 10,
  min.features = 200,
)`

to 
`
chrom_assay <- CreateChromatinAssay(
  counts = counts$Peaks,
  sep = c(":", "-"),
  genome = 'hg19',
  fragments = sampleFragmentsFile,
  min.cells = 10,
  min.features = 200,
)`

would resolve the errors.

**Comment by colinmcgovern** [comment]
I also got this same issue. It was because my "counts" object was not loaded from the proper filepath
