### ISSUE TITLE
Error message when running FindMotifs()

### ISSUE THREAD

**Issue by chent5** [timoast/signac#223]
Hi Tim,

Thanks a lot for developing this very useful package.

I got an error message when running the code below:
```
enriched.motifs <- FindMotifs(
    object = signac.object,
    features = da.list[[i]]
  )
```
Here is the error message: "Testing motif enrichment in 265 regions
Error in smooth.spline(lambda, pi0, df = smooth.df) : 
  missing or infinite values in inputs are not allowed".

Actually, I used a loop to do motif enrichment for a list of differential accessible peaks. Each list element contains a vector of the DA peaks for a specific cluster. The error only occurs in a specific loop but not all.

I googled this error and I found this link https://support.bioconductor.org/p/105623/
It seems something wrong happens when computing q value. Is there any way to bypass this error or computing q value? I can compute adjusted p-value later after I get all the motif enrichment results.

**Comment by timoast** [comment]
It looks like when there are a lot of p-values close to zero, qvalue has trouble estimating pi0. Since this can often happen when finding enriched motifs, and it's easy for users to compute adjusted p-values themselves using whatever method they prefer, I have removed the qvalue calculation (0a3b4de96e4555fa13cb7c8c3015003b1fe12bbd). This is currently available on the develop branch

**Comment by cacaonib** [comment]
> It looks like when there are a lot of p-values close to zero, qvalue has trouble estimating pi0. Since this can often happen when finding enriched motifs, and it's easy for users to compute adjusted p-values themselves using whatever method they prefer, I have removed the qvalue calculation ([0a3b4de](https://github.com/timoast/signac/commit/0a3b4de96e4555fa13cb7c8c3015003b1fe12bbd)). This is currently available on the develop branch

really sorry. i watched 0a3b4d. but i can't understand that how apply in my R environment. please explicate this command and work flow in detail thank you
