### ISSUE TITLE
scATAC-seq merging objects and perform follow-up analysis?

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#225]
Hi 

I want to compare the difference between normal tissue and tumor. I want to merge two scATAC-seq data (normal and tumor) first, and then find differentially expressed genes between samples.
But after merging the two scATAC-seq data, I have encountered problems, how should I perform follow-up analysis?
For example, QC, gene activity matrix, Plotting genomic regions.
or is there a better analysis method?

Thank you

**Comment by timoast** [comment]
You can follow the standard analysis workflow shown in other vignettes using the merged object

**Comment by Ping-lin14** [comment]
Hi timoast
After merging the objects, I ran into a problem on QC, I couldn’t find "pct_reads_in_peaks", "peak_region_fragments", "blacklist_ratio".
 below is my code
`gr <- GRanges(seqnames = "chr1", ranges = IRanges(start = c(20, 70, 300), end = c(120, 200, 400)))
gr

library(Signac)
library(Seurat)
library(GenomicRanges)
library(future)

plan("multiprocess", workers = 4)
options(future.globals.maxSize = 50000 * 1024^2) # for 50 Gb RAM

# read in peak sets
peaks_n <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_N/peaks.bed",
  col.names = c("chr", "start", "end")
)

peaks_t <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_T/peaks.bed",
  col.names = c("chr", "start", "end")
)

# convert to genomic ranges
gr.thym_n <- makeGRangesFromDataFrame(peaks_n)
gr.thym_t <- makeGRangesFromDataFrame(peaks_t)

# Create a unified set of peaks to quantify in each dataset
combined.peaks <- reduce(x = c(gr.thym_n,gr.thym_t))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks

# load metadata
md.thtm_n <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_N/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

md.thym_t <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_T/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.thtm_n <- md.thtm_n[md.thtm_n$passed_filters > 500, ]
md.thym_t <- md.thym_t[md.thym_t$passed_filters > 500, ]

# create fragment objects
frags.n <- CreateFragmentObject(
  path = "C:/Users/Jacky/Desktop/ATCT/s3234_N/fragments.tsv.gz",
  cells = rownames(md.thtm_n)
)

frags.t <- CreateFragmentObject(
  path = "C:/Users/Jacky/Desktop/ATCT/s3234_T/fragments.tsv.gz",
  cells = rownames(md.thym_t)
)

thtm_n.counts <- FeatureMatrix(
  fragments = frags.n,
  features = combined.peaks,
  cells = rownames(md.thtm_n)
)

thym_t.counts <- FeatureMatrix(
  fragments = frags.t,
  features = combined.peaks,
  cells = rownames(md.thym_t)
)

thym_n_assay <- CreateChromatinAssay(thtm_n.counts, fragments = frags.n)
normal <- CreateSeuratObject(thym_n_assay, assay = "ATAC")

thym_t_assay <- CreateChromatinAssay(thym_t.counts, fragments = frags.t)
tumor <- CreateSeuratObject(thym_t_assay, assay = "ATAC")

normal$dataset <- 'normal'
tumor$dataset <- 'tumor'

combined <- merge(
  x = normal,
  y = list(tumor),
  add.cell.ids = c("N", "T")
)
combined[["ATAC"]]

combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(combined)
combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')

DimPlot(combined, group.by = 'dataset', pt.size = 0.1)

CoveragePlot(
  object = combined,
  group.by = 'dataset',
  region = "chr14-99700000-99760000"
)

combined[['peaks']]

granges(combined)
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)

# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "hg19"

# add the gene information to the object
Annotation(combined) <- annotations

# compute nucleosome signal score per cell
thym_merging <- NucleosomeSignal(object = combined)

# compute TSS enrichment score per cell
thym_merging <- TSSEnrichment(object = thym_merging, fast = FALSE)

# add blacklist ratio and fraction of reads in peaks
thym_merging$pct_reads_in_peaks <- thym_merging$peak_region_fragments / thym_merging$passed_filters * 100
thym_merging$blacklist_ratio <- thym_merging$blacklist_region_fragments / thym_merging$peak_region_fragments

thym_merging$high.tss <- ifelse(thym_merging$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(thym_merging, group.by = 'high.tss') + NoLegend()

thym_merging$nucleosome_group <- ifelse(thym_merging$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram(object = thym_merging, group.by = 'nucleosome_group')

VlnPlot(
  object = thym_merging,
  features = c('pct_reads_in_peaks', 'peak_region_fragments',
               'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal'),
  pt.size = 0.1,
  ncol = 5
)

`
How can I solve it?
