### ISSUE TITLE
Trajectory with Monocle

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#226]
Hi Tim,

For the purposes of constructing a trajectory in Signac is it okay to run the  mouse_brain_vignette up to the integration with scRNA seq dataset and then run the downstream steps outlined in "Building trajectories with Monocle 3".

Would that suffice or are there specific lines of script in the trajectory vignette that must be executed prior to the section entitled  "Building trajectories with Monocle 3".

Also when it comes to ordering cells based on lineage (erythroid, lymphoid) or cell states can we use the predicted.id discerned from the Seurat objects subsequent to the integration of scATAC with scRNA seq dataset?

Thanks!

**Comment by timoast** [comment]
Yes. The vignettes are just meant to demonstrate the functionality available in Signac, you can certainly combine different analysis steps to suit your own goals
