### ISSUE TITLE
Generating root cells txt

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#227]
<img width="704" alt="Screen Shot 2020-09-09 at 1 27 03 PM" src="https://user-images.githubusercontent.com/64283689/92638665-3d93b180-f2a0-11ea-955a-e9f2b6cc6428.png">

Hi Tim,
Please advice on how to generate a list of root cells. I tried to look up promoter sums in C loupe Browser based on specific genes and then exported the barcodes of cells expressing them.

 I got the error that reads as follows:
All provided root_cells must be present in the cell data set.

What should i do to address this problem?

Thanks!

**Comment by timoast** [comment]
This is an issue for monocle3: https://github.com/cole-trapnell-lab/monocle3
