### ISSUE TITLE
R session aborted while running FindTransferAnchors

### ISSUE THREAD

**Issue by piscesmk** [timoast/signac#23]
Hello Tim,

I've tried to integrate two 10X scATAC data sets using Seurat/Signac, however when I run the "FindTransferAnchor" function,  R session has always been automatically stopped. I tried other computers, but same problem always popped up. 

_transfer.anchors.WT <- FindTransferAnchors(reference = WT.RNA, query = WT, reduction = 'cca', dims = 1:50)_

![Screen Shot 2019-09-13 at 10 59 37 AM](https://user-images.githubusercontent.com/48770715/64872683-a0af2180-d615-11e9-9a9b-27dec1e30653.png)

**Comment by millersan** [comment]
Hi piscesmk！
Could you help me？Cause I met the same problem

**Comment by funpys** [comment]
> Hi piscesmk！
> Could you help me？Cause I met the same problem
I think rownames should be identical, both scRNA & scATAC objects.
https://github.com/satijalab/seurat/issues/2392
