### ISSUE TITLE
Following error crept up when running CreateChromatinAssay 

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#232]
Computing hash
Checking for 3542 cell barcodes
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to ftp.ncbi.nlm.nih.gov port 21: Connection refused

How may I override it?

Thanks!

**Comment by timoast** [comment]
This indicates you're not able to connect to the internet. You haven't included the code you're running, but if you specify the name of a genome (hg19 or mm10 for example) for the `genome` parameter it will attempt to download the seqinfo for that genome from UCSC (see the [documentation](https://satijalab.org/signac/reference/CreateChromatinAssay.html) for CreateChromatinAssay). To avoid this error either provide a Seqinfo object to the `genome` parameter or leave it empty, or fix the internet connection

**Comment by sylestiel** [comment]
<img width="941" alt="Screen Shot 2020-09-10 at 4 15 18 PM" src="https://user-images.githubusercontent.com/64283689/92807830-d699f980-f380-11ea-8f33-d17bafc48e3c.png">
<img width="827" alt="Screen Shot 2020-09-10 at 4 14 51 PM" src="https://user-images.githubusercontent.com/64283689/92807843-d7cb2680-f380-11ea-92bb-2abe6c5e6284.png">


FYI:  It was working for me but I had to restart the analysis a few times to change certain parameters. Subsequently, it gave me this error. Internet is working fine.

**Comment by sylestiel** [comment]
Also restarted the computer twice to no avail.

**Comment by timoast** [comment]
The error is due to failing to connect to NCBI so it's not something in Signac. Running `GenomeInfoDb::Seqinfo(genome="mm10")` would also fail. As I mentioned above you have a few options for solving this

**Comment by sylestiel** [comment]
<img width="707" alt="Screen Shot 2020-09-10 at 5 10 45 PM" src="https://user-images.githubusercontent.com/64283689/92814405-ab1b0d00-f388-11ea-8f15-a6248bde4780.png">

I tried the wget option in terminal but was still unable to proceed.  I'm not clear on what you are saying. Can you simplify it for me further.

**Comment by timoast** [comment]
You don't need to set the `genome` parameter to create the ChromatinAssay, so unless there's a particular reason you need it you should leave it as `NULL` (the default) and move on.

If there is a specific reason that you need to set this parameter, you should supply a `seqinfo` object for your genome rather than the name of the genome, since your R session is not able to connect to NCBI. One way to do this would be to load the BSgenome object for mm10 and extract the seqinfo from there. For example:

```r
library(BSgenome.Mmusculus.UCSC.mm10)
genome <- seqinfo(BSgenome.Mmusculus.UCSC.mm10)
```

**Comment by sylestiel** [comment]
Got it! Thank you very much!

**Comment by MaraLlamas** [comment]
Hi!
I am trying to run the Analyzing PBMC scATAC-seq vignette but I am having this same error when trying to change EnsDb annotations to UCSC annotations

```
> # change to UCSC style since the data was mapped to hg19
> ensembldb::seqlevelsStyle(annotations) <- 'UCSC'
Error in function (type, msg, asError = TRUE)  : 
  Failed to connect to ftp.ncbi.nlm.nih.gov port 21: Timed out
```
  
I tried to leave the `genome` parameter as default when creating the ChromatinAssay and then proceed by also skipping this step, but this creates a problem later with the TSSEnrichment function

```
> pbmc <- TSSEnrichment(object = pbmc, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  : 
  attempt to set 'colnames' on an object with less than two dimensions
```
which I read somewhere it is caused because annotations don't match. 
Then, I don't know how to proceed.

Any help is very appreciated.
Thanks

**Comment by 1061047021lql-AI** [comment]
> Hi, I also encountered a similar problem as @MaraLlamas when following the Analyzing PBMC scATAC-seq vignette. And I noticed the problem is that when I first ran `annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)` and then ran `seqlevelsStyle(annotations) <- 'UCSC'`, I got the Timed out error as below:
> 
> ```r
> > seqlevelsStyle(annotations) <- 'UCSC'
> Error in function (type, msg, asError = TRUE)  : 
>   Failed to connect to ftp.ncbi.nlm.nih.gov port 21: Operation timed out
> ```
> 
> But if I converted the style to `'UCSC'` first by doing the following steps, calling `seqlevelsStyle()` won't give me timed out error. So I think I don't have a connection issue to NCBI.
> 
> ```r
> # extract gene annotations from EnsDb
> edb <- EnsDb.Mmusculus.v79
> 
> # change to UCSC style since the data was mapped to mm10
> seqlevelsStyle(edb) <- "UCSC"
> annotations <- GetGRangesFromEnsDb(edb)
> ```
> 
> However, I got a lot warnings as below because I convert the style before calling `GetGRangesFromEnsDb()`.
> 
> ```r
> Warning in .formatSeqnameByStyleFromQuery(x, sn, ifNotFound) :
>   More than 5 seqnames with seqlevels style of the database (Ensembl) could not be mapped to the seqlevels style: UCSC!) Returning the orginal seqnames for these.
> ```
> 
> Is there a way to solve this issue? Thanks!

**Comment by 1061047021lql-AI** [comment]
I have the same error when I run analyze PBMC Scatac-seq vignette, but when I try to change EnsDb comment to UCSC comment, have you fixed this problem?  Thank you very much! 

 seqlevelsStyle(annotation) <- "UCSC" 
Error in function (type, msg, asError = TRUE)  :
 Failed to connect to ftp.ncbi.nlm.nih.gov port 21 after 68137 ms: Connection timed out

**Comment by carversh** [comment]
This is a function of the server being down. Try retrying this.
