### ISSUE TITLE
QC problem after merged object

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#233]
Hi timoast

You told me that I should modify the meta.data parameter in CreateSeuratObject, but I still don’t know what I should add? filtered_peak_bc_matrix.h5? Can you tell me the details?

thank you.

**Comment by timoast** [comment]
To add metadata to the Seurat object you can set the `meta.data` parameter in `CreateSeuratObject()`. See the documentation for `CreateSeuratObject()`, and the [vignettes](https://satijalab.org/signac/articles/pbmc_vignette.html)
