### ISSUE TITLE
geneeration of conns

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#234]
Hi Tim,

How can I address the following error?

> genome <- seqlengths(SH7P2)
> 
> # use chromosome 1 to save some time
> # omit this step to run on the whole genome
> #genome <- genome[1]
> mouse.mm10.genome <- read.table(file = "~/Downloads/chromInfo.txt")
> # convert chromosome sizes to a dataframe
> genome.df <- data.frame("1:19, X, Y" = names(mouse.mm10.genome))
> 
> # run cicero
> conns <- run_cicero(SH7P2.cicero, genomic_coords = genome.df, sample_num = 100)
[1] "Starting Cicero"
[1] "Calculating distance_parameter value"
Error in names(chr_maxes) <- c("V1", "V2") : 
  'names' attribute [2] must be the same length as the vector [1]

Thanks!

**Comment by sylestiel** [comment]
Nevermind!  Addressed it.

**Comment by ZayaAyush** [comment]
Hi [sylestiel](https://github.com/sylestiel),
How did you address this error? I have same problem.
