### ISSUE TITLE
Error in knitr::kable step of motif analysis

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#237]
knitr::kable(head(enriched.motifs))
Error in kable_mark(x, c(NA, "-", NA), "|", padding, align.fun = function(s,  : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/xfun/R/xfun.rdb' is corrupt
In addition: Warning messages:
1: In kable_mark(x, c(NA, "-", NA), "|", padding, align.fun = function(s,  :
  restarting interrupted promise evaluation
2: In kable_mark(x, c(NA, "-", NA), "|", padding, align.fun = function(s,  :
  internal error -3 in R_decompress1

**Comment by timoast** [comment]
Looks like you need to reinstall xfun. By the way, the use of `knitr::kable` in the vignette is only for formatting purposes and is not needed for the analysis. You can just run `head(enriched.motifs)` if you want to look at the top enriched motif results.

**Comment by sylestiel** [comment]
Thanks!!
Loving all the additions to Signac!!!
