### ISSUE TITLE
Error in .headerTabix(file,(...

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#242]
Hi Tim,

What does the following error message mean? How may I fix it?

FragmentHistogram(object = SH2E16, group.by = 'nucleosome_group', region = 'chr1-1-10000000')
Error in .headerTabix(file, ...) : [internal] bgzf_seek() failed

Thank you!

**Comment by timoast** [comment]
Can you try accessing the same range from the fragment file on the command line using tabix?

```
tabix <fragment_file> chr1:1-10000000
```

**Comment by sylestiel** [comment]
When I enter the following
tabix '/Volumes/BKUP2/scATAC_data/72020_scATAC/SH2_E165/outs/fragments.tsv.gz' chr1:1-10000000
It prompts for the next line with $

I guess it ran

**Comment by timoast** [comment]
If nothing is printed then that means there are no fragments in that region. Can you print the first few lines of the fragment file and show them here? `gzip -dc <fragment_file> | head`

**Comment by sylestiel** [comment]
<img width="414" alt="Screen Shot 2020-09-16 at 3 58 11 PM" src="https://user-images.githubusercontent.com/64283689/93391863-7221e300-f835-11ea-90ec-15cbb7abaabd.png">

**Comment by timoast** [comment]
It seems like maybe something is wrong with the file index, because tabix isn't returning entries even though you have fragments in the region. How did you create the fragment file and index? I'd suggest decompressing the file, re-compressing with bgzip and then re-indexing with tabix, then run `tabix <fragment_file> chr1:1-10000000` and see if it prints the expected lines

**Comment by sylestiel** [comment]
The fragment file was generated by someone else who used Cell Ranger for that purpose.
Can you provide the scripts to do so?

**Comment by timoast** [comment]
```
gzip -d <fragments>
bgzip <fragments>
tabix -p bed <fragments>
```

**Comment by sylestiel** [comment]
Okay it appears to have worked in the command line. Going to try it in R. Thanks!!

**Comment by sylestiel** [comment]
Awesome. It worked!!!
