### ISSUE TITLE
normalisation points along integration workflow

### ISSUE THREAD

**Issue by Nicholas-Younger** [timoast/signac#243]
Hey, thanks for making such an awesome set of tools and providing such detailed feedback to other people's issues - huge help!

I'm a little confused about when I need to do normalization and on what assays when merging and integrating. Ultimately I'm looking to merge multiple scATAC-seq datasets from the same tissue, integrate them using Harmony to remove technical variation between datasets, and then transfer labels to the integrated object from matched scRNA-seq. I have managed to do this, however I'm not sure if I've done so correctly. **My question is: at what point(s) do I need to normalise the ATAC assay, and at what point(s) do I need to make and normalise a gene activity assay for the best anchor identification and transfer?**

What I'm currently doing is LSI normalisation on each sample before merging, then again on the merged object, and again after Harmony. 

In parallel with this I'm making and normalising gene activity assays for each sample at the start prior to merging, but then not doing anything else with them until I use them for finding transfer anchors - do I need to re-make/normalise the gene activity assay again after merging and after Harmony?   

n.b. I'm merging by reducing all peaks across samples with `GenomicRanges::reduce()` then using Harmony, as opposed to finding a downsampled common peak set and using `IntegrateData()`. My tissue is dominated by a single cell type and I find the latter approach results in loss of rarer cell types. 

What I get out the other end does look sensible, however I can get similar looking results using different variations on this workflow and I wanted to find out the correct way of doing this. 

Thank you for your help. I can provide a full script for clarity if needed, but it's a bit long to attach here.

**Comment by timoast** [comment]
> What I'm currently doing is LSI normalisation on each sample before merging, then again on the merged object, and again after Harmony.

You will need to run `RunTFIDF()`either before or after merging datasets. Unlike scRNA-seq normalization (`Seurat::NormalizeData()`), these values are dependent on the set of cells included, and so will change depending on if you run before or after merging the objects.

Harmony corrects the low-dimensional cell embeddings so will have no effect on the TF-IDF values.

> do I need to re-make/normalise the gene activity assay again after merging and after Harmony?

No, adding/removing cells will not affect the RNA normalization in this case as each cell is independent (`log((counts / total_counts * scale_factor) + 1)`). Running Harmony will also have no effect on the normalization

**Comment by Nicholas-Younger** [comment]
Hi Tim, 

Thanks for clearing that up, that makes sense.
