### ISSUE TITLE
predicted id vs assigned cell type difference

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#245]
Trying to understand why the UMAP plot obtained after integration(with scRNAseq) 
DimPlot(object, group.by = 'predicted.id') 
is different  from  running DimPlot(object) subsequent to running the re- id cells script

for(i in levels(object)) {
  cells_to_reid <- WhichCells(object, idents = i)
  newid <- names(sort(table(object$celltype[cells_to_reid]),decreasing=TRUE))[1]
  Idents(object, cells = cells_to_reid) <- newid
}
object$assigned_celltype <- Idents(object)

Is the assigned cell type essentially different from the predicted id.

Also what does [1] mean when we re-id cells?

**Comment by timoast** [comment]
This step assigns each cluster to the most common predicted cell type. `[1]` indexes the vector returned by `names(sort(..`, taking the first element (most common cell type)

This step is optional

**Comment by sylestiel** [comment]
Thank you!
