### ISSUE TITLE
The screening criteria of Nucleosome_signal 

### ISSUE THREAD

**Issue by Ariel-TC** [timoast/signac#248]
Hello, I'm using 'Signac' for scATAC-Seq data analysis and i wondered why we should filter nucleosome signal upper than four? I had look up many papers but i still have no idea for the reason. Or maybe it just match the fragments size distribution condition? Does that mean that I could change the standard number which suit my own data?
So sorry to bother you.

Best,
Ariel.
![image](https://user-images.githubusercontent.com/65101587/93653624-4e84b580-fa4c-11ea-8c79-ce58d3fc3b23.png)

**Comment by timoast** [comment]
The idea is to remove cells that are outliers for this metric. You should change the cutoff used to suit your data

**Comment by Ariel-TC** [comment]
Thank you very much！
