### ISSUE TITLE
Geneactivity() alternative

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#250]
Hi  timoast

It is now known that geneactivity() will generate a matrix on merged object of all zeros, which is a bug.
I would like to know if there are any alternatives at present.

Thanks.

**Comment by timoast** [comment]
As explained in the original issue for this bug (#205), this is fixed on the develop branch. See the website for instructions on installing from the develop branch: https://satijalab.org/signac/articles/install.html#development-version-1
