### ISSUE TITLE
CCA in Transfer Data

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#252]
Hi Tim,

When applying the TransferData function the filtering function results in a substantial reduction of anchors from 26K to 1K approximately.
How may I tweak the parameters so as to increase the number of retained anchors with a view to getting better resolution of clusters.

Also if I would like to write out the list of transfer anchors per cluster how would I do so.

**Comment by timoast** [comment]
Changing `k.filter` will affect the number of anchors filtered (see the documentation for FindTransferAnchors). Note that retaining more anchors will not necessarily give better results or "better resolution". See the paper for more information about the data transfer method: https://doi.org/10.1016/j.cell.2019.05.031

> Also if I would like to write out the list of transfer anchors per cluster how would I do so.

You can extract the list of anchors from the `AnchorSet` object returned by `FindTransferAnchors()`. The cell indices of the anchor pairs is stored in the `anchors` slot. Seurat does not currently have functions to, for example, automatically extract the anchors for cells in a given cluster, but you can extract the cluster membership information for each cell from the metadata (accessible via `object[[]]`).
