### ISSUE TITLE
Analyze the merged objects with the standard analysis process.

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#253]
Hi timoast

When I merge the two objects with the standard analysis process and execute the standard analysis process, I get an error when executing `thym_merging[['peaks']]`. It will show that Cannot find'peaks' in this Seurat object.

What am I missing?

**Comment by timoast** [comment]
Please include the code you're running

**Comment by Ping-lin14** [comment]
Here it is
`gr <- GRanges(seqnames = "chr1", ranges = IRanges(start = c(20, 70, 300), end = c(120, 200, 400)))
gr

##Creating a common peak set
library(Signac)
library(Seurat)
library(GenomicRanges)
library(future)

plan("multiprocess", workers = 4)
options(future.globals.maxSize = 50000 * 1024^2) # for 50 Gb RAM

# read in peak sets
peaks_n <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_N/peaks.bed",
  col.names = c("chr", "start", "end")
)

peaks_t <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_T/peaks.bed",
  col.names = c("chr", "start", "end")
)

# convert to genomic ranges
gr.thym_n <- makeGRangesFromDataFrame(peaks_n)
gr.thym_t <- makeGRangesFromDataFrame(peaks_t)

# Create a unified set of peaks to quantify in each dataset
combined.peaks <- reduce(x = c(gr.thym_n,gr.thym_t))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks

##Create Fragment objects
# load metadata
md.thym_n <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_N/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

md.thym_t <- read.table(
  file = "C:/Users/Jacky/Desktop/ATCT/s3234_T/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.thym_n <- md.thym_n[md.thym_n$passed_filters > 500, ]
md.thym_t <- md.thym_t[md.thym_t$passed_filters > 500, ]

# create fragment objects
frags.n <- CreateFragmentObject(
  path = "C:/Users/Jacky/Desktop/ATCT/s3234_N/fragments.tsv.gz",
  cells = rownames(md.thym_n)
)

frags.t <- CreateFragmentObject(
  path = "C:/Users/Jacky/Desktop/ATCT/s3234_T/fragments.tsv.gz",
  cells = rownames(md.thym_t)
)

##Quantify peaks in each dataset
thym_n.counts <- FeatureMatrix(
  fragments = frags.n,
  features = combined.peaks,
  cells = rownames(md.thym_n)
)

thym_t.counts <- FeatureMatrix(
  fragments = frags.t,
  features = combined.peaks,
  cells = rownames(md.thym_t)
)

thym_n_assay <- CreateChromatinAssay(thym_n.counts, fragments = frags.n)
normal <- CreateSeuratObject(thym_n_assay, assay = "ATAC" , meta.data = md.thym_n)

thym_t_assay <- CreateChromatinAssay(thym_t.counts, fragments = frags.t)
tumor <- CreateSeuratObject(thym_t_assay, assay = "ATAC" , meta.data = md.thym_t)


##Merge objects
normal$dataset <- 'normal'
tumor$dataset <- 'tumor'

thym_merging <- merge(
  x = normal,
  y = list(tumor),
  add.cell.ids = c("N", "T")
)
thym_merging[["ATAC"]]

thym_merging <- RunTFIDF(thym_merging)
thym_merging <- FindTopFeatures(thym_merging, min.cutoff = 20)
thym_merging <- RunSVD(thym_merging)
thym_merging <- RunUMAP(thym_merging, dims = 2:50, reduction = 'lsi')

DimPlot(thym_merging, group.by = 'dataset', pt.size = 0.1)

CoveragePlot(
  object = thym_merging,
  group.by = 'dataset',
  region = "chr14-99700000-99760000"
)



thym_merging [[ 'peaks' ]]#error:Cannot find'peaks' in this Seurat object.


#combined[['peaks']]
granges(thym_merging)
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)

# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "hg19"

# add the gene information to the object
Annotation(thym_merging) <- annotations

# compute nucleosome signal score per cell
thym_merging <- NucleosomeSignal(object = thym_merging)

# compute TSS enrichment score per cell
thym_merging <- TSSEnrichment(object = thym_merging, fast = FALSE)

# add blacklist ratio and fraction of reads in peaks
thym_merging$pct_reads_in_peaks <- thym_merging$peak_region_fragments / thym_merging$passed_filters * 100
thym_merging$blacklist_ratio <- thym_merging$blacklist_region_fragments / thym_merging$peak_region_fragments

thym_merging$high.tss <- ifelse(thym_merging$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(thym_merging, group.by = 'high.tss') + NoLegend()

thym_merging$nucleosome_group <- ifelse(thym_merging$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram(object = thym_merging, group.by = 'nucleosome_group')

VlnPlot(
  object = thym_merging,
  features = c('pct_reads_in_peaks', 'peak_region_fragments',
               'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal'),
  pt.size = 0.1,
  ncol = 5
)

thym_merging <- subset(
  x = thym_merging,
  subset = peak_region_fragments > 3000 &
    peak_region_fragments < 20000 &
    pct_reads_in_peaks > 15 &
    blacklist_ratio < 0.05 &
    nucleosome_signal < 4 &
    TSS.enrichment > 2
)

thym_merging

thym_merging <- RunTFIDF(thym_merging)
thym_merging <- FindTopFeatures(thym_merging, min.cutoff = 'q0')
thym_merging <- RunSVD(thym_merging)

DepthCor(thym_merging)

thym_merging <- RunUMAP(object = thym_merging, reduction = 'lsi', dims = 2:50)
thym_merging <- FindNeighbors(object = thym_merging, reduction = 'lsi', dims = 2:50)
thym_merging <- FindClusters(object = thym_merging, verbose = FALSE, algorithm = 3)
DimPlot(object = thym_merging, label = TRUE) + NoLegend()

gene.activities <- GeneActivity(thym_merging)

# add the gene activity matrix to the Seurat object as a new assay and normalize it
thym_merging[['RNA']] <- CreateAssayObject(counts = gene.activities)
thym_merging <- NormalizeData(
  object = thym_merging,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(thym_merging$nCount_RNA)
)

DefaultAssay(thym_merging) <- 'RNA'

FeaturePlot(
  object = thym_merging,
  features = c('SLC7A5', 'FBLN2', 'LIPE', 'ABCA10', 'DGAT2', 'SLC16A7','SELENBP1','KLF4'),
  pt.size = 0.1,
  max.cutoff = 'q95',
  ncol = 3
)

`

**Comment by timoast** [comment]
You named the assay "ATAC" not "peaks"
