### ISSUE TITLE
Error in smooth.spline(lambda, pi0, df = smooth.df) :

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#254]
> enriched.motifs <- FindMotifs(
+   object = SH2,
+   features = top.da.peak
+ )
Selecting background regions to match input
              sequence characteristics
Matching GC.percent distribution
Testing motif enrichment in 224 regions
Error in smooth.spline(lambda, pi0, df = smooth.df) : 
  missing or infinite values in inputs are not allowed

**Comment by timoast** [comment]
See #223 

Please search previous issues before opening a new issue

**Comment by sylestiel** [comment]
Can you provide a link to a clean version of the script. Don't understand the layout. Thanks!

**Comment by timoast** [comment]
I'm not sure what you mean, but this bug is fixed on the develop branch. See the website for instructions on installing from the develop branch: https://satijalab.org/signac/articles/install.html#development-version-1
