### ISSUE TITLE
Issues running motif analysis with Signac

### ISSUE THREAD

**Issue by shabs24** [timoast/signac#256]
I run into this error when I try yo extract pfms

pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE)
)

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'getMatrixSet' for signature '"JASPAR2020”'

I installed JASPAR2020  using the command below 
remotes::install_github("da-bar/JASPAR2020”)

I have loaded both the libraries without any errors
library(JASPAR2020)
library(TFBSTools)

I have seen the post regarding this error but not sure if it has been resolved. 

Any suggestions?

**Comment by timoast** [comment]
You probably need to update `TFBSTools`. Try running `BiocManager::install(c("TFBSTools", "JASPAR2020"))`

**Comment by shabs24** [comment]
I get the following message while trying to install “JASPAR2020” with BiocManager 
Warning message:
package 'JASPAR2020' is not available (for R version 3.6.3)

**Comment by shabs24** [comment]
I get the following message while trying to install “JASPAR2020” with BiocManager 
Warning message:
package 'JASPAR2020' is not available (for R version 3.6.3)

**Comment by timoast** [comment]
Then you need to update bioconductor: `BiocManager::install(version = "3.11")`

**Comment by timoast** [comment]
You'll also need to update R as bioconductor depends on R >=4.0.0

**Comment by shabs24** [comment]
Thanks! it resolved the issue.
