### ISSUE TITLE
Aesthetics of Coverage Plots and Tile Plots

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#257]
Hi Tim,

 How can I change the **color** of the tile plot and the **text size** of the composite Coverage Plot?

Thank you!!

**Comment by timoast** [comment]
These are standard `ggplot` objects, so you can adjust the plot style using `ggplot2` functions (see https://ggplot2.tidyverse.org/reference/index.html)

For example, to change the color scale of the tile plot:

```r
library(Signac)
library(ggplot2)

region.use <- LookupGeneCoords(obj, gene = "CD8A")
tile <- TilePlot(object = obj, region = region.use, group.by = "orig.ident")
tile + scale_fill_continuous(type = "viridis")
```

<img width="746" alt="Screen Shot 2020-09-24 at 3 56 46 pm" src="https://user-images.githubusercontent.com/4591688/94193615-8e013680-fe7e-11ea-9aea-21a79f4e65d6.png">
