### ISSUE TITLE
motif_analysis

### ISSUE THREAD

**Issue by lyuguol** [timoast/signac#258]
In the vignette "Motif analysis with Signac", you set 
"pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE)"

Should 'species = 9606' be 'species = 10090' since you are analyzing a mouse data set?

Thank you very much.

All the best,
Guoliang

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/58#issuecomment-571183108

**Comment by A-legac45** [comment]
Hello, I am having this error message do you now why   
I am working on mice.

pfm <- getMatrixSet(
+   x = JASPAR2020,
+   opts = list(species = '10090', all_versions = FALSE)
+ )


test_motif <- AddMotifs(
+   object = test_p,
+   genome = BSgenome.Mmusculus.UCSC.mm10,
+   pfm = pfm, assay = "PEAKS"
+ )
Building motif matrix
Finding motif positions
Creating Motif object
Warning: Features do not match in ChromatinAssay and Motif object.
                Subsetting the Motif object.

best regards
