### ISSUE TITLE
reopening thread re FindMotifs

### ISSUE THREAD

**Issue by justin-malin** [timoast/signac#259]
Hi, 
I'm reopening this thread because after I created a chromatinAssay, which solves the problem described above, I'm getting an error in FindMotifs. It's not clear what the cause is.  Any ideas?
Thanks,
Justin

```
> coords <- read.table(path.to.bed)
> 
> ranges <- paste0(coords$V1, '-', coords$V2, '-', coords$V3)
> 
> fragments <- CreateFragmentObject(prefixed.fragments.path)
Computing hash
> 
> featurematrix <- FeatureMatrix(
+   fragments = fragments,
+   features = StringToGRanges(ranges, sep=c('-', '-')),
+   sep = c('-', '-')
+ )
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=38s
>
> chromatinassay <- CreateChromatinAssay(counts = featurematrix, genome = "mm10")
> new.object <- CreateSeuratObject(counts = chromatinassay, assay='peaks')
>
> new.object <- subset(new.object, cells = colnames(new.object)[colnames(new.object) %in% colnames(pbmc.1)])
> 
> DefaultAssay(new.object) <- 'peaks'
> new.object <- RunTFIDF(object = new.object, assay = 'peaks')
Performing TF-IDF normalization
> 
> motif.mtrx <- CreateMotifMatrix(features = StringToGRanges(rownames(new.object), sep = c("-", "-")), pwm = pfm, genome = 'mm10',  use.counts = FALSE)
> 
> motif <- CreateMotifObject(data = motif.mtrx, pwm = pfm)
> 
> new.object <- SetAssayData(
+   object = new.object,
+   slot = 'motifs',
+   new.data = motif
+ )
> 
> enrchd.motifs <- FindMotifs(
+   object =  new.object,
+   features = rownames(new.object), 
+   sep = c('-', '-')
+ )
Selecting background regions to match input
              sequence characteristics
Matching GC.percent distribution
Error in density.default(x = mf.query[[i]], kernel = "gaussian", bw = 1) : 
  argument 'x' must be numeric
In addition: Warning message:
In MatchRegionStats(meta.feature = GetAssayData(object = object,  :
  Requested more features than present in supplied data.
            Returning 0 features
>
```

_Originally posted by @justin-malin in https://github.com/timoast/signac/issues/246#issuecomment-696944788_

**Comment by timoast** [comment]
Here you're using all peaks as the input to `FindMotifs()`, so it's not able to find a background set of peaks that's not used in the input. The purpose of `FindMotifs()` is to identify overrepresented motifs in a subset of peaks relative to a background set of peaks, so it's unclear what the motivation would be in supplying all peaks as the input to `FindMotifs()`

**Comment by justin-malin** [comment]
Ah. Here, I created a new chromatin object with a set of features that resulted from filtering out 10X peaks and *fractions* of 10X peaks that overlap exonic regions. This set of features, therefore, isn't a proper subset of the features in the original object, so I created a new object containing just the exon-filtered features.  I was trying to use FindMotifs the way one would use Homer, say, to find enriched motifs for a user-supplied bedfile of features, and let the software supply randomly chosen genomic sequences matched for length, GC content, etc, to serve as background...

If I understand you right, I should be able to find  enriched motifs with FindMotifs for the new object by inputting features for the background: eg, the set of features from the original object that were filtered out minus, of course, the features that partially overlap the new features. Given that I no longer have the original object, is there a  workaround you could suggest that works without a user-supplied background?
Thanks,
Justin

**Comment by timoast** [comment]
Right, the `FindMotifs()` function does not do _de novo_ motif finding and requires a set of background peaks. The background peaks can be selected from peaks in the object automatically, or they can be manually supplied using the `background` parameter. To be honest I don't think there's a workaround for this case, as it's not really what the function was designed for. I'd suggest using the original object (not the filtered object) and choosing a set of peaks from the main object to perform motif enrichment tests on.

**Comment by justin-malin** [comment]
Got it. 
Thank you so much for all your help!
