### ISSUE TITLE
NucleosomalSignal to extract reads in requested region

### ISSUE THREAD

**Issue by siyunw** [timoast/signac#26]
Hi I am merging the two object with MergeWithRegions,
and get this error:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]) : 
  some values in the "end" column cannot be turned into numeric values
In addition: Warning message:
Expected 3 pieces. Missing pieces filled with `NA` in 218594 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]. 
How could I fix this? Thank you!

**Comment by siyunw** [comment]
Sorry get through this step, could you please me know how the "total" can be found? I am comparing wt vs mutant in one file using chromium aggregation?

~~~~~~~~~~~~~~~
pct_reads_in_peaks <- peak_region_fragments / total * 100
Error in `[[.Seurat`(x, i, drop = TRUE) : 
  Cannot find 'total' in this Seurat object
~~~~~~~~~~~~

**Comment by timoast** [comment]
Hi, the column ‘total’ is from the cellranger metadata (see #4)

For your first question, can you post the full code you’re using?

**Comment by JBreunig** [comment]
Just to chime in because I had the same problem, "total" is not generated when an aggregated output of two samples is generated in CellRanger.  Is there any other way to calculate it?

**Comment by siyunw** [comment]
@timoast  Thanks for posting the method described in the #14 and I ended up merging the two objects and it worked. Please see below for the full code. So I merged the two seurat objects by replacing the barcode of one object and re-indexing the multiple merged fragment file, example full code shown below:
lattee<-MergeWithRegions(
  object.1 = coffee,
  object.2 = milk,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)
 wondering if there are differences between this two approaches, i.e compare subsample and aggregate, or first merge and then normalize. came across this post https://bioinformatics.stackexchange.com/questions/2356/cellranger-aggr-and-seurat-merge-difference
@JBreunig re the 'total' problem I haven't figure out how to generate the total columns in the aggregate file so that the format looks like the single 10x each single file?

**Comment by timoast** [comment]
@JBreunig I will work on adding a function for this in the future. A workaround right now would be to generate a genome bin matrix using the [`GenomeBinMatrix`](https://satijalab.org/signac/reference/GenomeBinMatrix.html) function and look at the `colSums` of that matrix to get the approximate total fragments per cell. 

@siyunw I haven't compared aggregate vs merge systematically, but I think the simplest thing to do if you have samples that can be aggregated with cellranger is to aggregate
