### ISSUE TITLE
AlleleFreq

### ISSUE THREAD

**Issue by cnk113** [timoast/signac#260]
When using difference thresholds for my high confidence variants I ran into this issue when try to compute AlleleFreq.
```r
Error in apply(X = matrix_positions, MARGIN = 1, FUN = function(x) { : 
  dim(X) must have a positive length
In addition: Warning message:
In split.default(x = idx_denom, f = rep(1:8, each = length(x = variants))) :
  data length is not a multiple of split variable
```

**Comment by timoast** [comment]
Hi, could you please include the full code you're running?

**Comment by cnk113** [comment]
Sorry for the late follow up, but I'm just following the tutorial with my own data.
Pretty much relax the threshold for high conf variants where it resulted ~25 variants.
It works if it's under ~21 high conf variants.
```
crc <- AlleleFreq(
  object = crc,
  variants = high.conf$variant,
  assay = "mito"
)
```

**Comment by timoast** [comment]
Should be fixed now on the develop branch. See [here](https://satijalab.org/signac/articles/install.html#development-version-1) for installation instructions
