### ISSUE TITLE
Help with generating a given heatmap plot

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#264]
Hi Tim,

 Can you provide a script to generate a heatmap as shown in the attached (Obtained from a paper).

Thanks!

<img width="422" alt="Screen Shot 2020-10-02 at 10 26 54 AM" src="https://user-images.githubusercontent.com/64283689/94955198-d2f52080-04af-11eb-88be-fe0dcc938ac6.png">

**Comment by timoast** [comment]
It looks like this is maybe chromvar plot showing the averaged chromvar deviations per group of cells? You should be able to recreate something similar using the `AverageExpression()` and `DoHeatmap()` functions in Seurat. For example:

1. Average chromvar values within each group of cells using `AverageExpression` with `slot="data"` and `return.seurat=TRUE`
2. Create heatmap using the object output by `AverageExpression`, eg `DoHeatmap(object = obj, features = features, slot = "data")`

**Comment by drosop** [comment]
Hi, I am trying to make a similar plot. However, when I am trying to run AverageExpression() on chromvar assay of signac object, it gives me this error

combined.msobj.av <- AverageExpression(
   object = combined.msobj,
   assay = "chromvar",
   return.seurat = TRUE,
   slot = "data"
 )

Error in if (any(data.use == Inf)) { : 
  missing value where TRUE/FALSE needed

Can you please help? And chromvar output values are already z scores, so do why we need to do AverageExpression() before doheatmap or dotplot? 

Thank you

**Comment by yojetsharma** [comment]
> It looks like this is maybe chromvar plot showing the averaged chromvar deviations per group of cells? You should be able to recreate something similar using the `AverageExpression()` and `DoHeatmap()` functions in Seurat. For example:
> 
> 1. Average chromvar values within each group of cells using `AverageExpression` with `slot="data"` and `return.seurat=TRUE`
> 2. Create heatmap using the object output by `AverageExpression`, eg `DoHeatmap(object = obj, features = features, slot = "data")`

(Apologies, I know this issue belongs to seurat, but since you replied here, I thought of following it up here) 
I did the following:
```
> agg<-AggregateExpression(seurat, assay = "chromvar", return.seurat = TRUE,slot="data")
Warning: Data is of class dgeMatrix. Coercing to dgCMatrix.
  |==========================================================================================================| 100%
Centering and scaling data matrix
  |==========================================================================================================| 100%
> DoHeatmap(object = seurat, features = features, slot = "data")
Error in features %||% VariableFeatures(object = object) : 
  object 'features' not found
```
