### ISSUE TITLE
Loading Barcodes.tsv, matrix.mtx and peaks.bed files into Signac.

### ISSUE THREAD

**Issue by Dragonmasterx87** [timoast/signac#265]
Hi All!

I apologize for the stupid questions just new to ATAC. So How can I load the output of my "ATAC_filtered_peak_bc_matrix" folder (created from `cellranger-atac count`) into Signac/seurat? Based on the vignette I need the following:

atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5
atac_v1_pbmc_10k_fragments.tsv.gz

But have the following:

barcodes.tsv
matrix.mtx
peaks.bed

Thanks a LOT!!

Cheers,
Fahd

**Comment by timoast** [comment]
You can use the `Seurat::Read10X()` function

**Comment by Dragonmasterx87** [comment]
Wait......for signac? read10x?.....

**Comment by timoast** [comment]
Right, the `Seurat::Read10X` function will return a matrix that can be used to create the assay object

**Comment by Dragonmasterx87** [comment]
Thanks mn youre the best.

**Comment by Garrobocel** [comment]
What is the code use Read10x to load: 
barcodes.tsv
matrix.mtx
peaks.bed

The function requests features.tsv.gz, which is for scRNAseq.
