### ISSUE TITLE
About the problems encountered in the implementation of Transcription factor footprinting

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#266]
Hi timoast

When I follow the standard process to execute the transcription factor footprinting, I encountered two problems: 
1. When executing `FindClusters`, a Warning message appears: UNRELIABLE VALUE: Future ('future_lapply-1') unexpectedly generated random numbers without specifying argument'[future.] seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument'[future.]seed', eg'seed=TRUE'. This ensures that proper, parallel -safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option'future.rng.onMisuse' to "ignore". 

Should I ignore him? Or how to solve it?

2. When I execute `motif.positions <- matchMotifs(
 pwms = pwm,
 subject = granges(thym_merging),
 out = 'positions',
 genome = 'hg19'
)`
There will be Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence "chr3"

 How to solve it?

**Comment by timoast** [comment]
Neither of these functions are part of the Signac package but I will try to answer anyway:

1. This can be ignored
2. This seems to indicate that there are genomic ranges in `granges(thym_merging)` that extend past the end of chromosome 3 in hg19. Are you sure that your data was mapped to hg19?

**Comment by Ping-lin14** [comment]
Regarding the second point, I am sure that my data is mapped to hg19.
`ChromatinAssay data with 199161 features for 17696 cells
Variable features: 0 
Genome: hg19 
Annotation present: FALSE 
Motifs present: FALSE 
Fragment files: 2 `

I will consult the developer of the package again.
Thank you, timoast!
