### ISSUE TITLE
The choice of peak file as well as peakwidth

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#267]
<img width="711" alt="Screen Shot 2020-10-06 at 11 02 46 AM" src="https://user-images.githubusercontent.com/64283689/95227294-8f5a2980-07c3-11eb-805b-c7862b8352a7.png">

Hi,

What peaks files should we be entering in the merged analysis? Within cellranger outs folder there is peaks.bed and a subfolder with peaks.bed.  Does it matter which one is used?

Also for the combined peaks peakwidths <- 10000 & peakwidth >20 
Why is the lower limit 20 and not 200?

Thanks!

**Comment by timoast** [comment]
> What peaks files should we be entering in the merged analysis? Within cellranger outs folder there is peaks.bed and a subfolder with peaks.bed. Does it matter which one is used?

If you look at these files I think you'll find they are the same

> Also for the combined peaks peakwidths <- 10000 & peakwidth >20
Why is the lower limit 20 and not 200?

Why would it be 200? Is there some other information you're referring to?

**Comment by sylestiel** [comment]
I thought for ATAC purposes we typically look at peak width of 200?
Is that not the norm?

**Comment by timoast** [comment]
No
