### ISSUE TITLE
'x' contains missing values---FindMotifs

### ISSUE THREAD

**Issue by QiFurong** [timoast/signac#27]
Hi, dears
I encountered an error while executing the FindMotifs command. 
```
enriched.motifs <- FindMotifs(object = pbmc,features = head(rownames(da_peaks), 1000))
Selecting background regions to match input sequence characteristics
Matching GC.percent distribution
Error in density.default(x = mf.query[[i]], kernel = "gaussian", bw = 1) :
  'x' contains missing values
```

How to fix this issue?

Best,
Furong

**Comment by QiFurong** [comment]
I have fixed it. Thanks

**Comment by yiluheihei** [comment]
@QiFurong  Could you share your solution? Thanks

**Comment by hahia** [comment]
> I have fixed it. Thanks

Could you share your solution? I also have this problem. Thank you for your reply
