### ISSUE TITLE
Identity specification in differentially accessible peak step prior to motif enrichment

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#270]
Hi,
If I'm interested in getting 'dataset' specific motif enrichment in the merged analysis (object=combined) how do I specify identity 1 and identity2 in the following step:

da_peaks <- FindMarkers(
  object = combined,
  ident.1 = "?",
  ident.2 = "?",
  only.pos = TRUE,
  test.use = 'LR',
  latent.vars = 'nCount_peaks'
)

# get top differentially accessible peaks
top.da.peak <- rownames(da_peaks[da_peaks$p_val < 0.005, ])

Thanks!

**Comment by timoast** [comment]
See the Seurat immune alignment vignette: https://satijalab.org/seurat/v3.2/immune_alignment.html

Including the most relevant code section here:

```r
immune.combined$celltype.stim <- paste(Idents(immune.combined), immune.combined$stim, sep = "_")
immune.combined$celltype <- Idents(immune.combined)
Idents(immune.combined) <- "celltype.stim"
b.interferon.response <- FindMarkers(immune.combined, ident.1 = "B_STIM", ident.2 = "B_CTRL", verbose = FALSE)
```

**Comment by sylestiel** [comment]
Sorry to press the matter. But does your suggestion apply to ATAC analysis where we are working with a common peak set?

**Comment by timoast** [comment]
Yes
