### ISSUE TITLE
Order of operations when comparing scATAC datasets

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#272]
Hi,

Having generated a **Unified set of peaks** by calling the **reduce** function I have  a **combined** dataset. Now to run the **FindMarkers** function do I need to run the findOverlaps outlined in the Integration of scATAC datasets vignette before FindMarkers?

**Comment by timoast** [comment]
If you have followed the [merge vignette](https://satijalab.org/signac/articles/merging.html), you will have quantified the same set of features across the different datasets. There is no need to run `findOverlaps()`
