### ISSUE TITLE
error in peak_region_fragments

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#273]
I am not sure why I am getting the following error?

```
# add blacklist ratio and fraction of reads in peaks
ATAC$pct_reads_in_peaks <- ATAC$peak_region_fragments/ ATAC$passed_filters * 100
ATAC$blacklist_ratio <- ATAC$blacklist_region_fragments / ATAC$A
```

```

Error: Cannot find 'peak_region_fragments' in this Seurat object
Traceback:

1. ATAC$peak_region_fragments
2. `$.Seurat`(ATAC, peak_region_fragments)
3. x[[i, drop = TRUE]]
4. `[[.Seurat`(x, i, drop = TRUE)
5. stop("Cannot find '", i, "' in this Seurat object", call. = FALSE)
```
running 

```
# compute nucleosome signal score per cell
ATAC <- NucleosomeSignal(object = ATAC)

ATAC <- TSSEnrichment(object = ATAC, fast = FALSE)
```

did not give any error

**Comment by timoast** [comment]
`peak_region_fragments` is metadata generated by cellranger-atac. Did you add the cellranger-atac metadata to the object?

**Comment by rojinsafavi** [comment]
Could you point me to where that information is added? I followed the merging tutorial, and I can see that "md.*" contains that information. but for some reasons I am not seen that added to the combined object

**Comment by rojinsafavi** [comment]
I think the md.* need sto be added to each seuratobject, testing it that right now and will let you know.

**Comment by rojinsafavi** [comment]
So I think that was the problem, my combined dataset now has that meta information. In the tutorial that information needs to be added, and may confuse people :-) thanks again!

**Comment by beginner984** [comment]
> `peak_region_fragments` is metadata generated by cellranger-atac. Did you add the cellranger-atac metadata to the object?

Hello

Hello

I have Chromium Single Cell Multiome ATAC + Gene Expression sequencing data by Cell Ranger ARC, but in output of Cell Ranger I am not seeing any `peak_region_fragments` or blacklist regions. How I can generate this from my data because I want to run https://satijalab.org/signac/articles/pbmc_vignette.html tutorial on my data

Thanks for any help

**Comment by tilofreiwald** [comment]
@beginner984 for the multiome kit the metadata can be found in the cellranger-arc output: `outs/per_barcode_metrics.csv`

(see also: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/output/per_barcode_metrics)

**Comment by ncborcherding** [comment]
For anyone having this issue using **cellranger-atac-2.0.0** - meta data is now labeled as summary.csv

**Comment by Jokendo-collab** [comment]
> So I think that was the problem, my combined dataset now has that meta information. In the tutorial that information needs to be added, and may confuse people :-) thanks again!

Could you post the line of code you used to solve the problem? I could not get around it.
