### ISSUE TITLE
Signac：the altered cells cannot map to fragments

### ISSUE THREAD

**Issue by coffeeCowLu** [timoast/signac#274]
When I merge multiple data (sample1 sample2), I append the cell name (use ad.cell.id) for cell repetition.
But then when I create the RNA data,
PBMC [['RNA']] <- CreateAssayObject(counts = Gene.Activities),
In Seurat Object, the altered cells cannot map to fragments, and nfeature_RNA is 0.
Without changing the cell name, it can be mapped to the data, but the cell name will be repeated when multiple sample data are combined.

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/205
