### ISSUE TITLE
merging and integration 

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#276]
Hi,

 With regard to scATAC_If I'm working with 2 samples per age (4 samples in all) should I first merge the two samples for each age and then proceed with integration? 

Also if there are big differences in cell numbers per sample what cut offs can I apply?

Thanks,

**Comment by timoast** [comment]
> With regard to scATAC_If I'm working with 2 samples per age (4 samples in all) should I first merge the two samples for each age and then proceed with integration?

I would suggest following the merge vignette (https://satijalab.org/signac/articles/merging.html) and seeing if there are batch effects that need to be removed. If so, you can use the integration methods demonstrated in the integration vignette

> Also if there are big differences in cell numbers per sample what cut offs can I apply?

Not sure what you're asking here

**Comment by sylestiel** [comment]
How does one look for batch effects?  

<img width="850" alt="Screen Shot 2020-10-13 at 9 34 55 AM" src="https://user-images.githubusercontent.com/64283689/95875417-9dfe8e80-0d37-11eb-95a9-e31789f725a9.png">
With respect to the second question if the peak counts are 165K, 166K for one age and 188K and 191K for the other how can one establish the lower threshold for filtering cells.

**Comment by timoast** [comment]
> How does one look for batch effects?

You can visually inspect the UMAP with cells colored by batch and see if there is batch-specific separation of what you believe are equivalent cell states across the batches, or you could compute batch mixing metrics like [kbet](https://github.com/theislab/kBET)

> With respect to the second question if the peak counts are 165K, 166K for one age and 188K and 191K for the other how can one establish the lower threshold for filtering cells.

The screenshot you attached is showing cell filtering based on total counts, so is not affected by the number of peaks called in each dataset. You will need to explore your own data and decide on cutoff values that make sense for your dataset
