### ISSUE TITLE
How to convert RangesSummarizedExperiment to dataframe or matrix

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#277]
<img width="542" alt="Screen Shot 2020-10-12 at 5 32 49 PM" src="https://user-images.githubusercontent.com/64283689/95795869-0c4c3e00-0cb1-11eb-9413-b618b006aa37.png">

Thanks!

**Comment by timoast** [comment]
This has nothing to do with Signac, I suggest asking on the bioconductor support forum
