### ISSUE TITLE
Issue for TSSenrichment

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#278]
Hi all,
      The monkey ATAC data.
     The tssenrichment showing different between the cellranger-atac and signac1.1.0,
      The picture showing below,
      Signac result,
![image](https://user-images.githubusercontent.com/41668708/95815498-64398200-0d4f-11eb-983b-c0c42a5b7b53.png)
      The cellranger-atac result,
       
![image](https://user-images.githubusercontent.com/41668708/95815534-787d7f00-0d4f-11eb-9c53-7e6b2b0303e6.png)
why this result so different ?
   any advice would be appreciated.

**Comment by timoast** [comment]
Are the gene annotations used in both cases the same?

**Comment by timoast** [comment]
You will need to find the correct set of annotations for your species. I suggest starting by searching the ensembl website: https://uswest.ensembl.org/index.html

**Comment by honghh2018** [comment]
Thank for the advice, But this was a large project for building the macaca monkey Ensembldb R package.

 I get another question with the error showing below.
 This issue show up because of the gtf file missing string 'chr' on the first column.
  So i hope can do TSSenrichment with without string 'chr', what parameter can be setted on TSSenrichment function?  
 > brain <- TSSEnrichment(brain, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
|--------------------------------------------------|
|==================================================|
Error in width(x = region)[[1]] : subscripts out of bounds
Thanks,
 Hope solved the problem with your help.

**Comment by timoast** [comment]
The annotations need to match the genome that the reads were mapped to, so if the genome names in the fragment file don't have "chr" prefix then you need to change the [`seqlevelsStyle`](https://www.rdocumentation.org/packages/ensembldb/versions/1.4.7/topics/seqlevelsStyle) of the annotations so that it matches the genome.
