### ISSUE TITLE
could not find function "SetFragments"

### ISSUE THREAD

**Issue by caochch** [timoast/signac#279]
After library(Signac) and running tests, the program reported that could not find function "SetFragments".

pbmc <- SetFragments(
  object = pbmc,
  file = fragment.path
)

The 'library' command could run successfully.
Donot know why this happened.

**Comment by timoast** [comment]
This was replaced with the `Fragments<-` assignment function in version 1.0.0. See [here](https://satijalab.org/signac/articles/data_structures.html#the-fragment-class-1) for more information
