### ISSUE TITLE
analysis

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#280]
I have 3 control and 3 treated smaples all merged into one signac object.

I have identified clusters. But now I would like to look at differential expression between the control and treated smaples in each cluster.

For example, I would like to compare the peask in the control smaples of cluster 1 to the treated samples in cluster 1 to see which peaks are significantly different.

Could you help me do this?

Thanks

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/270#issuecomment-705172533
