### ISSUE TITLE
CreateChromatinAssay() different number of features despite min.cells = 0 and identical "ranges =" argument 

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#282]
I am trying to integrate 5 snATAC datasets.  I created feature matrices in a common coordinate space by merging the rownames of each original ChromatinAssay.  Now I would like to add these matrices to my original seurat objects to use for integration.  I checked the nrow()'s of each feature matrix to make sure they were identical.  However, when I use CreateChromatinAssay() to add these feature matrices to my seurat object, the number of rows changes (Yes, I remembered to change DefaultAssay() ).  I have provided my code below, starting with the feature matrices.  I **bolded** my output where the error occurs.   NOTE: I am also experiencing the same issue as #268 and figured this may be part of the issue.

#Feature matrices
reduced.peak.assay1099 <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/frags1099.rds")
reduced.peak.assay1557 <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/frags1557.rds")
reduced.peak.assay542 <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/frags542.rds")
reduced.peak.assay347 <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/frags347.rds")
reduced.peak.assay357 <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/frags357.rds")

total.features <- c(nrow(reduced.peak.assay1099), 
                    nrow(reduced.peak.assay1557),
                    nrow(reduced.peak.assay347),
                    nrow(reduced.peak.assay357),
                    nrow(reduced.peak.assay542)
)
total.features
**[1] 233205 233205 233205 233205 233205**
#^above output looks good

.........................................................................

#Seurat objects with original assays 
atac1099  <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/atac1099.rds")
atac1557 <-  <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/atac1557.rds")
atac542  <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/atac542.rds")
atac347  <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/atac347.rds")
atac357  <- readRDS("C:/Users/danie/Desktop/Seurat Objects/snATAC seq Rough Draft/atac357.rds")
object.list <- list(atac1099, atac1557, atac542, atac347, atac357)
............................................................................

#Combined peaks from all objects
peak.list <- list(1,2,3,4,5)
names(peak.list) <- c("peaks1099", "peaks1557", "peaks542", "peaks347", "peaks357")
for (i in 1:5) {
  peak.list[[i]] <- StringToGRanges(rownames(object.list[[i]]), sep = c("-", "-"))
}
list2env(peak.list, envir = .GlobalEnv)
all.peaks<- c(peaks1099, peaks1557, peaks542, peaks347, peaks357)
reduced.peaks <- reduce(all.peaks, ignore.strand = TRUE)
peakwidths <- width(reduced.peaks)
reduced.peaks <- reduced.peaks[peakwidths < 10000 & peakwidths > 20]
length(reduced.peaks)
**233205**
#^looks good
............................................................................

#Adding assays to my original objects
reduced.peak.list <- list(reduced.peak.assay1099, reduced.peak.assay1557, reduced.peak.assay542, reduced.peak.assay347, reduced.peak.assay357)
**for (i in 1:length(object.list)) {
  object.list[[i]][["merged.peak.assay"]] <- CreateChromatinAssay(
    counts = reduced.peak.list[[i]],
    min.cells = 0,
    ranges = reduced.peaks,
    genome = 'hg38'
  )
  DefaultAssay(object.list[[i]]) <- "merged.peak.assay"
}**
rm(atac1099, atac1557, atac347, atac357, atac542)
list2env(object.list, envir = .GlobalEnv)

total.features2 <- c(nrow(atac1099),
                    nrow(atac1557),
                    nrow(atac347),
                    nrow(atac357),
                    nrow(atac542))
total.features2
**[1] 223650 232612 233132 233179 233106**
#^why are these numbers all different?

**Comment by danielcgingerich** [comment]
I think there is a bug with the "min.cells = " argument in CreateChromatinAssay()

**Comment by timoast** [comment]
Should be fixed on the develop branch
