### ISSUE TITLE
TSSEnrichment（) file path

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#284]
HI timoast

When I performed the calculation of the TSS enrichment score for each cell, an error occurred.
Error TabixFile: file(s) do not exist:
'C:\Users\Jacky\Desktop\ATCT\s3234_N\fragments.tsv.gz''C
:\Users\Jacky\Desktop\ATCT\s3234_N\fragments.tsv.gz .tbi'

How to change these file paths?

thank you

**Comment by timoast** [comment]
See #206
