### ISSUE TITLE
Error: Cannot find 'lsi' in this Seurat object

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#285]
Hi,

I first merged  2 samples per age separately. Then I tried to run findOverlaps  between to two merged datasets and generate a feature matrix. 
<img width="1010" alt="Screen Shot 2020-10-14 at 10 23 42 AM" src="https://user-images.githubusercontent.com/64283689/96010398-5d6e4600-0e07-11eb-8fc9-2908eebaade2.png">

> peaknames <- GRangesToString(grange = peaks.use)
> 
> P2[['P2Peaks']] <- CreateChromatinAssay(
+   counts <- GetAssayData(P2, assay = "ATAC", slot = "counts")[peaknames, ],
+   ranges = peaks.use,
+   genome = "mm10"
+ )
> # run TF-IDF for the new assay
> DefaultAssay(P2) <- "P2Peaks"
> P2 <- RunTFIDF(P2)
Performing TF-IDF normalization
> 
> unintegrated <- merge(P2, E16)
  |============================================================================================================================| 100%
Binding matrix rows
  |============================================================================================================================| 100%
Binding matrix rows
> DefaultAssay(unintegrated) <- "P2Peaks"
> unintegrated <- RunTFIDF(unintegrated)
Performing TF-IDF normalization
> unintegrated <- FindTopFeatures(unintegrated, min.cutoff = 50)
> unintegrated <- RunSVD(unintegrated)
Running SVD
Scaling cell embeddings
> unintegrated <- RunUMAP(unintegrated, reduction = 'lsi', dims = 2:30)
22:40:23 UMAP embedding parameters a = 0.9922 b = 1.112
22:40:23 Read 16978 rows and found 29 numeric columns
22:40:23 Using Annoy for neighbor search, n_neighbors = 30
22:40:23 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
22:40:25 Writing NN index file to temp file /var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T//RtmpIFSA4Y/filefd0a2fd8fab9
22:40:25 Searching Annoy index using 4 threads, search_k = 3000
22:40:27 Annoy recall = 100%
22:40:29 Commencing smooth kNN distance calibration using 4 threads
22:40:31 Initializing from normalized Laplacian + noise
22:40:31 Commencing optimization for 200 epochs, with 594590 positive edges
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
22:40:40 Optimization finished
> p1 <- DimPlot(unintegrated, group.by = 'stage', pt.size = 0.1) + ggplot2::ggtitle("Unintegrated")
> 
> # find integration anchors between 10x and sci-ATAC
> anchors <- FindIntegrationAnchors(
+   object.list = list(E16, P2),
+   anchor.features = rownames(E16),
+   assay = c('P2Peaks', 'P2Peaks'),
+   k.filter = NA
+ )
Scaling features for provided objects
UNRELIABLE VALUE: Future ('future_lapply-1') unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore".UNRELIABLE VALUE: Future ('future_lapply-2') unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore".Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 24440 anchors
UNRELIABLE VALUE: Future ('future_lapply-1') unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore".
> 
> # integrate data and create a new merged object
> integrated <- IntegrateData(
+   anchorset = anchors,
+   weight.reduction = P2[['lsi']],
+   dims = 2:30,
+   preserve.order = TRUE
+ )
  |============================================================================================================================| 100%
Binding matrix rows
  |============================================================================================================================| 100%
Binding matrix rows
Error: Cannot find 'lsi' in this Seurat object

**Comment by timoast** [comment]
Did you add a dimension reduction called "lsi" to the `P2` object?

**Comment by sylestiel** [comment]
I did this at the merging step
P2$stage <- 'P2ATAC'
P2.combined <- RunTFIDF(P2)
P2.combined <- FindTopFeatures(P2.combined, min.cutoff = 20)
P2.combined <- RunSVD(P2.combined)
P2.combined <- RunUMAP(P2.combined, dims = 2:30, reduction = 'lsi')

And this  subsequently
DefaultAssay(P2) <- "P2Peaks"
P2 <- RunTFIDF(P2)

This is how the script reads in the vignette and that is what I did. Am I supposed to specify

**Comment by timoast** [comment]
Here you ran LSI on an object called `P2.combined`, rather than on `P2`. If you want to weight anchors using neighborhoods defined by LSI in the query data when running integration, you need to run LSI on your query object first (in this case, `P2`)

**Comment by sylestiel** [comment]
Thanks!!!
