### ISSUE TITLE
CoveragePlot error when used with object containing chromvar assay

### ISSUE THREAD

**Issue by jogiles** [timoast/signac#286]
Hello!

(And sorry for putting this issue in the wrong place!)

When I use the CoveragePlot function with an object that contains a 'chromvar' assay, I receive an error, but not when I use an object that does not contain a chromvar assay.

CoveragePlot(
  object = so,
  region = "chr14-2366850-24681500",
  features = "GZMB",
  annotation = TRUE,
  peaks = TRUE,
  tile = TRUE
)

Error: Cannot find 'nCount_chromvar' in this Seurat object

This same code with an earlier version of the object -- without a chromvar assay -- works.

Thanks! Josephine

**Comment by timoast** [comment]
You need to change the default assay from "chromvar" to a `ChromatinAssay`.  You can do this using the `DefaultAssay()` function

**Comment by jogiles** [comment]
Silly mistake! That worked. Thank you.
