### ISSUE TITLE
How to add 10x feature_linkage.bedpe to Signac object 

### ISSUE THREAD

**Issue by jogiles** [timoast/signac#287]
Hello!

I have data from the 10x multiomic assay. I would like to add the feature_linkage.bedpe file that is output from the cellranger ARC pipeline to the Links in my Signac object. It looks like Links() requires a Granges object as input. Since the bedpe file is a 13 column file with 2 sets of locations, I am unsure how to format properly. I'm sorry if this is obvious!

Thank you so much for your help! Josephine

**Comment by timoast** [comment]
The Signac links need to be a GRanges object where the start and end coordinates give the positions of the linked DNA coordinates. I haven't looked at the cellranger-arc bedpe file, but you should be able to reformat it such that it fits the required format for Signac.

**Comment by jogiles** [comment]
I will try reformatting the coordinates. Is there any way to include "score" information -- numeric data that reflects strength of association? I'm not sure if there is a way to include this type of meta data in the granges object or whether it can then be aesthetically mapped by line thickness (or something else) in the coverage plot. Thank you!!!! (Signac is a fantastic package.)

**Comment by timoast** [comment]
Yes, you can add a metadata column to the granges called "score" and it will be mapped to the color of the arc

**Comment by jogiles** [comment]
Hi Tim!

I created a granges object and added it to the Links() assay, but get an error when I use CoveragePlot with links = TRUE.
Thank you for your help!!!

> so
An object of class Seurat 
145731 features across 31237 samples within 4 assays 
Active assay: ATAC (85470 features, 83936 variable features)
 3 other assays present: RNA, SCT, chromvar
 4 dimensional reductions calculated: pca, umap.rna, lsi, umap.atac
> Links(so)
GRanges object with 0 ranges and 0 metadata columns:
   seqnames    ranges strand
      <Rle> <IRanges>  <Rle>
  -------
  seqinfo: no sequences
> linksN2min
GRanges object with 4022 ranges and 1 metadata column:
         seqnames            ranges strand |     score
            <Rle>         <IRanges>  <Rle> | <numeric>
     [1]     chr1   8945877-8946729      * |  0.388425
     [2]     chr1   8945877-8970141      * |  0.432150
     [3]     chr1   8945877-9728764      * |  0.534250
     [4]     chr1   9680964-9728764      * |  0.428075
     [5]     chr1   8945877-9850539      * |  0.412350
     ...      ...               ...    ... .       ...
  [4018]    chr21 31133023-31359942      * |   0.28720
  [4019]    chr21 41767085-42653716      * |   0.28450
  [4020]    chr21 44654255-44919849      * |  -0.34070
  [4021]    chr21 44765542-44919849      * |  -0.37500
  [4022]    chr22 38985205-39077274      * |  -0.28015
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
> Links(so) <- linksN2min
> Links(so)
GRanges object with 4022 ranges and 1 metadata column:
         seqnames            ranges strand |     score
            <Rle>         <IRanges>  <Rle> | <numeric>
     [1]     chr1   8945877-8946729      * |  0.388425
     [2]     chr1   8945877-8970141      * |  0.432150
     [3]     chr1   8945877-9728764      * |  0.534250
     [4]     chr1   9680964-9728764      * |  0.428075
     [5]     chr1   8945877-9850539      * |  0.412350
     ...      ...               ...    ... .       ...
  [4018]    chr21 31133023-31359942      * |   0.28720
  [4019]    chr21 41767085-42653716      * |   0.28450
  [4020]    chr21 44654255-44919849      * |  -0.34070
  [4021]    chr21 44765542-44919849      * |  -0.37500
  [4022]    chr22 38985205-39077274      * |  -0.28015
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
> DefaultAssay(so) <- 'ATAC'
> cov_plot_noLinks <- CoveragePlot(
+   object = so,
+   region = "chr14-23670000-24700000",
+   annotation = TRUE,
+   peaks = TRUE,
+   links = FALSE,
+   tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.
> cov_plot_Wlinks <- CoveragePlot(
+   object = so,
+   region = "chr14-23670000-24700000",
+   annotation = TRUE,
+   peaks = TRUE,
+   links = TRUE,
+   tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.
Error in `$<-.data.frame`(`*tmp*`, "group", value = integer(0)) : 
  replacement has 0 rows, data has 30
>

**Comment by jogiles** [comment]
Hi Tim!

I created a granges object and added it to the Links() assay, but get an error when I use CoveragePlot with links = TRUE.
Thank you for your help!!!

DefaultAssay(so) <- 'ATAC'

Links(so) <- linksN2min
Links(so)
GRanges object with 4022 ranges and 1 metadata column:
         seqnames            ranges strand |     score
            <Rle>         <IRanges>  <Rle> | <numeric>
     [1]     chr1   8945877-8946729      * |  0.388425
     [2]     chr1   8945877-8970141      * |  0.432150
     [3]     chr1   8945877-9728764      * |  0.534250
     [4]     chr1   9680964-9728764      * |  0.428075
     [5]     chr1   8945877-9850539      * |  0.412350
     ...      ...               ...    ... .       ...
  [4018]    chr21 31133023-31359942      * |   0.28720
  [4019]    chr21 41767085-42653716      * |   0.28450
  [4020]    chr21 44654255-44919849      * |  -0.34070
  [4021]    chr21 44765542-44919849      * |  -0.37500
  [4022]    chr22 38985205-39077274      * |  -0.28015
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths

DefaultAssay(so) <- 'ATAC'
cov_plot_noLinks <- CoveragePlot(
	object = so,
	region = "chr14-23670000-24700000",
	annotation = TRUE,
	peaks = TRUE,
	links = FALSE,
	tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.


cov_plot_Wlinks <- CoveragePlot(
	object = so,
	region = "chr14-23670000-24700000",
	annotation = TRUE,
	peaks = TRUE,
	links = TRUE,
	tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.
Error in `$<-.data.frame`(`*tmp*`, "group", value = integer(0)) : 
  replacement has 0 rows, data has 30

**Comment by jogiles** [comment]
Hi Tim!

I created a granges object and added it to the Links() assay, but get an error when I use CoveragePlot with links = TRUE.
Thank you for your help!!!

```
DefaultAssay(so) <- 'ATAC'

Links(so) <- linksN2min
Links(so)
GRanges object with 4022 ranges and 1 metadata column:
         seqnames            ranges strand |     score
            <Rle>         <IRanges>  <Rle> | <numeric>
     [1]     chr1   8945877-8946729      * |  0.388425
     [2]     chr1   8945877-8970141      * |  0.432150
     [3]     chr1   8945877-9728764      * |  0.534250
     [4]     chr1   9680964-9728764      * |  0.428075
     [5]     chr1   8945877-9850539      * |  0.412350
     ...      ...               ...    ... .       ...
  [4018]    chr21 31133023-31359942      * |   0.28720
  [4019]    chr21 41767085-42653716      * |   0.28450
  [4020]    chr21 44654255-44919849      * |  -0.34070
  [4021]    chr21 44765542-44919849      * |  -0.37500
  [4022]    chr22 38985205-39077274      * |  -0.28015
  -------
  seqinfo: 24 sequences from an unspecified genome; no seqlengths
```
```
DefaultAssay(so) <- 'ATAC'
cov_plot_noLinks <- CoveragePlot(
	object = so,
	region = "chr14-23670000-24700000",
	annotation = TRUE,
	peaks = TRUE,
	links = FALSE,
	tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.


cov_plot_Wlinks <- CoveragePlot(
	object = so,
	region = "chr14-23670000-24700000",
	annotation = TRUE,
	peaks = TRUE,
	links = TRUE,
	tile = FALSE) 
Scale for 'y' is already present. Adding another scale for 'y', which will
replace the existing scale.
Error in `$<-.data.frame`(`*tmp*`, "group", value = integer(0)) : 
  replacement has 0 rows, data has 30
````

**Comment by jogiles** [comment]
An update!

The error is being caused by this line:

```
link.df$group <- as.factor(link.df$group)
```
 in the LinkPlot() function. 

If I remove it, it works perfectly. Then, I combined with the other plots generated separately.

I'm still not sure why this is necessary -- it's not finding a global variable?

**Comment by timoast** [comment]
That line has been removed on the develop branch, it was added originally to support the "groups" information in cicero but it's not needed. If you install from the develop branch you shouldn't have this error. Alternatively, you can add a "group" column to the link information (for example, `linksN2min$group <- 1`)
