### ISSUE TITLE
Obtaining Coverage Plots and running FindMarkers function subsequent to Integration 

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#288]
Hi Tim,

I know you have touched upon this numerous times in your previous posts. However, I'm still trying to wrap my head around it.

If i ran integration of scATAC datasets using the scATAC-seq data integration vignette and used the following

# find integration anchors between E16(2datasets merged) and P2(2datasets Merged)
anchors <- FindIntegrationAnchors(
  object.list = list(E16, P2),
  anchor.features = rownames(E16),
  assay = c('P2Peaks', 'P2Peaks'),
  k.filter = NA
)

Question 1:  How do I modify the Coverage Plot commands
CoveragePlot(
  object = integrated,
  group.by = 'age',
  region = "chr8-91698525-91901915",
  annotation = TRUE,
  tile.size = 400,
  tile = TRUE
)

Question 2) What am I doing wrong below:

integrated$dataset.stage <- paste(Idents(integrated), integrated$stage, sep = "_")
> integrated$dataset <- Idents(integrated)
> Idents(integrated) <- "dataset.stage"
> Markers <- FindMarkers(integrated, ident.1 = "E16ATAC", ident.2 = "P2ATAC", verbose = FALSE)

Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: E16ATAC

Thank you!

**Comment by timoast** [comment]
> Question 1: How do I modify the Coverage Plot commands

You do not need to modify the CoveragePlot function call, just make sure the active assay is the merged ChromatinAssay

> Question 2) What am I doing wrong below:

It's impossible to say without the full code you're running, but the error suggests that you don't have an identity called "E16ATAC" in the object
