### ISSUE TITLE
Changing color scheme (3 colors) when visualizing ChromVAR activity

### ISSUE THREAD

**Issue by ElenaTT** [timoast/signac#29]
Thanks a lot for developing the package! 

I am trying to visualize the motif activity from chromVAR with FeaturePlot using a red (high)-white (0)-blue (low) color scheme as in the last plot in: https://bioconductor.org/packages/release/bioc/vignettes/chromVAR/inst/doc/Introduction.html   but when I specify 3 colors, the plot appears with a very different scale (removing values below 1). 
How can I keep the full scale but specify 3 colors? 

Many thanks, 

Elena

**Comment by timoast** [comment]
Hi Elena, you can set a custom color scale using `scale_color_gradientn()` from `ggplot2`. For example:

```r
library(ggplot2)
library(RColorBrewer)
FeaturePlot(mouse_brain, “MA0497.1”) + scale_color_gradientn(colors = rev(brewer.pal(11, “RdBu”)))
```

**Comment by ElenaTT** [comment]
Hi Tim, 

Thanks! Your suggestion works perfectly if I plot a single motif, but the color scale goes back to default when I plot more than one feature. 

Any idea why? 

Elena

`
FeaturePlot(
  object = scatac,
  features = c("MA0497.1"),
  pt.size = 0.1,
  max.cutoff = 'q99',
  ncol = 3
)+ scale_color_gradientn(colors = rev(brewer.pal(11 ,"RdBu"))) 

![One_motif](https://user-images.githubusercontent.com/8389172/66064190-f0955000-e512-11e9-88a5-940b658014b1.png)


FeaturePlot(
  object = scatac,
  features = c("MA0497.1", "MA0497.1"),
  pt.size = 0.1,
  max.cutoff = 'q99',
  ncol = 3
)+ scale_color_gradientn(colors = rev(brewer.pal(11 ,"RdBu")))

![TwoMotifs](https://user-images.githubusercontent.com/8389172/66064195-f3904080-e512-11e9-8833-82d3943e7540.png)

`

**Comment by timoast** [comment]
To apply this to multiple plots you need to specify `combine=FALSE` in `FeaturePlot`, add the color scale to each plot, then combine the modified plots using `CombinePlots`. For example:

```r
library(Seurat)

p <- FeaturePlot(
  object = scatac,
  features = c("MA0497.1", "MA0497.1"),
  pt.size = 0.1,
  max.cutoff = 'q99',
  combine = FALSE
)

for(i in 1:length(p)) {
  p[[i]] <- p[[i]] + scale_color_gradientn(colors = rev(brewer.pal(11 ,"RdBu")))
}

CombinePlots(p, ncol = 3)
```

**Comment by ElenaTT** [comment]
Great, thanks!
