### ISSUE TITLE
GeneActivity() function error!

### ISSUE THREAD

**Issue by hchintalapudi** [timoast/signac#294]
Hi,
I'm trying to analyze our lab's 10x ScATAC data based on the Signac tutorial (https://satijalab.org/signac/articles/pbmc_vignette.html)

atac_10x_counts<- Read10X_h5(filename = "/Users/hchintalapudi/..10x_ATAC../Ptf1a_1/filtered_peak_bc_matrix.h5")
atac_10x_metadata<- read.csv(
  file = "/Users/hchintalapudi/Desktop/...10x.../Ptf1a_1/singlecell.csv",
  header = TRUE,
  row.names = 1
)
  
chrom_assay <- CreateChromatinAssay(
  counts = atac_10x_counts,
  sep = c(":", "-"),
  fragments = '/Users/hchintalapudi/Desktop/ScATAC/10x_ATAC.../Ptf1a_1/fragments.tsv.gz',
  min.cells = 1,
  min.features = 0
)

atac <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = atac_10x_metadata
)

dr_gtf <- rtracklayer::import("/Users/hchintalapudi/.../Danio_rerio.GRCz11.101.gtf")
gene.coords <- dr_gtf[dr_gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'Ensembl'
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
genebodyandpromoter.coords <- Extend(x = gene.coords, upstream = 2000, downstream = 200)

View(data.frame(gene.coords))
Annotation(atac)<- gene.coords

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = gene.coords)

# compute nucleosome signal score per cell
atac <- NucleosomeSignal(object = atac)

# compute TSS enrichment score per cell
atac <- TSSEnrichment(object = atac, fast = F)

# add blacklist ratio and fraction of reads in peaks
atac$pct_reads_in_peaks <- atac$peak_region_fragments / atac$passed_filters * 100
atac$blacklist_ratio <- atac$blacklist_region_fragments / atac$peak_region_fragments

atac$high.tss <- ifelse(atac$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(atac, group.by = 'high.tss') + NoLegend()

#Fragment length periodicity:
atac$nucleosome_group <- ifelse(atac$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram(object = atac, group.by = 'nucleosome_group')

VlnPlot(
  object = atac,
  features = c('pct_reads_in_peaks', 'peak_region_fragments',
               'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal'),
  pt.size = 0.1,
  ncol = 5
)

#Remove outliers:
atac <- subset(
  x = atac,
  subset = peak_region_fragments > 3000 &
    peak_region_fragments < 20000 &
    pct_reads_in_peaks > 15 &
    blacklist_ratio < 0.05 &
    nucleosome_signal < 4 &
    TSS.enrichment > 2
)

atac <- RunTFIDF(atac)
atac <- FindTopFeatures(atac, min.cutoff = 'q0')
atac <- RunSVD(atac)

DepthCor(atac)

#Non-linear dimension reduction and clustering:

atac <- RunUMAP(object = atac, reduction = 'lsi', dims = 2:30)
atac <- FindNeighbors(object = atac, reduction = 'lsi', dims = 2:30)
atac <- FindClusters(object = atac, verbose = FALSE, algorithm = 3)
DimPlot(object = atac, label = TRUE) + NoLegend()

gene.activities <- GeneActivity(atac)
Extracting gene coordinates
Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07m 16s
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  'NA' indices are not (yet?) supported for sparse Matrices

Can I get some help diagnosing this error please?
Thanks!

**Comment by timoast** [comment]
> dr_gtf <- rtracklayer::import("/Users/hchintalapudi/.../Danio_rerio.GRCz11.101.gtf")
gene.coords <- dr_gtf[dr_gtf$type == 'gene']
seqlevelsStyle(gene.coords) <- 'Ensembl'
gene.coords <- keepStandardChromosomes(gene.coords, pruning.mode = 'coarse')
genebodyandpromoter.coords <- Extend(x = gene.coords, upstream = 2000, downstream = 200)
View(data.frame(gene.coords))
Annotation(atac)<- gene.coords

This is not the correct way to construct the gene annotations. Please see the documentation in the vignettes for examples of how to add gene annotation information to a ChromatinAssay object.

**Comment by tzhu-bio** [comment]
I'm getting the same error, how can I fix it please?
