### ISSUE TITLE
DE peaks for treated vs Control

### ISSUE THREAD

**Issue by manjumoorthy95** [timoast/signac#295]
Basically i have 2 samples( treated and control) that has underwent cell ranger atac processing. I am interested in calling differentially accessible regions with plan of treated Vs Control. Should my pipeline be like merge, then if batch effect persist then integrate, then call findMarker() function? 

Also had a doubt like is integration optional? Is it done only if batch effect is there? Thanks in advance.

**Comment by timoast** [comment]
> Should my pipeline be like merge, then if batch effect persist then integrate, then call findMarker() function?

Yes, this is what I'd recommend

> Also had a doubt like is integration optional? Is it done only if batch effect is there?

Yes, only perform batch correction if there are batch effects
