### ISSUE TITLE
About gene activity matirx of sample integration

### ISSUE THREAD

**Issue by millersan** [timoast/signac#296]
Hi Tim,
thank you for this great package.
Base on the vignettes of "scATAC-seq data integration", I have integrated the scATAC data across 2 samples. Then I have a question how to calculated the gene activity matrix of the integrated data? should I combined two sample fragment to caluculated the gene activity matirx?

If I follow the "PBMC scATAC-seq Vignette" using the "hm.integrated", which assay represent the "ACTIVITY", should I create the gene activity matirx again in the "sciPeaks" assay?

**Comment by timoast** [comment]
The `GeneActivity()` function can be run on a merged or non-merged object, it doesn't matter.
