### ISSUE TITLE
could not install signac

### ISSUE THREAD

**Issue by ZheLiu1991** [timoast/signac#3]
When installing signac

devtools::install_github("timoast/signac")

Reported error:

Downloading GitHub repo timoast/signac@master
Skipping 13 packages not available: AnnotationFilter, BiocGenerics, GenomeInfoDb, GenomicFeatures, GenomicRanges, IRanges, Rsamtools, S4Vectors, TFBSTools, ggbio, motifmatchr, patchwork, AnnotationDbi
Installing 3 packages: ggbio, ggseqlogo, patchwork
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) packages 'ggbio', 'patchwork' are not available (for R version 3.5.3)

**Comment by timoast** [comment]
Some of the dependencies are on bioconductor not CRAN and so will likely not be installed automatically when running `devtools::install_github("timoast/signac")`. There is also one package, `patchwork`, that is only available through github and will need to be installed manually before installing Signac:

```r
devtools::install_github("thomasp85/patchwork")
```


You can tell R to also look on bioconductor for the dependencies by running:

```r
setRepositories(ind=1:2)
```

You should then be able to run `devtools::install_github("timoast/signac")` and have Signac and all the dependencies install. If you don't want to run `setRepositories(ind=1:2)`, you can copy the following to install the bioconductor dependencies before installing Signac:

```r
BiocManager::install(c(
  'AnnotationFilter',
  'BiocGenerics',
  'GenomeInfoDb',
  'GenomicFeatures',
  'GenomicRanges',
  'IRanges',
  'Rsamtools',
  'S4Vectors',
  'TFBSTools',
  'ggbio',
  'motifmatchr',
  'AnnotationDbi')
)
```

I will update the installation instructions on the Signac website with this information too.

**Comment by ZheLiu1991** [comment]
Thank you, problem solved.

**Comment by dagarfield** [comment]
Only semi-related -- would be great to have this up and running for R 3.6
R 3.5.3 is a current hole in the Conda distributions.

**Comment by timoast** [comment]
This should work fine with R 3.6, the dependency is on >= 3.5.3
