### ISSUE TITLE
TSSEnrichment freezes.

### ISSUE THREAD

**Issue by nourin-nn** [timoast/signac#302]
Hi, I have a question about the `TSSEnrichment` function. I am able to calculate the tss enrichment scores for the example in Signac vignettes: "Human peripheral blood mononuclear cells". However, when I repeat same steps on my own scATAC-seq data:
`seu.obj <- TSSEnrichment(object = seu.obj, fast = FALSE) `

it freezes after printing:

> Extracting TSS positions
Finding + strand cut sites

and then, it gets killed by:
> kill 9 

To make sure there is no memory issue, I have down sampled my data by:
```
chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'GRCh38',
  fragments = file.path(project_path, folder, 'fragments.tsv.gz'),
  min.cells = 2000,
  min.features = 100
)
```
which makes an object smaller than example in Signac vignettes:
> An object of class Seurat 
> 9522 features across 5616 samples within 1 assay 
> Active assay: peaks (9522 features, 0 variable features)

Still the same issue!
Not sure if it's related, but I have a mac. My annotation step is:

```
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v79)
Annotation(seu.obj) <- annotations
```
and the input object is:

`seu.obj[["peaks"]]`
> ChromatinAssay data with 9522 features for 5616 cells
> Variable features: 0 
> Genome: GRCh38 
> Annotation present: TRUE 
> Motifs present: FALSE 
> Fragment files: 1 

Any idea what is going wrong here?
Thanks

**Comment by timoast** [comment]
`killed 9` usually indicates it ran out of memory. Can you try with `fast=TRUE`?

**Comment by nourin-nn** [comment]
Anyhow, here is the whole code:

metadata <- read.csv(
  file = file.path(project_path, folder , "singlecell.csv"),
  header = TRUE,
  row.names = 1
)

counts <- Read10X_h5(filename=file.path(project_path, folder, "filtered_peak_bc_matrix.h5"))

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'GRCh38',
  fragments = file.path(project_path, folder, 'fragments.tsv.gz'),
  min.cells = 2000,
  min.features = 100
)

seu.obj <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata,
  project = "YR20002"
)

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v79)
# change to NCBI style since the data was mapped to GRCh38
# seqlevelsStyle(annotations) <- 'NCBI'
# genome(annotations) <- "GRCh38"
# add the gene information to the object
Annotation(seu.obj) <- annotations

print(seu.obj)
print(seu.obj[["peaks"]])
print(dim(seu.obj@meta.data), sep = "\n")

# Nucleosome banding pattern:
# compute nucleosome signal score per cell
seu.obj <- NucleosomeSignal(object = seu.obj)

print(dim(seu.obj@meta.data), sep = "\n")

# compute TSS enrichment score per cell
seu.obj <- TSSEnrichment(object = seu.obj, fast = FALSE)

**Comment by nourin-nn** [comment]
Same! not sure how the algorithm works, but size of my data is smaller than example in Signac vignettes:

> An object of class Seurat 
> 9522 features across 5616 samples within 1 assay 
> Active assay: peaks (9522 features, 0 variable features)
> ChromatinAssay data with 9522 features for 5616 cells

I have also this warning after `CreateSeuratObject`:

> Computing hash
> Checking for 5616 cell barcodes
> Warning message:
> In CreateSeuratObject.Assay(counts = chrom_assay, assay = "peaks",  :
>   Some cells in meta.data not present in provided counts matrix.

Any chance my annotation command causes any internal issue, maybe the cellranger output is incompatible with ensdb?

Anyhow, the whole code is below:

```
folder <- "cellranger"
metadata <- read.csv(
  file = file.path(project_path, folder , "singlecell.csv"),
  header = TRUE,
  row.names = 1
)

counts <- Read10X_h5(filename=file.path(project_path, folder, "filtered_peak_bc_matrix.h5"))

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'GRCh38',
  fragments = file.path(project_path, folder, 'fragments.tsv.gz'),
  min.cells = 2000,
  min.features = 100
)

seu.obj <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata,
  project = "peaks"
)

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v79)
# change to NCBI style since the data was mapped to GRCh38
# seqlevelsStyle(annotations) <- 'NCBI'
# genome(annotations) <- "GRCh38"
# add the gene information to the object
Annotation(seu.obj) <- annotations

# Nucleosome banding pattern:
# compute nucleosome signal score per cell
seu.obj <- NucleosomeSignal(object = seu.obj)

# compute TSS enrichment score per cell
seu.obj <- TSSEnrichment(object = seu.obj, fast = TRUE) 

```

**Comment by timoast** [comment]
Are you 100% sure the annotations you're using are for the genome that the data were mapped to? Can you show the first few lines of the fragment file (`gzip -dc <fragment_file> | head`)?

**Comment by nourin-nn** [comment]
from cellranger web_summar:

> Organism | Homo_sapiens
> Assembly | GRCh38
> Annotation | gencode.v28.basic

`gzip -dc fragments.tsv.gz | head`

> chr1	10079	10339	TCTCTGGAGTCACGCC-1	1
> chr1	10095	10284	GATGGCCGTGCCGGTT-1	1
> chr1	10097	10267	GACTAGTCAAGGATGC-1	1
> chr1	10097	10284	GCACCTTAGGATGTAT-1	2
> chr1	10097	10307	CACAGATGTTTGCATG-1	1
> chr1	10102	10278	TCACCACGTCGACTGC-1	1
> chr1	10102	10279	CTAGGGCAGGGTAATT-1	1
> chr1	10151	10186	TGGGTTACACACATGT-1	1
> chr1	10151	10204	TGCTATTGTACGAGAC-1	1
> chr1	10151	10209	TGCATTTCAAATTCCG-1	3

**Comment by timoast** [comment]
This looks like UCSC-style chromosome names rather than Ensembl / NCBI ("chr" prefix). It's probably mapped to hg38 rather than GRCh38. Since you set the seqlevelsStyle here to NCBI, it's expecting the chromosomes to be named 1, 2, 3, etc rather than chr1, chr2, chr3 etc.

Try changing the seqlevelsStyle to UCSC

**Comment by nourin-nn** [comment]
OK... it seems doing something, thanks! 
Although it seems trivial, but maybe a suggestion could be to add a check-and-flag on top.

**Comment by timoast** [comment]
Added a check for common chromosome names to the develop branch
