### ISSUE TITLE
Variability plot of Motifs in Signac

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#303]
Hi,

1) Is it possible to generate the Varibility plot using chromVAR within Signac.

If so how should I go about doing it?

2) Does Signac allow us to use other motif databases apart from JASPAR?

Thank you!

**Comment by timoast** [comment]
> Is it possible to generate the Varibility plot using chromVAR within Signac.

No, this is not currently possible in Signac. You can always run chromVAR yourself if this is something you want

> Does Signac allow us to use other motif databases apart from JASPAR?

Yes, you can use any list of position weight matrices.
