### ISSUE TITLE
Find Variable Features in Signac

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#304]
Hi,

 Is it practical to run Find Variable Features when analysing scATAC seq data in Signac.

Do we still use vst for that purpose. What is the recommended nfeatures for the same?

Thanks,

**Comment by timoast** [comment]
No, the concept of "mean expression" doesn't make sense for scATAC-seq. We typically use all peaks open in some minimum number of cells. See the `FindTopFeatures()` function
