### ISSUE TITLE
Is it possible to link peaks to genes?

### ISSUE THREAD

**Issue by jogiles** [timoast/signac#306]
Hello!

Forgive me if this is already possible in Signac -- but, it would be wonderful to link gene expression to peak accessibility within Signac using one object that contains an RNA assay and ATAC assay.

There are a few different methods described in the literature (as I'm sure you know!) -- one is implemented in ArchR, another described in the SHARE-seq paper, 10x has their own method. The feature linkage analysis that is output from cellranger-arc is limited because the linkages are only calculated for one sample at a time; it is not possible to consider all of the samples together (best to increase variance).

Thank you for wonderful package!
Josephine

**Comment by timoast** [comment]
Yes, this is available in the latest release (1.1.0). See [here](https://satijalab.org/signac/articles/pbmc_multiomic.html#linking-peaks-to-genes-1) for an example. The method we implemented is based on the method used by SHARE-seq
