### ISSUE TITLE
A bug for TSSEnrichment（）

### ISSUE THREAD

**Issue by hcygirl** [timoast/signac#308]
TSSEnrichment(object = atac_small,verbose=F)
Error in validObject(r) :
  invalid class "ngTMatrix" object: Dim slot must have length 2

I  guess，It may be the reason：

In Signac:::SingleFileCutMatrix function：
 if (nrow(x = fragments) == 0) {
        cut.matrix <- sparseMatrix(i = NULL, j = NULL, dims = c(length(x = cells),
            width(x = region)))
    }

dims should be    dims = c(length(x = cells), width(x = region)[[1]])

**Comment by timoast** [comment]
Right, this is already fixed on the develop branch: https://github.com/timoast/signac/blob/develop/R/utilities.R#L1425
