### ISSUE TITLE
FindMotifs -----Error in density.default(x = mf.query[[i]], kernel = "gaussian", bw = 1) :    'x' contains missing values

### ISSUE THREAD

**Issue by hahia** [timoast/signac#311]
I have this error on findmotifs, how to solve this. Thank any comments.
```
peaks.matched <- MatchRegionStats(
  meta.feature = GetAssayData(pbmc, assay = "peaks", slot = "meta.features")[open.peaks, ],
  regions = top.da.peak,
  n = 10000
)
```
`Error in density.default(x = mf.query[[i]], kernel = "gaussian", bw = 1) :    'x' contains missing values`

**Comment by timoast** [comment]
What is the length of `open.peaks` and `top.da.peak`? This error occur if you're trying to select more regions than are available

**Comment by timoast** [comment]
Closing this now as I haven't heard back
