### ISSUE TITLE
batch correction + transfer data

### ISSUE THREAD

**Issue by minjunp** [timoast/signac#312]
I have scRNA-seq and scATAC-seq data.
Here I created a gene activity matrix and ran Harmony.

Now when I transfer the labels, 

transfer.anchors <- FindTransferAnchors(
					  reference = snRNA,
					    query = obj,
					    reduction = 'cca',
					      dims = 2:50
					    )

predicted.labels <- TransferData(
				   anchorset = transfer.anchors,
				     refdata = snRNA$celltype,
				     weight.reduction = obj[['harmony']],
				       dims = 2:50
				     )

For the weight.reduction, should I use 'harmony' or 'lsi' ?

**Comment by timoast** [comment]
You can use either, but I'd suggest using the `harmony` dimension reduction
