### ISSUE TITLE
could not install signac Development version for R 4.0.3 running on CentOS Linux 7 

### ISSUE THREAD

**Issue by guoyanzhao** [timoast/signac#313]
I read the post "could not install signac #3" and tried the suggestion. I still get the error message. I was able to install the current release without any problem. I also was able to install development version for R 4.0.3 running on Windows 10. However I tried different ways and still can not get it to install on the linux platform. I want to try the new peakcalling function and need to get it to work on linux platform. Thank you very much for your help!

Here is the command I used:
setRepositories(ind=1:2)
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("timoast/signac", ref = "develop")

 Here is the output I got:
Downloading GitHub repo timoast/signac@develop
Skipping 1 packages not available: GenomeInfoDbData
Skipping 31 packages ahead of CRAN: zlibbioc, XVector, GenomeInfoDb, IRanges, S4Vectors, BiocGenerics, GenomicRanges, Biobase, DelayedArray, SummarizedExperiment, BiocFileCache, GenomicAlignments, Rhtslib, BiocParallel, biomaRt, Biostrings, ProtGenerics, Rsamtools, rtracklayer, AnnotationDbi, AnnotationFilter, GenomicFeatures, RBGL, graph, BSgenome, ensembldb, VariantAnnotation, RcppArmadillo, OrganismDbi, biovizBase, ggbio
✓  checking for file ‘/tmp/RtmpqzjfXA/remotes1e62e2305b5dc/timoast-signac-f8c3bca/DESCRIPTION’ ...
─  preparing ‘Signac’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘Signac/.github’
   Removed empty directory ‘Signac/vignettes’
─  building ‘Signac_1.0.9005.tar.gz’
   
....
make: *** [split.o] Error 1
ERROR: compilation failed for package ‘Signac’

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
I tried to install those skipped packages using following command as suggested. Then I tried the installation again. But I got the same error message as above.

BiocManager::install(c(
    'zlibbioc', 'XVector', 'GenomeInfoDb', 'IRanges', 'S4Vectors', 'BiocGenerics', 'GenomicRanges', 'Biobase', 'DelayedArray', 'SummarizedExperiment', 'BiocFileCache', 'GenomicAlignments', 'Rhtslib', 'BiocParallel', 'biomaRt', 'Biostrings', 'ProtGenerics', 'Rsamtools', 'rtracklayer', 'AnnotationDbi', 'AnnotationFilter', 'GenomicFeatures', 'RBGL', 'graph', 'BSgenome', 'ensembldb', 'VariantAnnotation', 'RcppArmadillo', 'OrganismDbi', 'biovizBase', 'ggbio','GenomeInfoDbData')
)

Here is session info output: 
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11     magrittr_1.5        usethis_1.6.3      
 [4] devtools_2.3.2      pkgload_1.1.0       R6_2.5.0           
 [7] rlang_0.4.8         fansi_0.4.1         tools_4.0.3        
[10] pkgbuild_1.1.0      sessioninfo_1.1.1   cli_2.1.0          
[13] withr_2.3.0         ellipsis_0.3.1      remotes_2.2.0      
[16] assertthat_0.2.1    digest_0.6.27       rprojroot_1.3-2    
[19] crayon_1.3.4        processx_3.4.4      BiocManager_1.30.10
[22] callr_3.5.1         fs_1.5.0            ps_1.4.0           
[25] curl_4.3            testthat_3.0.0      memoise_1.1.0      
[28] glue_1.4.2          compiler_4.0.3      desc_1.2.0         
[31] backports_1.2.0     prettyunits_1.1.1

**Comment by timoast** [comment]
This seems to be a more general issue of not being able to compile R packages, rather than anything specific to Signac. I'd suggest seeking help on general R forums

**Comment by guoyanzhao** [comment]
Thank you for your quick response!
I'm wondering what's the differences between the developmental version vs. the current release could lead to this issue. I was able to install the current release without any problem.
