### ISSUE TITLE
 TSSEnrichment issues

### ISSUE THREAD

**Issue by shabs24** [timoast/signac#314]
I am getting the error below when I run the command 
lung <- TSSEnrichment(object = lung, fast = FALSE)
"Finding + strand cut sites
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'intersect': [internal] bgzf_seek() failed"
 
On traceback() 
9: h(simpleError(msg, call))
8: .handleSimpleError(function (cond) 
   .Internal(C_tryCatchHelper(addr, 1L, cond)), "[internal] bgzf_seek() failed", 
       base::quote(.headerTabix(file, ...)))
7: .headerTabix(file, ...)
6: seqnamesTabix(file = tabix.file)
5: seqnamesTabix(file = tabix.file)
4: intersect(x = seqlevels(x = regions), y = seqnamesTabix(file = tabix.file))
3: MultiRegionCutMatrix(regions = plus.strand, object = object, 
       assay = assay, cells = cells, verbose = FALSE)
2: CreateRegionPileupMatrix(object = object, regions = tss.positions, 
       assay = assay, cells = cells, verbose = verbose)
1: TSSEnrichment(object = lung, fast = FALSE)

Any suggestions?

**Comment by timoast** [comment]
Try re-building the fragment file index. You can do so using tabix (tabix -p bed <fragment_file>)

**Comment by shabs24** [comment]
Hi,

I have run into the same error again while running the command:
CoveragePlot(
  object = lung,
  region = c("Ccr2"),
  extend.upstream =40000,
  extend.downstream = 20000,
  ncol = 1
)

9: h(simpleError(msg, call))
8: .handleSimpleError(function (cond) 
   .Internal(C_tryCatchHelper(addr, 1L, cond)), "[internal] bgzf_seek() failed", 
       base::quote(.headerTabix(file, ...)))
7: .headerTabix(file, ...)
6: seqnamesTabix(file = tabix.file)
5: seqnamesTabix(file = tabix.file)
4: intersect(x = seqnames(x = region), y = seqnamesTabix(file = tabix.file))
3: CutMatrix(object = object, region = region, assay = assay, cells = cells, 
       verbose = FALSE)
2: SingleCoveragePlot(object = object, region = region, annotation = annotation, 
       features = features, expression.assay = expression.assay, 
       expression.slot = expression.slot, show.bulk = show.bulk, 
       peaks = peaks, peaks.group.by = peaks.group.by, ranges = ranges, 
       ranges.group.by = ranges.group.by, ranges.title = ranges.title, 
       assay = assay, links = links, tile = tile, tile.size = tile.size, 
       tile.cells = tile.cells, bigwig = bigwig, bigwig.type = bigwig.type, 
       group.by = group.by, window = window, extend.upstream = extend.upstream, 
       extend.downstream = extend.downstream, ymax = ymax, scale.factor = scale.factor, 
       cells = cells, idents = idents, sep = sep, heights = heights, 
       max.downsample = max.downsample, downsample.rate = downsample.rate)
1: CoveragePlot(object = lung, region = c("Ccr2"), extend.upstream = 40000, 
       extend.downstream = 20000, ncol = 1)

I think I was able to resolve the issue by rebuilding the fragment file index. But when I now run the command
tabix -p bed “fragments.tsv.gz" 

I get the following error 
Error: unexpected symbol in "tabix -p bed”


Any suggestions?? Why am I running into this issue with this particular data set. It is working fine with another dataset.

**Comment by ECSaputra** [comment]
I'm currently facing the same problem.  I've tried rebuilding the fragment file index following the code below, but the problem persists:

sort -k 1,1 -k2,2n GSM4995565_scATAC_WT_fragments.bed > GSM4995565_scATAC_WT_fragments.sorted.bed
bgzip GSM4995565_scATAC_WT_fragments.sorted.bed
tabix -p bed GSM4995565_scATAC_WT_fragments.sorted.bed.gz

Any suggestions on possible sources of the problem?
