### ISSUE TITLE
ChromatinAssay and subsetting by features

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#315]
Hi,

Would someone has time to point out what is wrong here? I have ChromatinAssay in my Seurat object. I try to subset both based cells and features. With cells this works as assumed, but if I try to subset with any features I get following error:

Error in SetAssayData.ChromatinAssay(object = x, slot = "ranges", new.data = ranges.keep) : 
  Number of ranges provided is not equal to the number
           of features in the assay
In addition: Warning message:
In rownames(x = x) == features :
  longer object length is not a multiple of shorter object length

And yes, features I try to select are in the object with the same names, and yes naturally vector I give to features parameter is shorter than entire list features. I guess that error is somehow related to the Granges/Annotation information within assay that it is no longer valid or something. I checked Chromatin Assay documentation and I think it says that subset works like in usual.

**Comment by timoast** [comment]
This might be related to a bug in the current release. The bug is fixed on the develop branch, can you try installing from there and see if that solves the issue? Installation instructions [here](https://satijalab.org/signac/articles/install.html#development-version-1)

**Comment by skilpinen** [comment]
Yes, that was it. It works with dev. version. Thanks a lot!
