### ISSUE TITLE
Exporting batch-corrected, normalized counts

### ISSUE THREAD

**Issue by hoondy** [timoast/signac#318]
First of all, thanks Tim for your contribution.

I am working with multiple scATAC-seq samples. Following the tutorials (https://satijalab.org/signac/articles/pbmc_vignette.html, https://satijalab.org/signac/articles/integration.html), I've managed to perform QC, integrate multiple samples, and batch-normalize using TF-IDF followed by SVD. As the PBMC example shows, the 1st LSI component was highly correlated with the depth in our samples.

I ultimately want to export the normalized 'count matrix' after removing the 1st component. If I am understanding this correctly, we can zero the 1st component and multiply the transpose of the rotation matrix to get the counts in the original dimension. This would effectively remove any depth-related variance from the count data. Another use case might be, after various dimensionality reduction, I would like to know if we can selectively export c(2:50) of low dimension back in the original count form.

I would like to know how to perform these in Signac/Seurat pipeline. If this isn't available out of the box, I would like to know if this can be implemented in the future version. Thanks for your support!

**Comment by timoast** [comment]
You could certainly try multiplying the left and right singular vectors after removing the first component, which would effectively produce an imputed data matrix. Depending on your ultimate goal, I'm not sure I'd recommend this approach though, as the resulting matrix will be dense rather than sparse, and since there are a large number of rows the matrix will require a huge amount of RAM to store.

Here's an example if you wanted to give it a try anyway:

```r
loadings <- Loadings(atac[["lsi"]])
embeddings <- Embeddings(atac[['lsi']])
imputed <- tcrossprod(x = loadings[, 2:50], y = embeddings[, 2:50])
```

**Comment by hoondy** [comment]
Thanks, Tim for your suggestion.

Since we are running SVD on TF-IDF transformed matrix, I think we need a diagonal matrix in-between "loadings" and "embeddings". I looked around and found that they are stored under misc. Could you check to see if the below code snippet makes sense? Let me know if I missed something..

```
# suppose we are trying to reconstruct original from SVD decomposed matrices
original <- as.matrix(atac[['ATAC']]@data)

# SVD components were stored in misc
components=Misc(atac[['lsi']])

# vdu instead of udv because t(original) was used
imputed <- components$v %*% diag(components$d) %*% t(components$u)
```

**Comment by timoast** [comment]
Right, you need the diagonal matrix as well
