### ISSUE TITLE
To change the colors in CoveragePlot

### ISSUE THREAD

**Issue by karenlai0222** [timoast/signac#319]
Hi,

I am using the current version of Signac (1.0.0), and I am wondering how I could change the colors of each coverage track in the CoveragePlot function. I saw issue #63, but those solutions did not work on my end. Here is a portion of my code:

cols_adults <- c('pink2', 'darkorchid4', 'dodgerblue2', 'goldenrod1',
                            'darkseagreen3', 'darkolivegreen2', 'cornsilk2')
p <- CoveragePlot(
  object = adult1,
  region = "chr12:84569762-84595457",
  sep = c(":", "-"),
  extend.upstream = 40000,
  extend.downstream = 1000,
  ncol = 1, ymax = 30) +
  scale_x_continuous(breaks=seq(84500000, 84600000, 5000)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p + scale_fill_manual(values = cols_adults)

And this does not change the default colors in the returned plot. Could you provide me some guidance on this? Thank you!

**Comment by timoast** [comment]
Try `p & scale_fill_manual(values = cols_adults)`. We use [patchwork](https://patchwork.data-imaginist.com/articles/guides/assembly.html#modifying-everything) to combine elements of the plot, so to apply modifications to all elements of the plot you need to use the `&` operator

**Comment by karenlai0222** [comment]
This works perfectly. Thank you!
