### ISSUE TITLE
How to excess data plotted with CoveragePlot

### ISSUE THREAD

**Issue by berixD** [timoast/signac#32]
Hi timoast,
Signac is a great tool. Thanks for that!
I would like to extract the normalized accessibility data for all identities as plotted with CoveragePlot. With this data, I would like to know all regions of open chromatin (above a certain threshold) in order to look for cis-acting elements. I tried looking at the functions buildup and came up with the idea to use the cutmat matrix. But I am stuck, because I dont know how to do it for all identities and multiple regions in an efficient way.

Thanks in advance!

 Ps. Is a command list of the signac package avialable? Something similar to Seurat's one would be nice https://satijalab.org/seurat/essential_commands.html

**Comment by timoast** [comment]
Hi, I think the easiest thing for you to do might be to call peaks on each group of cells and then quantify reads in those peaks using the `FeatureMatrix` function. You can write the cell names for each group to a file and then split the bam file by into different file for each group of cells using [sinto](https://github.com/timoast/sinto), and then call peaks using the split bam files.

I don't have a command list for the package available right now, but I will add this to my list of things to do for Signac.

**Comment by berixD** [comment]
Thanks for the quick reply! I will try the FeatureMatrix option:)
