### ISSUE TITLE
Cannot change cellnames of fragment object

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#320]
I merged 23 snATAC samples, but while doing so I changed the cell names to include the sample number as a prefix.  Now I am trying to add all the individual fragment objects as a list to the seurat object.  However, it says:
```
 Error in AddFragments(object = object, fragments = value[[i]]) :
  None of the cells in the fragment object are present in the assay
```
I realize this is becuase the prefix changed the names of the cells.  So when I try to add a prefix to the fragment object cells, I get this error message. 

```
Cells(fragment.list[[1]])<-paste("99",Cells(fragment.list[[1]]),sep="_")
Error in `Cells<-.Fragment`(`*tmp*`, value = c("99_AAACGAAAGCTACGCC-1",  :
  Cells must be a named vector

```

**Comment by timoast** [comment]
As stated in the error message, the cell names must be a named vector. See the [documentation](https://satijalab.org/signac/articles/data_structures.html#the-fragment-class-1) for more information.

FYI, Signac will rename cells in the Fragment object for you if it's stored in the assay

**Comment by danielcgingerich** [comment]
@timoast I used a named vector and it still will not work

**Comment by danielcgingerich** [comment]
@timoast the fragments were not stored in the assay because merge() would not work for seurat.  I had to do it manually

**Comment by danielcgingerich** [comment]
```
x<-paste0("99_",Cells(fragment.list[[1]]))
names(x)<-Cells(fragment.list[[1]])
Cells(fragment.list[[1]])<-x
Error in `Cells<-.Fragment`(`*tmp*`, value = c(`AAACGAAAGCTACGCC-1` = "99_AAACGAAAGCTACGCC-1",  :
  Cells not present in fragment file
```
 It is present in the fragment file.  
```
which(Cells(fragment.list[[1]])=="AAACGAAAGCTACGCC-1")
[1] 1
```

**Comment by timoast** [comment]
From the `Fragment-class` documentation:

> cells
A named vector of cells where each element is the cell barcode as it appears in the fragment file, and the name of each element is the corresponding cell barcode as stored in the ChromatinAssay object.

Here you've set the name of each element to the cell name as it appears in the fragment file, rather than as it appears in the ChromatinAssay. You need to reverse it:

```r
x <- Cells(fragment.list[[1]])
names(x) <- paste0("99_", x)
Cells(fragment.list[[1]]) <- x
```
