### ISSUE TITLE
CoveragePlot Error in UseMethod question

### ISSUE THREAD

**Issue by minjunp** [timoast/signac#321]
Hi Tim,

I am trying to run the following code:
cov_plot <- CoveragePlot(
  object = obj,
  region = "chr2-87011729-87035519",
  annotation = FALSE,
  peaks = FALSE
)
cov_plot

I am getting an error that says:
Error in UseMethod(generic = "Fragments", object = object): no applicable method for 'Fragments' applied to an object of class "Assay"
Traceback:

1. CoveragePlot(object = f4, region = loc, annotation = FALSE, peaks = FALSE)
2. SingleCoveragePlot(object = object, region = region, annotation = annotation, 
 .     features = features, expression.assay = expression.assay, 
 .     expression.slot = expression.slot, show.bulk = show.bulk, 
 .     peaks = peaks, ranges = ranges, ranges.title = ranges.title, 
 .     assay = assay, links = links, tile = tile, tile.size = tile.size, 
 .     tile.cells = tile.cells, group.by = group.by, window = window, 
 .     extend.upstream = extend.upstream, extend.downstream = extend.downstream, 
 .     ymax = ymax, scale.factor = scale.factor, cells = cells, 
 .     idents = idents, sep = sep, heights = heights, max.downsample = max.downsample, 
 .     downsample.rate = downsample.rate)
3. CutMatrix(object = object, region = region, assay = assay, cells = cells, 
 .     verbose = FALSE)
4. Fragments(object = object[[assay]])

It is a little odd because I have set fragments in the object.
Here is how my object looks like:
An object of class Seurat 
263001 features across 18888 samples within 2 assays 
Active assay: peaks (241166 features, 234390 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: lsi, umap, harmony

Can you explain why I am getting this error?

**Comment by timoast** [comment]
Can you provide the full code you ran?

**Comment by minjunp** [comment]
Hi Tim,

I realized that I need to use CreateChromatinAssay in order to plot coveragePlot. 
I found the source of the error. Thanks!
