### ISSUE TITLE
Possible to add 2 chromatin assays?

### ISSUE THREAD

**Issue by jogiles** [timoast/signac#324]
Hello!

Is it possible to add two chromatin assays (given them different names) to the same signac object? One based on a genome bin by cell matrix and a second with a peak by cell matrix?

Thank you!
Josephine

**Comment by timoast** [comment]
Yes, you can add as many ChromatinAssay or Assay object as you like to the Seurat object, they just need to have different names. To add a new assay use the `[[<-` operator, eg `obj[['new_assay_name']] <- CreateChromatinAssay(...)`
