### ISSUE TITLE
Normalized Accessibility Score

### ISSUE THREAD

**Issue by minjunp** [timoast/signac#325]
Hi Tim,

Can I get the normalized accessibility score for all peaks in the object?
In the CoveragePlot, I see normalized accessibility.

I am trying to subset those peaks that have high accessibility. 
Or do you have any other suggestions to subset highly accessible peaks?

Thanks!

**Comment by timoast** [comment]
You can use the `Seurat::AverageExpression()` function to find the average counts for each peak for each group of cells (use `slot="counts"`). Alternatively, if you just want to find peaks with over a certain number of counts in the dataset, you can run the `Signac::FindTopFeatures()` function
