### ISSUE TITLE
CoveragePlot() is blank.

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#327]
I am trying to make a coverage plot of control vs stim cells within a merged seurat object that comes from many samples.  As such, the aggregated fragments object for this seurat object is a list of 23 different fragment objects.  My coverage plot shows information on the peaks and gene annotations, but the rest is completely empty.  From past issues (#98), I see this is a common problem when the cell names of the fragments file do not match the cell names of the object to plot.  I checked my fragments and this is not the case, all names match up.  Below I have provided information on the seurat object, the region to plot, column names, fragment cell names, and the resulting coverage plot.  The merged seurat object (~70000 cells) was downsampled X10 for speed and then filtered for `Idents() `of interest.

```
#SEURAT OBJECT INFO
> seurat.object
An object of class Seurat 
269206 features across 1420 samples within 1 assay 
Active assay: combined.peaks (269206 features, 0 variable features)

#FRAGMENT INFO
>Fragments(seurat.object)
[[1]]
A Fragment object for 544 cells
[[2]]
A Fragment object for 385 cells
[[3]]
A Fragment object for 171 cells
[[4]]
A Fragment object for 156 cells
[[5]]
A Fragment object for 429 cells
[[6]]
A Fragment object for 127 cells
[[7]]
A Fragment object for 179 cells
[[8]]
A Fragment object for 172 cells
[[9]]
A Fragment object for 563 cells
[[10]]
A Fragment object for 636 cells
[[11]]
A Fragment object for 37 cells
[[12]]
A Fragment object for 229 cells
[[13]]
A Fragment object for 572 cells
[[14]]
A Fragment object for 304 cells
[[15]]
A Fragment object for 229 cells
[[16]]
A Fragment object for 727 cells
[[17]]
A Fragment object for 375 cells
[[18]]
A Fragment object for 124 cells
[[19]]
A Fragment object for 228 cells
[[20]]
A Fragment object for 61 cells
[[21]]
A Fragment object for 6 cells
[[22]]
A Fragment object for 215 cells
[[23]]
A Fragment object for 531 cells
> fragment.cells<-c(Cells(Fragments(seurat.object)[[1]]),
   Cells(Fragments(seurat.object)[[2]]),
   Cells(Fragments(seurat.object)[[3]]),
   Cells(Fragments(seurat.object)[[4]]),
   Cells(Fragments(seurat.object)[[5]]),
   Cells(Fragments(seurat.object)[[6]]),
   Cells(Fragments(seurat.object)[[7]]),
   Cells(Fragments(seurat.object)[[8]]),
   Cells(Fragments(seurat.object)[[9]]),
   Cells(Fragments(seurat.object)[[10]]),
   Cells(Fragments(seurat.object)[[11]]),
   Cells(Fragments(seurat.object)[[12]]),
   Cells(Fragments(seurat.object)[[13]]),
   Cells(Fragments(seurat.object)[[14]]),
   Cells(Fragments(seurat.object)[[15]]),
   Cells(Fragments(seurat.object)[[16]]),
   Cells(Fragments(seurat.object)[[17]]),
   Cells(Fragments(seurat.object)[[18]]),
   Cells(Fragments(seurat.object)[[19]]),
   Cells(Fragments(seurat.object)[[20]]),
   Cells(Fragments(seurat.object)[[21]]),
   Cells(Fragments(seurat.object)[[22]]),
   Cells(Fragments(seurat.object)[[23]]))
> seurat.object.cells<-colnames(seurat.object)
> table(seurat.object.cells %in% fragment.cells)
TRUE 
1420

#CHROMOSOME REGION TO PLOT INFO
> chr.region
GRanges object with 1 range and 0 metadata columns:
      seqnames            ranges strand
         <Rle>         <IRanges>  <Rle>
  [1]    chr21 24993065-27000532      *
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths

#RESULTING COVERAGE PLOT
> CoveragePlot(seurat.object,region = inh.region)
Scale for 'y' is already present. Adding another scale for 'y', which will replace the existing scale.
```

![image](https://user-images.githubusercontent.com/65676131/99279895-beba7800-27fe-11eb-8d1e-4bfdd9503237.png)

```
Warning messages:
1: Removed 2 rows containing missing values (geom_segment). 
2: Removed 2 rows containing missing values (geom_rect). 
3: Removed 4 rows containing missing values (geom_segment). 
4: Removed 1 rows containing missing values (geom_text). 
```

**Comment by timoast** [comment]
Can you include the full code you used to create the object?

**Comment by danielcgingerich** [comment]
Hi Tim, here is my code: 

```
#COMPILE ALL PEAKS ACROSS SAMPLES
object.list <- as.list(1:23)
number.list <- list("99", "111", "127", "191", "196",
                    "273", "347", "357", "372", "430",
                    "437", "542", "676", "688", "730",
                    "963", "984", "1099", "1545", "1557",
                    "1600", "1670", "1690")
for (i in 1:length(number.list)) {
  object.list[[i]] <- readRDS(paste0('/gpfs/fs1/.../filteredQC_objects/',
                                     number.list[[i]],
                                     'atac_seurat.object_nucsig-tss-pct.reads-blacklist-filtered.rds'))
}
peak.list <- as.list(1:length(object.list))
names(peak.list) <- c("peaks99", "peaks111", "peaks127", "peaks191", "peaks196",
                      "peaks273", "peaks347", "peaks357", "peaks372", "peaks430", 
                      "peaks437", "peaks542", "peaks676", "peaks688", "peaks730",
                      "peaks963", "peaks984", "peaks1099", "peaks1545", "peaks1557",
                      "peaks1600", "peaks1670", "peaks1690")
for (i in 1:length(object.list)) {
  peak.list[[i]] <- StringToGRanges(rownames(object.list[[i]]), sep = c("-", "-"))
}
list2env(peak.list, envir = .GlobalEnv)
combined.peaks <- reduce(x = c(peaks99, peaks111, peaks127, peaks191, peaks196,
                               peaks273, peaks347, peaks357, peaks372, peaks430, 
                               peaks437, peaks542, peaks676, peaks688, peaks730,
                               peaks963, peaks984, peaks1099, peaks1545, peaks1557,
                               peaks1600, peaks1670, peaks1690))
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]

#QUANTIFY FRAGMENTS FOR EACH SAMPLE. BE SURE TO ADD PREFIX DENOTING SAMPLE ID
for (i in 1:23){
  object.list[[i]] <-RenameCells(object.list[[i]], add.cell.id = number.list[[i]])
  quantified.frag.list[[i]] <- FeatureMatrix(
    fragments = Fragments(object.list[[i]]),
    features = combined.peaks,
    cells = colnames(object.list[[i]]))
}

#MERGE FRAGMENT MATRICES
merged.combined.mtx <- quantified.frag.list[[1]]
for (i in 2:23){
  merged.combined.mtx <- merge.Matrix(merged.combined.mtx, quantified.frag.list[[i]], 
                                      by.x = rownames(merged.combined.mtx),
                                      by.y = rownames(quantified.frag.list[[i]]))
}

#CREATE SEURAT OBJECT
combined.peaks <- CreateChromatinAssay(counts = merged.combined.mtx,
                                              min.cells = -1,
                                              ranges = combined.peaks,
                                              genome = 'hg38')
combined.peaks <- CreateSeuratObject(counts = merged.combined.assay,
                                             assay = 'combined.peaks')

#ADD FRAGMENT OBJECTS
fragment.path.list <- list(
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz',
  '/gpfs/fs1/.../fragments.tsv.gz')

cells.use.list<-list()
fragment.list<-list()

#substr() is used to omit prefix that was added to cells that is not included in fragment files
for (i in 1:23){
  message(i)
  cells.use.list[[i]]<-colnames(combined.peaks)[startsWith(colnames(combined.peaks),number.list[[i]])]
  fragment.list[[i]]<-CreateFragmentObject(fragment.path.list[[i]], 
                                           cells = substr(cells.use.list[[i]],nchar(number.list[[i]])+2,nchar(cells.use.list[[i]])))
}
cellnames.vector.list<-list()
for (i in 1:23){
  message(i)
  cellnames.vector.list[[i]]<-Cells(fragment.list[[i]])
  names(cellnames.vector.list[[i]])<-paste0(number.list[[i]],"_",Cells(fragment.list[[i]]))
  Cells(fragment.list[[i]])<-cellnames.vector.list[[i]]
}
Fragments(combined.peaks)<-fragment.list

```

**Comment by timoast** [comment]
I'm not sure what the issue is here but I'd suggest the following:

1. Check that there are fragments present in the region you're plotting
2. Run the same code using only one fragment file 
3. Double-check that the correct cell barcodes are present in the fragment file

**Comment by yingyonghui** [comment]
Hi all,
I've just encountered the same error.
Is there any update on this problem?
Any suggestions would be appreciated!
Thx!

**Comment by danyama312** [comment]
Hi all,

I have also encountered a similar problem, except CoveragePlot() seems to have issues linking to some, but not all of my fragment files. I know that there is an issue here as I get the following result when plotting the accessibility profile of beta-Actin, which as a housekeeping gene should be accessible, across all cell types represented in the dataset.

```
p3 <- CoveragePlot(ATAC, 
                   region = "Actb", 
                   group.by = "Sample")
```

> [W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_14D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_14D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_30D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_30D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_5D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_5D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_Naive/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/O_Naive_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_14D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_14D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_30D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_30D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_5D_1/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_5D_2/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_Naive/outs/fragments.tsv.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: /home/rstudio/cellRanger_Fragments/Y_Naive_2/outs/fragments.tsv.gz.tbi

```
p3
```
![image](https://github.com/stuart-lab/signac/assets/93013930/31cb4919-e6fd-43c4-9011-46d379ebd176)


I have double-checked that the fragment file directories are correct and that they are linked:
```
Fragments(ATAC)
```

> [[1]]
> A Fragment object for 6375 cells
> 
> [[2]]
> A Fragment object for 2892 cells
> 
> [[3]]
> A Fragment object for 3326 cells
> 
> [[4]]
> A Fragment object for 3636 cells
> 
> [[5]]
> A Fragment object for 3209 cells
> 
> [[6]]
> A Fragment object for 3926 cells
> 
> [[7]]
> A Fragment object for 4122 cells
> 
> [[8]]
> A Fragment object for 902 cells
> 
> [[9]]
> A Fragment object for 3481 cells
> 
> [[10]]
> A Fragment object for 3751 cells
> 
> [[11]]
> A Fragment object for 3941 cells
> 
> [[12]]
> A Fragment object for 3326 cells
> 
> [[13]]
> A Fragment object for 2230 cells
> 
> [[14]]
> A Fragment object for 3371 cells
> 
> [[15]]
> A Fragment object for 3427 cells
> 
> [[16]]
> A Fragment object for 773 cells

I have also checked that the correct cell barcodes are present in the fragment files which are not being plotted (i.e O_Naive, O_Naive_2, Y_Naive, Y_Naive_2) as suggested by @timoast 

```
atac_cells <- as.data.frame(Cells(x = ATAC))
colnames(atac_cells) <- "UMIs"

fragment_cells <- ATAC@assays[["peaks"]]@fragments[[7]]@cells
fragment_cells <- fragment_cells + ATAC@assays[["peaks"]]@fragments[[8]]@cells
fragment_cells <- fragment_cells + ATAC@assays[["peaks"]]@fragments[[15]]@cells
fragment_cells <- fragment_cells + ATAC@assays[["peaks"]]@fragments[[16]]@cells

fragment_cells <- as.data.frame(fragment_cells)

# Check if barcodes in fragment_cells are listed in atac_cells
matching_cells <- row.names(fragment_cells) %in% atac_cells$UMIs

# Count the number of matched and unmatched barcodes
num_matched <- sum(matching_cells)
num_unmatched <- sum(!matching_cells)
```

> print(paste("Number of matched barcodes:", num_matched))
> [1] "Number of matched barcodes: 4122"
> print(paste("Number of unmatched barcodes:", num_unmatched))
> [1] "Number of unmatched barcodes: 0"
