### ISSUE TITLE
Wrong clustering

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#328]
I followed the merging and QC tutorials, but the clustering solution that I'm getting does not make sense. I was using Signac ~6 months ago, and the clustering was okay back then. ArchR is also giving me the correct clustering solution.
this is what I get 
![image](https://user-images.githubusercontent.com/19545198/99318258-36e36680-281c-11eb-9cdd-b1aa9ea6f6a7.png)

The previous clustering looked like this(sorry I only had the RNA expression overlay)
![image](https://user-images.githubusercontent.com/19545198/99318652-f2a49600-281c-11eb-81da-fc777fc888e9.png)

And this is what I'm getting with ArchR

![image](https://user-images.githubusercontent.com/19545198/99319230-043a6d80-281e-11eb-8149-09e65bb040d5.png)

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by rojinsafavi** [comment]
I emailed them to you, thanks again

**Comment by timoast** [comment]
Do you expect to have 106k cells? My guess is that there are many empty droplets here and you need to do a more stringent cell filtering

**Comment by rojinsafavi** [comment]
The number of cells that I have with ArchR after all filtering and stuff ends up to be 82,485. The filtering would be in the QC part correct?

**Comment by rojinsafavi** [comment]
So I looked at the object again, and after all filtering I end up with 35281 cell (in Signac)

**Comment by timoast** [comment]
Ok, in the notebook you sent the object appears to be different sizes at different stages (35k cells, then later 71k cells) which doesn't make sense. I'd suggest re-running the code in order, in a new R session
