### ISSUE TITLE
Field information returned from ClosestFeature()

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#329]
I am really enjoying Seurat/Signac, and I greatly appreciate this repository where our questions can be answered at no cost - thank you @satijalab @timoast @andrewwbutler and all others I may not have mentioned.  

I am trying to understand how` ClosestFeature()` works in order to describe a figure I am working on.  I have a bunch of peaks that overlap with genes (distance = 0).  I see that for any one gene name, `ClosestFeature()` can be multiple different regions.  Does this mean that it is counting overlaps with exons, cds, utr's, and introns... or does closest feature only count overlaps with a subset of these types, such as exons.  I see there is a `type` field in the object returned by closest feature.  Is this referring to the type of the `closest_region `or the `query_region` fields of the dataframe.  

I am currently trying to figure this out on my own using `subsetByOverlaps`() on between GRanges from the `closest_region` field and my annotations object from Ensdb.v86.  However, there are around 10X as many overlaps as there are peak ranges, leading me to believe that the peak ranges overlap with more than one type (exon, intron, cds, utr etc.)  Could someone please explain?

Thanks!

**Comment by timoast** [comment]
ClosestFeature is just a wrapper for `GenomicRanges::distanceToNearest`, you can see the code here: https://github.com/timoast/signac/blob/master/R/utilities.R#L204-L221

By default ClosestFeature uses the gene annotations stored in the assay, which typically includes cds, exons, UTRs, etc.

> I see there is a type field in the object returned by closest feature. Is this referring to the type of the closest_region or the query_region fields of the dataframe.

The "type" refers to the annotated type (cds, exon...) and corresponds to the closest_region (the query_region is the input genomic ranges and doesn't have a type)
