### ISSUE TITLE
Error with AddMotifs

### ISSUE THREAD

**Issue by kelsell15** [timoast/signac#334]
After updating to Signac 1.1 and performing the pfm <- getMatrixSet step in the Motif analysis vignette, when I attempt to #add motif information, with the following script

Sg <- AddMotifs(Sg, BSgenome.Drerio.UCSC.danRer11, pfm = pfm)

I get the following error code:

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function 'matchMotifs' for signature '"PWMatrixList", "Assay"'

**Comment by timoast** [comment]
The default assay is probably a standard Seurat Assay rather than a Signac ChromatinAssay. You can change the default assay using the `DefaultAssay` function.

**Comment by kelsell15** [comment]
Even after performing:

DefaultAssay(Sg) <- 'ATAC'

(where 'ATAC' is equivalent to 'peaks' in the adult mouse brain vignette), I still receive the same error.

**Comment by timoast** [comment]
What's the output of `class(Sg[["ATAC"]])`?

**Comment by kelsell15** [comment]
`> class(Sg[["ATAC"]])
[1] "Assay"
attr(,"package")
[1] "Seurat"`

**Comment by kelsell15** [comment]
> class(Sg[["ATAC"]])
[1] "Assay"
attr(,"package")
[1] "Seurat"

**Comment by timoast** [comment]
So that's a standard Seurat Assay rather than a Signac ChromatinAssay. You need to create a ChromatinAssay using the `CreateChromatinAssay()` function, see the [vignettes](https://satijalab.org/signac/articles/pbmc_vignette.html) for examples.
