### ISSUE TITLE
Cannot run CoveragePlot() on data without fragment file

### ISSUE THREAD

**Issue by genecell** [timoast/signac#335]
Hi,

I used a data without fragment file, and when I run `CoveragePlot()`, I got this error:

> Error in `colnames<-`(`*tmp*`, value = start(x = region):end(x = region)): attempt to set 'colnames' on an object with less than two dimensions

> Traceback:
> 
> 1. CoveragePlot(object = seo, region = c("CDK9"), extend.upstream = 1000, 
>  .     extend.downstream = 1000, ncol = 1)
> 2. SingleCoveragePlot(object = object, region = region, annotation = annotation, 
>  .     features = features, expression.assay = expression.assay, 
>  .     expression.slot = expression.slot, show.bulk = show.bulk, 
>  .     peaks = peaks, ranges = ranges, ranges.title = ranges.title, 
>  .     assay = assay, links = links, tile = tile, tile.size = tile.size, 
>  .     tile.cells = tile.cells, group.by = group.by, window = window, 
>  .     extend.upstream = extend.upstream, extend.downstream = extend.downstream, 
>  .     ymax = ymax, scale.factor = scale.factor, cells = cells, 
>  .     idents = idents, sep = sep, heights = heights, max.downsample = max.downsample, 
>  .     downsample.rate = downsample.rate)
> 3. `colnames<-`(`*tmp*`, value = start(x = region):end(x = region))
> 4. stop("attempt to set 'colnames' on an object with less than two dimensions")

Is fragment files required to run `CoveragePlot()`? Thanks!

MD

**Comment by timoast** [comment]
Yes, a fragment file is required
