### ISSUE TITLE
About CreateChromatinAssay (seraut) and I can't use signac

### ISSUE THREAD

**Issue by July233** [timoast/signac#336]
1、**I want to intergret sc-ATACseq(mouse) by seraut.**
My error is as follows:
`atac <- Read10X("D:/1astudy/heterogeneity/Ecell_data/ATAC/", gene.column = 1)`
`gtf_file<-load("D:/1astudy/heterogeneity/Ecell_data/atac1/GRCm38_mm10.gtf.gz")`
`activity.matrix <- CreateGeneActivityMatrix(peak.matrix = atac,
annotation.file = gtf_file,
seq.levels =sep = c(":", "-"),
upstream = 2000,
verbose = TRUE)`
Error:GenomeInfoDb::keepSeqlevels(x = gtf, value = seq.levels, pruning.mode = "coarse") :    invalid seqlevels: :, -

2、**I want use the signac method,but  I don't have fragment files.Because I use others data,that just includes(acATACseq) bed.files ,matrix.mtx and barcode.**
Thanks for you reply.

**Comment by timoast** [comment]
The `seq.levels` argument should be a vector of sequence levels to retain in the gtf file...here you've set it to the "sep" argument. See the documentation for CreateGeneActivityMatrix: https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/CreateGeneActivityMatrix

Note that CreateGeneActivityMatrix is a deprecated function in Seurat.

Signac requires a fragment file as input to create a gene activity matrix, and for many other functions.

**Comment by July233** [comment]
sorry,I don't understand it very well.Can you give me an example with mm10？why is it different with pump example-------- 原始邮件 --------发件人： Tim Stuart <notifications@github.com>日期： 2020年11月21日周六 半夜11:20收件人： timoast/signac <signac@noreply.github.com>抄送： July233 <xiaoyannuonuo@163.com>, Author <author@noreply.github.com>主    题： Re: [timoast/signac] About CreateChromatinAssay (seraut) and I can't use signac (#336)
The seq.levels argument should be a vector of sequence levels to retain in the gtf file...here you've set it to the "sep" argument. See the documentation for CreateGeneActivityMatrix: https://www.rdocumentation.org/packages/Seurat/versions/3.1.4/topics/CreateGeneActivityMatrix
Note that CreateGeneActivityMatrix is a deprecated function in Seurat.
Signac requires a fragment file as input to create a gene activity matrix, and for many other functions.
