### ISSUE TITLE
Having issues with AddMotifs function

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#339]
<img width="914" alt="Screen Shot 2020-11-23 at 12 57 07 PM" src="https://user-images.githubusercontent.com/64283689/100003300-7285af80-2d8b-11eb-8771-35fe66ff601a.png">
<img width="1008" alt="Screen Shot 2020-11-23 at 12 59 11 PM" src="https://user-images.githubusercontent.com/64283689/100003468-c1cbe000-2d8b-11eb-8f92-e6fca103d931.png">

Having issues with AddMotifs function.
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'matchMotifs' for signature '"PWMatrixList", "Assay"'

**Comment by timoast** [comment]
It looks like you're trying to run this function on a Seurat object where the default assay is a standard Assay rather than a ChromatinAssay. This can only be run on a ChromatinAssay object. See #334, #338
