### ISSUE TITLE
Subsetting data based on metadata & mixed species samples

### ISSUE THREAD

**Issue by mliiv** [timoast/signac#34]
Hi,

I have pooled hg19 + mm10 scATAC-seq data, 10X, CellRanger v3 output. Wanted to run signac MergeWithRegions for two different samples, made with same method. Since the data is mixed-species, I have genome version appended to peak names where "" is replaced with "-" during CreateSeuratObject (peak names e.g. hg19-chr1:10384-10479 & mm10-chr1:10384-10479). So now the "hg19-" and "mm10-" in peak names do not match the "hg19" and "mm10_" in the fragments file (where chromosomes as hg19_chr1 and mm10_chr1).
1. I made new species-specific fragment files without genome version appended to chrom names. Then changed the Dimnames to also not have "hg19-" and "mm10-" in chrom names: siC.D3.atac$peaks@counts@Dimnames[[1]] <- gsub("mm10-","", siC.D3.atac$peaks@counts@Dimnames[[1]])
So now all I would need to do is subset the mouse data from the seurat object. Tried to use the metadata is_mm10_cell_barcode for that (since it's nicely incorporated when creating the object) - no error but also no subset taken: 

a <- SubsetData(CN.atac, cells.use = CN.atac@meta.data[which(CN.atac@meta.data$is_mm10_cell_barcode == "1"), ]) - NO SUBSET PRODUCED

2. Tried to merge with MergeWithRegions the two samples without separating the mouse and human samples (both samples have hg19+mm10). I think there is a problem here with
sep.1 = c(":", "-"),
sep.2 = c(":", "-")
since I would need sep to also include "hg19_" and "mm10_" .
Also, the fragment file has "hg19_" whereas seurat object was changed to "hg19-" so that's also a problem, I guess.

Do you have a solution for using such mixed-species samples? And subsetting them easier for integration?

> unintegrated <- MergeWithRegions(
object.1 = TR.atac,
object.2 = CN.atac,
assay.1 = "peaks",
assay.2 = "peaks",
sep.1 = c(":", "-"),
sep.2 = c(":", "-")
)

> Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) :
some values in the "start" column cannot be turned into numeric values
In addition: Warning message:
Expected 3 pieces. Additional pieces discarded in 224211 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...].
System configuration

Running on:

    Operating System: CentOS Linux 7 (Core)
    Version of Python: python3.7
    version: R version 3.6.0 (2019-04-26)
    Signac * 0.1.5 2019-10-27 [1] Github (timoast/signac@241ad37)

Thank you in advance,
Maria

**Comment by timoast** [comment]
Hi Maria,

For merging the objects the chromosome naming in the fragment file won't matter. You should just need to replace the underscore in the peak name with something else so that it doesn't get changed to a dash when the Seurat object is created. Here's an example using two mixed genome datasets from the 10x Genomics website (https://support.10xgenomics.com/single-cell-atac/datasets):

```r
library(Signac)
library(Seurat)

counts.1 <- Read10X_h5(filename = "/home/stuartt/data/10x_atac/human_mouse/5k_v1/atac_hgmm_5k_v1_filtered_peak_bc_matrix.h5")
counts.2 <- Read10X_h5(filename = "/home/stuartt/data/10x_atac/human_mouse/10k_v1/atac_hgmm_10k_v1_filtered_peak_bc_matrix.h5")

rownames(counts.1) <- gsub(pattern = '_', replacement = '', x = rownames(counts.1))
rownames(counts.2) <- gsub(pattern = '_', replacement = '', x = rownames(counts.2))

obj.1 <- CreateSeuratObject(counts = counts.1, assay = 'ATAC')
obj.2 <- CreateSeuratObject(counts = counts.2, assay = 'ATAC')

combined <- MergeWithRegions(
  object.1 = obj.1,
  object.2 = obj.2,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)
```

If you want to subset a dataset to only the human or mouse cells and have the 10x metadata stored in the object, you can use the `subset` function or the `[` operator. For example:

```r
counts <- Read10X_h5(filename = "/home/stuartt/data/10x_atac/human_mouse/10k_v1/atac_hgmm_10k_v1_filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "/home/stuartt/data/10x_atac/human_mouse/10k_v1/atac_hgmm_10k_v1_singlecell.csv",
  header = TRUE,
  row.names = 1
)
obj <- CreateSeuratObject(counts = counts, meta.data = metadata, assay = "ATAC")
mouse <- obj[, obj$is_mm10_cell_barcode == 1]
```

**Comment by mliiv** [comment]
Hi Tim,

thank you for the rapid answer! Subsetting much more simpler than I was trying. Didn't know that the fragment file can stay as is. As a small comment, some cells in my data have both is_mm10_cell_barcode=1 and is_hg19_cell_barcode=1, so I need to add !(obj$is_hg19_cell_barcode == 1) . 

I have cell line samples from the same 10X Chromium run, so merging two lanes with low assumed tech variability - still the MergeWithRegions gives two separate clusters (tried min.cutoff = "q5" and min.cutoff = 50). So I guess that's just the singe cell ATAC-seq variability in peak calling from cellragner? Anyway,
I then continued to run GetIntersectingFeatures, following the tutorial scATAC-seq data integration. I still think there's a problem with the hg19+mm10 original fragments file since when running FeatureMatrix with my subsampled 10000 regions, I get error "Error: subscript contains out-of-bounds indices". And I can't think of anywhere else than the fragments file for its origin. 

peaks.use <- sample(intersecting.regions[[1]], size = 10000, replace = FALSE)
g <- StringToGRanges(peaks.use, sep = c(":", "-"))
gene.activities <- FeatureMatrix(
   fragments = "scATAC-seq/cellranger/T1/outs/fragments.tsv.gz",
   features = g,
  cells = colnames(siC.D3.atac),
  chunk = 10 )
Error: subscript contains out-of-bounds indices

I then again changed to my mm10-only fragment file, but get a new error with FeatureMatrix which I did not have before so that's puzzling. Have you seen it or could have an idea how to fix? 

 gene.activities <- FeatureMatrix(
     fragments = fragment_file_filtered,
     features = g,
     cells = colnames(m27a.D3.atac),
     chunk = 10  )

Extracting reads overlapping genomic regions
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=14s  
Constructing matrix
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE

Btw, I am filtering and indexing the fragments file with the FilterFragments function.

Thanks again, appreciate the help!
Maria

**Comment by mliiv** [comment]
Hi again,

I now figured out the problem of the last error. I was also changing the cell names in each sample since there were non-unique names. That again lost cell name matching with the fragment file.. so looks like I still need to change the fragment file with awk or smth like that and then re-run FilterFragments. 

Cheers,
Maria
