### ISSUE TITLE
Trajectory analysis problem

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#341]
Hi timoast

I have a question.

When I draw UMAP according to the standard process and rename cell clusters.
How can I subset different genealogies and create a track for each?

Thank you.

**Comment by timoast** [comment]
Not sure exactly what you mean, but you can subset the object using the `subset()` function or the `[` operator. There are examples of how to do this shown in the vignettes: https://satijalab.org/signac/articles/monocle.html

**Comment by Ping-lin14** [comment]
I’m referring to the `erythroid <- bone[,  bone$assigned_celltype %in% c("HSC", "MEP", "CMP-BMP")]` in the "building projects with monocle 3" teaching.

**Comment by timoast** [comment]
To subset objects you just need a list of cells that you want to keep, this could be manually provided or based on any metadata present in the object
