### ISSUE TITLE
Gene Activity

### ISSUE THREAD

**Issue by craiga02** [timoast/signac#342]
Hello, 

I have been getting the following error when I try to run the function GeneActivity:

gene.activities <- GeneActivity(obj)
Extracting gene coordinates

Error in SingleFeatureMatrix(fragment = fragments[[x]], features = features,  : 
  No matching chromosomes found in fragment file.

Thanks for your help!

**Comment by timoast** [comment]
Do the chromosome names in the fragment file match the chromosome names in the gene annotation you've stored in the object?

**Comment by craiga02** [comment]
It looks like my fragments file has chr and the annotation file does not. Do you know of a way I can add chr to the annotation file?

gzip -cd fragments.tsv.gz | head
chr1	10065	10124	TTGTTCAAGGAATGGA-12	2
chr1	10067	10197	GCGAGAATCATTCTTG-14	1
chr1	10073	10204	GACTAGTGTCGTAATC-5	1
chr1	10079	10279	TACGCCTTCCACCTAC-5	2
chr1	10079	10321	TTCTAACAGAGCCACA-8	1

Annotation(obj)
GRanges object with 3021151 ranges and 5 metadata columns:
                  seqnames        ranges strand |           tx_id   gene_name
                     <Rle>     <IRanges>  <Rle> |     <character> <character>
  ENSE00001489430        X 276322-276394      + | ENST00000399012      PLCXD1
  ENSE00001536003        X 276324-276394      + | ENST00000484611      PLCXD1
  ENSE00002160563        X 276353-276394      + | ENST00000430923      PLCXD1
  ENSE00001750899        X 281055-281121      + | ENST00000445062      PLCXD1
  ENSE00001489388        X 281192-281684      + | ENST00000381657      PLCXD1

**Comment by timoast** [comment]
You need to change the seqlevelStyle to UCSC. See the examples in the vignettes: https://satijalab.org/signac/articles/pbmc_vignette.html

**Comment by yankiven** [comment]
the chromosome names in the fragment file match the chromosome names in the gene annotation, I also meet the error!! please help me.
> gene.coords
GRanges object with 55801 ranges and 13 metadata columns:
          seqnames            ranges strand |     source     type     score
             <Rle>         <IRanges>  <Rle> |   <factor> <factor> <numeric>
      [1]     Chr1        2903-10817      + | 1r7     gene        NA
      [2]     Chr1       11218-12435      + | 1r7     gene        NA
      [3]     Chr1       12648-15915      + | 1r7     gene        NA
      [4]     Chr1       16292-20323      + |1r7     gene        NA
      [5]     Chr1       22841-26971      + | 1r7     gene        NA
      ...      ...               ...    ... .        ...      ...       ...
  [55797]    Chr12 27491864-27493254      + | 1r7     gene        NA
  [55798]    Chr12 27494401-27508851      - | 1r7     gene        NA
  [55799]    Chr12 27512303-27513821      + | 1r7     gene        NA
  [55800]    Chr12 27513939-27518251      - | 1r7     gene        NA
  [55801]    Chr12 27524980-27529682      - | 1r7     gene        NA

fragment.tsv
Chr1    994     1271    GTGTCAAGTAGAAGCC-1      1
Chr1    995     1177    ATAGGCTTCGGTCAGC-1      2
Chr1    1001    1076    CATTCATCACAAACGG-1      4
Chr1    1001    1077    GTGTCCTCACTACACA-1      5
Chr1    1001    1078    TCCATCGAGTCCCTCT-1      1
Chr1    1001    1081    TCACAAGTCGCATACA-1      1
Chr1    1001    1083    GGAGTAGTCCAGCACG-1      6
Chr1    1001    1084    TCGGGACGTAAACGTA-1      6
Chr1    1001    1086    GTGGCGTTCGATCTTT-1      1
