### ISSUE TITLE
Fragment path no longer appears changeable

### ISSUE THREAD

**Issue by Connorr0** [timoast/signac#344]
I have been unable to find the new function for changing the fragment path after updates. I was trying UpdatePath() but that gave the following error:

```
> DefaultAssay(d53_ATAC_sub) = "peaks"
> UpdatePath(d53_ATAC_sub, new.path = "R:/Genomics/scATAC-seq/scATAC_10_16_2020/SCA6_d53_Macs2_reanalysis/outs/fragments.tsv.gz")
Error in slot(object = object, name = slot) : 
  no slot of name "path" for this object of class "Seurat"
```

**Comment by timoast** [comment]
The `object` argument should be a `Fragment` object rather than a `Seurat` object. See the documentation for UpdatePath: https://satijalab.org/signac/reference/UpdatePath.html

**Comment by Connorr0** [comment]
How do I get to the object?

Would this work: 

UpdatePath(object@assays$peaks@fragments, 'somePath/fragments.tsv.gz')

**Comment by timoast** [comment]
```r
frags <- Fragments(object)[[1]] # assuming there's only one fragment object in the assay
frags <- UpdatePath(frags, ...)

# replace old fragment object
Fragments(object) <- NULL
Fragments(object) <- frags
```

**Comment by Connorr0** [comment]
Thank!
