### ISSUE TITLE
CallPeaks using different cells and fragments.tsv.gz file

### ISSUE THREAD

**Issue by guoyanzhao** [timoast/signac#349]
Hi Tim,

I am trying CallPeaks function using fragments.tsv.gz file as you suggested in #261 . The function worked. However, it seems it is using fragments from all cells instead of selected cells for peak calling. I tried to select subset of cells to perform peak calling. I got the same number of peaks no matter how many cells I choose. Is this a bug? Or there is something wrong with my code? Thank you for looking into this issue!

Here is the code I used. 
FragmentFile_mFin1 <- "./fragments.tsv.gz"
TotalFragments_mFin1 <- CountFragments(fragments = FragmentFile_mFin1)
cells.use_mFin1 <- as.character(TotalFragments_mFin1[TotalFragments_mFin1$frequency_count > 1000, "CB"])

or: 
 cells.use_mFin1 <- as.character(TotalFragments_mFin1[TotalFragments_mFin1$frequency_count > 5000, "CB"])

Obj_fragments_mFin1 <- CreateFragmentObject(path = FragmentFile_mFin1, cells.use_mFin1)

mFin1_SignacPeaks <- CallPeaks(Obj_fragments_mFin1, macs2.path = "/opt/apps/python2/bin/macs2", outdir = "/Peak_calling_output" )

Thanks!

**Comment by timoast** [comment]
If `group.by=NULL` (the default), the whole fragment file will be used when calling peaks. To use only cells present in the object you should be able to set the `group.by` argument to anything in the metadata that includes all the cells. For example:

```r
obj$allcells <- "all"
peaks <- CallPeaks(obj, group.by = "allcells")
```

I haven't actually tried this but I think it should work. It would create a new temporary fragment file only containing cells in the object, then call peaks using that file.

**Comment by guoyanzhao** [comment]
Hi Tim, 
Sorry for the late reply. I tried your suggestion. I have to first go through the steps of creating ChromatinAssay and Seurat object in order to add metadata and do peak calling using cells of interest. Is it possible to directly call peaks using only cells used for constructing the fragment object (only cells have TotalFragments_mFin1$frequency_count > 1000)?

**Comment by guoyanzhao** [comment]
Hi Tim,
I posted a follow up question after you closed this issue. I don't know whether you saw it. Here is the post. Could you please help? Thank you!

Hi Tim,
Sorry for the late reply. I tried your suggestion. I have to first go through the steps of creating ChromatinAssay and Seurat object in order to add metadata and do peak calling using cells of interest. Is it possible to directly call peaks using only cells used for constructing the fragment object (only cells have TotalFragments_mFin1$frequency_count > 1000)?
Best,Guoyan
    On Tuesday, December 8, 2020, 06:47:55 AM CST, Tim Stuart <notifications@github.com> wrote:  
 
 


Closed #349.

**Comment by timoast** [comment]
If you want to use a subset of cells, you'll need to create the Seurat object and ChromatinAssay first

**Comment by guoyanzhao** [comment]
Thank you for your explanation Tim.
    On Thursday, January 7, 2021, 07:57:13 AM CST, Tim Stuart <notifications@github.com> wrote:  
 
 


If you want to use a subset of cells, you'll need to create the Seurat object and ChromatinAssay first
