### ISSUE TITLE
Use MACS2 called peaks to FindMarkers

### ISSUE THREAD

**Issue by drlaurenwasson** [timoast/signac#351]
Hello,
I am writing because I was able to Call Peaks using MACS2 on my object. This is an excellent upgrade to the default Peaks, and I wanted to know if I could use the MACS2 peaks in the context of FindMarkers, to find peaks that are differentially expressed between my clusters. 

pbmc<- pbmc_atac
DefaultAssay(pbmc) <- 'peaks'
testpeaks<- CallPeaks(object = pbmc, group.by = "pred_cell_type", macs2.path = "/n/app/macs2/2.1.1.20160309/bin/macs2")

I have a GRanges file now called testpeaks that has the peaks, and the column "peak_called_in" which is a character vector containing my groups ("pred_cell_type"), but I would love to be able to incorporate these peaks into FindMarkers.

Is this possible?
Thanks
Lauren

**Comment by timoast** [comment]
Yes, you just need to quantify the peaks and create a new assay. See an example here: https://satijalab.org/signac/articles/pbmc_multiomic.html#peak-calling

**Comment by drlaurenwasson** [comment]
This does work, but I was wondering about the order of events here:

I have a joint Seurat object from eight different samples. I had no trouble before merging them together and using Harmony to normalize. I had called peaks on the joint object.  The group.by parameter was based on cell type, not the sample. 

DefaultAssay(pbmc) <- 'peaks'
testpeaks2<- CallPeaks(object = pbmc, group.by = "pred_cell_type", macs2.path = "/n/app/macs2/2.1.1.20160309/bin/macs2", outdir = "/n/data1/hms/genetics/seidman/lauren/scATAC/MACS", combine.peaks = FALSE, cleanup = FALSE)

macs2_counts <- FeatureMatrix(
  fragments = Fragments(pbmc),
  features = peaks,
  cells = colnames(pbmc)
)

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"


pbmc[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
#  fragments = fragpath,
  annotation = annotation
)

> pbmc$peaks
ChromatinAssay data with 244740 features for 13198 cells
Variable features: 244740 
Genome: 
Annotation present: TRUE 
Motifs present: FALSE 
Fragment files: 0 

pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'patient',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE
)


# re-compute the UMAP using corrected LSI embeddings
pbmc <- FindNeighbors(object = pbmc, reduction = "harmony", dims = c(2:30))
pbmc <- FindClusters(object = pbmc, resolution = 1.0)
pbmc <- RunUMAP(object = pbmc, reduction = "harmony", dims = c(2:30))

DimPlot(object = pbmc, label = TRUE) + NoLegend()
ggsave("MACS/scATAC_ClusterID_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'region')
ggsave("MACS/scATAC_region_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'patient')
ggsave("MACS/scATAC_patient_afterharmony.png")



Now, I want to use this new peak set to Harmonize, but because I have no fragments, Harmony doesn't work anymore? It converges after two iterations and the plots look the same as they did before harmonization. My questions then are:

Should I call peaks and create a new chromatin assay before joining them? I would obviously lose peaks because there would be much fewer cells in each individual object. If I provide a list of fragment paths I get this error:

Computing hash
Error in validateCells(fragments = filepath, cells = cells, find_n = find_n,  : 
  Expecting a single string value: [type=character; extent=8].
In addition: Warning messages:
1: In if (nchar(x = fragments) > 0) { :
  the condition has length > 1 and only the first element will be used
2: In if (!file.exists(path) & !is.remote) { :
  the condition has length > 1 and only the first element will be used
3: In if (!file.exists(index.file) & !is.remote) { :
  the condition has length > 1 and only the first element will be used
4: In if (!is.remote) { :
  the condition has length > 1 and only the first element will be used
5: In if (is.remote) { :
  the condition has length > 1 and only the first element will be used

**Comment by drlaurenwasson** [comment]
This does work, but I was wondering about the order of events here:

I have a joint Seurat object from eight different samples. I had no trouble before merging them together and using Harmony to normalize. I had called peaks on the joint object. The group.by parameter was based on cell type, not the sample.

DefaultAssay(pbmc) <- 'peaks'
testpeaks2<- CallPeaks(object = pbmc, group.by = "pred_cell_type", macs2.path = "/n/app/macs2/2.1.1.20160309/bin/macs2", outdir = "/n/data1/hms/genetics/seidman/lauren/scATAC/MACS", combine.peaks = FALSE, cleanup = FALSE)

macs2_counts <- FeatureMatrix(
  fragments = Fragments(pbmc),
  features = peaks,
  cells = colnames(pbmc)
)

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"


pbmc[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
#  fragments = fragpath,
  annotation = annotation
)

> pbmc$peaks
ChromatinAssay data with 244740 features for 13198 cells
Variable features: 244740
Genome:
Annotation present: TRUE
Motifs present: FALSE
Fragment files: 0

pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'patient',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE
)


# re-compute the UMAP using corrected LSI embeddings
pbmc <- FindNeighbors(object = pbmc, reduction = "harmony", dims = c(2:30))
pbmc <- FindClusters(object = pbmc, resolution = 1.0)
pbmc <- RunUMAP(object = pbmc, reduction = "harmony", dims = c(2:30))

DimPlot(object = pbmc, label = TRUE) + NoLegend()
ggsave("MACS/scATAC_ClusterID_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'region')
ggsave("MACS/scATAC_region_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'patient')
ggsave("MACS/scATAC_patient_afterharmony.png")



Now, I want to use this new peak set to Harmonize, but because I have no fragments, Harmony doesn't work anymore? It converges after two iterations and the plots look the same as they did before harmonization. My questions then are:

Should I call peaks and create a new chromatin assay before joining them? I would obviously lose peaks because there would be much fewer cells in each individual object. If I provide a list of fragment paths I get this error:


pbmc[["peaks"]] <- CreateChromatinAssay(

counts = macs2_counts,

fragments = c("/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_RV_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_RA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_LV_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_RA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_AP_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_LA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_SP_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_AP_ATAC/outs/fragments.tsv.gz”),

 annotation = annotation)

Computing hash

Error in validateCells(fragments = filepath, cells = cells, find_n = find_n, :
Expecting a single string value: [type=character; extent=8].
In addition: Warning messages:
1: In if (nchar(x = fragments) > 0) { :
the condition has length > 1 and only the first element will be used
2: In if (!file.exists(path) & !is.remote) { :
the condition has length > 1 and only the first element will be used
3: In if (!file.exists(index.file) & !is.remote) { :
the condition has length > 1 and only the first element will be used
4: In if (!is.remote) { :
the condition has length > 1 and only the first element will be used
5: In if (is.remote) { :
the condition has length > 1 and only the first element will be used



On Dec 3, 2020, at 10:10 AM, Tim Stuart <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes, you just need to quantify the peaks and create a new assay. See an example here: https://satijalab.org/signac/articles/pbmc_multiomic.html#peak-calling<https://urldefense.proofpoint.com/v2/url?u=https-3A__satijalab.org_signac_articles_pbmc-5Fmultiomic.html-23peak-2Dcalling&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=xb3nfGLd3sm-px55ElcHTv9YFLAYPalNSu9ZZGrz7cc&m=QeROKV_QjncC9I8Rc_GMQUUR5ASB_rZ5nqNdEPUNqMU&s=XdyS4mlwKCA2jmgYIaOAU8G852wzxu5qumRiCgloH4I&e=>

**Comment by drlaurenwasson** [comment]
Hi,
Thanks, but I figured it out.
If I set fragments to Fragments(pbmc) like in the featurematrix, this seems to work now.
Thanks
Lauren

On Dec 3, 2020, at 3:26 PM, Wasson, Lauren Kristen <Lauren_Wasson@hms.harvard.edu<mailto:Lauren_Wasson@hms.harvard.edu>> wrote:


This does work, but I was wondering about the order of events here:

I have a joint Seurat object from eight different samples. I had no trouble before merging them together and using Harmony to normalize. I had called peaks on the joint object. The group.by parameter was based on cell type, not the sample.

DefaultAssay(pbmc) <- 'peaks'
testpeaks2<- CallPeaks(object = pbmc, group.by = "pred_cell_type", macs2.path = "/n/app/macs2/2.1.1.20160309/bin/macs2", outdir = "/n/data1/hms/genetics/seidman/lauren/scATAC/MACS", combine.peaks = FALSE, cleanup = FALSE)

macs2_counts <- FeatureMatrix(
  fragments = Fragments(pbmc),
  features = peaks,
  cells = colnames(pbmc)
)

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"


pbmc[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
#  fragments = fragpath,
  annotation = annotation
)

> pbmc$peaks
ChromatinAssay data with 244740 features for 13198 cells
Variable features: 244740
Genome:
Annotation present: TRUE
Motifs present: FALSE
Fragment files: 0

pbmc <- RunHarmony(
  object = pbmc,
  group.by.vars = 'patient',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE
)


# re-compute the UMAP using corrected LSI embeddings
pbmc <- FindNeighbors(object = pbmc, reduction = "harmony", dims = c(2:30))
pbmc <- FindClusters(object = pbmc, resolution = 1.0)
pbmc <- RunUMAP(object = pbmc, reduction = "harmony", dims = c(2:30))

DimPlot(object = pbmc, label = TRUE) + NoLegend()
ggsave("MACS/scATAC_ClusterID_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'region')
ggsave("MACS/scATAC_region_afterharmony.png")

DimPlot(object = pbmc, reduction = 'umap', group.by = 'patient')
ggsave("MACS/scATAC_patient_afterharmony.png")



Now, I want to use this new peak set to Harmonize, but because I have no fragments, Harmony doesn't work anymore? It converges after two iterations and the plots look the same as they did before harmonization. My questions then are:

Should I call peaks and create a new chromatin assay before joining them? I would obviously lose peaks because there would be much fewer cells in each individual object. If I provide a list of fragment paths I get this error:


pbmc[["peaks"]] <- CreateChromatinAssay(

counts = macs2_counts,

fragments = c("/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_RV_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_RA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_LV_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_RA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_AP_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0035_LA_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_SP_ATAC/outs/fragments.tsv.gz", "/n/data1/hms/genetics/seidman/DeLaughter/pipeline/H0025_AP_ATAC/outs/fragments.tsv.gz”),

 annotation = annotation)

Computing hash

Error in validateCells(fragments = filepath, cells = cells, find_n = find_n, :
Expecting a single string value: [type=character; extent=8].
In addition: Warning messages:
1: In if (nchar(x = fragments) > 0) { :
the condition has length > 1 and only the first element will be used
2: In if (!file.exists(path) & !is.remote) { :
the condition has length > 1 and only the first element will be used
3: In if (!file.exists(index.file) & !is.remote) { :
the condition has length > 1 and only the first element will be used
4: In if (!is.remote) { :
the condition has length > 1 and only the first element will be used
5: In if (is.remote) { :
the condition has length > 1 and only the first element will be used



On Dec 3, 2020, at 10:10 AM, Tim Stuart <notifications@github.com<mailto:notifications@github.com>> wrote:



Yes, you just need to quantify the peaks and create a new assay. See an example here: https://satijalab.org/signac/articles/pbmc_multiomic.html#peak-calling<https://urldefense.proofpoint.com/v2/url?u=https-3A__satijalab.org_signac_articles_pbmc-5Fmultiomic.html-23peak-2Dcalling&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=xb3nfGLd3sm-px55ElcHTv9YFLAYPalNSu9ZZGrz7cc&m=QeROKV_QjncC9I8Rc_GMQUUR5ASB_rZ5nqNdEPUNqMU&s=XdyS4mlwKCA2jmgYIaOAU8G852wzxu5qumRiCgloH4I&e=>

**Comment by drlaurenwasson** [comment]
I figured it out.
I had to create the new chromatin assay as follows:

pbmc[["peaks"]] <- CreateChromatinAssay(
  counts = macs2_counts,
  fragments = Fragments(pbmc),
  annotation = annotation
)
