### ISSUE TITLE
CallPeaks MACS files overwrite each other if cleanup = FALSE

### ISSUE THREAD

**Issue by drlaurenwasson** [timoast/signac#352]
Hello,
I have an issue where I am trying to call peaks for each cluster, and save the output bed files. My code is:

testpeaks2<- CallPeaks(object = pbmc, group.by = "pred_cell_type", macs2.path = "/n/app/macs2/2.1.1.20160309/bin/macs2", outdir = "/n/data1/hms/genetics/seidman/lauren/scATAC/MACS", combine.peaks = FALSE, cleanup = FALSE)

Because I grouped by "pred_cell_type", it will call peaks for each one, and write the output to the out directory specified. However, in my output directory I only have three files:
SeuratProject_peaks.narrowPeak
SeuratProject_peaks.xls
SeuratProject_summits.bed

For each of my pred_cell_type calls, R outputs:
Call peaks for each chromosome... 
INFO  @ Wed, 02 Dec 2020 14:42:44: #4 Write output xls file... n/data1/hms/genetics/seidman/lauren/scATAC/MACS/SeuratProject_peaks.xls 
INFO  @ Wed, 02 Dec 2020 14:42:47: #4 Write peak in narrowPeak format file... n/data1/hms/genetics/seidman/lauren/scATAC/MACS/SeuratProject_peaks.narrowPeak 
INFO  @ Wed, 02 Dec 2020 14:42:47: #4 Write summits bed file... n/data1/hms/genetics/seidman/lauren/scATAC/MACS/SeuratProject_summits.bed 

so it overwrites every time, and the only file I have is for the last pred_cell_type.

Is there a way to fix this?
Thanks
Lauren

**Comment by timoast** [comment]
What's the output of `levels(pbmc$pred_cell_type)`?

**Comment by timoast** [comment]
This should be fixed now on the current develop version. See the website for installation instructions: https://satijalab.org/signac/articles/install.html#development-version-1
