### ISSUE TITLE
GetGRangesFromEnsDb() not including all genes?

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#354]
I am trying to align the genome of scATAC data with the genome of scRNA data.  The scRNA data was aligned to ensembl 98 and the seurat object has 36601 features.  However, when I use GetGrangesFromEnsDb() on my EnsDb object, it only has 19999 genes.  Why is this? Code below: 

```
ah = AnnotationHub()
ah <- subset(ah, species == "Homo sapiens")
qgrc <- query(ah, "GRCh38")

which(qgrc$title=="Homo_sapiens.GRCh38.98.gtf")
qgrc[204,] 
atac.annots <- ensDbFromAH(ah["AH75393"])
atac.annots<-EnsDb(atac.annots)

annotations <-GetGRangesFromEnsDb(ensdb = atac.annots)
length(unique(annotations$gene_id))
[1] 19999

#snRNA Data
length(rownames(snRNA))
[1] 36601
```

**Comment by timoast** [comment]
As stated in the [documentation](https://satijalab.org/signac/reference/GetGRangesFromEnsDb.html), `GetGRangesFromEnsDb` applies [`biovizBase::crunch`](https://www.rdocumentation.org/packages/biovizBase/versions/1.20.0/topics/crunch) to all chromosomes in the supplied input. There are additional parameters to determine which biotypes are kept.
