### ISSUE TITLE
About QC 

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#356]
Hi timoast

In teaching, do the QC standards have different standards in different tissues, such as PBMC versus tumor tissue? Or just remove those abnormal cells that are too different?
And I have a merged data with one The pct_reads_in_peaks of most cells are lower than 15. Is it necessary to remove it?

Thanks.

**Comment by timoast** [comment]
The QC thresholds used should be tailored to each dataset. 15% reads in peaks is quite low, and could indicate an issue with peak calling accuracy
