### ISSUE TITLE
Compiler error when install package Signac

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#357]
Hi @timoast,
    i want to install the latest package Signac, but it occurred error like C++ compiler error.
    The detail showing below,
    install.packages('Signac')
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4: Error: The deleted function'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>& )'
  {::new((void *)__p) _Up(std::forward<_Args>(__args)...);}
    ^
In file included from split.cpp:4:0:
/usr/include/c++/4.8.2/fstream:599:11: Note:'std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_ofstream: public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: Error: used deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ 
      It was weird to showing this error in the packages of setup.
      The miniconda env can solved this issue, but the local env be obstructed by the Error: The deleted function'
        Any kindly help would be appreciated
       Best,
       hanhuihong

  The info:
![image](https://user-images.githubusercontent.com/41668708/101318166-d6839a00-389a-11eb-9b27-b483ef5f1ad0.png)

**Comment by timoast** [comment]
Fixed on the develop branch. See #326

**Comment by honghh2018** [comment]
Thanks @timoast, it had solved for your kindly help.
