### ISSUE TITLE
How to find all peaks with min.pct = 0.05

### ISSUE THREAD

**Issue by minjunp** [timoast/signac#358]
Hi Tim,

I am using FindMarkers to identify significant differential accessible peaks from scATAC-seq data. We are using min.pct = 0.05 and logfc.threshold = 0.25 as cut-offs. However, this analysis obviously ignores all sites that are shared (logfc.threshold < 0.25). We are interested in also knowing the number of peaks that are shared between the two groups, i.e. those with a min.pct = 0.05, but not significantly different:

FindMarkers(data, ident.1 = "ident1",
                       ident.2 = "ident2",
                       min.pct = 0.05,
                       assay = "peaks",
                       test.use = "LR",
                       latent.vars = "peak_region_fragments",
                       logfc.threshold = 0)

However, this test would take us nearly 2 hours to run, just to get the list of peaks with a min.pct = 0.05. Is there a way to pull this information before passing it to FindMarkers for differential testing?

Thank you,

Minjun

**Comment by timoast** [comment]
See the [`FoldChange`](https://satijalab.org/signac/reference/FoldChange.html) function

**Comment by jeffsteimle** [comment]
Hi Tim,
I work with Minjun. The FoldChange function is actually better than what we were originally planning. 
Thank you for pointing us in the right direction!
Jeff
