### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#359]
Hi timoast

I want to install Signac on our server, but I receive the following error, can you help me solve it?
 `if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("timoast/signac", ref = "develop")`

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/pinglin/R/x86_64-pc-linux-gnu-library/4.0/jpeg/libs/jpeg.so':
  /home/pinglin/R/x86_64-pc-linux-gnu-library/4.0/jpeg/libs/jpeg.so: invalid ELF header
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Signac’
* removing ‘/home/pinglin/R/x86_64-pc-linux-gnu-library/4.0/Signac’
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpw47J46/file177368bb2102/Signac_1.1.0.9006.tar.gz’ had non-zero exit status

**Comment by timoast** [comment]
It looks like there's a problem with the installation of `jpeg`. You should reinstall `jpeg`, and any other packages that give a similar error message
