### ISSUE TITLE
Tutorial suggestion

### ISSUE THREAD

**Issue by kwells4** [timoast/signac#36]
Under QC for your tutorial (for both mouse brain and PBMCs) you compute percent reads in peaks with the following

```{r}
pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$total * 100
```

Based on reading about the singlecell.csv file output by cell ranger (https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/singlecell) I believe that this line should instead be

```{r}
pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
```

The total refers to all read pairs, which includes duplicates and other non-usable reads. The passed_filters should be more accurate as these don't include duplicate and low-quality reads. Using the total will give artificially low values for the percent of reads in peaks.

Overall, thanks for making this package! I've been impressed with Seurat for single cell RNA and am looking forward to using tools from your group for single cell ATAC as well.

**Comment by timoast** [comment]
Hi, thanks for pointing this out, you're right that we should use the deduplicated count rather than all reads. I'll update the vignettes soon.

**Comment by timoast** [comment]
This has been updated now on the website
