### ISSUE TITLE
Error after gene activity matrix

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#367]
Hi @timoast ,

I am using the v1 version of Signac after using the previous ones with no problem However, with the new version after running the gen activity matrix there is a problem that all the RNA values are 0. I have read #205 but I do not understand what I would change in the script. Could you help me understand what I should change?

Anyway, the coverage plot works perfectly, but not the RNA assay results. I do not understand why. I am attaching the script.

Thank you very much for your help in advance.

Aitor

##################################
# read in peak sets
peaks.dr <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-R/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.dl <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-L/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.wr <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-R/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.wl <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-L/outs/peaks.bed",
  col.names = c("chr", "start", "end")
)

# convert to genomic ranges
gr.dr <- makeGRangesFromDataFrame(peaks.dr)
gr.dl <- makeGRangesFromDataFrame(peaks.dl)
gr.wr <- makeGRangesFromDataFrame(peaks.wr)
gr.wl <- makeGRangesFromDataFrame(peaks.wl)

# Create a unified set of peaks to quantify in each dataset
combined.peaks <- reduce(x = c(gr.dr, gr.dl, gr.wr, gr.wl))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks
##################

# load metadata

md.dr <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-R/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ] # remove the first row

md.dl <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-L/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.wr <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-R/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.wl <- read.table(
  file = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-L/outs/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

# # perform an initial filtering of low count cells
md.dr <- md.dr[md.dr$passed_filters > 500, ]
md.dl <- md.dl[md.dl$passed_filters > 500, ]
md.wr <- md.wr[md.wr$passed_filters > 500, ]
md.wl <- md.wl[md.wl$passed_filters > 500, ]

# create fragment objects

frags.dr <- CreateFragmentObject(
  path = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-R/outs/fragments.tsv.gz",
  cells = rownames(md.dr)
)

frags.dl <- CreateFragmentObject(
  path = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2D-L/outs/fragments.tsv.gz",
  cells = rownames(md.dl)
)

frags.wr <- CreateFragmentObject(
  path = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-R/outs/fragments.tsv.gz",
  cells = rownames(md.wr)
)

frags.wl <- CreateFragmentObject(
  path = "/home/aanduez/Desktop/scATACseq/Cell_ranger/2W-L/outs/fragments.tsv.gz",
  cells = rownames(md.wl)
)

#Quantify peaks in each dataset
pbmcdr.counts <- FeatureMatrix(
  fragments = frags.dr,
  features = combined.peaks,
  cells = rownames(md.dr)
)

pbmcdl.counts <- FeatureMatrix(
  fragments = frags.dl,
  features = combined.peaks,
  cells = rownames(md.dl)
)

pbmcwr.counts <- FeatureMatrix(
  fragments = frags.wr,
  features = combined.peaks,
  cells = rownames(md.wr)
)

pbmcwl.counts <- FeatureMatrix(
  fragments = frags.wl,
  features = combined.peaks,
  cells = rownames(md.wl)
)

#Create the objects
pbmcdr_assay <- CreateChromatinAssay(pbmcdr.counts, fragments = frags.dr)
pbmcdr <- CreateSeuratObject(pbmcdr_assay, assay = "ATAC")

pbmcdl_assay <- CreateChromatinAssay(pbmcdl.counts, fragments = frags.dl)
pbmcdl <- CreateSeuratObject(pbmcdl_assay, assay = "ATAC")

pbmcwr_assay <- CreateChromatinAssay(pbmcwr.counts, fragments = frags.wr)
pbmcwr <- CreateSeuratObject(pbmcwr_assay, assay = "ATAC")

pbmcwl_assay <- CreateChromatinAssay(pbmcwl.counts, fragments = frags.wl)
pbmcwl <- CreateSeuratObject(pbmcwl_assay, assay = "ATAC")

#Merge objects
# add information to identify dataset of origin
pbmcdr$dataset <- '2D-R'
pbmcdl$dataset <- '2D-L'
pbmcwr$dataset <- '2W-R'
pbmcwl$dataset <- '2W-L'

# merge all datasets, adding a cell ID to make sure cell names are unique
combined <- merge(
  x = pbmcdr,
  y = list(pbmcdl, pbmcwr, pbmcwl),
  add.cell.ids = c("2D-R", "2D-L", "2W-R", "2W-L")
)
combined[["ATAC"]]

#Non-liner Dimentional reduction
combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 'q0')
combined <- RunSVD(combined)
combined <- RunUMAP(object = combined, reduction = 'lsi', dims = 2:30)
combined <- FindNeighbors(object = combined, reduction = 'lsi', dims = 2:30)
combined <- FindClusters(object = combined, verbose = FALSE, algorithm = 3, resolution = 0.4)
DimPlot(object = combined, label = TRUE) + NoLegend()
#######################################
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)

# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"

# add the gene information to the object
Annotation(combined) <- annotations

################
# compute gene activities
gene.activities <- GeneActivity(combined)

# add the gene activity matrix to the Seurat object as a new assay
combined[['RNA']] <- CreateAssayObject(counts = gene.activities)
combined <- NormalizeData(
  object = combined,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(combined$nCount_RNA)
)
DefaultAssay(combined) <- 'RNA'
VlnPlot(
  object = combined,
  features = c('Cdh5','Pecam1',"Icam2","Cldn5")
)
DefaultAssay(combined) <- 'ATAC'
CoveragePlot(
  object = combined,
  region = c("Cdh5"),
  extend.upstream = 1000,
  extend.downstream = 1000,
  ncol = 1
)

**Comment by timoast** [comment]
This is fixed in the latest release. Update Signac to solve this issue
