### ISSUE TITLE
Are tile plots made from normalized fragment counts?

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#368]
My coverage plot shows clear upregulation of a differentially accessible peak, while my tile plot looks like the peak is downregulated.  Could this be because the tile plots are made from raw fragment files rather than normalized fragments?

Coverage plot:
![image](https://user-images.githubusercontent.com/65676131/102527607-56fc8480-406b-11eb-80c7-e5371c369403.png)

Tile plot: 
![image](https://user-images.githubusercontent.com/65676131/102527681-75fb1680-406b-11eb-89d7-196bfcf8abed.png)

**Comment by timoast** [comment]
The tile plot shows the raw count of Tn5 insertions within each tile, for the top _n_ cells (`tile.cells` parameter) sorted by total number of fragments in the region. See the documentation for more
