### ISSUE TITLE
TSSEnrichment() issue

### ISSUE THREAD

**Issue by Soap4** [timoast/signac#374]
Hello, can you help me with this problem :
         I got an error when i used the TSSEnrichment() function:
> pbmc <- TSSEnrichment(object = pbmc, fast = F)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  : 
  attempt to set 'colnames' on an object with less than two dimensions

**Comment by rajib100bd** [comment]
Facing the same problem here while working with the ATAC seq data following the vignette (Signac 1.1.0)

`> pbmc_ATAC_A1SM1_trial2 <- TSSEnrichment(object = pbmc_ATAC_A1SM1_trial2, fast = FALSE)
Extracting TSS positions
Finding + strand cut sites
Finding - strand cut sites
Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  : 
  attempt to set 'colnames' on an object with less than two dimensions`

Any suggestions?

**Comment by timoast** [comment]
This would happen if no fragments are found in the set of TSS regions. We'll work on some better error handling here, but it suggests that the wrong TSS sites might be being used. I'd suggest double-checking that the correct set of gene annotations are being used for the genome that the data was mapped to.

**Comment by Soap4** [comment]
> This would happen if no fragments are found in the set of TSS regions. We'll work on some better error handling here, but it suggests that the wrong TSS sites might be being used. I'd suggest double-checking that the correct set of gene annotations are being used for the genome that the data was mapped to.

Thank u so much. I will be looking into that.

**Comment by timoast** [comment]
I'll close this now, if you're sure the gene annotations are correct and are still having issues, you can reopen

**Comment by hoondy** [comment]
> I'll close this now, if you're sure the gene annotations are correct and are still having issues, you can reopen

I am still having this issue (Signac 1.2.0). Genome annotations are correct but I am still getting the same error as above. Any suggestions? FYI, the same code worked in **Signac_1.1.0.9005** several months ago.

```
obj <- TSSEnrichment(obj, fast=F)

Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) - : attempt to set 'colnames' on an object with less than two dimensions
Traceback:

1. TSSEnrichment(obj, fast = F)
2. CreateRegionPileupMatrix(object = object, regions = tss.positions, 
 .     assay = assay, cells = cells, verbose = verbose)
3. `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) - 
 .     midpoint)
4. stop("attempt to set 'colnames' on an object with less than two dimensions")
```
