### ISSUE TITLE
Error message with TSSEnrichment()

### ISSUE THREAD

**Issue by martychat** [timoast/signac#377]
This is the error message I'm getting on trying to do QC for my 10x multiomics dataset:

Extracting TSS positions
Error in strand[[1]] : subscript out of bounds
In addition: Warning messages:
1: In min(start) : no non-missing arguments to min; returning Inf
2: In max(end) : no non-missing arguments to max; returning -Inf

Any suggestion as to how it can be fixed?

**Comment by timoast** [comment]
Closing this as the gene annotations here are not formatted correctly, based on your previous issue
