### ISSUE TITLE
Coverage in peak for a particular cell 

### ISSUE THREAD

**Issue by AnjaliC4** [timoast/signac#378]
Hi, thanks for this awesome tool and happy new year!
I am wondering if there is a way to plot coverage in a peak of one or few cells by their barcode name? For example, I may be interested in plotting normalized coverage in XIST gene or its respective peak coordinates of a cell with barcode name lets say "CAGTCCGGATCAATGC". I know it can be done with clusters, but not sure if can be plotted by specifying one or two cells?
If not, could you please add this functionality that extracts a particular barcode name from the count matrix stored in signac object and plots its accessibility in a peak. 

Thank you!

**Comment by timoast** [comment]
See the [`TilePlot()`](https://satijalab.org/signac/reference/TilePlot.html) function
