### ISSUE TITLE
Z-scores of cis-regulatory elements and TF motif 

### ISSUE THREAD

**Issue by Ping-lin14** [timoast/signac#379]
Hi timoast

I want to know if there is any way in Signac to implement this paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7299161/#SD2), Fig 2-c and Fig 5-g Analysis method.

Thanks.

**Comment by timoast** [comment]
2C is a heatmap of z-scores, which you could create using `ScaleData` and `DoHeatmap`.

5G is a heatmap of averaged accessibility over pseudotime, with accessibility at each pseudotime point shown as the percentage of maximum accessibility. We don't have functionality to make smoothed heatmaps currently in Seurat/Signac and it looks like Monocle has dropped that functionality also. However, it should be fairly straightforward to do outside of Seurat/Signac by extracting the data from the object (`d <- GetAssayData(...)`), divide each row by the row maximum (` d <- d / apply(d, 1, max)`) , then create a heatmap.

**Comment by Ping-lin14** [comment]
Thank you very much for your suggestion.

For the heat map of z scores, I got this result(https://ibb.co/fqYBpJB). I want to convert the open regions of chromatin into gene names, but using `Closest Feature()` will lose logFC information. Is there any other method?

**Comment by timoast** [comment]
I don't quite understand what you're wanting to do, there's no fold-change information involved in the z-score or needed for the heatmap. `ClosestFeature()` will give you the gene annotation closest to each region, but I would caution against interpreting open chromatin regions as simply regulating the closest gene.
