### ISSUE TITLE
Why did Signac 1.10 change the direction of scaling during LSI?

### ISSUE THREAD

**Issue by XinWang19** [timoast/signac#380]
In signac 0.25, the scaling of SVD U matrix was against the direction of each cell. But in Signac 1.10, scaling was against the direction of each LSI_. The change made the LSI_1 read count-relied and meanless. In my analysis, the dimensional reduction effect of  signac 1.10 was much worse than  signac 0.25.

**Comment by timoast** [comment]
This was a bug that was fixed in version 0.2.2 (see the [release notes](https://satijalab.org/signac/news/index.html#signac-0-2-2-unreleased)). We recommend removing the first LSI component as it typically captures sequencing depth (see the vignettes for more).
