### ISSUE TITLE
Compilation failed for package 'Signac'

### ISSUE THREAD

**Issue by kelly7358** [timoast/signac#384]
To whom it may concern,
I was trying to install Signac package on my institute's server but encountered the following error messages:
error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
make: *** [split.o] Error 1
ERROR: compilation failed for package ‘Signac’

Could you please give me some hint on how to fix this problem?
Thank you very much in advance for your help!

**Comment by timoast** [comment]
This should be fixed in the current develop branch version (see #326)
