### ISSUE TITLE
Which integration vignette is most feasible

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#385]
Hi Tim,

For  scATAC I have 2 replicates each for 2 conditions/stages.
What is the best approach for integrating with **scRNA seq not from the same cells.**

1)Merge the scATAC replicates per stage
2)Followed by integration of the ATAC stages
3)Integrate with already integrated scRNAseq dataset

If the steps are correct which vignette would be most applicable for step 3 since the data was not obtained from the same cells in other words not a multiomic ATAC+GEX assay.
Do I use the Stimulated vs Control vignette implement with Seurat?

Thanks!

**Comment by timoast** [comment]
I'd suggest trying the different approaches and seeing which works best for you. You can see examples of how to integrate scATAC and scRNA in the Signac [PBMC](https://satijalab.org/signac/articles/pbmc_vignette.html) and [mouse brain](https://satijalab.org/signac/articles/mouse_brain_vignette.html) vignettes.
