### ISSUE TITLE
UNRELIABLE VALUE: Future ('future_lapply-1') unexpectedly generated random numbers 

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#386]
Scaling features for provided objects
Finding all pairwise anchors
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 24440 anchors
UNRELIABLE VALUE: Future ('future_lapply-1') unexpectedly generated random numbers without specifying argument '[future.]seed'. There is a risk that those random numbers are not statistically sound and the overall results might be invalid. To fix this, specify argument '[future.]seed', e.g. 'seed=TRUE'. This ensures that proper, parallel-safe random numbers are produced via the L'Ecuyer-CMRG method. To disable this check, use [future].seed=NULL, or set option 'future.rng.onMisuse' to "ignore".

I got this error when running FindIntegrationAnchors() function in the scATAC-seq data integration vignette.
What can I do to get past it?
Is it happening because I loaded the library(future) to merge samples?

Thanks!

**Comment by timoast** [comment]
See https://github.com/satijalab/seurat/issues/3622
