### ISSUE TITLE
Error message for CreateChromatinAssay min.cells argument

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#387]
Just noticed that setting min.cells so high that no features fulfilled the constraint leads to an error regarding dgCMatrix dimnames. See below. While logical why, don't know if you want to consider more informative error there. Took some testing to validate that this was the reason behind the error.

Error in dimnamesGets(x, value) : 
  invalid dimnames given for "dgCMatrix" object

**Comment by timoast** [comment]
Thanks, this is a good point and I've now added more informative error messages to the next release
