### ISSUE TITLE
Calling gene activity on integrated dataset

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#388]
> Annotation(integrated) <- annotations
Error in UseMethod(generic = "Annotation<-", object = object) : 
  no applicable method for 'Annotation<-' applied to an object of class "Assay"

How can i annotate the integrated object? It sees it as an object of Class Assay. 

Thanks!

**Comment by timoast** [comment]
I'd suggest computing gene activities prior to merging or integrating the objects
