### ISSUE TITLE
RunSVD. Centering data before doing SVD?

### ISSUE THREAD

**Issue by fransilvion** [timoast/signac#39]
Hi,

this might be a stupid question, but I am confused by the RunSVD implementation. Shouldn't we center the data first before irlba function? Or is it already done implicitly by TF-IDF normalization? And why do you normalize principal components after computing them (cell.embeddings to norm.embeddings)?

**Comment by timoast** [comment]
We don't need to scale and center the data before running SVD, and if we did we would lose the sparsity and the method would not be scalable to many cells or peaks. We use the SVD as one of the steps in LSI, you can read more about LSI [here](https://en.wikipedia.org/wiki/Latent_semantic_analysis#Mathematics_of_LSI).

The reason we standardize the embeddings is that it can help reduce the dependence of each component on sequencing depth, which is sometimes a major confounder in scATAC-seq. You might get similar results by regressing out sequencing depth too. However I now realize this is not documented, so I will add a `standardize.embedding` parameter to `RunSVD` in the next version to control whether this normalization is performed or not.

**Comment by fransilvion** [comment]
Thank you, now it makes sense
