### ISSUE TITLE
merging

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#391]
Hi Tim,
I have a few ATACseq fragment files that I want to merge. I looked at the emerging tutorial, and I noticed you are using a bed file. I just wanted to make sure that the bed file is similar to the name of the peaks which could be extracted from the fragment file?

**Comment by timoast** [comment]
Sorry I don't understand the question, what bed file are you referring to? Can you explain a bit more...not sure what is meant by "name of peaks which could be extracted from the fragment file"

**Comment by rojinsafavi** [comment]
```
# read in peak sets
peaks.500 <- read.table(
  file = "/home/stuartt/data/pbmc500/atac_pbmc_500_nextgem_peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.1k <- read.table(
  file = "/home/stuartt/data/pbmc1k/atac_pbmc_1k_nextgem_peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.5k <- read.table(
  file = "/home/stuartt/data/pbmc5k/atac_pbmc_5k_nextgem_peaks.bed",
  col.names = c("chr", "start", "end")
)
peaks.10k <- read.table(
  file = "/home/stuartt/data/pbmc10k/atac_pbmc_10k_nextgem_peaks.bed",
  col.names = c("chr", "start", "end")
)

# convert to genomic ranges
gr.500 <- makeGRangesFromDataFrame(peaks.500)
gr.1k <- makeGRangesFromDataFrame(peaks.1k)
gr.5k <- makeGRangesFromDataFrame(peaks.5k)
gr.10k <- makeGRangesFromDataFrame(peaks.10k)

# Create a unified set of peaks to quantify in each dataset
combined.peaks <- reduce(x = c(gr.500, gr.1k, gr.5k, gr.10k))

# Filter out bad peaks based on length
peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks
```

**Comment by rojinsafavi** [comment]
what I have is fragmnet.tsv file (similar to bed file) with the following columns
chr1    10079   10433   TATCGAGTCTTGTCGC-1      1
chr1    10091   10278   GTAGTACTCTATCCTA-1      2
chr1    10097   10285   TCGAGCGGTTCCTGTC-1      1
chr1    10129   10333   CGTACAAGTTATAGAG-1      1

**Comment by timoast** [comment]
What is your question?

**Comment by rojinsafavi** [comment]
I just wanted to make sure that the bed file you are using is similar to the fragment file I have. The reason I'm asking is that the fragment file that I have do not have three column c("chr", "start", "end"), it has 4. But I can easily extract that peak names from it and store it in a separate .bed file. Just wanted to make sure that I'm not missing something here. thanks again for your time

**Comment by timoast** [comment]
I still don't really understand the question but maybe this will help

There are two different things being shown here:
1. A fragment file, which is a coordinate-sorted, bgzip-compressed file describing the position of the two Tn5 integration events that generated a sequenced DNA fragment, the cell barcode that was associated with the fragment, and the number of times the fragment was sequenced.
2. A genomic ranges object describing the coordinates of peaks identified by MACS2 from the frequency of Tn5 insertion sites at each position in the genome

**Comment by rojinsafavi** [comment]
Okay so I think I was wrong. The bed file is the peak file after the peak calling. So I should perform peak calling on each ATAC file independently, and then do the merging correct?

**Comment by timoast** [comment]
Sure, or merge and call peaks on the merged object

**Comment by rojinsafavi** [comment]
Hi @timoast 

Sorry if I'm still a bit confused!

So I think it is easier if I merge all the objects and then do the peak calling. My question is, what is the correct way of merging objects(ATACseqs) that have not been basecalled yet? in the merging tutorial, it seems that the bed files that are provided at the beginning are from peak calling

**Comment by timoast** [comment]
> My question is, what is the correct way of merging objects(ATACseqs) that have not been basecalled yet?

I think you mean peakcalled?

The `CallPeaks()` function can take as input either (see the [docs](https://satijalab.org/signac/reference/CallPeaks.html)):
* A Seurat object containing a ChromatinAssay
* A ChromatinAssay
* A Fragment object
* A character vector containing the path to one or more fragment files

If you want to call peaks directly from the fragment file using Signac, you can supply a vector containing the path to each fragment file to include. You can then quantify the peaks using `FeatureMatrix()`, etc.
