### ISSUE TITLE
 Distance of peak from TSS 

### ISSUE THREAD

**Issue by l-magnificence** [timoast/signac#392]
When I merge the multidataset using the reduce function from GenomicRanges package as described in vignettes/merging.Rmd, how can I extract the information of  the distance of each peak from TSS in signac object to self-define peak as promoter-associaed and distal?

**Comment by timoast** [comment]
You can use functions in the `GenomicRanges` package for this (`distanceToNearest()`, for example). See the [GenomicRanges](https://bioconductor.org/packages/release/bioc/html/GenomicRanges.html) package documentation
