### ISSUE TITLE
error in "build a joint UMAP visualization"

### ISSUE THREAD

**Issue by yystl36** [timoast/signac#393]
Hello!
I am analyzing the pbmc dataset with Joint RNA and ATAC analysis using your vignette: https://satijalab.org/signac/articles/pbmc_multiomic.html

In Joint UMAP visualization, I had an error below:
> pbmc <- RunUMAP(object = pbmc, nn.name = "wknn", assay = "RNA", verbose = TRUE)
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
Error in RunUMAP.Graph(object = data.use, reduction.model = reduction.model,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).

Even after I installed umap-learn with "pip install umap-learn" in Terminal and restarted R, the error still occured.

I appreciate your help!

**Comment by timoast** [comment]
Please update uwot and make sure Seurat v4 is installed.

**Comment by yystl36** [comment]
Thank you for your comment, Tim. 
I have already installed and used updated packages, but the code above did not work.
> packageVersion("Seurat")
[1] ‘3.9.9.9026’
> packageVersion("Signac")
[1] ‘1.1.0’
> packageVersion("uwot")
[1] ‘0.1.10’

Also,RunUMAP function worked without error when I analyzed the PBMC dataset with the seurat vignette: https://satijalab.org/seurat/v4.0/weighted_nearest_neighbor_analysis.html, but it didn't work this time.

**Comment by timoast** [comment]
Can you include the full code you're running?

**Comment by yystl36** [comment]
Sure! I have attached the full code.

[error in build a joint UMAP visualization.txt](https://github.com/timoast/signac/files/5822049/error.in.build.a.joint.UMAP.visualization.txt)

**Comment by timoast** [comment]
I still wasn't able to reproduce this, I'd suggest installing the latest version of Seurat ("release/4.0.0" branch on GitHub) and Signac ("develop" branch on Github) and restarting R (making sure the environment is not saved when you restart)
