### ISSUE TITLE
Signac installation failing / "Error in GetGRangesFromEnsDb"

### ISSUE THREAD

**Issue by lramsdell** [timoast/signac#395]
Hi, I was having trouble with installing Signac on my Mac, when prompted: "Do you want to install from sources the package which needs compilation?" I kept choosing "Yes" and I got the error message that installation of Signac had non-zero exit status:

`install.packages("Signac")

  There is a binary version available but the source version is later:
       binary source needs_compilation
Signac  0.2.5  1.1.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) yes
installing the source package 'Signac'

trying URL 'https://cran.rstudio.com/src/contrib/Signac_1.1.0.tar.gz'
Content type 'application/x-gzip' length 720211 bytes (703 KB)
==================================================
downloaded 703 KB

* installing *source* package ‘Signac’ ...
** package ‘Signac’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘Signac’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Signac’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Signac’
Warning in install.packages :
  installation of package 'Signac' had non-zero exit status`

 So instead I re-installed and chose "No" and the installation seemed successful. But now when running the following code I am getting this error message: 
`> annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)
Error in GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75) : 
  could not find function "GetGRangesFromEnsDb"`

It seems like there still might be an issue with the installation

**Comment by timoast** [comment]
The package did not install, which is why you see the error about `GetGRangesFromEnsDb`. As stated in the compilation error message, you're missing `xcrun`, which suggests you're installing on a mac and haven't installed the xcode command-line tools needed. See https://stackoverflow.com/questions/52522565/git-is-not-working-after-macos-update-xcrun-error-invalid-active-developer-pa

**Comment by lramsdell** [comment]
@timoast Thank you!
