### ISSUE TITLE
Super Enhancers and Coverage Plots

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#396]
Hi,

1) The Coverage Plot subsequent to running ConnectionsToLinks is NOT showing the gene within the region specified. Have I missed a step?

2) Is there a way to show Super Enhancers using Coverage Plot or any other function?

Thanks!

**Comment by timoast** [comment]
> The Coverage Plot subsequent to running ConnectionsToLinks is NOT showing the gene within the region specified. Have I missed a step?

Did you add gene annotations to the assay? Can you include the code you're running?

> Is there a way to show Super Enhancers using Coverage Plot or any other function?

You can plot any set of additional genomic ranges using the `ranges` argument in `CoveragePlot()`. To plot super enhancer positions, pass a set of genomic ranges containing the superenhancer coordinates

**Comment by sylestiel** [comment]
CoveragePlot(combined,  annotations = TRUE, group.by = "age", region = "chr17-85584277-85788274") + theme(axis.text = element_text(size=12))

**Comment by timoast** [comment]
I'd suggest checking:

* genes in the region you're plotting
* genome build and gene annotation version match

**Comment by sylestiel** [comment]
[chromInfo.txt](https://github.com/timoast/signac/files/5816042/chromInfo.txt)

Is this sufficient for mm10 genome?

**Comment by timoast** [comment]
I'm not sure what you mean...please see the documentation on the Signac website

**Comment by sylestiel** [comment]
> # get the chromosome sizes from the Seurat object
> genome <- seqlengths(combined)
> 
> 
> # convert chromosome sizes to a dataframe
> genome.df <- data.frame("chr" = names('chr1:chr19, X, Y'), "length" = genome)
> 
> # run cicero
> conns <- run_cicero(combined.cicero, genomic_coords = genome.df, sample_num = 100)
[1] "Starting Cicero"
[1] "Calculating distance_parameter value"
Error in names(chr_maxes) <- c("V1", "V2") : 
  'names' attribute [2] must be the same length as the vector [0]

**Comment by sylestiel** [comment]
I apologize Tim. Adding gene_plot = TRUE addressed my issue.
