### ISSUE TITLE
pct_reads_in_peaks calculation

### ISSUE THREAD

**Issue by smanne07** [timoast/signac#4]
Hi,
First of all ,congratulations on the new package for scATAC.

I was trying to calculate the following on my own dataset

`brain$pct_reads_in_peaks <- brain$peak_region_fragments / brain$total * 100`

And i got the following message
`Error in `[[.Seurat`(x, i, drop = TRUE) : 
  Cannot find 'total' in this Seurat object`

Is the total calculated when CreateSeuratObject is run?

I was not able to find how it is calculated and it was missing for my dataset.

Best regards
Sasi

**Comment by timoast** [comment]
Hi, the metadata "total" that we used in the vignette comes from the 10x Genomics metadata provided with the example datasets. We add this metadata in the vignette when we create the Seurat object using the `meta.data` argument.

If you quantified your scATAC-seq using CellRanger you could do the same, and then you'll have access to columns with `peak_region_fragments` and `total`.

If you used another method to quantify your scATAC-seq, we have other functions in Signac you can use to achieve the same thing. See the bottom of the PBMC [vignette](https://satijalab.org/signac/articles/pbmc_vignette.html) for a full explanation, under "Working with datasets that were not quantified using CellRanger"

**Comment by smanne07** [comment]
Thank you Tim!
