### ISSUE TITLE
Doublet in snATAC-seq

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#40]
Hi,
I sometimes find cellular doublets in scATAC-seq dataset like scRNA-seq data. Do you know the way to efficiently remove them like doublet-finder? If the Signac had such kind of function, it would be really useful.
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, I don't know of any methods currently able to do this for snATAC-seq, but it is possible to build something using the Seurat label transfer methods. I agree that it would be useful, especially as there are no other methods for ATAC doublet removal. I unfortunately don't have much time to work on it right now but it is on my list of things to do.

**Comment by ymuto802** [comment]
Thank you Tim !
Cheers,
Yoshi
