### ISSUE TITLE
Transfer annotation from Azimuth to multiome analysis

### ISSUE THREAD

**Issue by bwang1324** [timoast/signac#400]
Hello,

Thank you for your package. I generated some multiome data on PBMC and am following the WNN tutorial. I used Azimuth on the GEX portion and now want to transfer over the cluster names to the WNN UMAP I generated at this part of the tutorial.

p1 + p2 + p3 & NoLegend() & theme(plot.title = element_text(hjust = 0.5))

First I want to run something similar to FindAllMarkers to identify cluster populations in the above WNN UMAP. Then rename according to the cluster identified via Azimuth.

Thank you,
Boya

**Comment by timoast** [comment]
I'm unsure what your specific question is. We demonstrate how to transfer cell type labels from a scRNA-seq dataset to the multiome dataset in the multiome vignette: https://satijalab.org/signac/articles/pbmc_multiomic.html#annotating-cell-types-1

Please reopen with more specific details if you're still having issues
