### ISSUE TITLE
Motif object data is empty (0 x 0 matrix)

### ISSUE THREAD

**Issue by decapicone** [timoast/signac#401]
Hello, I am performing motif footprinting analysis from the signac [footprinting vignette](https://satijalab.org/signac/articles/footprint.html).  After using `CreateMotifObject `and `SetAssayData`, the motif data slot appears to be empty.  I see information in the `pwm `, ` motif.names` and `positions `slots.  The functions `Footprint `and `PlotFootprint `seem to work, but there appears to be missing enrichment information at the motif site on the graph.

```
pwm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 9606, all_versions = FALSE)
)
motif.positions <- matchMotifs(
  pwms = pwm,
  subject = granges(bone),
  out = 'positions',
  genome = 'hg19'
)
motif <- CreateMotifObject(
  positions = motif.positions,
  pwm = pwm
)
bone <- SetAssayData(
  object = bone,
  slot = 'motifs',
  new.data = motif
)
grch38 <- getBSgenome('hg19')
bone <- Footprint(bone, 
                       genome = grch38,
                      in.peaks = TRUE,
                       motif.name = "MA1541.1"
                       )
p2 <- PlotFootprint(bone, features = "MA1541.1")
```
Additional information: 

```
bone@assays$RNA@motifs
A Motif object containing 0 motifs in 0 regions

head(bone@assays$RNA@motifs@pwm)
$MA0030.1
  [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
A    1   10   17   13    3    7    0   27   27    27     0    27    16     7
C   10    7    4    5   11    0    0    0    0     0    25     0     4     4
G    7    5    2    5    8   20    0    0    0     0     0     0     2     6
T    9    5    4    5    0    0   27    0    0     0     2     0     5    10

head(bone@assays$RNA@motifs@positions)
GRangesList object of length 6:
$MA0030.1
GRanges object with 10725 ranges and 1 metadata column:
          seqnames            ranges strand |     score
             <Rle>         <IRanges>  <Rle> | <numeric>
      [1]     chr1     713850-713863      + |   15.1362
      [2]     chr1     911203-911216      + |   12.6067
      [3]     chr1   1140326-1140339      + |   14.4963
      [4]     chr1   1294754-1294767      + |   13.4810
      [5]     chr1   1337386-1337399      + |   13.2899
```

The graph (looks like missing info where the footprint should be): 

![image](https://user-images.githubusercontent.com/77586198/104853381-725ae980-58ce-11eb-9ddc-79d7b9389465.png)

**Comment by timoast** [comment]
It's not empty, you just haven't add the motif matrix (which is not needed for foot printing). The number of motifs and number of regions shown when you print the object is the dimension of the motif matrix. There's no issue here

**Comment by decapicone** [comment]
@timoast Ok, that is reassuring.  Thank you, Tim.  And what about the graph at the bottom - why is there no enrichment information in the center where the footprint should be?

**Comment by timoast** [comment]
My guess is that there are NA values there, maybe because the data is so sparse here (0 enrichment of Tn5 in the flanking regions)
