### ISSUE TITLE
Aesthetics of Links in Coverage Plot

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#405]
How may I alter the  color of the links in the Coverage Plot  from grey-blue to something more contrasting?
scale_fill_continuous(type ="viridis") is not doing it.
This is with respect to the Links component of the CoveragePlot function.

**Comment by timoast** [comment]
To change the aesthetics you can create the link plot separately and modify it using standard `ggplot2` functions (`scale_color_viridis_c()`, etc.), then combine it with other plot elements using the `CombineTracks()` function (see here: https://satijalab.org/signac/articles/visualization.html#combining-genomic-tracks)
