### ISSUE TITLE
Transcription factor footprinting

### ISSUE THREAD

**Issue by l-magnificence** [timoast/signac#406]
When I performed motif footprinting analysis from the signac footprinting vignette in my own dataset, the motif object set in seurat was 0x0 and there occur an error in functon  PlotFootprint:  Error in (ncol(x = x) - background):ncol(x = x) : argument of length 0.
So I created motif assay directly in Motif analysis vignette , and then run footprint and PlotFootprint function, but it still occur an error: Error in (ncol(x = x) - background):ncol(x = x) : argument of length 0.

code:
tmp <- Footprint(
  object = tmp ,
  motif.name = features,
  genome = BSgenome.Hsapiens.UCSC.hg38
)
![image](https://user-images.githubusercontent.com/68798288/105147935-c79c3280-5b3c-11eb-910c-dc4142aca0b4.png)

PlotFootprint(tmp, features = features)
![image](https://user-images.githubusercontent.com/68798288/105148053-e3073d80-5b3c-11eb-9dd1-1e0b8b616efa.png)

**Comment by timoast** [comment]
Please include the full code you're running and the output of sessionInfo()

**Comment by l-magnificence** [comment]
> Please include the full code you're running and the output of sessionInfo()
I found the reason why this error occured.
One of the cell types in my data has number 1 ,so it can't extract data in GetFootprintData function.
When I deleted this cell, it run greatly.

**Comment by timoast** [comment]
Ok this should now be fixed on the develop branch. See the website for installation instructions
