### ISSUE TITLE
Motif analysis with Signac species

### ISSUE THREAD

**Issue by widsquid** [timoast/signac#409]
Hello,
I have been getting a great deal of use out of your tools lately, thanks as always for the excellent work.

I am wondering if the species (9606) in the mouse brain vignette is actually human. I have run my data through with both 9606 and 10090 (mouse?) and get different results, albeit with slight overlap. Is there a reason to use human here or should it be mouse? Thanks so much.
W

https://satijalab.org/signac/articles/motif_vignette.html

**# Get a list of motif position frequency matrices from the JASPAR database**
pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = **9606**, all_versions = FALSE)
)

**# add motif information**
mouse_brain <- AddMotifs(
  object = mouse_brain,
  genome = BSgenome.Mmusculus.UCSC.mm10,
  pfm = pfm
)

**Comment by timoast** [comment]
See #58 

You can certainly use whichever motif set makes the most sense for your analysis

**Comment by widsquid** [comment]
Thanks, yes it definitely seemed that some pertinent motifs were absent from one species or the other.
W
ps thanks for pointing me to issue #58, sorry I did not find it first as I think it adequately answered my question.
