### ISSUE TITLE
My scATAC data is hg38, my scRNA data is hg19

### ISSUE THREAD

**Issue by wudustan** [timoast/signac#410]
Hi,

I am following the Signac vignette for merging scATACSeq datasets as well as integrating scRNASeq data. My scRNA data is aligned to hg19, but scATAC is aligned to hg38. We're currently awaiting on re-alignment, but in the meantime I'd like to push forward. 

What would be the best method for modifying the hg38 scATAC dataset in order to make it compatible with my hg19 scRNA data? All data is 10X and I am using processed Cellranger peaks

**Comment by timoast** [comment]
For integrating with scRNA-seq data it should not matter. You can quantify gene activities in the scATAC as normal and proceed.
