### ISSUE TITLE
Visual depiction of CCANS using chord diagram

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#412]
Hi,

I would like to generate a cord diagram using the CCANS output. However, I do not know how to show the links between regions as shown below
<img width="465" alt="Screen Shot 2021-01-22 at 4 29 54 PM" src="https://user-images.githubusercontent.com/64283689/105557365-a9b40680-5cd1-11eb-92cc-532ef593ecb3.png">

Do you have any suggestions I could try?

Thanks!

**Comment by timoast** [comment]
You would need to classify the genomic region for each start and end position for each link, and then summarise it as a chord diagram. This is a bit too general for a Signac issue, I suggest asking in a general forum like stackoverflow or biostars
