### ISSUE TITLE
Error: run the test sample when Read10X_h5

### ISSUE THREAD

**Issue by BioAmber5599** [timoast/signac#413]
Hi! Signac is a useful tool for the analysis of - chromatin data and we have used the tool since version 0.2.5.
   We found the newest version(Signac v1.1.0) added some useful functions for RNA and ATAC analysis. But when we run the test 
sample data according to the tutorial on Joint RNA and ATAC analysis: 10x multiomic([https://satijalab.org/signac/articles/pbmc_multiomic.html], the script [counts <- Read10X_h5("pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5"); counts;] will read the h5 file in the error format, this error will make the pipeline cut down when run to Annotating  types part. 
   The session info showed the test procession used packages of Seurat_3.9.9.9008 and Signac_1.1.0. We found the test sample will be read in the right format when used packages of Seurat_3.2.3 and Signac_1.1.0, but it also showed error in the Annotating  types part when it was read by Seurat v3.9.
Could you help us repair the error? We will appreciate it.
	
Install:
install.packages("Signac")

Run:
> library(Seurat)
> library(Signac)
> packageVersion("Signac")
[1] '1.1.0'
> packageVersion("Seurat")
[1] '3.9.9.9032'

> counts <- Read10X_h5("pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5")
Genome matrix has multiple modalities, returning a list of matrices for this genome
Warning message:
In sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
> counts
$`Gene Expression`
36601 x 11909 sparse Matrix of class "dgCMatrix"
Error in validObject(x) : 
  invalid class "dgCMatrix" object: superclass "AnyMatrix" not defined in the environment of the object's class

Best

**Comment by timoast** [comment]
This might be related to some recent changes in the Seurat v4 beta release, where the Seurat object definition was split into a separate package. Can you try reinstalling Signac and restarting R, and see if you still have the same issue?

**Comment by timoast** [comment]
Closing now as I haven't heard back

**Comment by biojiangke** [comment]
After a recent Ubuntu update, it seems that my R markdown document also broke at the monocle3 "cluster_cell" step after converting a Seurat object to a "cds" object for monocle3 using "as.cell_data_set". It throws the same error message as this one: 

Error in validObject(x) :
invalid class "dgCMatrix" object: superclass "AnyMatrix" not defined in the environment of the object's class

I updated R and all related packages (Seurat 4.0.0 and SeuratWrapper 0.3.0) and still could not pass this error. The Seurat and cds objects both seem to be fine. A search of this error message led me here to see potential clues. Meanwhile, a similar setup on MacOS (R 4.0.3, Seurat 4.0.0 and SeuratWrapper 0.3.0) is running without any problem. It seems that the only thing I could think of is the recent Ubuntu update that may have broken something.

**Comment by timoast** [comment]
@biojiangke try reinstalling Signac

**Comment by biojiangke** [comment]
It's working after reinstalling Signac. Thanks for the help!
