### ISSUE TITLE
Which version of signac is compatible with Seurat 4.0.0?

### ISSUE THREAD

**Issue by smk5g5** [timoast/signac#415]
I was trying to install latest version of signac with Seurat 4.0.0 but it keeps failing. I was wondering if I have to use the development version of signac for it to be compatible with Seurat 4.0.0.

Thanks!

**Comment by timoast** [comment]
The current CRAN release works with Seurat v4, can you explain further how it's failing and what code you're running?

**Comment by smk5g5** [comment]
Actually I just realized it is not signac but EnsDb.Hsapiens.v75 that keeps failing. Below is the reason that it failed!

`BiocManager::install("EnsDb.Hsapiens.v75")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Installing package(s) 'EnsDb.Hsapiens.v75'
trying URL 'https://bioconductor.org/packages/3.12/data/annotation/src/contrib/EnsDb.Hsapiens.v75_2.99.0.tar.gz'
Content type 'application/x-gzip' length 79029669 bytes (75.4 MB)
==================================================
downloaded 75.4 MB

* installing *source* package ‘EnsDb.Hsapiens.v75’ ...
** using staged installation
** R
** inst
Warning in file.append(to[okay], from[okay]) :
  write error during file append
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'EnsDb.Hsapiens.v75':
 .onLoad failed in loadNamespace() for 'EnsDb.Hsapiens.v75', details:
  call: EnsDb(system.file("extdata", files[[i]], package = pkgname, lib.loc = libname))
  error: Database does not have any tables!
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/khan.saad/RLibs_cellassignfinal4.0.3/EnsDb.Hsapiens.v75’

The downloaded source packages are in
	'/tmp/104007.tmpdir/Rtmp0YwPtP/downloaded_packages'
Installation path not writeable, unable to update packages: arrow, backports,
  blogdown, broom, DBI, DT, forcats, gert, git2r, gitcreds, hms, knitr, Lahman,
  memoise, patchwork, rappdirs, reprex, RMariaDB, rmarkdown, RPostgres,
  RSQLite, rticles, servr, tinytex, usethis, xaringan, xfun, boot, class,
  codetools, foreign, KernSmooth, Matrix, nlme, nnet, spatial
Old packages: 'ggthemes', 'princurve'
Update all/some/none? [a/s/n]: n
Warning message:
In install.packages(...) :
  installation of package 'EnsDb.Hsapiens.v75' had non-zero exit status`

**Comment by timoast** [comment]
Ok, then you should ask for support on the bioconductor support forum
