### ISSUE TITLE
Installing MACS2

### ISSUE THREAD

**Issue by decapicone** [timoast/signac#420]
Ok.  
Ive downloaded 3 different versions of python and pip and still cannot install MACS2.  
Ive gotten this error almost every time: 
`ERROR: Could not build wheels for macs2 which use PEP 517 and cannot be installed directly
`
What version of python are you using in the vignette?

**Comment by timoast** [comment]
I installed using python 3 and conda. If you are having issues installing MACS2, I'd suggest asking the MACS2 authors: https://github.com/macs3-project/MACS
