### ISSUE TITLE
CallPeaks() Error

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#422]
I installed macs2 but cannot seem to get it to work with Signac.  See below: 

```
peaks <- CallPeaks(
+   object = astro,
+   macs2.path = '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/MACS2'
+ )
sh: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/MACS2: is a directory
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/var/folders/hj/zm2l4_hx7gn_vc0n5gqrm4mr0000gn/T//RtmptWz20Z/combined.peaks_peaks.narrowPeak': No such file or directory



```

**Comment by timoast** [comment]
You need to give the path to the actual `macs2` program, not the directory it's installed in. See the example in the peak calling vignette: https://satijalab.org/signac/articles/peak_calling.html

**Comment by danielcgingerich** [comment]
@timoast how do I find where that is?

**Comment by danielcgingerich** [comment]
Found it.  On MacBook it is this "/Library/Frameworks/Python.framework/Versions/3.9/bin/Macs"
