### ISSUE TITLE
CoveragePlot Signac 0.2.5 version

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#425]
Hi @timoast ,

I am trying to get some data from scATACseq that we already analyzed. However, last year I updated to the new version of Seurat and Signac, and now I am struggling to use the scATACseq data because It was produced with the old Signac 0.2.5 version.

Therefore, I decided to uninstall everything and start from zero. 

I installed R 3.6.3, Seurat 3.2.1, and Signac 0.2.5, but now when I plot the CoveragePlot I have an error that I do not know how to solve.

>CoveragePlot(
  object = combined,
  region = c(region2),
  sep = c(":", "-"),
  annotation = EnsDb.Mmusculus.v79,
  peaks = StringToGRanges(regions = rownames(combined), sep = c(":", "-")),
  extend.upstream = 5000,
  extend.downstream = 5000,

Error in SingleCoveragePlot(object = object, region = region, annotation = annotation,  : 
Annotation must be a GRanges object or EnsDb object.

The weirdest thing is that EnsDb.Mmusculus.v79 is already there. Can you help to figure out what is the issue? 

Best,

Aitor

**Comment by Aitor91** [comment]
Error found. However, how can I zoom in a concrete location of the genome such as "chr13-42920000-42930000"? It only shows me the entire protein. I remember that I could zoom in and analyze the accessibility in any selected region.

Could you help me with that?

Aitor

**Comment by timoast** [comment]
@Aitor91 the `region` parameter controls the region plotted

**Comment by Aitor91** [comment]
I just figured it out. Thanks.
