### ISSUE TITLE
Reasons why co-embedding is not working

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#427]
I am having a similar problem to issue #219 and am thinking about why this is happening.  

Please correct me if I am wrong: 

According to the documentation on feature imputation, the expression matrix is multiplied by the weights matrix.  The weights are 1 - d(query-anchor) / [ d(query-k.anchor) * anchor.score ].  So essentially, the weights are between 0 and 1, where 1 is strong anchor, and 0 is poor anchor.  This means the imputation expression values will all be less than the reference used to impute.  The worse the anchor, the less imputed expression.  To see if this is the case, I looked at a DimPlot of the PCA, and see that all the ATAC cells are in the middle, near 0, while RNA cells appear to be more spread out.  

![image](https://user-images.githubusercontent.com/65676131/106936817-0ad4d480-66eb-11eb-9d5a-f503b51ce17b.png)

**Comment by timoast** [comment]
> The weights are 1 - d(query-anchor) / [ d(query-k.anchor) * anchor.score ]. So essentially, the weights are between 0 and 1, where 1 is strong anchor, and 0 is poor anchor. 

Not true, the weights are all between 0 and 1 but sum to 1 (weighted sum of k-nearest anchors)

What's likely happening here is that incorrect anchors cause expression vectors of distinct cell types to be blended, resulting in something that's more in-between the different cell types in the RNA-seq. With no code, I can't say more about why this might be happening.

**Comment by danielcgingerich** [comment]
@timoast Oh, ok - thanks for pointing me in the right direction I have a lot to learn.  Here is my code if you feel like investigating it further: 

Nuclei from 23 different samples were isolated.  For each sample, dissociated nuclei solution was split to use for snATAC and snRNA sequencing (we dont have a multiome kit).  Since nuclei for ATAC and RNA come from the same tissue sample, I want `FindTransferAnchors `to work on each ATAC/RNA pair, so I use the following workflow:  1) standard processing of datasets 2) Integrate all 23 snRNA samples 3) Split integrated snRNA assay by sample 4) `FindTransferAnchors `for each sample RNA/ATAC pair (23 pairs total) 5) impute expression for ATAC data 6) co-embed each ATAC/RNA pair 7) merge final object

```
#standard dim reduction of all objects~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#atac gene activity
for (i in 1:length(atac.list)){
  message(i)
  DefaultAssay(atac.list[[i]]) <- 'gene.activity'
  atac.list[[i]] <- NormalizeData(atac.list[[i]])
  atac.list[[i]] <- ScaleData(atac.list[[i]], features = rownames(atac.list[[i]]))
}

#rna unintegrated
for (i in 1:length(rna.list)){
  message(i)
  DefaultAssay(rna.list[[i]]) <- 'RNA'
  rna.list[[i]]@assays$integrated <- NULL
  rna.list[[i]] <- NormalizeData(rna.list[[i]])
  rna.list[[i]] <- FindVariableFeatures(rna.list[[i]])
  rna.list[[i]] <- ScaleData(rna.list[[i]])
  rna.list[[i]] <- RunPCA(rna.list[[i]])
}

#integrate RNA and split by sample~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rna.anchor <- FindIntegrationAnchors(rna.list, assay = rep('RNA', length(rna.list)), reference = which.max(lapply(rna.list, ncol)), 
                                     normalization.method = 'LogNormalize', reduction = 'cca', k.filter = 50)
rna.int <- IntegrateData(rna.anchor, normalization.method = 'LogNormalize', dims = 1:30)

rna.list <- SplitObject(rna.int, split.by = 'sampID')

#re-order list to match atac.list
x<- substr(names(rna.list), 4,nchar(names(rna.list)))
names(rna.list) <- x
pos <- match(names(atac.list), names(rna.list))
rna.list <- rna.list[pos]

#find rna-atac anchors for each pair~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

anchor.list <- list()
for (i in 1:length(atac.list)){
  message(i)
  DefaultAssay(atac.list[[i]]) <- 'gene.activity'
  DefaultAssay(rna.list[[i]]) <- 'integrated'
  anchor.list[[i]]<- FindTransferAnchors(reference = rna.list[[i]], query = atac.list[[i]],
                                         features = VariableFeatures(rna.list[[i]]), reference.assay = 'integrated',
                                         query.assay = 'gene.activity', reduction = 'cca', k.filter = 50)
}

#impute atac expression for each pair~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

impute.list <- list()
refdata.list <- list()
for (i in 1:length(atac.list)){
  message(i)
  genes.use <- rownames(rna.list[[i]])
  refdata.list[[i]] <- GetAssayData(rna.list[[i]], assay = 'integrated', slot = 'data')[genes.use,]
  impute.list[[i]] <- TransferData(anchorset = anchor.list[[i]], refdata = refdata.list[[i]], weight.reduction = atac.list[[i]][['lsi']], dims = 2:30)
}
for (i in 1:length(atac.list)){
  message(i)
  atac.list[[i]][['RNA']] <- impute.list[[i]]
  DefaultAssay(atac.list[[i]]) <- 'RNA'
}

#make sure assays align before merging~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

{
  message(i)
  atac.list[[i]][['common.peaks']] <- NULL
  atac.list[[i]][['gene.activity']] <- NULL
  rna.list[[i]][['RNA']]<-NULL
  rna.list[[i]][['SCT']]<-NULL
  atac.list[[i]][['coembed']]<-atac.list[[i]][['RNA']]
  rna.list[[i]][['coembed']]<- rna.list[[i]][['integrated']]
  DefaultAssay(atac.list[[i]]) <- 'coembed'
  DefaultAssay(rna.list[[i]]) <- 'coembed'
  atac.list[[i]][['RNA']]<- NULL
  rna.list[[i]][['integrated']] <- NULL 
}

#merge co-embeddings and plot UMAP~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

coembed.list <- list()
for (i in 1:length(atac.list)){
  message(i)
  coembed.list[[i]] <- merge(atac.list[[i]], rna.list[[i]])
}
coembed.merge <- merge(x = coembed.list[[1]], y = coembed.list[2:length(coembed.list)])

coembed.merge <- ScaleData(coembed.merge, features = rownames(coembed.merge), do.scale = FALSE)
coembed.merge <- RunPCA(coembed.merge, features = rownames(coembed.merge))
coembed.merge <- RunUMAP(coembed.merge, dims = 1:30)

```
![image](https://user-images.githubusercontent.com/65676131/106940136-29d56580-66ef-11eb-8054-37077a731ec8.png)

**Comment by timoast** [comment]
I'd suggest integrating all the scRNA, merging the scATAC, and then integrating the RNA/ATAC (just two objects)

**Comment by danielcgingerich** [comment]
> I'd suggest integrating all the scRNA, merging the scATAC, and then integrating the RNA/ATAC (just two objects)

Thank you, I am going to try this.  When integrating the RNA/ATAC, should I use the ATAC gene activities, or the ATAC imputations for integration?

**Comment by timoast** [comment]
> When integrating the RNA/ATAC, should I use the ATAC gene activities, or the ATAC imputations for integration?

Not sure what you mean by ATAC imputations....to integrate RNA/ATAC you'll need to use the gene activities. If you want to co-embed the cells you'd then use the imputed RNA (example here: https://satijalab.org/seurat/articles/atacseq_integration_vignette.html#co-embedding-scrna-seq-and-scatac-seq-datasets)

**Comment by danielcgingerich** [comment]
@timoast  Ok, I will try all of these options out.  

What I mean to ask is after `TransferData `calculates the imputed expression values, I add them to a new assay `atac.object[['RNA']]`, can I integrate this assay with my scRNA data?  Based on your first comment, with the incorrect anchors causing distinct cell types to be blended, I could perhaps integrate the imputed assay with my scRNA data for better visualization?
I also plan on trying this, but only if you think it is reasonable

Thanks

**Comment by timoast** [comment]
I wouldn't integrate the imputed RNA and the scRNA, you should be able to just merge them and run PCA/UMAP

**Comment by danielcgingerich** [comment]
Ok, thanks for your advice!

**Comment by danielcgingerich** [comment]
@timoast One more thing... scATAC and scRNA celltypes were annotated previously in the analysis.  Since incorrect anchors cause expression vectors of distinct cell types to be blended, could I split the integrated scRNA and scATAC objects by cell type, run `FindTransferAnchors `and impute with `TransferData` for each celltype separately for better results?

**Comment by timoast** [comment]
I wouldn't really recommend splitting into each separate cell type and integrating them individually. There are some anchor exploration and filtration functions in the new Seurat v4 release (`AnnotateAnchors()` and `subset()`). We're still working on adding examples of how to use these functions but you could try using them to remove incorrect anchors from your dataset, for example:

```r
filtered.anchors <- subset(
    x = anchors,
    disallowed.ident.pairs = list(c("celltype1", "celltype2")),
    group.by="celltype"
)
```

Here `group.by` must be the name of a metadata variable in both the original reference and query objects, and `disallowed.ident.pairs` lists the pairs of cell types that you want to remove anchors between. Note that the version in the current Seurat v4 release has a bug so you'll need to install Seurat from the develop branch on GitHub

**Comment by danielcgingerich** [comment]
Hi @timoast, thanks this function sounds so useful!  I am definitely trying it out.  I tried the function, but sadly it doesnt appear to be doing anything, not even an error message.  The command takes no time to run, almost as if I just pressed `return`:
```
anchors
An AnchorSet object containing 3745 anchors between the reference and query Seurat objects.
 This can be used as input to TransferData.
a <- "Excitatory Neuron"
b <- "Inhibitory Neuron"
c <- "Astrocyte"
d <- "Microglia"
e <- "Oligodendrocyte"
f <- "OPC"

a1 <- "Exc"
b1 <- "Inh"
c1 <- "Astro"
d1 <- "Micro"
e1 <- "Oligo"
f1 <- "OPC"
disallowed <- list(c(a1,b), c(a1,c), c(a1,d), c(a1,e), c(a1,f),
                   c(b1,a), c(b1,c), c(b1,d), c(b1,e), c(b1,f),
                   c(c1,a), c(c1,b), c(c1,d), c(c1,e), c(c1,f),
                   c(d1,a), c(d1,b), c(d1,c), c(d1,e), c(d1,f), 
                   c(f1,a), c(f1,b), c(f1,c), c(f1,d), c(f1,e), 
                   c(e1,a), c(e1,b), c(e1,c), c(e1,d), c(e1,f))
#subset anchors
Idents(atac) <- atac$predicted.id
Idents(rna) <- rna$cell.type
anchors <- subset(anchors, disallowed.ident.pairs = disallowed)
anchors
An AnchorSet object containing 3745 anchors between the reference and query Seurat objects.
 This can be used as input to TransferData.
```

**Comment by timoast** [comment]
You need to set the `group.by` parameter in `subset`, and it needs to be the name of a metadata variable in both reference and query objects that was present before running FindTransferAnchors. You might need to store atac$predicted.id and rna$cell.type under a common metadata name and re-run FindTransferAnchors

**Comment by danielcgingerich** [comment]
@timoast thank you, that helps a lot.  Also, for `disallowed.ident.pairs =`, what order do I place idents of query and reference?  Is it `c(ident.query, ident.reference) `or `c(ident.reference, ident.query)` ?

**Comment by timoast** [comment]
Either is fine, it is assumed as symmetric (eg, disallowed A-B will remove A-B and B-A)

**Comment by danielcgingerich** [comment]
Ok, thats super easy and convenient.  Thanks again
