### ISSUE TITLE
CreateChromatinAssay :  'special_mappings' has values not in 'NCBI_seqlevel'

### ISSUE THREAD

**Issue by mirifax** [timoast/signac#428]
Hi, I am trying to liftover sciATAC data from dm3 to dm6 and then create a ChromatinAssay. It works fine with dm3, but as soon as I lift over to dm6 I get this errror: 

Error in .map_UCSC_seqlevel_to_NCBI_seqlevel(UCSC_seqlevel, NCBI_seqlevel,  : 
  'special_mappings' has values not in 'NCBI_seqlevel'

As far as I understand, special_mappings are e.g. "chrM", but I get the error even with a small subset of just using "chr2L" regions. If I leave out the argument genome it works also fine. Is there maybe some specific problem with dm6?

Thanks a lot!

**Comment by timoast** [comment]
Not sure what this error is from, but you should be able to omit the `genome` parameter
