### ISSUE TITLE
running signac on a cell ranger aggr object

### ISSUE THREAD

**Issue by nbahlis** [timoast/signac#43]
Is it possible to run signac on cellranger aggr 10x file?

**Comment by timoast** [comment]
Yes, the output of cellranger atac aggr is very similar to that of cellranger count. See here for information on cellranger atac aggr outputs: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/aggr

You will have a count matrix, fragments file, and single-cell metrics file that you can use to create a Seurat object and run the Signac pipeline as shown in the vignettes: https://satijalab.org/signac/articles/pbmc_vignette.html

**Comment by el-hodiri** [comment]
After running aggr output through Signac, is there a way to identify cells by the equivalent of "orig.ident"? The cellranger aggr documentation states that barcodes are assigned a suffix corresponding to GEM well and part of the input for aggr is library_id, so it seems that this information may be in the Seurat/Signac object.
