### ISSUE TITLE
Informtion missing in the object

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#431]
Hi @timoast ,

I have an issue doing the QC with my merged objects. I have been following your vignette to merge different samples in one step by step. However, when I do the QC to each sample, I have seen that there is information missing, such as:
- brain$peak_region_fragments
- brain$passed_filters
- brain$blacklist_ratio
However, if I follow the vignette were you explain how to analyze one sample by adding the peaks with **h5 file format**, I have all the information needed. Therefore, if I use **h5 file** I have all the information, but if I use the **bed file**, some information is missing.

How can I solve this issue?

Thank you for your time and help,

Aitor

**Comment by Aitor91** [comment]
Observing and analyzing the code in the merge vignette, the Seurat object generated above is missing the metadata. I guess if we add it this way would be fine:

> pbmc500 <- CreateSeuratObject(pbmc500_assay, assay = "ATAC", meta.data = md.500)

What do you think? 

Aitor

**Comment by timoast** [comment]
Yes, that information is in the 10x metadata

**Comment by Aitor91** [comment]
Okay, thanks. I suggest you add that modification to vignette.

Aitor
