### ISSUE TITLE
Error in Embeddings

### ISSUE THREAD

**Issue by minjunp** [timoast/signac#432]
Hi Tim,

I integrated two scATAC-seq data using the following tutorial, and I faced an error in the code where I run:
https://satijalab.org/signac/articles/integration.html

For transferring labels, the code below gave me an error.
I am wondering if I should not use integratedLSI reduction for integrated object.
Or is it okay to run SVD on integrated object again to get 'lsi' reduction?

Code:
predicted.labels <- TransferData(
    anchorset = transfer.anchors,
    refdata = snRNA$celltypes,
    weight.reduction = integrated[['integratedLSI']],
    dims = 2:50
)

Error Message:
Extracting gene coordinates
Extracting reads overlapping genomic regions
Extracting reads overlapping genomic regions
Warning: Non-unique features (rownames) present in the input matrix, making unique
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 36928 anchors
Filtering anchors
	Retained 4896 anchors
Warning message:
In RunCCA.Seurat(object1 = reference, object2 = query, features = features,  :
  Running CCA on different assays
Finding integration vectors
Finding integration vector weights
Error in Embeddings(reduction)[nn.cells2, dims] : subscript out of bounds
Calls: TransferData -> FindWeights
Execution halted

**Comment by timoast** [comment]
Can you post the full code, and please format it so it's readable: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by minjunp** [comment]
Hi Tim,

I resolved the issue for now -- It was a simple mistake I made.

Thanks!
