### ISSUE TITLE
Annotating ATAC data from scRNA

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#433]
I have two large objects of ATAC and RNA cells.  I want to compare DEGs to DAPs on a cluster level.  Just like with cell type annotation, I am trying to transfer the cluster information from the snRNA onto my ATAC data.  Since we are comparing DAPs and DEGs per each cell type anyways, I figured transferring the actual cluster information would make the analysis even more powerful. 

The transfered clusters are all over the place.  I am wondering what is going wrong  Here is the code I am using and the output:
```
atac
atac <- RunTFIDF(atac)
atac <- FindTopFeatures(atac, min.cutoff = 'q0')
atac <- RunSVD(atac)

atac <- RunUMAP(atac, reduction = 'lsi', dims = 2:30)
atac <- FindNeighbors(atac, reduction = 'lsi', dims = 2:30)
atac <- FindClusters(atac, algorithm = 3, resolution = 0.5)
atac <- RenameCells(atac, add.cell.id = '1690')

library(sctransform)
atac[['RNA']] <- CreateAssayObject(act@assays$gene.activity@counts)
atac <- SCTransform(atac, assay = 'RNA', method='glmGamPoi')

DefaultAssay(atac) <- 'SCT'

rna
DefaultAssay(rna) <- 'integrated'
vf.ref <- VariableFeatures(rna)
DefaultAssay(rna) <- 'SCT'

vf.query <- VariableFeatures(atac)
length(intersect(vf.ref, vf.query)) #use vf.ref. not enough intersections

anchors <- FindTransferAnchors(reference = rna, query = atac, reduction = 'cca', dims = 1:30, 
                               reference.assay = 'SCT', query.assay = 'SCT', normalization.method = 'SCT', features = vf.ref)
predicted.labels <- TransferData(anchorset = anchors, refdata = rna$seurat_clusters, weight.reduction = atac[['lsi']], dims = 2:30)

atac <- AddMetaData(atac, metadata = predicted.labels)

atac$predicted.id
DefaultAssay(atac) <- 'peaks'
DimPlot(atac, reduction = 'umap', group.by = 'seurat_clusters')
```
![image](https://user-images.githubusercontent.com/65676131/107423532-6d164680-6aea-11eb-8c37-1b7f11d3e643.png)

**Comment by timoast** [comment]
I definitely wouldn't run SCTransform on the ATAC gene activity values. I'd suggest running with log-normalisation as shown in the vignettes

**Comment by danielcgingerich** [comment]
@timoast thank you, that is also something I was concerned about

**Comment by timoast** [comment]
You should use log-normalized RNA

**Comment by danielcgingerich** [comment]
will do, thanks @timoast

**Comment by danielcgingerich** [comment]
Also, I get much better results using dims 1:10 for the CCA

**Comment by timoast** [comment]
Sure, that parameter should be adjusted for your specific dataset

**Comment by Gregory94** [comment]
@timoast Can I use the new version, SCTransform_v2 [https://satijalab.org/seurat/articles/sctransform_v2_vignette.html], for normalization of either/both the RNA and ATAC data, or is Log-normalization still perferred?
