### ISSUE TITLE
GeneActivity() leaving out genes

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#434]
I would like to create a gene activity matrix that includes all of the genes from my RNA dataset in the gene activities.
Beforehand, I made sure that the annotations lined up with the RNA features.  The `FALSE `values are duplicate features that have added identifiers.  As you can see, RNA features and annotation align: 
```
grch38.2020a <- rtracklayer::import('Gencode.v32.primary_assembly.annotation.gtf')
grch38.2020a$gene_biotype <- grch38.2020a$gene_type
 table(rownames(rna) %in% grch38.2020a$gene_name)
FALSE  TRUE
   10 36591
```
Then, I added the annotations to my ATAC object and created the gene activity matrix.  I was sure to specify `features = `using the gene names from the features.tsv (file from 10X cellranger that contains feature names in the RNA seurat object)
```
srt <- readRDS(obj.path)
Annotation(srt) <- grch38.2020a
act <- GeneActivity(srt,
                    features = features.tsv$gene.name)
 table(rownames(rna) %in% rownames(activity))
FALSE  TRUE
17256 19345

```
I thought maybe the features.tsv file had different names as the RNA seurat object, but this is not the case: 
```
table(features.tsv$gene.name %in% rownames(rna))
 TRUE
36601

```
Why is this happening?  I am going to try out just manually creating the gene activity matrix for now

**Comment by timoast** [comment]
You can see the gene ranges that will be used by running `Signac:::CollapseToLongestTranscript(ranges = Annotation(object))` (note you need to use `:::` as this function is not exported by the package). Only the protein-coding gene are used. 

You can always run `FeatureMatrix()` on a define set of genomic ranges instead, and that might be easier if you're not using annotations from the Ensembl packages.

**Comment by danielcgingerich** [comment]
@timoast would a workaround be to edit my annotation GRanges object `gene_biotype `column so that all genes are "protein_coding", and then specify genes I want from the `features =` argument?

**Comment by timoast** [comment]
You could try that, yes. Otherwise if you have the coordinates of the genes, you can extend them to include the 2 kb upstream region and pass those GRanges directly to FeatureMatrix
