### ISSUE TITLE
RunChromVar() custom annotation

### ISSUE THREAD

**Issue by wudustan** [timoast/signac#435]
Hi, 

Would it be possible to pass the function annotation for promoter regions of genes (as a Granges for example), rather than Jaspar Motifs? I would like to get single-cell level deviation scores for promoter regions for genes of interest in different programmes of expression. Is this possible within Signac currently?

**Comment by timoast** [comment]
You can use the `motif.matrix` parameter in `RunChromVAR()`, and provide a binary peak x class matrix (1-dimensional), where each entry in the column is a 1 if the peak is in a promoter, and 0 otherwise
