### ISSUE TITLE
Blacklist mm10 unified step error

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#439]
I'm running into the following error when using the Multiomic Vignette

> peaks <- keepStandardChromosomes(peaks, pruning.mode = "coarse")
> peaks <- subsetByOverlaps(x = peaks, ranges = blacklist_mm10_unified, invert = TRUE)
**Error in subsetByOverlaps(x = peaks, ranges = blacklist_mm10_unified,  : 
  object 'blacklist_mm10_unified' not found**

I downloaded the mm10.blacklist.bed to my working directory from the Boyle-Lab site on Github. Is that not enough. Can you help me get past this error.

Thank you!

**Comment by timoast** [comment]
There is no `blacklist_mm10_unified` in Signac, I think you want `blacklist_mm10`. Downloading a bed file into the directory will not affect the R environment...

**Comment by sylestiel** [comment]
I don't understand what you mean by "Downloading a bed file into the directory will not affect the R environment...".

Do I need to do anything different?

**Comment by timoast** [comment]
I mean that if you download a file, that has no effect on the R session. You would need to read that file into R and create a `GRanges` object.

Yes you need to do something different: use `blacklist_mm10`

**Comment by sylestiel** [comment]
Ok. Thanks!
