### ISSUE TITLE
Integrating Cicero gene activity with gene expression data

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#44]
Dear Dr. Stuart,

I want to integrate Cicero gene activity matrix with the normalized gene expression matrix. Normalization of the gene expression matrix is done by the function (NormalizeData()) in Seurat pipeline.

The gene activity matrix is normalized by Cicero pipeline. Can I integrate both of them (one is normalized by Seurat pipeline and the other is normalized in a different way by Cicero pipeline)? Or I should use the unnormalized gene activity matrix and normalize it by Seurat function (NormalizeData()) and then integrate them by CCA (as in Seurat)?

Thanks

**Comment by timoast** [comment]
Hi, you should be able to integrate these datasets as they are if you've run the `normalize_gene_activities` function as shown in the Cicero vignette (https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#cicero-gene-activity-scores).
