### ISSUE TITLE
scATAC integration with a subset of features

### ISSUE THREAD

**Issue by kmwinkley** [timoast/signac#441]
Currently the only supported workflow for integrating scATACseq data involves integration of all the features in a set of objects, as if only a subset of the features are used for anchor finding or integration errors are thrown due to underlying merging steps in the workflow. It would be useful to be able to integrate multiple objects using only a subset of the features, as is currently the default in RNA integration, since the integration anchors can quickly become quite large when all features are included. The current alternative to this issue is to downsample the features as presented in the Signac integration vignette, but this requires either creating a new assay containing only the downsampled features (which causes more memory issues as the number of integrated objects gets larger), or to throw away data in the current ATAC assay (which is obviously an issue for downstream analysis after integration). I've done a bit of poking around in the underlying code and I think most of the issues are raised by interactions with the ScaleData slot of the assays during the FindIntegrationAnchors, IntegrateData, and merge.ChromatinAssay functions.

**Comment by timoast** [comment]
We're working on some improvements to integration in Seurat that should improve the performance on single-cell chromatin data and should solve this issue.

**Comment by laurabchopp** [comment]
@timoast any updates on improving speed/resource dependence of integration? I'm unable to integrate my 5 snATAC datasets, even with massive amounts of memory allocated. Thanks!
