### ISSUE TITLE
Generating Reference dataset for mapping

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#447]
Hi,

 How can i generate a reference dataset for mapping for the multi-omic assay analysis. What file types would I need to generate them. Would we use scRNA seq dataset files deposited in GEO (for e.g. genes, matrix and counts). I do not understand what LoadH5 Seurat means? I did glance at the vignette but I feel confounded. Should I be running some of this using Seurat first?

Care to shed some light or furnish some pointers.

**Comment by timoast** [comment]
If you want guidance on generating a scRNA-seq reference dataset I'd suggest opening a discussion in the Seurat repo
