### ISSUE TITLE
How to get cluster from Seurat object to monocle3

### ISSUE THREAD

**Issue by Aitor91** [timoast/signac#448]
Hi @timoast ,

I have finished analyzing the scATACseq data using Signac package. Everything worked perfectly. Congratulation. Currently, I am trying to perform now the pseudotime analysis following your vignette and also Monocle3's explanations.  Howver, when I move to monocle cds object from Seurat I lose the cluster information. How could avoid that? Can I add them later? Is there any vignette on how to do that?

Any help would be great. Thank you very much.

Aitor

**Comment by timoast** [comment]
Since the conversion function is part of the [SeuratWrappers](https://github.com/satijalab/seurat-wrappers) package, please ask this question there
