### ISSUE TITLE
Error with Creating Chromatin Assay

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#449]
I just upgraded to R version 4 and installed Seurat v4. Now I'm getting the following error:

Computing hash
Checking for 10765 cell barcodes
Error in validObject(.Object) : 
  invalid class "ChromatinAssay" object: undefined class for slot "assay.orig" ("OptionalCharacter")

**Comment by timoast** [comment]
Please reinstall Signac and restart R

**Comment by sylestiel** [comment]
Worked. Thanks!
