### ISSUE TITLE
Umap  function not found

### ISSUE THREAD

**Issue by sylestiel** [timoast/signac#450]
Warning: The following arguments are not used: reduction.model, return.model, n.neighbors, set.op.mix.ratio, local.connectivity, angular.rp.forest
Warning: Running UMAP on Graph objects is only supported using the umap-learn method
Error in RunUMAP.Graph(object = data.use, reduction.model = reduction.model,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by sylestiel** [comment]
<img width="887" alt="Screen Shot 2021-02-11 at 1 21 54 PM" src="https://user-images.githubusercontent.com/64283689/107687480-22243c80-6c6c-11eb-9ca3-eafebab1e762.png">

**Comment by timoast** [comment]
This seems to be a Seurat issue rather than a Signac issue, please raise an issue in the Seurat repo instead
