### ISSUE TITLE
CoveragePlot() function doesn't work well for some peaks/genes

### ISSUE THREAD

**Issue by ChengxiangQiu** [timoast/signac#452]
The CoveragePlot() function, it works for some peaks/genes, but sometimes it doesn't work.
The error message showed as below. Any suggestions?

Thank you!!

```
> CoveragePlot(
+     object = obj,
+     region = rownames(obj)[177618],
+     extend.upstream = 20000,
+     extend.downstream = 20000
+ )
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
|--------------------------------------------------|
|==================================================|
Error in width(x = region)[[1]] : subscript out of bounds
```

**Comment by timoast** [comment]
My guess would be that you're requesting a region that extends beyond the end of the chromosome. Does this work if you remove the `extend.upstream` and `extend.downstream` parameters?

**Comment by ChengxiangQiu** [comment]
Hi Tim, thanks for your reply. I have tried what you say, but it still doesn't work. Also this issue happened very frequently, so I don't think it's due to region that extends beyond the end of the chromosome. It seems more likely some problem from other tools.

**Comment by ChengxiangQiu** [comment]
Hi Tim, I am happy to tell you that it works after I update the Signac (previously it's v1.0.0). Thanks for your patience, and super sorry to bother you with such naive problems.
