### ISSUE TITLE
cannot add new column to a Signac object

### ISSUE THREAD

**Issue by ChengxiangQiu** [timoast/signac#456]
Hi, I find that I cannot add a new column to a Signac object. My Signac version is 1.1.1, and my Seurat version is 3.2.3

`> obj$test = "test"
Error in `[[<-`(`*tmp*`, i, value = value) :
  [[<- defined for objects of type "S4" only for subclasses of environment`

`> obj[[]]$test = "test"
Error in `[[<-`(`*tmp*`, , value = list(orig.ident = c("SeuratProject",  :
  [[<- defined for objects of type "S4" only for subclasses of environment`

`> obj[[]][['test']] = "test"
Error in `[[<-`(`*tmp*`, , value = list(orig.ident = c("SeuratProject",  :
  [[<- defined for objects of type "S4" only for subclasses of environment`

`> obj[[]][['test']] = rep("test", nrow(obj[[]]))
Error in `[[<-`(`*tmp*`, , value = list(orig.ident = c("SeuratProject",  :
  [[<- defined for objects of type "S4" only for subclasses of environment`

It worked before I updated my Signac from 1.0.0 to 1.1.1
Is there any suggestions?

Thank you!

**Comment by ChengxiangQiu** [comment]
I installed the 1.1.0 Signac, and it works now. I guess there is some bug in the latest version (not 100% sure, but rather some suggestions). Anyway, thanks for providing and maintaining the Signac package!

**Comment by timoast** [comment]
This should be solved by reinstalling Signac, it should not be related to the version number
