### ISSUE TITLE
long running time of RunChromVAR

### ISSUE THREAD

**Issue by linzhangTuesday** [timoast/signac#458]
Hi I am using RunChromVAR to compute motif activity on a scATAC-seq object of ~40k cells and 253k peaks. 

It has not finished after running for nearly an hour. Is there any benchmarking or ETA for it?

Thanks in advance!

**Comment by timoast** [comment]
This is typical for chromVAR. Note that Signac only provides a wrapper for chromVAR functionality, if you have questions about chromVAR itself you should ask the chromVAR authors: https://github.com/GreenleafLab/chromVAR

**Comment by Dena2021** [comment]
Hello, 
 I have the same question. I am stuck on the step of chromvar, nothing is happening after computing deviations from background. 

I have seen that you are sending to the authors but perhaps you can comment before I write them.

Thanks in advance

[1] "R version 4.1.1 (2021-08-10)"

[1] "Signac version 1.6.0"

[1] "Seurat version 4.1.0"

> DefaultAssay(mySeurat) <- "macspeaks"
> # Get a list of motif position frequency matrices from the JASPAR database
> pfm <- getMatrixSet(
+   x = JASPAR2020,
+   opts = list(collection = "CORE", tax_group = 'vertebrates', all_versions = FALSE)
+ )
> # add motif information
> mySeurat <- AddMotifs(
+   object = mySeurat,
+   genome = BSgenome.Mmusculus.UCSC.mm10,
+   pfm = pfm
+ )
Building motif matrix
Finding motif positions
Creating Motif object
> View(pfm)
> register(MulticoreParam(10, progressbar = TRUE))
> mySeurat <- RunChromVAR(
+   object = mySeurat,
+   genome = BSgenome.Mmusculus.UCSC.mm10,
+   verbose=TRUE
+ )
Computing GC bias per region
Selecting background regions
Computing deviations from background
  |                                                         |   0%

**Comment by Fernandobec** [comment]
Did you guys manage to solve this somehow? I have the same problem, with a dataset of 30K cells 250ishK peaks, I leave it running for up to 14 days and it's just stuck at Computing deviations from background. I'd be glad to hear if any of you managed to solve this and could share how.

**Comment by Dena2021** [comment]
This what worked for me- 
Before chromvar command run
register(SerialParam())

**Comment by Fernandobec** [comment]
Thanks a lot! :D Also worked for me

**Comment by Xiangjun99** [comment]
hi，I met the same issue. do you remember how long it takes for this step? I tried to run register(SerialParam()) before  chromvar command. looks like stucked in Computing deviations from background. Thanks. 

library(BiocParallel)
library(chromVAR)
library(motifmatchr)
library(BSgenome.Hsapiens.UCSC.hg38)

register(SerialParam())

> pbmc.filter.H <- RunChromVAR(
+   object = pbmc.filter.H,
+   genome = BSgenome.Hsapiens.UCSC.hg38
+ )
Computing GC bias per region
Selecting background regions
Computing deviations from background

**Comment by Dena2021** [comment]
This step did not take much time (seconds).

**Comment by sugiYag** [comment]
@linzhangTuesday  @Fernandobec 

firstly, i wanna know whether you guys finished runchromvar command run or not;

if you successfully run chromvar, can you tell me how long it takes?

**Comment by HaikuoLi** [comment]
Time significantly reduced with
`library(BiocParallel)
register(SerialParam())`

Thank you!

**Comment by sjasws** [comment]
> hi，I met the same issue. do you remember how long it takes for this step? I tried to run register(SerialParam()) before chromvar command. looks like stucked in Computing deviations from background. Thanks.
> 
> library(BiocParallel) library(chromVAR) library(motifmatchr) library(BSgenome.Hsapiens.UCSC.hg38)
> 
> register(SerialParam())
> 
> > pbmc.filter.H <- RunChromVAR(
> 
> * object = pbmc.filter.H,
> * genome = BSgenome.Hsapiens.UCSC.hg38
> * )
>   Computing GC bias per region
>   Selecting background regions
>   Computing deviations from background

Hi, dear all, especially @Xiangjun99 ,
Did you finally solve the problem?
I run the code "library(BiocParallel) register(SerialParam())" before RunChromVAR(), but still stuck at the "Computing deviations from background" stage.
Thank you.
