### ISSUE TITLE
long running time for Footprint()

### ISSUE THREAD

**Issue by linzhangTuesday** [timoast/signac#459]
Hi I am trying to run Footprint()on a dataset of ~40k cells x 250k peaks,
to gather footprinting info for 3 motifs. 

It has been running for half an hour and has not finished. I am confused whether it is running or stuck.

May I ask how long it usually takes?

Thanks!

**Comment by timoast** [comment]
This is a typical of the runtime for motif footprinting. You can speed up this step by setting a parallelization plan: https://satijalab.org/signac/articles/future.html
