### ISSUE TITLE
About FindTransferAnchors function

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#46]
Dear all,

I am asking about FindTransferAnchors function, 

does it look for the nearest match between scRNA-seq cell and scATAC-seq cells? Or it looks for the nearest match between scRNA-seq clusters and scATAC-seq clusters?

From the output of the function, I believe that it looks for the nearest match between cells, right?

But I noticed that one cell in scRNA-seq may have more than one match in scATAC-seq cells, is that true?

So, to take the two most matching cells from the two datasets together, I should take the cells with the highest score? Is there a threshold for the score to determine the confidence of matching? For example, if the score is > 0.5, can I consider this a confident match?

and for the function TransferData, how does it determine the score of cell type prediction in scATAC-seq cells? I found that the scores here are totally different from the matching scores in FindTransferAnchors function.

Thank you

**Comment by timoast** [comment]
Hi, this information is in our paper where we describe the method: https://www.sciencedirect.com/science/article/pii/S0092867419305598?via%3Dihub 

Please take a look at that first and let me know if you have further questions
