### ISSUE TITLE
peak_region_fragments and blacklist_region_fragments metadata disappeared after merging

### ISSUE THREAD

**Issue by linzhangTuesday** [timoast/signac#462]
Hi I am trying to use merging from Signac,  https://satijalab.org/signac/articles/merging.html

It completed smoothly, then I wanna to follow the QC steps from the PBMC sample here https://satijalab.org/signac/articles/pbmc_vignette.html

To look at Vlnplot of 'pct_reads_in_peaks','peak_region_fragments','TSS.enrichment','blacklist_ratio','nucleosome_signal'.

So I run the below 
combined$pct_reads_in_peaks <- combined$peak_region_fragments / combined$passed_filters * 100
combined$blacklist_ratio <- combined$blacklist_region_fragments / combined$peak_region_fragments

which reports
Error: Cannot find 'peak_region_fragments' in this Seurat object
Error: Cannot find 'blacklist_region_fragments' in this Seurat object

These should be from the singlecell.csv file, and was there without merging. However when I follow the merging protocol, these metadata columns disappeared.

Is there any suggestions on that? Do people also see this when merging?

Thanks in advance!

**Comment by timoast** [comment]
Can you provide the full code you're running?

**Comment by linzhangTuesday** [comment]
Thanks for the quick response. Yes, please find below the codes.  I think it is the same as the merging tutorial.

`peaks.sample1 <- read.table(file="sample1/outs/peaks.bed",col.names = c("chr", "start", "end"))
  peaks.sample2 <- read.table(file="sample2/outs/peaks.bed",col.names = c("chr", "start", "end"))

 gr.sample1 <- makeGRangesFromDataFrame(peaks.sample1)
 gr.sample2 <- makeGRangesFromDataFrame(peaks.sample2)

combined.peaks <- reduce(x = c(gr.sample1,gr.sample2))

peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]

md.sample1 <- read.table(file="sample1/outs/singlecell.csv",stringsAsFactors = FALSE,sep = ",",header = TRUE,row.names = 1)[-1, ] 

md.sample2 <- read.table(file="sample2/outs/singlecell.csv",stringsAsFactors = FALSE,sep = ",",header = TRUE,row.names = 1)[-1, ]

md.sample1 <- md.sample1[md.sample1$passed_filters > 500, ]
md.sample2 <- md.sample2[md.sample2$passed_filters > 500, ]

frags.sample1 <- CreateFragmentObject(
  path = "sample1/outs/fragments.tsv.gz",
  cells = rownames(md.sample1)
)

frags.sample2 <- CreateFragmentObject(
  path = "sample1/outs/fragments.tsv.gz",
  cells = rownames(md.sample2)
)

sample1.counts <- FeatureMatrix(
  fragments = frags.sample1,
  features = combined.peaks,
  cells = rownames(md.sample1)
)

sample2.counts <- FeatureMatrix(
  fragments = frags.sample2,
  features = combined.peaks,
  cells = rownames(md.sample2)
)

sample1_assay <- CreateChromatinAssay(sample1.counts, fragments = frags.sample1,sep = c(":","-"), genome = "hg38")
sample1 <- CreateSeuratObject(sample1_assay, assay = "ATAC")

sample2_assay <- CreateChromatinAssay(sample2.counts, fragments = frags.sample2,sep = c(":","-"), genome = "hg38")
sample2 <- CreateSeuratObject(sample2_assay, assay = "ATAC")

sample1$dataset <- 'sample1'
sample2$dataset <- 'sample2'

combined <- merge(
x=sample1,
y=sample2,
add.cell.ids=c("sample1","sample2"))

annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)

# change to UCSC style since the data was mapped to hg38
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "hg38"

# add the gene information to the object
Annotation(combined) <- annotations

combined <- NucleosomeSignal(object = combined)
combined <- TSSEnrichment(object = combined,fast = FALSE)

# ERROR
combined$pct_reads_in_peaks <- combined$peak_region_fragments / combined$passed_filters * 100
Error: Cannot find 'peak_region_fragments' in this Seurat object
# ERROR
combined$blacklist_ratio <- combined$blacklist_region_fragments / combined$peak_region_fragments
Error: Cannot find 'blacklist_region_fragments' in this Seurat object
`

Thanks and please let me know if there is any questions or suggestions.

**Comment by timoast** [comment]
You didn't add the metadata to the Seurat object. You need to set the `meta.data` parameter in `CreateSeuratObject`
