### ISSUE TITLE
Error in AddMotifs function

### ISSUE THREAD

**Issue by strawberry789** [timoast/signac#463]
Hello,

When I tried to use the AddMotifs function, using a Drosophila melanogaster genome, I get the following error:

Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width, : sequence 2L not found

Please advise.

Thank you.

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by strawberry789** [comment]
Here's the code:

pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 7227, all_versions = FALSE)
)

T1_ATAC_clustered <- AddMotifs(
  object = T1_ATAC_clustered,
  genome = BSgenome.Dmelanogaster.UCSC.dm6,
  pfm = pfm
)

Thanks.

**Comment by timoast** [comment]
Ok so the BSgenome for Dmel has UCSC-style chromosome names (eg, chr2L), but your error message suggests that your peak names are NCBI style (eg, 2L). You need to ensure the chromosome names match in the BSgenome and in your dataset. You can change the style using `seqlevelsStyle`, eg:

```r
GenomeInfoDb::seqlevelsStyle(BSgenome.Dmelanogaster.UCSC.dm6) <- "NCBI"
```

**Comment by strawberry789** [comment]
Thanks.

I ran the suggested command:
GenomeInfoDb::seqlevelsStyle(BSgenome.Dmelanogaster.UCSC.dm6) <- "NCBI"

And then tried AddMotifs again:
T1_ATAC_clustered <- AddMotifs(
  object = T1_ATAC_clustered,
  genome = BSgenome.Dmelanogaster.UCSC.dm6,
  pfm = pfm
)

But this time, I got this error:
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence
  "chr2R"

**Comment by timoast** [comment]
Are you sure you're using the correct genome build?

**Comment by strawberry789** [comment]
I used "Drosophila_melanogaster.BDGP6.28.100.gtf" to find the gene coordinates for my ATAC object and "BSgenome.Dmelanogaster.UCSC.dm6" for the AddMotifs function.

But I checked that they both don't have "chr" in front of the chromosome name.  Not sure why I'm getting this error:
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence
"chr2R"

**Comment by timoast** [comment]
You must have features in the dataset that extend beyond the end of the dm6 genome, which is why I asked if you're sure about the genome build (were the data mapped to dm6?)

**Comment by strawberry789** [comment]
I rebuilt the ATAC reference genome using UCSC fasta and gtf files:
http://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/dm6.fa.gz
http://hgdownload.soe.ucsc.edu/goldenPath/dm6/bigZips/genes/dm6.ensGene.gtf.gz

Then I ran CellRanger-atac with this reference genome.

When I get to the AddMotifs function, I used BSgenome.Dmelanogaster.UCSC.dm6 as the genome:
object <- AddMotifs(
  object = object,
  genome = BSgenome.Dmelanogaster.UCSC.dm6,
  pfm = pfm
)

And I still get the same error:
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence
  "chr2R"

**Comment by timoast** [comment]
The length of dm6 chr2R should be 25286936. You can check which peaks you have that extend beyond the end of chr2R, for example:

```r
obj_ranges <- granges(obj)
chr2r <- obj_ranges[seqnames(obj_ranges) == "chr2R"]
which(end(chr2r) > 25286936)
```

**Comment by strawberry789** [comment]
I tried the above code, but I'm not getting any results (e.g. no peaks that extend beyond the end of chr2R)

**Comment by t-and** [comment]
Hi @strawberry789, I am running into the same issue using a custom reference genome for zebrafish. Did you manage to resolve this issue?

**Comment by strawberry789** [comment]
> Hi @strawberry789, I am running into the same issue using an object aligned to a custom reference genome for zebrafish. Did you manage to resolve this issue?

Hi @t-and, unfortunately I wasn't able to resolve this issue.
