### ISSUE TITLE
GeneActivity not recognizing fragment file 

### ISSUE THREAD

**Issue by liron27** [timoast/signac#472]
Hi,
I have used the Signac pipeline step by step (from the PBMC tutorial) and every thing went smoothly, until the following command:

    gene.activities <- GeneActivity(object.atac) 

I got the following error:

Extracting gene coordinates
Error in SingleFeatureMatrix(fragment = fragments[[x]], features = features,  : 
  No matching chromosomes found in fragment file.

Not sure why it's not finding matching chromosomes...

```

**Comment by timoast** [comment]
Can you provide the output of `head(Annotation(object.atac))` and the first few rows of the fragment file?

**Comment by liron27** [comment]
GRanges object with 6 ranges and 5 metadata columns:
                  seqnames        ranges strand |           tx_id   gene_name         gene_id   gene_biotype     type
                     <Rle>     <IRanges>  <Rle> |     <character> <character>     <character>    <character> <factor>
  ENSE00001489430        X 276322-276394      + | ENST00000399012      PLCXD1 ENSG00000182378 protein_coding     exon
  ENSE00001536003        X 276324-276394      + | ENST00000484611      PLCXD1 ENSG00000182378 protein_coding     exon
  ENSE00002160563        X 276353-276394      + | ENST00000430923      PLCXD1 ENSG00000182378 protein_coding     exon
  ENSE00001750899        X 281055-281121      + | ENST00000445062      PLCXD1 ENSG00000182378 protein_coding     exon
  ENSE00001489388        X 281192-281684      + | ENST00000381657      PLCXD1 ENSG00000182378 protein_coding     exon
  ENSE00001719251        X 281194-281256      + | ENST00000429181      PLCXD1 ENSG00000182378 protein_coding     exon

**Comment by liron27** [comment]
What's is the best way to provide you with the first few rows of the fragment file? It's in tsv.gz form and is pretty big...

**Comment by liron27** [comment]
Here is the first few rows of the fragments:

head(fragments):

  chr1 X10013 X10138 TACATTCCAGAGCCAA.1 X1
1 chr1  10030  10126 TTTACGTGTGCAACAG-1  1
2 chr1  10048  10132 GATCATGCAGGAGCAT-1  1
3 chr1  10052  10120 GTAGACTGTATTCGCA-1  1
4 chr1  10054  10113 CCCTGATAGGGTTCTT-1  1
5 chr1  10054  10114 TCCAGAATCAAACCAC-1  1
6 chr1  10055  10116 GGATAGGAGGCCTCTG-1  2

**Comment by liron27** [comment]
I think that there is a annotation has the names of the chromosomes by numbers "1", "2",... "MT", where as fragment file has the name of the chromosomes as "chr1", "chr2",.... Not sure how to change that

**Comment by timoast** [comment]
Yes, that is the reason. We show how to change it in the vignettes (eg https://satijalab.org/signac/articles/pbmc_vignette.html). You need to change the `seqlevelsStyle` to UCSC

**Comment by liron27** [comment]
I did change it to UCSC and still got the same error

**Comment by timoast** [comment]
Can you show the code you're running?

**Comment by rylanci** [comment]
Hello. I am attempting to integrate two merged objects and having a similar issue, except it appears the chromosomes in the frag files are consistent with the annotations. Not sure if I need to merge fragment files for the atac component as in the 0.2.5 signac merging vignette. It seems that method was phased out. Any advice would be appreciated.  Thanks! 

Annotation: 
GRanges object with 6 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id
                        <Rle>       <IRanges>  <Rle> |        <character>
  ENSMUSE00001236884     chr3 3508030-3508332      + | ENSMUST00000108393
  ENSMUSE00000676606     chr3 3634150-3634347      + | ENSMUST00000108394
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108393
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108394
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108393
  ENSMUSE00000149313     chr3 3641223-3641317      + | ENSMUST00000108394
                       gene_name            gene_id   gene_biotype     type
                     <character>        <character>    <character> <factor>
  ENSMUSE00001236884       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000676606       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000149313       Hnf4g ENSMUSG00000017688 protein_coding     exon
  -------
  seqinfo: 22 sequences from mm10 genome

Fragment object (one of six present in merged atac object):
chrom	start	end	barcode	readCount
<chr>	<int>	<int>	<chr>	<int>
chr1	3000826	3000898	LL_7_TACTTTGCGCAAAGGAACAGAC	1
chr1	3001689	3001808	LL_7_CCTATGTGTAACCGTCCCATTC	1
chr1	3001738	3001792	LL_7_GGATTGCCTTCTTAGGTAGCGT	1
chr1	3001738	3001956	LL_7_GCCAACTGAGGGTTGTCCTCTG	1
chr1	3003199	3003367	LL_7_ACTCCTATGGAAATAAGGCCAG	1
chr1	3003574	3003641	LL_7_CAACCTCATTTGACACTGTGCG	1

**Comment by timoast** [comment]
@rylanci please open a new issue with the full code you're running and output of `sessionInfo()`

**Comment by rylanci** [comment]
Sure. Appreciate the quick reply
