### ISSUE TITLE
`fread` error on rare situation when only one reads returned

### ISSUE THREAD

**Issue by ghbore** [timoast/signac#474]
Hi Signac Team,

Recently I encountered a rare error when manually evoking the internal `CutMatrix` function to retrieve the matrix of integration sites for interesting regions. After debugging, I find the error raised probably because `scanTabix` in `GetReadsInRegion` may return only one read, and then `fread` in `TabixOutputToDataFrame` cannot properly parse the one-line newline-free text, for example

```
  reads <- 'chr1\t1\t2\tcell\t1'

  df <- fread(
    text = reads,
    sep = "\t",
    header = FALSE,
    col.names = c("chr", "start", "end", "cell", "count"),
    fill = TRUE
  )
```

https://github.com/timoast/signac/blob/e0512d348adeda4a3f23a2e8f56d1fe09840e03c/R/utilities.R#L1761-L1767

**Comment by timoast** [comment]
Thanks for reporting, this should be fixed now on the develop branch. See the [website](https://satijalab.org/signac/articles/install.html#development-version-1) for installation instructions.
