### ISSUE TITLE
the Seurat3.2.2 load and SingleR 1.0.1 conflict error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#479]
Hi @timoast ,
   this error make me confused, when i run the Seurat(3.2.2) and SingleR(1.0.1) at the same time, the Seurat's DimPlot would be generated below error, how can i fix this question. and it well the old version SingleR using for my data , so i chosen the old version of SingleR.
![image](https://user-images.githubusercontent.com/41668708/108996986-0e4ff000-76da-11eb-8cd2-e9324b51229c.png)
    On this case, how can i fix it from this error?
     Any advice would be appreciated.
     Best,
      hanhuihong

**Comment by timoast** [comment]
I'd suggest raising this issue in either the Seurat or SingleR repo
