### ISSUE TITLE
About integration of scRNA-seq and scATAC-seq data

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#48]
Hi,

To integrate scRNA-seq data and scATAC-seq data, I followed this tutorial: https://satijalab.org/seurat/v3.1/atacseq_integration_vignette.html

However, when I read the methods section of your paper, I found that the gene expression matrix (scRNA-seq) and gene activity matrix (obtained from scATAC-seq) should have the same number of features (genes) and probably in the same order. This information was not mentioned in the tutorial I mentioned above. Does that mean that I need to repeat all the work again but with both matrices having the same number of genes? Is there in Seurat an easy function to perform this step and produce an output compatible with the Seurat objects?

Thanks

**Comment by timoast** [comment]
You don't need the entire set of features to be the same (you don't need to quantify gene activity in the scATAC for every gene that was detected in the scRNA), a subset of features will be sufficient. They don't need to be placed in the same order, this is handled internally.

Have you seen the tutorial here? https://satijalab.org/signac/articles/pbmc_vignette.html. It shows one method of creating a gene activity matrix.

**Comment by ahmedabbas81** [comment]
Thank you very much! Is this method for creating gene activity matrix published is a paper? If yes, can you please tell me its title or send me its link so that I see it.

Thanks

**Comment by timoast** [comment]
It's not published in a paper, it's just a function in the Signac package. It simply counts fragments over a region, for example the gene body and 2 kb upstream region

**Comment by kat-yuan** [comment]
Has issues for the installation. Did try R3.6.1 as well, same error. So what exact version of R should I used for signac. 
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) packages ‘GenomeInfoDbData’, ‘GO.db’ are not available (for R version 3.5.3)

**Comment by timoast** [comment]
Try installing `GenomeInfoDbData ` and `GO.db`:

```r
BiocManager::install(c("GenomeInfoDbData", "GO.db"))
```

**Comment by kat-yuan** [comment]
Hi Tim,

 Sorry to bother you again.

 Still has issue for one package  ‘DirichletMultinomial’, then I tried
reinstall this package, same error as showed below, really really need your
help please:
* installing *source* package ‘DirichletMultinomial’ ...
** libs
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c R_init_DirichletMultinomial.c -o R_init_DirichletMultinomial.o
/bin/sh: gsl-config: command not found
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c dirichlet_fit.c -o dirichlet_fit.o
/bin/sh: gsl-config: command not found
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c dirichlet_fit_main.c -o dirichlet_fit_main.o
/bin/sh: gsl-config: command not found
dirichlet_fit_main.c:1:25: fatal error: gsl/gsl_rng.h: No such file or
directory
 #include <gsl/gsl_rng.h>
                         ^
compilation terminated.
make: *** [dirichlet_fit_main.o] Error 1
ERROR: compilation failed for package ‘DirichletMultinomial’
* removing
‘/home/xiaolikat.yuan/R/x86_64-pc-linux-gnu-library/3.5/DirichletMultinomial’
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) installation of package ‘DirichletMultinomial’
had non-zero exit status
> install.packages("DirichletMultinomial")
Installing package into
‘/home/xiaolikat.yuan/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL '
https://bioconductor.org/packages/3.8/bioc/src/contrib/DirichletMultinomial_1.24.1.tar.gz
'
Content type 'application/x-gzip' length 409776 bytes (400 KB)
==================================================
downloaded 400 KB

* installing *source* package ‘DirichletMultinomial’ ...
** libs
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c R_init_DirichletMultinomial.c -o R_init_DirichletMultinomial.o
/bin/sh: gsl-config: command not found
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c dirichlet_fit.c -o dirichlet_fit.o
/bin/sh: gsl-config: command not found
gcc -std=gnu99 -I"/global/software/r/r-3.5.3/lib64/R/include" -DNDEBUG
-I/usr/local/include  `gsl-config --cflags` -DR_DIRICHLETMULTINOMIAL -fpic
 -g -O2  -c dirichlet_fit_main.c -o dirichlet_fit_main.o
/bin/sh: gsl-config: command not found
dirichlet_fit_main.c:1:25: fatal error: gsl/gsl_rng.h: No such file or
directory
 #include <gsl/gsl_rng.h>
                         ^
compilation terminated.
make: *** [dirichlet_fit_main.o] Error 1
ERROR: compilation failed for package ‘DirichletMultinomial’
* removing
‘/home/xiaolikat.yuan/R/x86_64-pc-linux-gnu-library/3.5/DirichletMultinomial’

The downloaded source packages are in
‘/tmp/RtmpMB0dm9/downloaded_packages’
Warning message:
In install.packages("DirichletMultinomial") :
  installation of package ‘DirichletMultinomial’ had non-zero exit status

**Comment by timoast** [comment]
Hi, it looks like you need to install [gsl](https://stackoverflow.com/questions/7033927/how-to-correctly-install-gsl-library-in-linux#7033971) in order to compile DirichletMultinomial.

I will be releasing an update in the next couple of days that will remove the dependency on DirichletMultinomial

**Comment by kat-yuan** [comment]
Hi Tim,

Thanks and will give it a try. Or I can wait for the updated version after.

Happy holidays.

KAT

**Comment by kat-yuan** [comment]
Hi Tim,

 Happy New Year.

Sorry to bother you again, just wondering when will the new version of
signac be available? Would you mind send me a message please.

Thanks a lot and have a good one.

KAT

**Comment by timoast** [comment]
@kat-yuan sorry for the delays, the new version is available now that removes several dependencies

**Comment by kat-yuan** [comment]
Hi Tim,

Thanks, I will try the new one. Hope will be alright.

KAT
