### ISSUE TITLE
peak by cell matrix input

### ISSUE THREAD

**Issue by Pikachu233** [timoast/signac#481]
Hi!

I was wondering if I could use matrix.mtx instead of .h5 file as input to Signac analysis. thanks!

**Comment by timoast** [comment]
Yes, use the `Seurat::Read10X()` or `Matrix::readMM()` function

**Comment by Pikachu233** [comment]
Hi @timoast! for sure the matrix could be read by [/ Matrix::readMM()/]. However, I wonder how I could generate a seurat object from the .mtx peak by cell matrix instead of .h5. It seems the "feature" file for ATAC could not be read as "gene" file for RNA by [/Read10X/]?

**Comment by timoast** [comment]
All you need to generate a Seurat object is the count matrix, so once you read in the count matrix you can follow the vignettes on the website

**Comment by Pikachu233** [comment]
I see, thank you!

**Comment by Nidane** [comment]
i might have a similar question
i have a barcode file, a matrix file and a peaks file, how could i read them in to create the Signac/Seurat object ? thanks
