### ISSUE TITLE
Using the ATAC peak matrix in place of masc2 calling peak matrix occurred error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#486]
Hi @timoast 
The other step can run successfully, and the DimPlot had be drawed already. however, when runing on RegionStats step get below error.
 I guess that the genome i used had the scaffold debris, in my case, the KI270727.1 chr liken the debris.
> gex <- RegionStats(gex, genome = BSgenome.Hsapiens.UCSC.hg38)
Error in .getOneSeqFromBSgenomeMultipleSequences(x, name, start, NA, width,  : 
  sequence KI270727.1 not found
 Under this condition, how can i fix it? 
  Best,
  hanhuihong

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by honghh2018** [comment]
Hi
The full code lying below:
data1<-Read10X('/share/nas1/Data/PipeLine/scRNA_ATAC_Combined/v1.0/analysis/result/sample345/outs/filtered_feature_bc_matrix')
data1$Peaks
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)

fragpath <- "/share/nas1/Data/PipeLine/scRNA_ATAC_Combined/v1.0/analysis/result/sample345/outs/atac_fragments.tsv.gz"

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "hg38"
gex<-CreateSeuratObject(
  counts = data1$`Gene Expression`,
  assay = "RNA"
)

gex[["ATAC"]] <- CreateChromatinAssay(
  counts = data1$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)
###control qc
DefaultAssay(gex) <- "ATAC"

gex <- NucleosomeSignal(gex)
gex <- TSSEnrichment(gex)

VlnPlot(
  object = gex,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)
##QC
gex <- subset(
  x = gex,
  subset = nCount_ATAC < 100000 &
    nCount_RNA < 25000 &
    nCount_ATAC > 1000 &
    nCount_RNA > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 1
)


###############
DefaultAssay(gex) <- "RNA"

gex <- SCTransform(gex)
gex <- RunPCA(gex)

##############
DefaultAssay(gex) <- "ATAC"
gex <- FindTopFeatures(gex, min.cutoff = 5)
gex <- RunTFIDF(gex)
gex <- RunSVD(gex)
DefaultAssay(gex) <- "SCT"
gex[['pca']]
###joint analysis

gex <- FindMultiModalNeighbors(
  object = gex,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)


# To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
gex <- RunUMAP(
  object = gex,
  nn.name = "weighted.nn", 
  assay = "RNA",
  verbose = TRUE
)

**Comment by timoast** [comment]
At what point are you calling `RegionStats()`? Please include the **full** code

**Comment by honghh2018** [comment]
sorry  to lately reply @timoast,
The full code i run post below:
library(Seurat)
library(Signac)
library(reticulate)
library(ggplot2)
py_config()
py_available('umap')
py_available('numpy')
sys<-import('sys')


data1<-Read10X('/scRNA_ATAC_Combined/v1.0/analysis/result/sample345/outs/filtered_feature_bc_matrix')
data1$Peaks
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)

fragpath <- "/scRNA_ATAC_Combined/v1.0/analysis/result/sample345/outs/atac_fragments.tsv.gz"

annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "hg38"
gex<-CreateSeuratObject(
  counts = data1$`Gene Expression`,
  assay = "RNA"
)

gex[["ATAC"]] <- CreateChromatinAssay(
  counts = data1$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)
###control qc
DefaultAssay(gex) <- "ATAC"

gex <- NucleosomeSignal(gex)
gex <- TSSEnrichment(gex)

VlnPlot(
  object = gex,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)
##QC
gex <- subset(
  x = gex,
  subset = nCount_ATAC < 100000 &
    nCount_RNA < 25000 &
    nCount_ATAC > 1000 &
    nCount_RNA > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 1
)


##############
DefaultAssay(gex) <- "RNA"

gex <- SCTransform(gex)
gex <- RunPCA(gex)

##############
DefaultAssay(gex) <- "ATAC"
gex <- FindTopFeatures(gex, min.cutoff = 5)
gex <- RunTFIDF(gex)
gex <- RunSVD(gex)
DefaultAssay(gex) <- "SCT"
gex[['pca']]
###joint analysis

gex <- FindMultiModalNeighbors(
  object = gex,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)


# To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
gex <- RunUMAP(
  object = gex,
  nn.name = "weighted.nn", 
  assay = "RNA",
  verbose = TRUE
)

DimPlot(gex, label = TRUE, repel = TRUE, reduction = "umap") 
gex<-FindNeighbors(gex,dims = 1:30)
gex<-FindClusters(gex,resolution = 0.3)
# Linking peaks to genes
DefaultAssay(gex) <- "ATAC"


# first compute the GC content for each peak
gex <- RegionStats(gex, genome = BSgenome.Hsapiens.UCSC.hg38)    ###the step showing error that i post on first floor.
Best,
hanhuihong

**Comment by honghh2018** [comment]
Could any advices for this solution ?

**Comment by timoast** [comment]
can you show the output of `head(rownames(gex[["ATAC"]]))`?

**Comment by honghh2018** [comment]
@timoast 
the result showing below:
![image](https://user-images.githubusercontent.com/41668708/109589354-29d95180-7b45-11eb-9ca1-9182908b92c1.png)

**Comment by timoast** [comment]
I think the issue is that the genome you mapped the data to has the scaffolds named differently to the BSgenome. The scaffolds aren't that useful for analysis, so you could solve this by removing peaks that are on scaffolds. For example:

```r
library(BSgenome.Hsapiens.UCSC.hg38)

main.chroms <- standardChromosomes(BSgenome.Hsapiens.UCSC.hg38)
keep.peaks <- as.logical(seqnames(granges(object)) %in% main.chroms)
object <- object[keep.peaks, ]
```

**Comment by honghh2018** [comment]
Hi @timoast ，
     It was weird when I follow your code that post above. the object should be had the RNA assay and the ATAC assay, but when i 
run the object <- object[keep.peaks, ] that you post, the object assay just only had the ATAC assay, without the RNA data.
if i try to remove the scaffolds like below, it occurred error:
![image](https://user-images.githubusercontent.com/41668708/110080799-f6592a00-7dc5-11eb-9cab-1c6534766f50.png)
 error:
![image](https://user-images.githubusercontent.com/41668708/110081215-9020d700-7dc6-11eb-8741-5ffb05869d85.png)
  On my case, i want to use the cellranger ATAC data and avoid the scaffold that can trigger the error and make the analysis
pause, based on this ,i hope that function can be include within on the Signac package.
   Hope the update.
   Best,
    hanhuihong

**Comment by honghh2018** [comment]
Have anyone could help?

**Comment by timoast** [comment]
To subset only the ATAC assay use:

```r
library(BSgenome.Hsapiens.UCSC.hg38)

main.chroms <- standardChromosomes(BSgenome.Hsapiens.UCSC.hg38)
keep.peaks <- which(as.character(seqnames(granges(object))) %in% main.chroms)
object[["ATAC"]] <- subset(object[["ATAC"]], features = rownames(object[["ATAC"]])[keep.peaks])
```

**Comment by YangLi-Bio** [comment]
Hi Tim,

This issue has been solved. I have reproduced the result in the vignette. The reason is probably the version of GenomInfoDb.

Thank you!
