### ISSUE TITLE
ConnectionsToLinks

### ISSUE THREAD

**Issue by Pikachu233** [timoast/signac#488]
Hi,

I was trying to find co-accessibilities with SeuratWrapper. However, after getting conns and canns, I encountered some issues when running the ConnectionsToLinks function:
```
> ccans <- generate_ccans(conns)
> links <- ConnectionsToLinks(conns = conns, ccans = ccans)
Error in stop_if_wrong_length("'seqnames'", ans_len) : 
  'seqnames' must have the length of the object to construct (1) or length 1
```
I didn't see why there would be a length issues.

**Comment by timoast** [comment]
Can you show the output of `head(conns)`, `dim(conns)`, and `head(ccans)`?
