### ISSUE TITLE
Function PeriodPlot error

### ISSUE THREAD

**Issue by zliu23** [timoast/signac#49]
Hi there,
I am trying the function PeriodPlot but get the following error:

> pbmc$nucleosome_group <- ifelse(pbmc$nucleosome_signal > 10, 'NS > 10', 'NS < 10')
> PeriodPlot(object = pbmc, group.by = 'nucleosome_group')
Error: At least one layer must contain all faceting variables: `group`.
* Plot is missing `group`
* Layer 1 is missing `group`

what should I do to solve this problem?

Thanks in advance

**Comment by timoast** [comment]
You probably don't have cells in one of the groups. What's the output of `table(pbmc$nucleosome_group)`?

**Comment by zliu23** [comment]
Thank you Tim.

> table(pbmc$nucleosome_group)

NS < 10 NS > 10 
   9628      95

**Comment by timoast** [comment]
Ok so there are cells in each group, I think you just need to increase the size of the region used. For example, set `region="chr1-1-249250621" to use fragments from the whole of human chromosome 1

**Comment by zliu23** [comment]
It worked, thanks again!
