### ISSUE TITLE
Analyzing a publicly available 10X dataset with Signac

### ISSUE THREAD

**Issue by Kcjohnson** [timoast/signac#490]
Thanks for the creation and maintenance of Signac, it's a very helpful tool. 

I am trying to analyze a publicly available 10X scATACseq dataset where the output provided are the CellRanger-ATAC files barcodes.tsv.gz, matrix.mtx.gz, and peaks.bed.gz. However, the fragments.tsv.gz is not available.

In following the PBMC tutorial, I was able to create the ChromatinAssay object and perform dimensionality reduction and clustering without the fragments file. However, I don't seem to be able to generate the QC metrics or calculate the GeneActivity which I assume is because FeatureMatrix(fragments = Fragments(object = object[[assay]]), ...). Is there a workaround for not having the fragments file that I may have missed or is the fragments file critical for Signac?

**Comment by timoast** [comment]
The fragment file is the required input data for most analyses in Signac. You can run many steps with just a matrix (LSI, clustering, find differential peaks), but many steps require the fragment file. Typically this is supplied in publicly available 10x Genomics datasets.

**Comment by Kcjohnson** [comment]
Thanks @timoast for confirming its requirement. I'll follow up with the authors since I don't believe this information was made public.

**Comment by alekseybelikov** [comment]
Many public datasets dont have fragment files. Please bring back the old CreateGeneActivityMatrix function!
