### ISSUE TITLE
Signac Annotation

### ISSUE THREAD

**Issue by summer-tao** [timoast/signac#492]
Hello, I am doing the Signac tutorial of  "Analyzing adult mouse brain scATAC-seq" https://satijalab.org/signac/articles/mouse_brain_vignette.html

When I did the gene annotation step:
seqlevelsStyle(annotations) <- 'UCSC'

There is an error:
**Error in .make_assembly_report_URL(assembly_accession) : 
  don't know where to find assembly report for GCF_000001635.20**

Could anybody help me, please?

I have tried to solve the issue by `#1`:GenomeInfoDb::seqlevelsStyle(annotations) <- 'UCSC'
`#2`: GenomeInfoDb::seqlevelsStyle(annotations) <- "UCSC"
And I checked that my GenomeInfoDb version is the newest one.

**Comment by timoast** [comment]
Can you post the full code?

**Comment by summer-tao** [comment]
> Can you post the full code?

Sure. Thanks very much of your nice concentration.

# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Mmusculus.v79)

# change to UCSC style since the data was mapped to hg19
**seqlevelsStyle(annotations) <- 'UCSC'**
genome(annotations) <- "mm10"

# add the gene information to the object
Annotation(brain) <- annotations

**Comment by timoast** [comment]
I wasn't able to reproduce this, but the error seems related to this bioconductor issue: https://support.bioconductor.org/p/125101/

I'd suggest following the suggestions there

**Comment by summer-tao** [comment]
> I wasn't able to reproduce this, but the error seems related to this bioconductor issue: https://support.bioconductor.org/p/125101/
> 
> I'd suggest following the suggestions there

I have figured out the reason was because of the network firewall of my school. Is there any replacement way to annotate the data, please?
