### ISSUE TITLE
DNA Motif Analysis Issue with addMotifs 

### ISSUE THREAD

**Issue by Jaureguy760** [timoast/signac#494]
Hi. It looks like I am running into issues with DNA motif analysis and specifically when I use the function add motifs(). I would really appreciate some feedback or help on this issue. Thank you for your time. 

Building motif matrix

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'matchMotifs' for signature '"PWMatrixList", "Assay"'
Traceback:

1. AddMotifs(object = brain, genome = BSgenome.Rnorvegicus.UCSC.rn6, 
 .     pfm = pfm)
2. AddMotifs.Seurat(object = brain, genome = BSgenome.Rnorvegicus.UCSC.rn6, 
 .     pfm = pfm)
3. AddMotifs(object = object[[assay]], genome = genome, pfm = pfm, 
 .     verbose = verbose)
4. AddMotifs.default(object = object[[assay]], genome = genome, 
 .     pfm = pfm, verbose = verbose)
5. CreateMotifMatrix(features = object, pwm = pfm, genome = genome, 
 .     use.counts = FALSE)
6. motifmatchr::matchMotifs(pwms = pwm, subject = features, genome = genome, 
 .     out = "scores", ...)
7. motifmatchr::matchMotifs(pwms = pwm, subject = features, genome = genome, 
 .     out = "scores", ...)
8. matchMotifs(pwms_list, subject, ...)
9. (function (classes, fdef, mtable) 
 . {
 .     methods <- .findInheritedMethods(classes, fdef, mtable)
 .     if (length(methods) == 1L) 
 .         return(methods[[1L]])
 .     else if (length(methods) == 0L) {
 .         cnames <- paste0("\"", vapply(classes, as.character, 
 .             ""), "\"", collapse = ", ")
 .         stop(gettextf("unable to find an inherited method for function %s for signature %s", 
 .             sQuote(fdef@generic), sQuote(cnames)), domain = NA)
 .     }
 .     else stop("Internal error in finding inherited methods; didn't return a unique method", 
 .         domain = NA)
 . })(list(structure("PWMatrixList", package = "TFBSTools"), structure("Assay", package = "SeuratObject")), 
 .     new("standardGeneric", .Data = function (pwms, subject, ...) 
 .     standardGeneric("matchMotifs"), generic = structure("matchMotifs", package = "motifmatchr"), 
 .         package = "motifmatchr", group = list(), valueClass = character(0), 
 .         signature = c("pwms", "subject"), default = NULL, skeleton = (function (pwms, 
 .             subject, ...) 
 .         stop("invalid call in method dispatch to 'matchMotifs' (no default method)", 
 .             domain = NA))(pwms, subject, ...)), <environment>)
10. stop(gettextf("unable to find an inherited method for function %s for signature %s", 
  .     sQuote(fdef@generic), sQuote(cnames)), domain = NA)
​
​
```r
# insert reproducible example here

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("AnnotationHub")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("motifmatchr")
BiocManager::install("BSgenome.Rnorvegicus.UCSC.rn6")


BiocManager::install("EnsDb.Rnorvegicus.v79")

#Import libraries

library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(ggplot2)
library(patchwork)
library(AnnotationHub)
set.seed(1234)
library(JASPAR2020)
library(TFBSTools)
library(motifmatchr)
library(BSgenome.Rnorvegicus.UCSC.rn6)
library(EnsDb.Rnorvegicus.v79)

#Pre-processing Workflow

counts <- Read10X_h5("/home/jjauregu/work/10x_1st_run_v_98/outs/filtered_peak_bc_matrix.h5")

EnsDb.Rnorvegicus.v98 = query(AnnotationHub(), pattern = c("Rattus Norvegicus", "EnsDb", 98))[[1]]
# create granges object with TSS positions
# we grab the TSS positions from the reference genome
gene.ranges <- genes(EnsDb.Rnorvegicus.v98)
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding',]
gene.ranges <- keepStandardChromosomes(gene.ranges, pruning.mode = 'coarse', species='Rattus_norvegicus')

metadata <- read.csv(
  file = "/home/jjauregu/work/10x_1st_run_v_98/outs/singlecell.csv",
  header = TRUE,
  row.names = 1
)

brain_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  fragments = '/home/jjauregu/work/10x_1st_run_v_98/outs/fragments.tsv.gz',
  min.cells = 1,
  annotation = gene.ranges
)

brain <- CreateSeuratObject(
  counts = brain_assay,
  assay = 'peaks',
  project = 'ATAC',
  meta.data = metadata
)

# Compute QC metrics

brain <- NucleosomeSignal(object = brain)
brain$nucleosome_group <- ifelse(brain$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram(object = brain, group.by = 'nucleosome_group')

brain <- TSSEnrichment(brain, fast = FALSE)

brain$high.tss <- ifelse(brain$TSS.enrichment > 2, 'High', 'Low')
TSSPlot(brain, group.by = 'high.tss') + NoLegend()


brain$pct_reads_in_peaks <- brain$peak_region_fragments / brain$passed_filters * 100
brain$blacklist_ratio <- brain$blacklist_region_fragments / brain$peak_region_fragments

VlnPlot(
  object = brain,
  features = c('pct_reads_in_peaks', 'peak_region_fragments',
               'TSS.enrichment', 'blacklist_ratio', 'nucleosome_signal'),
  pt.size = 0.1,
  ncol = 5
)

brain <- subset(
  x = brain,
  subset = peak_region_fragments > 3000 &
    peak_region_fragments < 100000 &
    pct_reads_in_peaks > 40 &
    blacklist_ratio < 0.025 &
    nucleosome_signal < 4 &
    TSS.enrichment > 2
)
brain

brain <- RunTFIDF(brain)
brain <- FindTopFeatures(brain, min.cutoff = 'q0')
brain <- RunSVD(object = brain)

DepthCor(brain)

#Non-linear dimension reduction and clustering

brain <- RunUMAP(
  object = brain,
  reduction = 'lsi',
  dims = 2:30
)
brain <- FindNeighbors(
  object = brain,
  reduction = 'lsi',
  dims = 2:30
)
brain <- FindClusters(
  object = brain,
  algorithm = 3,
  resolution = 1.2,
  verbose = FALSE
)

DimPlot(object = brain, label = TRUE) + NoLegend()

# compute gene activities
gene.activities <- GeneActivity(brain)

# add the gene activity matrix to the Seurat object as a new assay
brain[['RNA']] <- CreateAssayObject(counts = gene.activities)
brain <- NormalizeData(
  object = brain,
  assay = 'RNA',
  normalization.method = 'LogNormalize',
  scale.factor = median(brain$nCount_RNA)
)


DefaultAssay(brain) <- 'RNA'
FeaturePlot(
  object = brain,
  features = c('Sst','Pvalb',"Gad2","Neurod6","Rorb","Syt6"),
  pt.size = 0.1,
  max.cutoff = 'q95',
  ncol = 3
)



# Get a list of motif position frequency matrices from the JASPAR database
pfm <- getMatrixSet(
  x = JASPAR2020,
  opts = list(species = 10116, all_versions = FALSE)
)

pfm


# add motif information
brain <- AddMotifs(
  object = brain,
  genome = BSgenome.Rnorvegicus.UCSC.rn6,
  pfm = pfm
)
```

**Comment by timoast** [comment]
Can you try reinstalling Signac and restarting R?

**Comment by strawberry789** [comment]
I have a similar issue.
When the active assay is set at RNA, I get the same error:
Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'matchMotifs' for signature '"PWMatrixList", "Assay"'

So I followed your instructions to reinstall Signac and restart R, but I still get the same error.

When the active assay is set at peaks/ATAC, I get this error (which I previously started a new issue but it has not yet been resolved, despite using the same UCSC genome to map the raw data):
Error in loadFUN(x, seqname, ranges): trying to load regions beyond the boundaries of non-circular sequence
  "chr2R"

**Comment by timoast** [comment]
@strawberry789 the active assay needs to be a `ChromatinAssay`, so it's expected that you'd get an error if running this on an RNA assay. I also realize now that this was the cause of the original issue here. We will try to add more informative error messages for these types of problems.
