### ISSUE TITLE
Finding co-accessible networks with Cicero showing error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#496]
Hi @timoast , 
    It was weird that i try to convert object gex into cds to perform cicero analysis trigger error lying below:
the full code posted below:
The gex object include RNA and ATAC assay on it,like  the picture i posted
![image](https://user-images.githubusercontent.com/41668708/110240085-2ac71480-7f85-11eb-9f44-5155ecca9335.png)
library(cicero)
library(monocle3)
library(monocle)
library(SeuratWrappers)
DefaultAssay(gex)<-'ATAC'
erythroid.cds1 <- as.cell_data_set(x = gex)  ###
gex.cicero <- cicero::make_cicero_cds(erythroid.cds1, reduced_coordinates = reducedDims(erythroid.cds1)$UMAP)
 error: is(object = cds, class2 = "CellDataSet") is not TRUE
i am certain that  erythroid.cds1  was a  cell_data_set, like below picture:
![image](https://user-images.githubusercontent.com/41668708/110240185-9f9a4e80-7f85-11eb-9165-ad3b873bd7af.png)
But the error indicate that the erythroid.cds1 no a CellDataSet.
It make me so confused.
what should i do for this cases.
Best,
hanhuihong

**Comment by honghh2018** [comment]
The issue i posted above had solved, the cicero version must be 1.3.4.11. the latest cicero version was 1.8.1.
I reinstall the cicero liken you vignette work well.
There was another about the next step, liking below:
genome <- seqlengths(gex)
genome <- genome[1]
genome.df <- data.frame("chr" = names(genome), "length" = genome)
the genome was NULL
![image](https://user-images.githubusercontent.com/41668708/110263147-b7f38300-7ff0-11eb-91c3-1374b48a5cac.png)
how to fix it.
Best,
hanhuihong

**Comment by timoast** [comment]
It looks like you haven't set the seqinfo for the object you're using. You can set this using the `genome` parameter in `CreateChromatinAssay()`, or by using the `seqinfo<-` assignment function

**Comment by Dragonmasterx87** [comment]
Guys.....some of us were dropped on our heads as a kid.......so just gonna leave this here for future self:

```
seur_sig_obj <- "any_seurat/signac object that you didnt run the genome = "whatever genome" on when you ran ChromatinAssay()"

if (is.null(seqinfo(seur_sig_obj))) {
  message("OOPSssssSSSSssss SOMEONE FORGOT TO RUN ....genome = 'hg38'... WHEN THEY RAN creatChromatinAssay() HAHAHAHAHAHAHA.......")
  message("YOU CANT RUN CICERO HAHAHAHAHAHAHA.......WHAT YOU GONNA DO NOW?? REPEAT EVERYTHING AGAIN????")
  message("Dont worry, drink wome water. I got you boo....keep runing the code XD")
  } else {
  print(seqinfo(seur_sig_obj))
  print("Wow...magic")
}

# Fix your mistakes, contemplate your life.
# Note the genome, make sure you load the correct genome corresponding to your genome of intrest
seur_sig_obj@assays[["ATAC"]]@seqinfo <- seqinfo(BSgenome.Hsapiens.UCSC.hg38)

# Test
if (is.null(seqinfo(seur_sig_obj))) {
  message("OOPSssssSSSSssss SOMEONE FORGOT TO RUN ....genome = 'hg38'... WHEN THEY RAN creatChromatinAssay() HAHAHAHAHAHAHA.......")
  message("YOU CANT RUN CICERO HAHAHAHAHAHAHA.......WHAT YOU GONNA DO NOW?? REPEAT EVERYTHING AGAIN????")
  message("Dont worry, drink wome water. I got you boo....keep runing the code XD")
} else {
  print(seqinfo(seur_sig_obj))
  print("Wow...magic")
}
```
