### ISSUE TITLE
Normalization of aggregated dataset in CellrangerATAC

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#51]
Hi Tim,
People would want to analyze the aggregated scATAC-seq data for their actual samples by Signac. 10xCellrangerATAC offers "aggr" function, and it normalizes the data by subsampling fragments from higher-depth GEM wells until they all have an equal number of unique fragments per cell by default. Signac also normalizes the data by TF-IDF. Do you think we should omit the normalization done by CellrangerATAC "aggr"?
Thanks!
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, I personally wouldn't use subsampling as a normalization method and would instead prefer to use [integration](https://satijalab.org/signac/articles/integration.html) methods to remove batch effects if it is a problem. This would allow you to retain more fragments per cell and increase the overall sensitivity. Differences in total fragments between groups can also be taken into account when testing for differential accessibility (see here: https://satijalab.org/signac/articles/pbmc_vignette.html#find-differentially-accessible-peaks-between-clusters)

**Comment by ymuto802** [comment]
Thanks ! I got it.
Yoshi
