### ISSUE TITLE
The switch for pruning the non standard chromosomes is not implemented.

### ISSUE THREAD

**Issue by artgolden** [timoast/signac#513]
https://github.com/timoast/signac/blob/e0512d348adeda4a3f23a2e8f56d1fe09840e03c/R/utilities.R#L398

Hi! 
Thanks a lot for the awesome package!

I could not get the GetGRangesFromEnsDb working with my Gasterosteus aculeatus genome, because it was leaving only "MT" chromosome. 
It looks like the switch to not prune the non-standard chromosomes was not implemented in the code. It would also be great to have an option to supply a vector of the chromosomes to keep.

**Comment by timoast** [comment]
Can you show the full code you're running?

**Comment by artgolden** [comment]
Thanks for the rapid response!

setup:
```
#GETTING gasAcu1 ensdb object 
library(AnnotationHub)
ah <- AnnotationHub()
ahDb <- query(ah, pattern = c("Gasterosteus aculeatus", "EnsDb", 103))
gasAcu1_ensdb <- ahDb[[1]]
```
This:
`annotations <- GetGRangesFromEnsDb(ensdb = gasAcu1_ensdb, standard.chromosomes = FALSE)`
and this:
`annotations <- GetGRangesFromEnsDb(ensdb = gasAcu1_ensdb, standard.chromosomes = TRUE)`
produce the same result, where `annotations` Granges object contains only "MT" chromosome.

I have looked at your source code, the place I have linked in the previous comment, and I did not find `standard.chromosomes = TRUE` parameter being used anywhere in the function. That is why I assumed that it was not implemented.

**Comment by timoast** [comment]
Thanks, this should be fixed now on the develop branch.
