### ISSUE TITLE
Manually adding pre-normalized data to the data slot before integration

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#517]
I have made separate combined peak assays for 24 datasets.  Then I did `RunTFIDF `--> `FindTopFeatures `on each dataset.  From these datasets, I have created a list of common variable features to use for integration.  Now, instead of simply specifying these peaks in the FindIntegrationAnchors / IntegrateData pipeline, I want to create a new object that only includes my desired features.  If I include all the combined peaks in each object, my integration will take a very long time  -  I have tried this before.  

The issue I have with re-quantifying fragments on a subset of peaks is that it would mess up normalization.  I think that if I re-normalize on a subset of peaks, this will change the term frequency.  So what I have done is extracted the normalized data from my initial combined peak objects, subsetted features I wanted, and added this matrix to both the count and data slots of my new common peak objects. Is it ok to manually add pre-normalized data to the object slots before integration?  I am worried this will mess up the analysis somehow.  
Code: 
```
atac.list <- list()
for (i in 1:24){
  message(i)
  atac.list[[i]] <- readRDS(paste0(main.dir, rds.list3[i]))
  atac.list[[i]] <- RunTFIDF(atac.list[[i]])
  atac.list[[i]] <- FindTopFeatures(atac.list[[i]], min.cutoff = 'q0')
}

int.features <- SelectIntegrationFeatures(atac.list[[i]], nfeatures = 10000)

mtx.list <- list()
assay.list <- list()
srt.list <- list()
for (i in 1:24){
  message(i)
  mtx.list[[i]] <- atac.list[[i]]@assays$combined.peaks@data[int.features, ]
  assay.list[[i]] <- CreateChromatinAssay(counts = mtx.list[[i]], sep = c(":", "-"), 
                                          genome = 'hg38', min.cells = -1)
  srt.list[[i]] <- CreateSeuratObject(assay.obj, assay = 'common.peaks')
}
```

**Comment by timoast** [comment]
Sure, you could do this. Keep in mind that you don't have the original counts in your new object, so if you tried to run TF-IDF on it you'd get some weird results. As a side-note, we've fixed some of the issues with object merging on the develop branch which were probably the reason for the integration taking a long time when keeping all features in the object.
