### ISSUE TITLE
Not all cells requested could be found in the fragment file

### ISSUE THREAD

**Issue by f6v** [timoast/signac#518]
I've downloaded SHARE-seq [ATAC-seq data](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4156599) and trying to create `ChromatinAssay` object:

```
fragments_file <- "./data/SHARE-seq/GSM4156599_brain.atac.fragments.sorted.bed.gz"
chrom_assay <- CreateChromatinAssay(
   counts = atac_counts,
   sep = c("_", "_"),
   genome = 'mm10',
   fragments = fragments_file,
   min.cells = 10,
   annotation = annotations
)
```
I get the following error:
```
Error in CreateFragmentObject(path = fragments, cells = cells, validate.fragments = validate.fragments, : Not all cells requested could be found in the fragment file.
```
However, if I create fragments object and disable validation:
```
fragments_obj <- CreateFragmentObject(
  path = "./data/SHARE-seq/GSM4156599_brain.atac.fragments.sorted.bed.gz",
  cells = colnames(atac_counts), 
  validate.fragments = F
)
```
and then compare the cells from fragments object to the column names of my ATAC counts matrix:
```
all(colnames(atac_counts) %in% Cells(fragments_obj))
```
it seems like all the barcodes are in the fragments file.

Am I doing something wrong?

**Comment by timoast** [comment]
Do you have reason to think this is a bug rather than a mismatch between cell names in the counts matrix and cell names in the fragment file? Disabling the validation check will just assume that the cells are present and store the cell names in the fragment object

**Comment by f6v** [comment]
@timoast 
> Disabling the validation check will just assume that the cells are present and store the cell names in the fragment object

So when I load fragments without validation, it just assigns cells passed as `cells` argument? I thought I could check

> Do you have reason to think this is a bug rather than a mismatch between cell names

by create fragment object without validation and retrieving cell barcodes from that object.

**Comment by f6v** [comment]
But yeah, I read in all the barcodes from the fragments file manually and compared them to barcodes of the ATAC counts matrix. There're more barcodes in fragments file, but all barcodes from counts are in the fragments.

**Comment by timoast** [comment]
Setting `validate.fragments=FALSE` should only be used when you're 100% sure those cells are in the fragment file, and want to save a bit of time by skipping the check.

If there are more cells in the fragment file than in the count matrix that's fine, but if there are many fragments from other cells, it might take longer to find fragments from the cells you request. By default, we wait until we've seen a fragment from 50% of the cells before saying the cells are valid. This avoids mistakes where you give a wrong fragment file, for example, without taking too long by performing an exhaustive search. There's also a maximum number of lines in the fragment file that we search, by default 5e07. You can change this in the `CreateFragmentObject` function (see also `ValidateCells`)

**Comment by f6v** [comment]
@timoast thanks for the tip! I'm not sure I get this from `ValidateCells` docs:
> Fraction of input cells that can be unseen before returning TRUE. For example, tolerance = 0.01 will return TRUE when 99 have observed fragments in the file. 

So how do I run the most exhaustive search? I can set `max.lines = NULL`, but what would the value for `tolerance` be?

**Comment by timoast** [comment]
Tolerance is the fraction of cells that can be unseen, so set it to 0 for exhaustive search.

**Comment by f6v** [comment]
Sorry, I don't get the wording. Does 'fraction of cells that can be unseen` mean fraction of cells that don't have to be present in the fragments file? So if I set `tolerance = 0`, all the cells have to present in the fragments?

**Comment by timoast** [comment]
Yes

**Comment by f6v** [comment]
Thanks! I guess it's not a bug after all.
