### ISSUE TITLE
How to analyze multiple samples together?

### ISSUE THREAD

**Issue by judas840429** [timoast/signac#52]
Hi Tim,
Really Nice work in scATAC analysis!
I see scATAC-seq integration in the Vignettes.
If it is possible to have some functions or vignettes in comparative analyses like this part in scRNA-seq analysis. (https://satijalab.org/seurat/v3.1/immune_alignment.html)
Kind regards,
Judas

**Comment by timoast** [comment]
Thanks! I will try to add a vignette for comparative analysis soon, in the meantime you could follow a very similar workflow to as is shown in the Seurat immune alignment vignette. First integrate the datasets and find clusters, then look for differentially accessible peaks within a cluster across groups. You could then do [motif analysis](https://satijalab.org/signac/articles/motif_vignette.html) on the differentially accessible peaks.

This paper also demonstrates a nice approach for comparative analysis (see figure 5: https://www.nature.com/articles/s41587-019-0147-6).
