### ISSUE TITLE
Integration Error: Query cells not present in supplied DimReduc object.

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#536]
I have found transfer anchors of 24 objects using reference-based integration.  Now I would like to integrate these objects.  Here is the code that gives an error: 

```

library(Seurat)
library(Signac)

number.list<- c("99", "111", "127", "191", "196",
                "273", "347", "357", "372", "430",
                "542", "601","676", "688", "730", 
                "781", "963", "984", "1099", "1545",
                "1557", "1600", "1670", "1690")
main.dir <- '/path/to/working/directory/'
rds.list3 <- paste0('rds', c(148:(148+23)), "_", number.list, "srt_combined.peak.assay.rds")


atac.list <- list()
for (i in 1:24){
  message(i)
  atac.list[[i]] <- readRDS(paste0(main.dir, rds.list3[i]))
  atac.list[[i]] <- RunTFIDF(atac.list[[i]])
  atac.list[[i]] <- FindTopFeatures(atac.list[[i]], min.cutoff = 'q0')
  atac.list[[i]] <- RunSVD(atac.list[[i]])
}

int.features <- SelectIntegrationFeatures(atac.list, nfeatures = 10000)
ref <- which(number.list == '542')

anchors <- FindIntegrationAnchors(object.list = atac.list, 
                                  anchor.features = int.features, 
                                  reference = ref, k.filter = NA)
```

Lastly, here is where the error occurs: 

```

atac.integrated <- IntegrateData(anchorset = anchors,
                                 weight.reduction = rep('lsi', 24),
                                 dims = 2:30)

Finding integration vectors
Error in RunIntegration(filtered.anchors = filtered.anchors, reference = reference,  : 
  Query cells not present in supplied DimReduc object. Set weight.reduction to a DimReduc object containing the query cells.
Calls: IntegrateData ... MapQueryData -> my.lapply -> lapply -> FUN -> RunIntegration
Execution halted

```

I have already tried just using `weight.reduction = 'lsi'.`  I get an error along the lines of `weight.reduction[[2]]: subscript out of bounds` if I remember correctly.  So its telling me to put a dimreduct string for each object present.

**Comment by danielcgingerich** [comment]
Issue #71 says it can be a name of a dim reduc present in all objects.  Im pretty sure lsi is present in all object, so Im not understanding what R is having trouble with

**Comment by timoast** [comment]
From the `IntegrateData()` docs:

> Note that, if specified, the requested dimension reduction will only be used for calculating anchor weights in the first merge between reference and query, as the merged object will subsequently contain more cells than was in query, and weights will need to be calculated for all cells in the object.

The issue here is that you can't compute weights after merging the objects. I'd recommend running `IntegrateEmbeddings()` in your case, since you have so many objects, rather than `IntegrateData()`. See this discussion: https://github.com/timoast/signac/discussions/438
