### ISSUE TITLE
Signac Installation Issue: Dependency 'Go.db' unavailable

### ISSUE THREAD

**Issue by kmhum** [timoast/signac#55]
Hello - 

I was trying to analyze some scATAC data (alongside matching scRNA-seq samples) based on the Seurat vignette. I ran into an issue when trying to RunLSI that said the function has been migrated to Signac; TDF-IDF normalization works just fine, but the "Running SVD on TF-IDF matrix" step stalls out and reports the following: 

> Scaling cell embeddings
Warning messages:
1: RunLSI is being moved to Signac. Equivalent functionality can be achieved via the Signac::RunTFIDF and Signac::RunSVD functions; for more information on Signac, please see https://github.com/timoast/Signac 
2: RunLSI is being moved to Signac. Equivalent functionality can be achieved via the Signac::RunTFIDF and Signac::RunSVD functions; for more information on Signac, please see https://github.com/timoast/Signac 
3: RunLSI is being moved to Signac. Equivalent functionality can be achieved via the Signac::RunTFIDF and Signac::RunSVD functions; for more information on Signac, please see https://github.com/timoast/Signac

So I went to install Signac; I was able to install BiocManager with no issue and followed [your instructions](https://satijalab.org/signac/index.html), but when I tried to install Signac using devtools, I get the following response: 

> Error: Failed to install 'Signac' from GitHub:
  (converted from warning) dependency ‘GO.db’ is not available

Prior to the error, I am prompted to update packages; choosing to update or not update seems to have no impact on the success of the attempted Signac installation (and, for whatever it is worth, I have updated pretty much everything now). 

I'm running RStudio v. 1.2.5033 (Windows/PC) on top of R 3.6.2.

Am I doing something wrong? I appreciate your assistance - I'm relatively new to R, so please pardon any naivete on my part.

**Comment by timoast** [comment]
Hi, you should be able to fix this by installing GO.db: `BiocManager::install("GO.db")`

**Comment by kmhum** [comment]
Well, thanks for your input. This got me a little closer, but still running into errors. I was able to install GO.db, but Signac still hits a problem: 

> Installing package into ‘\\humacyte/dfs/users/knaegeli/My Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: dependencies 'AnnotationFilter', 'GenomicFeatures', 'TFBSTools', 'ggbio', 'motifmatchr', 'BSgenome' are not available for package 'Signac'
* removing '\\[filepath omitted]/R/win-library/3.6/Signac'
Error: Failed to install 'Signac' from GitHub:
  (converted from warning) installation of package ‘C:/[filepath omitted]/AppData/Local/Temp/Rtmp8g3JqC/file3ff4feda18/Signac_0.1.6.tar.gz’ had non-zero exit status

I've tried a few solutions for non-zero exit statuses which I found via Google, but thus far none have resolved the issue. Do I need to install all the dependencies separately?

**Comment by timoast** [comment]
Did you run `setRepositories(ind=1:2)`?

**Comment by kmhum** [comment]
So, yes, I did run `setRepositories(ind=1:2)` prior to installation.

Now I went back and figured I should just try everything again, and somehow or another I've taken a step backwards. When retrying, I was prompted to install GO.db (despite a successful installation earlier). In doing so, GO.db now had a non-zero exit status. The output of re-trying the GO.db installation now is this:

```
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing package(s) 'GO.db'
installing the source package ‘GO.db’
trying URL 'https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GO.db_3.10.0.tar.gz'
Content type 'application/x-gzip' length 31820873 bytes (30.3 MB)
downloaded 30.3 MB

* installing *source* package 'GO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : there is no package called 'GO.db'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'GO.db'
* removing '\\[filepath omitted]/My Documents/R/win-library/3.6/GO.db'

The downloaded source packages are in
	‘C:\[filepath omitted]\Rtmp675j67\downloaded_packages’
Installation path not writeable, unable to update packages: boot, foreign, MASS, nlme
Old packages: 'bibtex'
```
I am presented with the option to update or not update bibtex; no matter whether I choose to update 'bibtex' (a process that fails, by the way) or not, I get this: 

```
Warning messages:
1: In install.packages(...) :
  installation of package ‘GO.db’ had non-zero exit status
```

Also for whatever it is worth, when I run library(BiocManager), it does give the following:
```
Bioconductor version 3.10 (BiocManager 1.30.10), ?BiocManager::install for help
Attaching package: ‘BiocManager’
The following object is masked from ‘package:devtools’:
     install
```

But I now have a separate issue upstream of ever getting to devtools to install Signac. Everything other than 'bibtex' 

Any ideas? Am I at a point where it is worthwhile burning down the R/Rstudio installations and starting fresh? Thanks for your assistance in all of this!

**Comment by timoast** [comment]
I'd just suggest restarting R and running this code:

```r
BiocManager::install("GO.db")
setRepositories(ind=1:2)
devtools::install("timoast/signac")
```

**Comment by kmhum** [comment]
Thanks for all your help; I've restarted R (and my computer) a number of times and rerun this code and permutations therein. I just tried it again now. It still fails. 

What is new now that hadn't happened after your first response to help install GO.db is that I have reverted back to GO.db being unavailable and the error message when I try `BiocManager::install('GO.db')` embedded in the text output (bold is my own, for emphasis): 

```
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.2 (2019-12-12)
Installing package(s) 'GO.db'
installing the source package ‘GO.db’

trying URL 'https://bioconductor.org/packages/3.10/data/annotation/src/contrib/GO.db_3.10.0.tar.gz'
Content type 'application/x-gzip' length 31820873 bytes (30.3 MB)
downloaded 30.3 MB

* installing *source* package 'GO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
**Error in findpack(package, lib.loc) : there is no package called 'GO.db'**
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'GO.db'
* removing '\\[filepath omitted]/R/win-library/3.6/GO.db'
```

I'm genuinely perplexed. For whatever this is worth, this happens in both RStudio and the plain R interface.

**Comment by timoast** [comment]
That's very weird. According to [this](https://support.bioconductor.org/p/123334/) issue on Bioconductor support, you might be able to solve it using:

```r
BiocManager::install("GO.db", INSTALL_opts="--no-test-load")
```

**Comment by kmhum** [comment]
Thanks for that recommendation; the resolution they proposed within did not work for me, but they made mention to some of the network paths to which files were being written. So this sent me down a rabbit hole: one of my `.libPaths()` is a network location, apparently. This hasn't been an issue until today, but I think that could be the source of the installation of GO.db, at least. 

It seems like the issue here is specifically my local network address and writing to a network location - though that is yet to be confirmed, as I'm still trying to permanently modify the library locations. I can update this post later with a full solution - assuming I reach one. 

For posterity's sake (in case someone else comes across this issue), the comments [here](https://stackoverflow.com/questions/15217758/remove-a-library-from-libpaths-permanently-without-rprofile-site) and [here](https://stackoverflow.com/questions/15170399/change-r-default-library-path-using-libpaths-in-rprofile-site-fails-to-work) were helpful in removing library paths. 

Thanks for all your help!

**Comment by kmhum** [comment]
Following up on this issue to provide closure in case someone ever has my same issue. 

One of my default library paths referred to a network location at my institution. I've been running R/RStudio and Seurat for many months now and analyzed dozens of data sets and never had an issue with this. But now in trying to move into some scATAC data and installing Signac, I've hit the snags.

In order to fix this, I changed my library paths to local locations on the physical machine that I've assured to be write-able. In so doing, I had to uninstall and reinstall R and RStudio, because migrating the libraries manually broke many of the installed packages (including Seurat). Everything installed without reporting errors. 

From there, I reinstalled Seurat - but had some small issues with the package `"multtest"` not being installed - so I had to manually install that package through BiocManager. In the past when I installed Seurat, I didn't have to do this. But whatever - I installed multtest and Seurat works fine - I can run scRNA-seq scripts that I created previously without any issues. 

However, when I installed Signac now, I ran into this error: 

```

* installing *source* package 'Signac' ... 
** using staged installation 
** R 
** data 
*** moving datasets to lazyload DB 
** byte-compile and prepare package for lazy loading No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools' From .checkSubclasses(): subclass "ICMatrixList" of class "PWMatrixList" is not local and is not updated for new inheritance information currently;  [where=<environment: 0x000000001640c008>, where2=<environment: namespace:Signac>] 
** help 
*** installing help indices
   converting help for package 'Signac'
     finding HTML links ... done
     AddMotifObject                          html
     ApplyMatrixByGroup                   html
     AverageCounts                           html
     BinarizeCounts                          html
     CellsPerGroup                           html
     ChunkGRanges                            html
      ClosestFeature                          html
       ClusterMotifs                           html
       CountsInRegion                          html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/CountsInRegion.Rd:18: file link 'findOverlaps' in package 'IRanges' does not exist and so has been treated as a topic
     CoveragePlot                            html
     CreateMotifMatrix                       html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/CreateMotifMatrix.Rd:13: file link 'PFMatrixList' in package 'TFBSTools' does not exist and so has been treated as a topic 
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/CreateMotifMatrix.Rd:13: file link 'PWMatrixList' in package 'TFBSTools' does not exist and so has been treated as a topic
        CreateMotifObject                       html
       CreateRegionPileupMatrix                html
       CutMatrix                               html
       DownsampleFeatures                      html
       Extend                                  html
       ExtractCell                             html
       finding level-2 HTML links ... done

      FRiP                                    html
       FeatureMatrix                           html
       FilterFragments                         html
       FindMotifs                              html
       FindTopFeatures                         html
       FractionCountsInRegion                  html
       GRangesToString                         html
       GenomeBinMatrix                         html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/GenomeBinMatrix.Rd:14: file link 'seqlengths' in package 'GenomeInfoDb' does not exist and so has been treated as a topic
     GetCellsInRegion                        html
       GetFragments                            html
       GetGroups                               html 
      GetIntersectingFeatures                 html
       GetMotifData                            html
       GetMotifObject                          html
       GetReadsInRegion                        html
       InsertionBias                           html
       IntersectMatrix                         html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/IntersectMatrix.Rd:25: file link 'findOverlaps' in package 'IRanges' does not exist and so has been treated as a topic
     Jaccard                                 html
     MatchRegionStats                        html
     MergeWithRegions                        html
     Motif-class                             html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/Motif-class.Rd:21: file link 'DimReduc' in package 'Seurat' does not exist and so has been treated as a topic
     MotifDimPlot                            html
       MotifPlot                               html
       MultiRegionCutMatrix                    html
       NucleosomeSignal                        html
       PeriodPlot                              html
       RegionPileup                            html   
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/RegionPileup.Rd:35: file link 'ggplot2' in package 'ggplot2' does not exist and so has been treated as a topic
     RegionStats                             html
       RunChromVAR                             html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/RunChromVAR.Rd:29: file link 'Seurat' in package 'Seurat' does not exist and so has been treated as a topic
     RunMotifTSNE                            html
       RunMotifUMAP                            html
       RunSVD                                  html
       RunTFIDF                                html
       SetFragments                            html
       SetMotifData                            html
       StringToGRanges                         html
       TSSEnrichment                           html
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/TSSEnrichment.Rd:23: file link 'Seurat' in package 'Seurat' does not exist and so has been treated as a topic
     TSSPlot                                 html   
Rd warning: C:/[local filepath omitted]/AppData/Local/Temp/RtmpMtHdws/R.INSTALL2c8c5dd642db/Signac/man/TSSPlot.Rd:20: file link 'ggplot2' in package 'ggplot2' does not exist and so has been treated as a topic
     TabixOutputToDataFrame                  html
       atac_small                              html
       blacklist_ce10                          html
       blacklist_ce11                          html
       blacklist_dm3                           html
       blacklist_dm6                           html
       blacklist_hg19                          html
       blacklist_hg38                          html
       blacklist_mm10                          html
       subset.Motif                            html
** building package indices 
** testing if installed package can be loaded from temporary location No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools' 
** testing if installed package can be loaded from final location No methods found in package 'IRanges' for request: 'score' when loading 'TFBSTools' 
** testing if installed package keeps a record of temporary installation path 
* DONE (Signac)
```

If I just proceed and hope for the best by running `library(Signac)` I get this: 

```
No methods found in package ‘IRanges’ for request: ‘score’ when loading ‘TFBSTools’
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
```

And then I get an error about `hdf5r` not being installed - so I installed that manually (again, another package that did not require manual installation previously). 

From there, I can run everything in the PBMC scATAC tutorial just fine until I get to the line: `pbmc.atac <- RunLSI(pbmc.atac, n = 50, scale.max = NULL)`, which again warns that this functionality is moving over to Signac. 

The good news, though, is that those functions in Signac (`Signac::RunTFIDF` and `Signac::RunSVD`) seem to be functional now. So this is good.

Moving directories got me stuck a bit between a rock and a hard place, as it seems some packages - especially those required by Signac and BiocManager do not like writing to my institution's network locations but also won't accept packages that were installed to custom library paths. 

But manual installation of missing packages and ignoring all the warnings above of Seurat and other packages being treated as topics seems - for now - to have everything running OK. 

I welcome comments if you have opinions on any of this (or interpretation of the error messages above), but I mostly wanted to chronicle this for future users who might encounter similar problems.

**Comment by timoast** [comment]
Glad you were able to work this out, it sounds like it was a real hassle! I think most of these problems stem from issues with the TFBSTools dependency (eg the incorrect import of `score`, although this has been fixed in their latest [version](https://github.com/ge11232002/TFBSTools/commit/fd37aec26fcf8d5cf33c3a44b1ce71f317fa0d3e)), so I am working on some updates that will remove this dependency. 

The warning on `Seurat::RunLSI` is just noting that the function is being deprecated from Seurat and will be removed at some point. This is replaced by `Signac::RunTFIDF` and `Signac::RunSVD`, so I recommend using those two functions in your code rather than `RunLSI`.

**Comment by timoast** [comment]
@kmhum I've just released an update that removes the TFBSTools dependency, which should remove the  need to install `GO.db`
