### ISSUE TITLE
The combined analysis in mouse species

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#551]
Hi @timoast ,
    I wonder that if i perform the scRNA+ATAC in mouse species using macs2 in step 'peaks <- subsetByOverlaps(x = peaks, ranges = blacklist_hg38_unified, invert = TRUE). i want to ensure that the blacklist_hg38_unified can be setting or had any other prefered value can choose ?
    I guess that the mouse project should not be chose the hg38 blacklist ?
    Any advice would be appreciated
    hanhuihong

**Comment by timoast** [comment]
The `blacklist_hg38_unified` coordinates are for the human genome, so they won't work for mouse. You need to change parameters according to the species and genome build that you're using in your experiment.
