### ISSUE TITLE
Remove promoter peaks prior to clustering

### ISSUE THREAD

**Issue by laurabchopp** [timoast/signac#56]
Hi Tim,
Thanks for the great package for scATAC analysis!
I'm interested in removing promoter-associated peaks from the dataset to see how it affects clustering. I've used Homer to identify promoter-peaks, and have generated a list excluding these promoter-peaks. I assume the next step would be to generate a new matrix without the promoter peaks, but this is beyond my skillset (I tried). Is there any way this function could be added to Signac?
Thanks!

**Comment by timoast** [comment]
Hi Laura, you can prevent promoter-associated peaks from being used for dimension reduction and clustering by removing them from the set of variable features. For example:

```r
VariableFeatures(object) <- setdiff(VariableFeatures(object), promoter_peaks)
```

**Comment by laurabchopp** [comment]
That worked perfectly, thanks for the easy solution!
