### ISSUE TITLE
Peak Calling using MACS2

### ISSUE THREAD

**Issue by st-tky** [timoast/signac#560]
Dear Signac Team,

I'm struggling with peak calling within my dataset by CallPeaks function. 
First, I tried to reproduce the results in the Signac vignette, "Joint RNA and ATAC analysis: 10x multiomic." 
However, I got an error below (I think this is similar to the error of Issue #473):

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/MY_OUTDIR/SeuratProject_peaks.narrowPeak': No such file or directory

I tried some steps proposed in #473 , but I could not solve the error.
Would you tell me some advice to solve this error?

Thank you!

**Comment by timoast** [comment]
Please include the full code you're running

**Comment by st-tky** [comment]
Thank you for your quick response, and Sorry for the lack of enough information.

The following is the full code I copied from the vignette (Most codes are the same except for the paths to data or macs2):

##################################################
library(Signac)
library(Seurat)
library(EnsDb.Hsapiens.v86)
library(BSgenome.Hsapiens.UCSC.hg38)

set.seed(1234)

counts <- Read10X_h5("D:/scATAC-GEX multiome/human GEX referenced/demo/pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5")
fragpath <- "D:/scATAC-GEX multiome/human GEX referenced/demo/pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz"

# get gene annotations for hg38
annotation <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v86)
seqlevelsStyle(annotation) <- "UCSC"
genome(annotation) <- "hg38"

# create a Seurat object containing the RNA adata
pbmc <- CreateSeuratObject(
  counts = counts$`Gene Expression`,
  assay = "RNA"
)

# create ATAC assay and add it to the object
pbmc[["ATAC"]] <- CreateChromatinAssay(
  counts = counts$Peaks,
  sep = c(":", "-"),
  fragments = fragpath,
  annotation = annotation
)

pbmc

DefaultAssay(pbmc) <- "ATAC"

pbmc <- NucleosomeSignal(pbmc)
pbmc <- TSSEnrichment(pbmc)

VlnPlot(
  object = pbmc,
  features = c("nCount_RNA", "nCount_ATAC", "TSS.enrichment", "nucleosome_signal"),
  ncol = 4,
  pt.size = 0
)

# filter out low quality cells
pbmc <- subset(
  x = pbmc,
  subset = nCount_ATAC < 100000 &
    nCount_RNA < 25000 &
    nCount_ATAC > 1000 &
    nCount_RNA > 1000 &
    nucleosome_signal < 2 &
    TSS.enrichment > 1
)

pbmc

# call peaks using MACS2
peaks <- CallPeaks(pbmc, macs2.path = "D:/linux_home/miniconda3/bin/macs2")

**Comment by timoast** [comment]
Can you also confirm that you have write permission to the output directory? Can you also check whether you are able to run MACS2 on the fragment file outside of R/Signac?

**Comment by st-tky** [comment]
I followed the step you proposed at #473  (chmod +rw /myout_dir/Data/peak).
I used Ubuntu20.04 to give write permission to the output directory, which was a temporary one ( /Local/Temp/RtmpKw4G3b).
Is it not the right way to give permission?

I also checked that the output was "true" when running the command: dir.exists("/Local/Temp/RtmpKw4G3b").

I have not been able to try MACS2 outside of R/Signac yet, so I will try as soon as possible.
Then I will report the result here.

I am sorry if these steps are very basic.
Thank you.

**Comment by st-tky** [comment]
I checked that I can run MACS2 outside of R/Signac using Ubuntu.

**Comment by npojo** [comment]
Hello Signac Team, 
I am having the same problem as st-tky #560. 
I am running R from windows environment. 
I think #560 uses the same environment while #473 was possibly R from Linux. 
Is CallPeaks tested for the mixed environment: R-windows with MACS-Linux?
If so, how should outdir be stated (e,g, "c:/xxx/..." vs "/mnt/xxx/...)"
Thank you.

**Comment by npojo** [comment]
Follow up on my earlier post:
When R is running on Windows and macs2 on Ubuntu WSL, CallPeaks cannot work as it is.
This because paths play a dual role in R and in macs2.
I have kept the call to CallPeaks using Windows paths and hardcoded the `system `call CallPeaks with linux paths as follows:
`system('bash -c "/home/.../anaconda3/bin/macs2 callpeak -t /mnt/g/..../pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n SeuratProject --outdir /mnt/g/.../macs" ', wait=T,ignore.stderr = !verbose,ignore.stdout = !verbose)`
This works fine.

**Comment by st-tky** [comment]
Dear npojo,

Thank you for your kind comments.
I tried the step you proposed, but an error returned, no object 'verbose'.
The Path " /home/.../anaconda3/bin/macs2"  is the path to macs2 in the Linux directory, isn't it?
If so, isn't it necessary to specify the path like C:/.../home/.../anaconda3/...?
I really appreciate your help.

Thank you!

**Comment by npojo** [comment]
From within Ubuntu, write: `which macs2` and the response will be the path to macs2 which needs to be part of the bash command in the system command.

**Comment by st-tky** [comment]
Thank you for your very quick response！
I checked the right path using "which macs2", but the error still remains.
I set home directory in External HDD ( /mnt/d/.../miniconda3/...). 
Should I change home directory into C drive？ Or, is there any pitfall to run system command?

**Comment by timoast** [comment]
I don't know how combined ubuntu/windows works, but you will need to provide the path to macs2 on the same file system that R is running on

**Comment by TatyanaLev** [comment]
I had this same stubborn problem on an hpc, but specifying an outdir explicitly, instead of letting CallPeaks use the default tempdir, fixed it for me.

**Comment by Kamilloo1234** [comment]
> Follow up on my earlier post: When R is running on Windows and macs2 on Ubuntu WSL, CallPeaks cannot work as it is. This because paths play a dual role in R and in macs2. I have kept the call to CallPeaks using Windows paths and hardcoded the `system `call CallPeaks with linux paths as follows: `system('bash -c "/home/.../anaconda3/bin/macs2 callpeak -t /mnt/g/..../pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n SeuratProject --outdir /mnt/g/.../macs" ', wait=T,ignore.stderr = !verbose,ignore.stdout = !verbose)` This works fine.

Dear npojo,

thanks for the code. I had the same problem getting macs2 running on my windows R, while macs2 was installed on ubuntu WSL. So callpeaks worked for me in Ubuntu and I have also the output files. But now I have the problem that I would like to proceed in R/Signac with "keepStandardChromosomes" and "subsetByOverlaps" and finally combining different peak files into one like it is shown in the vignette "Joint RNA and ATAC analysis: 10x multiomic". Btw I have 4 ATAC Multiome samples/files. But how can I change the callpeak output files into a seqinfo class?

I am sorry, if this question might be too easy for you guys, but I am not so advanced in this field.

**Comment by rsggsr** [comment]
Just want to follow this thread. First, thanks @timoast for this great tool. I am currently trying to use signac/macs2 to do scATACseq analysis but on Window system it seems impossible to install macs2 on python. Therefore macs2 was installed on ubuntu (WSL). @npojo I am wondering if you could specify more clearly how to do it when R/signac is running on Windows but macs2 on Ubuntu WSL. Thanks!

**Comment by HelloWorldLTY** [comment]
Hi, I tried to specify one output path, but I still cannot run this successfully.
![image](https://user-images.githubusercontent.com/43333475/197111301-f8ea8462-3fea-44f7-aa42-8d680eadc970.png)
I tested my macs2. Moreover, I wonder if I do not run this callpeaks, will it affect too much for gene-peak link test? I found that I cannot find gene-peak link for my dataset, is it normal? Thanks.

**Comment by st-tky** [comment]
Hi guys,

This might not help you but just in case.
As @npojo already mentioned, R/Rstudio cannot perform MACS2 via python in Windows PC (If Windows users installed MACS2 in python via WSL, like Ubuntu, which is a potential cause of this problem).
In that case, please follow his script as mentioned before.
Or, you can perform MACS2 in python first (e.g., via WSL/Ubuntu) and use/specify the output file by the path. 
At least, I could solve my problem through these.

Good luck!

**Comment by HelloWorldLTY** [comment]
I used conda to install MACS2 and my system is linux. I can call macs2 in my system. I also wonder that if I do not call macs2 and will it affect too much for my gene-peak link finding.

**Comment by hira-anis** [comment]
> Follow up on my earlier post: When R is running on Windows and macs2 on Ubuntu WSL, CallPeaks cannot work as it is. This because paths play a dual role in R and in macs2. I have kept the call to CallPeaks using Windows paths and hardcoded the `system `call CallPeaks with linux paths as follows: `system('bash -c "/home/.../anaconda3/bin/macs2 callpeak -t /mnt/g/..../pbmc_granulocyte_sorted_10k_atac_fragments.tsv.gz -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n SeuratProject --outdir /mnt/g/.../macs" ', wait=T,ignore.stderr = !verbose,ignore.stdout = !verbose)` This works fine.

Hey npojo,
Will this work on a multiple fragment files? My seurat object is actually a merged object of 5 samples.

**Comment by robin-sto** [comment]
We are seeing this problem on our HPC also (In file(file, "rt") :  cannot open file .. No such file or directory)
although the full path is designated in the R script and the user has permission to write to the directory.  Has anyone 
found a solution to this?

**Comment by swainasish** [comment]
I solved this error by fixing the bed file. MACS2 expect the bed file to have 5 columns only: chrome, chromStart, chromEnd, barcode, and readSupport. But in some bed files, there are 6 columns, Using AWK to remove the last column, I did this by;
```
awk '{print $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5}'  fragment.bed > fragments_awk.bed

```	
Next, sort the bed file, bgzip and tabix by, 
```
sort -k1,1 -k2,2n fragments_awk.bed > fragments_awk_sorted.bed
bgzip fragments_awk_sorted.bed
tabix fragments_awk_sorted.bed 
```
Finally, the CallPeaks command is able to run for me.
