### ISSUE TITLE
Display TF name instead of motif ID on plots?

### ISSUE THREAD

**Issue by scZfish** [timoast/signac#562]
I am using FeaturePlot() and DotPlot() to visualize enriched motifs in clusters of interest (this is a great feature BTW!). I am using JASPAR2020 as the source of the pwms, pretty much according to the vignette (except using BSgenome.Drerio.UCSC.danRer11). 

Everything works great, but just wondering how to set the feature label to be the transcription factor name rather than the motif ID?

**Comment by timoast** [comment]
Hi, you can look up the motif name using a motif ID and vice-versa using the `ConvertMotifID()` function. To change the title of the feature plot you will need to change the titles manually using functions in ggplot2, for example:

```r
library(Seurat)
library(ggplot2)

p <- FeaturePlot(pbmc_small, features = head(rownames(pbmc_small)))
to_rename <- 1:6 # replace with a vector containing the names to use
for (i in seq_along(p)) {
  p[[i]] <- p[[i]] + ggtitle(to_rename[[i]])
}
```
