### ISSUE TITLE
hormany integrated found non-isolation on cluster

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#57]
Hi Tim,
     I found the workflow had lots of problem on it, The hormany integrated showing NA cluster legend, when i take it to integrated ATAC data. On the second hand, using harmony integrated two ATAC data showing perfect melted, but the clusters cell have not isolated, which mixed in each other cluster.
   The code showing below:

```r
    integrated_atac <- MergeWithRegions(
  object.1 = Fat,
  object.2 = Health,
  sep.1 = c(":", "-"),
  sep.2 = c(":", "-")
)

integrated_atac <- FindTopFeatures(integrated_atac, min.cutoff = 0)
integrated_atac <- RunTFIDF(integrated_atac)
integrated_atac <- RunSVD(integrated_atac, n = 30, reduction.name = 'lsi', reduction.key = 'LSI_')
integrated_atac <- RunUMAP(integrated_atac, dims = 1:30, reduction = 'lsi')
p5 <- DimPlot(integrated_atac, group.by = 'tech', pt.size = 0.1) + ggplot2::ggtitle("Unintegrated")

library(harmony)
View(integrated_atac@meta.data)
integrated_atac <- RunSVD(integrated_atac, n = 30, reduction.name = 'lsi', reduction.key = 'LSI_') ###要运行这个才能整合

integrated_atac <- RunHarmony(
  object = integrated_atac,
  group.by.vars = 'orig.ident',
  reduction = 'lsi',
  assay.use = 'peaks',
  project.dim = FALSE
)
?RunHarmony
integrated_atac <- RunUMAP(integrated_atac, dims = 1:30, reduction = 'harmony')
DimPlot(integrated_atac, group.by = 'orig.ident', pt.size = 0.1) + ggplot2::ggtitle("Harmony integration")
View(integrated_atac@meta.data)
table(integrated_atac@meta.data$orig.ident)
table(Idents(integrated_atac))
##############################
integrated_atac <- FindNeighbors(
  object = integrated_atac,
  reduction = 'lsi',
  dims = 1:30
)

integrated_atac <- FindClusters(
  object = integrated_atac,
  verbose = FALSE
)

DimPlot(object = integrated_atac, label = TRUE )
```

the picture showing follow:
 
![image](https://user-images.githubusercontent.com/41668708/71792223-e5ead980-3072-11ea-9563-61c2863355d0.png)

**Comment by timoast** [comment]
Here you have clustered on the original LSI coordinates rather than the harmony-corrected coordinates, which might be why you see disagreement between the UMAP visualization (which you made using the harmony-corrected coordinates) and the clustering.

The presence of `NA` in the legend means that some cells have `NA` for their current identity. If the identities are determined by clustering, there should not be any `NA` values. Can you confirm that some cells are assigned `NA` cluster values if you run the above code in a new R session?

**Comment by honghh2018** [comment]
Thanks for your ugent reply,
    can you fix the code i pasted on this post, i don't what be first run on your workflow at https://satijalab.org/signac/articles/integration.html site, which code should be run in oder.

**Comment by timoast** [comment]
To use the harmony-corrected coordinates set `reduction="harmony"` in `FindNeighbors`
