### ISSUE TITLE
Cell Barcodes not matching in input: Cannot add a different number of cells than already present

### ISSUE THREAD

**Issue by phoebee-h** [timoast/signac#570]
Hi,

I am using Signac for getting back more cells by customized filtering threshold, so, I have to use the "raw_feature_bc_matrix" instead of the "filtered_feature_bc_matrix". Don't know whether it is a problem using the "raw_feature_bc_matrix" as input that makes the error:  `"Error: Cannot add a different number of cells than already present"`. Both my data and [data downloaded from the 10x official](https://support.10xgenomics.com/single-cell-multiome-atac-gex/datasets/1.0.0/pbmc_unsorted_3k) generated this error. The cell barcodes are matching in `counts$"Gene Expression"` and `counts$Peaks`, but it somehow shows different number from these two matrices during `CreateChromatinAssay`. 

I saw a previous reported question,  https://github.com/timoast/signac/issues/173, and I set `counts = counts$Peaks[, colnames(pbmc)]` but still not working.

```
counts <- Seurat::Read10X("/mnt/10x_test/raw_feature_bc_matrix/")
fragpath <- "/mnt/10x_test/atac_fragments.tsv.gz" 
pbmc <- SeuratObject::CreateSeuratObject(counts = counts$"Gene Expression", assay = "RNA") 
pbmc[["ATAC"]] <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath)
```

![image](https://user-images.githubusercontent.com/28743573/115187509-0890ec80-a116-11eb-97f7-c1a8677d45e8.png)

I used the default packages in Signac docker at first but encountered some problems. Thus, packages were reinstalled.

```
SeuratObject_4.0.0
Seurat_4.0.1
Signac_1.1.1
```

Thank you.
Phoebe.

**Comment by timoast** [comment]
It's possible that some cells are being removed in the `CreateChromatinAssay` step if they have zero counts. Can you try setting `min.counts=-1` in `CreateChromatinAssay()`? Alternatively, can you create the chromatin assay first before adding it to the Seurat object and check the number of cells in the assay? eg:

```r
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath)
ncol(chrom_assay)
```

You might also be better off performing some basic filtering on the raw matrix before creating the Seurat object, otherwise you'll have cells in there with a very low number of counts. You could remove all cells with <50 counts in either the gene expression or ATAC assays first, for example.

**Comment by phoebee-h** [comment]
The cell number is 307437:
```
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath)
ncol(chrom_assay)
```
![image](https://user-images.githubusercontent.com/28743573/115323125-07b19680-a1ba-11eb-8e31-34cb4c2adeb9.png)


The argument is unused:
```
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath, min.counts = -1)
```

![image](https://user-images.githubusercontent.com/28743573/115323305-7393ff00-a1ba-11eb-86d0-049ebec3b406.png)


And then, consider about creating another object in two steps:
```
pbmc <- SeuratObject::CreateSeuratObject(counts = counts$"Gene Expression", assay = "RNA", min.cells = 1) 
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath)

pbmc_2<- SeuratObject::CreateSeuratObject(counts = chrom_assay, assay = "ATAC")
pbmc_2[["RNA"]]<- SeuratObject::CreateSeuratObject(counts = counts$"Gene Expression"[,colnames(pbmc_2)])
```
![image](https://user-images.githubusercontent.com/28743573/115327382-6d555100-a1c1-11eb-9eb8-a80dad44d790.png)


The `dim(counts$"Gene Expression"[,colnames(pbmc_2)]) ` is "36601, 307437". Why the cell barcodes become the row in new created "RNA" assay, which makes it fail to integrate?

**Comment by timoast** [comment]
Sorry the argument name is `min.features` not `min.counts`

The issue with your second test, when you create the object in two steps, is that you're creating a Seurat object rather than assay. This should work:

```r
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks[, colnames(pbmc)], sep = c(":", "-"), fragments = fragpath)
pbmc_2 <- CreateSeuratObject(counts = chrom_assay, assay = "ATAC")
pbmc_2[["RNA"]]<- CreateAssayObject(counts = counts$"Gene Expression"[,colnames(pbmc_2)])
```

**Comment by phoebee-h** [comment]
Thank you for your help. I have successfully made the object. 
With or without `min.features = -1`  should work, just create the object reversely (ATAC first and then RNA assay ). However the cells would be filtered if not specify the parameter, as you mentioned.

```
counts <- Seurat::Read10X("/mnt/10x_test/raw_feature_bc_matrix/")
fragpath <- "/mnt/10x_test/atac_fragments.tsv.gz" 

# With min.features = -1
chrom_assay <- CreateChromatinAssay(counts = counts$Peaks, sep = c(":", "-"), fragments = fragpath, min.cells = 1, min.features = -1)
pbmc <- CreateSeuratObject(chrom_assay , assay = "ATAC")
pbmc[["RNA"]] <- CreateAssayObject(counts = counts$"Gene Expression")

# Without min.features = -1, colnames should be matched in ATAC assay
chrom_assay2 <- CreateChromatinAssay(counts = counts$Peaks, sep = c(":", "-"), fragments = fragpath, min.cells = 1)
pbmc2 <- CreateSeuratObject(chrom_assay2 , assay = "ATAC")
pbmc2[["RNA"]] <- CreateAssayObject(counts = counts$"Gene Expression"[, colnames(pbmc2)])
```
![image](https://user-images.githubusercontent.com/28743573/116173392-16122c00-a73f-11eb-8f4e-6b0dfefc9e7f.png)


One last question about the `min.features`. I wonder why the negative "-1" would work?

**Comment by timoast** [comment]
> (1) Just wonder why the negative "-1" in min.features would work?

If the cell has 0 features detected it would be removed, setting to -1 forces all cells to be retained

> (2) The rownames in ATAC assay were separated by "chr1-180746-181080", instead of "chr1:180746-181080", why? I thought I've already set the sep = c(":", "-") ?

The `sep` parameter in `CreateChromatinAssay()` specifies the separators used in the input matrix, which for cellranger will be `c(":", "-")`. After creating the chromatin assay, the separators are changed which is why you see "-" and "-" in your assay
