### ISSUE TITLE
Some puzzled problem on motif analysis.

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#58]
Hi Tim,
    There is one question showing below:
     # Get a list of motif position frequency matrices from the JASPAR database
pfm <- getMatrixSet(
  x = JASPAR2018,
  opts = list(species = 9606, all_versions = FALSE)
)
 It was so confused that I saw your workflow code on motif analysis, which The code i showed above was mouse brain analyized using species human, 9606, to get pfam MatrixSet. This was mistake or something? please explain what situation on this code?

**Comment by timoast** [comment]
The human and mouse TF motifs are highly similar, but certain key motifs for the brain are missing from the mouse database, eg MEF2C. For this reason I used the human motifs for the example in the vignette

**Comment by JulongWei** [comment]
It would be better for beginners if you clarify it in tutorial.

**Comment by timoast** [comment]
I've now updated the vignette to use the core vertebrate motifs
