### ISSUE TITLE
Problem about  ATAC integrated for CoveragePlot plotting error

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#59]
Hi Tim,
     I running CoveragePlot to plot the chromosome coverage rate in each sample occurred error when I used two ATAC integrated data. The error showing below:
     error: Faceting variables must have at least one value
additional: Warning messages:
1: Factor `group` contains implicit NA, consider using `forcats::fct_explicit_na` 
2: In max(downsampled_coverage$coverage, na.rm = TRUE) :
  max was not present in parameter；coverge -Inf
The code i was running following:
   region1 <- 'chr16:10796004-10797160'
region2 <- GRangesToString(subset(gene.coords, symbol=="Prm1")) ###根据基因获取坐标

CoveragePlot(
  object = testic,
  region = region2,
  sep = c(":", "-"),
  annotation = EnsDb.Mmusculus.v79,
  extend.upstream = 5000,
  extend.downstream = 5000,
  ncol = 1
)

**Comment by timoast** [comment]
Here you've converted the `granges` for the Prm1 gene to a string using the default separator `c("-", "-")`, but they are using the separator `c(":", "-")` to convert back to `granges` in the plotting function call. Remove the `sep` argument in `CoveragePlot` and you should not have the error.

The examples in the vignettes are not meant to be copied verbatim, you will need to change arguments depending on your own data and use-case.
