### ISSUE TITLE
mouse brain tutorial issues

### ISSUE THREAD

**Issue by JBreunig** [timoast/signac#6]
Looking forward to utilizing Signac!

When I was running through the mouse brain tutorial, I got:
"Error in is(file, "TabixFile") : 
  object 'fragment_file_filtered' not found"
after running
> gene.activities <- FeatureMatrix(
+   fragments = fragment_file_filtered,
+   features = genebodyandpromoter.coords,
+   cells = colnames(brain),
+   chunk = 10
+ )

should it be: 
gene.activities <- FeatureMatrix(
+   fragments = **fragment.path**,
+   features = genebodyandpromoter.coords,
+   cells = colnames(brain),
+   chunk = 10
+ )

Also, sorry if I missed this, but where can I download the allen_brain.rds file?
Thanks in advance!
Josh

**Comment by timoast** [comment]
Hi, the `fragment_path_filtered` is defined in the "Optional step: Filtering the fragment file" drop-down in the vignettes, but you will be able to substitute that path to the un-filtered fragment file (`fragment.path`) and get the same result.

The allen_brain.rds file was made using [this](https://github.com/satijalab/Integration2019/blob/master/preprocessing_scripts/allen_brain.R) R script, with data downloaded from the Allen institute using [this](https://github.com/satijalab/Integration2019/blob/master/preprocessing_scripts/allen_brain.sh) script.

To make things easy I have uploaded the allen_brain.rds dataset to dropbox [here](https://www.dropbox.com/s/kqsy9tvsklbu7c4/allen_brain.rds?dl=0) and the pbmc_10k_v3.rds dataset [here](https://www.dropbox.com/s/zn6khirjafoyyxl/pbmc_10k_v3.rds?dl=0), and I'll add these links to the vignettes later.

**Comment by JBreunig** [comment]
Great, thank you!

**Comment by darlene003** [comment]
Hi I'm trying to download allen_brain.rds but it seems to be deleted?

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/952
