### ISSUE TITLE
what different parameter between --normalize=depth of cellrange-atac aggr and Signac RunTFIDF or RunSVD?

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#60]
Hi Tim,
    Nice works for this Signal integrated Tool.
    The cellrange-atac aggr and Your Package integrated workflow showing different way to merge multiple sample into one dataset. however the normlize parameter of two about normlized data whether or not was different? 
    if The cellrange-atac seted normlize parameter, then Should be not run TFIDF or SVD on Signac aggregated ?
   please advices,
    Thanks.

**Comment by timoast** [comment]
If you use the normalization methods in `cellranger-atac aggr`, still need to run `RunTFIDF`.  TF-IDF is the first step in [latent semantic indexing](https://en.wikipedia.org/wiki/Latent_semantic_analysis#Mathematics_of_LSI)
