### ISSUE TITLE
Export peaks of specific cluster as a BAM file

### ISSUE THREAD

**Issue by st-tky** [timoast/signac#600]
Dear Signac team,

Thank you for providing a nice package!
I wonder if we can export a bam file containing peaks of specific clusters.
I want to use the bam file to investigate cluster-specific Motifs by other platforms, such as HOMER.
I already got peaks by running macs2.
Could you tell me how to export peaks as a bam file or alternatives to investigate Motifs in Signac platform?

Thank you!

**Comment by timoast** [comment]
I think you mean a BED file?

To export a BED file containing peak coordinates specific to a given cluster, you would first find differential peaks for the cluster (https://satijalab.org/signac/articles/pbmc_vignette.html#find-differentially-accessible-peaks-between-clusters-1) and then write those peak coordinates to a file.
