### ISSUE TITLE
CoveragePlot argument extend.upstream/extend.downstream

### ISSUE THREAD

**Issue by joschif** [timoast/signac#601]
Hi, this is not really a feature request or bug report, but I've noticed that the `extend.upstream/extend.downstream` arguments of `CoveragePlot` seem to ignore the strand info of the gene and always assume that it's +, so that 'upstream' always means lower genomic coordinates. Is this desired behavior or could this be changed so 'upstream/downstream' are actually relative to the TSS of the gene and match the behavior of `Extend`?

**Comment by timoast** [comment]
For now this is the expected behaviour, we could in future consider updating it to consider the strand of the gene if a gene name is supplied for the `region` argument

**Comment by timoast** [comment]
Closing this for now, I think this is the behaviour we want to keep
