### ISSUE TITLE
integrate ATAC data occured error on step TransferData parameter weight.reduction = pbmc[['lsi']]

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#61]
Hi Tim,
     Integrated ATAC data triggered an error on step TransferData parameter,weight.reduction = pbmc[['lsi']], which  conform to your workflow rule. but wiredly, as i change the parameter weight.reduction='lsi', it worked. But I can figure it out if it was correctly?
     please advice me this solution was apprectiated.
The code showing below:
     integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = 'lsi',  ####
  preserve.order = TRUE
)  can work.

    integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = ATAC[['lsi']],  ####
  preserve.order = TRUE
) not worked, occured error.

**Comment by timoast** [comment]
Yes, using `weight.reduction="lsi"` will also work. You can supply a dimreduc object or the name of a dimreduc present in the query. See the documentation for `IntegrateData` for more information
