### ISSUE TITLE
Error for CreateChromatinAssay() function

### ISSUE THREAD

**Issue by ZhengJIN94** [timoast/signac#610]
Hello,

When I tried to import data as the tutorial, it gave back some error information.

> Computing hash
> Checking for 3694 cell barcodes
> 
>  *** caught segfault ***
> address (nil), cause 'memory not mapped'
> 
> Traceback:
>  1: validateCells(fragments = filepath, cells = cells, find_n = find_n,     max_lines = max.lines, verbose = verbose)
>  2: ValidateCells(object = frags, verbose = verbose, ...)
>  3: CreateFragmentObject(path = fragments, cells = cells, validate.fragments = validate.fragments,     verbose = verbose, ...)
>  4: CreateChromatinAssay(counts = counts, sep = c(":", "-"), genome = "mm10",     fragments = "/dir/fragments.tsv.gz",     min.cells = 0, min.features = 0)

Here is my code,
```
library(Signac)
library(Seurat)
library(tidyverse)
counts <- Read10X_h5(filename = "/dir/filtered_peak_bc_matrix.h5")
chrom_assay <- CreateChromatinAssay(counts = counts, sep = c(":", "-"), genome = 'mm10', fragments = '/dir/fragments.tsv.gz', min.cells = 0, min.features = 0)
```

The file size:
filtered_peak_bc_matrix.h5 (12M)
fragments.tsv.gz (254M)

The computational resource:
Available memory (352G)
CPUs (40+)

Could I get some suggestion to avoid such problem?
Thank you so much!

**Comment by timoast** [comment]
See #609
