### ISSUE TITLE
issue with AddChromatinModule

### ISSUE THREAD

**Issue by kelsell15** [timoast/signac#615]
While I can get this to work with some sets of peaks, other lists frequently produce the error: Error in sparseMatrix(i = unlist(x = feat.idx, use.names = FALSE), j = unlist(x = j,  : 
  NA's in (i,j) are not allowed

Even if the list is loaded the same way, in the same format, the same length, everything is the same as lists of peaks I've used to properly Add a new chromatin module in the past. I usually use the pipeline: 
> peaks <- read.table("StitchCart.txt", header = FALSE, sep = "", dec = ".")
> features <- list(module2 = peaks$V1)
> C = AddChromatinModule(C, features = features, genome = BSgenome.Drerio.UCSC.danRer11)

And the error only occurs sometimes

**Comment by timoast** [comment]
Can you provide the full code you're running and the output of `sessionInfo()`? Also, are you able to provide a reproducible example using either the test data provided in Signac (`atac_small`) or one of the datasets used in the online Signac [vignettes](https://satijalab.org/signac/articles/overview.html)?

**Comment by timoast** [comment]
Closing this now since I haven't heard back, feel free to reopen if you can get the requested additional information

**Comment by wjyzidane** [comment]
I just want to leave a command that works for me. 

I tried the function with the dataset "atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5". The matrix looks like this:
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/34944811/225378538-c01bc12c-389a-48d2-9c96-ddd0074179df.png">

If I use list("module1" = c("chr1-713460-714823")), it works.
If I use list("module1" = c("chr1:713460-714823")), it gives the error as above.
