### ISSUE TITLE
About differential peak in different integrated mothed

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#62]
Hi Tim,
     I found lots of differential peak, the number about two or three thousand, which Base on the Standard workflow of integrated data in Signac. nevertheless, The less differential peak, just twenty or thirty ,found using cell-atac aggr for integrated data.
    why the number of differential peak  is significantly different about on two integrated way?
     Thanks

**Comment by timoast** [comment]
If I understand correctly, you're saying that you find fewer differentially accessible peaks when using cellranger aggr to combine datasets, compared with merging the data? Cellranger aggr downsamples the reads to an equal level across the batches, so it's expected that you would lose some sensitivity. Note that we don't recommend performing differential expression or accessibility using integrated data, for explanation see several closed issues in the [Seurat](https://github.com/satijalab/seurat/issues) package
