### ISSUE TITLE
Getting UMAP of TSS 

### ISSUE THREAD

**Issue by beginner984** [timoast/signac#620]
Hello

I have standard scATAC-seq by cell-ranger atac pipeline

I am fine when running with `filtered_peak_bc_matrix.h5` file but for promoter-proximal/distal regions I always get error using this file **_filtered_tf_bc_matrix.h5_**

Please have a look

```
> counts <- Read10X_h5(filename = "filtered_tf_bc_matrix.h5")
Warning message:
In sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you
```
```
> metadata <- read.csv(
+   file = "singlecell.csv",
+   header = TRUE,
+   row.names = 1
+ )
```

`> chrom_assay <- CreateChromatinAssay( +   counts = counts, +   sep = c(":", "-"), +   genome = 'hg38', +   fragments = 'fragments.tsv.gz', +   min.cells = 10, +   min.features = 200 + ) 
`
`
Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]) :    some values in the "start" column cannot be turned into numeric values In addition: Warning messages: 1: Expected 3 pieces. Additional pieces discarded in 1 rows [67].  2: Expected 3 pieces. Missing pieces filled with `NA` in 534 rows [1, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 24, ...].`
 
Do you know the reason please?

**Comment by timoast** [comment]
You should not use the 10x Genomics TF matrix to construct a ChromatinAssay, as the features in that matrix are not genomic coordinates. See the documentation from 10x: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/matrices
