### ISSUE TITLE
Error in getting the coverage 

### ISSUE THREAD

**Issue by beginner984** [timoast/signac#621]
Hello

I am not able to solve this error of my standard scATAC-seq from cell-ranger atac pipeline

I am very new to single cell science and I need help please

This is my data

```
> pbmc
An object of class Seurat 
68197 features across 995 samples within 1 assay 
Active assay: peaks (68197 features, 0 variable features)
``
```
> pbmc[['peaks']]
ChromatinAssay data with 68197 features for 995 cells
Variable features: 0 
Genome: hg38 
Annotation present: FALSE 
Motifs present: FALSE 
Fragment files: 1 
```
And this the the error

```
> CoveragePlot(
+     object = pbmc,
+     region = rownames(da_peaks)[1],
+     extend.upstream = 40000,
+     extend.downstream = 20000
+ )
Error in FindRegion(object = object, region = region, sep = sep, assay = assay,  : 
  Gene not found
```
```
> CoveragePlot(
+     object = pbmc,
+     region =c('MS4A1', 'CD3D', 'LEF1', 'NKG7', 'TREM1', 'LYZ'),
+     extend.upstream = 40000,
+     extend.downstream = 20000
+ )
Error in FindRegion(object = object, region = region, sep = sep, assay = assay,  : 
  Gene not found
```

**Comment by timoast** [comment]
You have not added a gene annotation to the assay, so you can't request genomic regions by gene name since this information is not present in the object. See the online documentation for information about adding gene annotations to the object: https://satijalab.org/signac/
