### ISSUE TITLE
GeneActivity: "Error in `rownames<-`(x = `*tmp*`, value = as.vector(x = gene.key[rownames(x = counts)])) : "

### ISSUE THREAD

**Issue by bschilder** [timoast/signac#625]
Super excited to use this tool!

I'm processing snATAC data from [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE174367). 

```R
library(Seurat)
atac_mat <- Seurat::Read10X_h5(filename = "Morabito2020/GSE174367_snATAC-seq_filtered_peak_bc_matrix.h5")
atac_meta <- read.csv("Morabito2020/GSE174367_snATAC-seq_cell_meta.csv.gz", row.names = "Barcode")

chrom_assay <- Signac::CreateChromatinAssay(
  counts = atac_mat,
  sep = c(":", "-"),
  genome = 'hg19',
  # fragments = '<none_available>',
  min.cells = 10,
  min.features = 200
)

atac <- Seurat::CreateSeuratObject(counts = chrom_assay, 
                                   assay = "ATAC", 
                                   meta.data =atac_meta)
```

I wasn't able to run the[ QC steps](https://satijalab.org/signac/articles/pbmc_vignette.html#computing-qc-metrics-1) bc they don't provide a fragments file. But despite this, everything after that in the tutorial was working ok, until I got to here:

```R
gene.activities <- GeneActivity(atac)
```
```
Extracting gene coordinates
Error in `rownames<-`(x = `*tmp*`, value = as.vector(x = gene.key[rownames(x = counts)])) : 
  attempt to set 'rownames' on an object with no dimensions
```

I'm guessing this might be related to not having done the QC steps. But is there some way bypass this in the meantime?

Many thanks, 
Brian

**Comment by timoast** [comment]
The `GeneActivity()` function requires a fragment file to run, so you won't be able to use it without having a fragment file for the dataset. We will work on adding more informative error messages here

**Comment by bschilder** [comment]
Got it, thank you for the lightning fast response!

**Comment by bschilder** [comment]
I just reran with the fragments file and was able to run the initial QC steps, but it seems there's still some metadata info I'm missing:

```R
# compute nucleosome signal score per cell
atac <- NucleosomeSignal(object = atac)

# compute TSS enrichment score per cell
atac <- TSSEnrichment(object = atac, fast = FALSE)

atac$pct_reads_in_peaks <- atac$peak_region_fragments / atac$passed_filters * 100
```
```
Error: Cannot find 'peak_region_fragments' in this Seurat object
```

I can't seem to find the step where these variables are computed. Did I miss something?

**Comment by bschilder** [comment]
Ah, apologies I just found this note in the documentation. I'll try these steps:
> Note that the last three metrics can be obtained from the output of CellRanger (which is stored in the object metadata), but can also be calculated for non-10x datasets using Signac (more information at the end of this document).

**Comment by timoast** [comment]
I've now added a check in `GeneActivity()` that the fragment file information is present

**Comment by bschilder** [comment]
Sorry, one last follow up question. Followed the instructions at the end of the tutorial, but seems there's still some variables missing:

```R
atac <- NucleosomeSignal(object = atac)
atac <- TSSEnrichment(object = atac, fast = FALSE)

## This step takes a long time
total_fragments <- CountFragments(syn25745094$path)
## Missing row.names
row.names(total_fragments) <- total_fragments$CB
data.table::fwrite(total_fragments, 
                   "raw_data/Morabito2020/total_fragments.csv.gz")
## Add metadata back into atac object
atac$fragments <- total_fragments[colnames(atac), "frequency_count"]

atac <- FRiP(
  object = atac,
  assay = "ATAC",
  total.fragments = 'fragments'
)

atac$blacklist_fraction <- FractionCountsInRegion(
  object = atac, 
  assay = "ATAC",
  regions = Signac::blacklist_hg19
)

atac$pct_reads_in_peaks <- atac$peak_region_fragments / atac$passed_filters * 100
atac$blacklist_ratio <- atac$blacklist_region_fragments / atac$peak_region_fragments
```

Is this simply a matter of differing variable names? Here's my best guesses:
- peak_region_fragments = fragments
- pct_reads_in_peaks = FRiP?
- blacklist_region_fragments = blacklist_fraction
- passed_filters = ? (can't seem to find this one anywhere)

**Comment by timoast** [comment]
Yes, the naming is not exactly the same as in cellranger. `peak_region_fragments` would not be the same as `fragments` here, however. `fragments` is the total number of sequenced fragments for the cell, and `peak_region_fragments` (from cellranger) is the number of fragments in peaks, which would be similar to a column sum of the peak counts matrix in Signac. `passed_filters` (cellranger) is similar/same as `fragments` in the Signac code above.

**Comment by bschilder** [comment]
Got it, thank you for the clarification @timoast !
