### ISSUE TITLE
Finding co-accessible networks with Cicero

### ISSUE THREAD

**Issue by MaryGoAround** [timoast/signac#627]
Hello

I am going to find co-accessible peaks but I get error

Please have a look

```
> library(Signac)
> library(Seurat)
> library(SeuratWrappers)
> library(ggplot2)
> library(patchwork)
> library(cicero)
> # convert to CellDataSet format and make the cicero object
```
```
> bone.cds <- as.cell_data_set(x = bone)
Warning: Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object
```

`bone.cicero &lt;- make_cicero_cds(bone.cds, reduced_coordinates = reducedDims(bone.cds)$UMAP) Error: is(object = cds, class2 = "CellDataSet") is not TRUE`

In one of github issues I tried 
```

> bone[["UMAP"]] <- bone[["umap"]]
Warning message:
Cannot add objects with duplicate keys (offending key: UMAP_), setting key to 'umap_' 
```
Thank you for any suggestion

**Comment by timoast** [comment]
My guess is that you have an older version of cicero installed, designed for monocle2 rather than monocle3. See installation instructions here: https://cole-trapnell-lab.github.io/cicero-release/docs_m3/#installing-cicero

**Comment by qiuxx221** [comment]
Hi, I am using monocle 3 and cicero 1.3.9 to generate cicero object but it has the same error. Could you take a look and see if something here is going wrong? Thank you for the help

TCR.cds <- as.cell_data_set(x = TCR)
Warning: Monocle 3 trajectories require cluster partitions, which Seurat does not calculate. Please run 'cluster_cells' on your cell_data_set object
TCR.cicero <- make_cicero_cds(TCR.cds, reduced_coordinates = reducedDims(TCR.cds)$UMAP)
Error: is(object = cds, class2 = "CellDataSet") is not TRUE

> TCR.cds
class: cell_data_set 
dim: 149662 21768 
metadata(0):
assays(2): counts logcounts
rownames(149662): chr1-3010600-3011487 chr1-3066123-3066998 ... chrY-90810622-90811451 chrY-90812343-90813232
rowData names(0):
colnames(21768): AAACGAAAGAAATGGG-3 AAACGAAAGAACGTCG-3 ... TTTGTGTTCTGGTACA-1 TTTGTGTTCTTCCGTG-3
colData names(30): orig.ident nCount_peaks ... ident Size_Factor
reducedDimNames(2): LSI UMAP
mainExpName: peaks
altExpNames(0):
