### ISSUE TITLE
LinkPeaks with a single gene

### ISSUE THREAD

**Issue by XinWang19** [timoast/signac#629]
Hi,
When I performed LinkPeaks with a single gene name like:

> LinkPeaks(
> object = seurat.obj,
> peak.assay = "ATAC",
> expression.assay = "RNA",
> genes.use = "INS")

It returned:

    No peaks fall within distance threshold 
    Have you set the proper genome and seqlevelsStyle for ATAC assay?"

I found the problem is caused by line 51 and 57. When genes.use is a single character, the expression.data will become a vector without a row.name.

> expression.data <- expression.data[genes.keep, ]
> genes <- rownames(x = expression.data)

**Comment by timoast** [comment]
Thanks for reporting, this should now be fixed on the develop branch. See installation instructions here: https://satijalab.org/signac/articles/install.html#development-version-1
