### ISSUE TITLE
Changing default colors in coverageplot

### ISSUE THREAD

**Issue by laurabchopp** [timoast/signac#63]
Hi Tim, 
Is there a way to change the colors of the tracks in CoveragePlot?
I use a different set of colors than the default Seurat to color my clusters, and I'd like the tracks to match.
I can't figure out a way to pass this color vector into CoveragePlot. 
I looked into grid_plot, but there are no arguments to change the colors. 
Thanks so much!

**Comment by timoast** [comment]
Hi, the function returns a ggplot object so you can style the object using standard ggplot functions. For example:

```r
library(ggplot2)
p <- CoveragePlot(object, region)
p + scale_fill_viridis_d()
```

See the ggplot2 docs for information about adding a manual color scale: https://ggplot2.tidyverse.org/reference/scale_manual.html

This currently only works if you do not include a gene annotation

**Comment by laurabchopp** [comment]
Great, thank you SO Much! I used:
p <- CoveragePlot(object, region)
p + scale_fill_manual(values = color24)
Where color24 is my vector of colors, and it worked perfectly.

**Comment by erebboah** [comment]
Have there been any updates to CoveragePlot that allow changing the colors while including a gene annotation?
