### ISSUE TITLE
SVD embeddings with singular values

### ISSUE THREAD

**Issue by hoondy** [timoast/signac#630]
Suppose you are running an SVD on log(TF-IDF) matrix, x

```
s <- svd(x)
x_hat <- s$u %*% diag(s$d) %*% t(s$v)
```
where x_hat is the reconstruction of the original matrix x.

Your "embedding" in this case is the dot product between the left singular matrix, u, and the diagonal singular values, d, which represent word similarity (in the context of scATAC, chromatin accessibility similarity).

```
x %*% v = s$u %*% diag(s$d) %*% t(s$v) %*% s$v = s$u %*% diag(s$d)
```

x_hat then becomes the dot product between embedding and transposed loadings

However, in Signac, Embeddings(atac[['lsi']]) is defined as just the left singular matrix, u. I am wondering if this is expected. I would like to know if it would be important to have the diag. matrix in the embeddings.

```r
atac <- RunTFIDF(atac)
atac <- FindTopFeatures(atac, min.cutoff = 'q0')
atac <- RunSVD(atac, n=100, verbose=TRUE, scale.embeddings=FALSE, irlba.work= 1000)

# SVD components were stored in misc
components=Misc(atac[['lsi']])

# Embeddings(atac[['lsi']]) == components$u
head(Embeddings(atac[['lsi']]))
head(components$u)

# alternatively, we can replace embeddings with s$u *%* diag(s$d)
atac.alt <- atac
atac.alt[['lsi']]@cell.embeddings <- Embeddings(atac[['lsi']]) %*% diag(components$d)

# then results of RunUMAP(atac) != RunUMAP(atac.alt)
```

**Comment by timoast** [comment]
Yes this is intended, not a bug. You could certainly explore results from weighting by singular value if you wanted to (and as you've found, the raw irlba output is stored in the dimension reduction `misc` slot)
