### ISSUE TITLE
Can't use rlsi in integration pipeline. " 'arg' should be one of 'cca', 'rpca " error

### ISSUE THREAD

**Issue by ah3918** [timoast/signac#634]
https://www.rdocumentation.org/packages/Seurat/versions/4.0.1/topics/FindIntegrationAnchors

Above is the link for the function used in the Signac integration pipeline, which I am following here https://satijalab.org/signac/articles/integrate_atac.html

I'm coming across the above issue; this is my code.

> `  
> mergedobject<-seuratobjlist[[1]]
> for(i in 2:length(seuratobjlist)){
> mergedobject<-merge(mergedobject,seuratobjlist[[i]])
>   }
> mergedobjet<-FindTopFeatures(mergedobject,min.cutoff=10)
> mergedobject <- RunTFIDF(mergedobject)
> mergedobject <- RunSVD(mergedobject)
> mergedobject <- RunUMAP(mergedobject, reduction = "lsi", dims = 2:30)
> 
>      integration.anchors <- FindIntegrationAnchors(
>     object.list = seuratobjlist,
>     anchor.features = rownames(seuratobjlist[[1]]),
>     reduction = "rlsi",
>     dims = 2:30
>   )
> `
> 
> 
> `Error in match.arg(arg = reduction): 'arg' should be one of "cca", "rpca"
> Traceback:
> 
> 1. FindIntegrationAnchors(object.list = seuratobjlist, anchor.features = rownames(seuratobjlist[[1]]), 
>  .     reduction = "rlsi", dims = 2:30)
> 2. match.arg(arg = reduction)
> 3. stop(gettextf("'arg' should be one of %s", paste(dQuote(choices), 
>  .     collapse = ", ")), domain = NA)
> `

**Comment by timoast** [comment]
As the vignette says:

> Note that this functionality currently requires the development version of Seurat. This can be installed from GitHub, see the installation instructions here

You need the development version of Seurat installed
