### ISSUE TITLE
Easy Installation with Conda

### ISSUE THREAD

**Issue by marianogabitto** [timoast/signac#637]
I am having troubles satisfying the dependencies of Signac if I create a condo package from scratch. I think that I went around it by using the commands below. 

So....

Would it be possible that you provide an easy installation from scratch using conda ? It will be great to have something like the instructions listed below. These two instructions are incomplete as point 1 is not exhaustive and many things are installed when you run point 2.

1)
conda create -n signac -c conda-forge -c bioconda r-base=4.0 r-seurat=4* bioconductor-genomicranges bioconductor-rsamtools r-biocmanager 

2) Then, within R, run:
install.packages("Signac")

Thanks

**Comment by timoast** [comment]
We might try to support this in the future, but in the meantime I'd recommend trying the [docker image](https://satijalab.org/signac/articles/install.html#docker-1) if you want an easy/fast way to start using Signac

**Comment by timoast** [comment]
It looks like Signac is actually available already on Bioconda: https://bioconda.github.io/recipes/r-signac/README.html
