### ISSUE TITLE
Problems in installing signac

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#64]
Hi,

I get this error when I try to install Signac:

ERROR: dependencies ‘TFBSTools’, ‘ggbio’, ‘motifmatchr’ are not available for package ‘Signac’

When I try to install the above dependencies, I get an error asking for DirichletMultinomial. When I try to install DirichletMultinomial, it fails to compile. I remember that you mentioned before that you will release a version that does not depend on DirichletMultinomial. Is this version available now?

Any suggestion for the above errors?

Thanks

**Comment by timoast** [comment]
The issue with installing DirichletMultinomial is likely due to [gsl](https://stackoverflow.com/questions/7033927/how-to-correctly-install-gsl-library-in-linux#7033971)

The new release is not available yet, I am hoping to have it ready soon
