### ISSUE TITLE
Error in ClosestFeature

### ISSUE THREAD

**Issue by eryildiz** [timoast/signac#647]
Hi Tim,

I am trying to generate the closest genes using my peaks file however I am doing something wrong when requesting the appropriate assay that I could not figure out.

![image](https://user-images.githubusercontent.com/32553198/120723002-b3225c00-c485-11eb-8fed-a7a2b895d24c.png)

Why do you think that I am getting this error?

Thanks a lot!

**Comment by timoast** [comment]
The requested assay is not a ChromatinAssay (as stated in the error message). You can only run this function on a ChromatinAssay
