### ISSUE TITLE
CallPeaks with Error in file(file, "rt") cannnot open the connection

### ISSUE THREAD

**Issue by qlan20** [timoast/signac#648]
Dear Tim,
I am encountering an error when using CallPeaks function following the Signac tutorial. The code and error are below. I was wondering how to solve this problem? Thanks.

> DefaultAssay(pbmc) <- "peaks"
> peaks <- CallPeaks(object = pbmc, group.by = "predicted.id", macs2.path="/d/Share/miniconda3/envs/peaks/bin/MACS2")

---------------
Processing file D:\R\projects\signac-tutorial\pbmc_scATAC\data\atac_v1_pbmc_10k_fragments.tsv.gz
Keeping 7060 cell barcodes
Splitting into 13 files
Done Processing 189 million lines                 

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'C:\Users\123\AppData\Local\Temp\RtmpayIeXI/CD14+_Monocytes_peaks.narrowPeak': No such file or directory

**Comment by timoast** [comment]
Can you provide the output of `sessionInfo()`?

See also https://github.com/timoast/signac/issues/560

**Comment by qlan20** [comment]
Thanks for pointing to the #560 . I am using the Ubuntu and R in Windows (probably they are under different users etc). I was able to run CallPeaks(MACS2) as suggested in #560 

`
system('bash -c "/mnt/d/Share/miniconda3/envs/peaks/bin/MACS2 callpeak -t /mnt/d/R/projects/signac-tutorial/pbmc_scATAC/data/atac_v1_pbmc_10k_fragments.tsv.gz -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n SeuratProject --outdir /mnt/d/R/projects/signac-tutorial/call-peaks/results"')

df <- read.table(
  file = "/mnt/d/R/projects/signac-tutorial/call-peaks/results/SeuratProject_peaks.narrowPeak",
  col.names = c("chr", "start", "end", "name",
                "score", "strand", "fold_change",
                "neg_log10pvalue_summit", "neg_log10qvalue_summit",
                "relative_summit_position")
)

peaks <- makeGRangesFromDataFrame(df = df, keep.extra.columns = TRUE)
`

**Comment by timoast** [comment]
Ok, closing this now as it seems to be related to the previous windows/ubuntu issue
