### ISSUE TITLE
The corresponding library for mouse cells?

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#65]
Hi,

I think this library is for human, right?
library(EnsDb.Hsapiens.v75)

What is the corresponding one for mouse?

And this command for human also: gene.ranges <- genes(EnsDb.Hsapiens.v75)

What is the corresponding one for mouse?

Thank you

**Comment by timoast** [comment]
This is shown in the mouse brain vignette: https://satijalab.org/signac/articles/mouse_brain_vignette.html
