### ISSUE TITLE
LinkPeaks fails if length(genes.use)==1

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#653]
Hi,

Found following peculiar problem:

Fails:
> LinkPeaks(s.data, peak.assay = "peaks", expression.assay = "RNA", n_sample=200,  genes.use=c("Tal1"), min.distance=2000)
Testing  genes and 181451 peaks
Error in LinkPeaks(s.data, peak.assay = "peaks", expression.assay = "RNA",  : 
  No peaks fall within distance threshold
Have you set the proper genome and seqlevelsStyle for peaks assay?

Fails:
> LinkPeaks(s.data, peak.assay = "peaks", expression.assay = "RNA", n_sample=200, genes.use=c("Gata2"), min.distance=2000)
Testing  genes and 181451 peaks
Error in LinkPeaks(s.data, peak.assay = "peaks", expression.assay = "RNA",  : 
  No peaks fall within distance threshold
Have you set the proper genome and seqlevelsStyle for peaks assay?

Works:
> LinkPeaks(s.data, peak.assay = "peaks", expression.assay = "RNA", n_sample=200, genes.use=c("Tal1","Gata2"), min.distance=2000)
Testing 2 genes and 181451 peaks

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/629
