### ISSUE TITLE
problem in using Read10X_h5

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#66]
Hello,

I have a problem in reading the .h5 file using Read10X_h5. Is there an alternative way to use the Read10X function instead and use the folder filtered_peak_bc_matrix

I know the problem is because I cannot install the hdf5 and this problem did not appear with me when using my personal computer. But I have to use the cluster and cannot install hdf5 on it.

Thank you for your understanding

**Comment by timoast** [comment]
Yes, see the section "Loading matrices into R" on the 10x support website here: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/matrices

**Comment by ahmedabbas81** [comment]
Thank you,

And I will give mtx to createSeuratObject() function instead of counts, right?

Thank you very much

**Comment by timoast** [comment]
Yes that's right
