### ISSUE TITLE
Unable to create a chrom assay

### ISSUE THREAD

**Issue by eryildiz** [timoast/signac#660]
I am trying to use my bed file to create a chromatin assay but it gives me the error below. Do I need to modify it?

```
chrom_assay_aml <- CreateChromatinAssay(
  counts = counts_aml,
  sep = c(":", "-"),
  genome = 'hg38',
  fragments = 'merged.filt.500.bed',
)
```
The error:
![image](https://user-images.githubusercontent.com/32553198/121634233-0aea3580-ca39-11eb-8bd6-7fbd355818c6.png)

A snippet of my bed file:
![image](https://user-images.githubusercontent.com/32553198/121634317-2ce3b800-ca39-11eb-9067-23e6dedbcd3e.png)

**Comment by timoast** [comment]
Your bed file does not look like a valid fragment file. Please see [here](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments) for more information
