### ISSUE TITLE
CallPeaks bedgraph output

### ISSUE THREAD

**Issue by gegenhu** [timoast/signac#663]
Hi,

Is it possible to generate a bedgraph file with the CallPeaks function by passing "bdg" and "SPMR" to the additional.args parameter and setting an output directory?

Thanks,
Bruno

**Comment by timoast** [comment]
This was not the intended use-case for the `CallPeaks()` function, if you want to run MACS2 in other modes I'd recommend using the `SplitFragments()` function to generate the bed files, and then running MACS2 itself with whatever parameters you want
