### ISSUE TITLE
LinkPeaks p-values

### ISSUE THREAD

**Issue by gegenhu** [timoast/signac#664]
Hi,

I am running LinkPeaks on different gene sets and noticed that the linkage p-values change depending on the number of genes specified with the "genes.use" parameter. I thought correlation analysis was performed on each gene independently, so I'm wondering why the p-values change depending on the input gene list?

Here is the code:

```
signac_obj <- LinkPeaks(object = signac_obj,
peak.assay = "peaks",
expression.assay = "RNA",
genes.use = "Etl4",
min.cells = 160,
distance = 7e+05)

as.data.frame(Links(signac_obj))
  seqnames    start      end width strand      score gene
1     chr2 19812987 19909780 96794      * 0.22768575 Etl4
2     chr2 19909706 19909780    75      * 0.08666936 Etl4
                    peak   zscore       pvalue
1 chr2-19812349-19813624 5.117118 1.551194e-07
2 chr2-19909218-19910193 2.274099 1.148003e-02
```

Compared to:

```
signac_obj <- LinkPeaks(object = signac_obj,
peak.assay = "peaks",
expression.assay = "RNA",
genes.use = c("Etl4", "Gad1"),
min.cells = 160,
distance = 7e+05)

as.data.frame(Links(signac_obj))
  seqnames    start      end  width strand       score gene
1     chr2 19812987 19909780  96794      *  0.22768575 Etl4
2     chr2 19909706 19909780     75      *  0.08666936 Etl4
3     chr2 69885569 70553072 667504      *  0.05509653 Gad1
4     chr2 70553072 70629613  76542      *  0.07913916 Gad1
5     chr2 70553072 71160534 607463      * -0.05374141 Gad1
                    peak    zscore       pvalue
1 chr2-19812349-19813624  5.021293 2.566239e-07
2 chr2-19909218-19910193  2.351881 9.339365e-03
3 chr2-69885154-69885984  1.937176 2.636189e-02
4 chr2-70629291-70629934  3.081632 1.029347e-03
5 chr2-71160117-71160950 -2.152852 1.566516e-02
```

**Comment by timoast** [comment]
`LinkPeaks()` calculates p-values for each peak-gene link based on the z-score generated by computing an expected distribution of correlation coefficients by sampling a background set of peaks matched for different characteristics (GC content, length, accessibility...). Since sampling is involved, the exact p-value will change slightly based on which peaks were chosen for the background set. Setting a random seed will ensure the samples are reproducible.
