### ISSUE TITLE
problem using brain <- RunUMAP(  )

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#67]
Hello,

Whenever I run this command:
brain <- RunUMAP(
  object = brain,
  reduction = 'lsi',
  dims = 1:30
),
the kernel dies. I removed it and continued the program and it worked. What may be the problem in it?

Thank you

**Comment by ahmedabbas81** [comment]
When I use TSNE:

brain <- RunTSNE(
  object = brain,
  reduction = 'lsi',
  dims = 1:30
)

It works normally

**Comment by timoast** [comment]
Please post a reproducible example in the [Seurat](https://github.com/satijalab/seurat) package
