### ISSUE TITLE
Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  :    attempt to set 'colnames' on an object with less than two dimensions

### ISSUE THREAD

**Issue by yanzhang19** [timoast/signac#681]
Hi,
I am following your code to work on mouse ATAC analysis, but have the error with TSSEnrichment (Error in `colnames<-`(`*tmp*`, value = seq_len(length.out = region.width) -  : 
  attempt to set 'colnames' on an object with less than two dimensions).

Following is the code I used:
getwd()
library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)
library(ggplot2)
library(patchwork)
set.seed(1234)
counts <- Read10X_h5(filename = "../Desktop/ATACC57P7A2/filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "../Desktop/ATACC57P7A2/singlecell.csv",
  header = TRUE,
  row.names = 1
)
chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'mm10',
  fragments = '../Desktop/ATACC57P7A2/fragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)
P7 <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)
P7
P7[['peaks']]
granges(P7)
# extract gene annotations from EnsDb
annotations <- GetGRangesFromEnsDb(ensdb = EnsDb.Hsapiens.v75)
# change to UCSC style since the data was mapped to hg19
seqlevelsStyle(annotations) <- 'UCSC'
genome(annotations) <- "mm10"
# add the gene information to the object
Annotation(P7) <- annotations
# compute nucleosome signal score per cell
P7 <- NucleosomeSignal(object = P7)

# compute TSS enrichment score per cell
P7 <- TSSEnrichment(object = P7, fast = FALSE)

And this is my version of R
> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen     

Is mouse "mm10" the right ref to use?
Thank you so much for your help
Sincerely
Yan

**Comment by timoast** [comment]
Here you have mouse data but are using the human gene annotations.

**Comment by yanzhang19** [comment]
Tim, Appreciated your response.
I did figure this is the issue and fixed that.
I am new to ATAC, in fact I have one more question while following the tutorial but using my own sample:
For code

P7$nucleosome_group <- ifelse<https://rdrr.io/r/base/ifelse.html>(P7$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
FragmentHistogram<https://satijalab.org/signac/reference/FragmentHistogram.html>(object = P7, group.by = 'nucleosome_group')

this code gave me error message said it is out of range;
then I skipped this, the next step for blacklist_ratio, there is no points (or dots) on the graph.

Do you think these two issue related?
Any suggestion about the range, why?
Thank you so much.
Sincerely
Yan
________________________________

**Comment by yanzhang19** [comment]
Tim,
To be precise on the issue, here is the error message I had:
> P7$nucleosome_group <- ifelse(P7$nucleosome_signal > 4, 'NS > 4', 'NS < 4')
> FragmentHistogram(object = P7, group.by = 'nucleosome_group')
Error in reads[[1]] : subscript out of bounds

And following is the graph I had for the blacklist_ratio
[cid:3e214e73-6301-4e8a-a4fd-badc6e7163fe]
I presume these two issues are related, but I do not understand why it is out of bound and how to fix it.

I have a 3rd question:
Before you run "integrating with ScRNAseq" data, how far do you need to analyze the ScRNAseq data; or to say in what stage for the ScRNAseq data be analyzed?

Thank you and have a great weekend.
Yan
________________________________
