### ISSUE TITLE
using default macs2 peak calling might miss signals

### ISSUE THREAD

**Issue by k326xh** [timoast/signac#682]
Hi,

I've been reading about the way macs2 works on the cellranger fragments files, and begin to think that the current default settings might miss half of the useful signals. 
From my understanding, both ends of the fragments from the cellranger output are cut sites and worth being included for peak calling. But currently, every fragment only shows up once in the fragments file. And when that is used as input for macs2, it will be taken like reads/tags, with only 5' end of each fragment being considered for shifting and extensions. 
If what I described above is correct, then I would propose to add a function to duplicate the fragments and label the original fragments as on positive-strand while the duplicates on negative-strand prior macs2 peak calling. In this way, both ends of the same fragment can be included for peak calling. 
Please correct me if I misunderstood how Signac handles macs2 peak calling, thanks!

**Comment by timoast** [comment]
Not sure this is required, see https://github.com/macs3-project/MACS/issues/145 and https://github.com/macs3-project/MACS/discussions/435

**Comment by k326xh** [comment]
I see. Considering the high short fragment proportion, it is probably not necessary. Thanks, Tim!

**Comment by jhjiang2020** [comment]
> Not sure this is required, see [macs3-project/MACS#145](https://github.com/macs3-project/MACS/issues/145) and [macs3-project/MACS#435](https://github.com/macs3-project/MACS/discussions/435)

@timoast If I understand correctly, macs2 will treat the per-group combined bed files as single-end reads with `-f BED --nomodel`, and thereby ignore the paired information PLUS lose half of the signals. This might cause wacky results in peak calling and downstream analysis.


Comparing to the cut site pileup outputted by Cell Ranger ARC, the peaks called using only 5‘ end information (the default setting) seem to be slightly shifted towards 5' (see the upper track in the attached image). 

After modifying the fragment files and keep cut sites at both ends, I did have better results with the same macs2 settings, which successfully captured the 3' part of our peaks (as shown in the lower track). 

![igv_snapshot](https://user-images.githubusercontent.com/75499605/133525799-79b9a3e4-150d-4734-adb7-52387cd015ef.png)

**Comment by jhjiang2020** [comment]
> A special mode will be triggered while the format is specified as BAMPE or BEDPE. In this way, MACS3 will process the BAM or BED files as paired-end data. Instead of building a bimodal distribution of plus and minus strand reads to predict fragment size, MACS3 will use actual insert sizes of pairs of reads to build fragment pileup. <br/><br/>The BEDPE format is a simplified and more flexible BED format, which only contains the first three columns defining the chromosome name, left and right position of the **fragment** from Paired-end sequencing. See [MACS3 docs](https://github.com/macs3-project/MACS/blob/master/docs/callpeak.md)

It might be useful to specify the format as `BEDPE` when calling peaks from cellranger fragments files? 

Here's what I got after simply changing `-f BED` to `-f BEDPE`: 

![igv_snapshot](https://user-images.githubusercontent.com/75499605/133618914-2b2735e4-ae46-47c5-9563-57d102c85980.png)

**Comment by timoast** [comment]
Hi @jhjiang2020, thanks for pointing out the `BEDPE` option, I think this could be a good solution. I've added a `format` parameter to `CallPeaks` to allow setting `-f BEDPE`, with the default still set to "BED"
