### ISSUE TITLE
SRA fastq to 10X raw fastq ？

### ISSUE THREAD

**Issue by TheSallyGardens** [timoast/signac#69]
May i ask you a question?
I am using fastq-dump to split  scATAC SRA form NCBI,but it create only two fastq file(R1,R2).
![深度截图_选择区域_20200110115634](https://user-images.githubusercontent.com/40382381/72124600-5b6ee680-33a0-11ea-9e13-1a8141e30164.png)

10X's raw fastq  just like this
![深度截图_选择区域_20200110115918](https://user-images.githubusercontent.com/40382381/72124703-a8eb5380-33a0-11ea-9e11-9ecd4a7225a1.png)
Best wish !

**Comment by rnsherpa** [comment]
Hi! Just wondering if you found the solution to this. I have the same problem right now.
