### ISSUE TITLE
issue with chrom_assay

### ISSUE THREAD

**Issue by yanzhang19** [timoast/signac#692]
Dear Signac people,
I have issue running chrom_assay  with mouse data this week.
It went ok last week, but when I run with new data, and tried with old data from last week, it showed same error message.  Please see below:

> chrom_assay <- CreateChromatinAssay(
+   counts = counts,
+   sep = c(":", "-"),
+   genome = 'mm10',
+   fragments = 'C:/Users/yzh08653/Documents/P28/ATACC57P28/fragments.tsv.gz',
+   min.cells = 10,
+   min.features = 200
+ )
Computing hash
Checking for 7594 cell barcodes
Error in .order_seqlevels(chrom_sizes[, "chrom"]) : 
  !anyNA(m31) is not TRUE
Called from: .order_seqlevels(chrom_sizes[, "chrom"])
Browse[1]>

I practiced with the PBMC human data after I am having this issue, it went through with no issue.
Appreciate your help.
Sincerely
Yan

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/687

Please search previous issues before creating a new issue
