### ISSUE TITLE
what the difference between cellranger-atac aggr and  Signac's merge function

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#695]
The cellRanger-atac aggr and merge function in signac package can perform similar functions---combine different samples.
I want to know what the difference between these two method. which method more appropriate to merge different sample?

**Comment by timoast** [comment]
See the documentation for cellranger-atac aggr: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/aggr

By default cellranger-atac aggr subsamples data to the same depth per sample, so you will remove fragments unless setting `--normalize=none`.
