### ISSUE TITLE
FindIntegrationAnchors Error

### ISSUE THREAD

**Issue by tzhu-bio** [timoast/signac#696]
Thanks for your Signac!

First, I run the **CreateChromatinAssay** with **sep = c(":", "-")**, but the results are not sep with ":" and  "-".

`> head(rownames(colon[["peaks"]])) 
[1] "chr1-18861-19378"   "chr1-57554-59363"   "chr1-82264-84330"  
[4] "chr1-102523-102924" "chr1-112094-115149" "chr1-116523-116897"
`

Second ,I get the error with **FindIntegrationAnchors**

See [https://github.com/satijalab/seurat/issues/4690](url)

**Comment by timoast** [comment]
The `sep` parameter defines the separators used in the input count matrix, not the output. The output will always be formatted as `-`, `-`
