### ISSUE TITLE
Which ensembl version suits for cellranger-atac-2.0?

### ISSUE THREAD

**Issue by dmsalsgh97** [timoast/signac#697]
Hi, I want to use Signac on my cellranger-atac-2.0 output.

I installed the developed version, and it works well.
However, I wonder know which ensembl version. 

In the vignettes and Install section on the Signac main page says EnsDb.Hsapiens.v86 suits for hg38.
When I searched the 10x homepage, they say reference is generated using (GENCODEv32/Ensembl98).

In that case, which version should I use for working with cellranger-atac-2.0.0 output?

Thanks!

**Comment by timoast** [comment]
You need to use a gene annotation that is compatible with the genome assembly used to map the data. This is  not related to the version of cellranger used. This table provides a mapping of genome assemblies to ensemble gene annotations: https://useast.ensembl.org/info/website/archives/assembly.html
