### ISSUE TITLE
Issue of fragments reading in

### ISSUE THREAD

**Issue by ZheLiu1991** [timoast/signac#7]
while reading in fragments information with command line:

fragment.path <- "/Users/outs/fragments.tsv.bgz"

scatac12wpcsignac <- SetFragments(
  object = scatac12wpcsignac,
  file = fragment.path
)

got this error:

Error in SetFragments(object = scatac12wpcsignac, file = fragment.path) : 
  Requested file does not exist or is not indexed

Which fragment file should we use, there is a tsv.bgz and a fragments.tsv.gz.tbi from 10x Cell ranger outputs.

**Comment by timoast** [comment]
Hi, the fragments.tsv.bgz file contains the fragments and the fragments.tsv.bgz.tbi is the fragments index file. You need both files present in the same directory, but supply the path to the fragments.tsv.bgz file in all functions in Signac that require a fragments file path (`SetFragments`, `FeatureMatrix`, etc).

**Comment by ZheLiu1991** [comment]
Thank you so much, appreciate it.

There is still an error when running NucleosomeSignal function. 

Extracting reads in requested region
Error: scanTabix: read line failed (error code 2); corrupt or invalid file?
 path: /Users/liuzhe/scATAC/12WPC_scATAC_signac/fragments.tsv.gz
 index: /Users/liuzhe/scATAC/12WPC_scATAC_signac/fragments.tsv.gz.tbi

I am pretty sure that I got both files in same directory.

Thanks.

**Comment by timoast** [comment]
Can you post the full code you ran?

If possible, could you also try following the [PBMC vignette](https://satijalab.org/signac/articles/pbmc_vignette.html) using the dataset from 10x Genomics linked to at the beginning of the vignette to verify that you get the expected results using that dataset and code?

**Comment by ZheLiu1991** [comment]
counts <- Read10X_h5(filename = "~/scATAC/12WPC_integration/filtered_peak_bc_matrix.h5")

metadata <- read.csv(
  file = "~/scATAC/12WPC_scATAC_signac/singlecell.csv",
  header = TRUE,
  row.names = 1
)

scatac12wpcsignac <- CreateSeuratObject(
  counts = counts,
  assay = 'peaks',
  project = 'ATAC',
  min.cells = 1,
  meta.data = metadata
)

fragment.path <- '/Users/liuzhe/scATAC/12WPC_scATAC_signac/fragments.tsv.gz'

scatac12wpcsignac <- SetFragments(object = scatac12wpcsignac,file = fragment.path)

#Optional step: Filtering the fragment file
#fragment_file_filtered <- "/Users/liuzhe/scATAC/12WPC_scATAC_signac/fragments.tsv.gz"
#FilterFragments(
 # fragment.path = fragment.path,
 # cells = colnames(scatac12wpcsignac),
 # output.path = fragment_file_filtered)
#scatac12wpcsignac <- SetFragments(object = scatac12wpcsignac, file = fragment_file_filtered)

#Computing QC Metrics
scatac12wpcsignac <- NucleosomeSignal (object = scatac12wpcsignac)

**Comment by timoast** [comment]
Thanks, and the second part of my question: do you get the expected results when using a public 10x Genomics dataset?

**Comment by rlevantovsky** [comment]
Hi, different user, same issue. To answer your question, I am running into this error both when running the PBMC vignette from the tutorial, and trying to apply the same code to a public 10X genomics data set (https://support.10xgenomics.com/single-cell-atac/datasets/1.1.0/atac_hgmm_500_v1).

When I run the PBMC tutorial, this is what I get:
![image](https://user-images.githubusercontent.com/53229601/62142073-a813a900-b2bb-11e9-908e-56228877dd55.png)

I also run into errors when trying to generate the correct QC metrics plots. 
Errors:
![image](https://user-images.githubusercontent.com/53229601/62142224-e90bbd80-b2bb-11e9-81a6-d8416e91be6e.png)

And the plots themselves do not match the ones in the tutorial:
![image](https://user-images.githubusercontent.com/53229601/62142268-004aab00-b2bc-11e9-9101-e9e4dc43b3ee.png)

I appreciate any advice you might have!

**Comment by timoast** [comment]
Hi @rlevantovsky, do you have both the fragments file and the index present in the same directory? The first error says that either the fragments.tsv.gz file or the fragments.tsv.gz.tbi file (or both) was not present at the path specified. All the subsequent errors are due to not having the file present. 

Can you confirm whether both files are present at the path you have specified? What happens if you run this in R:

```r
file.exists(fragment.path)
file.exists(paste0(fragment.path, 'tbi'))
```

**Comment by timoast** [comment]
Closing this issue now as I haven't heard back, but please open another issue if you have any more problems

**Comment by Lynnna** [comment]
Hi, Tim. I used the Signac 1.0.0 to analyze my scATAC-seq data, and I could not find the  "SetFragments" function.

**Comment by timoast** [comment]
@Lynnna `SetFragments` was removed in Signac 1.0.0. See the updated [vignettes](https://satijalab.org/signac/articles/overview.html) for more information, and the [Fragment class documentation](https://satijalab.org/signac/articles/data_structures.html#the-fragment-class-1)

**Comment by Lynnna** [comment]
I see. Thank you very much.

**Comment by wuzhigui** [comment]
Hello,everyone ! I download the newest version of Seurat and Signac .But ,I got a new error here : When  I  run `chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'hg19',
  fragments = 'fragments.tsv.gz',
  min.cells = 10,
  min.features = 200)
)` 
I got the feedback 👍
![image](https://user-images.githubusercontent.com/70992194/112841642-509e8f80-90d3-11eb-9856-0df38dcbcc00.png)
What does this mean?
