### ISSUE TITLE
it might be an old issue but

### ISSUE THREAD

**Issue by hjack123** [timoast/signac#70]
how do i solve with the following error?

Error in Read10X_h5(filename = h5name) : 
  Please install hdf5r to read HDF5 files

**Comment by hjack123** [comment]
tried installing by 

install.packages("hdf5r")

didnt work

**Comment by timoast** [comment]
Can you elaborate on how it didn’t work?

**Comment by hjack123** [comment]
Hi thanks for your reply. 
the same error msg occurred.  I solved by following 10x webpage to read the matrix...

**Comment by timoast** [comment]
I don't know which error message you're referring to, but since this is an issue with `hdf5r` not Signac, and there are other ways to load in the data, I will close the issue.
