### ISSUE TITLE
peak calling

### ISSUE THREAD

**Issue by kstriedinger** [timoast/signac#700]
Hi, I am following the vignette for calling peaks for scATAC, here is my script:

```r
DimPlot(husc500Ag)

peaks <- CallPeaks(
  object = husc500Ag,
  group.by="500_activated.id"
  macs2.path = "/Users/katharinestriedinger/opt/anaconda3/bin/MAC2"
)
```
error is showing in not recognizing the ID, although is the same verbatim ID for one of my samples. I installed the MACS2 package from pip succesfully. 
please help.

**Comment by timoast** [comment]
It looks like you're missing a comma between the `group.by` and `macs2.path` parameters
