### ISSUE TITLE
DNAStringSet as genome input for RunChromVAR and AddMotifs

### ISSUE THREAD

**Issue by rpolicastro** [timoast/signac#712]
Currently the documentation for `AddMotif` and `RunChromVAR` states that a `BSgenome` object is required for input to the `genome` argument. To avoid having to forge a `BSgenome` for new/custom assemblies or unsupported organisms, a `DNAStringSet` would be preferred as an alternative input. It appears that without modification to the code both `AddMotif` and `RunChromVAR` work with a `DNAStringSet` in a preliminary test run.

For `AddMotif` the internal call is to `motifmatchr::matchMotifs`. A `DNAStringSet` is a supported genome input according to their documentation.

For `RunChromVAR` although the `chromVAR` documentation only states that a `BSgenome` object  is used for input, their generic functions support `DNAStringSets`.

There also don't appear to be any input checks or BSgenome specific function calls in Signac that would throw an error in an initial perusal of the code.

Thanks!

**Comment by timoast** [comment]
You're right, the requirement for a BSgenome object in `Signac::RunChromVAR()` comes from what's stated in the documentation for `chromVAR::addGCBias()` but it seems like other inputs are supported (based on https://github.com/GreenleafLab/chromVAR/blob/master/R/utils.R#L320-L358). I'm happy to update the documentation to state that `DNAStringSet` and `FaFile` objects are also supported.

For `AddMotifs()` I will also update to match what's stated in `motifmatchr::matchMotifs()`

**Comment by timoast** [comment]
Updated on the develop branch
