### ISSUE TITLE
Error running signac with chicken genome

### ISSUE THREAD

**Issue by kgerner** [timoast/signac#713]
Hello,

I have been trying to run my dataset with the chicken genome but keep running into this error:

```r
> pbmc<-TSSEnrichment(pbmc)
Extracting TSS positions
Extracting fragments at TSSs
  |                                                  | 0 % ~calculating  Error in base::rowSums(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions
```

Is there any known solution to this?

This is how I am loading in the chicken genome:

```r
h <- AnnotationHub()
query(h, "EnsDb")
#list query for your favorite species
query(h, c("EnsDb", "GGallus"))
edb <- h[["AH83209"]]
setwd("~/Desktop/E13 Chicken Analysis") #should have .h5; .tsv.gz; .tsv.gz.tbi files from outs
counts<-Read10X_h5("./filtered_feature_bc_matrix.h5")
fragpath<-"./atac_fragments.tsv.gz"
annotation<-GetGRangesFromEnsDb(ensdb=edb)
seqlevelsStyle(annotation)<-"UCSC"
genome(annotation)<-"galGal6"
rm(edb)
rm(h)

pbmc<-CreateSeuratObject(counts = counts$`Gene Expression`, assay = "RNA")
pbmc[["ATAC"]]<-CreateChromatinAssay(counts = counts$Peaks, sep=c(":","-"),fragments = fragpath, annotation=annotation)
#7344 cells; 133737 features (32285 RNA plus 101452 ATAC)

DefaultAssay(pbmc)<-"RNA"
pbmc<-PercentageFeatureSet(pbmc, pattern = "^mt-", col.name = "percent.mt")
pbmc<-SCTransform(pbmc)
pbmc<-RunPCA(pbmc)

DefaultAssay(pbmc)<-"ATAC"
pbmc<-NucleosomeSignal(pbmc)
pbmc<-TSSEnrichment(pbmc)
```

Thank you for your time.

**Comment by timoast** [comment]
What is the output of `head(Fragments(pbmc)[[1]])`?

**Comment by kgerner** [comment]
> head(Fragments(pbmc)[[1]])
  chrom start end            barcode readCount
1    MT     5  24 AGCCGGTTCATGGTTA-1         3
2    MT     5  29 ATGTTCAAGGACCGCT-1         3
3    MT     5  34 GCAGGCTTCGCAACAT-1         6
4    MT     5  35 CATGCGCAGTTATCCT-1         4
5    MT     5  36 CGTTAGGTCATGAAGG-1         7
6    MT     5  36 TGAGGGCCACTTCATC-1         5

**Comment by timoast** [comment]
It looks like your data was mapped to a genome that was not UCSC-format, so you should not convert the gene annotations to UCSC format. The chromosome names in the genome and gene annotation need to match.

**Comment by kgerner** [comment]
Thank you for the help!~
