### ISSUE TITLE
Whether the addMotifs function accepts pwm matrix format

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#714]
I want to use human_pwms_v2 (https://github.com/GreenleafLab/chromVARmotifs) to do motif analysis. But it is a pwm format. I check the parameter of addMotifs function, it only have a pfm parameter.  What should I do if I want to use pwm matrix?

**Comment by timoast** [comment]
You can use a PFM as input to `AddMotifs()`, I have updated the documentation on the develop branch
