### ISSUE TITLE
integration of different datasets

### ISSUE THREAD

**Issue by hjack123** [timoast/signac#72]
Hi thanks for making the tool helpful. 
when integrating different datasets, is it true that it is taking intersecting peaks and generating, the intersected peak count matrix? would it be better to take the union peak sets instead? by taking the intersection, it is eliminate peaks that are unique to each datasets and would be key information? thanks.

**Comment by hjack123** [comment]
thanks very much for your reply. do u happen to have ideas about best way to make union peak sets?

**Comment by timoast** [comment]
See https://github.com/timoast/signac/issues/35#issuecomment-549389201

The [GenomicRanges](https://bioconductor.org/packages/release/bioc/html/GenomicRanges.html) package contains functions for dealing with sets of ranges
