### ISSUE TITLE
Issue while using Create fragment objects

### ISSUE THREAD

**Issue by SinghalDivya** [timoast/signac#730]
Hi, 
I am observing a weird error while creating a Seurat object using CreateFragmentObject function.  

p4_r <- read.table(
  file = "./peaks.bed",
  col.names = c("chr", "start", "end")
)

gr.p4_r <- makeGRangesFromDataFrame(p4_r)

md.p4_r <- read.table(
  file = "./final_singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.p4_r <- md.p4_r[md.p4_r$passed_filters > 500, ]

frags.p4_r <- CreateFragmentObject(
  path = "./fragments.tsv.gz",
  cells = rownames(md.p4_r)
)

##########
I obtain checking for 19569 cell barcodes
###############

but if i use same files and create seurat object using general scATAC pipeline:,

counts <- Read10X_h5(filename = "./filtered_peak_bc_matrix.h5")
metadata <- read.csv(
  file = "./final_singlecell.csv",
  header = TRUE,
  row.names = 1
)

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'hg38',
  fragments = './fragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)

pbmc <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks",
  meta.data = metadata
)

####################
I obtain checking for 3132 cell barcodes
#####################

, which is the correct number of barcodes. Did I miss any steps for merging the objects?

**Comment by timoast** [comment]
The `cells` parameter in `CreateFragmentObject()` tells the function which cells to check for. In the first case, you provide the rownames of the metadata table, which must be 19,569 cells (including some background empty droplets that would have very few fragments detected). In the second case, you are creating a Fragment object via the `CreateChromatinAssay()` and so the function performs pre-filtering of cells based on the supplied count matrix and the thresholds given (`min.features=200`). This would result in fewer cells being retained in the assay object.

**Comment by SinghalDivya** [comment]
please correct me if I am wrong, after running cellranger-atac, I obtain barcodes file, for me, those are the number of valid cells:
wc -l barcodes.tsv 
3132 barcodes.tsv

As per your suggestion, after running CreateFragmentObject(), I ran CreateChromatinAssay() with similar thresholds, I do obtain 4450 fewer cells as compared to 19569 cell barcodes, but I still get cells more than 3132 barcodes.

On the other hand, when I ran the same pipeline for my other samples, I obtain a similar number of cell barcodes as that of cellranger barcodes. 

what could be the reason behind it?
