### ISSUE TITLE
how to construct the peak to gene link in independent scRNA and scATAC sequencing results of a sample

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#741]
Nice tool! I found this LinkPeaks function appeared in this vignette (https://satijalab.org/signac/articles/pbmc_multiomic.html#linking-peaks-to-genes-1). In this vignette, one cell detects RNA and chromtin accesssibly simultaneous. But my data is the separate sequencing results of scRNA and scATAC for the same sample. I followed the vignette (https://satijalab.org/seurat/articles/atacseq_integration_vignette.html) and integrated these data. I got some co-accessibility links and want to construct the peak-to-gene linkage like in ArchR (https://www.archrproject.com/bookdown/peak2genelinkage-with-archr.html). But I don’t know how to achieve a similar purpose in signac.

**Comment by timoast** [comment]
The `LinkPeaks()` function requires two assays, one measuring peak accessibility and one measuring gene expression. If you have paired scATAC-seq and scRNA-seq data from the same sample (but not multiome data), you can estimate gene expression in the scATAC-seq dataset using data transfer methods that we developed in Seurat: https://satijalab.org/seurat/articles/atacseq_integration_vignette.html#co-embedding-scrna-seq-and-scatac-seq-datasets

This will allow you to transfer gene expression values to the scATAC-seq dataset (predict gene expression for each cell in the scATAC-seq dataset). You can then add those predicted gene expression values as a new assay and run the `LinkPeaks()` function. When interpreting the results, be aware that the expression values used in the correlation were not measured in the cell but were predicted based on patterns of chromatin accessibility.

**Comment by Dragonlongzhilin** [comment]
Thanks.
