### ISSUE TITLE
CoveragePlot showing not differential expression but FindMarker showing significantly differential expression

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#75]
Hi Tim,
     The peak coverage of my concern like , chr1:39042135-39042572, displayed  no differential peak using CoveragePlot function to plot,  where The  peak of mentioned above showed significantly differential expression when I token as differential expression analysis using  FindMarkers funciton in the light of your vignette.
     I wonder that why it  was just reversed bwteen the FindMarker showing differential peak result and  
CoveragePlot function picture showing not differential peak result.

**Comment by honghh2018** [comment]
@timoast the Coverage plot showing below, which indicated non-differential expression peak,
![image](https://user-images.githubusercontent.com/41668708/72676095-455fd500-3ac8-11ea-82bd-6decd70274cb.png)
However, the peak postion: chr15:36177554-36177921 are significantly differential expression on Fat versus Health sample generated FindMarker function.
 Your advice would be appreciated.
  Thanks.

**Comment by timoast** [comment]
Can you plot only the differentially accessible peak without the surrounding region and turn off the window smoothing and downsampling, eg: `region="chr15:36177554-36177921",  sep=c(":", "-"), window=1, downsample=1`

**Comment by timoast** [comment]
@honghh2018 any update on this?

**Comment by timoast** [comment]
Closing now as I haven't heard back

**Comment by honghh2018** [comment]
Hi @timoast , As result of chinese New Year, later for reply.
On this case,  the peak coverage that take CoveragePlot plotting showed no differential expression yet, but the peak  that above plot suggested significantly differential by using FindMarker function to test, when I follow your tip that add parameter,window=2, downsample=1,into CoveragePlot.
The detail showing below:
I have samples including treatment and control,health sample and fat sample, I want to determined What different peak occurred between fat and health.
 The FindMarker peak,chr13:55469377-55477892, indicated significantly differential showing below:
p_val   avg_logFC       pct.1   pct.2   p_val_adj
chr13:55469377-55477892 0       1.77182370736014        0.282   0.009   0
###However, this peak showing  no different for plotting it by taking CoveragePlot showing below:
![image](https://user-images.githubusercontent.com/41668708/73813598-6b50dd80-481b-11ea-8e1c-7a5e2f10bf8e.png)

**Comment by honghh2018** [comment]
Hi  @timoast , above parameter was wrong for my writing mistake. Above it should be as same 
 as you suggest me, window=1, downsample=1.
