### ISSUE TITLE
How should the gorilla data be annotated

### ISSUE THREAD

**Issue by bill0919** [timoast/signac#760]
As the title says, my data are from gorillas, and the pantro4 of UCSC was used for comparison. In signac, how should I comment annotate?

**Comment by bill0919** [comment]
Maybe I solved the problem by myself. I downloaded ''Pan_troglodytes.CHIMP2.1.4.90.gtf'' from Ensembl.

I then introduced it into R as  GRanges.

`library("rtracklayer")`
`annotations <- import('Pan_troglodytes.CHIMP2.1.4.90.gtf')`

And then move on to the next step sucessfully.

**Comment by timoast** [comment]
See the FAQ on Signac website: https://satijalab.org/signac/articles/faq.html#an-annotation-or-genome-sequence-for-my-organism-is-not-available-on-bioconductor-what-do-i-do-
