### ISSUE TITLE
no method for coercing this S4 class to a vector

### ISSUE THREAD

**Issue by hjack123** [timoast/signac#77]
#### My code
# peak-bc matrix
mex_dir_path <- "outs/filtered_peak_bc_matrix"
mtx_path <- paste(mex_dir_path, "matrix.mtx", sep = '/')
feature_path <- paste(mex_dir_path, "peaks.bed", sep = '/')
barcode_path <- paste(mex_dir_path, "barcodes.tsv", sep = '/')

features <- readr::read_tsv(feature_path, col_names = F) %>% tidyr::unite(feature)
barcodes <- readr::read_tsv(barcode_path, col_names = F) %>% tidyr::unite(barcode)

mtx <- Matrix::readMM(mtx_path) %>%
  magrittr::set_rownames(features$feature) %>%
  magrittr::set_colnames(barcodes$barcode)
colnames(mtx) <- gsub("^","2_",colnames(mtx))
##############
metadata <- read.csv(
  file = "outs/singlecell.csv",
  header = TRUE,
  row.names = 1
)
rownames(metadata)<- gsub("^","2_",rownames(metadata))
pbmc <- CreateSeuratObject(
  counts = mtx,
  assay = 'peaks',
  project = 'ATAC',
  min.cells = 1,
  meta.data = metadata
)
fragment.path <- '2.fragments.edit.tsv.gz'
pbmc <- SetFragments(
  object = pbmc,
  file = fragment.path
)
##### QC
pbmc <- NucleosomeSignal(object = pbmc)
pbmc$pct_reads_in_peaks <- pbmc$peak_region_fragments / pbmc$passed_filters * 100
pbmc$blacklist_ratio <- pbmc$blacklist_region_fragments / pbmc$peak_region_fragments

VlnPlot(
  object = pbmc,
  features = c('pct_reads_in_peaks', 'blacklist_ratio', 'nucleosome_signal', 'peak_region_fragments'),
  pt.size = 0.1,
  ncol = 4) + NoLegend()
pbmc$nucleosome_group <- ifelse(pbmc$nucleosome_signal > 10, 'NS > 10', 'NS < 10')
PeriodPlot(object = pbmc, group.by = 'nucleosome_group')
##### GRange object with TSS positions
# create granges object with TSS positions
gene.ranges <- genes(EnsDb.Hsapiens.v86)
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding', ]

tss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges),
  ranges = IRanges(start = start(gene.ranges), width = 2),
  strand = strand(gene.ranges)
)

seqlevelsStyle(tss.ranges) <- 'UCSC'
tss.ranges <- keepStandardChromosomes(tss.ranges, pruning.mode = 'coarse')

# to save time use the first 2000 TSSs
pbmc <- TSSEnrichment(object = pbmc, tss.positions = tss.ranges[1:2000])

##### Remove cells based on QC metrics
pbmc <- subset(pbmc, subset = peak_region_fragments > 1000 & peak_region_fragments < 20000 & pct_reads_in_peaks > 15 & blacklist_ratio < 0.05 & nucleosome_signal < 10 & TSS.enrichment > 2)
##### Normalization

pbmc <- RunTFIDF(pbmc)
pbmc <- FindTopFeatures(pbmc, min.cutoff = 'q0')
pbmc <- RunSVD(
  object = pbmc,
  assay = 'peaks',
  reduction.key = 'LSI_',
  reduction.name = 'lsi'
)

pbmc <- RunUMAP(object = pbmc, reduction = 'lsi', dims = 1:30)
pbmc <- FindNeighbors(object = pbmc, reduction = 'lsi', dims = 1:30)
pbmc <- FindClusters(object = pbmc, verbose = FALSE)
pbmc1=pbmc

### made the pbmc.2 same way
pbmc.1@meta.data$sample="1"
pbmc.2@meta.data$sample="2"
##### Integration 2 datasets
# find union peak set
peaks1=StringToGRanges(regions=rownames(pbmc.1))
peaks2=StringToGRanges(regions=rownames(pbmc.2))
all.peaks <- union(peaks1,peaks2)
newcounts1 <- FeatureMatrix(fragments = GetFragments(pbmc.1), features = all.peaks, cells = colnames(pbmc.1))
newcounts2 <- FeatureMatrix(fragments = GetFragments(pbmc.2), features = all.peaks, cells = colnames(pbmc.2))
pbmc.1[['peakunion']] = CreateAssayObject(counts=newcounts1)
pbmc.1 <- RunTFIDF(object=pbmc.1, assay='peakunion')
pbmc.2[['peakunion']] = CreateAssayObject(counts=newcounts2)
pbmc.2 <- RunTFIDF(object=pbmc.2, assay='peakunion')

peaks.use <- sample(all.peaks, size = 10000, replace = FALSE)

anchors <- FindIntegrationAnchors(
  object.list = list(pbmc.1, pbmc.2),
  anchor.features = peaks.use,
  assay = c('peakunion', 'peakunion'),
  k.filter = NA
)

#### Error
> anchors <- FindIntegrationAnchors(
+   object.list = list(pbmc.1, pbmc.2),
+   anchor.features = peaks.use,
+   assay = c('peakunion', 'peakunion'),
+   k.filter = NA
+ )
Scaling features for provided objects
  |                                                  | 0 % ~calculating  Error in as.vector(x) : no method for coercing this S4 class to a vector

**Comment by timoast** [comment]
I think the issue here is that `peaks.use` will be a set of GRanges, not the names of peaks in the objects.

Using `peaks.use <- sample(rownames(newcounts1), size = 10000, replace = FALSE)` for example should work

**Comment by hjack123** [comment]
Hi Tim. Thank you so much, yes it passed.
