### ISSUE TITLE
the order of step in signac

### ISSUE THREAD

**Issue by l-magnificence** [timoast/signac#777]
Hello,
Peak calling using MACS2  is an excellent upgrade to the default Peaks in siganc. But I am confused about the corret order to process the scATAC-seq.

My thoughts:
Firstly, using the CellRanger peak count matrix and fragment file as input to create a signac object followed by computing QC metrics, normalizatio, linear dimensional reduction and creating a gene activity matrix to label the cluster.
Secondly, using MACS2 to call peaks and add it to the original object.
Finally, using this new object to do other analysis such as findmarker, motif analysis and so on.

Is this correct steps to process scATAC-seq or what about your opinions?

**Comment by timoast** [comment]
Yes, that's a reasonable approach. You could also cluster cells using the MACS2 peak matrix, but in practice it may not make much difference. The main difference is in finding differentially accessible peaks.

If you wanted to use the MACS2 peaks only (no cellranger), you can call peaks directly from the fragment file (giving the path to the fragment file as input to `CallPeaks()`, and then quantify those peaks using `FeatureMatrix()`.
