### ISSUE TITLE
Issue plotting after LinkPeaks

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#787]
I am analysing data from Cellrnager ARC. I get everything set which works fine I then try:

```r
combined <- LinkPeaks(
  object = combined,
  peak.assay = "ATAC",
  expression.assay = "RNA",
  genes.use = c("Col1a1", "Thy1")
)

p1 <- CoveragePlot(
  object = combined,
  region = "Col1a1",
  features = "Col1a1",
  expression.assay = "RNA",
  extend.upstream = 15000,
  extend.downstream = 15000,
  links = T,
  )
```

But I get this message and no plot:

```
Error in unit(width, default.units) :
  'x' and 'units' must have length > 0
Calls: <Anonymous> ... simplify_gt.gtable -> simplify_free -> lapply -> FUN -> viewport -> unit
In addition: Warning message:
Removed 1 rows containing missing values (position_stack)

```
If you could offer some help i would really appreciate it. Thanks

**Comment by timoast** [comment]
Can you show the output of `sessionInfo()`? It looks like this could be related to an old patchwork issue: https://github.com/thomasp85/patchwork/issues/200

**Comment by chrismahony** [comment]
Here you go! Thanks
Chris

**Comment by chrismahony** [comment]
***@***.***

**Comment by chrismahony** [comment]
[New Microsoft PowerPoint Presentation (2).pdf](https://github.com/timoast/signac/files/7137002/New.Microsoft.PowerPoint.Presentation.2.pdf)
Sorry, finally attached now!

**Comment by timoast** [comment]
It looks like you have the old version of patchwork before this bug was fixed, updating patchwork should solve the issue: `install.packages("patchwork")`

**Comment by chrismahony** [comment]
It works now, thanks!
