### ISSUE TITLE
chromVAR motif activity fold change calculation

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#793]
The chrom var assay 'data' slot is the bias corrected z scores.  It appears that for the chromvar assay, signac is using the same mean.fxn that is used for the Seurat data slot, which uses the `expm1` function on the input data... the code below produces identical results to FindMarkers: 
```
motif.mtx <- atac[['chromvar']]@data
mean.cells1 <- log(rowMeans(expm1(motif.mtx[, cells.1])) + 1, base = 2)
mean.cells2 <- log(rowMeans(expm1(motif.mtx[, cells.2])) + 1, base = 2)
log2fc <- mean.cells1 - mean.cells2
```

Since the input data is bias corrected z scores, it seems there is no way to compute a raw fold change from those values. Negative values mess the calculation up... perhaps average difference would be best for this.  

I also propose an alternative method below.  For each motif i, sum the fragments at each peak k where motif i occurs.  Then, fold change can be calculated for each motif.  (!!!) I will mention however, that when I did this calculation all of my results were negative and very small, which doesn't feel right. 
```
motif.mtx <- t(atac[['peaks']]@motifs@data)
count.mtx <- atac[['peaks']]@counts
motif.counts <- motif.mtx %*% count.mtx
mean.cells1 <- log(rowMeans(motif.counts[, cells.1]), base = 2)
mean.cells2 <- log(rowMeans(motif.counts[, cells.2]), base = 2)
log2fc <- mean.cells1 - mean.cells2
```

**Comment by timoast** [comment]
Hi @danielcgingerich 

You're right, exponentiating the z-scores to compute a fold change makes no sense. In this case, the Seurat defaults are not appropriate. You can set `mean.fxn=rowMeans` to instead compute the mean difference between z-scores across groups (and you can set `fc.name="avg_diff"` to change the name of the column in the output dataframe).

I've added this to the motif vignette
