### ISSUE TITLE
Help with chromvar

### ISSUE THREAD

**Issue by smanne07** [timoast/signac#8]
Hi,
This is more of documentation request than issue.
I see that chromVar function is added in latest Signac release.

Can you please provide the workflow to run chromVar through Signac?

Best regards
Sasi

**Comment by timoast** [comment]
Hi Sasi, I am still working on methods for motif analysis and will provide a full vignette when it's finished, in the meantime here is a short example of how to run chromVAR using Signac:

```r
library(Signac)
library(JASPAR2018)
library(TFBSTools)
library(BSgenome.Hsapiens.UCSC.hg19)

# the object "pbmc" is just an example
# if you have a different species, change the genome used and motifs PWMs used accordingly
pbmc <- readRDS("pbmc.rds")

# get a list of motif position weight matrices from the JASPAR database
# taxonomy ID for human is 9606
PFMatrixList <- getMatrixSet(
  x = JASPAR2018,
  opts = list(species = 9606, all_versions = FALSE)
)

# create a peak x motif matrix, where each entry is 1 if the peak contains the motif, otherwise 0
motif.mat <- CreateMotifMatrix(
  features = StringToGRanges(rownames(pbmc)),
  pwm = PFMatrixList,
  genome = 'hg19'
)

# run chromvar
pbmc <- RunChromVAR(
  object = pbmc,
  genome = BSgenome.Hsapiens.UCSC.hg19,
  motif.matrix = motif.mat
)

# this will add a new assay to the pbmc object called "chromvar", containing the motif activity scores
```

Please make sure to update to 0.1.3 before running, as I just pushed some new updates to the chromVAR wrapper. Right now this is only on the develop branch, you can install using:

```r
devtools::install_github("timoast/signac", ref = "develop")
```

**Comment by smanne07** [comment]
Thank you Tim,this should be good for getting started with the motif analysis
