### ISSUE TITLE
Question about Integration between scRNA-seq and scATAC-seq cells

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#80]
Dear all,

I am asking about FindTransferAnchors function,

I read the paper and know how the anchor scoring and prediction scoring are done.

I still have some questions:

1- After anchoring, only 2100 anchors are retained. However, all cells in scATAC-seq data have prediction scores and more than 3000 of them have scores > 0.5. I think prediction score is done using the anchor weighting matrix which is calculated after retaining a subset of anchors (as far as I understand). So, how does all cells have prediction scores?

2- Another point that I need to ask about, I found one RNA-seq cell matching with several ATAC-seq cells, is that normal and expected?

Thanks

**Comment by timoast** [comment]
1. The prediction score is different to the anchor score. See the sections Anchor Scoring, Anchor Weighting, and Label Transfer under the Methods section in: https://doi.org/10.1016/j.cell.2019.05.031
2. Yes, that is expected

**Comment by ahmedabbas81** [comment]
1- So, is the weighting matrix for all set of anchors or for retained anchors only? This point is not clear to me.

2- After integrating gene expression matrix and gene activity matrix, and after getting cell prediction for scATAC-seq cells, should I use the new expression matrix y^ (that you say obtained by the function IntegrateData) for downstream analysis to be consistent with the scores predicted for cells? Or I use the original Y matrix? And which function returns to me the matrix y^?

3- And suppose I need the Y matrix with only the genes used for integration, which function returns this to me?

4- And is the function SelectIntegrationFeatures() called internally when called FindTransferAnchors()?

Thanks

**Comment by timoast** [comment]
> So, is the weighting matrix for all set of anchors or for retained anchors only? This point is not clear to me.

Only retained anchors.

> should I use the new expression matrix y^ (that you say obtained by the function IntegrateData) for downstream analysis to be consistent with the scores predicted for cells? Or I use the original Y matrix?

For transferring gene expression data I recommend this workflow: https://satijalab.org/signac/articles/pbmc_vignette.html#integrating-with-scrna-seq-data

> And suppose I need the Y matrix with only the genes used for integration, which function returns this to me?

The genes used for integration are those specified with the `anchor.features` argument in `FindIntegrationAnchors`. The list of features is also stored in the anchor object, you can access it using `anchor_object@anchor.features`

> And is the function SelectIntegrationFeatures() called internally when called FindTransferAnchors()?

No, it is used in `FindIntegrationAnchors`: https://github.com/satijalab/seurat/blob/master/R/integration.R#L158

`FindTransferFeatures` will use the variable features in the reference object by default.

**Comment by ahmedabbas81** [comment]
Dear Tim,

1- Suppose that the number of retained anchors is 2000. And suppose we have 5000 scATAC-seq cells. And as you said, weighting is only for retained anchors. And prediction score depends on weighting matrix. So, how can we have a prediction score for each of the 5000 cells?

2- I use the workflow you mentioned. I know it from Seurat tutorials. However, suppose I need to use the gene activity matrix for other purposes after integration. Which matrix should I use, Y or Y^? And which function returns Y^ to me?

Thanks

**Comment by timoast** [comment]
> 1- Suppose that the number of retained anchors is 2000. And suppose we have 5000 scATAC-seq cells. And as you said, weighting is only for retained anchors. And prediction score depends on weighting matrix. So, how can we have a prediction score for each of the 5000 cells?

For each **cell**, we calculate a weight for the cell's _k_ nearest **anchors**. These anchor weights will determine the prediction score for the cell. This is described in detail in the paper that I linked to previously.

> 2- I use the workflow you mentioned. I know it from Seurat tutorials. However, suppose I need to use the gene activity matrix for other purposes after integration. Which matrix should I use, Y or Y^? And which function returns Y^ to me?

This depends what the "other purposes" are. If you want to visualized the predicted expression of marker genes use the imputed gene expression matrix. This matrix is returned by `TransferData` (for imputation) or `IntegrateData` (for integration)

**Comment by ahmedabbas81** [comment]
Thank you for your answer

1- So, it is not strange to have only 2000 retained anchors and have prediction scores for all the 5000 scATAC-seq cells, right? I am sorry. This part is not very clear to me in the paper. 

2- Thank you, I will try your suggestion

Thanks

**Comment by timoast** [comment]
> 1- So, it is not strange to have only 2000 retained anchors and have prediction scores for all the 5000 scATAC-seq cells, right? I am sorry. This part is not very clear to me in the paper.

I answered this above: For each cell, we calculate a weight for the cell's k nearest anchors. These anchor weights will determine the prediction score for the cell. Therefore, we have a prediction score for each cell regardless of the number of anchors, as we look at the k nearest anchors for each cell.
