### ISSUE TITLE
Another question about data integration

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#81]
Hello,

After integrating gene expression matrix and gene activity matrix, and after getting cell prediction for scATAC-seq cells,

should I use the new expression matrix y^ (that you say obtained by the function IntegrateData) for downstream analysis to be consistent with the scores predicted for cells? Or I use the original Y matrix?

And suppose I need the Y matrix with only the genes used for integration, which function returns this to me?

And is the function SelectIntegrationFeatures() called internally when called FindTransferAnchors()?

Thanks

**Comment by timoast** [comment]
Answered in https://github.com/timoast/signac/issues/80#issuecomment-579372037
