### ISSUE TITLE
CoveragePlot for hg38

### ISSUE THREAD

**Issue by Brawni** [timoast/signac#82]
Hi Tim,

I have been using signac for analysis of multiple scATAC-seq and found it great! One thing though is that I would like to have genome annotation underneath the coverage plots using the hg38 annotation, which as far as i understood is not supported for now. Are you going to implement this in the near future? 

Thank you

**Comment by timoast** [comment]
Any set of annotations is supported. You can use the [EnsDb.Hsapiens.v86](https://www.bioconductor.org/packages/release/data/annotation/html/EnsDb.Hsapiens.v86.html) package for a set of annotations for hg38. Alternatively, you can provide any set of genomic ranges containing the appropriate columns (seqnames, start, end, strand, gene_name).
