### ISSUE TITLE
Import of SHARE-seq pipeline results

### ISSUE THREAD

**Issue by jwtobias** [timoast/signac#820]
I could use some advice (code snippets) for how best to import the results of the SHARE-seq pipeline:

https://github.com/masai1116/SHARE-seq-alignment/

I would like to use these results to construct a multiomic Seurat object for joint analysis of expression and ATAC chromatin assays.

The SHARE-seq platform is specifically mentioned on the Seurat homepage, but I can't find any documentation.

**Comment by timoast** [comment]
Analysis of RNA + ATAC  coassay single-cell datasets requires a gene count matrix and a fragment file as input. We have two vignettes on the Signac website demonstrating how to run such an analysis: https://satijalab.org/signac/articles/pbmc_multiomic.html https://satijalab.org/signac/articles/snareseq.html
