### ISSUE TITLE
Creating fragment file path from sciATAC-seq 

### ISSUE THREAD

**Issue by raphaela2018** [timoast/signac#83]
Hi Tim, 

After clustering using bins, I called peaks from each cluster using MACS2 and merged peaks. I added a peak matrix to my Seurat object and try to add a gene activity matrix. 
But I am using sciATACseq dataset. So I don't have a .tsv.gz file that Signac requires to run FeatureMatrix. Would you let me know how I can generate such file using sciATACseq data so that I can run FeatureMatrix? 

Thanks a lot!

**Comment by timoast** [comment]
Hi, we don't provide functions to generate the fragment file. You can find a description of the fragment file here: https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments

If you have a BAM file with your mapped reads you will be able to create a fragment file by computing the fragment interval (adjusting for the Tn5 integration offset), and creating a position-sorted BED file containing the fragment positions and cell barcodes, compressing the file with bgzip and indexing the file with [tabix](https://www.htslib.org/doc/tabix.html). Unfortunately we can't provide specific instructions as these will vary depending on your upstream data processing.

**Comment by timoast** [comment]
@raphaela2018 I have another package ([Sinto](https://github.com/timoast/sinto)) that now provides a function to create a fragments file from a BAM file that you can use for sci-ATAC-seq data

**Comment by raphaela2018** [comment]
Thanks!
