### ISSUE TITLE
Option to define column from genome annotation used in GeneActivity as gene name

### ISSUE THREAD

**Issue by skilpinen** [timoast/signac#837]
Currently, if I am not mistaken, GeneActivity() uses as forced default gene_name column from the genome annotation of chromatin assay as basis for gene nomenclature. This then causes problems with label transfer from scRNA if scRNA has been processed with Ensembl ids. Could there be option in in GeneActivity which specifies the column used as gene identification. Like in this case:
GRanges object with 1763965 ranges and 5 metadata columns:
                     seqnames          ranges strand |              tx_id   gene_name            gene_id   gene_biotype     type
                        <Rle>       <IRanges>  <Rle> |        <character> <character>        <character>    <character> <factor>
  ENSMUSE00001236884     chr3 3508030-3508332      + | ENSMUST00000108393       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00000676606     chr3 3634150-3634347      + | ENSMUST00000108394       Hnf4g ENSMUSG00000017688 protein_coding     exon
  ENSMUSE00001345708     chr3 3638059-3638230      + | ENSMUST00000108393       Hnf4g ENSMUSG00000017688 protein_coding     exon

There is ENSMUSG id available in the same annotation data.

**Comment by timoast** [comment]
I've now added a `gene.id` parameter to `GeneActivity()` to enable naming the genes using gene IDs rather than gene names

**Comment by skilpinen** [comment]
Thanks, I should have asked for PR and do that as well, but just too many open things at the moment. Anyway, thanks a lot, this is really phenomenal library.
