### ISSUE TITLE
nucleosome signal

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#84]
What is the meaning of Nucleosome signal < 10? Does it mean ratio of fragments with length between 147 - 294 bp to fragments < 147 bp less than 10?

And what is the meaning of nuclesome figures in this link https://satijalab.org/signac/articles/mouse_brain_vignette.html ? Is the x-axis mean the fragment length? And how does the figure relate to NS < 10 or NS>10

Thanks

**Comment by timoast** [comment]
As per the [docs](https://satijalab.org/signac/reference/NucleosomeSignal.html) for NucleosomeSignal: 

> Computes the ratio of fragments between 147 bp and 294 bp (mononucleosome) to fragments < 147 bp (nucleosome-free)

The figure shows fragment length on the x-axis and fragment count on the y-axis, separated by whether the nucleosome signal (defined above) was less than 10
