### ISSUE TITLE
Error with IntegrateEmbeddings -- Part 2 -_-

### ISSUE THREAD

**Issue by jogiles** [timoast/signac#846]
I couldn't re-open the previous issue (#619).

Hi @timoast ! 
I did as suggested and modified the reference and query objects so there are no overlapping cells, but I'm still getting the same error.

Any help would be greatly appreciated!!!!

```r
aPDL1 <- TransferData(
  anchorset = transfer.anchors, 
  reference = noRx,
  weight.reduction = "lsiproject",
  query = aPDL1,
  refdata = noRx$clustersA )

aPDL1 <- IntegrateEmbeddings(
  anchorset = transfer.anchors,
  reference = noRx,
  query = aPDL1, 
  reductions = "lsiproject",
  new.reduction.name = "ref.lsi" )

Error in ValidateParams_IntegrateEmbeddings_TransferAnchors(anchorset = anchorset,  : 
  The set of cells used as a reference in the AnchorSet does not match the set of cells provided in the reference object.

> table(colnames(noRx) %in% colnames(aPDL1) )

FALSE 
42735 
> table( colnames(aPDL1) %in% colnames(noRx))

FALSE 
 8497 
 
> table(transfer.anchors@reference.cells == paste0(colnames(noRx), "_reference"))

 TRUE 
42735 
> table(transfer.anchors@query.cells %in% paste0(colnames(aPDL1), "_query"))

TRUE 
8497
```
_Originally posted by @jogiles in https://github.com/timoast/signac/issues/619#issuecomment-950189223_

**Comment by jogiles** [comment]
Hi @timoast ,

Congrats on the paper!!!!

Here is the code to generate the transfer anchors:transfer.anchors <- FindTransferAnchors(
  reference = noRx,
  query = aPDL1,
  reference.reduction = "lsi",
  reduction = "lsiproject",
  dims = 2:30 )

Update: I did eventually get it to work by creating a new reference object with renamed cells.:

noRx_rename <- noRx
noRx_rename <- RenameCells(noRx_rename, new.names = paste0("noRx_", colnames(noRx)))

transfer.anchors <- FindTransferAnchors(
  reference = noRx_rename,
  query = aPDL1,
  reference.reduction = "lsi",
  reduction = "lsiproject",
  dims = 2:30 )

aPDL1 <- MapQuery(
  anchorset = transfer.anchors,
  reference = noRx_rename,
  query = aPDL1,
  refdata = noRx$clustersA,
  reference.reduction = "lsi",
  new.reduction.name = "ref.lsi",
  reduction.model = 'umap' )

I don't understand why this worked. But, the aPDL1 object and noRx object were created by subsetting a master object with both sets of cells. Is that information -- those removed barcodes -- retained somewhere?

Thanks for all your help!

**Comment by timoast** [comment]
Thanks @jogiles !

I think the issue here is that when you make the combined LSI, some cells are automatically renamed in the merged objects since they match cells in the reference object. When you find anchors, the cells in the anchor object are not being renamed, and so some of them don't match cells in the combined LSI object.

This is a problem that will need to be fixed in Seurat. For now, renaming the cells in one of the objects is a good workaround.
