### ISSUE TITLE
Error in FindMotifs

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#849]
I am running the follwing:

```r
Idents(object = fibroblasts_all) <- "new_clusters2"
open.peaks <- AccessiblePeaks(fibroblasts_all, assay='ATAC')

meta.feature <- GetAssayData(fibro_all, assay = "ATAC", slot = "meta.features")
peaks.matched_0 <- MatchRegionStats(
  meta.feature = meta.feature[open.peaks, ],
  query.feature = meta.feature[markerpeaks_0_top, ],
  n = 50000
)

enriched.motifs_0 <- FindMotifs(
  object = fibroblasts_all,
  features = markerpeaks_0_top,
background=peaks.matched_0 
)
```
But when I try to run FindMotifs motifs, I get:

```r
Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  : 
  'x' contains missing values
Calls: MatchRegionStats -> density -> density.default
Execution halted
```
If you could help, I would really appreciate it, thanks.
Chris

**Comment by chrismahony** [comment]
> head(open.peaks)
[1] "chr1-3414101-3414398" "chr1-3514712-3515217" "chr1-3611248-3611518"
[4] "chr1-3670623-3672600" "chr1-3900358-3900744" "chr1-3903424-3903732"
> head(peaks.matched_0)
[1] "chr7-142967171-142967870"  "chr13-108214024-108215433"
[3] "chr7-36075896-36076297"    "chr14-56319352-56319503"
[5] "chr3-152346123-152347188"  "chr4-155853046-155853195"
> length(peaks.matched_0)
[1] 50000
> length(open.peaks)
[1] 151756
> head(meta.feature)
                     count percentile AA AC AG AT CA CC CG CT GA GC GG GT TA TC
chr1-3119915-3120234    13  0.3012142 39 12 30 24 20 13  2 16 26 16 18 16 20 10
chr1-3297558-3297757     8  0.1938008 15 12 10 19 10  8  2 18 16  4 11  8 15 14
chr1-3414101-3414398    16  0.3531205 23 11 24 20 20 11  2 24 17 14 24 18 18 21
chr1-3414658-3414916     7  0.1690494 18 19 21 19 24 10  0 20 18 12 10 15 17 13
chr1-3514712-3515217    50  0.6328414 38 32 38 29 43 30  4 38 39 27 43 26 17 26
chr1-3611248-3611518    29  0.5038367 19 10 21 19 14  7  3 24 19 10 15 22 17 21
                     TG TT GC.percent sequence.length AA AC AG AT CA CC CG CT
chr1-3119915-3120234 26 31   40.00000             320 39 12 30 24 20 13  2 16
chr1-3297558-3297757 16 21   39.00000             200 15 12 10 19 10  8  2 18
chr1-3414101-3414398 23 27   43.62416             298 23 11 24 20 20 11  2 24
chr1-3414658-3414916 24 18   42.08494             259 18 19 21 19 24 10  0 20
chr1-3514712-3515217 50 25   49.60474             506 38 32 38 29 43 30  4 38
chr1-3611248-3611518 27 22   42.06642             271 19 10 21 19 14  7  3 24
                     GA GC GG GT TA TC TG TT GC.percent sequence.length
chr1-3119915-3120234 26 16 18 16 20 10 26 31   40.00000             320
chr1-3297558-3297757 16  4 11  8 15 14 16 21   39.00000             200
chr1-3414101-3414398 17 14 24 18 18 21 23 27   43.62416             298
chr1-3414658-3414916 18 12 10 15 17 13 24 18   42.08494             259
chr1-3514712-3515217 39 27 43 26 17 26 50 25   49.60474             506
chr1-3611248-3611518 19 10 15 22 17 21 27 22   42.06642             271
> dim(meta.feature)
[1] 224674     38
> length(markerpeaks_0_top)
[1] 5
> head(markerpeaks_0_top)
[1] "chr17-56461757-56463129" "chr14-34310159-34311641"
[3] "chr12-75668868-75670299" "chr8-84065787-84067507"
[5] "chr14-61555913-61557633"

**Comment by timoast** [comment]
I'm a bit confused by this...are you sure that you get this error when running `FindMotifs()` and not `MatchRegionStats()`? Can you double check that you see this error if you re-run the code in a fresh R session?

**Comment by timoast** [comment]
@chrismahony any update on this?

**Comment by timoast** [comment]
Closing this since I haven't heard back, please reopen if you're still having issues

**Comment by chrismahony** [comment]
Hi

Sorry for the delay.

I am just revisiting this now. I have restared my R session. Yes this is a problem with MatchRegionStats().

Any ideas?

Thanks
Chris

**Comment by annamarie67** [comment]
Following, same issues However, I cannot run MatchRegionStats() or FindMotifs() without getting:

Error in density.default(x = query.feature[[featmatch]], kernel = "gaussian",  :
  'x' contains missing values
