### ISSUE TITLE
Visualize marker genes with scATAC-seq data

### ISSUE THREAD

**Issue by ahmedabbas81** [timoast/signac#85]
If I want to visualize marker genes, 

should I use the gene activity matrix as in https://satijalab.org/signac/articles/mouse_brain_vignette.html

Or use the imputed gene expression matrix returned by TransferData as you told me before?

By the way, figures in both cases are totally different. Figures using the imputed matrix make much sense. I need to know the correct way.

Thanks

**Comment by timoast** [comment]
Hi, you can visualize either. Understand that the imputed expression is a prediction, whereas the "gene activity" (accessibility in the gene body and promoter) was actually measured in the experiment. It is expected that these can show quite different patterns, as the gene activity data will be much more sparse.

The imputation is based on an assumption that the gene expression is correlated with the accessibility at the gene body and promoter. This is likely the case in mature cell types but may not hold true in developing systems, for example. Therefore the "correct" way will depend on your goals and your data.

If you're visualizing these markers for the purpose of annotating cell types, you could also annotate cell types in the RNA data and transfer cell type labels to the ATAC-seq dataset, as shown in the vignettes.
