### ISSUE TITLE
Which reduction is suitable for scRNA and scATAC integration

### ISSUE THREAD

**Issue by Dragonlongzhilin** [timoast/signac#859]
In the vignette (https://satijalab.org/signac/articles/integrate_atac.html), the 'lsi' reduction is replaced by 'integrated_lsi'. 
When I used the Harmony method to integrate several scATAC object, a new ‘harmony’ reduction will be generated.
I read the vignette of'Integrating scRNA-seq and scATAC-seq data' (https://satijalab.org/seurat/articles/atacseq_integration_vignette.html), which only involves the integration of a single scRNA and scATAC object.
When integrating multiple scRNA and scATAC objects, which reduction is suitable for TransferData?

**Comment by timoast** [comment]
For integration of scRNA-seq and scATAC-seq, you need to use the CCA reduction and use ATAC gene activities
