### ISSUE TITLE
CoveragePlot() Error: Aesthetics must be either length 1 or the same as the data (546): label

### ISSUE THREAD

**Issue by zrcjessica** [timoast/signac#861]
Hello,

I am trying to visualize a connection between two regions of interest using the `CoveragePlot()` function:

| Peak1                	| Peak2                	| coaccess   	|
|----------------------	|----------------------	|------------	|
| 10-65585753-65586815 	| 10-65280956-65282262 	| 0.05797204 	|

I know that the region in Peak1 overlaps the TSS of the gene Aldoc. 

I have no problem running the following `CoveragePlot()` commands:
```r
# just for Peak1
CoveragePlot(atac, region = "10-65585753-65586815")
```

```r
# just for Peak2
CoveragePlot(atac, region = "10-65280956-65282262")
```

```r
# just for Aldoc
CoveragePlot(atac, region = "Aldoc")
```

However, when I try to specify a region that includes both Peak1 and Peak2, I get the following error:

```
Error: Aesthetics must be either length 1 or the same as the data (546): label
Traceback:

1. CoveragePlot(atac, region = "10-65280956-65590126")
2. SingleCoveragePlot(object = object, region = region, annotation = annotation, 
 .     features = features, expression.assay = expression.assay, 
 .     expression.slot = expression.slot, show.bulk = show.bulk, 
 .     peaks = peaks, peaks.group.by = peaks.group.by, ranges = ranges, 
 .     ranges.group.by = ranges.group.by, ranges.title = ranges.title, 
 .     assay = assay, links = links, tile = tile, tile.size = tile.size, 
 .     tile.cells = tile.cells, group.by = group.by, window = window, 
 .     extend.upstream = extend.upstream, extend.downstream = extend.downstream, 
 .     ymax = ymax, scale.factor = scale.factor, cells = cells, 
 .     idents = idents, sep = sep, heights = heights, max.downsample = max.downsample, 
 .     downsample.rate = downsample.rate)
3. AnnotationPlot(object = object[[assay]], region = region)
4. ggplot_build(plot = p)
5. ggplot_build.ggplot(plot = p)
6. by_layer(function(l, d) l$compute_aesthetics(d, plot))
7. f(l = layers[[i]], d = data[[i]])
8. l$compute_aesthetics(d, plot)
9. f(..., self = self)
10. check_aesthetics(evaled, n)
11. abort(glue("Aesthetics must be either length 1 or the same as the data ({n}): ", 
  .     glue_collapse(names(which(!good)), ", ", last = " and ")))
12. signal_abort(cnd)
```

The Annotation for my Signac object is the annotation for Rattus norvegicus from Ensembl. I have checked that the range I'm specifying does not extend past the bounds of the chromosome. Also, interestingly the problem seems to go away if I set `annotation = FALSE` in the `CoveragePlot()` function; however, I do need the visualize the gene. Do you have any thoughts for why this might be happening? 

Thank you,
Jessica

**Comment by timoast** [comment]
Could you share the annotation object you're using, or the code to make it?

**Comment by zrcjessica** [comment]
'''R
# Load Ensembl GTF

ens.gtf <- import("Rattus_norvegicus.Rnor_6.0.101.gtf")
genome(ens.gtf) <- "Rnor_6.0"

Annotation(atac) <- ens.gtf
'''

**Comment by timoast** [comment]
I tried running `AnnotationPlot()` for that region using the Rattus_norvegicus.Rnor_6.0.101.gtf annotation file and it worked fine. Can you try updating Signac and see if you still have this issue?

**Comment by zrcjessica** [comment]
What is the best way to update the package?

**Comment by timoast** [comment]
`devtools::install_github("timoast/signac", ref = "develop")`

**Comment by timoast** [comment]
@zrcjessica did updating solve the issue?

**Comment by timoast** [comment]
Closing this since I couldn't reproduce the issue and haven't heard back. Please reopen if you're still having issues

**Comment by zrcjessica** [comment]
Sorry I didn't respond to this earlier, missed your reply! Yes, I do believe it solved the issue. Thanks!
