### ISSUE TITLE
Signac equivalent in Python

### ISSUE THREAD

**Issue by Mayank0512** [timoast/signac#879]
I am trying to find the equivalent package of Signac in Python. Can anyone please help me out here ? 
I found that bio-conductor uses rpy2 to bridge the gap between Python and R .Is something similar possible with Signac too?
Thank you for your help and time
Regards,
Mayank Ghogale

**Comment by timoast** [comment]
There's no equivalent of Signac in Python, but the episcanpy package provides some of the same functionality: https://episcanpy.readthedocs.io/en/latest/index.html

rpy2 allows you to run R code from Python: https://rpy2.github.io/

**Comment by Mayank0512** [comment]
Thank you for the help sir
