### ISSUE TITLE
Can Signac calculate gene activity matrix only with peak counts matrix?

### ISSUE THREAD

**Issue by Telogen** [timoast/signac#885]
Hi, I 'm trying to calculate gene activity matrix using Signac, but I do not have neither fragment file nor BAM file. I only have the peak counts matrix, and this matrix has already pass the quality control and peak calling. Can I calculate gene activity matrix only with this peak counts matrix using Signac? Thanks for your help!

**Comment by timoast** [comment]
We don't currently support this. We could add it in the future but this is not a high priority, I'd recommend trying to get a fragment file for your dataset.

**Comment by Telogen** [comment]
Thanks for your answering! I also wander why Signac must use fragment file to calculate gene activity, in my point of view, the peak file contains all the information to calculate gene activity, is fragment file more accurate or some other reasons?

**Comment by timoast** [comment]
The fragment file contains information for the whole genome, whereas the peak matrix only has information for regions that were identified as peaks. There are a lot of fragments that fall outside of peaks, and so using the fragment file to calculate gene activities is more accurate and less dependent on peak calling.

**Comment by Telogen** [comment]
Got it. Thanks for your answering!
