### ISSUE TITLE
percent.mt in multiomics?

### ISSUE THREAD

**Issue by laurabchopp** [timoast/signac#895]
Hi Tim,

I'm using Signac to do 10x multimodal analysis. I noticed that the tutorial for 10x multimodal doesn't have anything about removing cells with a high fraction of mitochondrial genes (which I used for scRNAseq filtering in the past). Initially I thought it wouldn't matter, as the mitochondria are removed during nuclear prep prior to capture. 

Unexpectedly, when exploring my data I found my cells had a higher percentage of mitochondrial genes than I normally see (around 10%). Digging into the literature, I found it's possible for mitochondrial genes to actually enrich in the nucleus (likely transported). 

My question is, was the mitochondrial filtering step removed intentionally or inadvertently from the tutorial? Is it reasonable for me to skip this filtering step, since it may not actually be a metric of dying cells in this context?

Thanks,
Laura

**Comment by timoast** [comment]
Some scATAC or multiome experiments may have higher percentages of mitochondrial reads, but I think this is more related to how the sample was prepared than the quality of individual cells. For example, [this paper](https://doi.org/10.1038/s41587-020-0645-6) shows how the fraction of mitochondrial reads recovered can be modulated by changing the cell fixation conditions. I wouldn't recommend routinely using mitochondrial percentage as a QC filtering metric for scATAC experiments. In some datasets it may be informative, but I'd always look at this in combination with other things like TSS enrichment score.

**Comment by YichaoOU** [comment]
Hi, 

How can we get percent.mt for scATAC data using signac? 

Thanks,
Yichao
