### ISSUE TITLE
spliting an "aggr" object accoding to its orignal idents

### ISSUE THREAD

**Issue by Leonrunning** [timoast/signac#897]
Dear Signac team,

I have a similar issue as reported in the page of "Seurat": https://github.com/satijalab/seurat/issues/5188. My data is prepared from a cellranger-arc aggr pipeline and those cell barcodes all have suffix like "-1", "-2" and "-3". The parameter of "names.delim" in the "CreateSeuratObject" works perfectly for the GEX part, however, it seems like there is no this function in "CreateChromatinAssay". Would you please let me know what scripts can be used to demultiplex those samples from a cellranger-arc aggr output?

thanks 
Leon

**Comment by timoast** [comment]
There's no cell metadata present in the chromatin assay, this is stored at the Seurat object level. Using the `names.delimiter` parameter in `CreateSeuratObject()` will achieve what you want. Example:

```r
library(Seurat)
library(Signac)

counts <- GetAssayData(atac_small[['peaks']], slot = "counts")
head(colnames(counts))
```

```
[1] "AAACGAAAGAGCGAAA-1" "AAACGAAAGAGTTTGA-1" "AAACGAAAGCGAGCTA-1" "AAACGAAAGGCTTCGC-1"
[5] "AAACGAAAGTGCTGAG-1" "AAACGAACAAGGGTAC-1"
```

```r
assay <- CreateChromatinAssay(counts)
obj <- CreateSeuratObject(assay, names.field = 2, names.delim = "-")
head(Idents(obj))
```

```
AAACGAAAGAGCGAAA-1 AAACGAAAGAGTTTGA-1 AAACGAAAGCGAGCTA-1 AAACGAAAGGCTTCGC-1 AAACGAAAGTGCTGAG-1 
                 1                  1                  1                  1                  1 
AAACGAACAAGGGTAC-1 
                 1 
Levels: 1
```

**Comment by Leonrunning** [comment]
> There's no cell metadata present in the chromatin assay, this is stored at the Seurat object level. Using the `names.delimiter` parameter in `CreateSeuratObject()` will achieve what you want. Example:
> 
> ```r
> library(Seurat)
> library(Signac)
> 
> counts <- GetAssayData(atac_small[['peaks']], slot = "counts")
> head(colnames(counts))
> ```
> 
> ```
> [1] "AAACGAAAGAGCGAAA-1" "AAACGAAAGAGTTTGA-1" "AAACGAAAGCGAGCTA-1" "AAACGAAAGGCTTCGC-1"
> [5] "AAACGAAAGTGCTGAG-1" "AAACGAACAAGGGTAC-1"
> ```
> 
> ```r
> assay <- CreateChromatinAssay(counts)
> obj <- CreateSeuratObject(assay, names.field = 2, names.delim = "-")
> head(Idents(obj))
> ```
> 
> ```
> AAACGAAAGAGCGAAA-1 AAACGAAAGAGTTTGA-1 AAACGAAAGCGAGCTA-1 AAACGAAAGGCTTCGC-1 AAACGAAAGTGCTGAG-1 
>                  1                  1                  1                  1                  1 
> AAACGAACAAGGGTAC-1 
>                  1 
> Levels: 1
> ```

Works great! Thanks!
