### ISSUE TITLE
FindMarkers() function ident.1 and ident.2 confusion

### ISSUE THREAD

**Issue by l-cli** [timoast/signac#900]
Hi! I'm going over the "Analyzing PBMC scATAC-seq" vignette on Signac's website, and in the section named "Find differentially accessible peaks between clusters" I saw that in the following codes:

```
# change back to working with peaks instead of gene activities
DefaultAssay(pbmc) <- 'peaks'

da_peaks <- FindMarkers(
  object = pbmc,
  ident.1 = "CD4 Naive",
  ident.2 = "CD14 Mono",
  min.pct = 0.05,
  test.use = 'LR',
  latent.vars = 'peak_region_fragments'
)

head(da_peaks)

plot1 <- VlnPlot(
  object = pbmc,
  features = rownames(da_peaks)[1],
  pt.size = 0.1,
  idents = c("CD4 Memory","CD14 Mono")

```

FindMarkers() was called with ident.1 = "CD4 Naive" and ident.2 = "CD14 Mono", but later plot1 was generated using idents = c("CD4 Memory", "CD14 Mono"), and hence I cannot be sure if the output of `head(da_peaks)` is consistent with the violin plot (plot1) or not. In our own analyses we wanted to make sure we are interpreting the results from FindMarkers() correctly in terms of whether ident.1 is the baseline or ident.2 is the baseline, but we couldn't tell from the information from the vignette or from how the function was written. We would very much appreciate some clarifications on this, thank you!

**Comment by timoast** [comment]
This is an error in the vignette, I have changed the violin plot to now show CD4 Naive cells

For information on the `FindMarkers()` function see the Seurat documentation
