### ISSUE TITLE
Variable peak in data not present in gene activity matrix

### ISSUE THREAD

**Issue by GBeattie** [timoast/signac#91]
Hey,

I have a gene of interest which has a prominent and variable peak close to it's TSS (looking at the coverage plot). However the gene does not appear in the gene activity matrix, and so I can't plot it on a UMAP. The normalised accessibility of the gene (as viewed in the coverage plot) is comparable or higher than other genes which are found in the activity matrix, so I don't think it's been filtered due to low peak height. Any thoughts as to why this could be would be appreciated! 

Coverage plot of the gene:
![image](https://user-images.githubusercontent.com/11555832/74424330-a40b3b00-4e49-11ea-94dc-0fa2dfd19874.png)

The coverage plot was generated with:
```
CoveragePlot(
  object = Tcell_pre.atac,
  region = c(GZMB.co),
  sep = c(":", "-"),
  peaks = StringToGRanges(rownames(Tcell_pre.atac), sep = c(":", "-")),
  annotation = EnsDb.Hsapiens.v75,
  extend.upstream = 2000,
  extend.downstream = 2000,
  ncol = 2
)
```

My activity matrix was created with:

```
activity.matrix <- CreateGeneActivityMatrix(peak.matrix = mtx[, grepl("Tcell_Pre", barcodes$Group)], annotation.file = "./Homo_sapiens.GRCh37.82.gtf", 
                                            seq.levels = c(1:22, "X", "Y"), upstream = 2000, downstream = 2000, verbose = TRUE)
```

And the FeaturePlot:
```
DefaultAssay(Tcell_pre.atac) <- 'RNA'
FeaturePlot(
  object = Tcell_pre.atac,
  features = c('PRDM1', 'GZMB', 'TBX21', 'CTLA4', 'MAF', 'TCF7', 'CD4', 'CD8A'),
  pt.size = 0.1,
  max.cutoff = 'q95'
)
Warning message:
In FetchData(object = object, vars = c(dims, "ident", features),  :
  The following requested variables were not found: GZMB
```

**Comment by timoast** [comment]
`CreateGeneActivityMatrix` is not part of Signac, it's part of [Seurat](https://github.com/satijalab/seurat/blob/master/R/preprocessing.R#L173). I recommend that you use the `FeatureMatrix` function instead, as shown in the Signac [vignettes](https://satijalab.org/signac/articles/pbmc_vignette.html#create-a-gene-activity-matrix).

**Comment by GBeattie** [comment]
Thanks, I'll take a look and close this issue in that case.
