### ISSUE TITLE
FindIntegrationAnchors with SCTransformed scRNA-seq data

### ISSUE THREAD

**Issue by ymuto802** [timoast/signac#92]
Hi,
Recently many people use SCTransform to preprocess scRNA-seq data. When we want to use SCTransformed scRNA-seq data for label-transfer, should we use the assay "SCT" instead of "RNA"? When we want to use SCTransformed pbmc_rna as a reference data:

transfer.anchors <- FindTransferAnchors(
  reference = pbmc_rna,
  query = pbmc,
  reference.assay = 'SCT',
  query.assay = 'RNA',
  reduction = 'cca'
)

Is it OK??

Thanks!
Yoshi

**Comment by timoast** [comment]
Hi Yoshi, in theory this could work for transfer (SCT normalized reference, log-normalized query), but it would require rewriting part of the `FindTransferAnchors` function in Seurat and is not currently supported. For now we can only recommend using log normalization when transferring data between RNA and ATAC, we will try to add support for this in the future.

**Comment by ymuto802** [comment]
Thanks Tim, I really appreciate your response. We want to use assay RNA for label transfer for now while we could also use assay SCT for clustering and cell-type determination in reference data, right?

**Comment by timoast** [comment]
Yes, you can still use SCT for everything else (clustering, annotating cell types, etc), just need to use the log-transformed RNA assay for label transfer

**Comment by ymuto802** [comment]
OK Thanks !
Yoshi
