### ISSUE TITLE
Unable to write gene annotations to Signac object

### ISSUE THREAD

**Issue by prullens** [timoast/signac#922]
Hi,

Thanks for developing Signac!

My data was aligned against the GRCm38 mouse genome (i.e. with 1,2,...,X rather than chr1,chr2,...,chrX). Hence I have set 
```seqlevelsStyle(annotations) <- 'NCBI'```.
However, trying to assign ```annotations``` to the Signac object using ```Annotation(object) <- annotations```,
then takes for ever before I kill it after a while? Strange thing is 
```seqlevelsStyle(annotations) <- 'UCSC'``` followed by ```Annotation(object) <- annotations```, 
just runs quickly without any trouble. But in that way I don't have correct ```seqlevels```.

Best,
Pim

**Comment by prullens** [comment]
After some additional browsing through other issues posted here, I realized I had ignorantly changed the vignettes' ```'hg19'``` to ```'mm10'``` in ```CreateChromatinAssay()``` like:

```
chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'mm10',
  fragments = fragments.tsv.gz
  min.cells = 10,
  min.features = 200
)  
````
while this of course should have been ```GRCm38```.  However, as mentioned above, this mistake didn't throw an error or warning, but rather kept running for ever without result. 

Best,
Pim

**Comment by timoast** [comment]
I wasn't able to reproduce this issue of the function not completing if the wrong genome is given. Unfortunately there isn't an easy way to automatically detect if the wrong genome is given (if there was, we wouldn't need the parameter).
