### ISSUE TITLE
clustering information missed in joint UMAP visualization

### ISSUE THREAD

**Issue by Leonrunning** [timoast/signac#926]
Hi team of Signac,

For joint UMAP visualization (multiome), functions of "FindMultiModalNeighbors" and "RunUMAP" were used. Then, a umap is generated with cells being grouped. While I have successfully generated a UMAP with cells being grouped at the replicate/treatment levels, the clustering information was missed. And this clustering information is not found in my metadata. 

Is there anything I could try to get those information? Some scripts are attached below.

thanks

## # build a joint neighbor graph using both assays
F2 <- FindMultiModalNeighbors(
  object = F2,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:50, 2:40),
  modality.weight.name = "RNA.weight",
  verbose = TRUE
)

# build a joint UMAP visualization
F2 <- RunUMAP(
  object = F2,
  nn.name = "weighted.nn",
  assay = "RNA",
  verbose = TRUE
)

DimPlot(F2, reduction = "umap")

**Comment by timoast** [comment]
In the vignette we used label transfer methods to predict the celltype for each cell in the dataset. If you want to cluster your cells instead, you will need to run the `FindClusters()` function as shown in other vignettes on the Signac and Seurat websites. For example, see https://satijalab.org/seurat/articles/weighted_nearest_neighbor_analysis.html#wnn-analysis-of-10x-multiome-rna-atac-1

**Comment by Leonrunning** [comment]
Okay, got it. Thanks for your prompt reply and happy holidays!
