### ISSUE TITLE
Error with CreateChromatinAssay  ( number of columns)

### ISSUE THREAD

**Issue by vfriver** [timoast/signac#927]
Dear Tim. 
I am analyzing data from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5465537 but when I ran:
 chrom_assay <- CreateChromatinAssay(
 I got an Error in the number of columns of the fragments file. 
In that case, which is the one that should change or modify the number of columns (.gz or. tbi)

Thanks,

**Comment by timoast** [comment]
The fragment file appears to be the correct format. What is the full code you're running that gives this error?

**Comment by vfriver** [comment]
library(Signac) 
library(Seurat)
library(GenomeInfoDb)
library(EnsDb.Mmusculus.v79) 
library(ggplot2)
library(patchwork)
set.seed(1234)

counts <- Read10X_h5(filename = "Adip_filtered_peak_bc_matrix.h5")
metadata <- read.csv(file = "Adip_singlecell.csv",  header = TRUE,  row.names = 1)
chrom_assay <- CreateChromatinAssay(counts = counts, sep = c(":", "-"), genome = 'mm10',  fragments =   'Adip_fragments.tsv.gz', min.cells = 10,  min.features = 200 )

An alternative, I ran with validate.fragments=FALSE,  but there is not change in the result

**Comment by timoast** [comment]
Works fine for me using the latest Signac release and the files on GEO. I'd suggest re-downloading the files, and make sure you don't modify them in any way.

**Comment by QiWangUTAS** [comment]
> Just flagging here that the latest version of cellranger ATAC (and ARC) includes strand as a 6th column in the fragment files which causes the same error to come up in earlier versions of Signac, you have to remove that last column from the frag file, and reindex for it to work.

Thank you! this really help me out : )
