### ISSUE TITLE
Spearman in LinkPeaks

### ISSUE THREAD

**Issue by lebf3** [timoast/signac#932]
Hi Tim,
I have a few observations on the LinkPeaks() function. I apologize if I missed pieces of code or information that make these point incorrect. 

1.	Within the LinkPeaks function, there seems to be no implementation of the Spearman correlation test. Correlation tests are done with corSparse() which only allows Pearson correlation according to qlcMatrix doc.
https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/links.R#L366  

2.	The selection of peaks by min number of cells is done on "count" (the output of `rowSums(peak)`) which represent the total number of fragments, not the number of cells with non-zero expression. I realize that for low numbers like 10 cells these are likely the same, but if someone was to test higher min number of cells, they will eventually diverge. 
https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/links.R#L283
https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/links.R#L285 

3.	The slot used for ATAC data is the count slot. Could you comment on this choice? The data slot is generally used in most statistical tests by Seurat. Adding the option to choose the slot in the function could be useful.  

Thanks for the support and great package,
Francis

**Comment by timoast** [comment]
> Within the LinkPeaks function, there seems to be no implementation of the Spearman correlation test. Correlation tests are done with corSparse() which only allows Pearson correlation according to qlcMatrix doc.

You're right, I think we used to use `cor()` and support other correlation methods, but this was dropped at some point in favour of much faster `corSparse()` and the documentation wasn't updated. I've fixed this now on the develop branch.

> The selection of peaks by min number of cells is done on "count" (the output of rowSums(peak)) which represent the total number of fragments, not the number of cells with non-zero expression. I realize that for low numbers like 10 cells these are likely the same, but if someone was to test higher min number of cells, they will eventually diverge.

Right, we should fix this in the future

> The slot used for ATAC data is the count slot. Could you comment on this choice? The data slot is generally used in most statistical tests by Seurat. Adding the option to choose the slot in the function could be useful.

We could consider adding this

**Comment by timoast** [comment]
Hi @lebf3, these issues should now be fixed on the develop branch
