### ISSUE TITLE
CreateChromatinAssay Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]): some values in the "start" column cannot be turned into numeric values

### ISSUE THREAD

**Issue by jessicafehlhaber** [timoast/signac#937]
Hey,
I am trying to create a Chromatin Assay, but I receive the following error:

`ATAC_Seu<-CreateChromatinAssay(counts=ATAC_subset_S1D1_T)`

```
Error in .get_data_frame_col_as_numeric(df, granges_cols[["start"]]): some values in the "start" column cannot be turned into numeric values
Traceback:

1. CreateChromatinAssay(counts = ATAC_subset_S1D1_T)
2. StringToGRanges(regions = rownames(x = data.use), sep = sep)
3. makeGRangesFromDataFrame(df = ranges.df, ...)
4. .get_data_frame_col_as_numeric(df, granges_cols[["start"]])
5. stop(wmsg("some values in the ", "\"", names(df)[[col]], "\" ", 
 .     "column cannot be turned into numeric values"))
```

I read out the heads of the object  and observed that the separators that are used c("-","-"), which is the default setting if I remember correctly. 

`head(colnames(ATAC_subset_S1D1_T))`

`'TAGTTGTCACCCTCAC-1-s1d1''CTATGGCCATAACGGG-1-s1d1''CCGCACACAGGTTAAA-1-s1d1''TCATTTGGTAATGGAA-1-s1d1''ACCACATAGGTGTCCA-1-s1d1''TGGATTGGTTTGCGAA-1-s1d1'`

I don't know where this error comes from. I look forward to your reply.

**Comment by timoast** [comment]
Can you show the output of `head(rownames(ATAC_subset_S1D1_T))`?

**Comment by jessicafehlhaber** [comment]
Yes, this is the output I get

`head(rownames(ATAC_subset_S1D1_T))`
`'nCount_peaks''atac_fragments''reads_in_peaks_frac''blacklist_fraction''nucleosome_signal''cell_type'`

**Comment by timoast** [comment]
That looks like the metadata dataframe rather than the counts matrix. I'd double-check that the data you're providing is correct. `CreateChromatinAssay` needs a count matrix with features (eg, peaks or genome bins) in the rows and cells in the columns.

**Comment by jessicafehlhaber** [comment]
I will check that, thank you so much for your feedback.
