### ISSUE TITLE
Unable to add metadata

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#939]
I am analysing 10x multiome data (RNA+ATAC). 

When I try to add the per barcode metrics for a sample, non of the barcode are recognised, could you help?

I am running:
S1 <- CreateSeuratObject(
  counts = countss1$`Gene Expression`,
  assay = "RNA"
)

# create ATAC assay and add it to the object
S1[["ATAC"]] <- CreateChromatinAssay(
  counts = countss1$Peaks,
  sep = c(":", "-"),
  fragments = fragpaths1,
  annotation = annotation
)

S1 <- AddMetaData(S1, per_barcode_metrics)

and ( have checked that some of the barcodes in my assay are found in the cvs):

head(per_barcode_metrics)
# A tibble: 6 x 31
  barcode    gex_barcode   atac_barcode  is_cell excluded_reason gex_raw_reads gex_mapped_reads gex_conf_intergen…
  <chr>      <chr>         <chr>           <dbl>           <dbl>         <dbl>            <dbl>              <dbl>
1 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTGTG…       0               0            10               10                  0
2 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTAAC…       0               2           432              359                 65
3 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTGCG…       0               0             5                4                  0
4 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTCCT…       0               0             1                1                  0
5 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTCAT…       0               0             1                1                  0
6 AAACAGCCA… AAACAGCCAAAC… ACAGCGGGTAGG…       0               0             7                7                  0

**Comment by timoast** [comment]
The metadata needs to have cell names in the rownames of the dataframe. Here you have a tibble, that does not contain rownames. You need to convert to a dataframe (or read using `read.table()` which returns a dataframe rather than a tibble)
