### ISSUE TITLE
Issue integrating two scATAC datasets with not all populations in common

### ISSUE THREAD

**Issue by laurabchopp** [timoast/signac#94]
Hi Tim,

I am trying to use the Integrate function to remove the batch effect from two of my samples, while preserving the biological variability. I know there should be some clusters shared between the two samples, and some clusters not shared.

Initially I followed the code from the scATAC integration Vignette, but this integrated the datasets "too well", meaning all populations were shared. I think this makes sense, since the peaks I used to integrate were derived from the intersect function. In this way, I assume sample specific peaks were dropped, masking biological variability.

To get around this, I used a peakset (Peaks) which is called on both samples (from the cellranger aggr command). It works up until the integrate step, when I get

 **Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing**

I'm not sure what to do at this point. 

Peaks is a list of ~90,000 peaks derived from the merged sample from Cell Ranger aggr
Sample1 and Sample 2 are 10x objects that have been filtered and pre-processed

##Step 1: count reads at regions defined in Peaks###
```
Sample1peaks <- FeatureMatrix(
  fragments = GetFragments(object = Sample1, assay = 'peaks'),
  features = StringToGRanges(Peaks, sep = c(":", "-")),
  sep = c(":", "-"),
  cells = colnames(Sample1),
  verbose= TRUE
)
```

```
Sample1[['MergedPeaks']] <- CreateAssayObject(counts = Sample1peaks, min.cells = 1)
Sample1 <- RunTFIDF(object = Sample1, assay = 'MergedPeaks')

Sample2peaks <- FeatureMatrix(
  fragments = GetFragments(object = Sample2, assay = 'peaks'),
  features = StringToGRanges(Peaks, sep = c(":", "-")),
  sep = c(":", "-"),
  cells = colnames(Sample2),
  verbose= TRUE
)

Sample2[['MergedPeaks']] <- CreateAssayObject(counts = Sample2peaks, min.cells = 1)
Sample2 <- RunTFIDF(object = Sample2, assay = 'MergedPeaks')

anchors <- FindIntegrationAnchors(
  object.list = list(Sample1, Sample2),
  anchor.features = Peaks,
  assay = c('MergedPeaks', 'MergedPeaks'), k.filter = 200)

```
### RETURNS 
Scaling features for provided objects
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02m 20s
Finding all pairwise anchors
  |                                                  | 0 % ~calculating  Running CCA
Merging objects
Finding neighborhoods
Finding anchors
	Found 10132 anchors
Filtering anchors
	Retained 2350 anchors
Extracting within-dataset neighbors
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=04m 29s
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.

######

```
integrated <- IntegrateData(
  anchorset = anchors,
  weight.reduction = "lsi",
  preserve.order = TRUE)
```
RETURNS
**Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
  invalid character indexing**

Apologies if this isn't an easy to understand issue--I'm a beginner with this and with posting on Github. 
-Laura

**Comment by timoast** [comment]
Hi Laura, I think you need to run LSI on each dataset before integration, as you're specifying the `weight.reduction="lsi"` parameter here. I'd also recommend setting `k.filter=NA` for scATAC data, but you can try both ways and see what works for you.

**Comment by laurabchopp** [comment]
Hi Tim, thanks for the response.
I ran TFIDF and SVD on the MergedPeaks assay for each individual object, then re-ran the anchoring and integration.
Unfortunately that didn't work--I still got the same error. 

In the meantime, I found what I think is a work-around. If you get the chance, can you please let me know if this is an inappropriate analysis?

I made a Seurat object from the output of the CellRanger aggr command, including making a meta data column indicating which batch the sample comes from. 
This force renames the cells, appending a -1 or -2 to indicate the batch.
The peakset is derived from peak calling on the combined datasets.
I filtered it following the standard Signac workflow. I also calculated a gene activity matrix for this object prior to putting it through the integration.

```
DefaultAssay(MergedExp1) <- "peaks"
MergedExp1 <- RunTFIDF(MergedExp1)
MergedExp1 <- FindTopFeatures(MergedExp1, min.cutoff = 'q0')
MergedExp1 <- RunSVD(
  object = MergedExp1,
  assay = 'peaks',
  reduction.key = 'LSI_',
  reduction.name = 'lsi'
)

```

###Here I took pieces of code from the scRNAseq integration workflow from Seurat###
```
Exp1.list <- SplitObject(MergedExp1, split.by = "Batch")


for (i in 1:length(Exp1.list)) {
  Exp1.list[[i]] <- RunTFIDF(Exp1.list[[i]], verbose = FALSE)
  Exp1.list[[i]] <- FindTopFeatures(Exp1.list[[i]], min.cutoff = 50)
}

reference.list <- Exp1.list[c("1", "2")]

```

###I used k.filter = 200, since otherwise it keeps all the anchors it finds###
```
exp1.anchors <- FindIntegrationAnchors(object.list = reference.list, assay = c("peaks", "peaks"), anchor.features = Peaks, k.filter=200)

Exp1.integrated <- IntegrateData(anchorset = exp1.anchors, weight.reduction = "lsi")
                        
Exp1.integrated <- RunSVD(
  object = Exp1.integrated,
  n = 30,
  reduction.name = 'integratedLSI'
)

Exp1.integrated <- RunUMAP(
  object = Exp1.integrated,
  dims = 1:30,
  reduction = 'integratedLSI'
)

```

Thank you!

**Comment by yuqiu77** [comment]
Hi Laura,

I ran into similar problem as you.  I think the issue is that when you create the seurat object, although you use the same peak list, some of them may not be presented in your seurat object because there is no count.   So instead of using Peaks as the anchor.features, try to find the common peaks presented in both seurat object first.

**Comment by laurabchopp** [comment]
@yuqiu77 
Thanks for your advice! My concern with only using peaks that are common to both datasets is that it will force integration where no integration should occur. Since many of the uncommon peaks are biologically relevant, only using common peaks will mask this. That's what happened when I tried running the integration with the common peaks--samples I know to contain both common and uncommon populations were integrated perfectly. My work-around preserves the uncommon populations, while integrating the common ones. It's not perfect, but it's certainly an improvement from non-integrated analysis (assuming it's a correct way to use the tools).

**Comment by yuqiu77** [comment]
I didn't test it, but you might be able to set min.cell =0 to keep all peaks in your peak list.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by timoast** [comment]
@laurabchopp that looks fine to me. I think @yuqiu77 might be right that the issue you were having could be due to features with 0 counts being dropped. If the approach above gives good results that make sense then I would just go ahead with that

**Comment by laurabchopp** [comment]
Thank you both so much for the input!

To clarify for anyone with similar issues:

My work-around works when you have populations that are shared and not shared, while trying to correct for batch effect within **one experiment.**

However, I ended up just merging my two independent experiments together (which should have matching populations in each), then followed the scATAC integration vignette with the Harmony function. It removed the batch effect from the two independent experiments, as well as the batch within experiment one. The result looks great, and makes biological sense.
