### ISSUE TITLE
adding mitochondrial genotyping data

### ISSUE THREAD

**Issue by chrismahony** [timoast/signac#940]
I have 13 samples and I have ran mgatk tenx to call variants in each seperat sample.

After I read in the seperate MGATK data using ReadMGATK(), how can I cobine these and add this to my aggregrated seurat object (that contains all 13 samples)?

Thanks
Chris

**Comment by timoast** [comment]
You can combine the mitochondrial count matrices using `cbind()`, just make sure the rows are in the same order and there are no duplicated cell names across the different experiments. Alternatively you can add the mito information to each Seurat object before merging
