### ISSUE TITLE
CreateChromatinAssay

### ISSUE THREAD

**Issue by jessicafehlhaber** [timoast/signac#944]
Hey,
like in issue #937 I am still trying to create a chromatin assay. I checked that I am using now using the count matrix as input. My new row- and colnames are the following

`head(rownames(ATAC_subset_S1D1$X))
head(colnames(ATAC_subset_S1D1$X))`

`'TAGTTGTCACCCTCAC-1-s1d1''CTATGGCCATAACGGG-1-s1d1''CCGCACACAGGTTAAA-1-s1d1''TCATTTGGTAATGGAA-1-s1d1''ACCACATAGGTGTCCA-1-s1d1''TGGATTGGTTTGCGAA-1-s1d1'
'chr1-9776-10668''chr1-180726-181005''chr1-181117-181803''chr1-191133-192055''chr1-267562-268456''chr1-629497-630394'`

But I am still getting the same error when creating the chromatin assay

`ATAC_Seu<-CreateChromatinAssay(counts=ATAC_subset_S1D1$X)`

```
Error in .get_data_frame_col_as_numeric(df, granges_cols[["end"]]): some values in the "end" column cannot be turned into numeric values
Traceback:

1. CreateChromatinAssay(counts = ATAC_subset_S1D1$X)
2. StringToGRanges(regions = rownames(x = data.use), sep = sep)
3. makeGRangesFromDataFrame(df = ranges.df, ...)
4. .get_data_frame_col_as_numeric(df, granges_cols[["end"]])
5. stop(wmsg("some values in the ", "\"", names(df)[[col]], "\" ", 
 .     "column cannot be turned into numeric values"))
```

I would really appreciate your help again.

**Comment by timoast** [comment]
It looks like the matrix is transposed, you should have features in the rows and cells in the columns
