### ISSUE TITLE
FragmentHistogram  Error: Faceting variables must have at least one value

### ISSUE THREAD

**Issue by tingxie2020** [timoast/signac#948]
I also encountered the same issue:
FragmentHistogram(object = object, group.by = 'nucleosome_group')
Error: Faceting variables must have at least one value
Could you please let me know the code for increasing the chromosome size with one hundred million?

table(object$nucleosome_group)

NS < 4 NS > 4
3058 2

_Originally posted by @tingxie2020 in https://github.com/timoast/signac/issues/199#issuecomment-1021588869_

**Comment by timoast** [comment]
Hi @tingxie2020 

You can change the region used to create the plot by setting the `region` parameter, see the documentation [here](https://satijalab.org/signac/reference/fragmenthistogram)

**Comment by wong-nw** [comment]
@timoast The documentation goes to a 404 link

**Comment by timoast** [comment]
@wong-nw I have now updated the link
