### ISSUE TITLE
MACS CallPeaks default settings ok for mouse?

### ISSUE THREAD

**Issue by chromatinitis** [timoast/signac#950]
Hi,
In CallPeaks, the effective.genome.size parameter default value, 2.7e+09, is for the human genome. Unfortunately, I didn't notice this until I lost access to the computational cluster, so I'm no longer able to rerun my data with a parameter value that is appropriate to mouse, like 2.3e+09. What impact do you think this has on the quality of my called peaks, especially the smaller, less statistically significant ones?
Thanks!

**Comment by timoast** [comment]
I'm not sure how much this affects the results, I'd suggest asking the MACS2 developers here: https://github.com/macs3-project/MACS

**Comment by chromatinitis** [comment]
Sounds good. Based on what I see at their site, anyone with an interest in this question might check out https://github.com/macs3-project/MACS/issues/116
