### ISSUE TITLE
Link of scRNA-Seq data expire in mouse brain tutorial

### ISSUE THREAD

**Issue by PeterZZQ** [timoast/signac#952]
Hi, 

I wish to reproduce the integration result of scRNA-Seq and scATAC-Seq in the Signac tutorial (https://satijalab.org/signac/articles/mouse_brain_vignette.html), but I find that the data link of scRNA-Seq is expired now (both raw and processed data). May I have the updated link of the scRNA-Seq data?

Thanks!

**Comment by timoast** [comment]
I've updated the link on the vignette, and it'll be updated online next time we re-build the website. 

The updated link is here: https://signac-objects.s3.amazonaws.com/allen_brain.rds

**Comment by darlene003** [comment]
Thank you so much!!

**Comment by tanasa** [comment]
I am also trying to access the brain data that is deposited on a S3 bucket, 

the message that I do get is 
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F3QRCBB1JC7F3F7F</RequestId>
<HostId>S/74WtzwjswdTro5Lc13GflvB89SbkxSONarOSKbJy4npRq/07lAVh5zNgDrAEnatEQkR0SI0oY=</HostId>
</Error>
```

**Comment by timoast** [comment]
@tanasa should be fixed now
