### ISSUE TITLE
add the gene activity matrix 

### ISSUE THREAD

**Issue by tingxie2020** [timoast/signac#954]
I integrated three ScATAC-seq objects, did the LSI embeddings, then created a new UMAP using the integrated embeddings, then create a gene activity matrix.
I followed the vignette: 
https://satijalab.org/signac/articles/integrate_atac.html
https://satijalab.org/signac/articles/pbmc_vignette.html
 # add the gene activity matrix to the Seurat object as a new assay and normalize it
at this step it shows the error 
> integrated[['RNA']] <- CreateAssayObject(counts = gene.activities)
Error: Cannot add a different number of cells than already present

Could you please help?
Thanks

**Comment by timoast** [comment]
My guess is there are cells with 0 total counts in the gene activity matrix, which get removed when you create the assay. Set `min.features=-1` in `CreateAssayObject()` to avoid this
