### ISSUE TITLE
Using LinkPeaks score to determine how well a gene's expression is explained by totality of all linked peaks

### ISSUE THREAD

**Issue by chromatinitis** [timoast/signac#956]
Hi @timoast,

I am interested in using the output of linkPeaks to determine whether variability in the expression of a given gene is well explained by the totality of the variability in all (MACS) peaks linked to the gene by LinkPeaks. That is, for gene X, I'd like to be able to calculate that xx % of it cross-cell variability in expression is explained by the "aggregate" cross-cell variability of all peaks linked to the gene.  Naively, I want to calculate the total variation explained as sum(score_i ** 2) across all linked peaks, where score_i is the correlation score output by LinkPeaks for peak i and gene X. But it's not clear to me this calculation is justified in light of LinkPeak's independent determination of score for each gene-peak pair. I'd be grateful if you could shed some light and/or provide a suggestion on how to achieve my objective if it's possible.

Thanks for the great package and equally great support.

**Comment by timoast** [comment]
The score is the Pearson correlation coefficient between gene expression and peak accessibility. It's possible that you could have any number peaks with a perfect correlation with the gene, in which case you would "explain" >100% of the variance using this type of approach.

Maybe something like reconstruction error would be a better metric for what you're trying to do.

**Comment by chromatinitis** [comment]
I see - the issue of co-variance amongst two or more peaks. I'll look into using reconstruction error.

Thanks!
