### ISSUE TITLE
Gene activity matrix without fragment files

### ISSUE THREAD

**Issue by PeterZZQ** [timoast/signac#957]
Hi, I'm using the`GeneActivity` function in `Signac`, and I only have the count matrix and region names (of the form `chrX:start-end`) but no fragment files. When I run `GeneActivity` function, it shows me the error:
```
Error in GeneActivity(seurat.atac, assay = "peaks", features = VariableFeatures(seurat.rna)) : 
  No fragment information found for requested assay
```
May I know if there is any way to run the GeneActivity without using the fragment file? In Seurat v3 only the count matrix and region names are needed when running `CreateGeneActivityMatrix`.  Thanks!

**Comment by timoast** [comment]
There's no way to create a gene activity matrix in Signac without a fragment file. If you want to use the old function from Seurat you will need to install Seurat v3: https://satijalab.org/seurat/articles/install.html#install-previous-versions-of-seurat-1

**Comment by PeterZZQ** [comment]
Hi, 

Is it OK if I directly transfer the count matrix back to the fragment file format? Will that make a huge difference compared to directly counting the fragments that have overlaps with the gene body?

**Comment by timoast** [comment]
Depends on the peak calling, if there were no peaks called near a certain gene then you're going to end up with zero counts for that gene. Using the fragment file removes the dependence on good peak calling

**Comment by alekseybelikov** [comment]
Many public datasets dont have fragment files. Please bring back the old CreateGeneActivityMatrix function!
