### ISSUE TITLE
Does GeneActivity() count individual cutsites?

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#965]
How are fragments counted in regions for FeatureMatrix() and GeneActivity() calculations?
Does GeneActivity count the number of fragments or the number of cut sites within a given region?

Counting fragments would be problematic, see below: 

hypothetical example 1:
gene is located on chr1: 100-200, and a fragment occurs at chr1: 50-250.  This should not be counted, because Tn5 access the flanking regions, not the region itself, even though they overlap.

hypothetical example 2:
gene is located on chr1: 100-200, and a fragment occurs at chr1: 110-150.  This should be counted twice, because Tn5 accesses the gene region twice, to make two cuts.  

I guess what I am saying is that I believe the Tn5 cut sites should be counted, rather than fragments.  Hard to find info online

**Comment by timoast** [comment]
It counts fragments, not cut sites. I agree that the it's possible that the internal sequence of long fragments may not actually be accessible, but in practice I don't think this has much impact at all.
