### ISSUE TITLE
`GetCellsInRegion` function has inconsistent behaviors in some rare scenarios.

### ISSUE THREAD

**Issue by zidong93** [timoast/signac#966]
I recently encountered an issue (Signac_1.5.0) that's probably related to [this issue](https://github.com/timoast/signac/discussions/626#discussioncomment-750532).

When I run `FeatureMatrix` on a `GRanges` object of length 3, I got this error message:
`Error in rep(x = seq_along(along.with = all.features), nrep) :  invalid 'times' argument`

I think the problem arises from the [`GetCellsInRegion`](https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/utilities.R#L647) function. If I understand correctly `GetCellsInRegion` should return a list of the same length of `region`, where each element is a vector of cell names that has fragment in that region. But occasionally it returns a matrix, which then causes problem for this line in [`PartialMatrix`](https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/utilities.R#L2106) 
```r
    nrep <- elementNROWS(x = cells.in.regions)
```
`nrep` can't get the correct value when cells.in.regions is not a list and it then causes error in `rep(x = seq_along(along.with = all.features), nrep)`

I think the reason is the use of `sapply` in [`GetCellsInRegion`](https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/utilities.R#L647) 
```r
if (!is.null(x = cells)) {
    reads <- sapply(X = reads, FUN = function(x) {
      x <- x[fmatch(x = x, table = cells, nomatch = 0L) > 0L]
      if (length(x = x) == 0) {
        return(NULL)
      } else {
        return(x)
      }
    })
  }
```
In my case, the 3 regions have the same number of cells, which causes `sapply` to simplify the return value to a matrix of (cellNumber x 3). So in most cases it won't cause problems. For example if I'm running on a large number of regions it's not likely that all regions have the same number of cells, and `sapply` will keep it as a list. But it does seem to cause problems in rare scenarios.

Also, if `sapply` is changed to something like `lapply` in `GetCellsInRegion`, then [these lines](https://github.com/timoast/signac/blob/63d61bed2d6f43c7fd483b77eef0c84aa70952c9/R/utilities.R#L2103) in `PartialMatrix` also need to be taken care of:
```r
if (length(x = regions) == 1) {
    nrep <- length(x = cells.in.regions)
  } 
```
Since when `length(regions) == 1`, `cells.in.regions` will still be a list of length 1 instead of the actual number of cells.

**Comment by timoast** [comment]
Hi @zidong93, thanks for the detailed bug report. This should now be fixed on the develop branch, let me know if this solves your error

**Comment by zidong93** [comment]
Yes this solves the error. Thanks!
