### ISSUE TITLE
Monocle 3 with multimodal data

### ISSUE THREAD

**Issue by wht10** [timoast/signac#980]
Hey @timoast,

Thank you for being so active and supportive with maintaining and helping Signac!

I am trying to complete the [Monocle3 vignette](https://satijalab.org/signac/articles/monocle.html), but with multimodal data. 

The seurat object seems to have been successfully converted to a cds object, but I think having multiple UMAP embeddings is causing some issues. 

Here is what the `$reducedDims` slot looks like in the cds object. 
![image](https://user-images.githubusercontent.com/53011983/154528182-62956f63-0f17-4435-a770-78eb834fe507.png)

Here are the errors that are output in the `cluster_cells` step.

```
> cds <- cluster_cells(cds, reduction_method = "UMAP")
Error: No dimensionality reduction for UMAP calculated. Please run reduce_dimension with reduction_method = UMAP before running cluster_cells
```

Trying to call a specific embedding, doesn't seem to work either. 

```
> cds <- cluster_cells(cds, reduction_method = "WNN.UMAP")
Error in match.arg(reduction_method) : 
  'arg' should be one of “UMAP”, “tSNE”, “PCA”, “LSI”, “Aligned”
```

Any help would be greatly appreciated!

**Comment by timoast** [comment]
I think this is a limitation of monocle3, they require the umap reduction to be called "UMAP"

A workaround is to copy the umap reduction you want to use into a new dimension reduction before converting the Seurat object, eg:


```r
obj[["UMAP"]] <- obj[["WNN.UMAP"]]
```

**Comment by wht10** [comment]
This worked! Thank you @timoast !
