### ISSUE TITLE
Correlation between total counts and LSI components

### ISSUE THREAD

**Issue by markgene** [timoast/signac#987]
Hi there, 

Thanks for your work on signac! I see a strong correlation between depth and the 5th LSI components. Do I need to drop the 5th component in addition to the 1st component for downstream analysis, or drop all the components from 1st to 5th?

<img width="696" alt="Screen Shot 2022-02-19 at 2 02 56 PM" src="https://user-images.githubusercontent.com/4841724/154817301-69f12f1c-8cd8-4c45-b8a2-941b59821a4c.png">

**Comment by timoast** [comment]
I would keep it. You can try removing it and see how the results change, I certainly wouldn't remove all dimensions 1 to 5
