### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) :    duplicate 'row.names' are not allowed In addition: Warning messages: 1: In CreateChromatinAssay(counts = mix_atac, sep = c(":", "-"), min.cells = 10) :   Overlapping ranges supplied. Ranges should be non-overlapping. 2: non-unique values when setting 'row.names': 'chr17-39844000-39845000', 'chr17-39845000-39846000', 'chrM-0-1000', 'chrM-1000-2000', 'chrM-10000-11000', 'chrM-11000-12000', 'chrM-12000-13000', 'chrM-14000-15000', 'chrM-15000-16000', 'chrM-2000-3000', 'chrM-3000-4000', 'chrM-4000-5000' 

### ISSUE THREAD

**Issue by ortholog** [timoast/signac#988]
Hi

When I want to create a ChromatinAssay from a TSV file,I get this error:

```
mix_atac<-read.table('atac_dc.tsv',sep='\t')
chrom_assay <- CreateChromatinAssay(
  counts = mix_atac,
  sep = c(":", "-"),
  genome = 'hg19',
  min.cells = 10
)

Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning messages:
1: In CreateChromatinAssay(counts = mix_atac, sep = c(":", "-"), min.cells = 10) :
  Overlapping ranges supplied. Ranges should be non-overlapping.
2: non-unique values when setting 'row.names': 'chr17-39844000-39845000', 'chr17-39845000-39846000', 'chrM-0-1000', 'chrM-1000-2000', 'chrM-10000-11000', 'chrM-11000-12000', 'chrM-12000-13000', 'chrM-14000-15000', 'chrM-15000-16000', 'chrM-2000-3000', 'chrM-3000-4000', 'chrM-4000-5000' 
```
and I check rownames of this TSV file,by
`length( unique(rownames(mix_atac)))`
The result displays that the rownames of this file are not duplicated,Could you tell me the cause of this error and how to improve to the error message ?Thank you

**Comment by timoast** [comment]
Are you sure `mix_atac` is a matrix that contains rownames? Can you show the output of `head(rownames(mix_atac))`?

**Comment by ortholog** [comment]
> 

I found that the problem was that the matrix had both 'chr17-39844000-39845000' and
'chr17-39844000-39845000.1'。Could you please tell me how to deal with this problem？Get rid of one or keep them all or some other solution？

**Comment by timoast** [comment]
I think it makes sense to remove the duplicated peaks, since the counts should be identical (same region quantified for the same cells). However, I'd also recommend reviewing the steps used to create the count matrix as it's a bit unexpected to have duplicated peaks and this could indicate a mistake somewhere along the pipeline.

**Comment by ortholog** [comment]
Thank you for your reply
