### ISSUE TITLE
Issue merging scATAC samples

### ISSUE THREAD

**Issue by Nafarroa1512** [timoast/signac#99]
Hello all,

I have issues merging different scATAC samples. We have 4 samples (2D-R, 2D-L, 2W-R and 2W-L) that we want to analyze. 

First, I have tried with the aggregated file that we obtained from Cell ranger, but the Singlecell.csv file for the aggregated data is not generated in the aggregation process. Therefore, I cannot continue.

Therefore, as a second alternative, I have tried to do it sample by sample. For that, I have followed Seurat and Signac instructions and also other recommendations. At first, I've thought that it's worked, but I was checking the object, I've seen that it hasn't. 
The merging part is not done properly. I can just see 2D-R and 2D-L, but not the others. How can I solve this problem?  Can somebody help me?

I would greatly appreciate any help. Thank you very much in advance.

This is my script:

#Read H5 files for 2D-R
dr <- Read10X_h5("/Users/andue/Desktop/scATACseq_h5_files/2D-R.h5")
dl <- Read10X_h5("/Users/andue/Desktop/scATACseq_h5_files/2D-L.h5")
wr <- Read10X_h5("/Users/andue/Desktop/scATACseq_h5_files/2W-R.h5")
wl <- Read10X_h5("/Users/andue/Desktop/scATACseq_h5_files/2W-L.h5")

#Read METADATA
metadata_2DR <- read.csv(file = "/Users/andue/Desktop/scATACseq_h5_files/singlecell_2DR.csv", header = TRUE, row.names = 1)
metadata_2DL <- read.csv(file = "/Users/andue/Desktop/scATACseq_h5_files/singlecell_2DL.csv", header = TRUE, row.names = 1)
metadata_2WR <- read.csv(file = "/Users/andue/Desktop/scATACseq_h5_files/singlecell_2WR.csv", header = TRUE, row.names = 1)
metadata_2WL <- read.csv(file = "/Users/andue/Desktop/scATACseq_h5_files/singlecell_2WL.csv", header = TRUE, row.names = 1)

#Creat an object for each sample
dr.obj <- CreateSeuratObject(counts = dr, assay = 'peaks', project = '2D-R', min.cells = 1, meta.data = metadata_2DR) 
dl.obj <- CreateSeuratObject(counts = dl, assay = 'peaks', project = '2D-L', min.cells = 1, meta.data = metadata_2DL) 
wr.obj <- CreateSeuratObject(counts = wr, assay = 'peaks', project = '2W-R', min.cells = 1, meta.data = metadata_2WR) 
wl.obj <- CreateSeuratObject(counts = wl, assay = 'peaks', project = '2W-L', min.cells = 1, meta.data = metadata_2WL) 

#Creat fragments to each Seurat/Signac object
fragment.path_dr <- 'Z:/jo-lab/Julian Perez/SnapATAC/Cell Ranger/2D-R/outs/fragments.tsv.gz'
fragment.path_dl <- 'Z:/jo-lab/Julian Perez/SnapATAC/Cell Ranger/2D-L/outs/fragments.tsv.gz'
fragment.path_wr <- 'Z:/jo-lab/Julian Perez/SnapATAC/Cell Ranger/2W-R/outs/fragments.tsv.gz'
fragment.path_wl <- 'Z:/jo-lab/Julian Perez/SnapATAC/Cell Ranger/2W-L/outs/fragments.tsv.gz'

#Add fragments to each
dr.obj <- SetFragments(object = dr.obj, file = fragment.path_dr)
dl.obj <- SetFragments(object = dl.obj, file = fragment.path_dl)
wr.obj <- SetFragments(object = dr.obj, file = fragment.path_wr)
wl.obj <- SetFragments(object = dl.obj, file = fragment.path_wl)

#Combine all the objects
pbmc <- merge(dr.obj, y = c(dl.obj, wr.obj, wl.obj), add.cell.ids = c("2D-R", "2D-L", "2W-R", "2W-L"), project = "scATACseq")
pbmc
head(colnames(pbmc))
tail(colnames(pbmc))
unique(sapply(X = strsplit(colnames(pbmc), split = "_"), FUN = "[", 1))
table(pbmc$orig.ident)

**Comment by Nafarroa1512** [comment]
Just to clarify, with 2 samples the merging works fine, but with 4 it doesn't work.

**Comment by timoast** [comment]
Please see https://github.com/timoast/signac/issues/89
