### ISSUE TITLE
Can not be integrated in two sample to remove the batch

### ISSUE THREAD

**Issue by honghh2018** [timoast/signac#998]
Hi @timoast ,
    I am running the workflow in your merge object vignette, but it can not be remove the batch like below picture,
![image](https://user-images.githubusercontent.com/41668708/155880923-09a194cd-2194-4af6-9883-33d3e394de9c.png)

the code lying below:
At1 <- read.table(
  file = "fragment_matrix/AT1/peaks.bed",
  col.names = c("chr", "start", "end")
)
At2 <- read.table(
  file = "fragment_matrix/AT2/peaks.bed",
  col.names = c("chr", "start", "end")
)

gr.at1 <- makeGRangesFromDataFrame(At1)
gr.at2 <- makeGRangesFromDataFrame(At2)

combined.peaks <- reduce(x = c(gr.at1, gr.at2))

peakwidths <- width(combined.peaks)
combined.peaks <- combined.peaks[peakwidths  < 10000 & peakwidths > 20]
combined.peaks
# load meta
md.at1 <- read.table(
  file = "fragment_matrix/AT1/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

md.at2 <- read.table(
  file = "fragment_matrix/AT2/singlecell.csv",
  stringsAsFactors = FALSE,
  sep = ",",
  header = TRUE,
  row.names = 1
)[-1, ]

# perform an initial filtering of low count cells
md.at1 <- md.at1[md.at1$passed_filters > 500, ]
md.at2 <- md.at2[md.at2$passed_filters > 500, ]

# create fragment objects
frags.at1 <- CreateFragmentObject(
  path = "fragment_matrix/AT1/fragments.tsv.gz",
  cells = rownames(md.at1)
)

frags.at2 <- CreateFragmentObject(
  path = "fragment_matrix/AT2/fragments.tsv.gz",
  cells = rownames(md.at2)
)

at1.counts <- FeatureMatrix(
  fragments = frags.at1,
  features = combined.peaks,
  cells = rownames(md.at1)
)

at2.counts <- FeatureMatrix(
  fragments = frags.at2,
  features = combined.peaks,
  cells = rownames(md.at2)
)

at1_assay <- CreateChromatinAssay(at1.counts, fragments = frags.at1)
at1 <- CreateSeuratObject(at1_assay, assay = "ATAC", meta.data=md.at1)

at2_assay <- CreateChromatinAssay(at2.counts, fragments = frags.at2)
at2 <- CreateSeuratObject(at2_assay, assay = "ATAC", meta.data=md.at2)

# merge
# add information to identify dataset of origin
at1$dataset <- 'AT1'
at2$dataset <- 'AT2'

# merge all datasets, adding a cell ID to make sure cell names are unique
combined <- merge(
  x = at1,
  y = at2,
  add.cell.ids = c("AT1", "AT2")
)
combined[["ATAC"]]

################ 

combined <- RunTFIDF(combined)
combined <- FindTopFeatures(combined, min.cutoff = 20)
combined <- RunSVD(combined)
combined <- RunUMAP(combined, dims = 2:50, reduction = 'lsi')

DimPlot(combined, group.by = 'dataset', pt.size = 0.1)

> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.2                         
year           2020                        
month          06                          
day            22                          
svn rev        78730                       
language       R                           
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again     
# Human species

       

Any advices for this issue to fix it?
Best
hanhuihong

**Comment by honghh2018** [comment]
Had anyone hear this?

**Comment by honghh2018** [comment]
It would showing this message: [W::hts_idx_load2] The index file is older than the data file: /fragment_matrix/AT2/fragments.tsv.gz.tbi

**Comment by timoast** [comment]
If there are significant batch effects between samples that cannot be removed by simply using the same peak set across datasets, you can follow the data integration vignette: https://satijalab.org/signac/articles/integrate_atac.html

**Comment by honghh2018** [comment]
The another question occurred, when running the anchor to integrate the data.
however, i was running the example data in your vignette, it can work well. 

Warning: No filtering performed if passing to data rather than counts
Projecting new data onto SVD
Projecting new data onto SVD
Finding neighborhoods
Finding anchors
	Found 236 anchors
Warning message:
In CheckDuplicateCellNames(object.list = object.list) :
  Some cell names are duplicated across objects provided. Renaming to enforce unique cell names.
error: The cell names in the reduction provided don't match the cell names present in the objects used to build the AnchorSet
stop execute

The code lying below:

fragpath <- 'AT1_fragments.tsv.gz' # AT1
fragcounts <- CountFragments(fragments = fragpath)
print(args[1])
atac.cells <- fragcounts[fragcounts$frequency_count > 1000, "CB"]
# create the fragment object
atac.frags <- CreateFragmentObject(path = fragpath, cells = atac.cells)
#######################
# quantify multiome peaks in the scATAC-seq dataset
# pre-process


counts <- Read10X_h5(filename = 'AT2.h5') #AT2

chrom_assay <- CreateChromatinAssay(
  counts = counts,
  sep = c(":", "-"),
  genome = 'hg19',
  fragments = 'AT2_fragments.tsv.gz',
  min.cells = 10,
  min.features = 200
)

pbmc <- CreateSeuratObject(
  counts = chrom_assay,
  assay = "peaks"
)
pbmc.multi<-pbmc

pbmc.multi <- RunTFIDF(pbmc.multi)
pbmc.multi <- FindTopFeatures(pbmc.multi, min.cutoff = 'q0')
pbmc.multi <- RunSVD(pbmc.multi)
counts <- FeatureMatrix(
  fragments = atac.frags,
  features = granges(pbmc.multi),
  cells = atac.cells
)

# create object
atac.assay <- CreateChromatinAssay(
  counts = counts,
  min.features = 500,
  fragments = atac.frags
)

pbmc.atac <- CreateSeuratObject(counts = atac.assay, assay = "peaks")
pbmc.atac <- subset(pbmc.atac, nCount_peaks > 500 & nCount_peaks < 30000)

# compute LSI
pbmc.atac <- FindTopFeatures(pbmc.atac, min.cutoff = 10)
pbmc.atac <- RunTFIDF(pbmc.atac)
pbmc.atac <- RunSVD(pbmc.atac)


# first add dataset-identifying metadata
pbmc.atac$dataset <- "AT1"
pbmc.multi$dataset <- "AT2"

# merge
pbmc.combined <- merge(pbmc.atac, pbmc.multi)

# process the combined dataset
pbmc.combined <- FindTopFeatures(pbmc.combined, min.cutoff = 10)
pbmc.combined <- RunTFIDF(pbmc.combined)
pbmc.combined <- RunSVD(pbmc.combined)
pbmc.combined <- RunUMAP(pbmc.combined, reduction = "lsi", dims = 2:30)

# find integration anchors 
integration.anchors <- FindIntegrationAnchors(
  object.list = list(pbmc.multi, pbmc.atac),
  anchor.features = rownames(pbmc.multi),
  reduction = "rlsi",
  dims = 2:30
)

# integrate LSI embeddings  
integrated <- IntegrateEmbeddings(
  anchorset = integration.anchors,
  reductions = pbmc.combined[["lsi"]],
  new.reduction.name = "integrated_lsi",
  dims.to.integrate = 1:30
)

# create a new UMAP using the integrated embeddings
integrated <- RunUMAP(integrated, reduction = "integrated_lsi", dims = 2:30)
p1 <- DimPlot(integrated, group.by = "dataset")
ggsave(p1,filename = "umap.png",width = 12,height = 10)


Had any idea for this issue?
Best
Hanhuihong

**Comment by honghh2018** [comment]
Had any idea for this issue?
